### ISSUE TITLE
[jorg] Who's Using Joomla Logos

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#10]
Review the logos and their usage & change them to be responsive. They're tiny at the moment due to incorrect classes resizing the images down. This is on the home page of the website.

![whos using joomla logos](http://s22.postimg.org/mbmny0vg1/IMG_0860.jpg)

**Comment by MAT978** [comment]
Closing as it should be solved on [jrepo] - Thanks
Thank you to reopen if needed
+ see #77
