### ISSUE TITLE
joomla-cms/releases - Deceptive Site!

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1001]
Hi,

Today, I'm finding that Chrome and Firefox are reporting that the download of a Joomla version from github https://github.com/joomla/joomla-cms/releases is coming from a **Deceptive Site**.

*Deceptive Site!

This web page at github-production-release-asset-2e65be.s3.amazonaws.com has been reported as a deceptive site and has been blocked based on your security preferences.

Deceptive sites are designed to trick you into doing something dangerous, like installing software, or revealing your personal information, like passwords, phone numbers or credit cards.

Entering any information on this web page may result in identity theft or other fraud.*

**Comment by mbabker** [comment]
Contact GitHub.  All we can do is click that same link.

**Comment by zero-24** [comment]
I have just contacted them via the contact form. Lets see what they respond.

**Comment by zero-24** [comment]
This is the response so it is known and they are working on a fix.

```
Hi Tobias,
Thanks for reaching out about this!
We've received several reports of users encountering this warning, and our team is currently working to resolve the situation.
I can't offer an ETA on a fix, but will update you as soon as we have any news to share.
Thanks again!
```

**Comment by zero-24** [comment]
I have just got response that is is working again. For me it does. IMO this can be closed than.

**Comment by anibalsanchez** [comment]
Yes, it works from my side too.
