### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Rafael-Honorato** [joomla/joomla-websites#1003]
Hey! I Think That theres an error on this page(https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts).

on 'Example for a light DatePicker XML field definition' theres two 'type=calendar' and it makes an error.
I Hope help with it. Sorry for my bad english o/.

**Comment by zero-24** [comment]
HI,

thank you for reporting but i can not find the string you mention on that page? you may want to report a different page?

**Comment by hvdmeer** [comment]
I think he means this page: https://docs.joomla.org/Calendar_form_field_type

**Comment by zero-24** [comment]
Please check that page again. I have just fixed that with the last change. Please let me know if you still see errors.

I'm closing here for now reopen if needed.
