### ISSUE TITLE
[jrd] Broken Pages

### ISSUE THREAD

**Issue by samniosaki** [joomla/joomla-websites#1004]
There are pages that fail to load the template.

http://resources.joomla.org/en/component/zoo/category/design-development/3

![mozilla_firefox](https://user-images.githubusercontent.com/30624126/28822846-b90f1c10-766f-11e7-88fd-d8307a4dfada.jpg)

**Comment by genr8r** [comment]
Sorry I forgot to loop back on the issue here. I got this one taken care right after it was posted...

https://resources.joomla.org/en/category/design-development/3

Feel free to re-open if there are any further concerns.
