### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1005]
The OG Tag of the 3.7 Landingpage shows still Do more with Joomla 3.5 

![image](https://user-images.githubusercontent.com/828371/28842841-78f04150-76ff-11e7-8d9a-326175e90a1c.png)

**Comment by Sandra97** [comment]
Can't reproduce.

OG information are the right one.

![2](https://user-images.githubusercontent.com/4682328/28852605-748164a2-76f8-11e7-8b42-07eadfcff0b4.png)
![capture-d ecran-2017-08-01-20 30](https://user-images.githubusercontent.com/4682328/28852606-74820ce0-76f8-11e7-90e9-3b892623decf.png)

**Comment by Sandra97** [comment]
As the OG tag is correct. I'm closing this issue.
Re-open if needed.

**Comment by coolcat-creations** [comment]
Looks like it´s a caching issue in Skype. Thank you!
