### ISSUE TITLE
[jcomm] event sharing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1007]
it would be really useful if there were social sharing links on the events listings

**Comment by Joomv** [comment]
Agreed - added to to do list.

**Comment by brianteeman** [comment]
Thanks - should i close this here?

**Comment by Joomv** [comment]
No leave it open please so it reminds me.  Will close when I've done it.

**Comment by Joomv** [comment]
This is done.  Share this page; feature rolled out across all components replacing other, article only, plugin.

**Comment by brianteeman** [comment]
Thanks but there is something not quite right as the text is wrong- for example

`The Joomla! Events Directory https://community.joomla.org/events/3577-summer-open-source-sprint-london.html via @joomla`

**Comment by Joomv** [comment]
Need to work the meta fields a bit.

**Comment by Joomv** [comment]
Ok this is much better now.
Pulls Event Title,  Date for Description, Event Image.
Scrapes well on Twitter and Facebook.
