### ISSUE TITLE
[jshow] - Links to categories on domain root are NOT put in

### ISSUE THREAD

**Issue by chriswagner0815** [joomla/joomla-websites#1008]
Hi guys,
on the domain root of showcase.joomla.org, all the links to the categories on the bottom are gone. Earlier, one could click on those to see the category.

Please fix this :)
Kind regards
Chris
SEO-Team

**Comment by Sandra97** [comment]
I confirm this issue. The "Browse Categories" elements don't have anymore links and is so totally useless

**Comment by sebastienlapoux** [comment]
Thanks! in progress

**Comment by oliviernolbert** [comment]
Hi, Should now be fixed.

**Comment by Sandra97** [comment]
Yes it's fixed. Thank you!
Closing this issue.
Re-open if needed.
