### ISSUE TITLE
[jshow] Directory-Index visible to outsiders (missing empty index.html?)

### ISSUE THREAD

**Issue by chriswagner0815** [joomla/joomla-websites#1009]
The page: https://showcase.joomla.org/media/sourcecoast/ can be seen as directory listing in the browser.
Maybe it lacks an empty index.html or should be blocked by the server system (Error 403 by default?)

Chris
SEO-Team

**Comment by Sandra97** [comment]
I can confirm.

**Comment by brianteeman** [comment]
Thats a server configuration issue. The blank index.html where only in joomla to cope with bad server configurations. The correct response is to fix it at the server level or failing that to add O`ptions -Indexes`
 to the htaccess file. Note that this is in the default joomla htaccess anyway so this must have been removed :(

**Comment by chriswagner0815** [comment]
Hey Brian,
neither Sandra nor I have access. Hope that someone with access can take care of that! :)

**Comment by jeckodevelopment** [comment]
@Joomv / @mbabker do you have access to it?

**Comment by Joomv** [comment]
Sorted.  Closing.

**Comment by Sandra97** [comment]
Thank you Rowan!!
