### ISSUE TITLE
[general] ideas web site 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#101]
The ideas.joomla.org web site is missing from the list of sites.

The last I heard was that the two people who have the login details are no longer members of the joomla community

**Comment by mbabker** [comment]
Which list?  It's in the mega menu and on the spreadsheet I'm looking at now.

**Comment by mbabker** [comment]
Also, as far as admins on that go, last I remember Mark Dexter and Rouven Weßling were the ones with the keys.

**Comment by brianteeman** [comment]
The list in the readme.md here
