### ISSUE TITLE
[jshow] No Sitemap.xml present, no link in robots.txt to sitemap.xml

### ISSUE THREAD

**Issue by chriswagner0815** [joomla/joomla-websites#1010]
We need to have a sitemap for Google to avoid all the parameter pages getting into the index (have been blocked via Webmaster Tools by me today). 

For this reason, I am attaching a current sitemap.xml file to make Google understand which pages are important to us. 

Please also put in a link to the sitemap in the robots.txt file of the showcase-directory with the following content once you have uploaded it. 

Sitemap: https://showcase.joomla.org/sitemap.xml 

Also in robots.txt there is a typo for the disallowance of a directory named showcase (not there anymore?) which goes like this:
Dia**_a_**llow: /showcase/
The a should be an s. However, since there is no content, the rule can be taken out.

[sitemap.zip](https://github.com/joomla/joomla-websites/files/1215758/sitemap.zip)

Thank you
Chris
SEO-Team

**Comment by sebastienlapoux** [comment]
Hi @chriswagner0815 , 

done https://showcase.joomla.org/sitemap.xml
Sitemap: https://showcase.joomla.org/sitemap.xml added on https://showcase.joomla.org/robots.txt

Quick question: is it really useful to add the sitemap into the robots.txt? Who use it?

I don't see into robots.txt something about /showcase/

Thanks!
