### ISSUE TITLE
[joomla.org] subdomain.jooma.org

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1012]
Regularly I type download.joomla.org instead of downloads and this results in an ugly ERR_NAME_NOT_RESOLVED page

Is it possible to setup a wildcard redirect to www.joomla.org for all non-existent subdomains?

**Comment by zero-24** [comment]
IIRC just subdomains don't cost anything so we can also do
download.joomla.org => downloads.joomla.org for that specific one for others a wildcard would be great sure ;)

**Comment by Radek-Suski** [comment]
As I remember @mbabker was against it 🤔

**Comment by mbabker** [comment]
As long as the aliases are proper redirects and not actually serving the same site under three separate subdomains (I'm staring at you, `(tm|trademark|license).joomla.org`), then let's get it set up.

**Comment by Joomv** [comment]
Was this done?

**Comment by conconnl** [comment]
The TM account holds multiple domains and also multiple aliases (Within CPANEL).
Where TM is configured as the main domain.

We can enable the redirect option within CPANEL, to move every other domain to the correct one. Or do it with htaccess.
Not sure what's the best way, as I don't know how CPANEL reacts with these kind of actions.

If anybody knows, that would be great, else I would need to do tests.

**Comment by jeckodevelopment** [comment]
Grant me cPanel access and i'll setup the aliases

**Comment by conconnl** [comment]
TM fixed.

**Comment by jeckodevelopment** [comment]
Thank you
