### ISSUE TITLE
[jcm] Share to Facebook

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1013]
If you try to share an article to facebook after you have pressed POST then you are redirected to a url `https://www.facebook.com/dialog/return/close#_=_` which I am sure is supposed to do something but it doesnt

**Comment by JacquesR** [comment]
That is the link that FB shows after you share the post, and before FB closes the share window.

The code on the JCM previously did not open the share page in a new window, and that may be why it gets stuck there.

I've updated the JCM share code to also open a new window. (similar to how it's done on the rest of the J sites)

**Comment by brianteeman** [comment]
its working now - thanks for the quick fix
