### ISSUE TITLE
[joomla.org]  - Your Logo has been misused

### ISSUE THREAD

**Issue by dev-yesapps** [joomla/joomla-websites#1015]
On of the Biggest Bank in India "State Bank Of India" has been using Joomla Logo as "Usefull Links" ICON in their Account Dashboard 

![screen shot 2017-08-18 at 11 13 28 am](https://user-images.githubusercontent.com/21323782/29445837-7552e25a-8406-11e7-8cb0-aeb8e62d1eb8.png)

**Comment by zero-24** [comment]
Thanks for your report. I have just forwarded that to the Trandmark Team and got this as ticket ID: [REPORTS-XD7EZ8127K]

When I hear anything for them I come back to you. Thanks for the report.

**Comment by Joomv** [comment]
This is coming from Font Awesome.  Not too sure what we can do about that.

**Comment by dev-yesapps** [comment]
Your wish.. I think even it is "font awesome" icon they have to use it only for mentioning for joomla only.. I am just informing..
Thank you

**Comment by jeckodevelopment** [comment]
Thanks for reporting.
As said by Rowan, we can't do too much in such case.
But we can try to contact them, asking to choose a proper icon for that.

**Comment by Sandra97** [comment]
@jeckodevelopment Can I close this issue?

**Comment by jeckodevelopment** [comment]
we contacted them
