### ISSUE TITLE
[joomla.org] مشکل در کلاس دادن به عنوان و محتوای فیلدهای جوملا 3.7

### ISSUE THREAD

**Issue by mrhossein2017** [joomla/joomla-websites#1017]
وقت بخیر
در جوملا 3.7 در کامپوننت فیلد نمی توان به  field value و field label در فیلدها کلاس اختصاص داد. لازم است در تنظیمات هر فیلد دو قسمت دیگر برای کلاس دادن به label و value  اختصاص داده شود. در حال حاضر تنها امکان اختصاص دادن کلاس به field-entry  وجود دارد.
ضمنا پلاگین درج فیلد در مطلب کلاس اختصاصی و سفارشی شده ی فیلدها را نمی تواند بارگزاری نماید و تنها کلاس های عمومی را نمایش می دهد. باید این پلاگین اصلاح شود تا در صورتی که فیلد دارای کلاس اختصاصی و سفارشی است دیگر کلاس عمومی را بارگزاری نکند.
با تشکر.

**Comment by zero-24** [comment]
Hi @mrhossein2017 ,

this is a tracker for issues with the *.joomla.org network. For support and help with your sites please use our forum you can find at https://forum.joomla.org

For issues with the CMS please fill out [this form](https://github.com/joomla/joomla-cms/issues/new) with all the infos and preferable in english.

As this is not touching the *.joomla.org network i'm going to close this one here. Thanks.
