### ISSUE TITLE
Weakness in style customization of Joomla! Fields 3.7

### ISSUE THREAD

**Issue by mrhossein2017** [joomla/joomla-websites#1018]
Good time
In the Joomla 3.7 custom class is applied to the field-entry and there is no possibility of custom-field-label and field-value for each field separately. This means you can not (for example) label your field blue and red its value. These two parts can not be designed separately

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla Websites like joomla.org.

**Comment by zero-24** [comment]
hi. I guess it is the same request as https://github.com/joomla/joomla-websites/issues/1017 So please use the forum or use the issue tracker of the CMS: https://github.com/joomla/joomla-cms/issues/new
