### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by culverpalmsumc** [joomla/joomla-websites#1019]
Website URL: www.culverpalmsumc.org
Contact: Linda at 310-390-7717 or culverpalmsumc@yahoo.com

This is what It gave me after updating a couple of weeks ago and won't let me update this part anymore.

Warning: Invalid argument supplied for foreach() in /home/content/81/9328481/html/components/com_roksprocket/lib/RokSprocket/Provider.php on line 123

Warning: Invalid argument supplied for foreach() in /home/content/81/9328481/html/components/com_roksprocket/lib/RokSprocket/Provider.php on line 123

Title *  
Show Title 
Hide 
Show 
Hide 
 
Access 
Public 
Public 
Registered 
Special 
 
Position 
 
Select position 
Status  
Shortcode 
[module-139] 
RokSprocket v2.1.21
Options 
Assignments 
Advanced 

Joomla! Provider
Mosaic Layout

PLEASE HELP!

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla Websites like joomla.org.
