### ISSUE TITLE
[jconf] Text is overflowing container

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1021]
When following the link `https://conference.joomla.org/#bottom4` from the last tweet

<img width="930" alt="screenshotr13-03-13" src="https://user-images.githubusercontent.com/1296369/29665595-ab5aa1e2-88cc-11e7-9b66-5133825e9966.png">

**Comment by Joomv** [comment]
Check now please? Might need a hard refresh.  Open again if not fixed.  Thanks

**Comment by brianteeman** [comment]
all good thanks
