### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ClareHF** [joomla/joomla-websites#1023]
My website can't be read and has all the programming details;www.musicfunforeveryone.com.au
I can't access my email clare@musicfunforeveryone.com.au

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by ClareHF** [comment]
Could you please have a look at these two items

**Comment by Sandra97** [comment]
@ClareHF The official [Forum](https://forum.joomla.org/) is the right place to post your issue and get help with your site.

**Comment by ClareHF** [comment]
I have registered for the Forum but it hasn't helped.  How do I post
something and get assistance?
