### ISSUE TITLE
[jcertif] map

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1025]
https://certification.joomla.org/exam/upcoming/list/calendar/date/at,2017.9

is the map supposed to show anything. i expected to see markers for the european events

<img width="972" alt="screenshotr21-55-40" src="https://user-images.githubusercontent.com/1296369/29944939-2b3f93b6-8e97-11e7-857d-392906afb9f9.png">

**Comment by Joomv** [comment]
I need to look at this further the dynamic view is breaking. I've turned it off so all upcoming exams show whilst I look to fixing it so it shows in line with the month.

**Comment by Sandra97** [comment]
@Joomv Any news about that?

**Comment by andreagentil** [comment]
It's fixed.

![image](https://user-images.githubusercontent.com/8660106/38862398-1b707980-4235-11e8-9a02-6f8ad0d3d293.png)

**Comment by Sandra97** [comment]
Thanks. 
I'm closing this issue.
