### ISSUE TITLE
[jdocs] spam

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1026]
I was searching the docs site for "telephone" and i found a lot of spam posts

https://docs.joomla.org/index.php?search=telephone&fulltext=1

**Comment by hvdmeer** [comment]
@hutchy68 is this for you?

**Comment by Hutchy68** [comment]
Yep. All those pages listed are deleted. Google should not be showing them. I'll make some tweaks to cse.

**Comment by Hutchy68** [comment]
So this is going to take some time to figure out why in the heck Google is not obeying...

`<meta name="robots" content="noindex,nofollow">`

Google CSE is completely ignoring that meta tag which is embedded on all the pages shown in the search results.

**Comment by Hutchy68** [comment]
Manually told Google to remove them. CSE is now tied to Search Console in Webmasters Tools only now. Almost 30 removed by this morning, added the last 16, so they should drop out today at some point. I'm just unsure if they will stay out. The pages are returning a 404 in the header besides being `noindex,nofollow` so they should stay gone.

Thanks for the heads up. Closing

**Comment by brianteeman** [comment]
Thanks a lot seems a lot better already
