### ISSUE TITLE
[jdocs] Can we have better documentation for Text Filters in Custom Fields?

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-websites#1027]
The current documentation (https://docs.joomla.org/Help37:Components_Fields_Fields_Edit) doesn't exactly explain much...
> Use from Plugin: Use from the plugin.
    No: Not.
    Raw: Raw.
    Safe html: Safe html.
    Text: Text.
    Alpha Numeric: Alpha Numeric.
    Integer: Integer.
    Float: Float.
    Telephone: Telephone.

Can we have a better documentation on how each of this selections differ from the others?

**Comment by Hutchy68** [comment]
It's a wiki, feel free to improve it. Or if someone else will step up, please do so. 

You left out the key statement above each list, "Filter. Allow the system to save certain html tags or raw data." Filters could be used on different fields too depending on one selected. 

Do a search on docs for "fields filter" to see more details per field type with examples.

**Comment by AndySDH** [comment]
@Hutchy68 I did, but I couldn't find explaination for what those individual options differ from each others. 
`It's a wiki, feel free to improve it. Or if someone else will step up, please do so.`
I would have if I knew. That's why I'm asking :)

**Comment by Sandra97** [comment]
As JDocs is a wiki and anyone can contribute and edit the custom fields tutorial, I'm closing this issue
