### ISSUE TITLE
[help] help.joomla.org/proxy is being Search Indexed

### ISSUE THREAD

**Issue by Hutchy68** [joomla/joomla-websites#1028]
We don't have a Search Console setup (Webmaster Tools) for help.joomla.org? At least that is what Google is stating. [Link to site:help.joomla.org search](https://www.google.com/search?source=hp&q=site%3Ahelp.joomla.org%2Fproxy&oq=site%3Ahelp.joomla.org%2Fproxy&gs_l=psy-ab.3...65718.75386.0.75805.30.27.1.0.0.0.213.2009.24j1j1.26.0....0...1.1.64.psy-ab..3.5.567.0..0j46j0i131k1j0i46k1.J8Ak0u4e2u4)

Someone needs to adjust robots.txt on help.joomla.org and disallow: /proxy as search engines should NOT be indexing admin help screens off of the proxy. We need to fix that right now. 

I can do it, but I don't have access to help.joomla.org. Just DM on Glip.

**Comment by mbabker** [comment]
Send a PR to https://github.com/joomla/help.joomla.org with an appropriate robots.txt file and I'll deploy it.

Also seems https://help.joomla.org/robots.txt exists on the server but not in the repo...

**Comment by Hutchy68** [comment]
So bigger question is robots.txt on server shows a disallow. Why are they indexed?

**Comment by mbabker** [comment]
No idea.  I just claimed Search Console on my account though so I've got that now.

**Comment by Hutchy68** [comment]
Ok, I see why. Disallow: /proxy/ as a folder and not Disallow: /proxy. URL is formed as `/proxy?keyref....`

I'll add robots.txt to repo and push a PR.

**Comment by mbabker** [comment]
The old URI schema was `/proxy/index.php?...`.  So both probably need to be in there to account for massively old site configs that would still use that schema and possibly make Google crawl those URLs.

**Comment by Sandra97** [comment]
Closing this issue too ;)
