### ISSUE TITLE
[jmag] Need code for the header include

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#103]
Hey, I saw the header code for the templates floating around somewhere.

The JCM website was upgraded to Joomla 3, can someone point me to the top header/menu code base so I can pull it in please?

http://magazine.joomla.org/sandbox1/

If anyone wants to check it

**Comment by MAT978** [comment]
@mbabker will be THE one!

**Comment by mbabker** [comment]
@pbwebdev I sent you the packaged template last night and you have access to the https://github.com/joomla/jdotorgtemplate repo which has all the CDN stuff in it.  Is there anything else you need?
