### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by pctechnikch** [joomla/joomla-websites#1032]
When i go to help page, i have this error

RuntimeException 

Error fetching page from MediaWiki API: The page you specified doesn't exist

Your Extension not working. I have only a button "administrator" with a blanc page.

Thanks

I have deinstalled.

**Comment by zero-24** [comment]
Please tell us which page you tryed to access maybe a scrennshot? Also which url did the popup open? Thanks.

**Comment by pctechnikch** [comment]
all forms

pctechnik.ch Herisau
René Grüter
Tobelackerstrasse
9100 Herisau
+41(0)71 351 58 05
+41(0)79 468 58 05
http://pctechnik.ch
________________________________
Von: zero-24 <notifications@github.com>
Gesendet: 12.09.2017 15:03
An: joomla/joomla-websites
Cc: pctechnik.ch Herisau; Author
Betreff: Re: [joomla/joomla-websites] [jhelp] (#1032)


Please tell us which page you tryed to access maybe a scrennshot? Also which url did the popup open? Thanks.

-

**Comment by mbabker** [comment]
From what area?  Is this with a core or third party extension?

All forms unfortunately isn't enough information to troubleshoot an issue.

It is a known issue that when you are on a component's options screen and click the help button, it does not work for third party extensions (we don't have help screens for third parties in our help system and there is still an effort to make that work correctly for those extensions).  Looking at the application's logs, the only 404s I see are either related to third party extensions (i.e. `/proxy/index.php?option=com_help&keyref=Help35:JHELP_COMPONENTS_com_widgetkit_OPTIONS` for Widgetkit) or it looks like some keys may have been incorrectly translated (i.e. `/proxy/index.php?option=com_help&keyref=Help35:Iniciar_Aqui`).

**Comment by infograf768** [comment]
Which language do you use in backend?

**Comment by Sandra97** [comment]
@pctechnikch, please give us more information so that we can help.
Without any answer, I'll close this issue in one week.

**Comment by pctechnikch** [comment]
Many Thanks. This is a long time ago, they can close. Rene
