### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by violavzw** [joomla/joomla-websites#1034]
I have a website under joomla 2.5.11. since this week I'm getting problems.
1) captcha: on a form it wasn't possible to get a captcha code , so the forms were refused. I checked out the  capcha and then it worked again
2) I have a link with google agenda so people could make an online-appointment by clicking on a possibility en fill in the form. they can do all that ( joomla 2)except when they click "verzenden" they get an error message ( joomla 3)
3) when I open my joomla as an administrator and I click on an article I want to open to adapt the only thing that happens is that a "hanglock" appears  before the title but nothing else. I can't open any article ( joomla1)
![joomla1](https://user-images.githubusercontent.com/32013475/30511794-496c6d62-9ad8-11e7-9774-8200b5a99d2c.jpg)
![joomla2](https://user-images.githubusercontent.com/32013475/30511795-4977b7c6-9ad8-11e7-8a29-3e550ff02def.jpg)
![joomla3](https://user-images.githubusercontent.com/32013475/30511796-4a7f4f8a-9ad8-11e7-8210-b1908018c76f.jpg)

**Comment by zero-24** [comment]
@violavzw you are still using the very outdated and not longer supported version 2.5 Please ask for help in our forum: https://forum.joomla.org 

This tracker is for issues with the joomla.org site network.
