### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jasonkhocl** [joomla/joomla-websites#1037]
I will like to report an issue pertaining to inaccurate information with regards to my company's product Martin Modern published on the below url. Please remove this url and its content.

https://martinmodern.joomla.com/

**Comment by franz-wohlkoenig** [comment]
please report this Issue at https://www.joomla.com/.

**Comment by jasonkhocl** [comment]
Hi, How do I do that?  Is it not under joomla websites?

**Comment by franz-wohlkoenig** [comment]
at https://www.joomla.com/ click on "Support".

**Comment by mbabker** [comment]
joomla.com is hosted by SiteGround so you could also contact their support or customer service directly.

**Comment by Sandra97** [comment]
As it's an issue not related to this repository, I'm closing it.
Re-open if needed.
