### ISSUE TITLE
[j3] 

### ISSUE THREAD

**Issue by carcam** [joomla/joomla-websites#1039]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

I think the imaginery of Joomla 3 is wrong:

https://www.joomla.org/3/

Right now you ready "An Eye on Joomla 3.7" while we are in Joomla 3.8. I think it was intended to be: "An Eye on Joomla 4", isn't it?

**Comment by mbabker** [comment]
No, it's intended.  It's continuing to highlight features from 3.7.  Clicking the hexagon on the landing page jumps to the "Spotlight on Joomla! 3.7's main features" section.
