### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by musakhalid** [joomla/joomla-websites#1040]
Please describe the problem or your issue.

I upgraded my Joomla to v3.8.0 after its completed 100% the backend started showing a blank page, but the front is showing normal.

the bankend will only show blank after you might have login.

what might be the issue, kindly assist. https://www.firstbulksmsng.com

Thank you

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like joomla.org. For this Reason please close this Issue, thanks.
