### ISSUE TITLE
[jrd] Please remove JLP category

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#1041]
Hello,
could you please remove the Joomla! Learning Partners category from the Joomla! Resource Directory?

Since not all of our partners are listed there and we're building our JLP Directory on the Certification website, such category is not needed anymore on the JRD.

Thank you for your precious collaboration.

**Comment by genr8r** [comment]
Hi @jeckodevelopment. Do you want to remove or update the sidebar menu item "find a JLP near you" from this page...

https://certification.joomla.org/jlp/joomla-learning-partners

before I unpublish the items?

I don't want to break the link on the certification site.

**Comment by jeckodevelopment** [comment]
Please remove the category, we're removing the link from the website. Thanks for noticing.

**Comment by genr8r** [comment]
Hi @jeckodevelopment I unpublished the JLP listings but there is now a 404 from the link at your site. Please pull the menu item asap as it points to what is now a missing asset at our site. Thanks.

**Comment by jeckodevelopment** [comment]
done, thanks!
