### ISSUE TITLE
[joomla.org] new feature mistake

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1042]
in the list of 3.8 features is this incorrect entry

Featured Articles: Schedule when to start and stop featuring an article #13596

**Comment by Joomv** [comment]
Gone across all languages.
I've display:none'd it until I can speak to Sandra.

**Comment by brianteeman** [comment]
thanks

**Comment by Sandra97** [comment]
Thanks Rowan!
Closing this issue. 
Re-open if needed.

**Comment by brianteeman** [comment]
Can it be removed properly rather than a display none please.

Google will still see the incorrect text

**Comment by Sandra97** [comment]
It will Brian. Just let me take a coffe first

**Comment by brianteeman** [comment]
Thanks

**Comment by Sandra97** [comment]
All removed properly.
