### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by simm12** [joomla/joomla-websites#1043]
After updating to Joomla 3.8.0 my website stoped working and I get this message: This page isn’t working
ipsmlb.org is currently unable to handle this request.
HTTP ERROR 500. I even restored the site from Backup, but still I get the same message. Also the on the backend I get the same message. 
Please Advise how can I solve the problem. Thank You.

**Comment by franz-wohlkoenig** [comment]
Please have a look at https://github.com/joomla/joomla-cms/issues/18020 (and similar Issues) or ask help on the [forums](https://forum.joomla.org/).

This repository concerns Joomla-Websites like joomla.org. For this Reason please close this Issue, thanks.

**Comment by simm12** [comment]
ok
