### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by romeoblaga** [joomla/joomla-websites#1044]
Porque no puedo ver mis articulos y menus creados en joomla 3.7 en localhost.Ayuda por favor

**Comment by romeoblaga** [comment]
Tengo otro problema he instalado joomla 3.7 en ubutnu server 16.4,he configurado el ftp para ver mis archivos y ahora en el navegador chrome no puedo seguir instalando joomla 3.7 me da el error 404 pagina no encontrada, el servidor no se encuentra disponible.Que hago.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,

Thanks
