### ISSUE TITLE
[issues.joomla.org] wrong link to JSST contact form

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-websites#1045]
The link to the JSST contact form in the message area is wrong:
https://issues.joomla.org/tracker/joomla-cms/add

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/jissues/commit/2708825ad0086d5801ea53a0ba3b13ac92c18d76

**Comment by SniperSister** [comment]
Thx!
