### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by Nibir** [joomla/joomla-websites#1048]
On this page https://downloads.joomla.org/cms/joomla25/2-5-28
All links on this page doesn't work!

**Comment by pe7er** [comment]
Are you having problems with all downloads? Could you please test one at https://downloads.joomla.org/cms/joomla3/3-8-0 too?

Are you located in Russia? The downloads are hosted at Amazon AWS which might be blocked by or for your country at the moment.

**Comment by Nibir** [comment]
Sorry for bothering. After a couple minutes i've saw the page about blocking from russian internet provider. I've used tor browser and everything fine now.

**Comment by pe7er** [comment]
No problem. Good to hear that you've found a solution.
