### ISSUE TITLE
[jorg] Home page announcements 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#1049]
This probably has just been forgotten or not archived - seen today 30 November 2017 when 3.8 has been released:
![announcements](https://user-images.githubusercontent.com/736887/31046078-3533a9b0-a5ea-11e7-98ba-dcde89d6d4b7.png)

**Comment by Joomv** [comment]
Good catch!
I've tweaked how this works now.
The module takes a feed from a featured articles item now.
I have unfeatured everything for the 3.8 and 3.7 releases so they don't appear in the feed.
Now when something needs to go from the feed, un-featuring it will remove it from the .org homepage.
Seems the best way of handling this
@Sandra97

**Comment by Hils** [comment]
Thank you @Joomv !
