### ISSUE TITLE
[jshow] Sites to unpublish/remove

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1050]
I've reported these sites but considering the last time I did no action has been taken, I'm opening an issue.

- [Amos and Connors](https://showcase.joomla.org/browse-sites/19662.html): access to the site is denied for security reason
![2](https://user-images.githubusercontent.com/4682328/31054034-c0d7bab4-a677-11e7-8f27-800136ac083f.png)

- [Joomla! Translate](http://joomlatranslate.com/): I have a malware warning when opening the site
![1](https://user-images.githubusercontent.com/4682328/31054043-f854d814-a677-11e7-8d21-3dee6b8df194.jpg)

It would be great if the Showcase team can regularly check some sites or at least, take care of the reports in a correct amount of time.

**Comment by Sandra97** [comment]
Update: No more issues with the Joomla Translate website.

**Comment by Sandra97** [comment]
Update: [Le Kréolia](https://showcase.joomla.org/browse-sites/16998.html) site seems to not exist anymore (I've submitted a report but as usual, I'll probably never get any answer)

**Comment by sebastienlapoux** [comment]
Thanks @Sandra97 .

Has been unpublish:
Amos and Connors https://showcase.joomla.org/browse-sites/19662.html
Le Kréolia https://showcase.joomla.org/browse-sites/16998.html

Thanks.

**Comment by Sandra97** [comment]
Thanks @sebastienlapoux.
Closing this issue.
Re-open if needed.

**Comment by Sandra97** [comment]
I'm re-opening this issue.

I reported one of my websites on October 10. Over one month later, it's still displayed on the Showcase site. 

I still think having an unpublish option would be more efficient. 

Also, I submitted a site on September 24. Still 0 answer. It's not a big issue for me, but if we ask users to submit sites and they have to wait so much time to get an answer, then, we have an issue and people will just stop submitting sites.

**Comment by sebastienlapoux** [comment]
Hi :-) @Sandra97 ,

You submitted 3 websites on September 24, the 3 has been processed on September 25, 2 have been accepted:
![image](https://user-images.githubusercontent.com/13470265/48469987-7d96c400-e7f0-11e8-978e-2b1e977fb6ff.png)

Maybe you don't reveive the email notification.

There is none submission pending. Since some months, the average time to moderate a site submission is less than 1 week.

We processed your report request.
There is less than 1 report per month.

Thanks.

**Comment by Sandra97** [comment]
Thanks Sébastien!

Only 2 has been processed (and you can see that on your screenshot) ;) 

One week to moderate a site is good! Thanks

**Comment by sebastienlapoux** [comment]
No Sandra. This icon means has been moderated and required corrections from you.

**Comment by Sandra97** [comment]
I can't correct anything if I don't receive information about what to correct ;)

**Comment by Sandra97** [comment]
All good now. I'm closing this issue.
