### ISSUE TITLE
[jforum] Update links to https in forum rules

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-websites#1052]
Hallo
Please update links to https where passible in forum rules on top of each section.
Regards.

**Comment by iknoorjobs** [comment]
Let me take this.
@wojsmol  Do you want me to update README.md file with links ?

**Comment by zero-24** [comment]
@iknoorjobs Thanks for stepping but but i think @wojsmol means the links on https://forum.joomla.org where obviously only a limited amount of members have access to :)

**Comment by wojsmol** [comment]
@zero-24 You understand me correctly.

**Comment by Sandra97** [comment]
@ooffick, could you help with that? Thanks!

**Comment by ooffick** [comment]
Thanks for reporting this, the links are now changed to https links.

**Comment by wojsmol** [comment]
@ooffick Thank you for fixing that :) I'm closing this issue.

**Comment by wojsmol** [comment]
@ooffick I checked the issue again and in same forum rules blocks there are http links for example to Forum Rules

**Comment by ooffick** [comment]
Can you tell me where in the forum that is, I just checked a few in the forum boards and those are all ok.

Kind Regards
Olaf
