### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by millerk712** [joomla/joomla-websites#1053]
I am Chair of our local Playgroup - our website is hosted by Joomla.
I can login via my laptop (as the password is saved) - however I cannot change the password from within the application. When I try to do so it says "Error - Username in use" - I can't change the username and have tried everything.
I am about to handover as Chair and currently this will mean our organisation will no longer have any ability to alter our website - rendering it useless!
Please can you help?

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,

Thanks
