### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MarkyG21** [joomla/joomla-websites#1054]
Blank admin page after updating 3.7.5 to 3.8.1
Client is very happy with new no fuss look...
debug is no help..

id | select_type | table | type | possible_keys | key | key_len | ref | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | joshb_viewlevels | ALL | NULL | NO INDEX KEY COULD BE USED | NULL | NULL | 5 | 100.00 | NULL

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason close this Issue, thanks.

**Comment by MarkyG21** [comment]
<p class=wtf-happened-to-joomla>joomla died</p>

**Comment by pe7er** [comment]
Like Franz wrote, this joomla-websites issue tracker is only for issues regarding the joomla.org websites.

For questions about your own Joomla sites, please post them in Joomla forum: https://forum.joomla.org/viewforum.php?f=710

**Comment by MarkyG21** [comment]
So you only helping yourselves?


Kind Regards

Mark Garland
Manager and Webmaster
Toowoomba Web Design
PO Box 821 Toowoomba Qld 4350 AU
Phone: (07) 4615 5397 or Mob: 0418 168 678 



Web: www.toowoombawebdesign.com.au

This email contains information that is for the sole use of the intended recipient and may be confidential or privileged. If you are not an intended recipient, you may not keep, forward, copy, use, save or rely on this communication, and any such action is unauthorised and prohibited. Toowoomba Web Design (ABN 47 213 817 502).

**Comment by alikon** [comment]
NO,
this channel is for the *.joomla.org sites only
there is another channel for all the questions about joomla and it is the https://forum.joomla.org
we are only asking you to post there on the forum

**Comment by pe7er** [comment]
No. 
On https://github.com/joomla/joomla-websites/issues/ volunteers help with solving issues regarding the joomla.org websites of the Joomla project.
On https://forum.joomla.org volunteers help with solving issues regarding the Joomla websites of Joomla users.

If you want help for your own website, please use https://forum.joomla.org
Thanks!
