### ISSUE TITLE
[jorg] "The Software" menu item is identical "About Joomla!"

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-websites#106]
In the "About" menu the sub-menu item "The Software" is identical to the "About Joomla!" sub-menu item, same link: https://www.joomla.org/about-joomla.html
See the screenshot

![about-joomla](https://cloud.githubusercontent.com/assets/1362388/9609574/544973cc-50cc-11e5-9e13-c343d3244d7b.png)

Sorry for my bad english  :)

**Comment by MATsxm** [comment]
Fixed until the rebuild of the site - Thanks
