### ISSUE TITLE
[jdev] 

### ISSUE THREAD

**Issue by venkatgopu93** [joomla/joomla-websites#1060]
i am getting web page title(site name) same for every page in website ? i dont want it in everypage.can you please  suggest me the way to resolve it ?

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks
