### ISSUE TITLE
[jconf] 403 and 404 errors behind talk title links on the timetable page

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#1061]
I am getting a mix of [403](https://conference.joomla.org/schedule/why-add-an-extension-if-you-can-do-it-in-core-features-you-never-knew-existed.html) and [404](https://conference.joomla.org/schedule/web-and-push-notifications-for-joomla.html) errors when visiting the links behind all of the talk titles on [the timetable page](https://conference.joomla.org/timetable.html)

**Comment by Joomv** [comment]
Thanks for heads up. Forgot to flick a switch.
Sorted now.
