### ISSUE TITLE
[jdocs] Believed typo on CMS versions page

### ISSUE THREAD

**Issue by twainj** [joomla/joomla-websites#1062]
I believe there is a typo on the Joomla! CMS Versions page. The End Of Life column lists the release of v3.7 as the EOS for v3.7, and the release of v3.8 as the EOS for v3.8.

I'm guessing that it was a copy/paste error for the 3.7 entry, and a blind increment on 3.8.  I'm guessing that the End of Life on Joomla 3.8 is the release o Joomla 3.9. Is that correct?

Please advise if I have misunderstood.

Thanks!
Jason

See issue at https://docs.joomla.org/Special:MyLanguage/Joomla!_CMS_versions

**Comment by Sandra97** [comment]
Hello,

Yes, you are right.
I've edited it with 3.8 as EOS for 3.7 and 3.9 for 3.8.

Thanks.

I'm closing this issue.
Re-open if needed.

**Comment by twainj** [comment]
Sure thing!

~Jason

Jason Jones
541-600-4096
