### ISSUE TITLE
Mistyped email address

### ISSUE THREAD

**Issue by dcassone** [joomla/joomla-websites#1064]
I was trying to sign up for a Joomla Showcase directory and must have mistyped my email address.

I never got the confirmation email and cannot now login.

I tried to get my password and was told that it was an invalid email address...so I must have mistyped it.

My user is djc1

Thanks!
Dom

**Comment by Sandra97** [comment]
@sebastienlapoux Can you help with this? Thanks.

**Comment by sebastienlapoux** [comment]
Hi @dcassone ,

Your account has been deleted, please create it again.

Thanks.
