### ISSUE TITLE
My Media Manager is having two issues [jhelp] 

### ISSUE THREAD

**Issue by asonnyn** [joomla/joomla-websites#1065]
Hello,

1. When I upload a pdf onto Media Manager, I'm unable to delete it.  It refreshes the page but keeps the documents.  I also tried to create an External URL with the <joomla root>/images/XXXXXXX.pdf and it won't link to it.  It's not had a problem previously.
2. When I click on Detail View of Media Manager, it won't change to a Details pane, it just stays the same.

What can I do?

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Websites like joomla.org. For this Reason close this Issue, thanks.
