### ISSUE TITLE
[jdown] Noindex or less Priority for old Versions (SEO)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1066]
Can we set the old versions to noindex or less priority on the sitemap so that Google does not recommend the outdated Versions?
<img width="832" alt="grafik" src="https://user-images.githubusercontent.com/828371/32002047-c88094fc-b99b-11e7-943c-86a5e7c57839.png">

**Comment by mbabker** [comment]
Sitemaps are now in place with proper prioritization rules.
