### ISSUE TITLE
[jdown] Mixed Formal Informal Form CDN Menu footer (german)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1067]
Unterstütze Joomla mit $5 = informal
Melden Sie einen Fehler = formal 

Both should be the same Form:
**if informal:**
Unterstütze Joomla mit $5 
Melde einen Fehler 

**formal:**
Unterstützen Sie Joomla mit $5
Melden Sie einen Fehler 

<img width="918" alt="grafik" src="https://user-images.githubusercontent.com/828371/32002144-07918dfe-b99c-11e7-8516-3c662b8ee3d7.png">

**Comment by mbabker** [comment]
This should be raised at https://crowdin.com/project/joomla-official-sites as all the translations are coming from there, I just push them up.

**Comment by coolcat-creations** [comment]
ok - which form should i put there?

**Comment by mbabker** [comment]
That's between you and the other German translators to decide, these days about the only Germany I remember is "Bier".

**Comment by coolcat-creations** [comment]
Prost! :)

**Comment by Sandra97** [comment]
All translations are managed on Crowdin, please post your suggestions there. 
I'm closing this issue.
