### ISSUE TITLE
Website Crash

### ISSUE THREAD

**Issue by ClaireWay** [joomla/joomla-websites#1068]
My website has crashed with the following message. Any insight on how to rectify this issue is appreciated.

Message when trying to access website

Fatal error: Call to undefined function utf8_strpos() in /home/cw105904590ss/public_html/libraries/joomla/string/string.php on line 164

Fatal error: Access to undeclared static property: JLoader::$classes in /home/cw105904590ss/public_html/libraries/loader.php on line 213

Message in admin> control panel> global configuration & my profile

Fatal error: Call to a member function setForm() on a non-object in /home/cw105904590ss/public_html/libraries/joomla/form/form.php on line 1734

Fatal error: Access to undeclared static property: JLoader::$classes in /home/cw105904590ss/public_html/libraries/loader.php on line 213

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
