### ISSUE TITLE
[jshow] add a "multilingual" tag

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#1069]
Could you add a tag 'multilingual' , as it's one of our core features and USP's, it would be great for marketing purposes to be able to link to a selection in the showcase of multilingual sites. 
Thank you to take this into consideration.
![2017-11-02_14-45-52](https://user-images.githubusercontent.com/4589318/32329224-ae53d08e-bfdc-11e7-9d79-45e129a56d46.png)

**Comment by sebastienlapoux** [comment]
Hi Mike,
Great! Added:
![image](https://user-images.githubusercontent.com/13470265/33656332-107b9b9e-da76-11e7-839a-014379532020.png)
Thanks.
