### ISSUE TITLE
[jdev]  YouTube icon missing

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#107]
Hi, I noticed on my phone that the YouTube icon is missing
![screenshot_2015-09-01-13-46-58](https://cloud.githubusercontent.com/assets/1581195/9613282/078040fa-50b0-11e5-96e3-10a441f83ffc.png)
Please describe the problem or your issue

**Comment by mbabker** [comment]
The CDN finally refreshed in the last half hour or so, it should be there (I just checked my mobile and I have it).

**Comment by jessicadunbar** [comment]
ok, thanks

**Comment by MAT978** [comment]
I noticed this and at this point, (should be because of cache), it doesn't appear on the first load, then ok if you refresh
