### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MargaretParker** [joomla/joomla-websites#1070]
I cannot get into my Joomla account.
website    www.arranapartments.co.uk
I have tried to get a password or user name reset but none of my e-mail addresses have been recognised. They are;
macs.parker@yahoo.co.uk
macs.parker@gmail.com
info@arranapartments.co.uk
My user name was !HolyIsle20
Thank you

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Websites like joomla.org. For this Reason please close this Issue, thanks.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Websites like joomla.org. For this Reason please close this Issue, thanks.

**Comment by MargaretParker** [comment]
Hello
Thank you for your prompt response but I cannot log in to access my account
and cannot find any other contact  details
Best wishes
Margaret

**Comment by Sandra97** [comment]
This repository is not the right place for asking for support about your website, as it's dedicated only to the Joomla! official websites.
You can check on JDocs [docs.joomla.org](https://docs.joomla.org) the tutorial on how to reset your password or ask for help in the [Forum](https://forum.joomla.org/)

**Comment by ot2sen** [comment]
Sounds like Margaret might have trouble logging in to the joomla forums
too. In that case you can contact the forum team at
https://volunteers.joomla.org/teams/forum-team and they can help you reset
you access.

**Comment by Sandra97** [comment]
For any issue with login to the Forum, the best way is to fill this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by MargaretParker** [comment]
Thank you for your help. It is much appreciated
Best wishes
Margaret

**Comment by MargaretParker** [comment]
Sorry, I'm still not getting into the forums as none of my emails have been
recognised. Is it possible for someone to contact me please
Many thanks
Margaret

**Comment by Sandra97** [comment]
The only way to get your forum issue solved is to fill the form I mentioned above: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by MargaretParker** [comment]
Thanks Sandra, I have tried that and hope it works

**Comment by ooffick** [comment]
Hi Margaret

As I mentioned to you in my last mails, you will need a joomla forum account, would you please register for a joomla forum account and ask your question in the forum. 

Kind regards 
Olaf

**Comment by MargaretParker** [comment]
I cannot register for a forum account as both my username and email address
are not recognised. That is my problem

**Comment by ooffick** [comment]
Hi Margaret

What do you mean your username and email are not recognised. You will need to register a new account. (do not try to reset your password, as you do not have an account) 

Kind regards 
Olaf
