### ISSUE TITLE
[jdown] Link funktioniert nicht

### ISSUE THREAD

**Issue by Dennis1993** [joomla/joomla-websites#1071]
Wenn ich folgenden Link aufrufe, ist ein Download nicht möglich. Wie kann ich dies manuell downloaden und installieren?

https://downloads.joomla.org/de/cms/install-from-web/1-1-1

Als Ausgabe kriege ich immer folgenden Fehler:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>joomladownloads/extensions/ifw/plg_webinstaller_3.4v1.1.1.zip</Key>
<RequestId>2D0FF9A287B6EE88</RequestId>
<HostId>21MC9wGbja9UiwoPfSPuq7ZEZ23ewABdcAukxAUl7Z65EzSQSY/Yms21OsaI5gft78v7o+O8Fqg=</HostId>
</Error>
```

**Comment by Sandra97** [comment]
Could you please write in English?
Thank you!

**Comment by franz-wohlkoenig** [comment]
If i call Link https://downloads.joomla.org/de/cms/install-from-web/1-1-1 i get : `<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>joomladownloads/extensions/ifw/plg_webinstaller_3.4v1.1.1.zip</Key>
<RequestId>2D0FF9A287B6EE88</RequestId>
<HostId>21MC9wGbja9UiwoPfSPuq7ZEZ23ewABdcAukxAUl7Z65EzSQSY/Yms21OsaI5gft78v7o+O8Fqg=</HostId>
</Error>`

**Comment by alikon** [comment]
got something similar with the English link  https://downloads.joomla.org/extensions/install-from-web/1-1-1/plg_webinstaller_3-4v1-1-1-zip?format=zip
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>joomladownloads/extensions/ifw/plg_webinstaller_3.4v1.1.1.zip</Key><RequestId>F82E972071F6B38A</RequestId>
<HostId>yiwnhYC8oPU2II1kHp/MevEGX45RHKLS8WScBhRCM9jGB6l5DZv2HhL1zPmhMHME1WrpRb/0E54=</HostId>
</Error>
```

**Comment by alikon** [comment]
Weblinks 3.6.0  works as expected

**Comment by Sandra97** [comment]
Yep, it seems it happens only for 1.1.1

**Comment by mbabker** [comment]
The filename reference was incorrect.  Fixed it, downloads work.

**Comment by Dennis1993** [comment]
Thank you! And sorry, I write it in english in the future!
