### ISSUE TITLE
Technical Requirements for 3.8.2 - Incorrect Minimum MSSQL version

### ISSUE THREAD

**Issue by an0ther1** [joomla/joomla-websites#1072]
Long time reader/lurker, first time poster!!

The requirements page https://downloads.joomla.org/technical-requirements identifies  MSSQL Version 10.50.1600.1 (MSSQL 2008 R2)
When attempting to login to the Administration page using Joomla 3.8.2 & MS SQL 2008 R2 users will receive a message that CONCAT is not a recognised function etc

The minimum version of MS SQL should be 11.0 (MS SQL 2012) as this version does include CONCAT

Kind Regards

**Comment by mbabker** [comment]
Actually, as we can't raise the minimums over the course of a major release series, it is actually a bug that the CONCAT function is used on unsupported platforms and should be reported on [the CMS repo](https://github.com/joomla/joomla-cms) as such.

**Comment by an0ther1** [comment]
Sorry Michael, wasn't aware, my bad.

Would you like me to raise the bug report there? 

Cheers

**Comment by mbabker** [comment]
Yes please.

**Comment by an0ther1** [comment]
Will do, thanks Michael, hope you have an awesome day
