### ISSUE TITLE
Update from 3.8.0 to 3.8.1 Timeout

### ISSUE THREAD

**Issue by AlainGerardin** [joomla/joomla-websites#1073]
My provider OVH says than the IP 213.251.182.115 is blaklisted by Joomla, which will explain this update problem.
What to do ?

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks

**Comment by zero-24** [comment]
@jeckodevelopment Isn't this is a `issues with the *.joomla.org websites,` when the IP get blocked?

**Comment by jeckodevelopment** [comment]
i guess it's more a CMS problem if we can't provide updates :)

**Comment by zero-24** [comment]
> i guess it's more a CMS problem if we can't provide updates :)

How do you think you can fix a blocked IP on the download / updateserver site codewise?

**Comment by jeckodevelopment** [comment]
you're right Tobias!
