### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MargaretParker** [joomla/joomla-websites#1074]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by Sandra97** [comment]
@MargaretParker Could you please describe your issue?

**Comment by MargaretParker** [comment]
Hello
I have had an account since 2013 but now can't get into it. It says my
email and/or user name is not recognised or I do not have an account.
www.arranapartments.co.uk
Thank you
Margaret

**Comment by Sandra97** [comment]
@ooffick Could you give a look to Margaret's issue? 
See also #1070 

Thanks.

**Comment by Sandra97** [comment]
I'm closing this issue as  @ooffick answered in the other open issue.

**Comment by ooffick** [comment]
Hi Margaret

You do not have an account at forum.joomla.org, your account  for your own website is not a Joomla forum account and therefore you will need to create an account of you want to ask a question in the Joomla forum.

But we did discuss all this before via unban request form. 

Kind regards 
Olaf

**Comment by MargaretParker** [comment]
Ok
