### ISSUE TITLE
[japi] Downloads API for signatures not working

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1076]
Downloads API for signatures not working
@mbabker 

https://downloads.joomla.org/api/v1/signatures/cms/3.8.2

  | {"error":{"code":404,"message":"Version not found"}}
-- | --

<img width="575" alt="screen shot 2017-11-14 at 14 26 35" src="https://user-images.githubusercontent.com/400092/32784835-d62db56a-c947-11e7-80aa-c7ee0ffa632c.png">

Same for all versions

**Comment by mbabker** [comment]
It uses hyphens for the version separators (same as the main site URIs).

**Comment by PhilETaylor** [comment]
ahhhhh :) that works :)
