### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ARNepal** [joomla/joomla-websites#1077]
Hello, 

 I would like to get in contact with this organization in Nepal in order to donate money them but the contact us part of the website doesnt work giving this responce #404 Component not found

http://www.cdecf.org.np/contact-us

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,
Thanks
