### ISSUE TITLE
[jhelp] NOT ALL INFO IS SHOWING ON THE WEB SITE using salesforce reader.

### ISSUE THREAD

**Issue by johnisjobu** [joomla/joomla-websites#1078]
I am not sure when the plugin stopped working. Some of the data shows up fine. I confirmed that data is salesforce and that is good. Then on the website I cleared the cache in the app. I still I am looking the web site and the sales force. I there a way to check the info coming across and how does is pull the data? Web hooks or just scraped everything with a specific URL?

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like joomla.org. For this Reason closing this Issue, thanks.
