### ISSUE TITLE
[jcertif] Youtube tags not converted

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-websites#1079]
After the list of images 2 Youtube tags are not converted

```
{youtube}kOp-pH4kPL4|300|225{/youtube}

{youtube}9W8OVfeoAak|300|225{/youtube}
````
URL: https://certification.joomla.org/news/117-great-results-at-joomladay-italy

**Comment by zero-24** [comment]
cc @jeckodevelopment can you help here? This is still a issue. Thanks,

**Comment by jeckodevelopment** [comment]
Andrea fixed it :)
Thank you
