### ISSUE TITLE
[jdocs] Typo in es-ES

### ISSUE THREAD

**Issue by antoniojosetorres** [joomla/joomla-websites#108]
Error ortográfico:
En https://docs.joomla.org/Joomla_3_FAQ/es pone:
Por favor use la Hoja de **ruda** del desarrollo del CMS Joomla! ...
y debería decir
Por favor use la Hoja de **ruta** del desarrollo del CMS Joomla! ...
![fireshot capture 61 - preguntas frecuentes de joomla 3 - _ - https___docs joomla org_joomla_3_faq_es](https://cloud.githubusercontent.com/assets/8727469/9613663/0f8d3a2c-50ed-11e5-838f-0df78e9b3cfa.png)

**Comment by MAT978** [comment]
Hello and thank you for pointing.

As a Wiki, The Joomla! Documentation is a participatory system and allows all registered users to correct, update, translate or create new content.
To register, please fill out the following form and then you will be able to contribute with your change:
https://docs.joomla.org/index.php?title=Special:UserLogin&type=signup

If necessary, do not hesitate to contact me.

Thank you in advance to be part of the Community .

**Comment by MAT978** [comment]
Closed as solved, thanks to Isidro
Next time, please report directly on the JDocs.
