### ISSUE TITLE
[jcertif] Missing link to certified administrators

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-websites#1080]
The https://certification.joomla.org/ has no link or indication anywhere that shows where the list of certified administrators is.

**Comment by genr8r** [comment]
Good catch @roland-d This (https://exam.joomla.org/directory) is the link you are looking for right? Just needs a link from certification site.

**Comment by roland-d** [comment]
@genr8r Correct, just a clear link to the directory, so people know where to find certified administrators.

**Comment by zero-24** [comment]
@jeckodevelopment can you help here? Thanks 😄

**Comment by jeckodevelopment** [comment]
Hi guys,
yes, it will be added to the Certification website.

**Comment by jeckodevelopment** [comment]
Added the link to the top menu
![immagine](https://user-images.githubusercontent.com/733133/33221517-66213272-d150-11e7-8a1c-27ab03728499.png)

This can change shortly with the review of the Certification website that is ongoing.
