### ISSUE TITLE
[jdocs] copyright policy

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1083]
The docs site content is all published under the [JEDL licence](https://docs.joomla.org/JEDL )

I can see there that it clearly addresses the copyright ownership and usage of the docs but I cant see anything regarding the copyright of text added to the docs.

Specifically I am looking for something that states that you can not simply copy and paste content from another site onto the docs site without permission or accreditation.

**Comment by brianteeman** [comment]
For reference I am specifically referring to content that has been copy and pasted from the w3c web site that does not comply with the [w3c documentation licence (https://www.w3.org/Consortium/Legal/2015/doc-license)

Because this content is in breach of the w3c copyright then the Joomla/Opensourcematters documentation licence is giving people the right to repeat the infringement.

**Comment by Hutchy68** [comment]
Page?

**Comment by brianteeman** [comment]
i am trying to not publicaly  name and shame and just ask if there is a policy for submissions and/or a procedure to report pages that infringe copyright

**Comment by Hutchy68** [comment]
![a030ca62-adf1-4a91-be36-54beff59debf](https://user-images.githubusercontent.com/3527469/33237346-391e8adc-d23f-11e7-89f0-7cb29b3a1bfb.jpeg)

No shaming, just need to correct this as every edit window’s has this below it. If it is an obvious violation it needs to be corrected. PM Sandra/me on Twitter so we can remove it. Thanks.

**Comment by brianteeman** [comment]
Ah ok thats great - I was looking for that text but didnt see it.

**Comment by brianteeman** [comment]
I will send you the information privately

**Comment by Hutchy68** [comment]
Closing as this was dealt with in #1119
