### ISSUE TITLE
[jrd] Please update JRD badge

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#1084]
![immagine](https://user-images.githubusercontent.com/733133/33338560-b7e8a508-d476-11e7-848c-4f7e7a19140c.png)

The badge displayed is out of date.
Please use the new version:

![immagine](https://user-images.githubusercontent.com/733133/33338671-0e9ad128-d477-11e7-8553-4ebcdf7afe8c.png)

You can find them here: https://tm.joomla.org/conditional-use-logos.html
Please remind them also to use the Disclaimer.

**Comment by genr8r** [comment]
Hi @jeckodevelopment only one of the three new badges matches up with the JRD categories. We have a custom plugin that makes the current badge and link available and it does not have logic to sort different badges by category.

I can check into assigning the "hosting provider" version to listings in that category. Should we just do the "solutions developer" version or "business support" for the others?

**Comment by jeckodevelopment** [comment]
thanks @genr8r 
i guess that, if possible, we can use "business support" for all the consultancy services (incl. marketing and so on) and "solutions developers" for the custom development categories, if any

**Comment by genr8r** [comment]
Thanks @jeckodevelopment We can review which badges for which categories at next week's meeting and then figure out how to swap that logic into the plugin. I will update this issue as appropriate until it is resolved

**Comment by jeckodevelopment** [comment]
Thank you!!!

**Comment by Sandra97** [comment]
@genr8r What's the status of this issue? Is it ok now? Can I close it?

**Comment by Sandra97** [comment]
No answer so far...

**Comment by Sandra97** [comment]
Still no answer. I'm closing this issue.

**Comment by Saeedghb** [comment]
Hi @Sandra97, @genr8r 

I've addressed and resolved the technical aspect of this issue.
I've edited the custom component for badges and added a feature to display both square and horizontal badges for each of the three service types. 

We also need to upload these image files to cdn.joomla.org, like previous ones.

Please assign to me any technical issues related to JRD.

**Comment by Sandra97** [comment]
Thanks @Saeedghb!
