### ISSUE TITLE
[jcomm] Language Danish is not an option in Meeting Language when searching for a JUG

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1087]
It's come to my attention that the language Danish is not an option when selecting a "meeting language" on the [Find a User Group page](https://community.joomla.org/user-groups/find-a-user-group.html).

Is this because no JUG from Denmark has filled in their language, I noticed this on checking on [JUG Odense](https://community.joomla.org/user-groups/europe/denmark/922-joomla-user-group-odense.html), or is something wrong here?

**Comment by Sandra97** [comment]
Danish still not an option. Any update about that?

**Comment by jeckodevelopment** [comment]
I added the Danish language to the language field.
Added "Danish" to JUG Odense, we should be ok now
