### ISSUE TITLE
[jexam] Fields missing at exam.joomla.org profile edit

### ISSUE THREAD

**Issue by renekreijveld** [joomla/joomla-websites#1088]
Steps to reproduce the issue:

- Login at the exam.joomla.org website.
- Go to Dashboard
- Go to Edit My Profile

Expected result:

- Street field is shown and can by changed
- Phone number is shown and can by changed
- Time zone can by changed

Actual result:

- Street field is missing
- Phone number field is missing
- Time zone cannot be changed

**Comment by jeckodevelopment** [comment]
Thanks René. 
I'm reporting to the Exam&Platform Team :)

**Comment by conconnl** [comment]
Hi René, why do you expect these fields?

**Comment by renekreijveld** [comment]
If you even have to ask this, that is worrying...

The data in my profile is not correct and it is in fields that do not show
up in the edit form. I mentioned the fields in the Github issue.

Regards,
Rene

Op 11 dec. 2017 19:11 schreef "Wilco Alsemgeest" <notifications@github.com>:

**Comment by conconnl** [comment]
I asked because it's not Joomla!, the Edit my profile is a other system.
I can't see any of these fields you mentioned in the system.
Can you tell me on which page you see the information displayed, so debug this info.

**Comment by renekreijveld** [comment]
To view the profile:

- Go to https://exam.joomla.org/directory
- In the Search by field input 'Kreijveld'
- In the search resuls click 'René Kreijveld'

Then you see my profile data.

To edit the profile:

- Go to https://exam.joomla.org/
- Login with the login module on the right
- Below Quicklinks click Edit My Profile

The URL is https://exam.joomla.org/index.php/update

Street field is missing.
Phone number field is missing.
Time zone cannot be changed.

When I change the City in edit my profile that updated city is then shown when you search my profile in the Certified User Directory.

**Comment by conconnl** [comment]
I found the information and the fields.
They are visible in the system, the layout is messed up somehow.

If you collapse "general" and "User picture", then you will see the "optional" fields.
There you will see phone number and street.

Will try to fix the layout or find someone who can.
Will probably remove the timezone field, even with the highest rights in the system this can't be changed.

**Comment by Sandra97** [comment]
@conconnl Has this issue been solved?

**Comment by conconnl** [comment]
No, but there is no reason for it anymore.
Moodle is going to be removed.
Then the issue solves itself.

**Comment by Sandra97** [comment]
Thanks Wilco.
I'm closing this issue.
