### ISSUE TITLE
[jdocs] https://docs.joomla.org/Joomla!_Development_for_Beginners

### ISSUE THREAD

**Issue by MKTGExperts** [joomla/joomla-websites#1089]
All the links to tutorials are 404's

**Comment by Hutchy68** [comment]
Thanks, the articles were never written and the page has now been archived. Additionally, that page was an orphan with no links to it at all. Given the titles of the redlinks on the page to none existent pages, it is out of scope of docs to write general/basic tutorials on HTML, Javascript, JSON, etc. Thanks and closing.
