### ISSUE TITLE
[jorg] FB debugger reports "Circular redirect path detected"

### ISSUE THREAD

**Issue by SigsiuTrinity** [joomla/joomla-websites#109]
e.g: https://www.joomla.org/announcements/general-news/5627-it-s-here-a-belated-birthday-gift-for-joomla.html
Facebook debugger reports the error "Circular redirect path detected" because it detects the shortened URL "http://joom.la/N5" as canonical URL and used as  `<meta property="og:url">` .
However, the source code of that page does not show any canonical URL.

When accessing the page via https://www.joomla.org/announcements/general-news/5627-it-s-here-a-belated-birthday-gift-for-joomla.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+JoomlaAnnouncements+%28Joomla%21+Announcements%29
this URL is used as canonical URL which is wrong.

**Comment by Radek-Suski** [comment]
I see in the source code 
`<meta property="og:url" content="http://joom.la/N5"/>`
It could be caused by the shortener implementation. I will check it. 

But the canonical with the feed burner tracking code is really strange. @mbabker could you check it please?

**Comment by mbabker** [comment]
Patched and deployed.

**Comment by Radek-Suski** [comment]
Thank you
