### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-websites#1090]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by Webdongle** [comment]
Slow and many timeouts

**Comment by Webdongle** [comment]
https://forum.joomla.org/viewtopic.php?f=7&t=957275

**Comment by Sandra97** [comment]
Closing this issue. 
Re-open if needed
