### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by ingeva** [joomla/joomla-websites#1091]
I have an issue with one of my Joomla! sites. I also can't log in to the forum for support. The password seems to have been changed, and I'm not getting any reset email.
My user name is ingeva and my email is inge(&)vabekk.no. I have checked the spam folder; nothing there.
Thanks, Inge

**Comment by Sandra97** [comment]
Please fill the [Forum Account Support Form](https://community.joomla.org/helpdesk/forum-un-ban-request.html).
Thank you.
