### ISSUE TITLE
login

### ISSUE THREAD

**Issue by NA7KR** [joomla/joomla-websites#1093]
I have made two accounts na7kr and na7krus I never get the email.
Please, can you help?
Would like NA7KR and kevin+joomla@na7kr.us or just kevin@na7kr.us

Kevin

**Comment by hvdmeer** [comment]
On what website did you make these accounts?

**Comment by NA7KR** [comment]
https://forum.joomla.org/

On Tue, Dec 5, 2017 at 12:12 AM, Hans van der Meer <notifications@github.com

**Comment by Sandra97** [comment]
Please fill the [forum account support form](https://community.joomla.org/helpdesk/forum-un-ban-request.html). 
Thanks.
