### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by Lwineman** [joomla/joomla-websites#1094]
Our issue is that we edited/created a three column megamenu but cannot edit the white background anywhere to fill in the transparent background in between the second and third column.  Can you help?

![image](https://user-images.githubusercontent.com/17929316/33623184-2a7aa69c-d9be-11e7-962a-c26352011c46.png)
![website template image issue](https://user-images.githubusercontent.com/17929316/33623281-783c9a52-d9be-11e7-9ac5-b16e3423464b.png)
![template image](https://user-images.githubusercontent.com/17929316/33625173-ba8d1034-d9c4-11e7-8434-4d257df1cedc.jpg)

thanks

Lindy
989 883 3411
lindy@abadata.com

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm gonna close this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks
