### ISSUE TITLE
[jhelp] I have no installation plugin enabled

### ISSUE THREAD

**Issue by ltdaniel** [joomla/joomla-websites#1098]
I was trying to upload a template for my site, but it seems there is a warning message, indicating that there is no installation plug in enabled. I had already consulted my problems to my website provider, but they are also clueless on the issue. Please do help me.
![install](https://user-images.githubusercontent.com/34391473/33793693-c3744020-dcf6-11e7-9a75-64c17ee2de1d.JPG)

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
