### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by rbuchjoomla** [joomla/joomla-websites#1099]
There is a malfunction at Menu Media of latest Joomla version. We have very much files and when click over this menu option, the list run very and very slow. Very slowly.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm closing this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

If you would like to report an issue with the CMS, please report it at https://issues.joomla.org

Regards,

Thanks
