### ISSUE TITLE
Coding style and standards page has no title (h1)

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1102]
Hi,
Searching for the updated **Coding style and standards** from the old docs page (https://docs.joomla.org/Coding_style_and_standards), I found the new page: https://developer.joomla.org/coding-standards.html

This new page (and the internal pages) doesn't have a title (h1, h2, etc).

**Comment by Sandra97** [comment]
Hi Anibal, 

These pages have titles (h1, h2, h3).
On all our properties <h1> is the title of the site (so for this one, 'Joomla! Developer Network')

**Comment by anibalsanchez** [comment]
Yes, all pages have the same H1. I've been expecting to find a title like in the previous articles, where you have a different h1 title for each page. Examples:

- https://docs.joomla.org/Coding_style_and_standards
- https://docs.joomla.org/Joomla_CodeSniffer

**Comment by mbabker** [comment]
The component rendering the manuals is replaced and there are now `<h1>` tags within the `<main>` section.
