### ISSUE TITLE
Help! Can't Access Site [joomla.org] 

### ISSUE THREAD

**Issue by la31779** [joomla/joomla-websites#1103]
We had to redirect our Joomla site to a new site. Now, we need to get access to the Joomla site to pull some of the data so we can start updating it. But now I can't get into the site. The redirect pulls me away. HELP! What can I do to access the administration portion of the site?

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Site like joomla.org.

**Comment by la31779** [comment]
Can you point me in the right direction on the forums. I don’t even know what question to ask?

Thank you,

Lenore Ankenman

**Comment by franz-wohlkoenig** [comment]
You find there an Index, choose one which fits your Issue best.

**Comment by la31779** [comment]
I've been looking but can't find anything. I'm not sure I'm asking the question correctly. I'm really lost.

**Comment by franz-wohlkoenig** [comment]
Personally i would ask first in https://forum.joomla.org/viewforum.php?f=708. But i think its no Problem if you start in a wrong one.

**Comment by franz-wohlkoenig** [comment]
Please close this Issue as this Report isn't an Issue for this Repository, thanks.

**Comment by la31779** [comment]
Ok. Except I can’t submit the issue or find an answer on forums. I tried to sign up so I could start a new thread and the system isn’t letting me in.

Thank you,

Lenore Ankenman

**Comment by Sandra97** [comment]
If you have issue with registration on the forum, please fill this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html
