### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by aceembossing** [joomla/joomla-websites#1104]
Hello,

I've lost the ability to edit my website, I can't login to joomla to access the site. 

Please help.

Derek@aceembossing.com
408.262.2585

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm closing this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

If you would like to report an issue with the CMS, please report it at https://issues.joomla.org

Regards,

Thanks
