### ISSUE TITLE
'JClassLoader' not found in /home/gismalawi/public_html/libraries

### ISSUE THREAD

**Issue by wsimbota** [joomla/joomla-websites#1105]
After uploading local joomla 3.8.2 web site to a server website I get an error message saying;
'JClassLoader' not found in /home/gismalawi/public_html/libraries

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm gonna close this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks
