### ISSUE TITLE
SiteLock is blocking access to joomla.org

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1108]
It looks like there are some issues with sitelock:

![image](https://user-images.githubusercontent.com/2596554/35171571-9449400a-fd64-11e7-84a4-5245f67d9939.png)

As they also broke all data served from joomla.org like the backed feeds:

![image](https://user-images.githubusercontent.com/2596554/35171632-bfce9a5e-fd64-11e7-876c-ac6a0a672898.png)

### Location tested

- Germany

**Comment by mbabker** [comment]
The first screenshot I imagine users will see periodically (I see something similar hitting CloudFlare's security screening on occasion with other domains).  As for the RSS issue, email sent out, I can confirm the issue on just about every server I have backend access to.

**Comment by zero-24** [comment]
> The first screenshot I imagine users will see periodically

Claim that my client is infected by malware without any evidence i think this should not happen again else everyone should lost trust to such screens.

>  As for the RSS issue, email sent out, I can confirm the issue on just about every server I have backend access to.

Thanks!

**Comment by mbabker** [comment]
I'm not saying the text on the page is any good, just commenting on the purpose as I understand it.

**Comment by brianteeman** [comment]
It only seems to be feeds on www - other joomla properties are ok
I am guessing from the sitelock features promoted here https://blog.sitelock.com/2016/05/good-and-bad-internet-bots/ that this is intentional behaviour by sitelock
so its definitely a "bug" that needs to be resolved with them. Who can do it?

**Comment by zero-24** [comment]
> so its definitely a "bug" that needs to be resolved with them. Who can do it?

I expect them to report back to Michael as he already email them 😄

**Comment by brianteeman** [comment]
i missed that info

**Comment by zero-24** [comment]
> It only seems to be feeds on www - other joomla properties are ok

Could be that they have not yet enabled that `feature` SiteLock to that sites yet (as there are no `Yes this is secure as we have security scanned this site badge`) ;)

**Comment by brianteeman** [comment]
Oops

**Comment by zero-24** [comment]
![image](https://user-images.githubusercontent.com/2596554/35177577-f2df7e74-fd80-11e7-9068-d8ee5841a100.png)

;)

**Comment by brianteeman** [comment]
any response from sitelock?

**Comment by mbabker** [comment]
The feed issue should be addressed.  When I looked to confirm this morning things were working OK from the servers I checked against.

**Comment by brianteeman** [comment]
sorry I should have checked before commenting. I just didnt see an update here but can now confirm the feed is appearing

**Comment by zero-24** [comment]
Feed works for me here too. Thanks for the update.
