### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by felipeparru** [joomla/joomla-websites#1109]
The slides Installer from folder and Installer from URL don't appear in the installation menu and this happened right after an update. I have tried some suggestions from forums but nothing has worked. Im kind of desperated.

**Comment by zero-24** [comment]
Hi,

please try Backend -> Extensions -> Plugins -> Search Tools -> Select type => `installer` -> enable the Plugins called:
- Installer - Install from Upload
- Installer - Install from Folder
- Installer - Install from URL

For any future questions please create your own topic at https://forum.joomla.org as this here is just the place to report issues with the *.joomla.org webseites ;)
