### ISSUE TITLE
[jorg] Header and Footer Images

### ISSUE THREAD

**Issue by Skullbock** [joomla/joomla-websites#111]
The header and the footer full screen images seem to be limited to 1980px in width.
This causes a bad look and feel on 27" screens (read: iMacs)

See attached image :)

![image](https://cloud.githubusercontent.com/assets/1104083/9631917/517dfad8-5184-11e5-9775-e19c712212c0.png)

**Comment by Radek-Suski** [comment]
It would be also good to compress this images. These are a bit too heavy

**Comment by Sandra97** [comment]
The full screen image has currently a max-width of 1920px. In fact, the max-width of the template we had to use is 1170px (as you can see on all the inner pages). We decide to override this imposed width for the frontpage only. Unfortunately, the current template does not allow a correct full-wdith except for the mega menu and the footer (CDN). 

For the image, the image used was the one used on the previous j.org. I can compress a bit this image (from 72ko to 57k). Note that we're not in charge of the graphic elements (Phase 2). 

As you both know, it's a migration, the purpose was to upgdrade the website to 3.4.3 and make it responsive without using a new template. The re-design, content and optimization of the website is for Phase 2, managed by an other team. 
(I would have love to work on an other template.)

**Comment by mbabker** [comment]
I'd suggest closing as "won't fix".  The current template just isn't optimized for 1920+.  With the template refresh we can look at being better accommodating for these bigger displays.
