### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by Vreeni** [joomla/joomla-websites#1110]
We re using the paid version of Falang, but still get displayed the falang translation text on the bottom of every website. This only happened after the Joomla update.
Please help to resolve this issue.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm gonna close this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks
