### ISSUE TITLE
[jorg] Is there a interest of implementing csp's for joomla.org

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1111]
I think the most of you know what csp's are, they are headers a website can set to block such as xss attacks and injecting of other shit. With Joomla 4 the core is [going to ship a plugin](https://github.com/joomla/joomla-cms/pull/18301) but give that [we also have the same features in a 3.x plugin](https://github.com/zero-24/plg_system_httpheader) I would be happy to help to set up a propper csp header setup for joomla.org. If there is a general interest of doing so I'm happy to help implementing this on other sites too.

Important notice is that this is not a onetime job and this needs monitoring on what is going on. I'm happy to help here too.

joomla.org is currently getting a `F` by https://securityheaders.io as no header is set currently
![image](https://user-images.githubusercontent.com/2596554/35302753-ecb094b8-008f-11e8-9e61-09842b8a56a8.png)

A wile ago I have setup the csp header things for joomla.de and it is working great as far as I can tell:
![image](https://user-images.githubusercontent.com/2596554/35302902-7798b8f8-0090-11e8-8f9f-318a1719d622.png)

**Comment by mbabker** [comment]
Just know this is a big ask because each separate subdomain/installation is going to have to be worked through, and extra work needed to set up in ways other than through that plugin on [every](https://github.com/joomla/jissues) [non](https://github.com/joomla/framework.joomla.org) [Joomla](https://github.com/joomla/api.joomla.org) [installation](https://github.com/joomla/help.joomla.org).

**Comment by zero-24** [comment]
sure I know. For that 4 non-joomla sites we can work out a rule we can write down to the code itself or use the `.htaccess` files protecting the sites. To be shipped with PR's
The plugin itself does not guess any rule anyway it just provides a human interface setting it up with some usable default values ;)

But the rule itself is in the most times a one time task. Just checking the external sites loaded run some time in testing mode and monitor the errors correct if needed if decided over it block the mail and done. The not onetime job is basically monitoring what is going to get reported and blacklist it.

**Comment by mbabker** [comment]
I've got no problem with it myself or on sites I'm running.  Others will need to chime in for their respective sites, I'm not in a spot to be able to force it one way or the other but I'd say they should be pushing for it.

**Comment by Joomv** [comment]
@zero-24  Hit me up and we'll roll out on the sub-domains I manage

**Comment by Joomv** [comment]
@zero-24  community. tm. certification. and the OSM site have all been brought up to a B grade - pinged you on Glip for help with final 2 header settings.

**Comment by zero-24** [comment]
You have got a initial version for the osm page just a few minutes ago.

A open point is where we can have a central place for a csp-reporter script where we can monitor the reports and maintain a central blacklist. Ideally this would be a place where i can login and maintain the blacklist myself as i expect a big list of entrys for the blacklist and i don't want to load a that work on you too.

@mbabker here is the first PR against the issue tracker:
https://github.com/joomla/jissues/pull/1005

If you agree with that rules i can send a PR to all public repos setting that htaccess rules.

After that and when we have the decision about the place of the reporter script we can start analyse all our pages (i have started with the osm page) and setup the csp rules and throw them into report oly mode, get the results and than set them live and monitor that rules etc.

**Comment by mbabker** [comment]
> A open point is where we can have a central place for a csp-reporter script where we can monitor the reports and maintain a central blacklist.

If you've got any suggestions feel free to share them.

> If you agree with that rules i can send a PR to all public repos setting that htaccess rules.

You know more on the topic than I do, as long as we aren't blocking a site's main functionality then we're good.

**Comment by Hutchy68** [comment]
So, this should be really looked at carefully. 

Yep, I love security but there will not be a one size fits all for all sites. Errors in applying CSP -> headers could grow enormously, breaks in content, ads for revenue being blocked, domain sharing resource breaking, social shares broken, etc.... Wrongly applying rules could also allow what a browser would normally block by default through to the user.

The CSP (Content-Security-Policy) header would really have to be set to reporting first. Even then, the amount of violations being reported for all the properties I imagine would be enormous and difficult to sort through.

**Comment by zero-24** [comment]
@mbabker 
> If you've got any suggestions feel free to share them.

Rowan suggested the cdn or the community page. But you have more insights into our infrastructure so you can tell me if that would be a good place.

> You know more on the topic than I do, as long as we aren't blocking a site's main functionality then we're good.

Yes that is the plan we need to adjust the rules for example on the help proxy sites.

Here some more explanation on what the headers are supposed to do:
```
Header set X-XSS-Protection "1; mode=block"
```
Enable the inbuild browser support for XSS detection. In case the browser find a XSS attack the browser will block that.
https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection

```
Header always append X-Frame-Options DENY
```
Don't allow this page to be loaded inside of a iframe. (for example the help proxy can't set this header)
https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options

```
Header set X-Content-Type-Options nosniff
```
Disable mime detection in IE & Chrome
https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options

```
Header always set Referrer-Policy "no-referrer-when-downgrade"
```
The browser will not send the referrer header when navigating from HTTPS to HTTP, but will always send the full URL in the referrer header when navigating from HTTP to any origin. It doesn't matter whether the source and destination are the same site or not, only the scheme.
https://scotthelme.co.uk/a-new-security-header-referrer-policy/


@Hutchy68 
> Yep, I love security but there will not be a one size fits all for all sites. Errors in applying CSP -> headers could grow enormously, breaks in content, ads for revenue being blocked, domain sharing resource breaking, social shares broken, etc.... Wrongly applying rules could also allow what a browser would normally block by default through to the user.

Correct. The first thing we can do is adding the headers != the csp one.
Like i did here: https://github.com/joomla/jissues/pull/1005 for the issue tracker.

For sure we need to be very carefully in apply the csp and constantly monitor the rules.

> The CSP (Content-Security-Policy) header would really have to be set to reporting first. Even then, the amount of violations being reported for all the properties I imagine would be enormous and difficult to sort through.

As this is not the first page i'm setting up with that report only thing i have a long blacklist for the reports. So i think we could at least try it out.

**Comment by zero-24** [comment]
> and extra work needed to set up in ways other than through that plugin on every non Joomla installation.

All public repos you linked now have a PR implementing the basic headers:
https://github.com/joomla/jissues/pull/1005
https://github.com/joomla/framework.joomla.org/pull/27
https://github.com/joomla/api.joomla.org/pull/4
https://github.com/joomla/help.joomla.org/pull/6 (excluding X-Frame-Options)

Another open question is how do you want to handle HSTS / Strict Transport Security

The general default is
```
	# Strict-Transport-Security
	Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
```

That instructs the browser to call that domain only using https for 1 Year (31536000 seconds).

I'm happy to update the PR's with the needed lines if you agree 😄

**Comment by hvdmeer** [comment]
I see this tweet stand also to us. Is it wise to reply on this?
https://twitter.com/ValbonneConsult/status/963054407154839552

AFAIK this isn't really easy and/or wise to implement in the standard install or am i mistaken?

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/18301

Already a 4.0 roadmap item.

**Comment by mbabker** [comment]
Unless I'm mistaken this should be complete now?

**Comment by zero-24** [comment]
Isn't complete on all pages but this is work in progress and most of the pages are done. I'm going to move forward on the missing pages but i'm also fine closing here as everything is in progress.

**Comment by zero-24** [comment]
Closing as we are in progress and we don't need to keep this open as the intial question has bean answered. Thanks!
