### ISSUE TITLE
I don´t have Intaller from upload and Installer from URL

### ISSUE THREAD

**Issue by felipeparru** [joomla/joomla-websites#1112]
I updated my joomla version, after that I couldn't find my Install from Upload
and Install from Folder slashes. So, I reported the issue here, and the answer was the next one:

Please try Backend -> Extensions -> Plugins -> Search Tools -> Select type => installer -> enable the Plugins called:
Installer - Install from Upload
Installer - Install from Folder
Installer - Install from URL

My problem continues because the plugins Installer-Install from Folder and Installer-Install from URL don't appear in the list of the plugins and I can´t reinstall them. Please help me.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm closing this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

If you would like to report an issue with the CMS, please report it at https://issues.joomla.org

Regards,

Thanks
