### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by sasnakra49** [joomla/joomla-websites#1113]
Please describe the problem or your issue

Attempt to login to account on joomla.org unsuccessful. 
     Cannot get joomla.org to recognize my email sneb1949@yahoo.com
Keeps error reporting "Security tokens" do not match on login attempts. 
      Will not allow password update. 
Will not recognize username: sasnakra

Previous to these events,  successful account established, and login successful on joomla.org. 

Now NOOP.

Ben F Schafer

**Comment by Sandra97** [comment]
Hi!

joomla.org is not open to user registration so you cannot log into joomla.org. 
But maybe you're talking about logging into your website?
If so, note that this repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

If you would like to report an issue with the CMS, please report it at https://issues.joomla.org

Thanks
