### ISSUE TITLE
[jtrain]  500 error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1114]
Reported on the forum and confirmed that all the training courses are resulting in a 500 error

https://forum.joomla.org/viewtopic.php?f=799&t=958757

**Comment by Joomv** [comment]
I have taken training offline and sent OST details of the issue.
Also tagging them here @stevejburge 
Thanks.

**Comment by Joomv** [comment]
OST have provided a fix and this is now live again.  Closing.
