### ISSUE TITLE
[JED] No email sent when review posted for exensions

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-websites#1117]
Since last month, JED no longer sends notification emails when our extensions received reviews from users. Could someone please check it?

**Comment by Sandra97** [comment]
@joomdonation Do you still have this issue?

**Comment by Sandra97** [comment]
@anibalsanchez @JazParkyn  Could you look at this? Thanks!

**Comment by anibalsanchez** [comment]
JED has its own ticketing system: https://github.com/joomla/jed-issues/issues

To avoid duplication, please, close this ticket and reopen it there.

**Comment by joomdonation** [comment]
@anibalsanchez I posted a new issue https://github.com/joomla/jed-issues/issues/38
