### ISSUE TITLE
[jcomm] On login attempt to community.joomla.org: "the security token did not match"

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-websites#1118]
I'm having problems at the moment attempting to login to community.joomla.org with the credentials that I established for my account there.

Attempting to login gives the message

> Warning
> 
>     The security token did not match. The request was aborted to prevent any security breach. Please try again.

I've tried about several times all with the same result. Are we aware of any login problems there?

First reported https://forum.joomla.org/viewtopic.php?f=7&t=958802

**Comment by Sandra97** [comment]
Can you try using the **log in** link located in the footer? It should work.

**Comment by sozzled** [comment]
Sandra,

 

Thank you for your email.

 

I attempted to use the only login form that I see on the page https://community.joomla.org <https://community.joomla.org/> , 

 



 

but, even after clearing all my browser history (e.g. cookies, etc.) or using different platforms, I am unable to login.  Even attempting to use a login/password that is clearly wrong (e.g. username=test34567 / password=1o1o1o1o1) I get the same error message:

Warning

The security token did not match. The request was aborted to prevent any security breach. Please try again.



I just can't login at all

 

Regards

 

Michael Russell

**Comment by mbabker** [comment]
Try the "Log in" link located at the footer of the site (this link is present on almost every site and essentially routes to that site's `index.php?option=com_users&view=login` page).  Scroll past the module and don't use that.

**Comment by sozzled** [comment]
Ahhhh ... success ... I didn't scroll down that far on the page.

Looks like there's a problem (for me) with the login form.

**Comment by Sandra97** [comment]
As this issue is solved, I'm closing it.
Re-open if needed.
