### ISSUE TITLE
[jdocs] breach of copyright - again :(

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1119]
The following pages all contain copyright material from the w3c and despite the clear instructions on the w3c website regarding their copyright they have been published without complying to the terms explained here https://www.w3.org/Consortium/Legal/2015/doc-license

https://docs.joomla.org/Portal:Accessibility/WAI-ARIA_1.1
https://docs.joomla.org/Portal:Accessibility/UAAG_2.0
https://docs.joomla.org/Portal:Accessibility/WAI-ARIA_1.1

**Comment by rdeutz** [comment]
seems to me that it should be enough to add 

> "Copyright © 2015 W3C® (MIT, ERCIM, Keio, Beihang). This software or document includes material copied from or derived from [title and URI of the W3C document]." 

and ofc linking to the correct document

**Comment by brianteeman** [comment]
yes exactly - not as if the submitting user hasnt already been told this

**Comment by rdeutz** [comment]
tried to add the notes but failed because of my great mediawiki knowledge :-)

**Comment by mbabker** [comment]
https://docs.joomla.org/index.php?title=Portal:Accessibility/WAI-ARIA_1.1&diff=477355&oldid=436384

https://docs.joomla.org/index.php?title=Portal:Accessibility/UAAG_2.0&diff=477356&oldid=427578

**Comment by Sandra97** [comment]
All content removed because of continuous copyright infringements and not Joomla related content.

**Comment by brianteeman** [comment]
Thank you
