### ISSUE TITLE
[jorg] Offical Joomla! logo

### ISSUE THREAD

**Issue by ChristopherRaymond** [joomla/joomla-websites#112]
Type treatment used instead of the official Joomla! logo in the header region.  
![screen shot 2015-09-02 at 3 35 31 pm](https://cloud.githubusercontent.com/assets/9215367/9642256/287c6106-5189-11e5-8148-d106cbdde160.png)

Sorry if this has been discussed already. Just seemed odd and like a mistake.

**Comment by MAT978** [comment]
Typeface of Joomla! (Asenine Wide) is on its way.

**Comment by mbabker** [comment]
![screen shot 2015-09-02 at 3 56 59 pm](https://cloud.githubusercontent.com/assets/368545/9642637/5420b242-518b-11e5-84cc-074d9ab05f22.png)

That's a screencap of the WIP update.  That is more than efficient for the .org site itself, we'll have to look at how the header can be updated for the subdomains to incorporate the typeface or an actual logo graphic.

**Comment by MAT978** [comment]
@Sandra97 is already playing with it ;)

**Comment by ChristopherRaymond** [comment]
@MAT978 @mbabker Sounds good and the screen grab looks great.

**Comment by mbabker** [comment]
Logo and font added to .org.

**Comment by MAT978** [comment]
merci
