### ISSUE TITLE
No items in the Database Type dropdown on the Database Configuration page (Joomla 4 Alpha 2)

### ISSUE THREAD

**Issue by sy4409** [joomla/joomla-websites#1120]
Just want to report this issue regarding Joomla 4 Alpha Test installation.  On the Database Configuration page, I was not able to select database type.  The drop down is empty.  Here is the screenshot of the issue.
![joomla error](https://user-images.githubusercontent.com/7356376/35777362-bd0ffba2-0a00-11e8-98e4-85f8a78e4fcb.JPG)

**Comment by franz-wohlkoenig** [comment]
Please have a Look at https://github.com/joomla/joomla-cms/issues/18783. The Issue you reported is know, please close the Issue as it is reported on wrong Repository.

**Comment by sy4409** [comment]
Thanks!
