### ISSUE TITLE
Joomla Connect page (remove or update)

### ISSUE THREAD

**Issue by heyjoecampbell** [joomla/joomla-websites#1121]
![1d97b849-6856-4ed1-aebb-5ad4f541363e](https://user-images.githubusercontent.com/8339561/35920378-b15944e4-0be5-11e8-826c-eed41d3a53a1.jpeg)

The Joomla Connect page should be removed or updated with:

- Twitter Feeds
- Official Joomla User Group (Linkedin)
- Facebook page(s)
- RSS Feeds
- Youtube Channel

#jFeedback

Referenced page:
https://community.joomla.org/connect.html

**Comment by Sandra97** [comment]
Joomla Connect has been removed from the top menu of our sites, so I'm closing this issue.
