### ISSUE TITLE
[jforum] access problem with Joomla forum

### ISSUE THREAD

**Issue by dmb0058** [joomla/joomla-websites#1122]
I haven't been able to access the joomla forum since mid-December, and assume it's been hacked to death - is this the case ?

Oddly while no web browser on any device (Samsung S6 phone, Mac, Windows 10 laptop, various tablets) can get to the site, I can wget an index.html from the unix command line ...

**Comment by franz-wohlkoenig** [comment]
This repository is for reporting issues with the joomla.org websites only. Please ask help on the [forums](https://forum.joomla.org/). For this Reason please close this Issue, thanks.

**Comment by pe7er** [comment]
@franz-wohlkoenig The user is having a problem with Joomla forum, this time it is not an issue with forum software in his/her own Joomla site.. :-)

@dmb0058 https://forum.joomla.org/ is working ok for me.
Could you please use https://community.joomla.org/helpdesk/forum-un-ban-request.html to report the issue to the Joomla Forum team? That way they will have the necessary information to investigate the problem. Thanks!

**Comment by franz-wohlkoenig** [comment]
@pe7er thanks for the Hint, haven't read exactly enough - maybe to much snowshipping today.

**Comment by pe7er** [comment]
@franz-wohlkoenig No prob!

**Comment by dmb0058** [comment]
Thanks, have done now.

All the best,

David
