### ISSUE TITLE
Urgent: please help with missing website

### ISSUE THREAD

**Issue by ukturb** [joomla/joomla-websites#1123]
The joomla hosted website
http://www.turbulence.ac.uk/
 for which i am administrator but not owner, has disappeared. this is a major EPSRC funded research page that has just vanished and i would like to speak to a human about it. (the owner is overseas and very slow to respond to emails.
 Does the page need paying for? I was informed we were paid up until May this year. Is the data still available. There is a LOT of work there that has for all intents and purposes vanished.
 please get back to me at aaceu@soton.ac.uk.
 Many Thanks

Richard

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm gonna close this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks

**Comment by ukturb** [comment]
SO the forum doesn't accept my sign on for joomla or ukturb, and i can't see where to go once i get here:
I think i have managed to put something on the CMS site, but can i just be clear, i just want to find out where the whole site has gone, i know nothing about how joomla works, and everyone i have talked to has just sent me on somewhere else. if it wasn't kind of hilarious how ridiculous this is i would be angry. Could you at least please check if [#19666] - Website disappeared, has got to the right place because i'd  really like to get on with some of my other work today? Please?

**Comment by pe7er** [comment]
> SO the forum doesn't accept my sign on for joomla or ukturb,

Could you please use https://community.joomla.org/helpdesk/forum-un-ban-request.html to report the issue with Joomla forum sign on to the Joomla Forum team? That way they will get the necessary information to investigate your sign on problem. Thanks!

**Comment by ukturb** [comment]
Peter,

That’s the first time I think I have got to a page which could lead to help.
THANK YOU!
Seriously I don’t know the first thing about joomla (as is probably very obvious) save occasionally adding an academic paper to the site.
Have submitted request on the link below, so hopefully that should be on the way to be sorted.

Thanks again. Appreciate your concrete help.

Richard
