### ISSUE TITLE
[jforum] - Never Receive Activation Link Upon Registering

### ISSUE THREAD

**Issue by awarner20** [joomla/joomla-websites#1124]
Hi all,

I registered on the forums yesterday and haven't received the activation link as indicated after I registered. Checked spam, etc. Also tried "resend activation email" with no success.

Can you advise? Username was adamwarner

**Comment by Sandra97** [comment]
Hi!
Please report your issue on [this form](https://community.joomla.org/helpdesk/forum-un-ban-request.html) so that the forum team can check.

Thank you!

**Comment by awarner20** [comment]
Done @Sandra97 , thanks! Looking forward to getting more deeply involved:)

**Comment by Sandra97** [comment]
Great!
Please tell me when your issue is solved so that then I can close it.

**Comment by Sandra97** [comment]
I presume this issue is now solved. I'm closing it. Re-open if needed
