### ISSUE TITLE
[jcomm] Just 3 items on home & blogs

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-websites#1125]
Currently, the community site display just 3 latest news items on the homepage and the blog (https://community.joomla.org/blogs.html) shows 3 items as well before the pagination is visible. For news of 10 days ago I already have to browse to page 3. Is this on purpose? Otherwise I would suggest increasing the number of articles on each page a bit :)

**Comment by Sandra97** [comment]
We display 3 articles per page on cjo and jorg, 5 on dev. I agree with you, a bit more than 3 articles per page would be better. I just changed it on jorg to display 5 articles per page as on dev. I'll see with Rowan for cjo.

**Comment by Sandra97** [comment]
I kept 3 articles on cjo homepage but set 5 for the blogs menu item and its sub items.
I'm closing this issue. Re-open if needed.
