### ISSUE TITLE
Kindly assist with belo error

### ISSUE THREAD

**Issue by nicokeed** [joomla/joomla-websites#1126]
Warning: Declaration of IceGroupContent::getListByParameters(&$params) should be compatible with IceGroupBase::getListByParameters($params) in /home/keval/webapps/gulfbm_joomla/modules/mod_ice_carousel/libs/content.php on line 17

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only.  For this Reason please close this Issue, thanks.
