### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by paketos** [joomla/joomla-websites#1127]
I have downloaded Joomla 1.5.26 from here https://downloads.joomla.org/cms/joomla15/1-5-26, and i am trying to upload to my host, however i am getting the following error:
The file you uploaded, Joomla_1.5.26-Stable-Full_Package.zip, contains a virus so the upload was canceled: PHP.chr_encode_mailer.116.UNOFFICIAL FOUND

Can you please check if you have been hacked ?

**Comment by paketos** [comment]
Please check all compressed files, i am getting the same error for all compressed files.

**Comment by mbabker** [comment]
These types of false positives are reported pretty constantly.  There has been no compromise of our packages or their contents.

**Comment by paketos** [comment]
thanx for the quick reply, and sorry for not checking these reports before posting.
