### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by BfdNova** [joomla/joomla-websites#1129]
I have installed joomla on a site http://hlcomputerclub.net/joomla30, and i cant access it as the admin.
![screenshot_20180223-230030](https://user-images.githubusercontent.com/18630359/36625434-73e4dc6c-18ed-11e8-815f-d4dc676c232a.png)

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
