### ISSUE TITLE
[jvols] No search box?

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#113]
I don't know if there is an interest based on the specificities of the site but there is no search box like it is on other JSites.
Thoughts?
Thanks
![reports](https://cloud.githubusercontent.com/assets/1972717/9648956/20344094-51bc-11e5-99df-ee38c750e71e.png)

**Comment by jessicadunbar** [comment]
I use search all the time. +1

**Comment by sanderpotjer** [comment]
The search box (finally...) arrived on volunteers.joomla.org

<img width="1235" alt="screen shot 2016-08-22 at 22 22 23" src="https://cloud.githubusercontent.com/assets/522834/17870257/ef196530-68b6-11e6-9054-3561a47d1c47.png">

**Comment by jeckodevelopment** [comment]
Great news! :beers:
