### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by sidney108** [joomla/joomla-websites#1131]
I just can't log in to Joomla forum with my correct credentials.  How on the earth can I reset my password or get any help here? All my attempts are just hitting a wall, even Facebook messages are not replied?
PLEASE, cod someone contact me on sidney108@gmail.com for reseting anything connected with user sidney108 or zdrska, or anything connected with following emails: sidney108@gmail.com and zdrska@volny.cz
I need some help with Joomla and this just extremely frustrating, as there is no other help then from the forum, which I am just locked of for good...
Thanks!

**Comment by pe7er** [comment]
Could you please use https://community.joomla.org/helpdesk/forum-un-ban-request.html to report the issue with Joomla forum sign on to the Joomla Forum team? That way they will get the necessary information to investigate your sign on problem. Thanks!

**Comment by Sandra97** [comment]
@sidney108 Is your issue solved? Can we close this issue?
