### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by Micco93** [joomla/joomla-websites#1132]
![joomlaerror](https://user-images.githubusercontent.com/36930748/36802970-9ed3158e-1cb6-11e8-9460-cdb5054e6369.png)

Help please, i erased for a mistake the cache and now the page with the slider are broken.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
