### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by alomarib** [joomla/joomla-websites#1134]
Hi there,
I've been trying to enter user manage to add/edit users, but every time facing this message:

An error has occurred.
 500 JM_INVALID_API_KEY (Your request did not include an API key.)

Any help appreciated?

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS so I'm closing this issue.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

If you would like to report an issue with the CMS, please report it at https://issues.joomla.org

Regards,

Thanks
