### ISSUE TITLE
sitelock issues again

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1135]
Looks like we are having problems with sitelock again

1. Its blocking access to the newsfeed in a joomla install
2. many reports on the forums of access to www.joomla.org being blocked

**Comment by genr8r** [comment]
sitelock is blocking joomla.org right now.

**Comment by genr8r** [comment]
and its back online...

**Comment by ssvt** [comment]
This is happening again.
<img width="780" alt="screen shot 2018-04-14 at 9 37 22 am" src="https://user-images.githubusercontent.com/3165234/38769072-047ea826-3fcb-11e8-9c4d-2f202997a46d.png">

**Comment by ssvt** [comment]
FYI, I just tried again and www.joomla.org seems fine but joomla.org is showing the Sitelock screen. I've cleared browser cache.

**Comment by Sandra97** [comment]
Thanks @SiteLockMike.
I'm closing this issue as solved.
Re-open if needed
