### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by SEPWebmaster** [joomla/joomla-websites#1138]
I uploaded a theme to my site and immediately after, i got a " currently unable to handle this request.
HTTP ERROR 500" message.  I can't log in or view the site. What may I do next?

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
