### ISSUE TITLE
No response beside auto to contact form at showcase.joomla.org

### ISSUE THREAD

**Issue by hehemrin** [joomla/joomla-websites#1140]
I submitted a question via the contact form at showcase.joomla.org 16 Jan 2018. I directly got the auto-notification my form was received. No other response after two months. 

Sebastien Lapoux told me (at a LinkedIn group) that there is a problem currently that the receivers of contact form do not get a notification when a contact form is submitted. He suggested I should report this as an issue here as well.

**Comment by sebastienlapoux** [comment]
Thanks a lot @hehemrin ! It has been fixed!
