### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by carlosmanrique** [joomla/joomla-websites#1141]
Hi

I need to wite an ARTICLE but show an error: **500 JForm::getInstance could not load file** 

![errot](https://user-images.githubusercontent.com/18315445/37528697-48957780-2903-11e8-9b70-c178b6a09361.JPG)
Please describe the problem or your issue

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
