### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by arminevergreen** [joomla/joomla-websites#1142]
Dear Sir or Madam,

I've got a problem with my homepage www.evergreenmusic.at/
After some 1 year I tried to log in to http://www.evergreenmusic.at/administrator/ to edit my page. The joomla login-window opens.
It seems like I forgot my password cause none of the ones I tried helped out.
And using the "Forgot password?" or "Forgot username?" links didn't help either because I haven't got a mail so far, although it displayed that the password/username will be sent to armin.rofner@hotmail.com...

Could you please help me. For example by resetting my password/username?

Thanks in advance!

All the Best,
Armin

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

if you find an issue in the CMS, please report it at https://issues.joomla.org/

Regards,

Thanks
