### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ofv1907** [joomla/joomla-websites#1143]
[Anzeigefehler.pdf](https://github.com/joomla/joomla-websites/files/1835316/Anzeigefehler.pdf)

In der Statuszeile vom Backend wird das Akeeba BoU-Symbol incl. Beschreibung nicht korrekt angezeigt.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For your issue, I encourage you to contact directly Akeeba.

For any user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,

Thanks
