### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by atomhbc** [joomla/joomla-websites#1144]
Out of Date Default Joomla Http Response Impedes Ability To Update Website In A Controlled Fashion

The default Joomla http response includes the following:
"Expires: Wed, 17 Aug 2005 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0"

I understand, many browsers, including Chrome, ignores the given cache control directives. Current browsers would accept cache control directive such as the "max-age=10" (max age 10 sec) directive, ensuring that the html code will not be held in the browser cache / proxy server caches longer than 10 sec.

The code that creates the Expires: Wed, 17 Aug 2005 00:00:00 GMT is in the following file:

public_html/libraries/src/Application/WebApplication.php

Below is the pertaining code:
`// If the response is set to uncachable, we need to set some appropriate headers so browsers don't cache the response.
      if (!$this->response->cachable)
         {
      // Expires in the past.
      $this->setHeader('Expires', 'Wed, 17 Aug 2005 00:00:00 GMT', true);
         // Always modified.
      $this->setHeader('Last-Modified', gmdate('D, d M Y H:i:s') . ' GMT', true);
      $this->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', false);`

Because of the default http response, when you update your website, it may not show up in your browser. For example, you update your css file, change the name of your css file from template-1.css to template-2.css and update the name of your css file in the index.php file as well.
However, because the given no-cache directive is ignored by the browser, when you reload the website in your browser, the browser doesn't refresh. It has cached in the html of the website, and in the cached html, the css file is still template-1.css.

Regards,
Tom

**Comment by Sandra97** [comment]
Hi @atomhbc 

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS or third party extensions.

For your issue, please ask at https://forum.joomla.org/

Thanks!
