### ISSUE TITLE
[joomla.org] Newsletter module not working.

### ISSUE THREAD

**Issue by sheetdhumal5dec** [joomla/joomla-websites#1145]
Newsletter module not working on https://www.joomla.org/. It says captcha is invalid, but captcha is missing in the newsletter module.
**Links**:
https://www.joomla.org/about-joomla.html
https://www.joomla.org/core-features.html
https://www.joomla.org/announcements.html
https://www.joomla.org/contribute-to-joomla.html
https://www.joomla.org/media-contact.html

![newsletter module](https://user-images.githubusercontent.com/37770272/38009479-5cbc2f1a-3209-11e8-9e3e-9225a1e0007c.png)

**Comment by Sandra97** [comment]
Thanks  for reporting it. It solved now. 
Please confirm me it's now ok for you so that I can close this issue.

**Comment by sheetdhumal5dec** [comment]
Yes, it is resolved now and it's working fine.

**Comment by Sandra97** [comment]
Thanks! 
I'm closing this issue
