### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by stator100** [joomla/joomla-websites#1146]
Official page, wrong russian translation :
1. Почему и как мигриовать?
2. Сообщить об проблеме

 it's here:
https://downloads.joomla.org/ru/

**Comment by franz-wohlkoenig** [comment]
Can you please give Information about which joomla.org website you talk?

**Comment by Sandra97** [comment]
Hi @stator100 
We are managing all these translations on Crowdin.
Please log in Crowdin to submit your translations. 

- "Почему и как мигриовать?", it's here: https://crowdin.com/translate/joomla-official-sites/524/engb-ru#18683
- "Сообщить об проблеме", it's here: https://crowdin.com/translate/joomla-official-websites-templates/515/engb-ru#22803

**Comment by Sandra97** [comment]
I'm closing this. Translation suggestions have to be done directly on Crowdin.
