### ISSUE TITLE
[jcomm] name missing in dutch part

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#1147]
On https://community.joomla.org/translations/joomla-3-translations.html Dutch translation missing `<a name="nl-nl">` so you can't jump from the top (How to Find a Joomla 3.x Translation) to the translation hitting [Dutch](https://community.joomla.org/translations/joomla-3-translations.html#nl-nl).

**Comment by Sandra97** [comment]
Thanks Martijn.
It works now. 
Please confim so that I can close the issue

**Comment by MartijnMaandag** [comment]
Yes it works, thanks.
