### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by DuncanBolam** [joomla/joomla-websites#1148]
Hi there, 
I am not even sure if I am writing to a public forum or contacting a carbon biped in person. So please do bear with me!
Back in 2013, I asked a website developer to build me a blog in WordPress. Sorry. I know that is probably a dirty word around here! Anyway, s/he managed to persuade me to go down the Joomla route on account of its functionality and progressiveness. Unfortunately, she took my money and broke an agreement to 'be there' for me whilst I settled in to using *my* site and familiarised myself with its inner workings. 
The truth is, I was so disappointed in it, I never bothered. I think it was because s/he was such a pivot-point and I was so let-down by him/her leaving me in the lurch. So, moving onwards and upwards, today I tried logging in to my site to make amends, update it and just work with what I have got. Unfortunately, my u/n and p/w provided by her in her departing email do not work and I cannot access my own site and IP. 
As I have taken such a ludicrously long time to prepare myself to lock horns and bury my Joomla demons, I am gutted by this unexpected setback to say the least. Does it mean my site is hijacked?! 
What can I do to obtain the login details as she has disappeared completely?
Thank you in advance for your assistance. 
Duncan Bolam 
Founder, www.careeradvise.me
ps - my u/n was my email: duncan@careeradvise.me and p/w: ********0sh

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the **joomla.org websites only**. For this Reason please close this Issue, thanks.

**Comment by Sandra97** [comment]
@DuncanBolam You can also give a look to this [tutorial](https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F) and as mentioned by Franz, don't hesitate to ask on the forum.
I'm closing this issue.

**Comment by DuncanBolam** [comment]
Dear Franz and Sandra, 

 

Thank you for your emails. 

 

As this is my first experience of the Joomla and the support / contact us facility offered on the bottom of the website, I do not understand your responses. If by clicking on this link it takes me through to GitHub, what else am I to do but trust the process itself. There is no other information available. 

 

I will take a look at the tutorial. But can you tell me in advance, will it resolve this query? 

 

Regards, 

 

Duncan

Watch Duncan’s short film: ‘ <https://vimeo.com/123841851> Every Person Has A Purpose’

 

Strengthening wellbeing, generating value and sparking greater harmony by dovetailing more people into sustaining careers!

 

Duncan Bolam Dip CG

Coach in: Purpose | Career | Executive | Performance | Motivation | Connector of People & Ideas | Human Capital Consultant | Innovator | Author | Registered Practitioner – Career Development Institute |

 

 

Author of:  <http://www.completelynovel.com/books/every-persons-path-to-purpose-everyones-work-manifesto/read> ‘Every Person’s Path to Purpose – Everyones Work Manifesto’ 

 

Founder/Creator of: TheCareer Dovetail Formula®™

 

Office:           01273 550939
Mobile:          07971 224262
Skype:           duncanbolamlaptop

New Website:  <http://www.careeradvise.me/> www.careeradvise.me

Email:            <mailto:duncan@careeradvise.me> duncan@careeradvise.me 
Blogs:            <http://careersustainability.blogspot.com/> http://careersustainability.blogspot.com/ 

Networks:       <http://www.linkedin.com/in/duncanbolam> www.linkedin.com/in/duncanbolam

Tweets:          <http://twitter.com/careeradvise_me> http://twitter.com/careeradvise_me  

Trading as:    Career Dovetail®™,

Please consider the environment before printing

[We are sorry if this email isn't for you as our intention is to respect everyone’s privacy. We would be grateful if you were to let us know by replying with "Received in Error" in the subject box. If it isn't for you, please understand that copying it, disclosing or distributing any of its contents is prohibited and Career Dovetail©®™ is protected by registered trademark and copyright law. Relating to all electronic content herein, an NDA (None Disclosure Agreement) is implicit regarding all of Duncan Bolam’s intellectual property contained in this email and/or its attachment/s. Our products, services and corresponding intellectual property are explicitly owned by Duncan Bolam trading as Career Dovetail©®™. Career Dovetail©®™ is a Registered Trademark and the property of Duncan Bolam©1998. This email is private and confidential and strictly for the attention of the named correspondent/addressee only. If it isn't for you, please delete it. Many thanks Career Dovetail©®™]

**Comment by franz-wohlkoenig** [comment]
@DuncanBolam have you asked help on the [forums](https://forum.joomla.org/)?

**Comment by pe7er** [comment]
@DuncanBolam I have removed your manual signature from your github message.

**Comment by Sandra97** [comment]
@DuncanBolam The 'Report an issue' button is to report an issue you may find on one of our official websites, like it's mentioned here  https://github.com/joomla/joomla-websites 

For any help about your own website, then the right place to ask is the official forum. You'll find there many people ready to help you.

I can't tell you in advance if the doc will resolve your issue, I don't know your site ;) You should definitely ask for help on the Forum. 
We do not provide support in this repository.
