### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by Daniellep2017** [joomla/joomla-websites#1151]
My website does not allow me to access my for more than for 15 min. We have checked with different service providers and nothing is wrong with our fibre connections. Please help!! I don't know what to do but I need to finish my website. 
![capture](https://user-images.githubusercontent.com/38517748/39034633-6110a4d0-4477-11e8-94ee-c8afc94df159.PNG)

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the **joomla.org websites only**. For this Reason please close this Issue, thanks.

**Comment by Daniellep2017** [comment]
Hi Franz 

 

Thanks for your help. 

 

Have a great day.

 

Warm Regards
