### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by wilshire5000** [joomla/joomla-websites#1152]
Hello,
Can someone reset my JomSocial forum user ID, for this site, https://www.joomla.org/?

I can't log into JomSocial forum because I can't remember my user ID. I can't send reactivation email because I can't remember my user name. I also don't remember my password. I need my user name to reset it. 

Thanks,
Louis Green
wiLshire5000@hotmail.com

**Comment by mbabker** [comment]
Hi,

There is not an active install of JomSocial on our joomla.org subdomains, so there is no account to reset.

If you mean an account on the Joomla Forums please use the form at https://community.joomla.org/helpdesk/forum-un-ban-request.html for assistance.
