### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by 73829** [joomla/joomla-websites#1153]
![captura de pantalla 324](https://user-images.githubusercontent.com/38574662/39078750-8d84d32c-44d3-11e8-989f-fd0257a0c871.png)
Estoy elaborando un proyecto estudiantil, una pagina e-commerce .
Me aparece ese error ;c ayúdenme por favor, al momento de enviar el mensaje pre-establecido me dice eso, como lo soluciono por :lying_face:

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the **joomla.org websites only.** For this Reason please close this Issue, thanks.
