### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Rewillis** [joomla/joomla-websites#1154]
Attention: Joomla.com staff:
     This morning I have created an entry in my joomla.com weblog ( username = "Rewillis1," if I remember correctly ).  However, I am currently unable to save and publish that weblog entry.  Thank you ( see Colossians 3:15, for example ) for your help.  Keep in touch.

Sincerely in Christ,
Russell E. Willis
P.S. - Please read Proverbs 23:23.

**Comment by Sandra97** [comment]
Hi, 
joomla.com will be soon replaced by a new service, launch.joomla.org
You can see more information here (the link is available from joomla.com homepage): https://www.cloudaccess.net/fresh/blog/entry/2018/04/17/an-exciting-glimpse-at-the-new-launch-joomla-org.html
