### ISSUE TITLE
[jhelp] Joomla 4 help buttons go to error page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1155]
Joomla 4 help buttons go to links like

https://help.joomla.org/proxy?keyref=Help40:Users_User_Manager_Edit&lang=en

which gives CONNECTION CLOSED

Would be better to redirect to https://help.joomla.org/ so that the offline message could be displayed

**Comment by mbabker** [comment]
This has nothing to do with J4.  Looks like there's a server error in general.

**Comment by PhilETaylor** [comment]
:-) over to you then :)

**Comment by mbabker** [comment]
Server up.

**Comment by brianteeman** [comment]
Closed
