### ISSUE TITLE
1054 Unknown column 'c.metatitle' in 'field list'[jhelp] 

### ISSUE THREAD

**Issue by hnokristian** [joomla/joomla-websites#1158]
I have tried to correct the database of my Joomla website and I could not. I get this message 

> 1054 Unknown column 'c.metatitle' in 'field list'

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
