### ISSUE TITLE
[jconf] I really want to know what Tessa enjoys...

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-websites#116]
The entire text does not appear with the :hover, and I would really like to know what Tessa enjoys ;)
https://conference.joomla.org/speakers

![sanse](https://cloud.githubusercontent.com/assets/1972717/9686491/3c3dfdac-52f2-11e5-90a1-252f07782dd1.png)

Thanks

**Comment by brianteeman** [comment]
Works for me

![9j1](https://cloud.githubusercontent.com/assets/1296369/9686626/c38add6e-531c-11e5-91d7-6f65261ae19e.png)

**Comment by jneubauer** [comment]
as already mentioned, it is working correctly.

**Comment by jneubauer** [comment]
that should fix it ;)

**Comment by Radek-Suski** [comment]
I see also some JavaScript error: 

`TypeError: a(...).tooltip is not a function`

**Comment by Sandra97** [comment]
Display is now of course correct.

**Comment by Sandra97** [comment]
Also some little responsive dislay issue for screen between 481px and 991px

**Comment by brianteeman** [comment]
Still broken at 1024px
