### ISSUE TITLE
[jcertif] White Page - File to download

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1160]
Seems something goes wrong with the site.
I have a white page and pop-up to download a file.

**Comment by conconnl** [comment]
Which page and browser?

**Comment by Sandra97** [comment]
Firefox, Chrome, Edge for the homepage. All is fine now, it doesn't happen anymore.

**Comment by conconnl** [comment]
Strange let’s keep an eye on the website. A lot is changing.
