### ISSUE TITLE
Privacy & Cookies Policy Update

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1161]
Some of us didn't have any other option than working on an update of the Privacy Policy to try to fill the GDPR requirements in time. 

I've just published it: https://www.joomla.org/privacy-policy.html

If anyone wants to help improve it, to complete it, please feel free to do it.

**Comment by mandville** [comment]
is there a central form for requests (sar, restriction, removal)

**Comment by Sandra97** [comment]
Yes: https://www.joomla.org/right-to-be-forgotten.html
The link is available from the Privacy Policy page.

**Comment by mandville** [comment]
thanks, the lower half of that form looks jumbled and offset

**Comment by mbabker** [comment]
Is there anything actionable here or is this one of those "if you have any bright ideas please share them" type of deals, because if it's the latter I doubt you're going to get those.

**Comment by Sandra97** [comment]
I'm in the Compliance Team so when edits will be needed, like for the cookies policy, I will be informed, so we can close this issue.
