### ISSUE TITLE
[jdocs] Search for FAQ

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1162]
If you try to search for FAQ on the docs site you dont get search results instead you get redirected to the default mediawiki FAQ page

![faq](https://user-images.githubusercontent.com/1296369/40480143-7bd023ac-5f45-11e8-9303-2bb39dbce0a7.gif)

**Comment by Sandra97** [comment]
@Hutchy68 Can you help with this?

**Comment by Hutchy68** [comment]
I'll look into it. Must be a redirect in htaccess. We have https://docs.joomla.org/index.php?title=FAQ&action=edit set as a redirect to FAQs. I'll try to get to this today.

**Comment by Hutchy68** [comment]
This is fixed now. Clear your cache if you are still going to the bare page.

**Comment by brianteeman** [comment]
thanks
