### ISSUE TITLE
Random Module problem

### ISSUE THREAD

**Issue by fanvirk** [joomla/joomla-websites#1163]
I have a web site  - www.irfanvirk.com - on which I have a random module. This used to work well. However, after I updated the site yesterday, the random module is generating a fatal error:

Fatal error: Using $this when not in object context in /homepages/45/d517594501/htdocs/ivjoomla/modules/mod_random_image/tmpl/default.php on line 16

If I unpublish the random module, the site runs - without the random images; if I publish the random module, I get the fatal error.

Any advice on how to address this would be appreciated.

Irfan Virk

**Comment by mbabker** [comment]
Just for the sake of completeness, even though this is already closed, known issue with https://docs.joomla.org/J3.x:Module_random_image_PHP_Error_after_3.8.8 explaining it.
