### ISSUE TITLE
[jhelp] Most of our redirects stopped working today

### ISSUE THREAD

**Issue by GC-Goteborg** [joomla/joomla-websites#1164]
Some redirects in Joomla just stopped working. Some are still working tho, cant find any pattern..

Do you know?

**Comment by Sandra97** [comment]
What are you talking about? Your own website?

**Comment by GC-Goteborg** [comment]
Hi.

Yes exactly








Viktor Osberg
Gokartcentralen

031 - 15 15 18

--- original message ---
On Fri, May 25, 2018 at 12:37 pm, <notifications@github.com> Sandra Decoux wrote:


What are you talking about? Your own website?

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by Sandra97** [comment]
So that's not the right place to ask for help as this repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For your issue, I encourage you to ask on https://forum.joomla.org/

Thanks.

**Comment by GC-Goteborg** [comment]
Hi,

I pressed "Help" and then "Report an issue" under the "Redirect" section of our joomla page. 










Viktor Osberg
Gokartcentralen

031 - 15 15 18

--- original message ---
On Fri, May 25, 2018 at 01:50 pm, <notifications@github.com> Sandra Decoux wrote:


So that's not the right place to ask for help as this repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For your issue, I encourage you to ask on https://forum.joomla.org/

Thanks.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by mbabker** [comment]
The "report an issue" links are solely for reporting issues regarding the `joomla.org` websites and their content.  The help screens come from our servers hence the reason the link is there, but I will change the text to make it more clear that it is NOT for support issues with user websites.

**Comment by zero-24** [comment]
Closing for the reasons stated above :)

Please ask on https://forum.joomla.org/ when you still need help thnanks!
