### ISSUE TITLE
[jcertif] php rendered as text

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1165]
the certification site is currently being rendered as text

<img width="684" alt="chrome_2018-05-25_20-34-44" src="https://user-images.githubusercontent.com/1296369/40563024-35eabf84-605b-11e8-9b56-156b6f2a73ed.png">

**Comment by conconnl** [comment]
I really don't know why this sometimes happens.
At this moment I don't see an issue anymore.
Just after Paris it happened as well for a short while.

**Comment by Sandra97** [comment]
As the site seems to be ok since a while, I'm closing this issue.
Re-open if needed.
