### ISSUE TITLE
Losing hyperlinks

### ISSUE THREAD

**Issue by CommManager** [joomla/joomla-websites#1166]
I put numerous hyperlinks into various articles, which I tested and all worked as expected. 1 week later all the links had gone. When I pass the mouse over the links they become underlined but clicking on them achieves no result. In 3 articles I have put in bookmarks and then linked them to a hyperlink in a contents list. The bookmark is still showing but the hyperlink isn't jumping to it. I replaced some of them, but the same happened again.

What is happening and how do I prevent losing the links again?

Christine Bibby
Communication Manager
SeniorNet Glenfield
www.seniornet-glenfield.org.nz

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Thanks!
