### ISSUE TITLE
[jdown] Wrong button padding on Joomla! Downloads pages

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-websites#1167]
### Steps to reproduce the issue

Open Joomla! Downloads pages in Chrome (for example, [https://downloads.joomla.org/cms/joomla3](https://downloads.joomla.org/cms/joomla3)).

### Expected result

Download/View files buttons had padding

### Actual result

Buttons have no padding

### System information (as much as possible)

Windows 10 x64
Chrome - last version

### Additional comments

Ok, I think it's maybe not Joomla! site css's problem, but "problem" with akeeba/release-system. Anyway, this style "problem" has very low importance. or it makes no sense. )

Download/View files buttons had padding in the past.
![screenshot 2018-05-29 at GMT+3 10:36](https://camo.githubusercontent.com/bb2920648062ae3370cd33bffd55e8bd0c6af364/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f66383636663033363731663135646632313635366263323161396465353362342e6a7067)
![screenshot 2018-05-29 at GMT+3 10:36](https://camo.githubusercontent.com/68fb95043cda076bef04ebdea3ec927a63735774/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f65666536626638313538313564633164646335363264663937363833343239662e6a7067)

**Comment by AndNovAtor** [comment]
Sorry for posting this to issues.joomla.org....

**Comment by Sandra97** [comment]
It's the right place to post it @AndNovAtor and thanks for noticing.

It should be displayed like this: 
![index](https://user-images.githubusercontent.com/4682328/40652139-b9584740-6337-11e8-996d-f459b993358e.png)

I'll check what's going on and correct the display.

**Comment by AndNovAtor** [comment]
Em, `reset.min.css:10` with `.akeeba-renderer-fef a` override template style for `.btn` in `template_2.3.0.min.css`. As I see....

**Comment by AndNovAtor** [comment]
Oh, these reset.css's....

**Comment by mbabker** [comment]
Fixed.  The Akeeba FEF CSS is unloaded on our frontend because it conflicts with our template's design, the `reset.min.css` was added after we updated so had to add that to the unload list.
