### ISSUE TITLE
[jshop] Service hours: Mon-Fri, 8am-5pm?

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1168]
At the bottom of the shop pages https://community.joomla.org/the-joomla-shop.html it says

Service
+353 1 4373 651
(Mon-Fri, 8am-5pm)

+353 = Ireland, so I suppose that the service hours are between 8am-5pm in Ireland.
For non EU visitors it might be confusing.
Maybe we could add the timezone "UTC+1 hour" ?

(Mon-Fri, 8am-5pm UTC+1 hour)

**Comment by Sandra97** [comment]
I'm sorry but this can't be edited at all. It's managed by Spreadshirt only.
I'm closing this issue as there's nothing I can do (at least as long as we have a Spreadshirt shop)

**Comment by pe7er** [comment]
Ok, I understand. No problem!
