### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by divadgo** [joomla/joomla-websites#1169]
Good afternoon, I'm José Luis Gordillo Mimbrero, director of the company GOMINTEC S.L. with NIF B-64215643 some years ago we hired an external company to take care of our website "www.gomintec.com" After several years this company has disappeared and it has been impossible for us to get in touch with it. The problem is the following one, we have to make changes in the web for the subject of the policy of privacy and for the ISO policies and our new contracted company needs to access JOOMLA to be able to make the changes that I comment to them.
I would be grateful if you would respond to our request as soon as possible since it is of vital importance to us.
If you need to contrast some type of information, please, please contact me through email or through my phone number.
Email: david@gomintec.com
Telephone number: +34639443428

Thank you very much.
A greeting.

**Comment by mbabker** [comment]
Hi there,

The Joomla project does not actively host or support sites using our software beyond responding to bug reports and feature requests in the core software itself.

For your scenario I can recommend a couple of options:

- Using the community forums at https://forum.joomla.org to discuss your issue and finding potential solutions to it
- Finding a service provider from our resource directory at https://resources.joomla.org that can provide direct assistance on your issue
