### ISSUE TITLE
Delete the invalid report ID 831

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1173]
I broke the volunteers' reports.... I don't know how it created a report without a team. Please, delete the report ID 831. https://volunteers.joomla.org/831-jed-team-meeting-june-8th-2018

I don't know how it happened.... this is the sequence:

- I created this report without problem  https://volunteers.joomla.org/teams/extensions-directory-team/reports/830-jed-team-sprint-j-and-beyond-may-11th-2018
- When I tried to submit a second report, it failed with 404 (... and I lost what I wrote)
- Then, I rewrote it to create the invalid ID 831.
- Then, I recreated the report again, and it works OK creating the report ID 832.

**Comment by sanderpotjer** [comment]
@anibalsanchez the incorrect report is deleted. We will look into reproducing the issue and see if we can fix it. Thanks for letting us know!

**Comment by anibalsanchez** [comment]
Great. Feel free to close it if it is no longer an issue.
