### ISSUE TITLE
[jdocs] Documentation about creating custom 404 error page is outdated

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-websites#1174]
The following page is outdated:
https://docs.joomla.org/Creating_a_Custom_404_Error_Page

To be more specific, The Step 4 is outdated. 
There is no 'restricted access' line in  /templates/system/error.php (J3.8.8)

**Comment by mbabker** [comment]
The "restricted access" line is the defined or die check.

The advice on this page is bad anyway.  This actually results in a 404 error issuing a 302 redirect in the browser to a page you've specified (which will be a 200 response).  So at no point does the site ever actually give a 404 response.

**Comment by Sandra97** [comment]
@sshcli JDocs is a wiki, meaning everybody can contribute to it and update the content. Would be great if you can update the page

**Comment by Sandra97** [comment]
If someone wants to update the page, go for it. 
I'm closing this issue.
