### ISSUE TITLE
No Activation email sent when trying to join the Joomla Forum 

### ISSUE THREAD

**Issue by osmoot** [joomla/joomla-websites#1175]
I have followed the activation instructions five times. I never get an email. I have since spent about an hour trying to find anyone to communicate this problem to. There appears to be no Board Administrator publicly available. The situation is Kafkaesque as every attempt to communicate that I cannot register is met with a demand to register.

**Comment by Sandra97** [comment]
Hello,
To join the forum's admins, please fill this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by jeckodevelopment** [comment]
@osmoot i hope that it has been solved.
If not, please feel free to reopen.

Thanks
