### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by StitchCraft** [joomla/joomla-websites#1176]
I was banned from the Joomla forum as being spam.  I have a website using Joonla and I don't understand.

**Comment by Sandra97** [comment]
Hello, 

I invite you to contact the forum's admins by filling this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by Sandra97** [comment]
Closing this issue. 
@StitchCraft If your problem is not solved, please use the form mentioned above. Thanks
