### ISSUE TITLE
SP Contact Module 

### ISSUE THREAD

**Issue by martinriver** [joomla/joomla-websites#1177]
Hi
Despite having configured an SMTP mail from Global Configuration in Joomla, an email admin in my domain, even when testing from there, the emails arrive at destination, but when I test from the contact module, and even appearing a message from that the mail was sent successfully, the emails do not arrive. The SP Quick contact module has the same admin mail, but the mails can not reach the destination. Will there be a configuration theme in the template or permissions? Why does it work well from a global configuration, but not from the Contacts module (SP Quick contact)?

The template has the latest version of joomla. 3.8.8

Thanks in advance for any assistance.

Martin

**Comment by Sandra97** [comment]
Hi Martin,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS or third party extensions.

For your issue, please contact Joomshaper or ask at https://forum.joomla.org/


Thanks!
