### ISSUE TITLE
[jhelp] Joomla > Extensions > Manage > Update Site

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-websites#1178]
Hi guys, 
Joomla 3.8.10 going to Extensions > Manage > Update Site: and clicking on "Help" 

I have back the error page:

RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist

Is it normal ?

**Comment by brianteeman** [comment]
It is not normal BUT it is also not unique to you ;)

@Hutchy68 @Sandra97 can you check and create the page please

**Comment by mbabker** [comment]
Probably better to rename the page at this point, the key in the CMS language files is different from the page on the docs site, and always has been.

Correct: https://docs.joomla.org/Help38:Extensions_Extension_Manager_Update_Sites

What tries to be loaded: https://docs.joomla.org/Help38:Extensions_Extension_Manager_Updatesites

**Comment by Sandra97** [comment]
No more error now but I need @Hutchy68 to redirect it to the right help screen

**Comment by mbabker** [comment]
The redirect's fine.  The pattern that the help proxy app was trying to match to follow redirects has changed from whenever that code was originally written, https://github.com/joomla/help.joomla.org/commit/c04cbcf668888b0412873f1b7e886453137d5269 fixes that and the change is live on the server now.

**Comment by joomleb** [comment]
Hi guys, 
thanks for the quick fix, the link is running.
But the documentation is lacking = nothing about Update Sites > Rebuild button feature.

I looked for it around and the only information I found are:
https://github.com/joomla/joomla-cms/issues/8512
https://www.itoctopus.com/the-rebuild-button-in-joomlas-menu-manager-page-a-double-edged-sword

Hooping can be useful to build a documentation page...

**Comment by Sandra97** [comment]
Thanks! Many help screens still need to be updated. I'll try to update this one during the weekend. 
If you want to help us update them for the benefits of all, do not hesitate and join us (I have cookies).

**Comment by Sandra97** [comment]
"Rebuild" added to the Help Screen. Note that the link you provided is for the Rebuild button of the Menu Manager (so a different help screen) and not the one of the Update Sites.

**Comment by Sandra97** [comment]
I'm closing this issue as it's solved.
