### ISSUE TITLE
[jvel] {ttweet}{fsubscribe} not replaced with connect content

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-websites#1179]
Hi 
In single entry view of Live VEL and Resolved menu items `{ttweet}` and `{fsubscribe}` are not replaced with correct HTML.
Sample link: https://vel.joomla.org/resolved/2117-prayercenter-3-0-2-sql-injection

**Comment by Sandra97** [comment]
Thanks for the report;

@mandville Could you give a look please?

**Comment by mandville** [comment]
This possibly only affects historical listings as the previous plug in was  it php7 compatible.
It does bit detract from listings. It is not  a bug.

**Comment by brianteeman** [comment]
Of course its a bug - if its not the intended display then its a bug.

**Comment by ot2sen** [comment]
When it is roughly 395 of 397 listings then it does detract a bit. Should be worth to run a query to remove the now unused plugin tags, or use Peters DB Replacer to quickly get rid of them all if that is more convenient.

**Comment by mandville** [comment]
Couldn't locate the figure quoted by ot2sen

**Comment by ot2sen** [comment]
Was just a rough guesstimate of live+resolved-(2 latest after 22th of May that was ok) :)
Looks like I was 41 off in the rough guess 354/356, but hey ...hehe. Seems like it is corrected by now which is the important part. Nice.
