### ISSUE TITLE
[jdev] Strange links generated by the shortener 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#118]
Any idea where this is coming from ?
![screen shot 2015-09-09 at 10 15 37](https://cloud.githubusercontent.com/assets/1110663/9756624/fc485aa6-56db-11e5-9362-e45dfcf32842.png)

**Comment by mbabker** [comment]
Your guess is as good as mine.  .77 is the dev site's IP and .76 is the server.

**Comment by Radek-Suski** [comment]
well, not that important. Just wondering ;)

**Comment by jessicadunbar** [comment]
is the developer site on a shared server or something? http://www.syest.net/

**Comment by mbabker** [comment]
It's on our own MVS with Rochen.
