### ISSUE TITLE
[jed][jshow][jforum] bad linking to launch site

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-websites#1180]
Hi
I checked to witch demo site we linking across j.org subdomains. Below are subdomains with error  - I always referring the button in top-right corner of the website.
|https://extensions.joomla.org/| - link to the old SG demo site|
|https://showcase.joomla.org/|  - link to the old SG demo site|
|https://forum.joomla.org/|  - typo in the demo site url|

**Comment by mbabker** [comment]
The forum's updated.  The other two sites still need to roll out the template updates (which is more than changing the button text/link).

**Comment by jonathanCA** [comment]
It looks like the issue persists, we are also seeing that demo.joomla.org no longer redirects to launch.joomla.org

**Comment by jonathanCA** [comment]
Just following up here - those links are fixed, only thing that remains (that we're aware of) is demo.joomla.org does not forward to launch.joomla.org

**Comment by jeckodevelopment** [comment]
> demo.joomla.org does not forward to launch.joomla.org
It does now. So closing this.

Thank you
