### ISSUE TITLE
Forget Password

### ISSUE THREAD

**Issue by ammarputin** [joomla/joomla-websites#1181]
Hello, 
I have a problem with rest password, i want to edit my website by accessing the admin panel but i forget the password and i tried to reset it but they told me to contact with the super admin 

This is my website i created www.putin.org.ps, and this is the e-mail "support@putin.org.ps" 
please contact me ASAP

Thank you.

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
