### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by jpokhrel1** [joomla/joomla-websites#1183]
I started to creat a website named: www.monamima.joomla.com but it is not open, why? 
and when I went through log in as administrator by entering: www.monamima.joomla.com/administrator/
and I supplied my log in username and password but it was not opened, instead its remained the same.
could anyone help me?

**Comment by hvdmeer** [comment]
Your joomla.com website is a subdomain. So don't use the www!
http://monamima.joomla.com/

Also, this is the place for issues with our own properties. If you encounter problems with a joomla.com subdomain you can send a ticket in the control panel at https://ccp.cloudaccess.net/clientarea.php

**Comment by jpokhrel1** [comment]
Hello there!


I also tried to log in through the link you provited:
http://monamima.joomla.com and its not open. after click the button 'log
in' its replace the url as:
http://monamima.joomla.com/index.php

but i didn't log in as administrator portal.

please resolve the issue.

**Comment by jonathanCA** [comment]
Hi there, 

We are thrilled that you are learning and building a new Joomla site. I'd recommend checking out https://community.joomla.org/joomla-training.html to get started. This will lead you through the differences between logging in through the front end vs back end (administrator).  I see the site has been modified a bit now so it's likely you already have this sorted :) 

Cheers

**Comment by jpokhrel1** [comment]
hello again,

but why my lo in is unsuccessful?

**Comment by Sandra97** [comment]
To login to your backend go to
http://monamima.joomla.com/administrator/

**Comment by mandville** [comment]
jpokhrel1 
the website ( a subdomain of joomla.com ) is free BUT it has limitations.
it is designed to learn joomla along with the videos here https://www.cloudaccess.net/joomla-knowledgebase/138-joomla-3-1/getting-started.html
Having a " www " is no longer a requirement. 
this github is for technical issues with websites. your website is acting as it should. please now go to https://forum.joomla.org/viewforum.php?f=805 for dedicated volunteer support and links
you may find it easier to converse in your own language at https://forum.joomla.org/viewforum.php?f=511

**Comment by jpokhrel1** [comment]
hi  there,
i could not log in my site http://monamima.joomla.com
it says"
×Warning
Unable to connect to authentication service."


what that mean? please reply me.

**Comment by jonathanCA** [comment]
Hi jpokhrel1, we'd really like to help you, but this is not the appropriate place to get support for your Joomla website. Please create an account and post to forum.joomla.org. 

Thank you
