### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jpokhrel1** [joomla/joomla-websites#1185]
I am facing to problem to log in. my username and password is already save in google chrom. hence its appear automatically in the log in section. when I click lig in, it says
"×
Warning

Unable to connect to authentication service."
please advice.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.
