### ISSUE TITLE
[jforum] No activation email sent

### ISSUE THREAD

**Issue by maxsenft** [joomla/joomla-websites#1188]
I registered the user "maxsenft" with my email address ...@gmx.de. I did not receive an activation email and even after using the resend function, I did not receive any. Nothing in my spam folder, or similar.

When trying to login I get the message "The specified username is currently inactive. If you have problems activating your account, please contact a board administrator." but unfortunately, the "The team" link can only be accessed as registered and logged in user ... I feel a little bit "dead locked". ;-)

Hope someone could help me ...

**Comment by mandville** [comment]
try https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by maxsenft** [comment]
I gave it a try. Let's see what happens next ...

**Comment by maxsenft** [comment]
I just used the [Resend activation email](https://forum.joomla.org/ucp.php?mode=resend_act) function again without success ...
And there was no reaction yet to my message via the "Forum Account Support Form" ...

**Comment by maxsenft** [comment]
Registered "max_senft" with another email address hosted by Google. That worked now ...

**Comment by Sandra97** [comment]
Thanks. I'm closing this issue as you fixed it.
Re-open if needed.
