### ISSUE TITLE
JED Image loading issue in Asia/Pacific

### ISSUE THREAD

**Issue by AbhishekDas** [joomla/joomla-websites#1189]
JED (https://extensions.joomla.org) seems to be having some image loading issue when accessing from **Asia/Pacific** region like India, Vietnam etc. Visitors from the region can not see extension's logos and images. It works fine for other regions like Europe, North America etc. 

It seems like a CDN server problem for the region. Image urls like -https://extensionscdn.joomla.org/cache/fab_image/57892a91d9971_resizeDown960px420px16.png all generating 404 error.

Probably the cache of the CDN needs to be cleared. Can anyone check this?

**Comment by hvdmeer** [comment]
Just spotted another post about this issue in our FB joomla group. Who can help on this?

**Comment by brianteeman** [comment]
and here in the forum https://forum.joomla.org/viewtopic.php?f=706&t=963773&p=3532629

**Comment by anibalsanchez** [comment]
Our hosting provider has checked the issue and it is now loading OK from several Asia/Pacific ISPs.

Please, confirm if the issue is still active on your end.

**Comment by jeckodevelopment** [comment]
@AbhishekDas did you purge your cache?

**Comment by AbhishekDas** [comment]
Yes, I cleared cache. Works fine if I use US or Europe VPN.

Refer the below screenshot for the exact errors displayed in the browser's console. 

![jed-image-issue](https://user-images.githubusercontent.com/2259108/42943583-c9dc40b4-8b80-11e8-8db3-ef837790239e.png)

**Comment by anibalsanchez** [comment]
Rochen support has been able to reproduce the issue and they are investigating this presently.

**Comment by AbhishekDas** [comment]
@anibalsanchez That sounds good.

**Comment by anibalsanchez** [comment]
An IP filter has been cleared for Asia Pacific zone. Now, the CDN is showing 200 OK responses from the affected point of presence. 

Please, re-check it now.

**Comment by AbhishekDas** [comment]
Yes, it is working fine now. 

Closing the issue.
