### ISSUE TITLE
EMAIL ADDRESS CHANGE

### ISSUE THREAD

**Issue by TheGrayCat-105** [joomla/joomla-websites#119]
FOLKS --

OLD EMAIL ADDRESS: <<tmc1@execpc.com>>
NEW EMAIL ADDRESS: <<tmc@att.net>>

PLEASE CHANGE THIS.
YOU HAVE NO WAY PROVIDED FOR MY DOING THIS!

**Comment by mbabker** [comment]
Not sure what platform/site you are referring to specifically but every joomla.org site with a front-end login has the ability to update your own user profile, to include e-mail addresses.
