### ISSUE TITLE
There is a 20-30px space at two sides of listing images on JED

### ISSUE THREAD

**Issue by JoomlaTema** [joomla/joomla-websites#1191]
There is a 20-30px space at the two sides of listing images.  Listing preview images has been wrapped around before. Now it seems that a 20-30px space between image and two sides.

**Comment by anibalsanchez** [comment]
For future reference, same note here:

> The current template is the result of several accumulated design changes (from 2014 to the date). Several volunteers have tried to solve the current design issues and settled on the current compromise. I think it can only be finally solved with a full review of the design, and the final solution will come with Joomla 4 and JED 4.

**Comment by Sandra97** [comment]
As all issues regarding JED should be posted and discussed here: https://github.com/joomla/jed-issues
I'm closing this issue.
Re-open if needed.
