### ISSUE TITLE
[forum.joomla.org] Performance

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1192]
For the last week or so the performance of the forum has been really bad. It is ok when searching and browsing. the problem is when you post a reply - it takes a very long time.

/me wondering if some anti-spam measure has been updated and thats taking a long time to process?

**Comment by mbabker** [comment]
They're doing an update tomorrow.  Maybe that'll help.

**Comment by brianteeman** [comment]
still painfully slow post update

**Comment by Sandra97** [comment]
@brianteeman Is it still painfully slow?

**Comment by brianteeman** [comment]
Seems to be better now
