### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by rudiroux** [joomla/joomla-websites#1193]
Afrikaans Language file. There is a spelling mistake in the sentence when there are no articles to show.

"Daar is Geen Artikels in hierdie kategorie nie. Indien daar sub-kategorië op hierdie bladsy verskyn, kan hulle moontliks artikeks bevat."
It should read: Daar is Geen Artikels in hierdie kategorie nie. Indien daar sub-kategorië op hierdie bladsy verskyn, kan hulle moontlik artikels bevat.

**Comment by Sandra97** [comment]
Please contact the Afrikaans coordinator to report the spelling mistake: gerrit (at) hoekstra.co.uk

**Comment by Sandra97** [comment]
Closing this issue.
Re-open if needed.
