### ISSUE TITLE
[jforum] Site template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1194]
Since the upgrade to the forum the joomla site template is not present and there are CSP errors

**Comment by Sandra97** [comment]
@ooffick Could you check, please?

**Comment by ooffick** [comment]
Not sure, it seems to be OK to me. Tobias looked at some csp rules as well.

Brian can you check if this is OK by now? 

Kind regards
Olaf

**Comment by brianteeman** [comment]
Seems to be ok now
