### ISSUE TITLE
[jforum] Breadcrumbs

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1195]
Since the upgrade a bug has returned with the forum breadcrumbs (iirc Rowan fixed this before)

![breadcrumbs](https://user-images.githubusercontent.com/1296369/43062839-07793a34-8e52-11e8-8cef-852a6e08bec7.gif)

**Comment by brianteeman** [comment]
see #907

**Comment by Sandra97** [comment]
@ooffick Could you check, please?

**Comment by ooffick** [comment]
Thanks, I will look into it.

**Comment by brianteeman** [comment]
The solution is in #907

**Comment by ooffick** [comment]
OK, I will look into it

**Comment by ooffick** [comment]
Can you check if this is still the case, as I just had a look and I cannot see this behaviour? If you can still see it would you mine sharing your Browser width, zoom level and browser version? Thank Brian.

**Comment by brianteeman** [comment]
Yes its a weird one and took @Joomv and me a while to sort it out last time

https://mybrowser.fyi/report/5b60517f9310a900144b3ffa

**Comment by ooffick** [comment]
OK, I was just able to replicate it when using a zoom factor of 67%.

Let me see what I can do about this.

Kind Regards
Olaf

**Comment by brianteeman** [comment]
Confirmed that its all working now.

Might be worth making a note about this change to prevent another update overwriting it

Thanks
