### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by jondhill** [joomla/joomla-websites#1196]
I tried to register for the forum, but it appears that the captcha isn’t working. I get these errors:

allow_url_fopen=0
[phpBB Debug] PHP Warning: in file [ROOT]/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4517: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3268)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4517: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3268)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4517: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3268)

The registration page says this afterwards:
![image](https://user-images.githubusercontent.com/24628374/43169282-21281346-8f66-11e8-95fe-0e43ff4da2ee.png)

The link to the "board administrator" is a do-not-reply address, so here I am.

**Comment by jondhill** [comment]
Done. Thank you!

**Comment by Sandra97** [comment]
Thanks. I'm closing this issue.
