### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by edwardgraceinteriors** [joomla/joomla-websites#1198]
www.edwardgraceinteriordesign.co.uk has disappeared. I have been trying to get Waltham Websites who manage my account to sort out the problem for weeks, however they are not responding to my phone calls and only giving me limited information via email. I am very concerned, can you help please?

Linda Treacy
Owner

**Comment by brianteeman** [comment]
I am sorry but there is nothing that we can do to help you. Joomla is just software and noth8ing to do with the hosting of your website.

However I did do a basic check on the domain name and it shows that there is no such domain name registered

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/

Thanks

**Comment by edwardgraceinteriors** [comment]
Brian

 Many Thanks for you response it was kind of you to take the time.

I have recently paid my webpage manger for two domain name renewals for both edwardgraceinteriordesign.co.uk and interiordbsigner.co.uk also a SSL for one year and a hosting fee.

Does this mean that the domains have not actually been renewed?

Linda

**Comment by brianteeman** [comment]
yes it does. both of those domains are available for anyone to register at this time

**Comment by edwardgraceinteriors** [comment]
Thank You

**Comment by edwardgraceinteriors** [comment]
Hi 
I hope you don’t mind me contacting you again. I am still having trouble with my website

https://www.interiordesigneressex.co.uk

Please have a look at it, my front page has gone and your logo is there?

My webpage manager, Waltham Websites has been very difficult to contact and when finally she replied to my email, her phone number no longer works.Please see her words to me below, I would appreciate your comments, is it true?

I will be moving my website to another manager and wondered how to go about this, I cannot get into the administration page any more either, can you help me?

 I paid her for my domain names and hosting, Feb 2018-2019)  and SSL for a year on the 31st May 2018, however I feel now that she is just not being honest with me.

Thank You in advance

Linda


Hi Linda, 

I am so very sorry for the lack of communication again.  
Your website is always going to get hacked now, from experience once they have been once they just keep coming back unfortunately.  Joomla is completely out of fashion because it is insecure to hackers now.  Websites are constantly changing and this is a big change in the industry.  

So by way of apology I can redo your website tonight for £199.  

Please choose a template you like and I will use all the current images and text on your new site unless you have new images?

https://www.squarespace.com/templates/ <https://www.squarespace.com/templates/>

Please check out the pricing (there will be no hosting charges from me anymore) and you will never get hacked again.

Pricing https://goo.gl/EVQSXZ <https://goo.gl/EVQSXZ>

Kind Regards 

Fay x

**Comment by edwardgraceinteriors** [comment]
Hi Brian

I hope you don’t mind me contacting you again. I am still having trouble with my website

https://www.interiordesigneressex.co.uk <https://www.interiordesigneressex.co.uk/>

Please have a look at it, my front page has gone and your logo is there?

My webpage manager, Waltham Websites has been very difficult to contact and when finally she replied to my email, her phone number no longer works.Please see her words to me below, I would appreciate your comments, is it true?

I will be moving my website to another manager and wondered how to go about this, I cannot get into the administration page any more either, can you help me?

 I paid her for my domain names and hosting, Feb 2018-2019)  and SSL for a year on the 31st May 2018, however I feel now that she is just not being honest with me.

Thank You in advance

Linda


Hi Linda, 

I am so very sorry for the lack of communication again.  
Your website is always going to get hacked now, from experience once they have been once they just keep coming back unfortunately.  Joomla is completely out of fashion because it is insecure to hackers now.  Websites are constantly changing and this is a big change in the industry.  

So by way of apology I can redo your website tonight for £199.  

Please choose a template you like and I will use all the current images and text on your new site unless you have new images?

https://www.squarespace.com/templates/ <https://www.squarespace.com/templates/>

Please check out the pricing (there will be no hosting charges from me anymore) and you will never get hacked again.

Pricing https://goo.gl/EVQSXZ <https://goo.gl/EVQSXZ>
