### ISSUE TITLE
[jorg] Site Speed Review

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#12]
Look at the assets of the website and see where additional speed tweaks can be made to reduce site foot print and increase speed.

http://tools.pingdom.com/fpt/#!/dB24k3/http://joomla.org

Should be an ongoing and regular review.

**Comment by mbabker** [comment]
I'm waiting for the CDN's .htaccess to refresh but on all other sites I have admin for I've added browser caching and compression directives to the .htaccess files, similar to the directives on the issue tracker (https://github.com/joomla/jissues/commit/a9baec7c826f200e82ed590b82046432876c405a) which IIRC I pulled out of Admin Tools' generator.  Without getting tricky with Joomla and messing with async/defer attributes, trying to combine all the CSS/JS files site wide (or implementing something like JCH Optimize), or trying to use HTTP 2 directives it's as good as it's going to get for now.
