### ISSUE TITLE
[jwc] 

### ISSUE THREAD

**Issue by RlkPrasad** [joomla/joomla-websites#120]
Hi there,

In the bottom left you have this message...
CONTACT US
Questions? We’ve got answers. Try us.

But the button there doesn't lead us to any where, it just points back on the home page.
Kindly let me know, whom to contact for more clarity about the program.

Regards,
Prasad.

**Comment by jneubauer** [comment]
can someone confirm this has been fixed? We've just updated this.

**Comment by MAT978** [comment]
Modal form appears and just sent a test message

**Comment by jneubauer** [comment]
success!! Thanks! :)

Closing this now.
