### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by clintrileyTCAA** [joomla/joomla-websites#1200]
The employee who administered our websites was released from employment today. He has locked down our websites and we're unable to log in or access them. There are five separate sites and I need to be able to revoke Rob Hosier's access of them all.

www.artsacademics.org
www.fwafa.org
www.mytesa.org
www.texasboyschoir.org
www.texasdanceconservatory.org

Please contact me to let me know what you need to do to revoke his access and grant us with that.

Thank you-
Clint Riley
President & CEO
Texas Center for Arts + Academics
clint.riley@artsacademics.org
817-766-2390 x106

**Comment by mbabker** [comment]
Hi there,

The Joomla project does not actively host or support sites using our software beyond responding to bug reports and feature requests in the core software itself.

For your scenario I can recommend a couple of options:

- Using the community forums at https://forum.joomla.org to discuss your issue and finding potential solutions to it
- Finding a service provider from our resource directory at https://resources.joomla.org that can provide direct assistance on your issue
