### ISSUE TITLE
[jcomm] Events not linked to Joomla

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1201]
Please remove these events:
![3](https://user-images.githubusercontent.com/4682328/43704262-fb986b12-9956-11e8-94ea-5f443ca044ca.png)

Once again, the report button on the events page doesn't work properly as it's not possible to report anything (even when I'm logged as SU):
![2](https://user-images.githubusercontent.com/4682328/43704291-1875fb0a-9957-11e8-8c08-fcae3cca0f77.png)

**Comment by Sandra97** [comment]
Update! These events are not shown where not logged in. I need more coffee.

**Comment by brianteeman** [comment]
what about rsform pro day? which also has invalid dates

**Comment by Sandra97** [comment]
It's not displayed either when not logged in.
