### ISSUE TITLE
[joomla.org] Wrong word

### ISSUE THREAD

**Issue by sarsaine** [joomla/joomla-websites#1203]
At https://www.joomla.org/3/fr
In "Support du chiffrement" particle the word "cryptage" is an Anglisism that doesn't make sense in French. Use "Chiffrement" instead.

**Comment by Sandra97** [comment]
Edited on the landing page. 
Note that cryptage is also often used in French, even if you're right that 'chiffrement' is preferable.
Also, for any translation suggestion, this should be done directly on Crowdin in the related project.
Thanks.
I'm closing this issue as it's solved
