### ISSUE TITLE
[jlaunch] joomla.com SSL warning can prevent redirect to launch.joomla.org

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#1204]
It looks like the joomla.com domain is using the SSL for joomla.org which throws an "insecure site" warning in chrome and prevents the redirect to https://launch.joomla.org/
![screen shot 2018-08-16 at 1 59 55 pm](https://user-images.githubusercontent.com/1870522/44229364-731b4e80-a15d-11e8-9f76-f30922cccc7b.png)

**Comment by jonathanCA** [comment]
Thank you, we are looking into this now.

**Comment by jonathanCA** [comment]
Just following up - this was resolved last week 👍

**Comment by Sandra97** [comment]
Thanks Jonathan!
I'm closing this issue.
Re-open if needed.
