### ISSUE TITLE
[jevnt] Archive: JUG Sussex with Start-Date.23. February 2019

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-websites#1205]
at https://community.joomla.org/events/archive.html you find JUG Sussex with Start-Date.23. February 2019

![modified](https://user-images.githubusercontent.com/8235763/44230032-2f930580-a19a-11e8-8b1c-00b334da7d4d.jpg)

**Comment by hvdmeer** [comment]
I think Archive is preselected when entering a new event.

**Comment by franz-wohlkoenig** [comment]
at https://community.joomla.org/events.html same Event is shown:

![screen shot 2018-08-17 at 06 00 13](https://user-images.githubusercontent.com/8235763/44247195-eadf8c80-a1e2-11e8-97ac-2d1069574f83.jpg)

**Comment by conconnl** [comment]
[Closed] - Issue is 1,5 year old and it looks fixed as the 2020 events are only shown in the Events page and not archive.
