### ISSUE TITLE
[jlaunch] CA-Nightly Build is not equal to developer.joomla.org/nightly-builds.html

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#1207]
Please read https://github.com/joomla/joomla-cms/pull/21579#issuecomment-414116905 and above as there are Differences between Nightly Builds offered by CloudAccess and https://developer.joomla.org/nightly-builds.html

**Comment by wojsmol** [comment]
cc @jonathanCA

**Comment by dmitriy-cloudaccess** [comment]
The issue has been fixed.
It was caused by our cronjob. We will improve it to catch this sort of errors on an early stage.

**Comment by franz-wohlkoenig** [comment]
Thanks for your Research and solving the issue.
