### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by feteno** [joomla/joomla-websites#1212]
Alerte (Joomla 3.8 .11

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 98, "Extension Update Admin Bruteforce Protection", URL : https://www.siteguarding.com/files/jadminbruteforceprotection.zip/extension.xml

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 105, "Admin Tools Core", URL : https://cdn.akeebabackup.com/updates/pkgadmintoolscore.xml

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 106, "Akeeba Backup Core", URL : https://cdn.akeebabackup.com/updates/pkgakeebacore.xml

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the **joomla.org websites only**. For this Reason please close this Issue, thanks.
