### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by h-brush** [joomla/joomla-websites#1213]
Здравствуйте! Можно ли обновить joomla Версия 1.5.22? Устал бороться с вирусами(. Сайт http://tdparikmaher.ru

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for reporting issues with the **joomla.org websites only**. For this Reason please close this Issue, thanks.

**Comment by mbabker** [comment]
> Hello! Is it possible to update joomla Version 1.5.22? I'm tired of fighting viruses

Yes, please see https://docs.joomla.org/S:MyLanguage/Joomla_1.5_to_3.x_Step_by_Step_Migration

**Comment by h-brush** [comment]
Спасибо, плохо что не на русском языке, врятли техническая информация будет правильно переведена онлайн переводчиком(22.08.2018, 16:11, "Michael Babker" <notifications@github.com>:
Hello! Is it possible to update joomla Version 1.5.22? I'm tired of fighting viruses

Yes, please see https://docs.joomla.org/S:MyLanguage/Joomla_1.5_to_3.x_Step_by_Step_Migration
