### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Pete71** [joomla/joomla-websites#1214]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/).This repository is for reporting issues with the joomla.org websites only. For this Reason please close this Issue, thanks.

**Comment by Pete71** [comment]
Hi, new to github, sorry for being a little bit clumsy.
I'm a translator for Joomla 4.x and got a 404 error following the link
https://api.joomla.org/cms-4/classes/Joomla.CMS.Plugin.CMSPlugin.html

I was asked to open an issue here.

Pete

**Comment by franz-wohlkoenig** [comment]
welcome @Pete71 an thanks for your Report (please ignore my first Comment).

**Comment by Pete71** [comment]
No problem, I should have looked what to do first

**Comment by mbabker** [comment]
This is expected, API docs for 4.0 are not being generated at this time.  During beta/RC we will set this up.
