### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by colorStarDani** [joomla/joomla-websites#1215]
Dear Sir/Madam,

I would like to ask for your help. I am the administrator of a homepage using joomla. I did not create the website, but I inherited it and have been updating the page for years now. I tried to login to the administrator page now, but for some reason it does not let me in with the same username and password as I used before. What can I do?

The page: http://colorstar.hu/new/administrator/

Thank you,
Daniel

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

Thanks!
