### ISSUE TITLE
JIssues has a CSP Error

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-websites#1217]
![image](https://user-images.githubusercontent.com/1986000/44634095-99769080-a98c-11e8-9876-eca398c70dc0.png)

// CC @zero-24

**Comment by zero-24** [comment]
This is part of expected. As no one found the switch to turn it off. They use there all google domains they ever created (for example google.de when I'm on the page) so it is hard to whitelist and as this data is not relevant any more we decided to block them. It should only popup on the first call to issues.joomla.org anyway.

**Comment by Sandra97** [comment]
@zero-24 Can this issue be closed?
