### ISSUE TITLE
[joomla.com] test-promo.joomla.com sends spam

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-websites#1218]
I received a report from a german user saying that he receives spam from test-promo.joomla.com - that site has to be switched off asap.

**Comment by Sandra97** [comment]
@jonathanCA, could you take care of this? Thanks!

**Comment by jonathanCA** [comment]
Hi All, the site has now been removed per our abuse workflows.

**Comment by jeckodevelopment** [comment]
Thank you!
Closing. @SniperSister please re-open if needed.
