### ISSUE TITLE
[icomoon] Invalid HTTPS certificate

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-websites#1219]
The HTTPS certificate used on https://icomoon.joomla.com/ is only valid for the domains `*.cloudaccess.net, cloudaccess.net`.

**Comment by Sandra97** [comment]
https is not yet available for joomla.com websites. But @jonathanCA will be able to tell you more about this

**Comment by Harmageddon** [comment]
Oh, I missed the fact that it is a joomla.com site instead of .org. Sorry! I'm using this site as a reference so often that I thought it was an official one.

**Comment by Harmageddon** [comment]
Alright, thank you for the information! So I'm closing this.
