### ISSUE TITLE
Wrong displayed size/MD5 Signature/SHA1 Signature for Joomla! 3.8.12 Full Package (.zip) on downloads.joomla.org - is it a cache?

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-websites#1221]
Open `https://downloads.joomla.org/cms/joomla3/3-8-12`. Download `Joomla! 3.8.12 Full Package (.zip)`. It's as usually `~13mb`. But the site displays `203.31 kB,` MD5 Signature and SHA1 Signature [hash] also "wrong". Is it a cached data from another file?

Btw, download url (not the "real" file url) from `downloads.joomla.org` - `https://downloads.joomla.org/cms/joomla3/3-8-12/Joomla_3-8-12-Stable-Full_Package.zip?format=zip`. Download url on the news article about release (`https://www.joomla.org/announcements/release-news/5743-joomla-3-8-12-release.html`) - `https://downloads.joomla.org/cms/joomla3/3-8-12/Joomla_3.8.12-Stable-Full_Package.zip?format=zip` (`_3-8-12` vs `_3.8.12`), but of cource the "real" file url is the same.

**Comment by mbabker** [comment]
Data corrected.
