### ISSUE TITLE
[Minor] Joomla.org icons not loading

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-websites#1223]
<img width="1280" alt="screen shot 2018-09-04 at 9 08 05 am" src="https://user-images.githubusercontent.com/5198092/45004825-43f05280-b022-11e8-8658-27fbce430640.png">

Footer icons not loading and shows cross origin issue on console.

**Comment by zero-24** [comment]
Has been resolved please clear the cache and check again should work now. Thanks for the efforts by Michael with Rochen and the CDN Provider!

**Comment by mbabker** [comment]
Issue should now be fixed fully.  You may need to clear browser cache to remove the stale (invalid) cache entry for the CSS.
