### ISSUE TITLE
[jcomm] download link to Dutch (but maybe also other languages) translations

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#1226]
On https://community.joomla.org/translations/joomla-3-translations/dutch-translation.html there is a link to the Dutch translations: http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6408
This is ordered on the name of the release. While we are on 3.8.12 this release is not on top.
Maybe change the link into: http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6408&br_pkgrlssort_by=release_date&br_pkgrlssort_order=desc, so the latest release is on top?

**Comment by Sandra97** [comment]
As it's solved for Dutch, I'm closing this issue. 
The Core Translation Team is in charge of this section. Any request about this section should be seen with them.
