### ISSUE TITLE
[jcm] vue in development mode

### ISSUE THREAD

**Issue by omarmfs98** [joomla/joomla-websites#1227]
good night, I realized that they use vue but in development mode in their comments, I managed to modify all the fields that send to the server as the contentId add an exaggerated value, many things that should not be modified or that must be the whole modify them , that can give them errors in their database, possibly by waiting for a type of data but a different one arrives, they must change it to production mode.

**Comment by franz-wohlkoenig** [comment]
can you please write in English?

**Comment by omarmfs98** [comment]
Sure, 

good night, I realized that they use vue but in development mode in their comments, I managed to modify all the fields that send to the server as the contentId add an exaggerated value, many things that should not be modified or that must be the whole modify them, that can give them errors in their database, possibly by waiting for a type of data but a different one arrives, they must change it to production mode.

**Comment by franz-wohlkoenig** [comment]
thanks, but i didnt really understand whats the Issue on joomla-website like joomla.org.

**Comment by omarmfs98** [comment]
in the following images I show you how I can alter the data of the component, in some cases modify the data "component" to "editable" and answer a status code 500, if I modify the value to "com_k2" it responds correctly, but alter the data "contentid" by an existing one, I do not know if that will make problems for having duplicated that id, in the last image I show how I could access from console and modify the data without the DevTools of vue, someone could create a script that would change all the data for example and never leave comment.

![1](https://user-images.githubusercontent.com/24736893/45284556-81cbfb80-b4a6-11e8-9471-0ed2ac50d492.png)
![2](https://user-images.githubusercontent.com/24736893/45284557-81cbfb80-b4a6-11e8-83c1-db77e33bbd07.png)
![3](https://user-images.githubusercontent.com/24736893/45284558-82649200-b4a6-11e8-8583-3480f19d9d87.png)
![4](https://user-images.githubusercontent.com/24736893/45284559-82649200-b4a6-11e8-8d51-8eb3d92daa47.png)
![5](https://user-images.githubusercontent.com/24736893/45284560-82649200-b4a6-11e8-9382-0163482e4251.png)
![6](https://user-images.githubusercontent.com/24736893/45284561-82649200-b4a6-11e8-998e-7219208e79d9.png)
![7](https://user-images.githubusercontent.com/24736893/45284562-82649200-b4a6-11e8-9ad2-09887e043052.png)
![8](https://user-images.githubusercontent.com/24736893/45284564-82fd2880-b4a6-11e8-8e63-515fffa4a4f2.png)
![9](https://user-images.githubusercontent.com/24736893/45284566-82fd2880-b4a6-11e8-8fca-a19c48d4ff92.png)
![10](https://user-images.githubusercontent.com/24736893/45284570-8395bf00-b4a6-11e8-85cb-732e7b42f637.png)
![11](https://user-images.githubusercontent.com/24736893/45284571-8395bf00-b4a6-11e8-8594-d72248dbd5bf.png)
![12](https://user-images.githubusercontent.com/24736893/45284574-84c6ec00-b4a6-11e8-8b18-3a3c2b24ad63.png)
![13](https://user-images.githubusercontent.com/24736893/45284575-84c6ec00-b4a6-11e8-9755-689fdfcfff19.png)

**Comment by franz-wohlkoenig** [comment]
thanks for your Explanation. I guess its about https://github.com/joomla/joomla-cms and not a Joomla-Website like https://www.joomla.org/.

**Comment by jeckodevelopment** [comment]
> thanks for your Explanation. I guess its about https://github.com/joomla/joomla-cms and not a Joomla-Website like https://www.joomla.org/.

I don't think so. It should be related to the comment plugin/component.

@wilsonge @JacquesR @helvecio ?

**Comment by zero-24** [comment]
I have also reported this weeks ago to @yvesh and he told me this will get fixed. And yes it is about the comment extension. Maybe @compojoom can help here too?

**Comment by compojoom** [comment]
@zero-24 - I just issued a new version and we no longer use vue in production mode. 

@omarmfs98 - Can you explain a little more why the described behavior is a problem. First of all you are on the website and the configuration of the website is that any user anonymous user can submit a comment. 

The form is protected with a token and you are able to submit a comment, because when you visit the page this token is still active(not expired). If you were to send the form without the token you'll get a 500 error. 

It's true that we don't verify whether or not you have access to a particular content id to post a comment, but I also don't see this as our responsibility.

**Comment by zero-24** [comment]
@compojoom it still shows me this message

![image](https://user-images.githubusercontent.com/2596554/45619630-43bc7200-ba7a-11e8-9135-74a67f6c471f.png)

Or is the patch not yet applied there?

**Comment by compojoom** [comment]
Clear cache? We are running this version on our demo site and the message is not showing there. 
If it is still not working after the update - ping me on glip/skype.

**Comment by zero-24** [comment]
I have no access to that website so i can not clear the cache maybe @jeckodevelopment @wilsonge @JacquesR @helvecio can help here. I thought you have access to the backed too. ;)

**Comment by compojoom** [comment]
Not that I knew. 
Another possibility is that you guys have a template override for templates/default/default.php

`media/lib_compojoom/third/vue/vue-prod.js` - this is the path to the production version of vue.

**Comment by JacquesR** [comment]
Updating to the latest version of the comment plugin resolved the Vue notice.

**Comment by zero-24** [comment]
Thanks 👍

**Comment by Sandra97** [comment]
As it's solved, I'm closing this issue.
Re-open if needed.
