### ISSUE TITLE
changing billing account details

### ISSUE THREAD

**Issue by davidmoor962** [joomla/joomla-websites#1229]
The management of the bdrpc.club website has changed. I am the new site manager. The club wants to change the billing account details and all contact details for the management of this website. I am just becoming familiar with the joomla tool and its features, but this is the most important issue I want to solve. Please advise me how to do this.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

So please close this issue. 

Thanks!
