### ISSUE TITLE
[jlaunch] 

### ISSUE THREAD

**Issue by Aidan38** [joomla/joomla-websites#1236]
Hello,

I'm using jlauch to build a new website.
Everything was ok since one since I install the component Uddeim.
Just after the installation I got a fatal error, and it's now impossible to connect to the admin.

I've contacted Cloudaccess support to ask to restore a backup.

This is the answer I got :

> We need some information from you first can you kindly fill out this section:
My Details:
https://ccp.cloudaccess.net/clientarea.php?action=details
You do not have any backups currently within your Cloud Control Panel (CCP)
https://ccp.cloudaccess.net/cloudaccess/cloud-control-panel/backups.php?id=969548
This being said you will have two choices and one means deleting all content and files and starting over completely:
Go here and locate Restore To Default: Press Reset to reset the application back to a fresh installation of either Joomla.
https://ccp.cloudaccess.net/cloudaccess/cloud-control-panel/application-toolkit.php?id=969548
Or you can pay 30.00 for each attempt and we can restore your sites within the 14 day window: What day works for you?
https://www.cloudaccess.net/backup-and-recovery.html

Please let us know if there is anything else we can do for you.

Zii Rios - Joomla! & WordPress Support Engineer

If you feel this ticket is solved, no reply is needed. This ticket will automatically close after 72 hours.

**Comment by Sandra97** [comment]
@jonathanCA Could you please check? Thanks!
