### ISSUE TITLE
[jlaunch] 

### ISSUE THREAD

**Issue by Aidan38** [joomla/joomla-websites#1238]
Hello,

I've a problem with a website build with JLaunch.
The admin work well, but the Frontend is very often not accessible and display the message:

This page isn’t working
chtuck.joomla.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

The website:
http://chtuck.joomla.com

Thanks for your help

**Comment by jonathanCA** [comment]
Hi there, I'm sorry that we did not get back to you on this. It's not possible for us to troubleshoot this far back, but in general I'd recommend using our support in these types of situation. Just click on the "Support" section in your Cloud Control Panel after launching the site. Thank you
