### ISSUE TITLE
[jdocs] Checkbox form field documentation is wrong

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#1239]
The [documentation for a Checkbox](https://docs.joomla.org/Checkbox_form_field_type) states that you can set a default value, but that is incorrect.

Instead you can set `checked="true"` which is not documented.

This was discovered in [this issue](https://github.com/joomla/joomla-cms/issues/22575).

**Comment by Sandra97** [comment]
Hi Soren, 
JDocs is a wiki, so everybody is free to edit/update it.
Could you please apply this change? Thanks!

**Comment by aDaneInSpain** [comment]
LOL, I didn't know it was that easy. You have a new contributor :-)
