### ISSUE TITLE
Spam from joomla.com-Subdomains?

### ISSUE THREAD

**Issue by duracell** [joomla/joomla-websites#1241]
After I found #1218 but no info about joomla.com at the README, I have no idea which place is the best to report maybe spammy *.joomla.com instances.
I get daily spam from different addresses with joomla.com-domains in the message-id and x-mailer PHPmailer. And always with the same subject: "Gewinnen Sie ein brandneues E-Bike". Can you check if the subdomains are used and if the have anything todo with the spam or if the message-id is just set to joomla.com-subdomains?

Sending domains are:
voucher.joomla.com 185.186.77.153
chaouidici3.joomla.com 188.213.31.115
dysonv2.joomla.com 93.113.206.60
vchrcomste.joomla.com 54.37.16.240
prmlnde.joomla.com 188.213.31.115
habakhoukha.joomla.com 188.213.31.115
johneyybernard.joomla.com 54.37.16.240

And maybe you or the hoster can help to prevent people sending spam. That would be great.

**Comment by jonathanCA** [comment]
Thank you for bringing these to our attention. We will clean and/or remove these sites from the launch.joomla.org platform. 

The current sending limits are 15 per hour. We are in discussion on reducing this by 50% to make the sites less enticing for spammers. The question is, will reducing the limit make the service less useful?

**Comment by jonathanCA** [comment]
I've been informed by our Abuse Team that all accounts had already been identified and taken down. Again, thanks for reporting, feel free to send any further reports to abuse@cloudaccess.net and they will be handled promptly.

**Comment by Sandra97** [comment]
As this seems to be solved, I'm closing the issue.
Please re-open if needed.
