### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by edwardgraceinteriors** [joomla/joomla-websites#1242]
I hope you don’t mind me contacting you again. I am still having trouble with my website

https://www.interiordesigneressex.co.uk

Please have a look at it, my front page has gone and your logo is there? Some parts are available but it is wrong.

My webpage manager, Waltham Websites has been very difficult to contact and when finally she replied to my email, her phone number no longer available, please see her words to me below, I would appreciate your comments, is it true?

I will be moving my website to another manager and wondered how to go about this, I cannot get into the administration page any more either, can you help me?

I can no longer access the administration either.

 I paid her for my domain names and hosting, Feb 2018-2019)  and SSL for a year on the 31st May 2018, however I feel now that she is just not being honest with me.

Please advise.

Thank You in advance

Linda

Hi Linda, 

I am so very sorry for the lack of communication again.  
Your website is always going to get hacked now, from experience once they have been once they just keep coming back unfortunately.  Joomla is completely out of fashion because it is insecure to hackers now.  Websites are constantly changing and this is a big change in the industry.  

So by way of apology I can redo your website tonight for £199.  

Please choose a template you like and I will use all the current images and text on your new site unless you have new images?

https://www.squarespace.com/templates/

Please check out the pricing (there will be no hosting charges from me anymore) and you will never get hacked again.

Pricing https://goo.gl/EVQSXZ describe the problem or your issue

Fay

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!

I'll close this issue here.
