### ISSUE TITLE
[jlaunch] J! v.4.0.0-alpha becomes J! 3.9.0-rc3-dev

### ISSUE THREAD

**Issue by AlainRnet** [joomla/joomla-websites#1244]
I wanted to test J!4 with Launch, so I select "Joomla! 4.0.0-alpha5-dev" in "Advanced settings" but my website was à J! 3.9.0-rc3-dev
I try again and have the same result.
Finally, I select J! 3.9.0-rc3-dev and i have a J! v.4.0.0-alpha website.

I think there is an inversion between labels (J! v.4.0.0-alpha vs J! 3.9.0-rc3-dev) and values (2015 vs 2049)

**Comment by igorkaczor** [comment]
Yup, mistaken related ids. Fixed.

**Comment by Sandra97** [comment]
Thanks Igor! As it's fixed, I'm closing this issue.

**Comment by AlainRnet** [comment]
Thank you both very much.
