### ISSUE TITLE
Typo on the Showcase Team page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#1245]
Hello,
please correct the highlighted typos on the Team Page:
https://showcase.joomla.org/about-jsd/team-members.html

![immagine](https://user-images.githubusercontent.com/733133/47720012-2f5cbf00-dc4d-11e8-8967-f7f81afb1c9c.png)

`Developper` should be `Developer`

**Comment by sebastienlapoux** [comment]
![image](https://user-images.githubusercontent.com/13470265/47725481-edd21100-dc58-11e8-8cce-25f19c1008a5.png)
Fixed.
Thanks.

**Comment by jeckodevelopment** [comment]
Thank you!
