### ISSUE TITLE
[jlaunch] Update 3.10 > 3.2.7

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#1246]
### Steps to reproduce the issue
Installed a new 3.10-dev.-Site. In Backend got Information that should Update on new Version "3.2.7".
![bildschirmfoto 2018-10-31 um 07 08 27](https://user-images.githubusercontent.com/8235763/47769339-ddaf4580-dcdb-11e8-9b84-9979716ddaa4.png)

### Expected result
No Information about an old Version.
### System information
- 3.10
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 63 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve
### Additional comments
Looks like 3.2 ist higher than 3.10.

**Comment by zero-24** [comment]
What update server do you use?

**Comment by franz-wohlkoenig** [comment]
Update Channel "Default".

**Comment by franz-wohlkoenig** [comment]
Using https://update.joomla.org/core/nightlies/next_minor_list.xml the Update-Message is gone.

**Comment by zero-24** [comment]
Can you only reproduce this on launch or also on an local install?

**Comment by franz-wohlkoenig** [comment]
i can only test on launch.

**Comment by zero-24** [comment]
hmm added to my todo list to analyse in detail when i get more time than today. Thanks for reporting.

**Comment by zero-24** [comment]
hmm I can not reproduce the issue on a local install nor on a newly created 3.9 site (at cloudaccess) and than upgraded to 3.10 how did you got a direct 3.10-dev install up and running at cloudaccess?

**Comment by franz-wohlkoenig** [comment]
ther was a 3.10-dev-Installation available at launch, which is not gone. I guess this problem can't come up and close it. Thanks for your Work, @zero-24.
