### ISSUE TITLE
A non-numeric value encountered in C:\xampp\htdocs\joomla\plugins\system\helix3\core\helix3.php

### ISSUE THREAD

**Issue by Joseph880929** [joomla/joomla-websites#1249]
Hello:

I am developing a website in joomla, as part of a e-learning course, but I am getting the following error: A **_non-numeric value encountered in C:\xampp\htdocs\joomla\plugins\system\helix3\core\helix3.php_**

I have tried to solve it by myself, but I have not succeeded on it.

I provide a screenshot showing the error, so you have a better idea of it:
![2018-11-09](https://user-images.githubusercontent.com/24527472/48289178-8d06bd80-e43c-11e8-8f65-8e579821d167.png)

Please, I will be grateful with any guidance or solution you can provide.

Thanks for your attention and sooner answer.

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
