### ISSUE TITLE
[jrd] Google Geocoding API error: The request was denied.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1250]
![screenshot 2018-11-09 at 23 02 28](https://user-images.githubusercontent.com/400092/48292749-8ba4b780-e473-11e8-89ce-cc6f1206f6a9.png)
https://resources.joomla.org/en/item/virya-group-limited

**Comment by genr8r** [comment]
Thanks @PhilETaylor. Saeed on our team is working to resolve this... https://volunteers.joomla.org/teams/resource-directory-team/reports/909-team-collaboration

**Comment by genr8r** [comment]
@Saeedghb have you had a chance to check into this?

**Comment by conconnl** [comment]
Closed - 
Don't see API errors anymore on the mentioned page, seems to be solved.
