### ISSUE TITLE
Class 'JToolbarHelper' not found[jdown] 

### ISSUE THREAD

**Issue by Latos88** [joomla/joomla-websites#1252]
Hello, there is issue with last joomla update when Installing Joomla 3.9 (from 3.8.13) using built-in Joomla Update. Clicked normal blue "Install the Update" button. After update we receive error message: "Error: 0 Class 'JToolbarHelper not found'. There is a button to return to the Control Panel. Pushing the button just re-displays the same screen. Joomla menu is visible (System, Users, Menu, etc.). No matter what option I select, this same screen re-displays.
To fix it I was obligate to use hold index.php from joomla 3.8.8 now it asking me  for update but I reserve myself to do so.
Thanks

**Comment by Sandra97** [comment]
Hello,

For this issue, please see [#21960](https://github.com/joomla/joomla-cms/issues/21960)

As this repository is only for issues on *.joomla.org websites, I'm closing it.
