### ISSUE TITLE
[jtm] Logo Usage

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1255]
https://tm.joomla.org/trademark-policy.html

> Fourth, you may not use the Joomla! logo.

Without additional clarification this is not legally correct

**Comment by jeckodevelopment** [comment]
Amended, please check

**Comment by conconnl** [comment]
@brianteeman Is it Ok now in your humble opinion?

**Comment by brianteeman** [comment]
> Fourth, you may not use the Joomla! logo to promote services like they are approved or endorsed by Open Source Matters, Inc. or the Joomla! Project.

I think what you mean is

> Fourth, you may not use the Joomla! logo to imply approval or endorsement by Open Source Matters, Inc. or the Joomla! Project of your services.

**Comment by jeckodevelopment** [comment]
Fixed.
Thank you for the better form!
