### ISSUE TITLE
[jtm] Logo Usage - Descriptive

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1257]
https://tm.joomla.org/joomla-name-and-logo-use.html

> When the use of the Joomla! name is used in a purely descriptive manner, such as in an article in a publication, or a presentation no permission is needed to use the trademark.

Surely the same should apply to the logo - otherwise everyone is in breach when they write a review of joomla, advertise that they host joomla, congratulate joomla with an award etc

**Comment by conconnl** [comment]
@mandville please take care of this or close the issue.

**Comment by brianteeman** [comment]
Please do not close it unless it is dealt with

**Comment by mandville** [comment]
Conditional use logos do not require any registration https://tm.joomla.org/conditional-use-logos.html 
This is stated in the paragraph above the one quoted.

**Comment by brianteeman** [comment]
And that absolutely does not answer the original post

**Comment by conconnl** [comment]
@jeckodevelopment 
Can you please shine you light on this.
The logo page doesn't show the normal clean logo, which is used by many people and also doesn't mention anything about articles and presentations.

The text selected by @brianteeman doesn't mention the logo.
I would think the text needs to be changed too "use of the Joomla! name & logo is used purely...."

**Comment by jeckodevelopment** [comment]
Amended, please check

**Comment by brianteeman** [comment]
Thanks. only took a year.

**Comment by conconnl** [comment]
Thanks @jeckodevelopment

**Comment by jeckodevelopment** [comment]
sorry for that.
