### ISSUE TITLE
[jtm] Transliteration

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1258]
> Can I transliterate "Joomla!"?
In no case should the word Joomla!® be transliterated using the local language glyphs or alphabet.

The israeli community has always transliterated the word Joomla as ג'ומלה

**Comment by jeckodevelopment** [comment]
> The israeli community has always transliterated the word Joomla as ג'ומלה

That doesn't mean it's correct neither allowed.
In all the policies I've always seen that Joomla shouldn't be translated, as well as, in Crowdin we explicitly ask people to not translate Joomla.

**Comment by brianteeman** [comment]
It was an observation and nothing more than that

**Comment by conconnl** [comment]
Thank you both.
