### ISSUE TITLE
[jtm] Email communication

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1259]
Last week I received an email - text below

This refers to several things 
- a limited license for two years
I am not aware of this and couldn't see any reference to it on the website
- Domain name use (joomla in your url) 
A domain name is not the same as a url. Surely you understand that.
- if you are not on that list then you do not currently hold permission to use the joomla! name in your url, 
So everyone in the past who has received permission no longer has permission? Without any notice? 

> Hello,
You are receiving this email because you are registered on the Joomla!® Trademark website ( tm.joomla.org).
Recently you may have noticed a few changes regarding the way the trademark license system operates. We are informing every one to remember the requirements to be granted a limited license for two years. Which enables you to use the Joomla! name in their domain names, the logos, trademark and brandmark.

> Recently we changed our ticket system to rstickets. If you are still outstanding an answer from your ticket, please contact us again as it may have got lost in migration.

> We have reviewed our documentation and FAQ which can be found as follows.
The Brand Manual - https://tm.joomla.org/brand-manual-and-limited-use-logos.html
The disclaimers required on a joomlaname site - https://tm.joomla.org/disclaimers.html logo use - https://tm.joomla.org/conditional-use-logos.html
Domain name use (joomla in your url) https://tm.joomla.org/registration-of-domain-names.html
More about the Trademark and FAQ - https://tm.joomla.org/trademark-license.html
We display our current license holders at https://tm.joomla.org/approved-domains.html , and if you are not on that list then you do not currently hold permission to use the joomla! name in your url, limited use logos, or other use that may be in contravention of the trademark.

> If you have any questions on the points above, then please contact us via the ticket system https://tm.joomla.org/tickets.html . If you do not hold a current limited use license then joomla may not be able to list you on its websites.

> Mandville

**Comment by mandville** [comment]
Clarification:     
**a limited license for two years is the decision to prevent lifetime licensing and allows for a license for the duration of the life for what is commonly known as a domain name or the url. and would apply equally to joomlawebsite.foo and it would to www.joomlawebsite.foo**
**The Trade Mark team power to limit use of the license is approved by OSM bylaws.  motion #2017-069 on September 28, 2017. refers. The email acted as notification and a reminder. see https://tm.joomla.org/registration-of-domain-names.html**

   

-  if you are not on that list then you do not currently hold permission to use the joomla! name in your url,
**Generally that is correct. Approval to use the Brand and Trademark is a limited approval. If you are not on the list and believe you have approval please follow the approval process.** 
    

- So everyone in the past who has received permission no longer has permission? Without any notice?
**The email acts as notice.** 

We are currently reminding all people who use the trademark or brandmark that they need to be reviewed.

**Comment by brianteeman** [comment]
1. that email does not constitute a legal notice especially as it is addressed to an individual without reference to the domain in question and it does not specifically state that the policies previously adopted and the permissions previously granted (for which you have no records) are now claimed to be invalid and/or expired.
2. a domain name and a url are not the same thing
3. the motion you refer to is only for domain names that solely consist of the word joomla plus a new tld.  for example joomla.shopping that is based on the title of the motion as the contents of the motion are not published

```
2017/069 - Approve the document called "Trademark Policy for new Top Level Domains (TLD)" as official policy regarding TLDs including one of the Joomla owned trademarks
Proposed by Luca Marzo - Seconded by Rowan Hoskyns-Abrahall
```

**Comment by brianteeman** [comment]
correction to above. i found the document you refer to and it clearly states it refers to the use of an osm trademark with one of the new tld
https://www.opensourcematters.org/images/documents/Trademark_Process_for_new_Top_Level_Domains_TLD.pdf
it makes no mention of being applicable to any domain name which may contain an osm trademark together with other non trademarked terms which is of itself questionable under us law

either your interpretation of the document is incorrect, the document does not reflect the intended purpose or you referred to the wrong document.

**Comment by brianteeman** [comment]
So I see that despite being notified that the document and vote you refer to are not related to using joomla within a domain name you are now telling people that it is policy - without any evidence

**Comment by Joomv** [comment]
This is being dealt with.
Please stand by for an announcement shortly.

**Comment by brianteeman** [comment]
Is it shortly yet?

**Comment by brianteeman** [comment]
@Joomv have read the osm minutes now - thanks

**Comment by brianteeman** [comment]
Still standing by waiting for an announcement or an updated web site

**Comment by brianteeman** [comment]
are the people who received this incorrect email going to be updated?

**Comment by jeckodevelopment** [comment]
@mandville did you send the update?

**Comment by mandville** [comment]
Discussed in document #2019/024 which were then ratified and published as per https://tm.joomla.org/registration-of-domain-names.html in September 2019. 
The Trademark team are continually reviewing the policies in light of planned procedure changes and maintain that all sites bearing the joomla name must comply with current requirements. This includes registration on the http://tm.joomla.org website and to be fully compliant with current TM policy at all times. The team will randomly spot check sites for compliance.

**Comment by brianteeman** [comment]
So the answer to the question is "No you did not"

**Comment by brianteeman** [comment]
Why did you close this. It is not resolved.

**Comment by conconnl** [comment]
You have received an answer what is done, which also means I doesn’t have to be an answer which you are happy with, but it’s still the truth. 

The answer is that no mail is send and that the website is updated and changes can happen regularly. 

It’s the same with many issues which get closed on the tracker for whatever reason, even if the reason is not what the issue creator expected.

**Comment by brianteeman** [comment]
Issues are never just closed without explanation

**Comment by brianteeman** [comment]
For future reference https://volunteers.joomla.org/board-of-directors/reports/955-osm-inc-full-board-meeting-january-24-2019
