### ISSUE TITLE
[jdevcon] Update or Take Offline

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#126]
The DevCon site hasn't been updated since it happened.  Either update the site with something or place it offline.

**Comment by Radek-Suski** [comment]
I think it something I should do but I have no access to this site. I would put it offline as I still have no answer about the future of this event

**Comment by brianteeman** [comment]
Why not put a redirect to conference.Joomla.org that way at least it is
something relevant and not an offline page

**Comment by mbabker** [comment]
That works too.  Anything's better than a live site promoting a conference from 13 months ago.

**Comment by Radek-Suski** [comment]
I will take care of it given I can now

**Comment by jessicadunbar** [comment]
+1 - Redirect it to conference.joomla.org.

**Comment by Radek-Suski** [comment]
The provided access data allow me only to access FTP so I did a redirect via .htaccess
