### ISSUE TITLE
[jtm] Jel Logo

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1260]
https://tm.joomla.org/brand-manual-and-limited-use-logos.html

> Whenever possible, the logo should appear in its full color horizontal gel version. When the gel version cannot be used, a solid color version is available.

Pretty sure that we changed this so that the flat/solid colour is the preferred/recommended option. If not then the order of he images should be changed to make the gel logos first.

**Comment by jeckodevelopment** [comment]
Fixed, thank you

**Comment by brianteeman** [comment]
better late than never
