### ISSUE TITLE
[jtm] Maqma

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1261]
https://tm.joomla.org/conditional-use-logos.html

Based on the email I received saying that maqma was no longer being used the link to the registration form on this page need to be corrected

`You must first register the use with Open Source Matters by submitting the appropriate form: Registration Form.
`

And just in case someone has the links bookmarked then maqma should be uninstalled

**Comment by jeckodevelopment** [comment]
Contact links now go to RSTickets.
Thanks for reporting it.

**Comment by brianteeman** [comment]
Contact links might do but that was not what I reported

![image](https://user-images.githubusercontent.com/1296369/49278995-3827f700-f47e-11e8-9810-aea296972942.png)

**Comment by brianteeman** [comment]
And maqma is still present on the site and active

![image](https://user-images.githubusercontent.com/1296369/49279259-e7fd6480-f47e-11e8-876a-1d80ac11542b.png)

**Comment by jeckodevelopment** [comment]
Thank you, fixed

**Comment by brianteeman** [comment]
No maqma is still active on the site

Simply removing the direct link does not remove maqma from the site which is still accessible on the same url as before and still present on google

![image](https://user-images.githubusercontent.com/1296369/49303067-aab9c680-f4c0-11e8-9ba8-cd10ad5923ee.png)

![image](https://user-images.githubusercontent.com/1296369/49303280-392e4800-f4c1-11e8-95c1-e4b779200128.png)
