### ISSUE TITLE
[joomla.org]  

### ISSUE THREAD

**Issue by Tamanda** [joomla/joomla-websites#1262]
Hi, I've tried to access https://extensions.joomla.org/ and I am getting the following error  Error: Failed to start application: Could not connect to MySQL server. This was several times  (on two mobiles and a laptop) and then my colleague tried also on his mobile phone and also found the same problem around 5pm (GMT+1) - today.   The rest of the site seems to be working fine.  I noticed this as I was going to check out and download some extensions I need.

I went back to the page and now it is just a blank white page.  Please advise.

**Comment by mbabker** [comment]
It's a known issue with the site that is being worked on.

**Comment by zero-24** [comment]
Seams to be fixed now. Closing.
