### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ng0177** [joomla/joomla-websites#1263]
I cannot access a page that I created a couple of days ago. (beginner's level)

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
