### ISSUE TITLE
[jtm] Name History

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1264]
#1254 has been closed without comment. 
The text has been changed from

> This name was chosen from thousands of community suggestions

to

> This name was chosen following a call for community suggestions by the core team, 

This is simply not true.

**Comment by ot2sen** [comment]
Just listen to Brian on these changes. He was there, also for this specific name issue where we all waited impatiently for an email from him to have a 1-hour advantage in registering domains with the new name the core team had chosen.

Just go have a read https://forum.joomla.org/viewtopic.php?f=9&t=2682
PS: the community calls were for the logo and later some templates

**Comment by mandville** [comment]
Can you suggest an accurate easily understood sentence that would convey the message in a way that would make sense to you .

**Comment by brianteeman** [comment]
I always find it is best to stick to the facts. 

I have no idea what the message is that you want to convey. 

Ths is the link to the official announcement https://forum.joomla.org/viewtopic.php?f=8&t=3097

**Comment by conconnl** [comment]
[Closed] - The text on the mentioned page is already different then the two mentioned here.
> This name was chosen by the founding team

If this is still not correct, a suggestion can be made.
