### ISSUE TITLE
[jtm] maqma

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1265]
#1261 has been closed byv @mandville despite @jeckodevelopment confirming that it is a valid issue and no change has been made on the website and links to maqma still exist

**Comment by jeckodevelopment** [comment]
Despite links are the same: https://tm.joomla.org/contact.html
They now go to RSTickets.
Thank you for reporting.

Closing, re-open if needed.

**Comment by brianteeman** [comment]
That is NOT the link I am reporting.

![image](https://user-images.githubusercontent.com/1296369/49279021-45dd7c80-f47e-11e8-8ce5-d49bffedbb1f.png)

I do not have permission to re-open!!!

**Comment by jeckodevelopment** [comment]
Thank you, fixed

**Comment by brianteeman** [comment]
No it is not fixed. Simply removing the direct link does not remove maqma from the site which is still accessible on the same url as before and still present on google

![image](https://user-images.githubusercontent.com/1296369/49303067-aab9c680-f4c0-11e8-9ba8-cd10ad5923ee.png)

![image](https://user-images.githubusercontent.com/1296369/49303280-392e4800-f4c1-11e8-95c1-e4b779200128.png)

**Comment by brianteeman** [comment]
Thank you for now correclty resolving this
