### ISSUE TITLE
[jcomm] How to change the security key device

### ISSUE THREAD

**Issue by BrunnoPrego** [joomla/joomla-websites#1266]
Hi Everyone,

    Sorry if it is not in correct place, but seems to me as a bug, or a feature request.

    I enabled the two factor authentication from community.joomla.org, but, I need to change the device (I still use the old one, but I need to discard this shortly), where I can change the device? Or include a new one?

**Comment by zero-24** [comment]
Hi this might help you?

https://www.turnon2fa.com/tutorials/how-to-turn-on-2fa-for-google-drive/ this shows you where to look and should also allow changing the seccond factor.

**Comment by BrunnoPrego** [comment]
@zero-24 this is for 2 Factor for google accounts, I am refering for site https://community.joomla.org/

**Comment by BrunnoPrego** [comment]
When I enabled the 2 factor on site community, I print a pdf from the emergency passwords; I found in the bottom page of the pdf a URI /my-profile/profile.html for alternate text to the button cancel, then I access that now, I cancel the two factor and then reconfigured this for the new device.

It necessary a link to this URI on communty page to allow the users to change this, or even the password.

**Comment by Sandra97** [comment]
@BrunnoPrego Do you still have issues?

**Comment by BrunnoPrego** [comment]
Hi @Sandra97

    My problem was solved as I commented before, but the page /my-profile/profile.html is not accessible in the community page until now.

**Comment by conconnl** [comment]
Enabled the link in the module:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/11913918/74928031-febc0e00-53d8-11ea-954b-59e12b799d05.png">
