### ISSUE TITLE
[jlaunch\] Can not login from CCP on Joomla 4.0

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-websites#1267]
I create a website with Joomla 4.0.
Then I try to login with Login button in the CCP.
It give this error:
`ERROR
Data collection error. Please contact Support`

**Comment by Sandra97** [comment]
I have the same error
![screenshot_2018-12-03 cloud control panel](https://user-images.githubusercontent.com/4682328/49454960-8f172e80-f7e6-11e8-9d41-d3dce36cca89.png)

**Comment by Razzo1987** [comment]
From ticket on cloudaccess:

> Hi Luca,
> The site: XXX.joomla.com is on Joomla! 4 - still an alpha release. At this point, the automatic login to Joomla! button is not using for the version 4 - please login to the back-end manually.

**Comment by tellmewhatyourname** [comment]
> I have the same error ![screenshot_2018-12-03 cloud control panel](https://user-images.githubusercontent.com/4682328/49454960-8f172e80-f7e6-11e8-9d41-d3dce36cca89.png)

i have same problem to,  how to fix it?

**Comment by tellmewhatyourname** [comment]
> From ticket on cloudaccess:
> 
> > Hi Luca,
> > The site: XXX.joomla.com is on Joomla! 4 - still an alpha release. At this point, the automatic login to Joomla! button is not using for the version 4 - please login to the back-end manually.
> 
> > From your CCP home click Manage by the site you want to log into and from there go to Application -> Overview and on that page there will be your Username and Password for the site.

same cant login web

**Comment by Hackwar** [comment]
This ticket is 6 years old. You wont have the same problem. In any case, this issue tracker is for handling issues with the project websites of the Joomla project and not jlaunch. Please contact the support of cloudaccess if you are using them.
