### ISSUE TITLE
[general] Update from PHP 5.4

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#127]
All Joomla web properties are running PHP 5.4.  PHP 5.4 is no longer supported by the PHP project.  Joomla's web properties should be updated to a supported stable version of PHP.  Joomla 2.5 and 3.x will run without errors (from core) on PHP 5.6, as will our Framework based websites (the Framework site itself and the issue tracker).  Software that will not function on supported PHP versions needs to be identified for upgrade and placed on a fast track for the upgrade to be completed.

Known sites that will fail without core hacks on an upgraded PHP version:
- ~~help.joomla.org (Joomla 1.0 install, don't confuse this with the /proxy subinstall for the help screens which is on Joomla 3.4)~~
- ~~community.joomla.org (Joomla 1.5 install)~~
- ~~showcase.joomla.org (Joomla 1.5 install)~~

Sites on server needing update:
- [x] api.joomla.org
- [x] appscdn.joomla.org/webapps (Install from Web)
- [x] certification.joomla.org
- [x] community.joomla.org
- [x] conference.joomla.org
- [x] docs.joomla.org
- [x] exam.joomla.org
- [x] help.joomla.org
- [x] magazine.joomla.org
- [x] opensourcematters.org
- [x] resources.joomla.org
- [x] shop.joomla.org
- [x] showcase.joomla.org
- [x] tm.joomla.org
- [x] vel.joomla.org
- [x] volunteers.joomla.org
- [ ] joom.la

**Comment by wilsonge** [comment]
OK so let's replace help.joomla.org with a single php file to server the help screens

**Comment by Radek-Suski** [comment]
Are there any plans to upgrade c.j.org or merge it with j.org ?

**Comment by mbabker** [comment]
The help site is offline now and replaced with a mini-app to handle the legacy help screens in 1.0 and 1.5 and give a simple landing page with navigation for web requests.  So that's no longer an issue.

https://github.com/joomla-projects/offline-help.joomla.org

**Comment by brianteeman** [comment]
Do you think its worth adding a link to the docs site in the text 
Perhaps 
The Joomla Help Site has been taken offline please see docs.joomla.org.

**Comment by mbabker** [comment]
I'm always fair game for improvements on the sites, especially since I push a lot of MVP style stuff.  I put that site's code on a GitHub repo for a reason.

**Comment by mbabker** [comment]
@joomla/webmasters This requires action ASAP.  If a site cannot be upgraded past PHP 5.4, then it should either be moved to a legacy server or using Rochen's current setup the PHP versions for each domain managed at WHM/CPanel level instead of server wide.  Also if the site is not being pegged for an update, there had better be a strong reason for it and someone needs to document what security measures are being taken to keep those sites safe.  Considering there are properties running EOL software (Joomla 1.5) on EOL PHP versions, and the latest round of security issues which JSST felt important enough to patch for unsupported software, there are now significant security issues for running anything < PHP 5.6 and Joomla 3.4.7.

**Comment by Radek-Suski** [comment]
Could we have a check list of sites that aren't compatible.
As I can see events site is running currently on 5.4.38

**Comment by mbabker** [comment]
For the Joomla installs, any remaining 1.5 sites are iffy on 5.5 or 5.6.
Don't know enough about phpBB to speak on its needs.  Everything else
should be upgradeable I think.

**Comment by Radek-Suski** [comment]
So basically community.joomla.org ( @sanderpotjer ) I guess

**Comment by mbabker** [comment]
jdev002 (PHP 5.6) and joomla-org (PHP 5.6) servers are updated.  joomla-misc cannot be updated as long as we have 1.5 installs on it.  And I can't speak for JED or the forum on what it'll take them to update.

**Comment by mbabker** [comment]
@joomla/webmasters Anyone got an issue with the `joomla-misc` server being upgraded to MySQL 5.6?  Rochen opened a ticket and want to upgrade that server's MySQL and PHP versions; I've already given guidance this isn't feasible at the moment for PHP but I want to make sure MySQL isn't an issue.

**Comment by jeckodevelopment** [comment]
@sam-suresh please check compatibilty for the Exam Platform.

**Comment by anibalsanchez** [comment]
I'm late to the party! Michael kindly point me to this ticket. 

https://vel.joomla.org/ is also running on PHP 5.4.

**Comment by jeckodevelopment** [comment]
@mandville can you please check?

**Comment by mbabker** [comment]
@joomla/webmasters Since so many have been looking to update the server to PHP 5.6, we're looking into options to move the showcase site and let everyone else get updated.  With that said, so we can move quickly when we reach an actionable point, please confirm your sites will run without error on a PHP 5.6 build.

**Comment by Sandra97** [comment]
The landing page works fine on PHP 7 so I presume we should not have any issue on PHP 5.6.

**Comment by mbabker** [comment]
It's already on a 5.6 server (live and sandbox), not too worried there.  It's our "catch all" server that has everything I need confirmation on.

**Comment by jeckodevelopment** [comment]
@mbabker can you publish a list of websites on that server so each webmaster can "check and confirm" with a task list here?

**Comment by mbabker** [comment]
It's in the comments at the top of the issue 😉

**Comment by jeckodevelopment** [comment]
was it already there? (so, tbh i didn't scroll up previously)

**Comment by mbabker** [comment]
I added it when I added the all call.

**Comment by jeckodevelopment** [comment]
thank you Michael :D

**Comment by Sandra97** [comment]
JDocs can run on PHP 5.6

**Comment by wilsonge** [comment]
Magazine is good on php 7 so by definition assume it's fine on 5.6

**Comment by sam-suresh** [comment]
exam.joomla.org should work. 
I suggest set a fixed time window with Rochen and announce it to prevent people panic and shout!!  Site owners too can check during the upgrade time window for possible problems.

**Comment by mbabker** [comment]
That'll definitely be coordinated.  That's why I'm trying to do the leg
work now so things can move quickly because independently reaching out to
me and through tickets direct to Rochen almost every team with a site on
this server has tried to get it upgraded.

**Comment by jeckodevelopment** [comment]
certification.joomla.org and tm.joomla.org will work.

**Comment by anibalsanchez** [comment]
VEL has only RSforms

**Comment by jeckodevelopment** [comment]
@anibalsanchez RS Forms should work properly also on PHP 5.6

**Comment by jeckodevelopment** [comment]
@mbabker I guess that community.joomla.org will work properly, because it's a new version.
Right? @Joomv

**Comment by mbabker** [comment]
I make no assumptions because extension developers are slow to make their code compatible with anything new or to refactor away from "legacy" structures.  Just this weekend I made the mistake of turning error reporting on a dev site to full while working on PHP 7 with extensions released in the last few months that STILL use PHP 4 style constructors.

**Comment by jeckodevelopment** [comment]
yes, in fact I tried to involve also @Joomv who is in charge for CJO.

**Comment by Joomv** [comment]
I am pretty sure it will run 7 - although maqma could be an issue (only thing I haven't tested thoroughly on 7).  I think it would be sensible to go to 5.6.x first - then I can clone and test on 7 rather than a switch and pray, I don't think there are any blockers, but I like to err on the side of caution.

**Comment by jeckodevelopment** [comment]
thank you @Joomv 
We'll update to 5.6! :)

**Comment by Joomv** [comment]
I believe the installation of Cloud Linux will allow webmasters to set their php versions as a cpanel level, if so, then each site can tweak as they see fit.

Is this right?

**Comment by mbabker** [comment]
Correct.

**Comment by mbabker** [comment]
Even after CloudLinux was installed there are still a lot of sites running PHP 5.4...

**Comment by Joomv** [comment]
CJO is on 7 now.

**Comment by sebastienlapoux** [comment]
Hi,
Will be done on Showcase site some days after the launch of the new site J3, so in October.

**Comment by jeckodevelopment** [comment]
@sebastienlapoux , can I ask you why after the launch? 
Let me remind that, if there will be some compatibility issues, it could be useful to "discover" and fix them before the official launch.

**Comment by sebastienlapoux** [comment]
@jeckodevelopment because currently the old site is on J1.5. Current site and new one are one the same instance.

**Comment by jeckodevelopment** [comment]
ok, thank you for clarifying this!

**Comment by mbabker** [comment]
Unless there's a hidden directive somewhere the CloudLinux installation applies on a per-account basis (so each subdomain), not per-directory.

**Comment by wilsonge** [comment]
Just checked volunteers and it's running 5.6

**Comment by sanderpotjer** [comment]
https://volunteers.joomla.org is actually running PHP 7 now ;-)

**Comment by wilsonge** [comment]
I thought about it earlier but decided without testing might not have been a good idea :P

**Comment by sanderpotjer** [comment]
@wilsonge wise decision, a small fix was needed first

**Comment by mbabker** [comment]
Can we please close this out?  And if you're running a site where you legitimately cannot upgrade past PHP 5.4, tell us what you need to make it happen.

**Comment by jeckodevelopment** [comment]
@mbabker TM website is currently on PHP 5.4.
I don't have access to cPanel to pick a newer version. 
@SpiritJC can you please choose another PHP version?
Otherwise @mbabker can you please do it?

**Comment by MATsxm** [comment]
@jeckodevelopment any updates?

**Comment by jeckodevelopment** [comment]
it's done ;)

**Comment by Joomv** [comment]
Vel was done a while ago unless they have switched it back

**Comment by Joomv** [comment]
joom.la redirects to JCM this is the last on the list @MATsxm  - I think this can close now.

**Comment by MATsxm** [comment]
WOOHOO!
Thanks @Joomv 
closing - reopen if needed
