### ISSUE TITLE
Error: 1054 Unknown column 'lock_time' in 'where clause' [forum.joomla.org] 

### ISSUE THREAD

**Issue by hocaklanguage** [joomla/joomla-websites#1272]
Updated CMS to Joomla 3.9 and front end and back end of site crashed. Checked the host about server updates, everything was working on their end. 
![screen shot 2018-12-06 at 3 25 54 pm](https://user-images.githubusercontent.com/45609645/49670629-e3aaeb80-fa2a-11e8-84b6-1e498cab3f36.png)

**Comment by mbabker** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
