### ISSUE TITLE
Form fields -> predefined lists is a 404 error

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1275]
https://docs.joomla.org/Predefined_List_form_field_type

It's a 404.  I came from:

https://docs.joomla.org/Special:MyLanguage/Standard_form_field_types 

So perhaps just remove the link if it's not relevant.

**Comment by Sandra97** [comment]
All the red links on this page are pages that should have been created but have never been... 

This page didn't get any update or nearly since nearly 3 years. I wish some would help to update JDocs, but I'm dreaming...

**Comment by conconnl** [comment]
@wilsonge would you be able to provide me some information.
I think I will be able to create the page.

I found this file:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/predefinedlist.php
And this folder where it seems to be used: https://github.com/joomla/joomla-cms/tree/staging/libraries/src/Form/Field

Wasn't able to find an XML example.

**Comment by wilsonge** [comment]
Wrote a basic page contents for you https://docs.joomla.org/Predefined_List_form_field_type before i realised you were volunteering to do it yourself 😅 sorry! Could do with a bit more love so feel free to expand.

Good example is the request status field: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_privacy/models/fields/requeststatus.php

XML Example: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_privacy/models/forms/filter_requests.xml#L15-L23

**Comment by conconnl** [comment]
Great that you completely took care of it and the additional information.
You are more knowledgeable then me, if I would write it, I would also asked you to review it.
Another issue solved, thanks.
