### ISSUE TITLE
Install is not possible in Joomla 3.9.1

### ISSUE THREAD

**Issue by kiwidesign** [joomla/joomla-websites#1276]
Hi,

my problem is that the installer does not allow me to install any apps.
Either from the web or from the zip file.
Can you please help me?

Thanks.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
