### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by almotter** [joomla/joomla-websites#1277]
I recently created flittalk.joomla.com. I wanted to delete it but the password isn't matching and it won't let me reset the password. What do I need to do to delete this empty site? Thanks.

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
