### ISSUE TITLE
[jlaunch] CCP loading new site with 3.9.1 not 4.0-alpha 6; terminating old site too early

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-websites#1278]
On 22 December I created a sub-domain on joomla.com which had the Joomla! 4.0 Alpha 5.0 installed. Fine.
Yesterday - 30 December, so well within the 30-day renewal zone - I tried to access the site again (directly, not via CCP panel) and it came up with a 'Server not found' error. I logged into CCP and discovered the site had been terminated, despite being only 8 days old.

So, I tried again with a new account and new site and discovered the following:

1. It has been installed with Joomla! 3.9.1 and not 4.0 Alpha 6.0 as expected
2. It is running on "PHP 7.0.33 which is obsolete and no longer receives official security updates by its developers" (this was the same on the Alpha 5.0 site on 22 December. I reported this at the time but had no response)

I have reported the issue on CCP but, as there was no response the last time, I am also reporting it here.

UPDATE: I am able to update the PHP version from within the CCP account, but not the Joomla version. There is a video of how to change the PHP version here: [https://www.cloudaccess.net/cloud-control-panel-ccp/158-server-management/1026-changing-php-versions.html](url)

**Comment by jonathanCA** [comment]
Thanks for bringing this to our attention, we will check on these items immediately. Please DM me the URL to the site in your account.

**Comment by Scrabble96** [comment]
Hi, thanks. I'm not sure how to DM you on here so I'm sending you an email.

**Comment by jonathanCA** [comment]
Our team has looked closely at the case and found our logs show "Renewal Period" was changed to "Daily" under the Advanced Options during launch. This caused the site to terminate the day after launching. The purpose of the "Daily" option is to allow people to create sites used for a quick test, not to keep on a permanent basis. We recognize that the wording/description needs to be improved to ensure it does not cause anyone else's sites to be inadvertently removed without their knowledge. Our team will make updates to that dropdown option ASAP. 

Regarding the version that was provisioned, this is less of a clear case. Our logs show that Joomla 4's latest build was selected on launch.joomla.org, and that was the version that was provisioned. We have thoroughly tested, and we have not been able to reproduce the issue of this scenario resulting in a Joomla 3.9 site. Our team has also been closely monitoring provisioning and looking for other cases, but we have yet to find one. At this point, we are left to assume that it was an isolated case. 

Again, thank you for bringing this to our attention. If you see the need for us to investigate anything further, please do let us know.

**Comment by jonathanCA** [comment]
Just following up, this can be closed.
