### ISSUE TITLE
[JED] Error message when updating an extension

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1280]
Someone reported at Joomla Forum an error with a language string at JED:
https://forum.joomla.org/viewtopic.php?f=262&t=968488

> Your form contains missing or incorrect information. Please correct the errors and resubmit the form: We can't deterime that the text in 'Description' is English. It could be that you just need to write a bit more...

Could someone please change "deterime" to "determine"?
Thanks!

**Comment by anibalsanchez** [comment]
The issue was caused by a recent system upgrade.

Now, I've just upgraded the library that has not been working right.

Please, try now. Issue solved :+1:

**Comment by pe7er** [comment]
Thanks @anibalsanchez !
