### ISSUE TITLE
Phishing Report <http://smilesresgate.joomla.com/b1/index1.php>

### ISSUE THREAD

**Issue by gssilveiraaa** [joomla/joomla-websites#1282]
Dear Abuse/Support Team,

We detected a phishing website hosted at:
 
	http://smilesresgate.joomla.com/b1/index1.php
 
	Hostname: smilesresgate.joomla.com with IP: 104.37.86.30

 This fake website was created to attack Banco do Brasil's website and its customers. The organization's legitimate website is:
 
	http://www.bb.com.br/

We kindly ask your cooperation, according to your policies, to cease this activity and shut down the phishing page as soon as possible.
 
Thanks in advance. We would also appreciate if you could provide a confirmation that this message has been received and an estimate of the time to shutdown.
 
Best regards,
CSIRT Axur
+55 51 4042-2987 
www.axur.com
 
This report was adapted from the model provided by CERT.BR (http://www.cert.br/docs/whitepapers/notificacoes/)

**Comment by jonathanCA** [comment]
Apologies for the delay, this has been taken care of. 

For reference, our abuse@cloudaccess.net email goes to the proper team. I'll have our team post information about this at the bottom of the launch.joomla.org page
