### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Drive4you** [joomla/joomla-websites#1283]
I have used Joomla on some sites and have changed to WordPress, but still I get the update email fron Joomla.
How can I stop it?

BR
Henrik

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
