### ISSUE TITLE
[launch] Strange field when registering new sub domain with known email

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1284]
I was trying to create a new sub domain on the launch service. After providing the details on the first screen launch recognized my email address.

There is an option to login but the field used a bit unclear because the field used is a bit large so it doesn't look like a password field which I guess it is. (I don't have my previous password anymore so I can't test).

![launch-login](https://user-images.githubusercontent.com/7062995/50812460-235b4080-1313-11e9-93d0-73d6f3bac55e.png)

**Comment by Sandra97** [comment]
If you enter your password, it works fine. 
(I agree with you that it doesn't look like a password field).

**Comment by jonathanCA** [comment]
Thank you for pointing this out, I agree it doesn't look like a PW field. Our team will make the appropriate improvements here. Closing.
