### ISSUE TITLE
[jdocs] Lost permission to edit documentation wiki while editing an article

### ISSUE THREAD

**Issue by efduggan** [joomla/joomla-websites#1286]
It appears that I lost the “Email Confirmed” status on my account while editing an entry on the documentation wiki. I posted a detailed message in the forums explaining what I was doing and have been looking for an answer and solution. See the post here -> https://forum.joomla.org/viewtopic.php?f=303&t=968654.
 
Toivo suggested I post here to hopefully get a solution so that I can get back to contributing to the community.

**Comment by efduggan** [comment]
Thanks for the prompt reply. I’ve been using efduggan for all the accounts I have in *.joomla.org websites.

**Comment by Sandra97** [comment]
I confirm our bot blocked you for abuse. I granted you the permissions you had previously. Hope it will be ok now.
You can edit the content, but please do not add any translation tag (I will add them).

Can you confirm me it's now ok?

**Comment by efduggan** [comment]
Yes, Sandra, I’ve been able to log in and edit the documentation. I’m not sure how I set off the bot, but I’ll be very careful to avoid triggering it again. Thanks for solving this issue.
