### ISSUE TITLE
[joomla.org]

### ISSUE THREAD

**Issue by kallegotting** [joomla/joomla-websites#1287]
Hi!
We are having a webiste hosting by you and the website is down. The error message we get from going in on "wadur.com" is following text:

Database connection error (1): The MySQL adapter 'mysql' is not available. Warning: session_write_close(): Cannot call session save handler in a recursive manner in /customers/5/8/7/wadur.com/httpd.www/libraries/joomla/session/session.php on line 681 Warning: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) in /customers/5/8/7/wadur.com/httpd.www/libraries/joomla/session/session.php on line 681

You can contact me on following e-mail adress: karljohangotting@hotmail.com

Best regards 
Karl-Johan Gotting

**Comment by mbabker** [comment]
Hi,

The Joomla project does not host any websites on behalf of end users.  Joomla is the software which is powering your site.

For user support issues, you can use one of the following platforms:
- Joomla! Forum (https://forum.joomla.org/)
- Joomla! Documentation (https://docs.joomla.org/Main_Page)
- Joomla! Resources Directory (https://resources.joomla.org/)
