### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by bradpatt** [joomla/joomla-websites#1289]
I believe that my registration as a super user on the below sites has been hacked and I can not access the sites.

- inverellaquatics.com.au
- eurobodallaaquatics.com.au
- communityaquatics.com.au
- macksvillemafc.com.au

Can you assist me?

I try to go via the forgotten password option, but the site keeps saying my user names and passwords do match or don't exist.

With thanks,
Brad
bradpat@bigislandsports.com.au
brad@communityaquatics.com.au

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page or follow this [tutorial](https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F)
or find a service provider at https://resources.joomla.org/

Thanks!

**Comment by bradpatt** [comment]
Thank you, Sandra97. 

Will look at those links today,

Cheers,
Brad
