### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mocha365** [joomla/joomla-websites#1290]
two issues... one, no one is replying to my tickets, and two, each time I reply or update my ticket, I get this "An error has occurred while processing your request. It happens to the best of us!" and below it says I can only respond to my own tickets. Um, this is my ticket that I am responding to. I've been waiting months for TM approval and no one is replying.

**Comment by PhilETaylor** [comment]
> I've been waiting months for TM approval and no one is replying. 

You might want to update your issue title to something more interesting to get the TM teams eye

Also they moved ticket system and seem to have abandoned all old tickets (although they say they migrated them, Ive yet to hear of anyone getting a reply)

Lastly on twitter today @joomla was saying to start again using the TM Forms on the TM site. https://tm.joomla.org/contact.html

**Comment by Sandra97** [comment]
@moc Did you finally get an answer?

**Comment by conconnl** [comment]
[Closed] - No reply from requestor since July 2019
