### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by may33** [joomla/joomla-websites#1294]
Hi,
They're a coule of day I observed that from the backend menu item, the field to select the template there is not. Does anybody know why?
Thanks a lot, bye.

**Comment by Sandra97** [comment]
Hi, 

It's a known issue introduced in 3.9.2. It will be solved in 3.9.3 which is planned to be released tomorrow (Tuesday 12th).
Please see: https://github.com/joomla/joomla-cms/pull/23556

I'm closing this issue as this repository is ONLY for reporting issues with the `*.joomla.org` websites, not about the Joomla! CMS.
