### ISSUE TITLE
[j3.9.2] 

### ISSUE THREAD

**Issue by PC-Rat** [joomla/joomla-websites#1296]
Hi!
After updating to J3.9.2 the com-contact interface disappeared from admin panel, So, I can add contacts only in DB and need to use third-part components to do smth with them.

More than that, scroll in the multicolumn dropdown menu does not work too. http://new.magiclife.su

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

If you found a bug in the CMS, please report it at issues.joomla.org

Thanks!
