### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by AsmKrblt** [joomla/joomla-websites#1297]
I was open administrator page of my site. And I tried to login. But I couldn't remember my password. After multiple tried to login, the site has now blacklisted my IP address. I can't reach my administrator page and my site. 

 how I can correct this issue?

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
