### ISSUE TITLE
[forum.joomla.org] can't login anymore

### ISSUE THREAD

**Issue by 7at1blow** [joomla/joomla-websites#1298]
Hello board admins fo forum.joomla.org,

could you please help me, I can't login anymore in forum.joomla.org since I've been also registered in docs.joomla.org, see also attached screen shot.

I also get no e-mails if I choose the opportunities "forgot password" or "resend activation e-mail"

![joomla org forum login problem](https://user-images.githubusercontent.com/42974861/52916714-4221ff00-32e3-11e9-8b2e-f74a3bea8463.png)

Thank you in advance

**Comment by Sandra97** [comment]
Hello,

Could you please report your issue in this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

Thanks

**Comment by Sandra97** [comment]
Closing this issue. Re-open if needed.
