### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by rcbiz5000** [joomla/joomla-websites#1299]
Dear Sirs: I am writing in regards to the unnecessary complexity of modifying Joomla and it's extensions - such as Jomsocial. I realize that Jomsocial and others are likely not being developed by the actual authors of Joomla, however they are all being made to fit the Joomla format.

If the developers of Joomla streamlined their format, then the 3rd party developers would of course have to follow suit. One example of this is in Jomsocial, wherein one might desire to simply change the (Front Page Jomsocial Image) and it's associated text (GET CONNECTED - Come & join our community...) text. That image & those words will of course be the FIRST things most people will want to change, but the procedure in doing so is so convoluted, that it has taken DAYS to figure out how to change the photo as well as the actual words themselves. 

Now it's VERY POSSIBLE that i'm doing it wrong, but I scrounged all through the directions and online forums to get help and this is all I could find.
 
So in changing the (Get Connected) text, I had to (Do a search) for the words, and then edit them in the module that came up from the search.. really? This  is very reminiscent of the early "Compuserve" days where everything had to be typed out and on-screen graphics didn't exist. 

The image was changed by logging in as Admin > Theme Designer > General.... then change the photo. Ok easy enough - perfect! However, the "Get Connected" text can not be changed there, nor the colors of the text. I actually haven't even figured out how to change the "Get Connected" colors yet - which is just outrageous!! Why is something so basic so labyrinthian??? 

I think that Joomla has the potential to literally DOMINATE the world of community building, if only you would streamline these operations and make them FAR more intuitive than they currently are. 
In addition, it should be a requirement that all 3rd party developers maintain AT LEAST a (live chat) module during business, for a minimum of 4-6 hours per day M-F, as well as an email address where tech issues can be dealt with on a fast & direct manner. Just posting to a public forum and keeping your fingers crossed is not really "OK" after shelling out hundreds of dollars, and even more for templates & extensions.

I would also like to add that the (Override) system is kind of going the right direction, but who knows what options to select to get the desired results? What would I select in override to change the front page font, text & colors?? It's a nice system, but useless without knowing how to apply it to a desired area. One forum post said that we have to use a (Developer Inspector) in Firefox or Chrome to find the proper naming conventions...  that's just crazy.  

Please consider streamlining the modification & override process with better & more comprehensive instructions - and making the whole thing more intuitive and in line with WYSIWYG conventions & formatting. Thank you.

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
