### ISSUE TITLE
[jcomm] Review and Update Leadership Page Content

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#13]
http://www.joomla.org/about-joomla/the-project/leadership-team.html

Looking at and reviewing links, formatting and content on this page to be up to date as possible.

**Comment by jessicadunbar** [comment]
Does this need an update?

**Comment by pbwebdev** [comment]
yep, Isidro has left leadership and I think Tessa's bio needs to be added here since she has moved from OSM to PLT. Looks like Dianne Henning has already removed her profile. Would be worth asking if the info in the bios are all up to date to. They look like they are.

Also, just being picky, but a "clear:both" would be really nice on the starting paragraph after the bio pics of the bio to clear the text wrapping.

**Comment by jessicadunbar** [comment]
I requested Tessa's Bio and moved both isidro and dianne to the honor roll http://www.joomla.org/about-joomla/the-project/honor-roll.html

http://www.joomla.org/about-joomla/the-project/leadership-team.html is a category layout, each of the bio's are individual articles. I added the "clear:both" and it messed up the formatting. (probably a user issue) I added a non break space for now. Is it better or worse? :)

**Comment by pbwebdev** [comment]
Woot! Thanks Jess. Looks better on page. I just won't inspect the code. I wouldn't spend too much time on it considering the site will be updated and content will be reviewed again at that point.

Just Tessa's bio and I'll close it off.

Thank you

**Comment by jessicadunbar** [comment]
added tessa, closing

**Comment by brianteeman** [comment]
The top of that page includes OSM
> Open Source Matters (OSM): responsible for managing all legal and
financial affairs for Joomla and also the Joomla demo sites.

But they are not listed.

On 6 August 2015 at 00:00, jessicadunbar <notifications@github.com> wrote:

> added tessa, closing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/13#issuecomment-128175891>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Ignore that I saw the link lower down
