### ISSUE TITLE
[jdocs] I think you mixed controller code with view code

### ISSUE THREAD

**Issue by alisherdavronov** [joomla/joomla-websites#130]
https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_a_view_to_the_site_part

Code Explanation

controller.php

I think you mixed controller code with view code

in code "function display($tpl = null) {...}" is in HelloWorldViewHelloWorld class, but in explanation it is in HelloWorldControllerHelloWorld class

**Comment by alisherdavronov** [comment]
here https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_a_model_to_the_site_part
problem with the object of the topic

1) by the title of the article it is a model;
2) by the 1st paragraf of "Adding a Model to Hello World!" section it is a view;
3) by the 2nd paragraf it is a menu

**Comment by MAT978** [comment]
Hello @alisherdavronov and thank you for taking the time to report this.

As a Wiki, The Joomla! Documentation is a participatory system and allows all registered users to correct, update, talk about, translate or create new content.
As mentioned on the Doc website, this "GitHub Issue Tracker", is only in case you are experiencing **technical issues** with https://docs.joomla.org.

To register, please fill out the following form and then you will be able to contribute with your change:
https://docs.joomla.org/index.php?title=Special:UserLogin&type=signup
If necessary, do not hesitate to contact me.

Thank you in advance for being part of the Community .

(closed as content issue)
