### ISSUE TITLE
Joomla template Morph

### ISSUE THREAD

**Issue by nblancodl** [joomla/joomla-websites#1300]
Hello, I have install the Morph template in my Joomla administrator but when I set it as default it doesn't update to this template, it remains with the past that I had installed. I need to set as default the Morph template for my web page. 

My name is Natalia Blanco, my email is nblancodl@gmail.com and my domain is compgenioss.com

Thank you, I will pending to your answer.

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
