### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by magskate** [joomla/joomla-websites#1301]
Hi,
our website is not working
westfieldvillage.co.uk

Error message:
Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /home/westfie3/public_html/libraries/vendor/joomla/registry/src/Format/Json.php on line 12

Please contact me urgently.
Kate 07917153693

**Comment by mbabker** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

For what it's worth, your issue looks to be running an old version of Joomla on a PHP 7.x version.  You need to update Joomla.
