### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Harmon777** [joomla/joomla-websites#1302]
I can not log into my account.  
I get an error that user name and
password do not match.  I am also
told that my email, ha@jpstudent,
does not exist.  I have been using this
email address for years at Joomla Shack.

I have also had this problem, described above,
several times in the past where I could no longer
sign into my account.  I am a lifetime member of
the University.
Harmon H Adams
6331 Flat Rock Dr
Flowery Branch, GA 30542
678-343-9182

**Comment by Sandra97** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS or extensions.

If I understood well, your issue is with your JoomlaShack account. Please contact them directly.

Thanks
