### ISSUE TITLE
[jansenbaba] 

### ISSUE THREAD

**Issue by jansenbaba** [joomla/joomla-websites#1305]
my joomla backend is still showing a white page, i have tried all online solutions but it still show a whitepage. i have created a new subdomain and all my modules and media is lost. please help fix it.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
