### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by thedarkknight228** [joomla/joomla-websites#1306]
Hi

We have a website called southdublinswans.com and it doesn't seem to be working.

When I go into southdublinswans.com/administrator it looks all weird.

![image](https://user-images.githubusercontent.com/5768640/54266023-77321200-456e-11e9-9bcf-d485e3f465de.png)

Would you know anything about this?

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
Thanks!
