### ISSUE TITLE
[jshow] User is blocked please report to administrators

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1307]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

showcase.joomla.org says my user is blocked eoin@squareballoon.co.uk.  Not sure if my account has done something wrong or if it's blocked because of length or time or something but I guess I'd like it to be unblocked.

**Comment by uglyeoin** [comment]
Ignore this I solved it myself.  Email went in junk.

**Comment by sebastienlapoux** [comment]
Thanks!
