### ISSUE TITLE
[como se descarga el paquete de idioma Epañol?] 

### ISSUE THREAD

**Issue by agrimarcal** [joomla/joomla-websites#1308]
Please describe the problem or your issue

**Comment by agrimarcal** [comment]
como se descarga el paquete de idioma? no puedo hacerlo

**Comment by zero-24** [comment]
Please checkout this page: https://community.joomla.org/translations/joomla-3-translations/spanish-translation.html
and this Download packages: http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6445

For any for further questions please use the Forum at https://forum.joomla.org

---

Por favor, visite esta página: https://community.joomla.org/translations/joomla-3-translations/spanish-translation.html
y estos paquetes de descarga: http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6445

Para cualquier otra pregunta, por favor utilice el foro en https://forum.joomla.org

[(Translated by DeepL)](https://www.deepl.com/translator)
