### ISSUE TITLE
Error adding new site [jshow] 

### ISSUE THREAD

**Issue by Martijn-Boomsma** [joomla/joomla-websites#1309]
I added one new site (exact.com) and wanted to add some more but when submitting I get the following error:
![afbeelding](https://user-images.githubusercontent.com/1172056/55221681-50c8d380-520a-11e9-869b-77cd501dd5b9.png)

**Comment by sebastienlapoux** [comment]
Hi @Martijn-Boomsma ,

Sorry, we're not able to reproduce your issue, can you please post a screenshot of your form values which make this error after submission?

We moderated your exact.com website (IMO to not be able to say no to Analytics Cookies is not legal).

Thanks Martijn!

**Comment by Martijn-Boomsma** [comment]
Hi @sebastienlapoux !,

Thank you. I'm still getting the same issue:
![firefox_2019-03-29_11-08-15](https://user-images.githubusercontent.com/1172056/55225576-3b0bdc00-5213-11e9-8c8f-ccd2f74ae54c.jpg)

Is it & or " characters that give an issue?

**Comment by sebastienlapoux** [comment]
Thanks @Martijn-Boomsma , working on it.

**Comment by sebastienlapoux** [comment]
Hi @Martijn-Boomsma ,

Fixed, it was specific to the "Non-Profit Organization" category.
Please try again and let us know.

Thanks.

**Comment by Martijn-Boomsma** [comment]
hi @sebastienlapoux,
Great, thnx!  It worked.

> Message
>Showcase successfully saved. Thank you!
