### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Semideusnet** [joomla/joomla-websites#131]
Download Error from Official? Extension:: Weblinks

http://withinsightband.com/administrator/index.php?option=com_installer&view=install#

Weblinks (By Joomla PLT)

The Web Links Manager allows you to add, edit and remove links to other web sites on your Joomla! web site, and organize them into categories. You can then display these links on your site, and optionally let visitors add new links.

Please confirm the installation by selecting the Install button
Extension Name: Weblinks
Install from: https://github.com/joomla-extensions/weblinks/releases

**Comment by Radek-Suski** [comment]
Sorry but I am not sure what are you actually trying to report hier.
Could you be more precise please?

**Comment by mikeveeckmans** [comment]
I think i know, if you try to update the weblinks by the update manager in the backend , it sometimes gives this error... had it on some sites , but when you retry after a while , it's working...

**Comment by Radek-Suski** [comment]
But how this is related to Joomla websites?

**Comment by mikeveeckmans** [comment]
not...

**Comment by Radek-Suski** [comment]
So closing then
