### ISSUE TITLE
[jcomm] google +

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1311]
As google + is now closed we should probably remove the ability to share to google +

**Comment by Sandra97** [comment]
We removed from our template, and I removed it from joomla.org and developer.joomla.org

**Comment by mbabker** [comment]
https://github.com/joomla-projects/plg_content_joomlarrssb is the plugin repo, PRs welcome if someone has some time

**Comment by pe7er** [comment]
PR: https://github.com/joomla-projects/plg_content_joomlarrssb/pull/18

**Comment by sebastienlapoux** [comment]
Thanks. Removing in progress on showcase.

**Comment by Sandra97** [comment]
@sebastienlapoux It's still not removed on the Showcase. Can you please remove it?
Same for the JCM, but I don't know who is currently managing this property
@sanderpotjer Please remove Google+ from the volunteers portal

**Comment by sebastienlapoux** [comment]
Thanks a lot @Sandra97 !

Done!
![image](https://user-images.githubusercontent.com/13470265/60493102-80c1c000-9cac-11e9-9497-de85e0c1c283.png)

**Comment by conconnl** [comment]
[Closed] - Property specific issues will be created where need.
