### ISSUE TITLE
[launch.joomla.org] How to login?

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-websites#1316]
Tried to create a j4 test site with my community credentials. It says I already have an account (which is true). But it just gives me a textarea which I have no clue what to do with? Also there's nowhere else to log onto the page, so I'm effectively blocked from creating a new site. I also tried logging into https://ccp.cloudaccess.net from the old confirmation email (and taking a few guesses at the url) but that still didn't fix anything

<img width="1440" alt="Screenshot 2019-04-23 at 13 04 56" src="https://user-images.githubusercontent.com/1986000/56579792-f2083700-65c8-11e9-9ec9-c0b6df511158.png">

**Comment by brianteeman** [comment]
This was supposed to have been fixed last year - see https://github.com/joomla/joomla-websites/issues/1170#issuecomment-396991261

**Comment by jonathanCA** [comment]
Thank you for reporting, we are looking into this now.

**Comment by wilsonge** [comment]
Ahh ok it's not a text area - it's a password field. I somehow totally missed this. That works when I put in my password. But it's definitely not clear.

**Comment by jonathanCA** [comment]
Thanks for pointing this out George. I'm certain we have updated the text in the past to be more clear, not sure why we had some regression on the message. Our team has updated/simplified the messaging on that pop-up. 
![2019-04-23_1006](https://user-images.githubusercontent.com/1110530/56587492-a4cb9b80-65af-11e9-966a-823c4ab00185.png)

**Comment by wilsonge** [comment]
Awesome! Thanks!
