### ISSUE TITLE
[launch] Phising attempt?

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1317]
I spotted this mention on the Joomla twitter account:
https://twitter.com/yvesago/status/1122779431456710656

Stating this launch-website is/could be a phising website. 
https://zxiumbbrewi.joomla.com/

Personally, I can't tell it is or isn't but the "Zimbra Web Client" tells me something is fishy here...

**Comment by jeckodevelopment** [comment]
Can you please send an email to abuse@cloudaccess.net ?

Thank you

**Comment by hvdmeer** [comment]
Will do :)

**Comment by jonathanCA** [comment]
I've confirmed, our Abuse Team has taken care of this. Closing 

Thank you for reporting
