### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by GeisserS** [joomla/joomla-websites#1318]
Hallo,
Es wird "PLG_USER_TERMS_LOGGING_CONSENT_TO_TERMS" vom Administrator Modul "Aktivitäten-Neueste" angezeigt, wenn ein neuer User beim Anmelden die Nutzungsbedingungen der Internetseite akzeptiert. Es müsste aber der Inhalt der "de-DE.plg_user_terms.ini" angezeigt werden.

"PLG_USER_TERMS_LOGGING_CONSENT_TO_TERMS" is displayed by the Administrator module "Activity-Latest" when a new user accepts the terms of use of the website when logging in. However, the content of the "de-DE.plg_user_terms.ini" should be displayed.

Gruß Stephan Geisser

**Comment by pe7er** [comment]
Hallo Stephan,
Auf welcher Seite sehen Sie das Problem? Ist es auf einer joomla.org-Website? Dieses Repository für "joomla-websites" gilt nur für Probleme auf den offiziellen joomla.org Websites.

Ich vermute, dass Ihr Problem mit der Joomla CMS-Software zusammenhängt. 
Probleme mit der Joomla CMS-Software können (auf Englisch) unter: 
https://github.com/joomla/joomla-cms/issues gemeldet werden

Ich schließe dieses Problem. Wenn sich Ihr Problem auf eine offiziellen joomla.org Website bezieht, können Sie dieses Problem erneut öffnen.
