### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by charlottepacke** [joomla/joomla-websites#1319]
I had a website, but because I registered the domain name(it was with another graphic designer) , i have been unable to find my web designer to transfer the files into the 1&1 account. so NO website.
please help me. my website was charlottepacke.com

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
