### ISSUE TITLE
[jdown]  https://joomla.org/latest does not work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1320]
Hi!
Tried to reach https://joomla.org/latest but it does not work
thanks for fixing it!

**Comment by brianteeman** [comment]
just checked and it gave a direct download of the latest stable

**Comment by coolcat-creations** [comment]
@brianteeman its 0 byte

![grafik](https://user-images.githubusercontent.com/828371/56979158-60c13380-6b79-11e9-84d7-46020759bbd1.png)

**Comment by brianteeman** [comment]
sorry I didnt check the file size

**Comment by Sandra97** [comment]
I can't reproduce. It works as expected for me.

**Comment by coolcat-creations** [comment]
Yes probably the person who closed fixed the issue...
