### ISSUE TITLE
[jcomm] Link to the Brazilian Portuguese translation package is not working

### ISSUE THREAD

**Issue by helvecio** [joomla/joomla-websites#1323]
I've been alerted by an user that the link to the Brazilian Portuguese translation package is not working on https://community.joomla.org/translations/joomla-3-translations.html 
I checked the HTML and noticed the anchor next to the language title is missing. Who is able to update this page?

**Comment by Sandra97** [comment]
@Joomv Can you please take care of that? Many anchors don't work

**Comment by imanickam** [comment]
I took care of this.  There was a space (&nbsp;) in the place of "pt-br".  Corrected the issue.  I will review all the links.  It is not clear what happened.

**Comment by imanickam** [comment]
Other than Portuguese (Brazilian) the language entries of Portuguese (Portugal) and Romanian did not have anchors defined correctly.  Corrected them as well.

After the corrections, checked all the languages links and all of them are working correctly.

**Comment by Sandra97** [comment]
Thanks MIG. 
Therefore, I'm closing this issue.
Re-open if needed.
