### ISSUE TITLE
[jcomm] Password reset / change not possible

### ISSUE THREAD

**Issue by Astaco** [joomla/joomla-websites#1328]
Hi,

the password reset is no longer possible via the website.

I received your email today, that a password reset is required. When I try to login, it says that the password would be wrong. If I try to reset my password I get the error, that the email address would be invalid.

It is the same address you send the email to, saying a password reset is required. It doesn't matter if I use the domain gmail or googlemail (as used by you).

Not working after opening the website via this url:
https://community.joomla.org/blogs/leadership/jed-server-security-incident-report.html

With regards
Matthias

**Comment by Sandra97** [comment]
@joomv Can you please answer Matthias?

**Comment by Astaco** [comment]
@Sandra97  Thank you for pushing this topic now.

I tried to access my account today again via [https://extensions.joomla.org/](https://extensions.joomla.org/). This time it worked and I was asked to change my password as intended. I don't know if you changed something in the backend or if the login method had an issue.

I am not sure if you want to close this issue now or if you would like to look into it to debug what might have happened in you backend.

Thank you for you support. In case there are any questions I can answer, feel free to ask me aswell.

**Comment by jeckodevelopment** [comment]
I'm not sure what is the issue reported here.
As stated also by Matthias, accounts are not shared across the properties, so to reset JED password there is the need to go to extensions.joomla.org and reset the password. 

Afaik, nothing changed in the backend of JED

**Comment by conconnl** [comment]
[Closed] - No response after a long period
