### ISSUE TITLE
[jorg] Wrong menu item set to active when entering "Contribute" item

### ISSUE THREAD

**Issue by isidrobaq** [joomla/joomla-websites#133]
When you browse this page in main j.org site

https://www.joomla.org/about-joomla/contribute-to-joomla.html

"About Joomla!" menu item is set to active (and therefore, highlighted) instead of "Contribute" item in secondary top menu.

![wrong_active](https://cloud.githubusercontent.com/assets/6462715/10342699/a26f0ee4-6d1a-11e5-8796-4ab4975cb9b4.png)

**Comment by Sandra97** [comment]
Contribute is in fact a sub item of About Joomla menu. 
Contribute item in the toolbar menu is an external URL menu type linked to that sub menu. 
Fixing it now has more disavatanges than advantages (SEO). It should be fixed during phase 2 (content cleaning).

**Comment by mbabker** [comment]
This was fixed.
