### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by TrevorBray** [joomla/joomla-websites#1331]
The Learn Joomla link on your home page seems to be broken. The error it reports is:

This redirect url is not allowed, you should change the "Allowed domains for the redirection via the module" parameter from the AcyMailing configuration page to "joomla.org|developer.joomla.org|community.joomla.org" to allow it or set it to "all" to allow all urls

Can I do anything to regain access to your YouTube training videos?

**Comment by Sandra97** [comment]
@Joomv Can you please take a look?

**Comment by TrevorBray** [comment]
No solution?

**Comment by mbabker** [comment]
Fixed.

**Comment by TrevorBray** [comment]
Thanks!

**Comment by 70shakeel** [comment]
> Fixed.

kindly share solution
