### ISSUE TITLE
[joomla.org] Broken links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1335]
All the links on https://www.joomla.org/rss-news-feeds.html to a feed beginning with http://feed is broken

**Comment by Sandra97** [comment]
It seems to work for me 
http://feeds.joomla.org/JoomlaAnnouncements:
![index](https://user-images.githubusercontent.com/4682328/60123418-6e4c0180-9755-11e9-83dc-d8c6cfcaf5c0.png)

**Comment by brianteeman** [comment]
It is because of this policy in the security headers
`strict-transport-security: max-age=31536000; includeSubDomains`

This forces the browser to redirect to https (in supported browsers) and when those feed links are loaded over https you get the problem.

@zero-24

**Comment by zero-24** [comment]
Well I can not reproduce this but I agree this would be the expected behavior. What is the reason that feed.joomla.org does not ship via https?

**Comment by mbabker** [comment]
Who actually has access to FeedBurner to configure that stuff, let's start there.  Because AFAIK that's been on cruise control for the better part of the decade.

**Comment by conconnl** [comment]
For what I have been able to find, within the Feedburner configuration console.

The official feedburner address can run HTTPS (E.g.: https://feeds.feedburner.com/JoomlaSecurityNews), there is no feature available to run a feed on your private address with HTTPS, you can't configure a certificate anywhere.
In the case you want to use "feeds.joomla.org", the feed address must be (http://feeds.joomla.org/JoomlaSecurityNews) 

I don't know where feeds.joomla.org is running, how it's configured and generate the domain mask. I can't say anything about that.

**Comment by zero-24** [comment]
What about updating the links for now to the feedburner address?

**Comment by conconnl** [comment]
I agree with this, I don't know who is normally responsible for this and knows how the alias part is working. @jeckodevelopment any idea?

**Comment by jeckodevelopment** [comment]
It should be Marketing, so Eric.

**Comment by conconnl** [comment]
I asked Marianela to discuss this within marketing.

**Comment by conconnl** [comment]
Marketing (Marianela) replied that we can update the page and change the address to the official feedburner addresses. @jeckodevelopment do you agree with @zero-24 his idea?
Change feeds.joomla.org to feeds.feedburner.com

**Comment by jeckodevelopment** [comment]
agree with Tobias.

**Comment by conconnl** [comment]
All links needed an updated are changed, the following is for history purposes.

* http://feeds.joomla.org/JoomlaAnnouncements -> https://feeds.feedburner.com/JoomlaAnnouncements
* http://feeds.joomla.org/JoomlaSecurityNews -> https://feeds.feedburner.com/JoomlaSecurityNews
* http://feeds.joomla.org/JoomlaExtensions -> https://feeds.feedburner.com/JoomlaExtensions
* http://feeds.joomla.org/JoomlaDocumentation -> https://feeds.feedburner.com/JoomlaDocumentation
* http://feeds.joomla.org/JoomlaExtensionDirectoryEditorBlog -> https://feeds.feedburner.com/JoomlaExtensionDirectoryEditorBlog
* http://feeds.joomla.org/JoomlaSecurityVulnerableExtensions -> https://feeds.feedburner.com/JoomlaSecurityVulnerableExtensions
* http://feeds.joomla.org/JoomlaMagazine -> https://feeds.feedburner.com/JoomlaMagazine

**Comment by jeckodevelopment** [comment]
can then this be closed?

**Comment by conconnl** [comment]
Yup, everything is updated.
