### ISSUE TITLE
[jtm] Reply to own ticket results into 403

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-websites#1337]
I have a ticket on which I received a reply and now I want to reply back. So I log in with my credentials and type my reply then check the checkbox for giving my consent and click submit. 

Now I tried this already multiple times but it always goes to:
403 Unfortunately, you are not allowed to view this ticket. You can only view your own tickets.

Which is peculiar as it is my own ticket. I tried it with Chrome & Edge but both the same result.

**Comment by mandville** [comment]
Please confirm ticket number. Thanks

**Comment by hennysmafter** [comment]
Dear Mandville,

Please find below the ticket code:
TRADEMARK-38V8MV9BI5

Thank you for your reply!

**Comment by mandville** [comment]
The ticket is open and you should be able to respond to it. 
Thank you

**Comment by hennysmafter** [comment]
@mandville Thank you for opening the ticket but unfortunately we tried responding but still, we receive the 403 error.

On the 24th of June this year we also send an email which contained our original reply to your email address. Maybe we could communicate via email or shall I post the reply in Github?

**Comment by hennysmafter** [comment]
@mandville I just tried it again but I am still receiving this error. So I am posting it here now as I don't want to come over as entitled and I know Joomla is run by volunteers but we also need to continue with our work and we really need answers.

The link you gave in your first reply we want to thank you for that. We have seen that we needed to change a few logo's on the website and we did this then also immediately (this is already been done for lots of weeks).

Furthermore we would like to receive the permission for the conditional use logos. We would like to use it on our website http://loginsecure.eu

We hope to receive the permissions so that we can start with uploading our extensions to the JED.

Thank you very much for going out of your way to help us out.

**Comment by brianteeman** [comment]
As the terms and conditions for the software make it non gpl that will have to be addressed first

**Comment by hennysmafter** [comment]
Hello @brianteeman ,

I am not sure how you already received a copy of one of our extensions as we are not yet distributing them?

Or you just made the assumption that they are non-gpl but then please allow us to clarify all our extensions are either GPL 2.0 or GPL 3.0. 
All extension.xml files are fitted with either:

```
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
```

Or the 3.0 equivalent.

Thank you for your response and for all the contributions you have made to Joomla.

**Comment by brianteeman** [comment]
Based on the terms and conditions published here https://loginsecure.eu/legal/terms-and-conditions

**Comment by hennysmafter** [comment]
Hey @brianteeman ,

Unbelievable that I missed that. Thank you so much for pointing this out. We will make immediate work off that and will fix this promptly.

Once again thank you for your feedback!

**Comment by conconnl** [comment]
Closed -
No future comments after 6 months.
