### ISSUE TITLE
[jforum] 

### ISSUE THREAD

**Issue by jordantsap** [joomla/joomla-websites#1338]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

what it means when I register at https://forum.joomla.org
and it goes out
Note that you must enter a valid email address before your account is activated. You will receive an email at the address you have specified that will contain a link activating link.
while I get a coronal email?

**Comment by hvdmeer** [comment]
Hi @jordantsap . Is this question still valid? 
I'm not sure what you mean with coronal email but after registering on the Forum you should receive an e-mail containing a activate-link which you should click. If you didn't receive this email (and it's not in a SPAM folder) could you fill in this form?
https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by jordantsap** [comment]
It's so long ago that i don't remember the issue, coronal i guess it means correct?, i'm not sure.
I logged in to the forum for now, if that was the issue.

**Comment by jordantsap** [comment]
Is there any method of changing the username?

**Comment by pe7er** [comment]
@jordantsap So you can log in into Joomla Forum https://forum.joomla.org and you would like to change your username?

Could you check at https://forum.joomla.org/memberlist.php if the name you want, is still free?

The forum moderators need to authenticate your request. You can do that by posting a message in the **Sites & Infrastructure - Feedback/Information** board,
e.g. reply in this topic https://forum.joomla.org/viewtopic.php?f=7&t=552713
and state that you want to change your username and which new username you would like to have.
Thanks!

**Comment by pe7er** [comment]
I am closing this issue. 
Feel free to re-open this issue if it has not been solved with my previous comment.
