### ISSUE TITLE
Joomla[jdown] 

### ISSUE THREAD

**Issue by nokuchi** [joomla/joomla-websites#1342]
I've been trying to demo Joomla. They had me sign up on their cloud service. Never got the email, can't contact support without an active account which I don't have because I never got the verification email. So, I clicked the "report an issue" button and here I am, reporting this issue. The email I used is this one, 4pc@gmx.com. I got the verification email from you guys, but nothing from Joomla or their cloud service. And yes, I checked spam.  Can you help?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/62883504-192b7580-bd2c-11e9-9c69-3ecbf565a225.png)

![image](https://user-images.githubusercontent.com/1296369/62883573-437d3300-bd2c-11e9-9a18-6ee93e781402.png)

**Comment by nokuchi** [comment]
I got your email. I get other emails. I forwarded you the email I received from GitHub.
On 12-Aug-19 20:09:09, Brian Teeman <notifications@github.com> wrote:
[image] [https://user-images.githubusercontent.com/1296369/62883504-192b7580-bd2c-11e9-9c69-3ecbf565a225.png]
[image] [https://user-images.githubusercontent.com/1296369/62883573-437d3300-bd2c-11e9-9a18-6ee93e781402.png]

**Comment by nokuchi** [comment]
You realize you sent this "bad email address'" report to the "bad'" email address and I received it and replied, right?
On 12-Aug-19 20:09:09, Brian Teeman <notifications@github.com> wrote:
[image] [https://user-images.githubusercontent.com/1296369/62883504-192b7580-bd2c-11e9-9c69-3ecbf565a225.png]
[image] [https://user-images.githubusercontent.com/1296369/62883573-437d3300-bd2c-11e9-9a18-6ee93e781402.png]

**Comment by brianteeman** [comment]
All I am saying is that two testers had problems

**Comment by jonathanCA** [comment]
Hi there, it is also possible that you did not receive the activation email because your IP address may be a known source of abuse. You can check to see if it is listed here https://www.abuseipdb.com/

**Comment by nokuchi** [comment]
Okay, well, I don't know why that is happening. I've never had a problem before today and been using this for years. How do I fix this problem? Joomla is somehow associated with you but I have no way of contacting them or the cloud service. Neither offer a way to resend the verification email as far as I can tell.
On 12-Aug-19 20:21:59, Brian Teeman <notifications@github.com> wrote:
All I am saying is that two testers had problems

**Comment by nokuchi** [comment]
I see. That would be the IP of my VPN. It says it was reported but long ago. But that still leaves the question about how I get the verification emails again? I can change the IP where I am to my normal one but doubt that I will be able to sign up with the same email address again.
On 12-Aug-19 20:32:51, Jonathan <notifications@github.com> wrote:
Hi there, it is also possible that you did not receive the activation email because your IP address may be a known source of abuse. You can check to see if it is listed here https://www.abuseipdb.com/ [https://www.abuseipdb.com/]

**Comment by jonathanCA** [comment]
Hi Nokucki, we would like to help you get this sorted so that you can use the service. 

Please go to https://www.whatsmyip.org/  and copy the IP listed at the top. Once you have that IP copied, you can paste it into this https://www.abuseipdb.com to see if your IP has been used in the past for abusive purposes. Please report back on your findings.

**Comment by nokuchi** [comment]
When I use this service myou recomend, what's my IP, it gives me 77.111.247.222, which the abuse site says is not listed. So now what? Neither Joomla nor their cloud service will resend the verification emails, at least I cannot find a link to do so. I suppose the logical solution would be to forget about Joomla and continue with Wordpress, as much as it pains me to say that. I doubt it will allow me to create another account with the same email address and if I can't sign up with my email then what else am I to do?
On 12-Aug-19 20:39:45, Jonathan <notifications@github.com> wrote:
Hi Nokucki, we would like to help you get this sorted so that you can use the service.
Please go to https://www.whatsmyip.org/ [https://www.whatsmyip.org/] and copy the IP listed at the top. Once you have that IP copied, you can paste it into this https://www.abuseipdb.com [https://www.abuseipdb.com] to see if your IP has been used in the past for abusive purposes. Please report back on your findings.

**Comment by jonathanCA** [comment]
Hi Nokuchi, you had previously mentioned that you are using a VPN which is using an IP that is listed on https://www.abuseipdb.com   This scenario causes you to not receive any verification email. It is a silent failure which blocks many thousands of abusive free Joomla site launches each month. To use the service, I would recommend using your own IP (not through VPN) and a legitimate email address. The service will then work properly. 

I do hope that you choose Joomla, it is truly the better system. Please let us know if you see any further issues.

**Comment by Pawel-Panek** [comment]
Hi @nokuchi ,

What's your desired name for joomla.com site?

**Comment by Pawel-Panek** [comment]
@nokuchi 

I just checked and I see you've already signed up. I think we can close this case here and continue in our ticket system.
