### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by johnf-dfs** [joomla/joomla-websites#1343]
From https://docs.joomla.org/Article, the link for Content Article Manager for version 3.9 does not exist and results in a 404 error page.

And as a suggestion, maybe part of the Getting Started in the docs should include adding Users and user permissions.

---John---

**Comment by coolwebcreations** [comment]
The link issue is solved. Thank you!
User management is a part of the administrator manuals.

**Comment by Sandra97** [comment]
I'm closing this issue as it's solved. Thanks
