### ISSUE TITLE
[jvel] list over 1 year old

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-websites#1344]
the https://vel.joomla.org/live-vel url shows me a vel that stops in march 2018. Can this be updated?

**Comment by mandville** [comment]
Thanks for the notification,  we will investigate.

**Comment by mandville** [comment]
When a vulnerable extension is updated it is moved from LIVE to RESOLVED, perhaps this is why you are not seeing an up to date LIVE list.

**Comment by cloudfaction** [comment]
it kind of makes sense when you put it like that, but when someone looks at the VEL and the latest entry is over a year old, they could question if it is maintained... and questioning the validity of this list is a shame in my opinion.

**Comment by cloudfaction** [comment]
a better option would be an extra column with 'resolved' in it if applicable, I guess.

**Comment by mandville** [comment]
The API feed we are testing contains that sort of format, or you could use the basic search tool 
https://vel.joomla.org/articles/search

**Comment by mandville** [comment]
![vellist](https://user-images.githubusercontent.com/893049/63647760-09456580-c71e-11e9-9c35-b32828f33e4e.jpg)
Proving that the LiveVel is correctly showing VEL items , pre moving to resolved list.

**Comment by mandville** [comment]
![vellist](https://user-images.githubusercontent.com/893049/63647760-09456580-c71e-11e9-9c35-b32828f33e4e.jpg)
Proving that the LiveVel is correctly showing VEL items , pre moving to resolved list.
