### ISSUE TITLE
[JED] No verification emails

### ISSUE THREAD

**Issue by tomduebaeck** [joomla/joomla-websites#1347]
Hi guys, I cannot access my account at Joomla extensions and there is NO way to contact unless logged in!
The problem is, that I do not receive any verification emails from them.
Can you help?
What can I do?
same as here:
tomduebaeck
and tom@duebaeck.dk

I got your email straight away.

Thank you very much

**Comment by zero-24** [comment]
@anibalsanchez can you take a look here?

**Comment by anibalsanchez** [comment]
Sure. 

Hi @tomduebaeck, Thanks for reaching out!

We are processing the queue in the fastest possible that volunteers can answer. Every ticket must be checked, replied, and followed until it is finally solved.

Finally, for us to better assist you, please do not submit multiple tickets per issue, and refrain of contacting us personally or by other social media means. Duplicate requests will slow down response time and may delay resolution. We recommend that you do not update tickets unless it is absolutely necessary. Updated tickets are automatically sent to the end of the processing queue.

Best Regards

**Comment by brianteeman** [comment]
@anibalsanchez That copy/paste reply does not answer the question

**Comment by anibalsanchez** [comment]
The answer provides the first level of response (and avoids the rest of the messages that I'm receiving from several channels).

**Comment by brianteeman** [comment]
Still doesnt answer the question that was asked

**Comment by anibalsanchez** [comment]
There is a queue and everyone must follow the process. I'll answer as soon as I can.

**Comment by brianteeman** [comment]
You are not reading what they wrote.

**Comment by anibalsanchez** [comment]
Hi,

I've just checked your account. Your email server (mx-1.duebaeck.dk) is blocking our smtp server (SendGrid). So, JED emails are not being received and they are rejected.

I can manually reset your account (or it will be automatically removed in a few days), but the problem will remain since it seems that your mail server is blocking the SendGrid network.

Let me know if any action needed from our side.

Regards

**Comment by tomduebaeck** [comment]
Thank you very much.

 

Hopsteurope say they are not blocking anything… so I cannot get access to Joomla Extensions anymore… Sad as my site is built in Joomla.

 

I guess I will have to make a new in another cms…. Damn.

 

But maybe first you can try to please delete all data of mine in the system?

 

Tom Duebaeck

 

tomduebaeck

 

tom@duebaeck.dk <mailto:tom@duebaeck.dk> 

 

tom@soalrventi.es <mailto:tom@soalrventi.es> 

 

tom@mundodanes.com <mailto:tom@mundodanes.com> 

 

info@mobar.es <mailto:info@mobar.es> 

 

tom@mobar.es <mailto:tom@mobar.es> 

 

tom@idrinkonly.beer <mailto:tom@idrinkonly.beer> 

 

 

I think that’s it.

 

Thank you very much again.

 

 

 

Atentamente | Yours sincerely | Med venlig hilsen



Tom Duebaeck           

 <http://www.evergreen-electrica.com/> 

M. 699 652 895

E. tom@duebaeck.dk

 

C. Santo Tomas 20
29631 Arroyo de la Miel



T. (+34) 952 44 93 49

F. (+34) 952 02 55 54

P Por favor considere el medioambiente antes de la impresión de este correo electrónico 

  _____  

Este mensaje y los archivos adjuntos son confidenciales y se dirigen exclusivamente a su destinatario.

Si no es usted el destinatario indicado, queda notificado de que la utilización, divulgación y/o copia sin autorización está prohibida en virtud de la legislación vigente.
Si usted ha recibido este correo por error, por favor avísenos inmediatamente a través de correo electrónico o por teléfono, escritos en la parte superior, y tenga la amabilidad de eliminarlo de su sistema.

 

En cumplimiento del REGLAMENTO (UE) 2016/679, y en relación al tratamiento de sus datos personales, le informamos de lo siguiente:

Responsable: El responsable del tratamiento es MUNDO DANES, S.L., CL SANTO TOMAS 20 - BAJO 1, 29631, ARROYO DE LA MIEL, BENALMADENA (MALAGA)

Finalidad: Envío de información, respuesta a sus consultas y peticiones, mientras dure nuestra relación y tengamos su consentimiento.

Legitimación: Ejecución de contrato o consentimiento del interesado.

Destinatarios: No se cederán datos a terceros salvo obligación legal.

 

Derechos: Puede ejercer los derechos de acceso, rectificación, supresión y portabilidad de sus datos, y la limitación u oposición al tratamiento
mediante escrito acompañado de copia de documento oficial que le identifique, dirigido al Responsable del tratamiento.
En caso de disconformidad con el tratamiento, también tiene derecho a presentar una reclamación ante la Agencia Española de Protección de Datos.

  _____  

 

Fra: Anibal Sanchez <notifications@github.com> 
Sendt: 7. september 2019 20:25
Til: joomla/joomla-websites <joomla-websites@noreply.github.com>
Cc: tomduebaeck <tom@duebaeck.dk>; Mention <mention@noreply.github.com>
Emne: Re: [joomla/joomla-websites] [JED] No verification emails (#1347)

 

Hi,

I've just checked your account. Your email server (mx-1.duebaeck.dk) is blocking our smtp server (SendGrid). So, JED emails are not being received and they are rejected.

I can manually reset your account (or it will be automatically removed in a few days), but the problem will remain since it seems that your mail server is blocking the SendGrid network.

Let me know if any action needed from our side.

Regards

**Comment by tomduebaeck** [comment]
HI, HOST EUROPE NEED THE SENDERS IP TO EVEN SEE IF IT IS BLOQUED

 

THANK YOU

 

Atentamente | Yours sincerely | Med venlig hilsen



Tom Duebaeck           

 <http://www.evergreen-electrica.com/> 

M. 699 652 895

E. tom@duebaeck.dk

 

C. Santo Tomas 20
29631 Arroyo de la Miel



T. (+34) 952 44 93 49

F. (+34) 952 02 55 54

**Comment by anibalsanchez** [comment]
Hi,

We've reorganized our mail servers. Please, try to register again. If the issue persists, please, reopen the ticket.

Regards
