### ISSUE TITLE
[jorg] leadership announce blog wrong link

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-websites#1349]
Hi there,

in the leadership blog:
https://community.joomla.org/blogs/leadership/joomla-group-1-2nd-round-nominee-announcement-2019.html

The image of Holger Kremers is linked to somebody else. (his name is liked correctly to his profile).

**Comment by jeckodevelopment** [comment]
Hi Sigrid @webgras ,
thanks for reporting.

The link has been fixed.
