### ISSUE TITLE
Adverts in blog posts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1350]
Is this something we should be allowing. Placing adverts for the author on blog posts
![image](https://user-images.githubusercontent.com/1296369/65919634-dd7c6600-e3d4-11e9-8489-8f230d788361.png)

**Comment by Sandra97** [comment]
IMO, this kind of "promotion" shouldn't be allowed in blog posts. 
It's fine on the volunteers portal profiles and on the JCM profiles, but it's really awkward on a property like JED (same if it was on jorg, cjo or others). It should just be mentioned JED Team Lead, or any position within the project, not positions outside the project.

**Comment by brianteeman** [comment]
Closed without action?
