### ISSUE TITLE
[jtm] Error 403

### ISSUE THREAD

**Issue by ahmadm42** [joomla/joomla-websites#1353]
I am trying to reply to the Trademark Ticket but after submitting the reply the following error is shown: 

"403 Unfortunately, you are not allowed to view this ticket. You can only view your own tickets."
[https://tm.joomla.org/tickets/view-ticket.html](url)

An error has occurred while processing your request. It happens to the best of us!
Don't worry! There are no bugs without a fix!

**Comment by mandville** [comment]
We are investigating,/. please use the email to reply to the ticket
