### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by panishapamit** [joomla/joomla-websites#1355]
![anydesk00074](https://user-images.githubusercontent.com/56346752/66475047-2ce72400-eab0-11e9-9052-521d0d598b78.png)

Dear Admin,

Greetings from Spectra ISP Network, AS No. 10029.

One of our customers is unable to access portal https://downloads.joomla.org/ from IP series 180.151.230.170 - 174. We have enclosed error screenshot and also including the trace route report below:

traceroute to downloads.joomla.org (72.29.124.146), 30 hops max, 60 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  14.141.116.69.static-Delhi.vsnl.net.in (14.141.116.69)  14.233 ms  14.249 ms  13.883 ms
 6  172.23.183.161 (172.23.183.161)  42.114 ms  41.307 ms  38.967 ms
 7  ix-ae-0-100.tcore2.mlv-mumbai.as6453.net (180.87.39.25)  39.188 ms  45.480 ms  34.789 ms
 8  if-ae-2-2.tcore1.mlv-mumbai.as6453.net (180.87.38.1)  145.361 ms  143.583 ms  142.577 ms
 9  if-ae-5-2.tcore1.wyn-marseille.as6453.net (80.231.217.29)  142.155 ms if-ae-5-6.tcore1.wyn-marseille.as6453.net (180.87.38.126)  152.913 ms  151.408 ms
10  if-ae-8-1600.tcore1.pye-paris.as6453.net (80.231.217.6)  143.830 ms  143.754 ms  143.505 ms
11  if-ae-11-2.tcore1.pvu-paris.as6453.net (80.231.153.49)  151.237 ms  147.811 ms  147.737 ms
12  ae12.mpr1.cdg11.us.zip.zayo.com (64.125.14.49)  143.277 ms  143.009 ms  145.112 ms
13  ae27.cs1.cdg11.fr.eth.zayo.com (64.125.29.4)  255.428 ms  271.890 ms  289.296 ms
14  ae6.cs2.dca2.us.eth.zayo.com (64.125.27.2)  301.227 ms  259.044 ms  258.411 ms
15  ae0.cs1.dca2.us.eth.zayo.com (64.125.29.228)  286.389 ms  263.418 ms  265.797 ms
16  ae3.cs1.iah1.us.eth.zayo.com (64.125.29.49)  251.265 ms  254.952 ms  277.369 ms
17  ae5.cs1.dfw2.us.eth.zayo.com (64.125.28.99)  266.906 ms  255.321 ms  254.790 ms
18  ae1.mcs1.dfw2.us.eth.zayo.com (64.125.28.125)  268.743 ms  260.556 ms *
19  * * *
20  208.184.165.123.IPYX-142887-ZYO.zip.zayo.com (208.184.165.123)  255.711 ms  255.677 ms  257.389 ms
21  173.237.128.24 (173.237.128.24)  258.823 ms 173.237.128.22 (173.237.128.22)  252.875 ms  252.838 ms
22  206.123.69.165 (206.123.69.165)  256.251 ms 206.123.69.161 (206.123.69.161)  257.588 ms 206.123.69.165 (206.123.69.165)  254.851 ms
23  72.249.137.132 (72.249.137.132)  257.557 ms  255.581 ms  257.541 ms
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by panishapamit** [comment]
Awaiting Response - Please update

**Comment by HLeithner** [comment]
hi @panishapamit 

we contacted our hosting provider and it seams that the IP was on a blacklist. It has been removed could you please confirm that the problem has been solved?

thx

**Comment by panishapamit** [comment]
> hi @panishapamit
> 
> we contacted our hosting provider and it seams that the IP was on a blacklist. It has been removed could you please confirm that the problem has been solved?
> 
> thx

Yes it is now working. Thank you for your support.
