### ISSUE TITLE
[Launch] Phishing website on launch

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1358]
Via our @Joomla twitter account it was mentioned that the following subdomain is being used for phishing attempts.

proximo-hoje.joomla.com/includes/dep/choose.php

I tried sending this to abuse@cloudaccess.net but the mail was rejected probably due to a spam filter. Could someone look at this?

**Comment by jeckodevelopment** [comment]
@jonathanCA can you please look at that?
Thanks

**Comment by hvdmeer** [comment]
It seems the subdomain has been closed now so I'll also close this issue.
