### ISSUE TITLE
[jcomm] Events: The Map is showing an error

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1359]
As title said: https://community.joomla.org/events.html

**Comment by brianteeman** [comment]
You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

**Comment by brianteeman** [comment]
Not that anyone seems to care but this can be closed as someone changed the code to use openstreetmap
