### ISSUE TITLE
Install Module Issue

### ISSUE THREAD

**Issue by upstategirl** [joomla/joomla-websites#1360]
My Joomla is up to date but when I try to install modules from the web tab it is a blank white screen. I had asked about this a few weeks ago and I was told that the issues was fixed but I continue to have the same problem.

**Comment by mbabker** [comment]
For this issue, please use [the Joomla Forum](https://forum.joomla.org/) for support.  This repository is primarily meant for reporting and dealing with issues with the `joomla.org` websites themselves, not for assisting with issues with a user's website.

We can confirm the install from web server is up and running and I was able to install an extension without an issue.
