### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by upstategirl** [joomla/joomla-websites#1361]
is is what I am getting when I try to click the "Install From Web". I have tried reporting this issue twice and both times I am told that it is working properly. I have tried it in 2 different browsers and I have cleared the cache. I've attached a photo of what I'm seeing.

Thanks

![Screenshot (25)](https://user-images.githubusercontent.com/19862682/67134459-3a06c000-f1e0-11e9-9e94-e4bbdcc9382f.png)

**Comment by mbabker** [comment]
As has been said before, the server is online and functional.  https://appscdn.joomla.org/live/

This repository is not staffed to provide one-on-one troubleshooting assistance with issues on end user websites.  This repository is for reporting issues related to the `joomla.org` domains.

If you can provide information that points to an issue with your server connecting to a `joomla.org` service (a failing ping and/or traceroute would be key indicators), we can troubleshoot on our end to determine if there is traffic being blocked.  But without any kind of confirmation that there is a system level issue, at best all we can recommend is going to the forums for assistance where there are people who would be able to help you troubleshoot the issue to identify if it is an issue related to your site or server or if there is a legitimate bug in the software or if there is a legitimate issue with the `joomla.org` hosting architecture.
