### ISSUE TITLE
[jdown] 4.0 Tech Requirements & Unsupported PHP Documentation

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1362]
In the J4 installer we link to this page if someone has an outdated PHP version.  We refused to let them install.  I don't think we give them the version they require / their current so perhaps I'll do a pull request on that.

https://docs.joomla.org/Unsupported_PHP_Version

It would make more sense to link to this page, but it doesn't include the J4 requirements.

https://downloads.joomla.org/technical-requirements

As someone trying to patch test J4, I think it's really important we empower our users by giving them the info they need easily.  I had PHP7 installed but I remembered PHP7.2 was the minimum now.  I couldn't find that information anywhere when looking, so I am asking for this document to be updated to help people like myself or PBF communities to test J4 and help out a bit.

**Comment by mbabker** [comment]
Technical requirements will be updated when reaching RC phase.  Requirements aren't published for in-development versions to avoid more confusion.

**Comment by conconnl** [comment]
Closed - 
mbabker explained why their is no information yet, on the official documentation.
uglyeoin proposed that he creates a PR on the J4 development branch.

Not a Joomla-Website repository issue.
