### ISSUE TITLE
[jcm] Is there an RSS feed for the magazine?

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1365]
It strikes me as odd that the magazine is one of the places that doesn't have an RSS feed listed on the feeds directory.  Is this the case?

**Comment by WebSolutionZau** [comment]
I stepped down from the JCM in May 2019, I believe it is being redone by somebody else but I'm not up to date.

**Comment by conconnl** [comment]
I found this link: http://feeds.joomla.org/JoomlaMagazine
On the rss feeds page: https://www.joomla.org/rss.html
