### ISSUE TITLE
[jvel] RSS links don't work unless directly from feed

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#1366]
You can see examples towards the bottom of our dev site https://dev.joomlalondon.co.uk/

We are trying to use mod_feeds to include feeds from Joomla! resources.  But the links don't work.  The links are exactly the same as on the feeds pages e.g. http://feeds.joomla.org/JoomlaAnnouncements

It seems to be something to do with the redirect that doesn't work.  I can't see any difference in the URL, could it be that the redirect only works from trusted sources or something like that?

I've used two different feed modules to confirm it is not the module causing the problem.

**Comment by mbabker** [comment]
The way it looks, you can't just put the feed URLs in and things work as they serve HTML documents.

One of the feed pages ended up having a "View Feed XML" link which adds a `?format=xml` query string, and the source looks like it is indeed a proper RSS feed.  So try that.

**Comment by uglyeoin** [comment]
You mean simply add `?format=xml` to the end of the feed URL?  That gives me a 404.  The feeds seem to be working, it's simply the link that is broken.  Even if it is serving a HTML document, surely a link to that HTML document should still work?

**Comment by uglyeoin** [comment]
It looks like I can use string replace to get this done by simply taking the end of the string and putting the announcements correct URL in front of it.  Never the less, I'd say this is a bug.  And if people need to write custom RSS readers for this stuff, that's a problem.

**Comment by mbabker** [comment]
What feed URL are you trying to put in?

If you're trying to use the Joomla component/module, those require properly formatted RSS/Atom feeds, not HTML documents.  It's why you can't just plug in https://www.joomla.org/announcements/release-news.html as a feed URL, you'd need to use https://www.joomla.org/announcements/release-news.feed instead to get the Joomla generated feed (which is what FeedBurner is processing).

**Comment by uglyeoin** [comment]
I'm using these feeds: https://www.joomla.org/rss-news-feeds.html

If you look on http://feeds.joomla.org/JoomlaAnnouncements you can see `mod_feeds` and it is pulling in `http://feeds.joomla.org/JoomlaAnnouncements`.  If you visit that page you will see that the URL is exactly the same as the one in our feed.  But the link doesn't work in our feed, but does in the atom feed.  So I think it's something to do with the URL being a redirect.  

FWIW I think Joomla! actually produces incorrect RSS and intend to do a pull request at some point (it's got the right file structure but someone didn't finish the RSS fully).

**Comment by mbabker** [comment]
I have no idea how FeedBurner works.  To be honest, I don't even use it where RSS is in use on `joomla.org` (all the feeds on the homepage are directly from the Joomla sites, not FeedBurner).  I'd suggest just using the Joomla generated feeds and avoiding the service (to be honest, I have no idea why nobody went through the effort to just get rid of the service anyway, the only benefit it offers is the ability to sign up for emails).

**Comment by uglyeoin** [comment]
But this: https://www.joomla.org/announcements/release-news.feed gives me a forbidden error when using mod_feeds.  Happy to avoid Feedburner as I don't really see the need for it either.

**Comment by mbabker** [comment]
And if you switch it to Atom?  https://www.joomla.org/announcements/release-news.feed?type=atom

If you're getting non-200 responses on the feeds, unless you've managed to get an IP blocked (which would mean more of the domain isn't accessible to your site than just the feeds), either you've found a bug in Joomla or something isn't working right and it's not something that'd be fixed in the context of this repo (as either it'd be a bug in Joomla or possibly some issue with your hosting or something like that, clearly the feed is there).

**Comment by mandville** [comment]
As you posted this on VEL but are referring to other sites, I will respond by saying that we do have raw feeds and also 'Jason' 
https://vel.joomla.org/vel-feed

**Comment by uglyeoin** [comment]
@mbabker Atom works, great suggestion.  I'm not sure if it is a problem with the RSS or not.  It appears to be a problem with the URL, which is being changed and redirected.  Atom does a direct link which works fine.  

@mandville thank you.  

Onto the community website, which has a helpdesk!  Should that be the link from GitHub?  Thanks for your help, all working well now.
