### ISSUE TITLE
[jcomm] Events - openstreet map security

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1367]
Whoever fixed #1359 by changing googlemaps to use openstreetmap didnt check to see if it was working. :(

On any event page eg https://community.joomla.org/events/user-group-meetings/4006-jugcn-favorite-extensions-2019.html then the event map will not display as it is being blocked because it violates the following Content Security Policy directive: "img-src 'self'

**Comment by zero-24** [comment]
confirmed. The image should be loaded over https. When this is fixed the rule `https://*.osm.org".` would have allowed that calls.

**Comment by conconnl** [comment]
[Closed] - The event map is visible on the mentioned page
