### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by KelsoTom** [joomla/joomla-websites#1369]
I designed and currently have my web site info on Joomla, but am unable to log in the the admin account. I try to retrieve both my username and password, but it states my log in info is incorrect, BUT IT'S THE CORRECT INFO.

How can I contact someone at Joomla to help me log in and update my site?

**Comment by genr8r** [comment]
Hi @KelsoTom . This area is for addressing problems with the joomla.org websites. Joomla is run by volunteers from around the world so there are a number of ways to get help depending on what you are looking for.

The documentation can help you find answers for yourself - https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

The forums allow you to ask questions of other Joomla users many of them with extensive experience that are willing to offer free advice. - https://forum.joomla.org/

And we have a directory of professionals from around the world if you are looking for paid assistance. - https://resources.joomla.org/en/

Thank you for using Joomla. Welcome to the community.
