### ISSUE TITLE
[issue-tracker] Dropdowns not readable (css)

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-websites#1378]
In the issue tracker - search - dropdowns have color == background-color and are not readable. 

![tracker-search-css](https://user-images.githubusercontent.com/1035262/72370485-a66f5d80-3702-11ea-863e-3256545e7c3b.JPG)

**Comment by brianteeman** [comment]
confirmed

**Comment by mbabker** [comment]
https://github.com/joomla/jissues/pull/1071

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/jissues/commit/c10016e84946c4872c98abad015d49f8f3478ad6
