### ISSUE TITLE
[jcomm] captcha breaks layout

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1380]
https://community.joomla.org/joomla-training.html

![image](https://user-images.githubusercontent.com/1296369/73099993-89960f80-3ee4-11ea-86ee-d12b10794ca0.png)

**Comment by conconnl** [comment]
Do you have a proposal CSS code, or maybe @Sandra97 
I personally not able to make it work 100%

**Comment by brianteeman** [comment]
Check with the folks at acymailing. It is coming from their code not from core

**Comment by Sandra97** [comment]
You can try

#formAcymailing12421-captcha {
    	-webkit-transform: scale(0.85);
    	-ms-transform: scale(0.85);
    	transform: scale(0.85);
	margin-left: -20px;
}

**Comment by conconnl** [comment]
Correct, but the ID changes every load.

**Comment by conconnl** [comment]
Changed it to a newer Recaptcha version, which doesn't display "I'm not a Robot"
