### ISSUE TITLE
[jcm] - Disable Google+ in RRSSB Plugin

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-websites#1386]
Please go to the property and disable Google+ in the "Content - Ridiculously Responsive Social Sharing Buttons for joomla.org" plugin.
Google+ doesn't exist anymore and should not be displayed.

Example page: https://magazine.joomla.org/about

**Comment by Joomv** [comment]
Actually a custom html module.  Has been removed.  Will not be on new site as new system in place.
