### ISSUE TITLE
[jtm] Report violation doesn't seem to work

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1389]
I tried to submit a possible trademark issue on tm.joomla.org and encountered two problems

- I couldn't type in the "Message" field 
- After submitting I only get a white screen, no way of telling if the ticket is submitted

I see some errors in the console.
![tm-error](https://user-images.githubusercontent.com/7062995/75242687-dd886280-57c8-11ea-9f8d-8d20814568e3.png)

**Comment by zero-24** [comment]
The first one is just a style that is not applied (should be reported to JCE how it looks from that message), than a cross-site cookie warning, a blocked font, and a blocked google tag manager. All of that should not break any site.

@jeckodevelopment might can disable the JCE for that contact form.

**Comment by hvdmeer** [comment]
I put that screenshot for the tinyMCE error. 
But please, the problem is in the text and not the screenshot.

**Comment by zero-24** [comment]
Just reported to the JCE: https://github.com/widgetfactory/jce/issues/73

>But please, the problem is in the text and not the screenshot.

I know this is the reason i suggested to disable the JCE and see whether this helps to migrate that JCE issue. With the editor "none" that form should work too.

**Comment by zero-24** [comment]
@jeckodevelopment 

> There is an error in the url for the ui.css stylesheet in the screenshot you included, which is most likely producing a 404 error, and therefore the MIME type message.
> This may be due to a mis-configuration of the editor in that form.

from https://github.com/widgetfactory/jce/issues/73#issuecomment-590834070

Maybe it is that simple too :)

**Comment by zero-24** [comment]
This setting might be the problem and can be fixed: https://github.com/widgetfactory/jce/issues/73#issuecomment-590841098

**Comment by conconnl** [comment]
@jeckodevelopment is this solved?

**Comment by mandville** [comment]
There have been no more reports regarding this.,

**Comment by brianteeman** [comment]
There might not have been any other reports - probably because it has already been reported.

Checking 30 seconds ago shows that nothing has changed

**Comment by conconnl** [comment]
@mandville and/or @jeckodevelopment if you give me access I will fix it.
It's a simple issue within JCE, probably takes 5 minutes to fix

**Comment by conconnl** [comment]
In this case it was about RSTickets display, the editor was still enabled while the users write messages in plain text.
The JCE profiles didn't hold certain groups, like Public and therefore those users didn't receive the CSS with the correct profile definition.

Issue is solved.

**Comment by jeckodevelopment** [comment]
Thank you Wilco!
