### ISSUE TITLE
[jcomm] Event approved email message : Link to the event is not rewrite 

### ISSUE THREAD

**Issue by agerix** [joomla/joomla-websites#1391]
Hello,

I have submitted an event and in the email I receive an email with a link to my event on CJO.
This is the link in the email : 
https://community.joomla.org/index.php?option=com_sobipro&pid=1253&sid=4087:docteur-joomla&Itemid=585

This is the normal link on CJO : 
https://community.joomla.org/events/user-group-meetings/4087-docteur-joomla.html

**Comment by Joomv** [comment]
This is an email to an event owner. Where is the need for SEF in that?

**Comment by conconnl** [comment]
Closed - No response.
