### ISSUE TITLE
[joomla.com] - redirgouvfr site = fishing

### ISSUE THREAD

**Issue by idrirap** [joomla/joomla-websites#1393]
redirgouvfr.joomla.com use your services to make a fishing website.

**Comment by idrirap** [comment]
Also I don't know where to properly report this kind of thing

**Comment by conconnl** [comment]
@jonathanCA can you take care of this?
Let's have a chat, to define the correct process.

**Comment by conconnl** [comment]
Website is removed and account closed.
Thank you @idrirap for noticing us.
