### ISSUE TITLE
[CDN] Our websites not working well

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1394]
Almost all of our websites are having problems in loading resulting in missing CSS in pages or just white screens.

Saw a report of this already 3-4 hours ago on twitter and it still is not working like it should.

**Comment by conconnl** [comment]
Sorry nobody replied to you.
MaxCDN Indeed has issues which influences our site rendering.
https://status.maxcdn.com/incidents/2hp3p257k3vw

**Comment by Sandra97** [comment]
The CDN top menu and footer are still not displayed on the downloads site (at least for me)

**Comment by conconnl** [comment]
I checked on multiple devices and internet connections, after making sure the CDN option was really enabled. I can't find any issue and everything is displayed as I expect.

**Comment by Sandra97** [comment]
It wasn't working on 3 of my devices, on 3 different browsers but now it's working. I'm closing the issue
