### ISSUE TITLE
[jorg] canceled, postponed events on frontpage

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1399]
On joomla.org there is a list of Upcoming Events shown. This list is not up to date with the community.joomla.org/events.html 

![upcomingevents](https://user-images.githubusercontent.com/7062995/77619541-b6908e00-6f38-11ea-80fd-3a151f952a04.png)

**Comment by conconnl** [comment]
It seems that its something which needs to be manually managed!
CJO also still shows canceled events.

**Comment by jeckodevelopment** [comment]
on CJO, the right "Upcoming Events" is a module that takes the events from SobiPro.
ID 296.
If events are still listed in the Upcoming Category on SobiPro they are visible, i believe.

**Comment by conconnl** [comment]
The issue is about JOrg not CJO, where the list is manual HTML.
I'm checking if there is a feed link available, so we can automate the display.

**Comment by conconnl** [comment]
Working with SobiPro to get the correct feedlink.
One is available now in the correct order, but it doesn't hold the dates.

**Comment by mbabker** [comment]
> Working with SobiPro to get the correct feedlink.

So, in the meantime, nobody could log in and make the edit to the module to remove the (now) 2 past events?  Working on automation is good, but it's still a good idea to also keep the info updated until the automation is in place.

**Comment by conconnl** [comment]
The events are now automatically loaded.
Tweaks will be made, on the displayed information.
