### ISSUE TITLE
[jcomm] Joomla Connect Review

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#14]
An old part of the Joomla website with lots of RSS feeds.

There have been complaints over the last few months stating that some of the feeds aren't working.

Please review the feeds and code here to ensure that it is still working. May need to assign to a PLT member to look at the code behind this part of the website.

http://community.joomla.org/connect.html

**Comment by jessicadunbar** [comment]
Can you add access ssh/ftp/cpanel logins to the vault? If someone can make me an admin for the community site, I can fix a few issues. Thanks Peter

**Comment by mandville** [comment]
It is probably me that complains about feeds not working. I sent an email to the "connect " team on the 18th July 
"hi
first im aware that community.joomla will undergo an upgradeate at
some point but
there is an issue with the parse of jconnect. i keep having to force
the parse as if the cron doesnt work anymore.
this has also bought up the amount of non responsive feeds out there.
also we
have some feeds that are just not being updated any more.
there are posts that need dumping from years ago along with their
associated spam comments.
anyone able to deal?"
I manually run the parse every few days. 
The script that runs the connect  is called planet from jextended , 
I can provide a list of the unpublished feeds that over the years have failed to be responsive as without suitable consensus, i think the mass deletion would create unneeded backlash. 
There are some 200 feeds currently unpublished, 150 published.

**Comment by mandville** [comment]
It is probably me that complains about feeds not working. I sent an email to the "connect " team on the 18th July 
"hi
first im aware that community.joomla will undergo an upgradeate at
some point but
there is an issue with the parse of jconnect. i keep having to force
the parse as if the cron doesnt work anymore.
this has also bought up the amount of non responsive feeds out there.
also we
have some feeds that are just not being updated any more.
there are posts that need dumping from years ago along with their
associated spam comments.
anyone able to deal?"
I manually run the parse every few days. 
The script that runs the connect  is called planet from jextended , 
I can provide a list of the unpublished feeds that over the years have failed to be responsive as without suitable consensus, i think the mass deletion would create unneeded backlash. 
There are some 200 feeds currently unpublished, 150 published.

**Comment by mandville** [comment]
Sorry to add I am not aware of any developers reporting their feeds not working for several months to the connect team ,

**Comment by mandville** [comment]
i have re run the cron and checked the feeds. i could list the unsreponsive feeds but there is around 200 of them that need removing, 
i also hecked into the comments on the feeds (that used to be allowed but were spammed to the heavens) and there are 20x1300 pages. 
i also checked the comments on the old articles. similar numbers. 
i requested a long time ago for these to be mass dumped from the db but never got a response beyond - "we will ask the upgrade team" i have tried to locate this team but so far been unsuccessful. there are some other areas that need sorting prior to migration that would assist the migration. copying over 10000s of spam comments would not be ideal. 
Perhaps the media team could put out a call for the people listed in connect to check their feeds and update them "in preparation"

**Comment by MATsxm** [comment]
Still relevant?

**Comment by Joomv** [comment]
There's only 44 feeds in total.
All the spam has been cleaned.
