### ISSUE TITLE
[jlaunch] - joomla menus out of date 

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-websites#1400]
launch joomla menu include

https://community.joomla.org/connect.html
joomlacode
https://issues.joomla.org/

needs updating

**Comment by conconnl** [comment]
All webmasters should be able to take care of Launch issues, as this is manage by CloudAccess.
Though there is no clear procedure for different type of issues, questions and actions, for this time I will contact Jonathan and ask how to care of this in the future.

**Comment by Sandra97** [comment]
FYI, I've asked CloudAccess many times to update the top and footer menus

**Comment by conconnl** [comment]
For someone reason CloudAccess isn't responding yet.
Trying other channels as well.

**Comment by conconnl** [comment]
Contact has been made.
The COVID-19 situation has a lot of influence on their availability.
This will be handled, but can't say when yet.

**Comment by conconnl** [comment]
CloudAccess provided us (Luca, Radek & Me) access to their repo, so we can make PRs.

**Comment by iwona** [comment]
Menu and footer have been updated. Please post issues on glip (Launch Site (CloudAccess) chat) and Igor will create a task for proper person to take care of it. Please do not update github without seeing the exact changes, adding changes by us takes less time than correcting later PRs.

**Comment by conconnl** [comment]
Thanks for all actions performed.
