### ISSUE TITLE
[jevents] FTP/HTTP/HTTPS option in new event JUG listing

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1401]
I was checking the Submit Event page and found a field that has a strange option.
The field is "JUG Listing" where you can share the URL of the JUG listing and in front of this field you can choose between
- http
- https
- ftp

Since the community.joomla.org has a HTTPS certificate I fail to see why one has to choose the method of connecting. Also, FTP?

Edit: added the URL
https://community.joomla.org/events/submit-event.html

**Comment by brianteeman** [comment]
Sounds like the standard joomla url field without any options set

**Comment by conconnl** [comment]
Fixed the SobiPro field configuration.
