### ISSUE TITLE
[jmag] Add standard magazine image on website

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1402]
After the relaunch of the website we from the Social Media Team shared this via our channels. But when you share https://magazine.joomla.org the preview shows the stock Joomla image.

Is it possible to add specific Magazine `meta property="og:image"` image so a magazine style preview is shown when linking to the portal?
Just like when sharing https://github.com/joomla/joomla-cms/

It would look better.

**Comment by Sandra97** [comment]
It is possible :)
I'll create an image when I find time.

**Comment by Sandra97** [comment]
![jcm-opengraph-card](https://user-images.githubusercontent.com/4682328/78036636-d7a71380-736a-11ea-883e-baba9a428769.jpg)
![jcm-twitter-card](https://user-images.githubusercontent.com/4682328/78036646-da096d80-736a-11ea-993a-b6de5a35f71c.jpg)

If text edits are needed, just tell me

**Comment by jeckodevelopment** [comment]
Thanks Sandra

**Comment by jeckodevelopment** [comment]
Done, thank you

**Comment by brianteeman** [comment]
You might want to rethink the text a little

If an article is "aiming" to do something then you are saying that it may do or it may not. Hopefully all the articles "do"

Suggestion
> Articles to educate, inform, challenge, and inspire you.

**Comment by Sandra97** [comment]
Thanks Brian! I'll edit the text with your suggestion

**Comment by Sandra97** [comment]
Updated images:
![jcm-opengraph-card](https://user-images.githubusercontent.com/4682328/78044493-0de99080-7375-11ea-92f6-56ce9faf882d.jpg)
![jcm-twitter-card](https://user-images.githubusercontent.com/4682328/78044512-1346db00-7375-11ea-8861-d1437459625e.jpg)
