### ISSUE TITLE
[jmag] Sharing article shows standard image and not article image on preview 

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1403]
I see an issue when sharing an article from the magazine.

So for magazine.joomla.org it now serves the new designed standard image. Perfect!
But when I share an article I would like to see the image provided in the article but it still shows the standard image. I see the standard image AND the article image are provided as `og:media` though.

Example, paste this URL on Facebook (you don't have to post it) and watch which image is shown on the preview:
https://magazine.joomla.org/all-issues/march-2020/joomla-privacy-journey

**Comment by brianteeman** [comment]
thats because the image is hardcoded in the head

`<meta property="og:image" content="https://magazine.joomla.org/images/opengraph/og.jpg">`

**Comment by hvdmeer** [comment]
I saw that:
> I see the standard image AND the article image are provided as og:media though.

**Comment by mbabker** [comment]
I have no idea how EasyBlog sets metadata, but they probably aren't using the `Joomla\CMS\Document\Document` API.  When the template is rendered, it hits this check to decide whether to add the default meta tag from the template params:

```php
/** @var $this \Joomla\CMS\Document\HtmlDocument */

if (!$this->getMetaData('og:image', 'property'))
{
	$this->setMetaData('og:image', $this->params->get('ogImage', 'https://cdn.joomla.org/images/joomla-org-og.jpg'), 'property');
}
```

I don't have any useful advice here, just using this as a "this is why extensions should use the API" moment of preaching.

**Comment by conconnl** [comment]
Thanks Michael....
This probably explains why the HTML source holds the Meta data twice when viewing the article.

```
<meta property="og:image" content="https://magazine.joomla.org/images/opengraph/og.jpg">
<meta property="og:image" content="https://magazine.joomla.org/images/easyblog_articles/2619/b2ap3_large_march.jpg">
```

**Comment by conconnl** [comment]
It should be fixed now.
Please test!

**Comment by hvdmeer** [comment]
I've tested it on Facebook & LinkedIn and in Hootsuite getting previews on FB/TW/LI. It shows the correct article image now. Thank Wilco and Mark.
