### ISSUE TITLE
[jcm] Incorrect image ratio on JoomlaCamp Chicago article

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#1404]
Can we change the image associated with this artilce...
https://magazine.joomla.org/all-issues/october-2018/the-first-joomlacamp-chicago

...so that it has the proper aspect ratio? I re-did the current one to work properly.
![joomla-camp-chicago](https://user-images.githubusercontent.com/1870522/78191349-6c794200-743b-11ea-9398-52f35976cdb5.jpg)

**Comment by genr8r** [comment]
It shows up fine in the article itself, but the cropping is very strange when viewed in the infinite scroll of all the other articles.

**Comment by conconnl** [comment]
@joomla/magazine-team can you look at this within the team?

**Comment by jeckodevelopment** [comment]
Done
