### ISSUE TITLE
[jdocs] - The Joomla Websites page is outdated

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-websites#1408]
The following page on docs is outdated.
https://docs.joomla.org/Joomla:The_Joomla_Websites

* test-joomla.org doesn't exist anymore.
* CDN is not website people can visit.
* domains.joomla.org isn't in the list.
* foundation.joomla.org isn't in the list.
* Joomla Idea Pool doesn't exist.
* It holds Managers names which are not correct anymore, every site is part of a team and not just one person.

**Comment by coolwebcreations** [comment]
The obsolete URLs are removed. The managers will be updated during the next days.

**Comment by conconnl** [comment]
How is it going?
Do you need any information from me?

**Comment by conconnl** [comment]
@coolwebcreations how is it going, any help needed?

**Comment by conconnl** [comment]
The page is fully updated by @coolwebcreations
