### ISSUE TITLE
Joomla.com hosting a phishing website 

### ISSUE THREAD

**Issue by VBustamante** [joomla/joomla-websites#1410]
Yesterday I received a shortened URL that points to  https://primeiraetapa.joomla.com/administrator/logs/index.php via SMS. This site is being used as a phishing form impersonating a Brazilian bank.
IT should be take down.

**Comment by conconnl** [comment]
Thanks,
Forwarded to abuse desk.

**Comment by janismic** [comment]
The site has been blocked. Regards from cloudaccess.net
