### ISSUE TITLE
https://mail.joomla.org does not work over SSL

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1411]
Try to open https://mail.joomla.org you get an `ERR_CONNECTION_CLOSED` error form chrome. The HTTP site works and correctly redirects to the google mail login.

But I would expect the HTTPS URL it be workting too. Maybe rochen can help us setting up the HTTPS cert? @conconnl @jeckodevelopment ?

**Comment by conconnl** [comment]
This is not a domain running in our platform. 
We don’t have internal mail servers. 
All our mail runs on https://mail.google.com

It seems someone has created a CNAME record in the past for this. 
I think we should remove it.

**Comment by zero-24** [comment]
> It seems someone has created a CNAME record in the past for this.

can't we just add the ssl support? that domain is very handy ;)

**Comment by conconnl** [comment]
How would you do that on a CNAME records which isn’t a domain with any CPANEL or whatever behind it?

**Comment by zero-24** [comment]
cant we just add that subdomain?

**Comment by conconnl** [comment]
Yes, but then we need to make it a redirect. 
If you type mail.joomla.org you will be forwarded to mail.google.com

We don’t have any mail services on our domain or platform.

**Comment by zero-24** [comment]
I know that we don't run the mail servers ourself but that would be awesome :-)

I use the mail.joomla.org just to get to the correct gmail login page and haveing that with https would be great.

**Comment by conconnl** [comment]
As agreed, I will ask Rochen to make changes.
So we have a https address to use, but the way it works will change because of this.
It will become a redirect instead of a CNAME.

**Comment by zero-24** [comment]
Awesome thanks
