### ISSUE TITLE
[osm] Invalid 404 handling

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1413]
https://github.com/joomla/opensourcematters.org/blob/1dbf55149d964f953291eb16ff78e50d01f9106f/www/templates/osm/error.php#L11-L14

This is NEVER EVER EVER EVER EVER a valid mechanism for handling 404 errors, unless you want a 404 report that has exactly 0 lines.  This mechanism for error handling results in the should-be 404 issuing a 302 response to a URL that issues a 200 response to display a "page not found" error and is beyond wrong.

This is SEO 101, folks.  Throw a 404 for a 404 response, not a 302 into 200.

**Comment by conconnl** [comment]
What is your proposal to fix this?
Removing it breaks the layout.

**Comment by mbabker** [comment]
The error template needs to load up the template assets properly to render a proper error page.  Right now in the 404 case it's doing a redirect to load a specific article inside the CMS.  So the fact it breaks the layout means that the error template was never fully designed out, just the hack added in to make a "pretty" 404 page.

**Comment by conconnl** [comment]
Are you saying that if I start over and following the manual on https://docs.joomla.org/Custom_error_pages its fixed?

**Comment by conconnl** [comment]
I tried to follow it, but it just breaks the website.
If you have a PR to fix it and still show the website, I will add it to the site.
Until that it's a won't fix.... With J4 a complete new template will be created.

**Comment by brianteeman** [comment]
Not knowing how to fix something isn't a valid reason to close something

**Comment by conconnl** [comment]
Not reading and just saying something without a PR is also not helping.
If you read, you noticed that a new template will be created.
https://github.com/joomla/opensourcematters.org/issues/1

**Comment by brianteeman** [comment]
I absolutely read your comment about a new template but that doesnt address the problem now or for the next six months

**Comment by brianteeman** [comment]
https://github.com/joomla/opensourcematters.org/pull/2
