### ISSUE TITLE
[osm] Outdated Bootstrap

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1414]
https://github.com/joomla/opensourcematters.org/blob/1dbf55149d964f953291eb16ff78e50d01f9106f/www/templates/osm/index.php#L62

1) Bootstrap 3.2.0 isn't current by any measure of the imagination

2) Core has a media override function to avoid these CDNs, the unset trick a few lines above is totally unnecessary

**Comment by conconnl** [comment]
@mbabker 
If I check the generated HTML and the Network tab I only see the one loaded from MaxCDN.
If I understand your text correctly, you say that the one from Joomla is just loaded, no matter if the "Unset" is defined.

* Do I need to update the MaxCDN line too: https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js ?
* Do I need to remove it complete including the unset line?
* Do I need to do something else?

Please advice!

**Comment by conconnl** [comment]
Removed MaxCDN bootstrap!
Now loading the joomla version.
https://github.com/joomla/opensourcematters.org/commit/12ce369e5a2247a3384f234d62e3b40e54b506f1
