### ISSUE TITLE
[jshow] Cannot login

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1416]
Hello, 

I wanted to log in. But it's impossible, here is the screen I got (I tried on 3 different browsers and 2 different devices)
![index](https://user-images.githubusercontent.com/4682328/79752439-988a3380-8314-11ea-9fcd-1eb554e6b5ac.png)

@sebastienlapoux Could you give a look?

Thanks

**Comment by sebastienlapoux** [comment]
Hi @Sandra97 ,

Thank you! Yes, due to a module unpublished (to see who). Fixed.

Thanks to try again.

**Comment by Sandra97** [comment]
It works now. Thanks Sébastien!

I'm closing the issue.
