### ISSUE TITLE
Forum: DMARC fail in the last emails

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1417]
The last forum emails are going directly to the spam folder.

Please, check the following output from gmail:

`
Received-SPF: pass (google.com: best guess record for domain of jforum@joomla-forum.directrouter.com designates 72.29.124.150 as permitted sender) client-ip=72.29.124.150;
Authentication-Results: mx.google.com;
       spf=pass (google.com: best guess record for domain of jforum@joomla-forum.directrouter.com designates 72.29.124.150 as permitted sender) smtp.mailfrom=jforum@joomla-forum.directrouter.com;
       dmarc=fail (p=QUARANTINE sp=QUARANTINE dis=QUARANTINE) header.from=joomla.org
`

The SPF record looks OK and it seems that there is some issue in the DMARC configuration.

**Comment by conconnl** [comment]
I understand that you say forum.joomla.org (The forum team) @ooffick 

DMARC is record is not a required record and it's also an cascading record, so when you don't create it in a subdomain it will take the root domain. DMARC is only meant to tell systems what to do when SPF and/or DKIM fails (https://en.wikipedia.org/wiki/DMARC)

The error message clearly states that the send is wrong.
The from is jforum@joomla-forum.directrouter.com which is not [at]joomla.org

**Comment by conconnl** [comment]
Probably it's me...
But MXToolbox clearly states forum has no SPF record at all.

**Comment by conconnl** [comment]
I’m going to check all domains we have for SPF the existence of SPF record.

**Comment by conconnl** [comment]
SPF has been added for forum domain and all others.
