### ISSUE TITLE
[jshow] Please use the latest version of jorg template

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#142]
Seems the dev website http://joomla-showcase.octopoos-dev.com/ is not using the latest version of the template (for example, it's the "old" CSS with a container of max 960 instead of the current 1 170px).

**Comment by sebastienlapoux** [comment]
Hi Sandra,
Thanks. And do you know who can provide us the new template?

**Comment by Sandra97** [comment]
@mbabker 
Could you help on this, please?

**Comment by mbabker** [comment]
Pass me an e-mail address and I'll send it

**Comment by sebastienlapoux** [comment]
Thanks Sandra and Michael.
Michael I sent you an email.

**Comment by mbabker** [comment]
It looks like the JED template might have been the starting model (based on the directory appearance).  So the updated template may not cleanly apply to this environment.  Just something to keep in mind as you work on the update.

**Comment by mbabker** [comment]
This was opened 10 months ago, and now the team wants to launch the site this coming week and it appears this task was not acted on at all.

**Comment by jeckodevelopment** [comment]
@sebastienlapoux please use the latest template.

**Comment by sebastienlapoux** [comment]
Hi,
Template updated.
* please delete your navigator cache before to test

**Comment by Sandra97** [comment]
Thanks Sébastien. 
As you are now using the jorg template, I can close this issue.
Re-open if needed
