### ISSUE TITLE
[joomla.org] Spell Check Cookie Policy Document

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1420]
Title.  "Stricly necessary cookies" definitely is not spelled correctly.  There may be other misspellings in the document.

**Comment by brianteeman** [comment]
Where is the document - happy to proof read it.

**Comment by conconnl** [comment]
This one:
https://www.joomla.org/cookie-policy.html

**Comment by brianteeman** [comment]
You realise that it conflicts with the privacy policy https://www.joomla.org/privacy-policy.html ?

**Comment by conconnl** [comment]
What I have heard is that one will be replaced as well. @jeckodevelopment

**Comment by brianteeman** [comment]
Answering @mbabker example error - 

"**Strictly necessary**" and "**Non-necessary**"  should be replaced with "**Essential**" and  "**Non-essential**" and "**Essential**"

**Comment by jeckodevelopment** [comment]
Thank you @mbabker , @brianteeman and @conconnl 
That is fixed
