### ISSUE TITLE
[joomla.org] Remove "Control using our Consent tool" section from Cookie Policy

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1422]
This tool is not ready, the section should be removed from the document until it is in order to prevent confusion.

**Comment by jeckodevelopment** [comment]
Removed this part:

> **Control using our Consent tool**
You can control and/or delete cookies as you wish by using our Cookie Control functionality. You can delete all cookies that are already on your computer or simply check/uncheck the categories of cookies that you want to be used (On/Off buttons). 

And added this one as temporary notice

> We plan to release a tool to control cookies on our websites soon. The tool will allow you to accept / delete all the cookies saved by any of the joomla.org websites.

Thanks @mbabker
