### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by soluzioniag** [joomla/joomla-websites#1424]
Hi!
Please, can you tell me why there are two same option in the tab "Advanced" of "User Settings"? 
Thanks for your Work??
![Joomla---](https://user-images.githubusercontent.com/64743678/80919567-fa15bd80-8d6a-11ea-916c-4b5a3179242c.jpg)

Alfredo

**Comment by conconnl** [comment]
I can’t as it’s not English. 
Please switch to English and check what it says. Maybe their is an error in the translation.

**Comment by brianteeman** [comment]
It is a bad translation

The first is for users
The second is for groups
