### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by fahadrulezzz** [joomla/joomla-websites#1427]
Download Section is Down. We are unable to download any version of Joomla

![image](https://user-images.githubusercontent.com/64898472/81165198-45fa7980-8f9a-11ea-8bd9-831606cc2787.png)

**Comment by pe7er** [comment]
From your screen shot it looks like your DNS is unable to find the Amazon AWS server (s3-us-west-2.amazonaws.com) where the Joomla download package is stored.

Did you try to download Joomla 3.9.18 from https://downloads.joomla.org/cms/joomla3/3-9-18 ?
For me (my location: The Netherlands, Europe) the downloads are working correctly.

Are you able to access the following:
https://s3-us-west-2.amazonaws.com
http://52.218.241.248
https://aws.amazon.com/s3/

**Comment by fahadrulezzz** [comment]
Thanks for acknowledgement. I am not sure if its DNS issue. I tried to access above link except first one, other 2 are working..

Also none of the download links are working. Let me try on by restart my modem .

Any further guidance?

**Comment by pe7er** [comment]
Thanks for your feedback! 

It looks like **your DNS** is **not able to translate** s3-us-west-2.amazonaws.com into 52.218.241.248.
I'll ask around if someone else knows a solution to this.

As temporary workaround: Are you able to use another DNS or maybe a VPN to download Joomla?

**Comment by pe7er** [comment]
Oh, and have you tried to download a Joomla release from github?
https://github.com/joomla/joomla-cms/releases

**Comment by fahadrulezzz** [comment]
> Oh, and have you tried to download a Joomla release from github?
> https://github.com/joomla/joomla-cms/releases

Thanks. This one works. 

Best Regards Man.

**Comment by pe7er** [comment]
Good to hear! You're welcome!
