### ISSUE TITLE
[jorg] Form submit on forgot password throws captcha errors

### ISSUE THREAD

**Issue by JazParkyn** [joomla/joomla-websites#1428]
![image](https://user-images.githubusercontent.com/6943227/81295390-3cd7de00-9068-11ea-8235-d6bcd356a034.png)

**Comment by conconnl** [comment]
Can you test again?
I seems the ReCaptcha Keys were wrong in the J! Plugin

**Comment by JazParkyn** [comment]
Fixed, thanks!
