### ISSUE TITLE
[jcomm] - RSTickets & JCE creates conflicts

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-websites#1429]
For some reason enable JCE as editor on the RSTickets Helpdesk form in the frontend, breaks the forms and make it impossible to submit any tickets.

**Comment by jeckodevelopment** [comment]
seems similar to what we had in TM

**Comment by conconnl** [comment]
It isn't!
The form works, we can enter text etc.
Only the message isn't accepted by RSTickets!

**Comment by conconnl** [comment]
RSTickets!Pro replied that there system is built with TinyMCE, that for problems with other editors they can't help even if it works on other websites.
The only thing I can do is test it with TinyMCE and hope that it also doesn't work to get support.

**Comment by conconnl** [comment]
Solved:
Reason was a wrong configuration in the prohibited elements within a JCE profile based on regex.
It broke JCE editor itself.
