### ISSUE TITLE
[jcomm] Community.joomla.org is down

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#143]
Community.joomla.org is down see:

http://community.joomla.org/

![cjorg](https://cloud.githubusercontent.com/assets/2596554/10495771/dabefbda-72bd-11e5-9d59-69dd0640c09e.PNG)

**Comment by mbabker** [comment]
Fixed

**Comment by mbabker** [comment]
Fixed

**Comment by Radek-Suski** [comment]
Fixed
