### ISSUE TITLE
[jcomm] Events description is empty with SobiPro

### ISSUE THREAD

**Issue by carcam** [joomla/joomla-websites#1430]
When users submit an event with current SobiPro implementation, description is not saved.

When  any member of the  events team edit the event  in the backend, and they write a description, it is correctly saved in any case.

Thanks!!

**Comment by conconnl** [comment]
Do you have a link to the public page where events are submitted?

**Comment by carcam** [comment]
Hi Wilco,
I'm afraid you need to be log in to be able to submit events. Any account in community can submit events though.

**Comment by conconnl** [comment]
It seems to be also something related to JCE, see: https://github.com/joomla/joomla-websites/issues/1429

The page loads JCE with TinyMCE, or something.
https://community.joomla.org/components/com_jce/editor/tiny_mce/tiny_mce.js

I will need to deep-dive into it, to possibly find the reason.

**Comment by conconnl** [comment]
....
Has this ever worked before?
Even if I disable TinyMCE, the editor in the SobiPro field.
It keeps showing errors in the console for this page.

**Comment by conconnl** [comment]
Sorry 😄, additional question!
Do you even need the Editor for the event users?

Before using / testing the form itself, where should I look after submit if the data is stored?

**Comment by carcam** [comment]
To be honest, I do not think we need an editor for that field in the frontend.

Once an event is submitted, it's added to the Events Section in Sobipro

**Comment by conconnl** [comment]
I have done multiple different tests for this page, focused on the description field.
The moment I disable the editor option in the field within SobiPro everything works.
With the Editor option enabled no matter if it's JCE or TinyMCE it's just doesn't work, without any errors for this specific part. (Not in log, screen, console & database)

For this moment, the only thing left for me is a ticket to SobiPro helpdesk.
Depending on your decision disabling the editor as well in the description field, until SobiPro has a solution.
**__Please let me know.__**

I found other issues on this page:
**CSP**
https://github.com/joomla/community.joomla.org/issues/1

**CSS**, will fix it.
![image](https://user-images.githubusercontent.com/11913918/82831621-33989f00-9eb9-11ea-8eb5-4dd13614b81e.png)

Errors:
[25-May-2020 16:38:49 UTC] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/communitysandbox/public_html/components/com_sobipro/lib/views/adm/view.php on line 1403
[25-May-2020 16:43:53 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/communitysandbox/public_html/components/com_sobipro/opt/fields/calendar.php on line 1038

**Comment by conconnl** [comment]
@carcam should we disable the editor on that field or not?

**Comment by carcam** [comment]
Hi @conconnl ,
Thank you very much for such a through and detailed explanation. Please disable the editor in that field as I think it's better to have a plain text description than no description.

Best!!

**Comment by conconnl** [comment]
Disabled it for this field.
I checked the other textarea fields, it seems that for those field it was already disabled.
I anything changes for SobiPro side I will give you an additional update.

For now I will close the issue, off course you can reopen it.

**Comment by conconnl** [comment]
@carcam by accident I have seem to have found the reason.
There was some regular expression configured in the prohibited elements parts, which broke the editor generation.
At least I'm now able to have the editor enabled and see the description when I change an entry as normal user for a JUG.
As the change was in JCE, I expect it works for events as well now.
