### ISSUE TITLE
[idp] date of birth

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1433]
My date of birth is displayed as
![chrome_2020-05-16_20-54-44](https://user-images.githubusercontent.com/1296369/82129054-f09f4300-97b7-11ea-964b-66b17e93ee45.png)

On the edit profile it is displayed as
![chrome_2020-05-16_20-55-32](https://user-images.githubusercontent.com/1296369/82129060-f7c65100-97b7-11ea-8cf4-50faa0260d17.png)

Not sure how but I would guess its a date format issue

I submitted a request for my data so I can see what is actually in the db but not got it yet

obviously both the dates are wrong

**Comment by sanderpotjer** [comment]
@brianteeman thanks for reporting. Both were incorrect formatted null dates. Fixed now.

**Comment by brianteeman** [comment]
@sanderpotjer Thanks I can confirm that it no longer displays anything BUT are you sure they were really null in the original data as one of them is very close - or maybe just a fluke

**Comment by sanderpotjer** [comment]
@brianteeman 0000-00-00, nothing else

**Comment by brianteeman** [comment]
ok - thanks for confirmin - weird fluke
