### ISSUE TITLE
[idp] City marked - while it is visual at the source from vol

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-websites#1434]
At your idp profile and concent pages the city is marked as '-' while it is actually filled in at the volunter portal site and in osm information (which is also fetched from vol.)
![16-05-2020 22-14-44id-loccity](https://user-images.githubusercontent.com/790445/82129579-3feb7080-97c4-11ea-8396-d0979063599e.png)

**Comment by sanderpotjer** [comment]
@ot2sen thanks for your feedback. Not sure if I understand you properly. 

There are two city fields, one for your location city, one for your mailing address city. If a `-` is visible for the location city in the location consent (meanwhile empty fields are no longer visible) your location city is not provided in your profile.

**Comment by conconnl** [comment]
I have checked this part in the system and all seems to be in order.
If there is still something wrong, you can reopen the issue or create a new one.
