### ISSUE TITLE
[idp] token email

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1437]
The text of the email with the token is

> Someone has created a request to export all personal information related to this email address at https://identity.joomla.org/. As a security measure, you must confirm that this is a valid request for your personal information from this website.
> 
> In order to confirm this request, you can complete one of the following tasks:
> 

But it doesn't say what you should do if you didnt request it. An example from my inbox today

> Someone requested that the password be reset for the following account
> Email: brian@teeman.net
> If this was a mistake, just ignore this email and nothing will happen.

**Comment by roland-d** [comment]
@brianteeman this is the Joomla core. If the text isn't good enough I think it will be better to propose a change on the CMS repo. Sure I can make an override on the IDP but a Joomla-wide fix would be better. What do you think?

**Comment by brianteeman** [comment]
I will submit a pr to the core but in the meantime if you could create a language override on the portal that would be great

**Comment by roland-d** [comment]
Not a problem to create a language override, can you send me the text I should put in?

**Comment by brianteeman** [comment]
I would just add 
"If this was a mistake, just ignore this email and nothing will happen."
on a new line before 
"In order to confirm this request, you can ...

**Comment by brianteeman** [comment]
PR submitted to core https://github.com/joomla/joomla-cms/pull/29125

**Comment by roland-d** [comment]
Overrides created for both the export request and remove request
