### ISSUE TITLE
[idp] Google Authenticator not completing process

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1439]
Yesterday I initially reported through @roland-d on Glip about the QR Code not being visible on IDP.

That was fixed (CSP issue addressed by @zero-24) but now when I attempt to complete setting up the authenticator, I can't.

Steps:
- Go to edit profile on IDP
- Change authenticator method to Google Authenticator
- Setup details appear, and QR Code appears. Scanning the code in the app adds it to the app.
- In Step 3, you enter the Security Code from the app.
- **Problem:** You can't then authenticate the authentication - you can only save the profile, and that does not complete the authentication step.
- When you go to edit the profile again after it's been saved, you'll find the authentication has not activated.

**Comment by roland-d** [comment]
Hello @particthistle I cannot reproduce the issue as I have already setup TOTP and just tried again and it worked. So I would like to know which browser you are using. Do you get any error message or just that the profile is saved?

**Comment by particthistle** [comment]
@roland-d thought it might look like you have TOTP activated for IDP, try logging in with just email and password. I've got TOTP configured now on my phone after the QR Code issue I mentioned, but in the profile, it's not activated as I couldn't complete the verification, so the setting stays set as "Disable Two Factor Authentication". 

You'll also find that if you have that setting and switch to Google Authenticator, it should show you the "One time emergency password" and instead it shows you:
![image](https://user-images.githubusercontent.com/5515866/82726072-031ffc00-9d25-11ea-82ca-eddff654948c.png)

Here's a walk-through of what's happening for me in Firefox in Windows.

- Log into identity.joomla.org with just email address and password (OTP is off)
- Click on Profile > Edit Profile
- Change option for 2FA to "Google Authenticator"
![image](https://user-images.githubusercontent.com/5515866/82726015-97d62a00-9d24-11ea-804b-02dcf58b0f35.png)
- Having scanned QR code previously, I go to enter Security Code from the app at Step 3:
![image](https://user-images.githubusercontent.com/5515866/82726042-cf44d680-9d24-11ea-8d4e-d6280aacd3d2.png)
- Scrolling further down, clicking Save it then shows:
![image](https://user-images.githubusercontent.com/5515866/82726083-25b21500-9d25-11ea-9d17-b5abfd6f0db1.png)
but it should have shown that it verified the connection to the 2FA, and when you go to get the emergency codes by editing your profile, you'll find it's gone back to:
![image](https://user-images.githubusercontent.com/5515866/82726102-55f9b380-9d25-11ea-9f8a-49541eb6603d.png)

I've then tried in Google Chrome and Windows Edge, with identical results.

**Comment by particthistle** [comment]
Also IMO editing the profile all as one long single record isn't all that efficient.
- If the user has their password saved, that can cause an error to throw if they save and it's only got a password in one of the two fields
- the 2FA isn't authenticating as it should
- Categorising some of the other sections into tabs would give you flexibility to allow certain parts of the identity to be drive by ACL - so for example, JCM Authors could have access to their Author Profile, but those not involved in the magazine could have that option hidden until they were to need it.

**Comment by particthistle** [comment]
@roland-d any additional information you need on this?

**Comment by roland-d** [comment]
Hello @particthistle I should have updated the issue but I have been testing and unable to reproduce it. Now that I have a test environment setup, I want to test some more and see if I can find something.

As for the design of the whole thing, that is better off in an issue of it's own as it really is a separate issue.

**Comment by roland-d** [comment]
Hello @particthistle I think I found what is going on. The devil is in the details and it has all to do with bullet point 4:
> Having scanned QR code previously, I go to enter Security Code from the app at Step 3

You cannot use the old QR code, that is because the Authenticator key is different. You need to rescan the QR code or enter the key again and then scan.

Let me know if that solves your issue.

**Comment by particthistle** [comment]
@roland-d thanks for that - apologies to have missed the notification of your reply 2 weeks ago.

You are correct... the string on the identity authenticator was subtly different to the one I'd been re-trying repeatedly.

Deleting the old authenticator record and scanning again resolved the issue.
