### ISSUE TITLE
[jdev] Auto reply typo on security submissions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#144]
If you submit a security report you get an auto-reply email that begins

> Thank you for your security concern. The Joomla! Security Team take every report seriously but may not be able to reply directly to all inquires.

This should be inquiries - note the extra i

**Comment by mbabker** [comment]
I just seriously spent 10 minutes looking for an auto-reply feature in the CMS…

Doubt that typo's ever gonna get fixed.  Only one person seems to have manager permissions on the helpdesk system and he's not around anymore (go figure).

**Comment by brianteeman** [comment]
Yikes - can it not be changed directly in the db?

**Comment by mbabker** [comment]
If it were on one of our managed servers, yes.  But I'm fairly certain it's on the servers of the same guy who has the admin keys.

**Comment by mbabker** [comment]
The helpdesk system isn't part of the security team workflow anymore.  So, no longer an issue.
