### ISSUE TITLE
[idp] Feature Request: Tabbing profile & profile edit page

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1440]
Having everything in a single column edit page seems very ordinary UX considering every other thin in Joomla's typically broken into tabs.

If this is going to become a one stop shop for everything in your Joomla identity, then typically you're going to only want to add or edit specific parts whenever you're updating your identity.

Initial breakdown into tabs I'll suggest would be:
- Account info
- 2FA Configuration
- Personal and Location information
- Profile - Introduction, Joomla Story
- Joomla & Social Accounts
and then from there, sub project specific tabs if required as services are added in:
- JCM Author Profile
- Forum profile
- Joomlers History modification requests (if that was to eventuate as a feature)
- others as you come to them.

On the profile screen, should it also have tabs that show information that is pulled in other Joomla sites so you can look through your identity in the one place and see what's shown where. Including, but not an exhaustive list:
- Joomlers involvement history
- JCM Articles
- Forum profile

**Comment by conconnl** [comment]
@sanderpotjer is there anything I can help with?

**Comment by sanderpotjer** [comment]
@particthistle thanks for your feedback & suggestion. For the consents, we implemented accordion sliders. This is now also implemented for the profile view & edit page for the existing fields. In the future, this will be extended based on the connected sites.
