### ISSUE TITLE
[idp] Missing language string

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-websites#1441]
When clicking on "Password forgotten?" and filling in an invalid/non-existing mail address, the error message has a missing language string. Also, that it reports that the mail address is (in-)valid could be seen as an information disclosure i.e. a security issue.

**Comment by zero-24** [comment]
As for the Security issue the core does that too. When you want to change it you can choose to change the language string. ;-)

**Comment by roland-d** [comment]
@Hackwar thank you for your report. The language string has been added. This comes straight out of com_users. If we want another message, I am open for it and just let me know what should be there. I am closing this issue as the missing string has been fixed.
