### ISSUE TITLE
[joomla.org] CSP issues on books page

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1445]
URL: https://www.joomla.org/joomla-press-official-books.html

![image](https://user-images.githubusercontent.com/1296369/82474912-a671d680-9ac3-11ea-96f0-5a687c9d24d3.png)

`Refused to load the image 'https://m.media-amazon.com/images/I/41jaf+Gc6bL._AC_SL115_.jpg' because it violates the following Content Security Policy directive: "img-src 'self' data: https://*.google-analytics.com https://*.googletagmanager.com https://*.joomla.org https://*.pingdom.net https://*.doubleclick.net https://*.gstatic.com https://*.google.com https://*.googleapis.com https://shield.sitelock.com https://img.youtube.com  https://i1.ytimg.com https://i.ytimg.com https://i9.ytimg.com https://s.ytimg.com https://*.amazon-adsystem.com https://*.ssl-images-amazon.com https://*.assoc-amazon.com https://opensourcematters.org https://*.opensourcematters.org".`

**Comment by zero-24** [comment]
Will look into that right now thanks for reporting.

**Comment by zero-24** [comment]
Hmm to me it loads fine on Chrome.

How can I reproduce it?

**Comment by zero-24** [comment]
Sorry had to scroll down.. ;-)

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla.org/pull/40 Closing here as there is a PR for the joomla.org repo. Thanks for your report :)

**Comment by zero-24** [comment]
PR has been merged and the changes has been deployed tonthe live site. Thanks for reporting @brianteeman
