### ISSUE TITLE
[jcomm] Delete abandoned Joomla User Group

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1447]
I received a message about a JUG that is still on the listing at CJO but hasn't had a meeting in years now. Can someone delete the entry of JUG Zwolle?
https://community.joomla.org/user-groups/europe/netherlands/1004-joomla-user-group-zwolle.html

I tried to report it at the JUG page but the documentation isn't correct, I don't see a "a red/orange cloud with a ? (Question Mark) inside.". I don't know if that goed wrong on my side or on the website.

**Comment by webdjam** [comment]
Hello Hans,
Thanks for reporting the listing, it will be unpublished, we don't delete listing for record purpose.the report of a listing button is missing, I will ask the webmaster team to investigate the issue.
Best,

**Comment by hvdmeer** [comment]
Thank you Djamel.

**Comment by conconnl** [comment]
I enabled the question mark part again in the system, connected to the ticket system.
The feature was disabled as it's was communicating with an old extensions
