### ISSUE TITLE
[jcm] passwords

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1454]
Trying to login to the magazine site to leave a review and its forcing me to change my password. No problem there. But it wont accept my long random password generated by google chrome as it is requiring a symbol
![image](https://user-images.githubusercontent.com/1296369/83514961-79aebd80-a4cc-11ea-9026-51c1cb3fc504.png)

**Comment by conconnl** [comment]
That is correct.
You need at least 1 Symbol as defined in the J! com_users configuration.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/11913918/83515883-5d178300-a4d6-11ea-85c8-ed73908a89e6.png">

**Comment by brianteeman** [comment]
That is bad security

**Comment by conconnl** [comment]
That is your opinion, which is not in line with JSST

**Comment by brianteeman** [comment]
I doubt that very much. Rules like this do not add security. They do not add to the entropy of the password at all. Which is why chrome isnt automatically enforcing it for example. Any rule that prevents the use of a password manager is a bad rule. Instead of blindly closing things take some time to understand the problem and if you dont then ask someone else.

**Comment by brianteeman** [comment]
NIST specifically state that you should not force the selection of special characters
https://pages.nist.gov/800-63-3/sp800-63b.html#appA

**Comment by conconnl** [comment]
I can't change your doubt about the JSST.

**Comment by zero-24** [comment]
As discussed with you both the JSST is and was not enforcing any password rule. Creating and enforcing rules for joomla.org is up to the webmasters not the JSST and this is exactly what happend in this case. Hopefully this clears things up. :-)
