### ISSUE TITLE
[jdev] typo

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1457]
Please correct the spelling of my name

https://developer.joomla.org/security-centre/814-20200602-core-inconsistent-default-textfilter-settings.html

![image](https://user-images.githubusercontent.com/1296369/83538774-2483a380-a4ee-11ea-9ced-bb46c78411b0.png)

**Comment by sebastienlapoux** [comment]
Like it! Brian the Brain

**Comment by HLeithner** [comment]
Thanks for the report, it's already fixed.

**Comment by brianteeman** [comment]
Thank you
