### ISSUE TITLE
[joomla.org] wrong link in article "Joomla 3.9.19 Release"

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1458]
On https://www.joomla.org/announcements/release-news/5812-joomla-3-9-19.html
the item
- Improve translation system supporting better pluralization for languages like Welsh **#28763**

links now to https://github.com/joomla/joomla-cms/pull/28691
but it should link to other issue https://github.com/joomla/joomla-cms/pull/28763

(Thanks to forum user Rondeb for this correction)

**Comment by HLeithner** [comment]
Thanks fixed
