### ISSUE TITLE
Lost revenue through adblock

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#146]
We all know that J gets a significant amount of our funds from adverts.
Many of us (majorty?) run adblockers and never see the adverts.
Hence the revenue from adverts is continuously diminishing

The problem is that the way the adblockers work we as users dont even know that they would have been there so even though we could disable the adblocker for joomla.org because we want to support Joomla we dont even realise or think about it.

An option is to detect that an adblocker is running and display a nice message in the place of the advert - perhaps "Please consider disabling your adblocker for this domain as we really need the money"

There are many techniques that will do this but the best write up I;ve seen is here http://www.labnol.org/internet/alternate-content-for-adblock/28602/

**Comment by Radek-Suski** [comment]
I think we should do this. Could be even maybe implemented via the CDN menu

**Comment by mbabker** [comment]
If someone wants to help with writing up JavaScript we can get it merged into the template or at least installed on sites that have ads.  My time's running kind of short at the moment; I can help with merging code to the template and getting updates pushed to admins but I'm not available to write out code right now (kinda burned my extra time allowance on the 3.4.5 release).

**Comment by Radek-Suski** [comment]
I can check it on weekend

**Comment by brianteeman** [comment]
Great - I would offer to help buy my JS is useless

On 28 October 2015 at 17:40, Radek Suski <notifications@github.com> wrote:

> I can check it on weekend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/146#issuecomment-151923304>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Radek-Suski** [comment]
Pull request created. If someone could improve my styling that would great.
It displays a bottom bar when ads blocker has been detected. 
![screen shot 2015-11-08 at 14 00 00](https://cloud.githubusercontent.com/assets/1110663/11020510/0f42cd8e-8621-11e5-9737-06e35abcb989.png)

**Comment by mbabker** [comment]
Added to main template and deployed on .org and dev.  I'll get around to adding it to API before the next deploy.  For the other sites, considering many are slow to update if they do at all, don't hold your breath.
