### ISSUE TITLE
[jdev] Cron Emails

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1462]
I had myself set up to receive emails for the weekly stats snapshot cron, recently someone has gone in and added cron jobs to run Akeeba Backup, but the results of those crons are being emailed to me as well.

Please configure the Akeeba crons to emit no output (meaning no email gets sent).  It would be good to check this on all sites because of the cron output isn’t silenced then it’s just spitting emails to an unwatched mailbox and eating disk space on every account.

**Comment by conconnl** [comment]
Thanks...
As discussed I updated the mentioned site configuration.
I will also check all other sites.

**Comment by conconnl** [comment]
All done, thanks again.
