### ISSUE TITLE
[ads] Spelling/Grammar Check In Notice, Styling Fix

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1463]
https://ads.joomla.org/register.html

1) "storing you informaion" should be "storing your information"

2) Any time a link is used inside of a Bootstrap alert, the `alert-link` class should be added to it so the link is actually visible (the class isn't a native feature of Bootstrap 2 but the general structure was backported from Bootstrap 3 into the core JUI library).

3) There should be a period at the end of the second sentence.

**Comment by conconnl** [comment]
Thanks, this is coming from the other properties which already had this sentence running. I will update it and try to find the other sites.

**Comment by conconnl** [comment]
Please confirm it's Ok now, on the site or at: https://github.com/joomla/joomla-websites/wiki
After I will copy it to the other sites.

**Comment by mbabker** [comment]
Looks fine

**Comment by conconnl** [comment]
Thanks for your valuable feedback.
I have tried to find all sites where it was used and replaced the string.
