### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#1464]
I try to register.
I do enter a password. The form removes the password and shows the attached screen. 
![temp](https://user-images.githubusercontent.com/4639364/83855929-16659b00-a719-11ea-9b85-917d0dd165a0.jpg)

**Comment by brianteeman** [comment]
@MartijnMaandag that is because someone has _mistakenly_ changed the password settings to now require a symbol. This is completely wrong and bad security as I reported at #1454 which was closed and locked because they knew better and now in #1461

**Comment by MartijnMaandag** [comment]
A Special character they mean. A letter is also a symbol for me. Maybe they can change the error-warning a littel bit.
I will close this.

**Comment by jeckodevelopment** [comment]
I'm sure that the decision has been discussed within the department.
I see there are other conversations about the requirements.

**Comment by brianteeman** [comment]
@MartijnMaandag sorry if i was a bit abrupt - I let my anger at the other report impact this one.

When it is written "symbols" it refers to !"£$%^
This is standard terminology in english

If it was written "special characters" then it would usually also include characters that do not have a direct key on the keyboard.

In the admin interface the tooltip when setting the symbols includes an example.

![image](https://user-images.githubusercontent.com/1296369/83875620-56377d00-a72f-11ea-92f3-06e7273b85ba.png)


Would it be clearer for you if the error message also included that information?

**Comment by MartijnMaandag** [comment]
What I do is copy-paste from KeePass.
I do hardly read the words just scan Passw... and paste the password. So I don't see the tooltip ;-) 
I think it is better to put it in the error message.

**Comment by brianteeman** [comment]
@MartijnMaandag That can be done and I will do that right now. 

However this is another example of a password manager that does not create passwords compliant with this silly rule which must be changed

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/29445
