### ISSUE TITLE
[certification] Save profile: Cannot select Country

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1468]
After loggin in at https://certification.joomla.org/ I need to save my profile but I can't.
The form complains that I have not selected a Country.
However, the country is already selected (Netherlands) and the selection dropdown is disabled
btw: The URL where I have this error:  https://certification.joomla.org/change-password?user_id=0

### Error after saving my profile:
![Screenshot_2020-06-08_13-00-22](https://user-images.githubusercontent.com/1217850/84023431-6302dd80-a988-11ea-8ce2-9f051d1fa184.png)

### Cannot select Country
![Screenshot_2020-06-08_13-00-56](https://user-images.githubusercontent.com/1217850/84023429-626a4700-a988-11ea-86bc-e33dd50f162f.png)

### Country selection is disabled
```
<select id="jform_com_fields_country" name="jform[com_fields][country]" 
class="required" required="required" aria-required="true" disabled="disabled" 
style="display: none;">
```

**Comment by conconnl** [comment]
I will contact you!

**Comment by pe7er** [comment]
The issue has been solved! Thanks @conconnl
