### ISSUE TITLE
[jevnt] Google Analytics Missing

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#147]
I was alerted that there's no traffic going to events.joomla.org. can someone get the analytics code in asap

**Comment by Radek-Suski** [comment]
Sorry. Forgot to add it after las template update. 
So blame @mbabker :P

**Comment by mbabker** [comment]
Put the codes into a plugin.  I did that for .org and the dev site so I don't have to remember to hack it in with every template update.
