### ISSUE TITLE
[joomla.org] wrong PR number in article "Joomla 3.9.19 Release"

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1471]
On https://www.joomla.org/announcements/release-news/5812-joomla-3-9-19.html
the item
- Extend the checks to make sure only real user admins can create accounts **#28948**

is wrongly tagged to 
PR #28948 https://github.com/joomla/joomla-cms/pull/28948

Please correct to
PR #24738 https://github.com/joomla/joomla-cms/pull/24738

(Thanks to forum user Krejt for reporting this issue at Joomla forum)

**Comment by HLeithner** [comment]
Fixed thanks
