### ISSUE TITLE
[jcm] 403 error text needs validating

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-websites#1474]
![jcm](https://user-images.githubusercontent.com/893049/85213922-90726280-b35c-11ea-9ad4-82ac3d5c7388.jpg)
default text used

**Comment by particthistle** [comment]
Raising in JCM team repository to arrange for not only text to be changed but also a login module to be displayed, as you should only see this if you're not logged in, so better UX is to show the login module than just telling you you've not got permission to access the page.

**Comment by particthistle** [comment]
@mandville can you describe how you got to the 403 error?

In going https://magazine.joomla.org/dashboard that if you're not logged in, you don't get the 403 message.

The triggering of the 403 though is not the problem you're raising though - it's that the message is still the default.
![image](https://user-images.githubusercontent.com/5515866/85946526-46a30100-b988-11ea-9f78-56c32bd6ea28.png)

**Comment by mandville** [comment]
i can not recall ho it happened.
the text is the issue

**Comment by conconnl** [comment]
A proposal within the webmasters team would be very helpful to update all websites.
For now the sentence "This request is blocked for security reasons." has been added within the component settings, which removes the default one displayed by the component.
