### ISSUE TITLE
[jcomm] Joomla! Community Portal issuing invalid new account activation links

### ISSUE THREAD

**Issue by pkortge** [joomla/joomla-websites#1475]
Just attempted to register at <https://community.joomla.org/register.html?layout=complete> and got the email below from <noreply@joomla.org>:-

++++++

Hello Peter KORTGE, 

Thank you for registering at Joomla! Community Portal. Your account is created and must be activated before you can use it. 
To activate the account select the following link or copy-paste it in your browser: 
tracking.joomla.org/tracking/click?d=Qm5CBAgeP8BFvn4jEFqkKB07Er4DqommwnzSJyk-3MBHoVwlfXgkGhAigBrDT7MwQnnORBvk5oxm23eatZ6qVbd6SCUdi_TOY9nT2_qziD0mC4MXdLol1ZN6VWz0oxa3KgVyOZlZYfTMo16DPeCMizbOsW0Ty8oYbgPtifqPazOkalBvrMkjlFWDzL3kn5iLYW8m8eAV5kVOeZng5Dow7nY-cFSjJsJgBA0hefGvapqXmCF4pwOIV4BgZk8H5GqOjg2 

After activation you may login to tracking.joomla.org/tracking/click?d=mKmJL0w5bL57w2bdZySoWhWTWd_k3bJ0oUK_ZC8ahbVAf0Io3CPDp6s8Iz2MpDi1vPz7F5jp8QKprEck-HPSPrjXAJiNaGTtyJH4jnBErxb8jOP8oJ6HNsxrfQqjZN-YoYmMmxVE7jk7_T5XAkxCytA1 using the following username and the password you entered during registration: 

Username: iworld 

tracking.joomla.org/tracking/unsubscribe?msgid=VzOmGBAtpuunH2wcY35rlQ2&c=1275285517176642890 
Created with Elastic Email. 
tracking.joomla.org/tracking/click?d=Dbo7PIeDYx3zqYlrhm-McEiE9yFi79qrfnhTzrMiOVT4rGMvFD9fMVXGSpAYTPFxyl--ND800BkJ3xuweE6WZ4v57UWnAAP-VMq00NXAaPQVPg3TiPPP31S3IcTelVBniHEeyGGvf2BINd4sEHz2ES7CqTesotMSNDhhuNc6JBiHacuCq70KnLo7FE

++++++

Does the system really need to generate an activation link that contains so much "alphabet soup" ??? I think that this is maybe what is causing the link to fail?

Also, the return email should not be <noreply@joomla.org> !!! There should be an email address to handle registration/activation issues that doesn't require someone to login to <github.com> to report a problem!

Regards, Peter KORTGE, iWorld
e: = info@iworld.com.au

**Comment by conconnl** [comment]
Thanks for reporting I will check what is going on and activate your account

**Comment by conconnl** [comment]
I have checked the system and your account was activated by you by using the link.
Can you tell me what errors you received as the activation was successful?

**Comment by pkortge** [comment]
Hi Wilco:

Good to hear from you again.

To answer your queries …  

Q1/.	I have checked the system and your account was activated by you by using the link.
Can you tell me what errors you received as the activation was successful?

A1/.	  Got this in Apple’s Safari Web browser:-



If you have any questions or queries, please don't hesitate to contact me on 0427 579 008.

I look forward to hearing from you in due course.

-- 

Regards ...
Peter KORTGE
46 Sandalwood Court
Flagstone  QLD  4280

  

e: peter@kortge.net
w: www.kortge.net  
p: 0490 044 867
m: 0427 579 008

Great minds discuss ideas; Average minds discuss events; Small minds discuss people.

**Comment by conconnl** [comment]
Replying on mail seems to remove the image.
I don't see your screenshot.

I just have tested the whole flow and clicking on the provided activation link results in:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/11913918/85378657-206e0300-b53b-11ea-9cc8-a25ff8b4a1ba.png">

On the page showing the message I can use the login form, to login onto the site.
It gives the following error, which has nothing to do with the registration, activation, etc.
It's something we will look at, as it's just not necessary.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/11913918/85378933-6fb43380-b53b-11ea-894d-376bacd73869.png">

**Comment by conconnl** [comment]
The mentioned error is also cleaned up.
Is there still anything I can do for you?

**Comment by pkortge** [comment]
Hi Wilco:

I’ve attached the screenshot again (this time in .jpg and .pdf formats) … and the activation link is still generating the same error message text:-

++++++

Safari Can’t Open the Page

"Safari can’t open the page “https://tracking.joomla.org/tracking/click?d=Qm5CBAgeP8BFvn4jEFqkKB07Er4DqommwnzSJyk-3MBHoVwlfXgkGhAigBrDT7MwQnnORBvk5oxm23eatZ6qVbd6SCUdi_TOY9nT2_qziD0mC4MXdLol1ZN6VWz0oxa3KgVyOZlZYfTMo16DPeCMizbOsW0Ty8oYbgPtifqPazOkalBvrMkjlFWDzL3kn5iLYW8m8eAV5kVOeZng5Dow7nY-cFSjJsJgBA0hefGvapqXmCF4pwOIV4BgZk8H5GqOjg2” because Safari can’t establish a secure connection to the server “tracking.joomla.org”.”

++++++


If you have any questions or queries, please don't hesitate to contact me on 0427 579 008.

I look forward to hearing from you in due course.

-- 

Regards ...
Peter KORTGE
46 Sandalwood Court
Flagstone  QLD  4280

  

e: peter@kortge.net
w: www.kortge.net  
p: 0490 044 867
m: 0427 579 008

Great minds discuss ideas; Average minds discuss events; Small minds discuss people.

**Comment by brianteeman** [comment]
@conconnl its because the link is https as it should be but its not setup correctly at your end

![image](https://user-images.githubusercontent.com/1296369/85388426-fbc75a80-b53d-11ea-9dfd-7db7d7084fcf.png)

**Comment by conconnl** [comment]
@pkortge thanks for sharing the info.
I have checked all links in the mail and they are sent without HTTPS, specifically for the reason it's a CNAME record and not an domain (It can't hold a certificate). It's even an configuration we don't own and directly communicates within the ElasticMail system. The configuration already exists for a few years, but it now seems to start giving problems.

I will send the supplier a message with the question how they are going to fix this, so it also works for you.
Every test I do, doesn't result in this problem, that doesn't mean it can't be an issue because of a possible preload hsts.
Probably we will need to use tracking.elasticemail.com instead of tracking.joomla.org which is ugly.

**Comment by brianteeman** [comment]
Its a simple fix. Stop tracking these emails. Tracking emails is for marketing campaigns not for transactional emails. When you stop tracking then elasticemail stops rewriting the url.

If you actually think about it asking someone to visit an insecure url to authenticate their account makes no sense at all.

**Comment by conconnl** [comment]
@pkortge 
Thanks again, we have solved the problem.
The HTTPS links are now working, it can take some time before all caching is updated.
The mentioned domain on HTTPS is now being correctly validated on special checks like SSLLabs.

I will close this issue as all check marks are green now.
You can off course reopen this issue, if you still have the problem after all caching is updated.
Or directly contact us by mail.
