### ISSUE TITLE
Crowdin Integrations Broken Across GitHub Repositories

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1481]
Apparently someone had taken it upon themselves to restructure the Crowdin projects for Joomla.  In doing so, integrations that were used in a number of repositories were broken.

At a minimum, this includes the downloads site and install from web server component, others may also be affected but I don't have the time to track them all down.

Changes like this should be communicated with all affected users prior to making the change so people do not find workflows unexpectedly broken.  Since the communication part was skipped over, I would now like to know what it will take for me to be able to provide updated translations for the install from web server component since it seems I don't have any form of admin level access to that project to even find an API key to just keep working without making a fuss.

**Comment by conconnl** [comment]
Technically I can imagine why IFW is broken.
Crowdin.yaml CLI config defines the "joomla-patchtester"
https://github.com/joomla/install-from-web-server/blob/master/crowdin.yaml

For the downloads the project identifier links to "joomla-official-sites"
Which is the following crowdin project: https://crowdin.com/project/joomla-official-sites
https://github.com/joomla/downloads.joomla.org/blob/master/crowdin.yaml

It seems to be updated:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/11913918/86489200-e9ca9080-bd63-11ea-807f-cd20d3a77d5f.png">

I can't say much about your access, you are still part of the Production related access.
Which should mean you still can access things like Crowdin Admin.
Configuration of Crowdin with Github can be done with the CLI API method or with the GitHub integration.

**Comment by mbabker** [comment]
Checked my config again, the downloads one did stay in place.

IFW definitely got moved to a new project though.  I have no access to retrieve the API token or upload a new version of the INI file through the UI though.  The only project I have a Settings button on, which would let me do either of those things, is the template project.

(Note, I'm not saying I want access, but it is irritating that the stuff was moved with no communication and the tools to handle uploads of new versions and downloads of translations not updated when the move was made)

**Comment by conconnl** [comment]
It looks like you have fixed IFW.
Anything else which needs to be done?
