### ISSUE TITLE
[jlaunch] Password invalid.

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#1482]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Somebody asked me "Can You help me, I want to learn Joomla, but I can't register at launch.joomla.org"
I tried but I can't also. When you register I see "Password invalid" Thats all. I tried a lot but can't get past this.

**Comment by conconnl** [comment]
@MartijnMaandag I have send the CloudAccess team a message to look at this.

**Comment by igorkaczor** [comment]
@MartijnMaandag we can't reproduce it from our end and need more details. Did you try that for the Free Site or the Paid Site option, and did you use any of the SSO registration options (Facebook, Google, Twitter)?

**Comment by igorkaczor** [comment]
@MartijnMaandag we have just fixed a bug that may have been affecting manual and sso registrations in some cases. Please try again and let us know if this is still happening.

**Comment by MartijnMaandag** [comment]
What now happens:
I enter on Launch.joomla.org:
martijnmaandag before "joomla.com"
Agree to the "Terms of Service", not on "help support"
Choose "Launch Now"
Register Manualy
Enter e-mailadres, password and Country (Netherlands).
Hit Register a pop-up passes and a fast message, which I can't read and nothing happens (no http://martijnmaandag.joomla.com)
I tried this with different browsers and different computers (all Windows10) and different e-mailaddresses.

**Comment by igorkaczor** [comment]
@MartijnMaandag we can't replicate the issue so it seems its related to something specific for you.
I have found that you had an old account with us in 2018 which may have been interfering. I have deleted it - please try again and let's see if that helped.
If not please contact us at support@cloudaccess.net pasting the link to this thread. 
We may need some specific details from you that shouldn't be posted on a public forum.

**Comment by MartijnMaandag** [comment]
This time i do see a "ready for Launch" screen, but I don't get a mail.
I will go to https://ccp.cloudaccess.net/submitticket.php
