### ISSUE TITLE
help.css paragraph style

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-websites#1483]
The help.css file used by the proxy server has no valid paragraph margin-bottom as seen in Firefox on Mac. See this url:

https://help.joomla.org/proxy?keyref=Help40:Content_Article_Manager&lang=en

So paragraphs are closed up making readability difficult. It looks Ok in Safari and Chrome, which both support webkit. Firefox does not.

**Comment by mbabker** [comment]
I've rewritten the site's CSS to be based on Bootstrap's Reboot component instead of the older reset.css and rebuilt everything else as a result of changing the CSS baseline and pulling out some stuff that appears to have targeted browsers 10 years ago.

**Comment by ceford** [comment]
Brilliant - thank you for that speedy response!
