### ISSUE TITLE
[JVP] - address checkbox state lost after IDP migration

### ISSUE THREAD

**Issue by JazParkyn** [joomla/joomla-websites#1485]
Please describe the problem or your issue:
My address checkbox was checked before the IDP migration, but now is showing as unchecked. My address is populated on IDP.
The same applies for a number of other profiles - I was attempting to review who hasn't yet populated their address for teams in the Programs Dept.
![image](https://user-images.githubusercontent.com/6943227/86825954-f1ea3f00-c087-11ea-8af8-5c558713a8b4.png)

It could be useful to include an URL of evidence:
Need to be logged in with edit permissions:
https://volunteers.joomla.org/teams/volunteer-engagement-team

**Comment by conconnl** [comment]
I can confirm, my address checkbox is gone as well now.
@roland-d or @sanderpotjer would you be able to look at this?

**Comment by sanderpotjer** [comment]
@roland-d for this we need a change in the post data of the IDP. It would be great if we can include a "smart" field for specific sites, maybe based on plugins?

In this example, we would like to know in the JVP if the "OSM Member Mailing address" consent is provided and if the fields of that consent are provided (address, zip, city, country). If that is the case a field with eg "osmAddress" `1` should be included, if not  "osmAddress" `0`.

In that way, we can catch that in the JVP and process it, without the need of passing the actual address data.

**Comment by roland-d** [comment]
@sanderpotjer This is now available for testing.

**Comment by sanderpotjer** [comment]
@JazParkyn the address checkbox is filled again, for those who provided their address on the IDP and "OSM Member Mailing address" consent.

**Comment by JazParkyn** [comment]
Fantastic, thanks!
