### ISSUE TITLE
[jcertif] 

### ISSUE THREAD

**Issue by bariweb** [joomla/joomla-websites#1486]
Hello, 
I just tried to complete my registration in certification.joomla.org but the system needs the country and I can't fill the data because the field is disabled.

Please see the attached image.

Best regards
Maurizio
![registration-problem](https://user-images.githubusercontent.com/45459926/86893749-682b8780-c102-11ea-822d-c7bd1030ef09.jpg)

**Comment by conconnl** [comment]
Thanks for reporting the issue.
We have fixed it.
