### ISSUE TITLE
[idp] 2FA emergency codes are badly formatted. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1487]
Edit your profile and enable 2FA with Google Authenticator on identity.joomla.org

Once saved, reedit your profile to copy your emergency codes for 2fa.

Note they are badly formatted, badly displayed and useless when copy and pasted. 

Screenshot:
<img width="621" alt="Screenshot 2020-07-08 at 12 19 52" src="https://user-images.githubusercontent.com/400092/86912946-c57d0400-c115-11ea-9871-a71be18a6458.png">

when copy and pasted:

```
2399- 4685- 5426- 1911 0338- 9538- 1812- 6207 4674- 6701- 5444- 6677 6474- 3691- 8842- 7419 0047- 5724- 8528- 2075 1439- 5961- 5021- 0688 8609- 9451- 3694- 5422 2853- 0365- 4226- 1464 3886- 3547- 1234- 4870 8367- 3914- 0021- 0891
```

**Comment by roland-d** [comment]
@PhilETaylor I have changed the layout, one OTP per line, easy copy/paste.

**Comment by PhilETaylor** [comment]
better now - thanks
