### ISSUE TITLE
[jdev] Captacha is marked as "optional"

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#1489]
Go to: https://developer.joomla.org/security/contact-the-team.html

![image](https://user-images.githubusercontent.com/2596554/85957952-0ba5cb00-b992-11ea-90cb-9e288f1ea11c.png)

Captacha "optional"?

cc @HLeithner

**Comment by conconnl** [comment]
https://github.com/pe7er/hCaptcha/issues/25
