### ISSUE TITLE
[jcertif] Feature Restorations: Certified Users Directory - Directory Search and Embedding Restrictions

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1492]
**There are multiple features broken on the Joomla Certification site since it's migration from Exam.joomla.org**

**Using a Wrapper to display a list of local Certified Administrators**
We'd had been cleverly using the search feature on the Certified Users Directory to display an iframe containing the results for Australia on the Joomla Australia website at https://joomla.org.au/get-help/australian-certified-joomlers

Today thought it's been bought to my attention that since the change from the exam subdomain to the certification subdomain, our module functionality has broken.

**Change in domain**
The module linked to
https://exam.joomla.org/directory?search=&country=AU&certification=&limit=20&limitstart=0&tmpl=component
which now gets a 301 redirect and now goes to this page as the new destination.
https://certification.joomla.org/certified-user-directory?search=&country=AU&certification=&limit=20&limitstart=0&tmpl=component
so we've updated the URL at our end now.

We're hoping that two pieces of functionality can be reviewed and restored:

**Allow embedding of the listings** 
We now get the following displayed when we go to embed the page, which is a setting at the certification.joomla.org end. 
![image](https://user-images.githubusercontent.com/5515866/87631741-53429a00-c77b-11ea-8c51-8fe238299290.png)

Can this be resolved so that we can embed the listing. If it needs to be allowed on a domain specific level, please allow joomla.org.au as the allowed domain.

**Restore Search And Filtering Functionality**
On the directory being moved from exam to certification subdomain, the directory had all it's search and filtering capabilities deprecated. This makes the directory pretty ineffective if you're trying to:
- filter for in-country Certified Joomla Administrators
- Search for an administrator by name if you were checking credentials

**Comment by conconnl** [comment]
We have never allowed embedding anything from our sites.
The CSP blocks this and will keep blocking it.
That it worked for the Exam site, is for the simple reason that we don't want to break the system until the final pieces are removed and therefore do not add the CSP.

For the Search / Filtering question, I added a public issue in our repository.
The feature was already on the list, we only have volunteers not payed people, so we can't force anybody.
