### ISSUE TITLE
shop.joomla.org expired SSL certificate

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-websites#1496]
https://shop.joomla.org/

The SSL certificate was valid until 11 June 2020.

Reported at the Joomla support forum at [https://forum.joomla.org/viewtopic.php?f=7&t=981195](url)

**Comment by HLeithner** [comment]
I reported it to rochen, thx for the report. I will give feedback when fixed.

**Comment by brianteeman** [comment]
Please see https://github.com/joomla/joomla-websites/issues/1097#issuecomment-371923974

**Comment by HLeithner** [comment]
That's unrelated, we have a wildcard certificate till may 2021.

**Comment by brianteeman** [comment]
it is related as the expired cert is also a wildcard ;)

**Comment by HLeithner** [comment]
@toivo rochen installed a new certificate.
