### ISSUE TITLE
[jdocs] Repairing Interwiki Links

### ISSUE THREAD

**Issue by cmbr** [joomla/joomla-websites#1497]
Some [interwiki links](https://docs.joomla.org/JDOC:Local_interwiki_links) have not been updated since the change from *http* to *https*. For example, the *jforum:nnn* link expands to:
`http://forum.joomla.org/viewforum.php?f=nnn`
The correct link location is
`https://forum.joomla.org/viewforum.php?f=nnn`
Please correct that [template](https://docs.joomla.org/Template:Jforum/doc).

**Comment by Hutchy68** [comment]
Everything is redirecting to https on j properties, but I did go through and updated all the ones that still seems relevant to https. Some of the platform and framework sites I don't think are valid anymore. Probably need to go through them all and delete out all the ones not used or valid. J properties and unused other external ones. Like gmailwiki.com (not a wiki now), http://teadvus.inspiral.org/ (dead), etc.

The template was updated too.
