### ISSUE TITLE
[jorg] Menu Item Corrections

### ISSUE THREAD

**Issue by cmbr** [joomla/joomla-websites#1498]
Several menu items in the top horizontal menu are being redirected and should be edited to bypass the redirects.

## Vulnerable Extensions List
The Vulnerable Extensions List has moved. See the top horizontal navigation bar on any page. Drop down the *Community & Support* menu item. The last item, *Vulnerable Extensions List*, links to
`https://vel.joomla.org/`

That URL redirects to
`https://extensions.joomla.org/`

I suggest, though, that the top menu item link directly to the *Vulnerable Extensions* page.
`https://extensions.joomla.org/vulnerable-extensions/vulnerable/`

## Events
Also under *Community & Support*, correct
`https://events.joomla.org/`
to
`https://community.joomla.org/events.html`

## Training
Under *Discover & Learn*, correct
`https://training.joomla.org/`
to
`https://community.joomla.org/joomla-training.html`

**Comment by conconnl** [comment]
Thanks for reporting.
The fixes are performed in our template repository, after the other changes are processed an update will be distributed on our websites. Which will change the network (cdn) menu.
