### ISSUE TITLE
[idp] No Joomla storwy yet

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1499]
On the profile page

<img width="472" alt="Screenshot 2020-07-24 at 22 16 51" src="https://user-images.githubusercontent.com/400092/88436065-6a2c6080-cdfb-11ea-8e85-5e0d378c6690.png">

> No Joomla storwy yet

Is this a typo? or just the English way of talking like a baby in a cartoon "I wanna stooorwwwwy"

**Comment by conconnl** [comment]
Thanks for sharing this typo with us, we will fix it.

**Comment by conconnl** [comment]
PR Merged by team.
Thanks again.
