### ISSUE TITLE
[jorg] Change over of top menu area to new standards

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#15]
The top menu area of the joomla.org website is using an old standard menu.

This needs to be upgraded to the new standard top level menu as seen on the Extension Directory and on the Volunteers Portal.

May need review by several parties to get into the old main website.

The newer menu has better keyboard tab highlighting and has a better standard of accessibility. (slightly)

Many benefits from change over and improvements.

**Comment by mbabker** [comment]
The sites that are still running 1.5 and 2.5 use a different template than the sites running 3.x (the top menu's difference is basically a custom mega menu versus a Bootstrap dropdown menu).  Personally, I would focus less on trying to integrate this design element in and more on upgrading these sites to 3.x (I know a team is working on this for the main .org site now).

**Comment by pbwebdev** [comment]
I'll close this one and crack the whip instead then on those teams.
