### ISSUE TITLE
no mention of hCaptacha in the Joomla official Privacy Policy

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1500]
There is also no mention of hCaptacha in the Joomla official Privacy Policy https://www.joomla.org/privacy-policy.html whereas its used on joomla properties.

**Comment by conconnl** [comment]
Correct, like a reasonable amount of other stuff. 
@jeckodevelopment can you confirm that the new version is finished and shared with the board for approval and publication?

**Comment by jeckodevelopment** [comment]
Hi, the new global privacy policy is on its way.
We aim to have it by the end of next week.
Sorry for the delay

**Comment by conconnl** [comment]
The new version has been published.
