### ISSUE TITLE
[jcm] Related Posts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1501]
I was reading this Joomla 4 article https://magazine.joomla.org/all-issues/july-2020/getting-templates-ready-for-joomla-4 and at the bottom I was surprised to see articles by Andrew Eddie And Fotis in the "Related Posts" section -

![image](https://user-images.githubusercontent.com/1296369/88654582-764b4300-d0c5-11ea-8134-59d74c0cd248.png)

Not only are they not related but they are 10 years old. At a minimum please could you change the display of the related posts so that they display the year as below

![image](https://user-images.githubusercontent.com/1296369/88654838-d3df8f80-d0c5-11ea-9562-b826bcf50331.png)

Better yet would be to fix the way related posts are chosen

**Comment by andreagentil** [comment]
Hi Brian, thanks for reporting this issue.

We've just changed the settings of the related post.
