### ISSUE TITLE
User blocked at Joomla Community Portal

### ISSUE THREAD

**Issue by fgsvictory** [joomla/joomla-websites#1502]
Hi,

How can I contact the administrators to unblock my user?

My email is: fredgribel@gmail.com

**Comment by ooffick** [comment]
Hi 

Can you tell me where you are blocked? Is it the Joomla! Forum?

Kind regards
Olaf

**Comment by fgsvictory** [comment]
[image: Screen Shot 2020-07-28 at 15.42.59.png]

Em ter., 28 de jul. de 2020 às 15:56, Olaf Offick <notifications@github.com>
escreveu:

**Comment by fgsvictory** [comment]
Did you receive the image? It is in the main site.

**Comment by ooffick** [comment]
No, I am afraid I cannot see the screenshot. When you say "main site", do you mean www.joomla.org ?

Kind regards
Olaf

**Comment by fgsvictory** [comment]
Yes www.joomla.org when I go to the login area and set my logon informations I receive the message: "Reminder failed: This user is blocked. If this is an error, please contact an administrator." I received an email with a link to reactivate my user but this link is crashed.

**Comment by conconnl** [comment]
Are you sure it’s about the www.joomla.org site, I ask because that specific address doesn’t have public users!

**Comment by fgsvictory** [comment]
Forgive me, it's https://community.joomla.org/joomla-training.html

**Comment by conconnl** [comment]
Enabled again.

**Comment by fgsvictory** [comment]
Thank you. It's working now
