### ISSUE TITLE
[jdev] Roadmap is full of out of date information

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1505]
It is a great thing to have a roadmap.
It is an embarrassement to have a roadmap where so many information are out of date (and some are just wrong). 
Can someone please take care of this page and think about updating it each time there's a new release? 

I highlighted some information that need to be updated: 
![1](https://user-images.githubusercontent.com/4682328/89307505-758c5100-d671-11ea-9121-ee02bc523740.png)

**Comment by HLeithner** [comment]
Thanks, updated
