### ISSUE TITLE
[jcertif] Restore search and filtering tools

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1506]
_Not finding an issue raised on this in joomla/joomla-websites, raising one now. Comment with the actual one if it exists._

Prior to being migrated to certification.joomla.org the Certified Administrator list on exam.joomla.org included sorting and filtering capabilities.

Please restore these to make https://certification.joomla.org/certified-user-directory more usable for those looking at finding a Certified Administrator.

**Comment by conconnl** [comment]
You already raised it before in: https://github.com/joomla/joomla-websites/issues/1492

Which is visible in the JCP Repo as well:
https://github.com/joomla/certification.joomla.org/issues/3
