### ISSUE TITLE
[idp] "Expiring consents" mail marked as spam

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-websites#1508]
The "Expiring consents on the Joomla! Identity Portal" mail get a high spam score:

```
X-Spam-Flag: Yes
X-Spam-Status: Yes, score=5.5, tag-level=5.5, block-level=8.0,
	envelope=bounces.joomla.org, from=joomla.org, bayes_tokens=Tokens: new,
	 44; hammy, 20; neutral, 98; spammy, 7.
X-Spam-Report: Flag: Yes,
	*  1.0 CUST_DNSBL_29_SENDERSC_MED RBL: score.senderscore.com
	*      (senderscore.com Medium)
	*      [54.36.22.7 listed in score.senderscore.com]
	* -0.1 CUST_DNSWL_5_ORG_NT RBL: list.dnswl.org (No Trust)
	*      [54.36.22.7 listed in list.dnswl.org]
	* -0.1 RCVD_IN_MSPIKE_H3 RBL: Good reputation (+3)
	*      [54.36.22.7 listed in wl.mailspike.net]
	*  0.3 URIBL_GREY Contains an URL listed in the URIBL greylist
	*      [URIs: elasticemail.com]
	*  1.5 BAYES_50 BODY: Bayes spam probability is 40 to 60%
	*      [score: 0.4989]
	* -0.1 SPF_PASS SPF: sender matches SPF record
	*  0.0 SPF_HELO_NONE SPF: HELO does not publish an SPF Record
	*  0.0 HTML_MESSAGE BODY: HTML included in message
	*  0.5 MIME_HTML_ONLY BODY: Message only has text/html MIME parts
	*  1.2 HTML_IMAGE_ONLY_20 BODY: HTML: images with 1600-2000 bytes of
	*      words
	* -0.1 DKIM_VALID_EF Message has a valid DKIM or DK signature from
	*      envelope-from domain
	* -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature
	*  0.1 DKIM_SIGNED Message has a DKIM or DK signature, not necessarily
	*       valid
	* -0.1 DKIM_VALID_AU Message has a valid DKIM or DK signature from
	*      author's domain
	*  0.0 RCVD_IN_MSPIKE_WL Mailspike good senders
	*  1.0 HTML_MIME_NO_HTML_TAG HTML-only message, but there is no HTML
	*      tag
	*  0.4 HTML_SHORT_LINK_IMG_3 HTML is very short with a linked image
	* -0.0 DKIMWL_WL_MED DKIMwl.org - Medium sender
```

The main problem for this is the invalid HTML part. I suspect that elasticemail converts the plain text mail to html to add the logo to it.

### Suggestion

Add a proper HTML and Plaintext part to the E-Mail.

### Reason

1.  0.5 MIME_HTML_ONLY BODY: Message only has text/html MIME parts
1.  1.2 HTML_IMAGE_ONLY_20 BODY: HTML: images with 1600-2000 bytes of words
1.  1.0 HTML_MIME_NO_HTML_TAG HTML-only message, but there is no HTML tag
1. 0.4 HTML_SHORT_LINK_IMG_3 HTML is very short with a linked image

Flag 1. means that the email only has an HTML Part and no plaintext part that should be easy to fix
Flag 2. means that the email is too short in combination with an image, with plaintext and proper html this should be fixed automatically
Flag 3. means the HTML part is broken because it doesn't start with `<html>`, it directly starts with a `<p>` fixed with proper html mail
Flag 4. more or less the same as 2.

**Comment by roland-d** [comment]
@HLeithner Thank you for this, the emails have been fixed and now includes the plaintext version as well. The HTML message contains the html tags.

**Comment by HLeithner** [comment]
Prefect thank you
