### ISSUE TITLE
[idp] Expiring Consent notice period

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1509]
Could you please increase the notification period before removing volunteer profiles etc five days is not long enough if someone was on holiday etc

Also its a bit confusing as it says the consent lasts for 1 year but it was only begun a few months ago

![image](https://user-images.githubusercontent.com/1296369/89871915-1ae28000-dbb0-11ea-8c03-719f721a4c21.png)

**Comment by Hutchy68** [comment]
Should be a minimum of 30 days with a reminder at 7 days and a last one at 24 hours.

**Comment by mandville** [comment]
> In case you do not provide us with your consent, we will no longer be able to process your data and your Volunteer profile will become anonymous.

Your consents are going to expire on 2020-05-26 19:37:33 (UTC), please take action prior to such date.

Confirming your consents is easy.

todays email

**Comment by brianteeman** [comment]
@mandville i have no idea what you are saying

**Comment by anibalsanchez** [comment]
I have checked my profile and it expires in "2020-08-16 10:58:48 (in 4 days)"

I didn't receive a notification explaining when, why or how I have to renew the consent.

**Comment by brianteeman** [comment]
Closing due to lack of response from anyone who can actually do anything to resolve this.
