### ISSUE TITLE
[idp] language string

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1511]
(I would have submitted a PR but there is no repo listed)

> Any active member of an official Joomla team is member of Open Source Matters.

Any active member of an official Joomla team is a member of Open Source Matters.

> The by-laws require your mailing address.

The by-laws require your mailing address is recorded.

**Comment by roland-d** [comment]
@brianteeman Thank you for the textual changes. These are not in the language files but in the consent description. I have updated them with your changes.
