### ISSUE TITLE
[jcomm]

### ISSUE THREAD

**Issue by buskerricc** [joomla/joomla-websites#1517]
Opening the link to download any of the language packages in this page https://community.joomla.org/translations/joomla-3-translations.html ends up in this error:

Unhandled PropelException [wrapped: Could not connect [User Info: host=192.168.105.102 dbname='gforge5' user='gforge' password='*********'] [User Info: Array]]
#0 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(203): Propel::getConnection('gf5')
#1 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(183): BaseLanguagePeer::doSelectRS(Object(Criteria), NULL)
#2 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(165): BaseLanguagePeer::doSelect(Object(Criteria), NULL)
#3 /opt/gforge.git/www/gf.php(113): BaseLanguagePeer::doSelectOne(Object(Criteria))
#4 {main}

**Comment by conconnl** [comment]
I just tested a few and they work for me.
Do you still have the problem. The site was offline for a few minutes?

**Comment by buskerricc** [comment]
The site seems to be online but the links doesn't work, now it works also
to me, just downloaded what I needed.
Thanks for assistance.

**Comment by conconnl** [comment]
Thanks for the confirmation
