### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by fujisawa2238** [joomla/joomla-websites#1519]
I am testing Joomla-4 now.
Since beta-3 came out, I installed it, but at the last "Install Joomla" stage, the following error occurred, and the process stopped.
Please tell me the cause and countermeasure.

’error
This is not implemented as pure PHP cannot implement Argon2i with acceptable performance.’

thank you.

**Comment by HLeithner** [comment]
Hi,

first this repository is only for *.joomla.org websites (the first line tells you this if you click on "New issue").

Second you need to install libsodium for your php version. More information at https://github.com/joomla/joomla-cms/issues/27375
