### ISSUE TITLE
[joomla.org] SECURITY INCIDENT

### ISSUE THREAD

**Issue by rmccarthy-mob** [joomla/joomla-websites#152]
I have been the target of a phishing attack that contains a link to a website built by your tool:  aaterapiahorticola.com.ar/

The subaddress for the source of the attack is:  aby/Index.html/index.php

It appears someone has buried a simple password collector there.

Do you have any knowledge of this, or are able to investigate this issue?

**Comment by MAT978** [comment]
This isn't a joomla.org web issue and we are not responsible for this. 
I would encourage you to try to reach out to the site's owner if you've noticed something that looks out of place.
