### ISSUE TITLE
[jdev] Roadmap still not updated correctly

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1522]
**3.9.21**
-  '1' is not linked
- it links to the 3.9.19 announcement

**3.10**
- no link to the Alpha release

**4.0**
- '3' is not linked
- Beta 3 links to Beta 1 announcement

**Last Updated**
- it should be August 25 and not August 11

**Comment by HLeithner** [comment]
At some point in the future I maybe do everything right on an update, in the meantime I thank you for your help finding the flaws ;-)
