### ISSUE TITLE
ads.joomla.org loads a second jQuery (v2.1.3) library

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1526]
Investigating another issue on JED, I've just noticed that ads.joomla.org is delivering another copy of jQuery (jQuery v2.1.3) after the core jQuery (jQuery v1.12.4-joomla).

https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js

```
:authority: ajax.googleapis.com
:method: GET
:path: /ajax/libs/jquery/2.1.3/jquery.min.js
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8,eu;q=0.7
cache-control: no-cache
pragma: no-cache
referer: https://ads.joomla.org/index.php?option=com_sa&view=remotecontrol&adData=%7B%22ads_params%22%3A%7B%22ad_unit%22%3A%22sa_ads32%22%2C%22zone%22%3A4%2C%22num_ads%22%3A1%2C%22ad_rotation%22%3A0%2C%22ad_rotation_delay%22%3A60%2C%22no_rand%22%3A1%7D%2C%22context_params%22%3A%7B%22keys%22%3Afalse%7D%7D&format=raw
sec-fetch-dest: script
sec-fetch-mode: no-cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
x-client-data: CIa2yQEIpbbJAQipncoBCJm1ygEIltbKAQ==
```
![jads-jquery](https://user-images.githubusercontent.com/385780/92327005-c3bcb780-f056-11ea-9b4d-7acb92716b67.png)

**Comment by conconnl** [comment]
Your screenshot holds a Google ad, loaded and provided by Google. Nothing we can do expect for removing google ads, which cost money. 
A won’t fix at this moment.

**Comment by brianteeman** [comment]
Wrong

**Comment by anibalsanchez** [comment]
Please, note that the issue affects all Joomla sites. The Community Portal is loading jquery three times.

**Comment by anibalsanchez** [comment]
On the forum, it is loading jquery four times:

![jqs](https://user-images.githubusercontent.com/385780/92332660-d0093a80-f07f-11ea-8f9f-8d3cdce62751.jpg)

**Comment by anibalsanchez** [comment]
My guess is that the ad server is adding jquery just in case, before redirecting the ad to Google. 

Google Ads service is not delivering jquery. So, this is not a request to remove Google Ads, only the dependency of jquery v2.1.3. 

Every time that jquery is reloaded, it losses the initialization of the previous jquery instance. As a consequence, the sites are not running on the core jQuery-Joomla  v1.12.4.

**Comment by JazParkyn** [comment]
The community portal only loads it once - the others come from Google
![image](https://user-images.githubusercontent.com/6943227/92333670-4eb1a800-f07f-11ea-8158-0950627d8440.png)

The forum only loads it once - the others come from Google
![image](https://user-images.githubusercontent.com/6943227/92333683-5d985a80-f07f-11ea-8343-8b16ba4e41ff.png)

The loading of jQuery is disabled in the component running on ads.joomla.org

**Comment by JazParkyn** [comment]
If you know of a solution to this, please share it in the Operations Dept chat.

**Comment by anibalsanchez** [comment]
Google Ads is not serving jQuery.

Joomla Ads server is delivering the ads in this way:

https://ads.joomla.org/index.php?option=com_sa&view=remotecontrol&adData=%7B%22ads_params%22%3A%7B%22ad_unit%22%3A%22sa_ads32%22%2C%22zone%22%3A4%2C%22num_ads%22%3A1%2C%22ad_rotation%22%3A0%2C%22ad_rotation_delay%22%3A60%2C%22no_rand%22%3A1%7D%2C%22context_params%22%3A%7B%22keys%22%3Afalse%7D%7D&format=raw

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<link rel="stylesheet" href="https://adscdn.joomla.org/modules/mod_socialads/assets/css/style.min.css?089b6cf22e8fd3a98082fd1a66b2299f&1598392480" />


<div class="sa_mod_sa_ads32" havezone="4">
	<div class = "ad_prev_main affiliate_div_style" preview_for= "2" ad_entry_number="0">

<div class="ad_prev_wrap layout6_ad_prev_wrap">
	<div class="preview-bodytext layout6_ad_prev_third">
		<div class='adtype' adtype='text'><div style="text-align:center;">
<script type="text/javascript">
google_ad_client = "ca-pub-1189370408998555";
google_ad_width = 728; 
google_ad_height = 90; 
google_ad_format = "728x90_as"; 
google_ad_type = "image"; 
google_ad_channel = ""; 
google_color_border = "FFFFFF"; 
google_color_bg = "FFFFFF"; 
google_color_link = "0000FF"; 
google_color_text = "000000"; 
google_color_url = "008000"; 
google_ui_features = "rc:10"; 
</script>
<script type="text/javascript" src="https://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
</div></div>	</div>
</div>
</div></div>

<script>
window.parent.postMessage(JSON.stringify({ad_unit:"sa_ads32", ad_count: "1"}), "*");
</script>
```

You could try to remove jQuery v2.1.3 from the output or check with the Ad Server provider why jQuery is required to be loaded on every Ad request.

**Comment by conconnl** [comment]
Closed: JED doesn't use ads site anymore

**Comment by anibalsanchez** [comment]
Great work!
