### ISSUE TITLE
[joomla.org] Captcha not working on Joomla login

### ISSUE THREAD

**Issue by fatgecko** [joomla/joomla-websites#1529]
I am trying to access an old website, but need to reset login password first.  On the website itself the Captcha is not showing, so can't reset password.
On the Joomla website itself, the Captcha is showing, but even when it is selected, it gives a Captcha error, as per below.

![image](https://user-images.githubusercontent.com/67764586/92536084-204cec00-f27c-11ea-9a12-36d5e5f155b0.png)

**Comment by conconnl** [comment]
Thanks for letting us know.
We are going to investigate why it doesn't work specifically on this site.

This doesn't help you accessing your website.
On the following page there are other options described to change your password:
https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

**Comment by Hutchy68** [comment]
Is someone going to fix this? Broken for over a month on j.org. How about changing from hcaptcha back to a captcha that actually works in the interim.

**Comment by conconnl** [comment]
Because it was fixed, but not mentioned on this page.
The site holds no public accounts, has no registration options, our template doesn't seem to have an option to hide to login button in the footer.

**Comment by Hutchy68** [comment]
This was for a forgot username. I witnessed it personally, same error on a phone.

**Comment by conconnl** [comment]
I just tested it again and it’s working, forget username and password. As I mentioned in the other reply, it was fixed for this site.

**Comment by Hutchy68** [comment]
Yes, I just tried and I can see it is working now. **BUT** it was not working when I originally posted a few hours ago. Tried forgot username three times in a 5 min period and I was presented with the same exact error posted in the screenshot above.

It is possible hCaptcha was down?

**Comment by brianteeman** [comment]
Reading this issue isnt the original poster referring to their OWN web site and not a Joomla property.

**Comment by conconnl** [comment]
> Reading this issue isnt the original poster referring to their OWN web site and not a Joomla property.

You would think so, it seemed our website was tried to see if it's a Joomla problem and with they found an issue on our site.
We tested it and indeed were able to confirm that just for the main site it didn't work, while the same configuration works on all other sites.

> It is possible hCaptcha was down?

Everything is possible, but the site also had some other perks which we were fixing and Rochen was doing some changes for me on the server around the time of your message.
The fact is... It was broken and we implemented a fix in the code.

**Comment by Hutchy68** [comment]
> On the Joomla website itself, the Captcha is showing, but even when it is selected, it gives a Captcha error, as per below.

I read it as the original try was their website but a check “On the Joomla website itself...” confirmed it was their website and J properties. Here is a screenshot. Exactly the same message I saw yesterday.

**Comment by Hutchy68** [comment]
Works as aspected. Testing it several more times over the past few days.
