### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by suklamc** [joomla/joomla-websites#1530]
Several template/extension developers populate demo data / provide a quick install.
Many of these have quite a bit of data populated in the **contacts component** .... 

Please ensure an ALERT is put out to these developers to avoid populating this data.
recently had multiple websites I maintain send out spam using the contact form of this contact

( "Send copy to submitter" can be kept disabled)

**Comment by brianteeman** [comment]
As a site builder I am sure you will agree that it is your responsibility to delete the dummy test content on the sites.

**Comment by conconnl** [comment]
Not related to our websites and reply given by member. - Close
