### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by dstokley20** [joomla/joomla-websites#1531]
Unable to view website www.jth73.com and unable to log into joomla.org website to update website.

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
