### ISSUE TITLE
[jrd] Map not loaded

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#154]
On https://resources.joomla.org/en/ the map is not loading... 
https issue : 
Mixed Content: The page at 'https://resources.joomla.org/en/' was loaded over HTTPS, but requested an insecure script 'http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&visualRefresh=true&libraries=places&language=en'. This request has been blocked; the content must be served over HTTPS.

**Comment by mbabker** [comment]
JRD's had an upgrade since this was reported, but there are still several HTTPS related issues.  Ping @artisanwebandprint

**Comment by genr8r** [comment]
that code is coming in through our geolocation component. I just pinged the developer for an update. I will update this issue once it is resolved.

**Comment by jeckodevelopment** [comment]
thank you Brian!

**Comment by genr8r** [comment]
Thanks for the ping @MATsxm I will hit the original developer again this afternoon.  I spent some time picking through the code but haven't been able to tease out where all the non-SSL urls are tucked away. FWIW - I think our homepage is the only outstanding issue.

**Comment by mbabker** [comment]
I looked at the site on HTTPS today and couldn't see any issues.  So, is this resolved?

**Comment by Radek-Suski** [comment]
I still see the issue 
![screen shot 2016-10-12 at 20 13 40](https://cloud.githubusercontent.com/assets/1110663/19322225/7cabd30a-90b8-11e6-83fb-8c615d1fdd3f.png)

**Comment by mbabker** [comment]
I saw that in the console but that doesn't look like it's affecting Google Maps (on the individual provider pages it was fine).  Then again on HTTP stuff doesn't work since Google's Geolocation requires HTTPS so maybe there is something still not working on the homepage.

**Comment by Radek-Suski** [comment]
But it won't load for me anyway. I am getting the annoying request for location service allowance (whose brilliant idea was that?) and no matter if I allow it or not, the map won't load

**Comment by mbabker** [comment]
Oh, gee, tell us how you really feel.

**Comment by Radek-Suski** [comment]
:hug:

**Comment by genr8r** [comment]
I have updates from the developer of the geo-radius component but it still appears not to have addressed the https issue. I will hit him again to address the issue.

And I agree @Radek-Suski that the location services nag should go away. I will fold its removal into this conversation. The "map" is actually a form that is using geo-radius to find Joomla service providers that are geographically proximate to the user. I cleared cache on the site and it is running for me. Feel free to let me know if it is still not loading for you.

**Comment by Sandra97** [comment]
@genr8r Any news about the map issue?
Still nothing displayed for me except the "loading" image
![jrd](https://cloud.githubusercontent.com/assets/4682328/23096135/cceaae42-f5ec-11e6-8ab4-bd60ed68d17a.png)

**Comment by MATsxm** [comment]
@genr8r can we expect something before the 4.0?

**Comment by genr8r** [comment]
Hi @MATsxm. Yes, our team made the decision earlier this week to pull the geo-radius search function. The site works well with the default categories and geo was introducing too many challenges.

1. Updates to geo are available but have been conflicting with other aspects of the site.
2. Does anyone really like their browser asking about location every time the page loads?
3. The language sequence in geo was random and conflicting with now abandoned josetta.
4. The geo component was breaking https on the front page preventing us from forcing https site wide.

The decision has followed years long discussions about geographic proximity not necessarily being the best search vector anyway.

We have retained our core functionality, we will be stripping out deprecated software that is no longer being used, and we are laying the groundwork for JRD 3.0.

I have long neglected posting updates via the volunteers portal. I think this post is about to get a copy, edit, paste to address that. Best of all I get to close several ridiculously long outstanding issues.

Feel free to re-open this issue or reach out to me directly if there are other outstanding concerns related to this. In the meantime, I will do a quick review of JRD issues here that have now been addressed with this switch.
