### ISSUE TITLE
[jhelp] Help screen missing for new Mail Templates feature

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1542]
Help missing for the following keys:
- Help40:JHELP_CONFIG_MAIL_MANAGER
- Help40:JHELP_COMPONENTS_COM_MAILS_OPTIONS
- Help40:JHELP_CONFIG_MAIL_MANAGER_EDIT

System > Mail Templates > Help
System > Mail Templates > Options > Help
System > Mail Templates > Edit a template > Help

![image](https://user-images.githubusercontent.com/5515866/95652289-b73aeb80-0b3b-11eb-8b66-16e90704344e.png)

![image](https://user-images.githubusercontent.com/5515866/95652347-fec17780-0b3b-11eb-98e2-84eac0101daa.png)

**Comment by ceford** [comment]
Noticed! As I have fixed all of the other Help screens over the summer I will look into this one.

**Comment by ceford** [comment]
The code changes have been committed and should be in the next nightly build so you can close this issue.

**Comment by particthistle** [comment]
Confirmed help screens are now accessible in Joomla 4 (Beta 5, nightly build 12/10/2020).
