### ISSUE TITLE
[jdocs] - Pages in category "Tutorials" stuck on first page

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-websites#1543]
Please describe the problem or your issue

On this page:
https://docs.joomla.org/index.php?title=Category:Tutorials&pagefrom=Creating+a+Plugin+for+Joomla
The (previous page) and (next page) links show the first page so it is impossible to move on. 
Unless you think to Open page in New Tab. I notice they both have #mw-pages at the end of their urls.

**Comment by particthistle** [comment]
Also effects Development category.

Pagination through the pages section is not working when a category has more than 200 articles. The pagination is limited to 200 records per page and there's 712 articles tagged Tutorials Category, 370 in Development.

Clicking on Next Page just refreshes the page while adding #mw-pages, or it might work on the first click, but not then on subsequent pagination clicks.

https://docs.joomla.org/index.php?title=Category:Tutorials
https://docs.joomla.org/index.php?title=Category:Development

https://docs.joomla.org/Category:Top_Level the above two categories are the only two showing in the Top Level page with more than 200 records.

Tested with Windows chrome, firefox and edge. Mac chrome.

![Jdocs Pagination](https://user-images.githubusercontent.com/5515866/95809695-26425b00-0d5b-11eb-8b45-5a1c62ba9ec1.gif)

**Comment by Hutchy68** [comment]
It only affected category pages with pagination, more than 200 pages in a category. Fixed.

**Comment by Hutchy68** [comment]
Closing as it is fixed
