### ISSUE TITLE
[jorg] 1500 volunteers or 218?

### ISSUE THREAD

**Issue by gostn** [joomla/joomla-websites#1545]
https://www.joomla.org/ count 1500 volunteers

![image](https://user-images.githubusercontent.com/71960554/96148698-cc7f9380-0f08-11eb-8f41-44519a337749.png)

https://volunteers.joomla.org/ 218

![image](https://user-images.githubusercontent.com/71960554/96148801-e91bcb80-0f08-11eb-9eb6-e9c1aa83f81b.png)

**Comment by gostn** [comment]
Correction: https://volunteers.joomla.org/ count now 219.

**Comment by hvdmeer** [comment]
I would guess a lot are anonymous now since they didn't give consent to have their profile on the portal.

**Comment by gostn** [comment]
I guess it makes a confusing impress of Joomla showing this different counts. My solution is to count on both places the same number, which is now 219.
