### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by hjsrolde** [joomla/joomla-websites#1547]
Hi There
I found that you can use hyperlink in First Name Field at next step when you are entering your personal information on Get Demo form and then you will get the first email of Welcome then hyperlink will be there at the Place of First name.
Steps:
1. Go to the website and click create account.
2. Put Hyperlink on  Username field.
3. Put all the other information then click Signup.
4. Go to your email and open your first mail from your site..
You will see Hyperlink is working..
Impact :
This permits users to send malicious/phishing links to potential clients.roblem

![hyperlink2](https://user-images.githubusercontent.com/45832433/96442911-25eb0980-120c-11eb-8700-11fde7d40f35.png)
![hyperlink1](https://user-images.githubusercontent.com/45832433/96442914-2683a000-120c-11eb-8622-35518b1b8d16.png)

**Comment by conconnl** [comment]
Can you please tell us on which Joomla Org website you found this problem with a Demo Form

**Comment by hjsrolde** [comment]
Hi Wilco, Thanks for the follow up. I forwarded an issue that was an internal issue at Cryptohopper. From now on, I will first check with our developers whether an issue is Joomla related or Cryptohopper related.  My apologies for the inconvenience, I will check it first internally before posting a Joomla issue. Kind regards,   Sent from Mail for Windows 10 From: Wilco AlsemgeestSent: Tuesday, October 27, 2020 3:41 PMTo: joomla/joomla-websitesCc: hjsrolde; AuthorSubject: Re: [joomla/joomla-websites] [joomla.org] (#1547) Can you please tell us on which Joomla Org website you found this problem with a Demo Form—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
