### ISSUE TITLE
[jrd] No repository for Joomla languages

### ISSUE THREAD

**Issue by mariarn** [joomla/joomla-websites#1549]
Hi,

When I try to install a new language in the Joomla administrator, it returns an error for all idioms.

**Error
Unable to find install package**

When I check the link of any of the languages ​​that I want to install and the Joomla Administrator makes the request to,
https://update.joomla.org/language/details3/fr-FR_details.xml

If you see that .zip links, for example,
http://joomlacode.org/gf/download/frsrelease/20042/162937/fr-FR_joomla_lang_full_3.4.8v1.zip
http://joomlacode.org/gf/download/frsrelease/20999/165681/fr-FR_joomla_lang_full_3.9.20v1.zip
(if you access to URL you see that have error connection in server)

Unhandled PropelException [wrapped: Could not connect...

Is there a problem with server languages repository?

Thanks, 
regards

**Comment by conconnl** [comment]
Thanks for letting us know.
We contacted the Hosting supplier to take action on the system.

**Comment by conconnl** [comment]
The system is responding again.
Thanks again.
