### ISSUE TITLE
[jshow] issue with about us page

### ISSUE THREAD

**Issue by carlostester** [joomla/joomla-websites#155]
in the about us page, social icons opensin the same page, should open in a new one 
http://joomla-showcase.octopoos-dev.com/about-jss.html

**Comment by MATsxm** [comment]
@sebastienlapoux
Thank you to take a look.

**Comment by oliviernolbert** [comment]
Fixed, thanks.

**Comment by oliviernolbert** [comment]
Updated url for testing: https://showcase.joomla.org/new/about-jsd/team-members.html

**Comment by MATsxm** [comment]
Thanks
Closed - Reopen if needed
