### ISSUE TITLE
[jcomm] 0 The image file does not exist.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1550]
Some old URLs that are very popular, like this one:

https://community.joomla.org/blogs/community/this-is-the-last-release-of-joomla-25-now-what.html

Are now giving error

`0 The image file does not exist.`

<img width="1140" alt="Screenshot 2020-10-29 at 10 34 29" src="https://user-images.githubusercontent.com/400092/97557184-5718c600-19d2-11eb-9a96-84e91f1f382b.png">

**Comment by conconnl** [comment]
Thanks for the notice.
The article only seems to load https://community.joomla.org/images/archive/stories/blogs/25_farewell.png
Which opens in the browser.

Any suggestions what it can be?

**Comment by PhilETaylor** [comment]
I have absolutely no idea.

**Comment by zero-24** [comment]
Thanks solved by: https://github.com/joomla-projects/plg_content_joomlarrssb/releases/tag/3.0.6 the regex for the image detection was broken and i was stupid enough to not check whether that file exists ... But both issues should be fixed now once the patched version has been installed

**Comment by PhilETaylor** [comment]
It seems resolved now, the page loads. Thanks
