### ISSUE TITLE
[jlaunch] Update DNS naming conventions register

### ISSUE THREAD

**Issue by ABashfo** [joomla/joomla-websites#1552]
Problem; naming conventions? probably
Where:    https://launch.joomla.org/

Does not allow '.uk' domain names to be used. I am assuming it would allow '.co.uk' or '.com' - The name I entered is registered domain not hosted elsewhere (as per requirement there).

I know nothing about what i am about to ask therefore i apologise for any fuzzy wording, my purpose for joining was as a pre-newbie to start somewhere and was not allowed as follows:

Background as i know it:  i registered a name to use on the launch.joomla.org site which is not permitted as a correction is requested (form turns domain name box red). I therefore made some checks as the name registered was recent.

The registered name is over a week old and while i checked it with the registrar and the name is verified as valid / paid for/ fully registered and ready to use. 

- their suggestion was the site or program i am attempting to use may need the naming database legalities of 'DNS' updating,  to include the new '.uk' and other top level domain naming conventions thingys endings. They only checked my registered names validity and not the form so it could be the joomla form allowing-ness part or the joomlas hosting via cloud control panel?.

[namingJoomla! Launch.pdf](https://github.com/joomla/joomla-websites/files/5510589/namingJoomla.Launch.pdf)
 
Thanks :)

**Comment by conconnl** [comment]
Hi @ABashfo 
Thanks for sending this message.

The site created on launch.joomla.org are "*.joomla.com" you can't use other TLDs like .uk
If you enter anabashford you will get anabashford.joomla.com

The error is indeed not clear (you are not entering a domain name), I asked the Launch team to update that.

**Comment by ABashfo** [comment]
Hello again :)

Many thanks for looking into this for me.

I have tried as suggested without using TLD identifier and with and without dot after name choice, with much the same result - red box showing invalid :/

Can someone test the form? to see if something obvious becomes apparent? I have hopefully attached my new entry to this page (I have tried with and without DOT after my name. (i used my country as uk and usa launch was fixed)
[2Joomla! Launch.pdf](https://github.com/joomla/joomla-websites/files/5518268/2Joomla.Launch.pdf)

The video content copyrighted 2020, on 'how to' by OS Training is very outdated too (joomla 3)  as it uses a different site altogether for demo joomla.

**Comment by DSniegu** [comment]
Hello, my name is Derek and I'm the Support Team Lead for CloudAccess.net which mainstains launch.joomla.org
Can you try the name without capital letters? No dot at the end of the name as well.
If it's still causing problems, please ues this https://screencast-o-matic.com/ to provide us with a video of what exactly you're seeing there.

**Comment by ABashfo** [comment]
thank you :)
our paths must have crossed, i was just trying it one more time and it sprang to life from a different webpage! 
Worked straight away and have received email confirming. 
whatever you did it worked, many thanks :) 
    On Tuesday, November 10, 2020, 03:27:34 PM GMT, DSniegu <notifications@github.com> wrote:  
 
 


Hello, my name is Derek and I'm the Support Team Lead for CloudAccess.net which mainstains launch.joomla.org
Can you try the name without capital letters? No dot at the end of the name as well.
If it's still causing problems, please ues this https://screencast-o-matic.com/ to provide us with a video of what exactly you're seeing there.
