### ISSUE TITLE
[jdocs] Using the Page Class Suffix in Template Code

### ISSUE THREAD

**Issue by mozaffar** [joomla/joomla-websites#1553]
In following link:

[https://docs.joomla.org/Using_the_Page_Class_Suffix_in_Template_Code](url)

In section **"By Active Menu Item"** - Subsection 2:

Instead of **`$menu->params->get`** you should write **`$menu->getParams()->get`**

**Comment by conconnl** [comment]
Hi @mozaffar 
The link you shared is for the J1.5 version, are you sure it needs to be changed?
