### ISSUE TITLE
[jcomm] Registration

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1554]
No idea what the DPCalendar thing is

![image](https://user-images.githubusercontent.com/1296369/99722395-850c9a00-2aa8-11eb-8bef-7c5f746361b3.png)

Whatever it is its not working as I am sure that 01 is not going to be a real token

![image](https://user-images.githubusercontent.com/1296369/99722507-a9687680-2aa8-11eb-9564-454ce9a22aa7.png)

**Comment by conconnl** [comment]
Thanks for noticing.
According to the DPCalendar documentation it's "Private token to get the ical feed without be logged in. Use with caution!"
With default value "yes".

I have disabled the setting, so it's not visible anymore.
