### ISSUE TITLE
[jcomm] SPD Terms and conditions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1555]
> Listing Content and the Applicant’s website linked from the listing must not promote ideological, religious, or political matters.

I am very disturbed by this clause. Open Source software is by its very nature both ideological and political. Hopefully the SPD doesn't intend to ban/block/punish sites that promote the use of open source software?

Would it block a site for having a banner promoting a political statement such as black lives matters? 

joomla.org and open source matters have at many times over the years made public statements that are ideological and political in nature and not directly related to joomla. Is it one rule for Joomla and another rule for everyone else.

Or is this just a cookie cutter terms and conditions that no one has really read and thought about

Finally who is to determine if something is ideological, religious or political and on what criteria

**Comment by conconnl** [comment]
@genr8r can you please answer the question?
The document was written by the Resources Directory members and used on that site for many years.
I hope you know what this means and why it's in there, as you were the TL for 6 years.

**Comment by genr8r** [comment]
Thanks for looping me in @conconnl. We originally got the Terms and Conditions from legal. So I am betting it is just language that is getting carried over from one iteration of the site to the next.

@brianteeman, I agree strongly that open source by its very nature is political/ideological. I am confident that this language failed to consider fully those implications. Are you just recommending the language be removed or do you have a clarification? I would wager the intent is to keep us from getting into idealogical battles that have nothing to do with open source in general or Joomla in particular. I also agree that trying to adjudicate what is objectionable per this statement is also a potential minefield.

**Comment by brianteeman** [comment]
This is fairly standard cookie cutter legal terms. Of course it is legally valid - I am not questioning that. It just goes against everything we should believe in and is impossible to _police_ in a global internet. Just kill the term. It really serves no purpose other than for someone to use it as a bat to hit people with.

Interestingly this was the exact question I was asked during my session at wordcamp.eu last year so my answer is on video.

**Comment by conconnl** [comment]
@genr8r do you have any update on this.
Specifically what we should do, update, change, remove or involve someone else?

**Comment by brianteeman** [comment]
Closing due to lack of response/action from anyone who is allowed to do anything.

So quick to create policies. So slow to carry them out or to correct obvious mistakes.
