### ISSUE TITLE
JED down

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1557]
00:22 GMT 20 Nov 2020

The jed site is down
![image](https://user-images.githubusercontent.com/1296369/99740291-99f82600-2ac6-11eb-86e4-b38b6611b925.png)

![image](https://user-images.githubusercontent.com/1296369/99740319-a7adab80-2ac6-11eb-96aa-5b38c74baf29.png)

**Comment by conconnl** [comment]
https://status.joomla.org/785709459

<img width="987" alt="image" src="https://user-images.githubusercontent.com/11913918/99743132-4e994400-2ad5-11eb-8516-b69ac90008fd.png">

**Comment by brianteeman** [comment]
oh cool - I must have missed the announcement of that site as I would have checked first.

**Comment by conconnl** [comment]
A new feature from uptime robot.
Enabled a few hours ago.
