### ISSUE TITLE
re removal of sites

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1558]
You closed the issue #1556 with a statement which means that my original comment was lost in translation

> Except now no one will see my training entry because you removed it instead of redirecting the existing entry.

I am NOT referring to the redirect put in place for bookmarked entries as you assumed. I had read the blog post and saw that this was in place.

I am referring to the fact that if you go to https://resources.joomla.org/category/training-education my entry has been removed from there. So its great that you set up the redirect for bookmarked links but that was not what I was talking about.

The situation right now is that anyone looking for joomla training will be directed to
https://resources.joomla.org/category/training-education

My listing has been removed from that page

My suggestion was that the existing listing was not removed from the current JRD but the links to it were redirected to the new site. That would maintain the visibility of the site on the https://resources.joomla.org/category/training-education page but send the user to the new directory for updated details.

If your own business was reliant on traffic from the JRD (even just a small %) then you would realise the importance of this. As of right now the visibility of my listing is almost zero and therefore the traffic is almost zero and therefore the income is almost zero.

So please stop and think before responding. If you think  the person is angry and you dont see why - dont assume they are idiots - ask for clarification.

**Comment by conconnl** [comment]
To please you
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/11913918/99743328-c1a2ba80-2ad5-11eb-9c52-fa065dde7b30.png">

**Comment by brianteeman** [comment]
Thank you for doing this and acknowledging the mistake. I accept your apology. I trust that this will be done for ALL listings - at least until the site is retired.
