### ISSUE TITLE
[jdocs] Adding favicon not trivial

### ISSUE THREAD

**Issue by janvle** [joomla/joomla-websites#1562]
[This page](https://docs.joomla.org/Special:MyLanguage/Changing_the_site_favicon) describes how to change a website's favicon, but it seems to be outdated and/or incomplete:

- of the links for converting to an ico-format I found one non-existing and two which timed out.

- copying a ico-file to `/joomla/templates/<your template>` is not trivial at all: what extensions and/or MIME-types must be enabled where?

- there is no code in `http://yoursite.com/templates/your_template/index.php` that contains the text '<link rel="shortcut icon"`, not even in the default template.

- what works is Phoca Favicon, but that is not mentioned.

- the Joomla forum [mentions](https://forum.joomla.org/viewtopic.php?t=980660) that png-files can be used as favicons, which is a much cleaner solution than using ico-files, but how do you get that to work?

So many questions on a page which says "Changing your website's favicon is a relatively easy task." makes me file this issue.
I'm sorry for being not too specific; if any details are helpful, please ask. I'm using Joomla! 3.9.22.

**Comment by MartijnMaandag** [comment]
Someone referred me to this issue.

About Joomla documentation:
Joomla Documentation is like Joomla, everebody can change wrong documentation.

> of the links for converting to an ico-format I found one non-existing and two which timed out.
One link pointed to a Deprecated project I removed the link. No time-outs for me.

> copying a ico-file to /joomla/templates/<your template> is not trivial at all: what extensions and/or MIME-types must be enabled where?
As far as I know, nothing, nowhere. Correct me if i am wrong.

> there is no code in http://yoursite.com/templates/your_template/index.php that contains the text '<link rel="shortcut icon"`, not even in the default template.
If you read: "**Some** templates contain code that redirects the browser .........."

> what works is Phoca Favicon, but that is not mentioned.
As I mentioned: "Add your text"

> the Joomla forum mentions that png-files can be used as favicons, which is a much cleaner solution than using ico-files, but how do you get that to work?
The forum does not answer this. If someone finds the "How to", change the text.
