### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by FodorTheMagnificent** [joomla/joomla-websites#1564]
Hi, I cannot log into or register for Joomla forum.  I am confused about all the different user names and password I need to create.   Then they don't seem to work.  I just created identity.joomla.org.   I used have an account on forum.joomla .org    My user and Pw don't work.  When I try to create another account, it says my email is already in use.   Yet I can't get it to send my username nor a new password.    

It's not me, I swear!  It's something the joomla admin needs to look into.  Thanks.

I can't find anyplace to ask for help, so I'm putting my request for support here.

Please someone on the backend help me to log into or create a new Joomla.org access

**Comment by ooffick** [comment]
Hi,

I can help you with getting your login back. The forum is not using the identity portal at the moment. At some point in the future that will most likely change but at the moment it requires a separate login.

To help you with your forum login, can you send us a message via the following form:
https://community.joomla.org/helpdesk/forum-un-ban-request.html

Kind regards
Olaf
