### ISSUE TITLE
Login identify joomla org error

### ISSUE THREAD

**Issue by shawnhy** [joomla/joomla-websites#1565]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

I was trying to see what I can help with improving joomla. I face a problem with login to this site. (https://identity.joomla.org/) My account was reported "username/password error" (it was reported error message "varification interruptted by user" eariler) . I tryed sign up again but it says account exists.
![Login_with_your_Identity_account](https://user-images.githubusercontent.com/7928790/101317165-ec905b00-3898-11eb-9b1d-96e64fa809f0.jpg)

**Comment by sanderpotjer** [comment]
@roland-d can you have a look at this?

**Comment by roland-d** [comment]
Hello @shawnhy Looking at your account it says you never logged into the identity portal before. Perhaps your password is incorrect. Can you try to do a password reset and see if you can login after that?

There is a **Forgot password** link at the bottom of the login page.

Let us know how it goes.

**Comment by conconnl** [comment]
Closing for lack of response
