### ISSUE TITLE
[jcomm] View All Service Providers

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1566]
Go to any entry in the service providers directory for example

https://community.joomla.org/service-providers-directory/listings/105-joomla-training-uk.html

On the menu you will see that the first entry is not highlighted as a link and if you hover over it the cursor does not change to a hand indicating that it is a link.

![image](https://user-images.githubusercontent.com/1296369/101648509-ca7e1080-3a31-11eb-8e78-c9e8191db1e4.png)

However it is a link and as its the only way to get back to the home page of the directory it needs to appear as a link

The problems come from this css
```
.nav-tabs>.active>a,.nav-tabs>.active>a:hover,.nav-tabs>.active>a:focus {
    color: #555;
    cursor: default;
    background-color: #fff;
    border: 1px solid #ddd;
    border-bottom-color: transparent
}
```

If you change it to the following then it works better (I have not checked if it has any impact elsewhere so it might need a more specific css

```
.nav-tabs>.active>a, .nav-tabs>.active>a:hover, .nav-tabs>.active>a:focus {
    color: #08c;
    cursor: pointer;
    background-color: #ddd;
    border: 1px solid #ddd;
    border-bottom-color: transparent;
}
```

![image](https://user-images.githubusercontent.com/1296369/101648457-bcc88b00-3a31-11eb-8a7c-d3c66e3501b7.png)

**Comment by JazParkyn** [comment]
Thanks for reporting - css rules updated.

**Comment by brianteeman** [comment]
thanks
