### ISSUE TITLE
[jcomm] Community Sponsorship Campaign, hCaptcha Error, payment impossible

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-websites#1570]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue:
It is not possible to sponsor and pay for Joomla Community Campaign!
The form filled returned no error, but the hCaptcha errors:
`Invalid verification code entered`
and it is not possbile to proceed to payment.

I tried several times, with 2 different browsers.

https://community.joomla.org/community-2017.html

![Screen Shot 2020-12-31 at 02 11 38](https://user-images.githubusercontent.com/1945310/103391105-9fa64a00-4b0f-11eb-9330-fe18aeb04b20.png)

**Comment by HLeithner** [comment]
I can confirm this issue, tested with vivaldi

**Comment by hvdmeer** [comment]
I didn't catch this issue, this goes for everyone who wants to donate? If so we will postpone our social post about the Sponsorship until this is resolved

**Comment by conconnl** [comment]
The complete system is replaced with something new.
