### ISSUE TITLE
[jcomm] helpdesk consent

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1571]
The _new_ helpdesk has a field on the submission form that requests consent to collect details 

1.) As you have to be logged in for you to be able to access the form you have already consented to the website collecting my details as the website clearly already has them.

2.) the field is a required field but unlike the other fields on the form it is not marked as a required field

![image](https://user-images.githubusercontent.com/1296369/103827756-9cf8a700-5071-11eb-8f12-04502d12f0c9.png)

![image](https://user-images.githubusercontent.com/1296369/103827764-9ff39780-5071-11eb-8014-811452d2bc88.png)

**Comment by brianteeman** [comment]
I now see that when different options are chosen then there are further fields exposed and consent would be required. However the comment about marking the field as required is still correct.

**Comment by conconnl** [comment]
Thanks for sharing.
I will send RSJoomla a ticket if they can add a star to the consent box in their RSTickets!Pro component.
It's a default field which only has the option enable/disable.

**Comment by conconnl** [comment]
Done.
I also added a temporary language override.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/11913918/103832050-b99adc00-507d-11eb-8b10-220a32a6954e.png">

**Comment by brianteeman** [comment]
Thank you. I suggest leaving this open until permanently resolved.

**Comment by conconnl** [comment]
A change was provided by RSJoomla and implemented on the site.

**Comment by brianteeman** [comment]
I can confirm that the * is now present so at least visual users get a consistent ui.

I am going to completely ignore that all of the fields are not marked as required in code as they should be. The thought that joomla would only use quality and accessible code on its own sites seems alien to everyone.

**That page alone has approx 50 accessibility errors**

**Comment by conconnl** [comment]
Thanks for checking and confirming.
