### ISSUE TITLE
[jcomm] Helpdesk JUG Registration

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1572]
On the JUG registration form there is a checkbox to confirm you have read both the rules of submission and terms of service

![image](https://user-images.githubusercontent.com/1296369/103829639-db429600-5072-11eb-9457-f704b350b38b.png)

However it is not possible for anyone to read either of those as a link in a bootstrap tooltip can never be clicked on. As soon as you move the mouse to try and click on the link the tooltip will disappear.

![buts](https://user-images.githubusercontent.com/1296369/103831199-73d91600-5073-11eb-9ab7-957769194e49.gif)

**Comment by conconnl** [comment]
Thanks for sharing.
I have changed the fields within the capabilities of the component.
A user can now at least use the links to read the mentioned pages.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/11913918/103833071-51012e80-5080-11eb-893d-1bb2291c8808.png">

@webdjam if you require any additional changes, we are available to help with that.

**Comment by brianteeman** [comment]
thanks
