### ISSUE TITLE
[jlaunch] Impossible to create a new account 

### ISSUE THREAD

**Issue by agerix** [joomla/joomla-websites#1575]
Hello,

Impossible to create a new account on launch.joomla.org
I've tried with Facebook and Google account and also manually but nothing happen after I have filled the fields

**Comment by Pawel-Panek** [comment]
Hello @agerix 

The issue is likely due to CSP blocking the register request. It's been now modified and the registration works now. Thank you for the report.

**Comment by hvdmeer** [comment]
Is it working now @agerix ? (if so this issue can be closed)
