### ISSUE TITLE
http://feeds.joomla.org/ redirects to invalid https 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1576]
load http://feeds.joomla.org/JoomlaAnnouncements in a browser, and you get redirected to https://
<img width="837" alt="Screenshot 2021-01-10 at 17 57 46" src="https://user-images.githubusercontent.com/400092/104131283-5a82e300-536d-11eb-8737-913af0a6d4a6.png">

when called from the command line curl you don't get redirected.

This came to light when testing the feed in Joomla 4 which has links to the feed items back which when clicked give the above error

<img width="1328" alt="Screenshot 2021-01-10 at 17 58 33" src="https://user-images.githubusercontent.com/400092/104131307-78504800-536d-11eb-9eb9-8384cf64eb2e.png">

**Comment by conconnl** [comment]
This sounds like a CMS issue. 
feeds.joomla.org never existed on https and never will exist that way. 
Google doesn’t support your own domain on https for the feeds system. 

See also: https://github.com/joomla/joomla-websites/issues/1335

The correct URLs are here:
https://www.joomla.org/rss-news-feeds.html

**Comment by PhilETaylor** [comment]
Its not a CMS issue. This is a browser issue.

On Mac:
In Safari - redirects to https

<img width="740" alt="Screenshot 2021-01-10 at 18 39 58" src="https://user-images.githubusercontent.com/400092/104132124-404c0380-5373-11eb-923b-40751a457d5d.png">


In Brave: 

<img width="976" alt="Screenshot 2021-01-10 at 18 40 04" src="https://user-images.githubusercontent.com/400092/104132126-45a94e00-5373-11eb-981c-c293c3028621.png">


In Google chrome:

<img width="1021" alt="Screenshot 2021-01-10 at 18 40 19" src="https://user-images.githubusercontent.com/400092/104132132-4d68f280-5373-11eb-9c3a-c84e6ec6cec6.png">

In firefox:

<img width="1136" alt="Screenshot 2021-01-10 at 18 40 46" src="https://user-images.githubusercontent.com/400092/104132148-5fe32c00-5373-11eb-8821-6ec392e46097.png">

**Comment by PhilETaylor** [comment]
ah I see - I'll push back to CMS....
