### ISSUE TITLE
Navigation Bar Styles

### ISSUE THREAD

**Issue by somya339** [joomla/joomla-websites#1581]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

I have visited the site and found it's navigation bar too primitive .There is an urgent need to work on its styling as the first impression of a website is  it's navigation bar.

**Comment by conconnl** [comment]
Closing because the issue describe an opinion (which is great) but not an issue.
If you indeed have a specific issue, please describe it completely with for example links, examples, etc.
