### ISSUE TITLE
[josm] Link leads to a restricted google document

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1582]
Go here: https://www.opensourcematters.org/organisation/directors/board-member-roles.html#president

Click "Listed Below" in the second paragraph of the Officers section

The link is https://docs.google.com/document/d/1rD-C0rLFtoJd51P6qV1NFDCOn3hB5ZofUtopT-rtpTs/edit?ts=5e2ab915#heading=h.e0zqic32ol4p

which leads to

<img width="710" alt="Screenshot 2021-01-22 at 20 48 22" src="https://user-images.githubusercontent.com/400092/105544714-30c5a680-5cf3-11eb-82db-579b7e7b0da1.png">

**Comment by jeckodevelopment** [comment]
Thanks @PhilETaylor for notifying.
The link to the document shouldn't be there. The document linked was the draft of the Board roles descriptions that are listed in the page. Evident copy/paste mistake.

Link removed. Thanks
