### ISSUE TITLE
Wrong link in an article

### ISSUE THREAD

**Issue by ITPrism** [joomla/joomla-websites#1583]
The link that points to the information about Bootstrap 5 in [this article](https://developer.joomla.org/news/839-joomla-4-0-will-ship-with-bootstrap-5.html) is wrong.

The following link
https://getbootstrap.com/docs/5.0/getting-started/introduction/
points to
https://superdevresources.com/bootstrap5-vs-bootstrap4-whats-new/

**Comment by HLeithner** [comment]
Fixed it thanks
