### ISSUE TITLE
[jcomm] - Training Page

### ISSUE THREAD

**Issue by syeyakmal** [joomla/joomla-websites#1585]
![image](https://user-images.githubusercontent.com/60573449/107118394-bb91ce00-68bb-11eb-998a-2f41f910873f.png)

Hello! I was looking for the tutorial but was missing and state the above error. Can i know why and where i can learn Joomla completely.

thank you

**Comment by conconnl** [comment]
The page is partly back.
A playlist is added for the first bunch of videos, this page will be extended with more and maybe even from other organizations.
