### ISSUE TITLE
Training Videos are not working

### ISSUE THREAD

**Issue by TuxMaster22** [joomla/joomla-websites#1586]
Hi, 
hope you are doing great,

Like 1 week ago I went to the following link

https://community.joomla.org/joomla-training.html

and they were working well,

But today *06/02/2021* they are not available 

I got the following error message:

"Warning OSTeammate API found an error. Please, check the log"

I am eager to watch the traning,

hope this information is useful,

**Comment by pe7er** [comment]
Thank you for reporting this issue!

I just noticed that there's another report about this issue: https://github.com/joomla/joomla-websites/issues/1585
I am closing this one.
Thanks!
