### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Maggan22** [joomla/joomla-websites#1587]
I  can not use the site Joomla.org.
After logging in, I am redirected to my profile, I should accept the terms and the two ways autification. I'll do it. After sending everything is reset and I am asked to accept the terms and to set up the autification.
Otherwise I can't do anything on the site, I am always directed back to my profile.

I ask for help

Many Thanks

**Comment by conconnl** [comment]
The joomla.org website doesn't have public accounts and the registration option enabled, it's our organizational website to publish information, but it doesn't have features enabled which require user to login.
Are you sure you mean the joomla.org website?

**Comment by pe7er** [comment]
This issue has been reported by the user at Joomla forum:
It is about **joomla.com**: https://forum.joomla.org/viewtopic.php?f=805&t=984612
