### ISSUE TITLE
[JED] confusing message: "or a server is actively running on your desktop IP"

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1590]
The error message of the Security checks is confusing.
Could you please change that error message from

> Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.

to something like

> Security checks determined you may be using an IP masking service, a VPN **or a server is actively running on the public IP address of your internet router.*** To continue, you need a different Internet connection.

## Background info

From my office I tried to add a review at JED but I couldn't.

### JED error
![jed-error](https://user-images.githubusercontent.com/1217850/107635676-d40f3900-6c6b-11eb-8702-c44088e8745f.png)

Error: 
Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.
Message: 
Please login or create a new account to review this extension

However, I am not using a VPN and I am logged in (see the "Log out" in the menu).

### Local Server

I re-read the error "Security checks determined you may be using an IP masking service, a VPN **or a server is actively running on your desktop IP**". That message is a bit confusing. On my desktop I have a local web server for development. I stopped it, but as expected no use.

### Raspberry Pi
In my office I use a Raspberry Pi as mini web server. I've connected to my internet router and forward TCP traffic for port 80/443 to my Raspberry Pi. When I switched my Raspberry Pi off, I was able to access the JED review page without issues!

IMHO the error message is confusing. Could you please improve it?
Thanks!

**Comment by anibalsanchez** [comment]
Sure. I've applied a new message with the suggestion to clarify the point. This is the new message:

Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your internet router's public IP address. To continue, you need a different Internet connection.

Case solved. Let me know if there is anything else that can be improved.

**Comment by Llewellynvdm** [comment]
@pe7er I am really sorry that this issue with VPN's and stuff is still not resolved.

@anibalsanchez is working on removing this current "false positive approach" and he is going to be adding cleantalk and hcaptcha. This this should be resolved... please let me know if you have any further questions.

**Comment by pe7er** [comment]
Thanks for the improvement!

I was able to submit a JED review after I temporary switched off my Raspberry Pi that was connected to my router / IP address.
