### ISSUE TITLE
[jlaunch] Site is very slow

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1592]
I've installed ‎4.0.0-beta8-dev on JLaunch for preparing for our User Group Meeting (virtual) next month. 

But for the last few days the load of the website is very slow. When I visit the homepage it takes a minute to load. There are only three articles in it and two normal sized images.

After this it still takes about 6 seconds to visit the administrator page and also for items in the back-end.
I hoped it was temporarily but it has been three days in a row now. Can someone from CloudAccess look into this?

**Comment by Pawel-Panek** [comment]
@hvdmeer what's the site name? Or please open a ticket within our Cloud Control Panel. Please link this discussion in a ticket.

**Comment by hvdmeer** [comment]
It is https://hans.joomla.com @Pawel-Panek and I visit it from the Netherlands if that can make a difference

**Comment by chmst** [comment]
I have openened some sites in the last year for testing J4. We had the same issue - members from germany, poland and italy. Sometimes response time was ok but but we gave up after some time due to response times.

**Comment by Pawel-Panek** [comment]
@hvdmeer Please check now. The very first request can be slower but when the site is loaded it will be fine. If you still see the same problem please provide a screenshot of waterfall chart from the browser dev tools (F12, network tab).
I checked the backend too and it looks fine from my location (Poland).

**Comment by hvdmeer** [comment]
Thank you @Pawel-Panek . It now opens like it should.
Since I also see the remark from @chmst I hope this shouldn't just work for my site but all who are trying/testing/using joomla.com.
