### ISSUE TITLE
[jforum] 

### ISSUE THREAD

**Issue by ramarjun** [joomla/joomla-websites#1593]
Hi There,

Recently I have changed my email address. I have entered the wrong email id for joomla forum, whom i need to contact for change to previous email address?

My old registered email address - ramwebdeveloper@gmail.com username - ramarjun

**Comment by pe7er** [comment]
Hi ramarjun,
I've changed your e-mail back to your old registered email address.
You should have received a notification e-mail from Joomla forum.

Please let me know if you are able to login again.

**Comment by ramarjun** [comment]
Hi,

i tried with my old mail id still it's not working, can you please confirm my old email id which is ramwebdevloper@gmail.com ?

**Comment by pe7er** [comment]
@ramarjun It's ramwebdeveloper@gmail.com (note that it is de**vel**oper, not de**vl**oper).

**Comment by ramarjun** [comment]
Please note my mail id is **ramwebdevloper@gmail.com** not ramwebdeveloper@gmail.com

**Comment by pe7er** [comment]
Ok, I noticed that ramwebdevloper@gmail.com was indeed your previous mail for your profile.
I've changed your forum registered email address to that.
You should have received a notification e-mail from Joomla forum.

Please let me know if it's working correctly, thanks!

**Comment by conconnl** [comment]
Please reopen, if you still have problems.
As @pe7er mentioned, he made the change for you.
