### ISSUE TITLE
.joomla.org is blocked

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1595]
Only checked community.joomla.org and www.joomla.org - they both have the same error

Viewing the headers  (and checking the uptime status page) I can see that the site is up however the page will not load because of the following 

**This document was blocked from loading in an iframe with a sandbox attribute because this document specified a cross-origin opener policy.**

![image](https://user-images.githubusercontent.com/1296369/109644371-4ed1c280-7b4d-11eb-9845-a1198d87efa7.png)

![image](https://user-images.githubusercontent.com/1296369/109644423-5ee9a200-7b4d-11eb-9fe3-86cbc51dd18a.png)

**Comment by conconnl** [comment]
Can you share some more information?
I don’t completely follow what you are trying to do! CC @zero-24

**Comment by brianteeman** [comment]
I am saying that visiting those two sites for at least one hour this morning resulted in no access to the home pages with the error message as shown

**Comment by zero-24** [comment]
> This document was blocked from loading in an iframe with a sandbox attribute because this document specified a cross-origin opener policy.

Can you remember which kind of page you visited before that happend?
And what browser and operation system versions you are using? Does that happen on all browsers?

**Comment by brianteeman** [comment]
> > This document was blocked from loading in an iframe with a sandbox attribute because this document specified a cross-origin opener policy.
> 
> Can you remember which kind of page you visited before that happend?

No 

> And what browser and operation system versions you are using? Does that happen on all browsers?

Chrome Version 88.0.4324.190 (Official Build) (64-bit), Windows 10

Did not test on any other browser or OS at the time

I have no understanding of COOP so wouldnt have had a clue on what to look for. Just acting as a user and reporting that access to the site was blocked at that time with that error message.

**Comment by zero-24** [comment]
"at that time" so it is working now again for you too?

COOP should not have much todo with iframes. Its a noopener setting on a domain level.

**Comment by brianteeman** [comment]
> "at that time" so it is working now again for you too?
> 

yes

> COOP should not have much todo with iframes. Its a noopener setting on a domain level.

Maybe or maybe not I have no idea. I can only go by the error message
