### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by EvanCalvert14** [joomla/joomla-websites#1597]
I can't log into the community with either of my email accounts.
Firstly, my work email account evan.calvert@ntegra.co.uk with the username evan.calvert14 it tells me that I am not allowed that username but it let me create it but will not let me in strangly?
Secondly, when i try to register using my email calvert.evan14@gmail.com it doesn't work either it say that email is already in use but it isn't.

Please help :(

Many thanks,

Evan

**Comment by pe7er** [comment]
Hi Evan,

Both addresses in use in Joomla Forum but are inactive:
username "calvertevan14" with evan.calvert@ntegra.co.uk 
username "0wlb0y" with calvert.evan14@gmail.com

Did you get an email notification with activation link? Please also check your spam box.
Did you activate your account?

I've just done a "force reactivation" for your account: calvertevan14
Could you please check your email and try again?
