### ISSUE TITLE
[jlaunch] Placeholder text overlaps with entered text

### ISSUE THREAD

**Issue by Ankur-Khandelwal** [joomla/joomla-websites#1598]
On the landing page of the website https://launch.joomla.org/, there is a text input box asking to enter the website name. This box has a placeholder text - "Enter website name". When we enter some text in there, the placeholder text initially goes up as long as the cursor is in that box, but as soon as we move the cursor out of that box, the placeholder text gets overlapped with the entered text.

I have attached a few pics below to make it clear.

![joomla_issue1](https://user-images.githubusercontent.com/55295915/110686390-640db780-8205-11eb-9956-aab22a4f23a9.png)

![joomla_issue2](https://user-images.githubusercontent.com/55295915/110686403-6839d500-8205-11eb-80c2-351a3f51c3aa.png)

![joomla_issue3](https://user-images.githubusercontent.com/55295915/110686416-6a9c2f00-8205-11eb-95a9-db4e61ecf5d0.png)

**Comment by Pawel-Panek** [comment]
Hello @Ankur-Khandelwal,

in what browser (name and version) you see this problem?

**Comment by Ankur-Khandelwal** [comment]
Hi @Pawel-Panek. Thank You for replying. 

I am facing the issue in two browsers.

- Google Chrome (Version 88.0.4324.150 (Official Build) (64-bit))
- Mozilla Firefox (Version 85.0.1 (64-bit))

I am using the Ubuntu operating system - Version 20.10

**Comment by Megh05** [comment]
@Ankur-Khandelwal I would like to work on it.

**Comment by conconnl** [comment]
This is a system provided by an external supplier and they already responded and are working it.

**Comment by Megh05** [comment]
> This is a system provided by an external supplier and they already responded and are working on it.

I've tested this issue in browsers like Safari, Chrome & Firefox and it seems like when we put space between two words in the text box only then the placeholder text is overlapping; if we don't add space between letters then the issue never occurs and generally, there should not be any space in the website name.

**Comment by Ankur-Khandelwal** [comment]
> > This is a system provided by an external supplier and they already responded and are working on it.
> 
> I've tested this issue in browsers like Safari, Chrome & Firefox and it seems like when we put space between two words in the text box only then the placeholder text is overlapping; if we don't add space between letters then the issue never occurs and generally, there should not be any space in the website name.

Yes, you are right. And one more point I noticed is that, even if there is no space, if you capitalize any letter in the word, then also the overlapping takes place.

**Comment by conconnl** [comment]
@Pawel-Panek 
Can you give an update and close the issue when solved?

**Comment by igorkaczor** [comment]
> @Pawel-Panek
> Can you give an update and close the issue when solved?

It's fixed now. Thank you for reporting it @Ankur-Khandelwal

**Comment by Ankur-Khandelwal** [comment]
Yes, It's fixed! @Pawel-Panek . So should we close this issue?

**Comment by conconnl** [comment]
Thank you all
