### ISSUE TITLE
[jshow] Mutliple H1 tags

### ISSUE THREAD

**Issue by arunsasi** [joomla/joomla-websites#160]
Mutliple H1 tags in http://joomla-showcase.octopoos-dev.com/

![multiple_h1_tags](https://cloud.githubusercontent.com/assets/270789/11013772/95f27938-8540-11e5-998f-0cd9f37cd548.png)

**Comment by mbabker** [comment]
Another task that wasn't touched from the last testing round.  Are we trying to launch a site with numerous known issues for the sake of launching it?

**Comment by sebastienlapoux** [comment]
Fixed. Thanks!

**Comment by mikeveeckmans** [comment]
checked and solved
