### ISSUE TITLE
[issues] Filter labels not alphabetical + not same as github

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1601]
Could someone please **synchronize** the **Filter labels** at https://issues.joomla.org/ with the ones from github?
Those are out of sync ("Release Blockers" is not avaible at the Joomla Issues site)
And please **change the order** of the items to list the labels **alphabetically**?
Thanks!

# Background

At Joomla forum someone wanted to get info about the Joomla 4 Release Blockers: https://forum.joomla.org/viewtopic.php?f=803&t=985486
I use github myself and you can filter the issues on the "Label" and select "Release Blockers"
However, it appeared that Joomla Issues website https://issues.joomla.org/ does not have "Release Blockers" as option in its filter dropdown.

## issues.joomla.org
https://issues.joomla.org/

![issues-joomla-org](https://user-images.githubusercontent.com/1217850/111775296-ddb23f00-88b0-11eb-811d-8b56a2ff1056.png)

## issues at github
https://github.com/joomla/joomla-cms/issues

![github-joomla-cms](https://user-images.githubusercontent.com/1217850/111775293-dd19a880-88b0-11eb-9dae-5a83489f0086.png)

**Comment by brianteeman** [comment]
probably better to post this https://github.com/joomla/jissues

**Comment by pe7er** [comment]
Ok, thanks. I've posted it there: https://github.com/joomla/jissues/issues/1116
