### ISSUE TITLE
Folder_icon [jdocs] 

### ISSUE THREAD

**Issue by vartikaSaxena** [joomla/joomla-websites#1602]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by vartikaSaxena** [comment]
On-webpage, having below link,
https://docs.joomla.org/J3.x:Installing_Joomla 
The icon in the section "Your Server's root Folder" is a "Light bulb" icon which should be a "Folder" icon.

![image](https://user-images.githubusercontent.com/80751519/111880521-10a02400-89d2-11eb-9b8b-4b10a3e62677.png)
Whereas it should be
![image](https://user-images.githubusercontent.com/80751519/111880619-83a99a80-89d2-11eb-9391-989bcea9d316.png)

The folder icon will look more _relatable_ to the content.

**Comment by vartikaSaxena** [comment]
I want to work on this issue. Please, assign it to me.

**Comment by conconnl** [comment]
Thanks for creating this request. 
The Bulb image within the blue bar means informational, like you also have in Joomla. 

It’s not related to the text (content) at all.
If the image is changed it means it changes in the whole system on every page were this is used. 
example: https://docs.joomla.org/Portal:Developers

**Comment by vartikaSaxena** [comment]
Okay...thanks for clearing my doubt :-)
