### ISSUE TITLE
[idp] Reconsider hCaptcha?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1603]
Reconsider hCaptcha?

<img width="618" alt="Screenshot 2021-03-23 at 12 21 12" src="https://user-images.githubusercontent.com/400092/112145517-617e6b00-8bd2-11eb-8fde-f5fea81da635.png">

**Comment by brianteeman** [comment]
For reference this is the way that it works https://www.hcaptcha.com/accessibility

At first glance it definitely looks to be an implementation that we should avoid

**Comment by AlisonAMG** [comment]
If J4 is coming out of the gate saying we are accessible then have this boat anchor hanging around our necks it isn't a good look.

**Comment by jeckodevelopment** [comment]
I would respond only for what is related to joomla.org 
Some months ago we made a partnership agreement with hCaptcha, but we don't make money and we don't pay.

We'll investigate the issue further directly with the team at hCaptcha in relation with their accessibility features. 

For J4 the best thing is to discuss in the public tracker of the CMS

**Comment by brianteeman** [comment]
@AlisonAMG hcaptcha is NOT in joomla4

**Comment by PhilETaylor** [comment]
> @AlisonAMG hcaptcha is NOT in joomla4

It was rejected here:

https://github.com/joomla/joomla-cms/pull/28798

**Comment by conconnl** [comment]
FYI
https://medium.com/@hCaptcha/accessibility-at-hcaptcha-current-and-future-plans-e99dbf2f3996

**Comment by conconnl** [comment]
The issue is about the website, for now hcaptcha will not be removed from the websites.
