### ISSUE TITLE
[joomla.org] remember me checkbox

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1609]
![image](https://user-images.githubusercontent.com/1296369/114628650-175b4780-9caf-11eb-95a7-52a0adde0f24.png)

This is caused by 

```
.form-horizontal input, .form-horizontal textarea {
    width: 75%;
}
```

**Comment by brianteeman** [comment]
It is fine on the community site so I'm _guessing_ the css is different on that site

![image](https://user-images.githubusercontent.com/1296369/114628978-b2542180-9caf-11eb-9a1f-ba3cc2ba2632.png)

**Comment by conconnl** [comment]
Thanks for sharing this @brianteeman 
The CSS is indeed different, I think it has been done for other forms with out targeting the specific page.
I just added a rule to just fix the checkbox and not impact other hidden things.
