### ISSUE TITLE
[jshow]  Contrast accessibility issue for <p>

### ISSUE THREAD

**Issue by vinod303** [joomla/joomla-websites#161]
The following page has the problem with color contrast.
https://joomla-showcase.octopoos-dev.com/
Suggested (passed by http://webaim.org/resources/contrastchecker/)  is  #5d6d6d.

**Comment by oliviernolbert** [comment]
Constrast enhanced, thanks.

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
