### ISSUE TITLE
[joomla.org] News Feeds

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1612]
I was checking to see if we still use feedburner as they are making some [changes ](https://support.google.com/feedburner/answer/10483501 )and wanted to give a heads up that they will be removing the ability to receive the news in your email and I spotted the terms of service.

> You are welcome to incorporate joomla.org and related feeds on your Web site as long as the use complies with the Terms of Service as well as Open Source Matters trademark, copyright, and licensing policies.
> 
> The contents of the Joomla.org and its sub domain feeds are copyrighted in the United States and internationally by Open Source Matters and the individual contributors. You do not have permission to store this work for use on your Web site. If you use a Joomla.org feed on your Web site, you:
> 
> Must not modify or delete any of the RSS feed content.
> Must not redistribute the feed.
> Must include any links in the feed.
> Must include the description, copyright notices or other information included as part of the feed that is currently included in the feed or that may be added in the future.

Has anyone ever read them? I assume not and that they were written (presumably at great expense) by a lawyer who doesn't understand the internet. 
The first and second sentences contradict each other.
The second point prevents a newsfeed aggregator using the feed
The fourth point is a problem as the joomla newsfeed has specific options to disable the feed description

**Comment by conconnl** [comment]
@brianteeman thanks for sharing
@hdouglassmith please take a look at it within the L&F department, it seems to require changes.

**Comment by conconnl** [comment]
As the mail feature of feedburner will disappear, as share by @brianteeman 
The following feeds probably need some communication action, the amount of mail subscribers is mentioned by the Feedburner tool itself.

@Llewellynvdm 
Feed: https://feeds.feedburner.com/joomlaextensions has 270 
Feed: https://feeds.feedburner.com/recentlyresolvedvulnerableextensions has 376
Feed: https://feeds.feedburner.com/joomlasecurityvulnerableextensions has 1660

@Hutchy68 
Feed: https://feeds.feedburner.com/joomladocumentation has 14

@HLeithner 
Feed: https://feeds.feedburner.com/joomlasecuritynews has 374825
Feed: https://feeds.feedburner.com/joomlaannouncements has 453

**Comment by brianteeman** [comment]
Would be a shame to miss the deadline for downloading the emails

**Comment by brianteeman** [comment]
Just wondering if there is any update about the legal terms which are clearly wrong

**Comment by hdouglassmith** [comment]
Perhaps you might like to make some suggestions as to what you think this should be and I will get it checked out. Many thanks. Hugh

**Comment by brianteeman** [comment]
I already did. It's blatantly obvious

**Comment by hdouglassmith** [comment]
Clearly I speak a different language, it isn't obvious to me.

**Comment by brianteeman** [comment]
Seriously. You don't understand so you brush it under the carpet and close it. No wonder osm is messed up.

**Comment by brianteeman** [comment]
The first and second sentences contradict each other.

The second point prevents a newsfeed aggregator using the feed

The fourth point is a problem as the joomla newsfeed has specific options to disable the feed description

**Comment by hdouglassmith** [comment]
Please read CAREFULLY what I asked you above and provide an alternative text which will then be considered.

**Comment by brianteeman** [comment]
I am not a lawyer - why would you ask me to write a legal policy

**Comment by brianteeman** [comment]
This should not be closed

**Comment by brianteeman** [comment]
I can consult lawyers who understand the internet who can rewrite it for you but obviously they would expect to pay their professional fees.

**Comment by hdouglassmith** [comment]
And there you have it, OSM too would need to consult with lawyers which would incur unbudgeted cost. That is something which I do not see as a priority at the current time, I am therefore thank you for pointing this out, but closing the issue because there is no budget to resolve this at the present time.

**Comment by brianteeman** [comment]
So you think its acceptable to have legal text on the joomla web sites that is completely wrong and inaccurate. I have already pointed out the flaws in the text. 

Better to have no text than this

**Comment by HLeithner** [comment]
Maybe I match your "first and second" sentence wrong so I try to match them here:

You only reference this points right?

> Must not modify or delete any of the RSS feed content.
> Must not redistribute the feed.
> Must include any links in the feed.
> Must include the description, copyright notices or other information included as part of the feed that is currently included in the feed or that may be added in the future.

Your sentense:
> The first and second sentences contradict each other.

Would reference 
> Must not modify or delete any of the RSS feed content.
> Must not redistribute the feed.

right? if so then they not contradict each other, I would interpret it like "you are allowed show the feed on your website but have to show everything unmodified" for first line and the second line means you are not allowed to copy-paste / mirror the rss feed one on one. 

> The second point prevents a newsfeed aggregator using the feed

That reference this line right?

> Must not redistribute the feed.

I see no problem with this, if you are a newsfeed aggregator you have to ask for permission but per default you are not allowed to mirror the feed.

> The fourth point is a problem as the joomla newsfeed has specific options to disable the feed description

here we talk about

> Must include the description, copyright notices or other information included as part of the feed that is currently included in the feed or that may be added in the future.

If a part doesn't exists you don't need to show it, not sure were the problem is.

I'm with you that some of the points are wired and maybe not got for some use cases but I see no legal problem but as you I'm not a lawyer so it's just my opinion.

**Comment by brianteeman** [comment]
Sorry, it was the first sentence and third sentence which say 

> You are welcome to incorporate joomla.org and related feeds on your Web site

> You do not have permission to store this work for use on your Web site.

**Comment by mfleeson** [comment]
Are not most feeds taken and shown on? As the feed updates so does the displayed data.
 So the two clauses:
    You are welcome to incorporate joomla.org and related feeds on your Web site
    You do not have permission to store this work for use on your Web site. 

The first says you can display the feeds on your website, and the second says you cannot store the feed data. You can only display the live feed.

At least that's the how I would intrepret the statements.

**Comment by brianteeman** [comment]
If there is no cache anywhere

**Comment by HLeithner** [comment]
> If there is no cache anywhere

I know several years ago there was a legal discussion if "caching" is "saving" sadly I can't remember the final outcome of this. (I think it was about the browser cache).

So caching may or may not mean saving ;-) Anyway working with the rss feed in "realtime" and showing it on your website is allowed.

**Comment by hdouglassmith** [comment]
Given Harald's very useful explanation (which makes perfect sense to me), I do not believe this is an issue and no changes are necessary
