### ISSUE TITLE
[joomla.org] Joomla downloads page is not displaying properly

### ISSUE THREAD

**Issue by durian808** [joomla/joomla-websites#1616]
The downloads page at https://downloads.joomla.org/us/ does not display properly.

**Comment by durian808** [comment]
it's happening to me on FireFox and Chrome on the Mac.

Try reloading your browser page.

Here's the screenshot... this is all I see on the home page (unless I scroll down).

![screenshot1](https://user-images.githubusercontent.com/15332828/115375948-f8a2f800-a169-11eb-932a-ea398595b7c6.png)

**Comment by pe7er** [comment]
Thank you for your follow-up with screenshot!

It looks like your browser is not loading the CSS files correctly:
- https://downloadscdn.joomla.org/media/mod_languages/css/template.css?1618199610
- https://downloadscdn.joomla.org/templates/joomla/css/custom.css?047529039839ba69e120077575d92c9c&1527594363
- https://cdn.joomla.org/template/css/template_3.0.0.min.css

From which country are you trying to visit the Joomla Download page?

**Comment by durian808** [comment]
I'm in the U.S.  It's suddenly working in both FireFox and Chrome now.  Did you change anything?  I didn't.

**Comment by pe7er** [comment]
Thanks. No, I haven't changed anything. 
I guess that it was a temporary DNS issue so that your browsers could not load the CSS files. 

Good to hear that it's working well again for you!
I'm closing this issue.

**Comment by aboarken** [comment]
@pe7er I have faced the same issue from 1 month ago while visiting community.joomla.org website ... I have also reported but my Joomla friends were able to load the site without any issues. Maybe there is an issue with Joomla CDNs? Have a great day.

**Comment by conconnl** [comment]
@aboarken do you still have this issue?
If so, can you check your browser console and see what happens related to the CDN?
