### ISSUE TITLE
[jshow] New site contrast border of inputboxes

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#162]
I don't know if this is an item but de borders of the input boxes don't have enough contrast.
example: http://joomla-showcase.octopoos-dev.com/browse-sites/featured-only.html
Search box 
![search](https://cloud.githubusercontent.com/assets/4639364/11013792/cda0862e-851b-11e5-81c8-d2cdbbd51009.png)

**Comment by oliviernolbert** [comment]
Fixed, Thank you.

![capture d ecran 2016-08-29 a 12 48 03](https://cloud.githubusercontent.com/assets/6637889/18049187/f1971fc0-6de6-11e6-869c-799559702173.png)

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
