### ISSUE TITLE
[jcomm] Not able to donate

### ISSUE THREAD

**Issue by saber-zz** [joomla/joomla-websites#1622]
Hi, the donation form does not work anymore. I always get the error "Invalid verification code entered". 
Regards
Simone (info@webcan.ch)
![Bildschirmfoto 2021-05-02 um 14 55 46](https://user-images.githubusercontent.com/329523/116813906-8f9e8580-ab56-11eb-9b50-c33d3c48d081.png)

**Comment by conconnl** [comment]
See: https://github.com/joomla/joomla-websites/issues/1570

The system needs a full replacement and the right department is working on it. CC @hdouglassmith
