### ISSUE TITLE
Weird error messages on the JED[jcomm] 

### ISSUE THREAD

**Issue by formfranska** [joomla/joomla-websites#1623]
When trying to post a review I'm getting weird messages on the JED. This hasn't happened before when I'm logged in. I'm attatching screenshot here.
<img width="1495" alt="Screenshot 2021-05-05 at 19 14 29" src="https://user-images.githubusercontent.com/3016723/117183452-dcdd5a00-add7-11eb-937b-7c31d4187d6d.png">

**Comment by anibalsanchez** [comment]
Hi,

JED has its issues tracker here: https://github.com/joomla/jed-issues

In particular, the issue related to review security checks has been already reported and the work is ongoing. Please, follow the issue here: https://github.com/joomla/jed-issues/issues/85
