### ISSUE TITLE
[jcm] /all-issues: Image overlap right column

### ISSUE THREAD

**Issue by sandramay0905** [joomla/joomla-websites#1624]
As title say on https://magazine.joomla.org/all-issues:

> ![Screen Shot 2021-05-12 at 19 39 17](https://user-images.githubusercontent.com/78906980/118020158-107d2e80-b35a-11eb-9a57-ce595ca1abcb.png)

**Comment by particthistle** [comment]
@sandramay0905 thanks for logging the issue.

We just performed a major layout adjustment, and there's a few views that look to have classes that are not quite right. PR following shortly.

@sandramay0905 please also take a moment to [get in touch](https://kps.fyi/pj) as we've been noticing your volume of contributions in the past few months but have not been able to find a way to get in touch to invite you into some other conversations on Joomla Bugs & Fun @ Home as well as other areas of the project.

**Comment by sandramay0905** [comment]
Thanks for the upcoming pull request. You can reach me at gmail com using my github-username :-)

**Comment by particthistle** [comment]
Closing as PR in magazine repo addresses the issue.
