### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by CharlesWJYee** [joomla/joomla-websites#1627]
Hello, I just registered and it says my user name (CZee) is inactive. Asks me to contact site admin. I have no idea why this is happening. Would like to be able to log in. Thanks

**Comment by pe7er** [comment]
Could you please check your email of the email address that you used during registration?
You should have received an email notification asking you to confirm your email address.
After that, your forum account will be active

**Comment by CharlesWJYee** [comment]
It’s the same as this email. Sorry never received a notification...

**Comment by pe7er** [comment]
I've chosen "force reactivation" so that you should receive a new email notification with activation link.

**Comment by CharlesWJYee** [comment]
Thank you very much!

**Comment by pe7er** [comment]
You're welcome!

I see that you have activated your account so I'm closing this issue.
