### ISSUE TITLE
[jcomm] create an account

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1629]
![image](https://user-images.githubusercontent.com/1296369/120164584-a4704680-c1f2-11eb-8513-e0fd745ba1fb.png)

This is caused because the css is calling two different icon libraries (icomoon and glyphicons-halflings)

**Comment by conconnl** [comment]
@brianteeman 
Thank you very much.
I'm probably blind, can't find it on the community website.
<img width="244" alt="image" src="https://user-images.githubusercontent.com/11913918/120232774-83d8d880-c254-11eb-86a3-d6f54d39b001.png">

Where did you saw this and in which browser?

**Comment by brianteeman** [comment]
https://community.joomla.org/service-providers-directory.html

Chrome

**Comment by conconnl** [comment]
Thanks again.
RSDirectory was loading additional files.
This is gone now.

**Comment by brianteeman** [comment]
looks good
