### ISSUE TITLE
[jshow] annoying issue in registration form

### ISSUE THREAD

**Issue by carlostester** [joomla/joomla-websites#163]
when tring to register as a user and for any reason i got an error in the filled form, the return page erease all the filds and its not a good for user experience

**Comment by oliviernolbert** [comment]
Can't be reproduced. Still the case on your side? any specific action needed to reproduce?

**Comment by sebastienlapoux** [comment]
Thanks to close this issue ! Or to provide more info.

**Comment by Sandra97** [comment]
Can't reproduce neither.
As no information has been provided to try to reproduce the error, I'm closing this issue.
Re-open if needed.
