### ISSUE TITLE
[jdocs] [osm] Sites blocked 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1631]
When you click on the help button top right of most pages in Joomla 4 then the docs site opens in a popup new browser window. BUT when you click on the help menu item bottom left then the help pages are opened in an iframe.

This issue is about the iframe use not the popup.

If you check the links on the page you will see they are all being _proxied_ through help.joomla.org however the links in the footer are not 

![image](https://user-images.githubusercontent.com/1296369/120560914-8b86b180-c3fb-11eb-8e52-e69ff8d1791d.png)

The first two (highlighted above) are direct to the docs site - but you cannot open the docs site links
![image](https://user-images.githubusercontent.com/1296369/120561019-ba048c80-c3fb-11eb-97f0-c39af834cc17.png)

You also cannot open the link to the osm site
![image](https://user-images.githubusercontent.com/1296369/120561093-d86a8800-c3fb-11eb-8869-19077b1ba8a9.png)

I believe this is due to the iframe blocking code on those two sites but it may also be something to do with how that block is generated. 

I don't know if this is a CMS issue or an Operations issue so I am crossposting it - please close it if this is the wrong place,

**Comment by brianteeman** [comment]
CMS post https://github.com/joomla/joomla-cms/issues/34367

**Comment by zero-24** [comment]
Will take a look once i'm back home. The link to osm is the license on? And thats opend in a iframe too?

**Comment by brianteeman** [comment]
![before](https://user-images.githubusercontent.com/1296369/120832147-3c09c800-c558-11eb-80aa-210afc3fae00.gif)

**Comment by brianteeman** [comment]
Still confirmed the exact same links as in the original report. Chrome, windows recording above. firefox error below

![image](https://user-images.githubusercontent.com/1296369/120832361-7d01dc80-c558-11eb-826f-348daba4360a.png)

**Comment by zero-24** [comment]
Ah thats a different place than i was looking at, confirmed will take a look.

**Comment by brianteeman** [comment]
its the place that I reported in the first post ;)

**Comment by zero-24** [comment]
PR done here: https://github.com/joomla/help.joomla.org/pull/31 no need to load the complete internet inside your joomla as iframe ;) Going to close here as there is a PR to fix the issue on help.joomla.org
