### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by mikewestcoast** [joomla/joomla-websites#1633]
Please see your Favicon instructions here online: https://docs.joomla.org/Changing_the_site_favicon

I've been a webmaster for over 20 years. Your Step 3 (The file you created in this way will have the extension .ico. Copy the file to the /joomla/templates/<your template> directory and name it favicon.ico.) makes no sense. 
* I started web design learning HTML and started with DreamWeaver. 
* I now use three different Content Management System. 3 CMS systems. THREE!
* Since each Content Management System is different in how you access the HTML code for templates, when anyone makes instructions they SHOULD CONTAIN ALL STEPS IN HOW TO PERFORM A SPECIFIC TASK. 
* AND SINCE I WORK ALONE IN MY APARTMENT, AS MANY WEBMASTERS DO, YOU NEED TO REALIZE THAT I AM NOT WORKING WITH A TEAM OF WEBMASTERS. IF I CAN'T FIGURE OUT HOW TO DO SOMETHING, I HAVE TO RELY ON PEOPLE EXPLAINING HOW TO PERFORM A TASK INSIDE A CONTENT MANAGEMENT SYSTEM.
* WHEN THE PERSON WRITING A "HOW-TO" ARTICLE ASSUMES EVERY WEBMASTER KNOWS ALL THE SECRET STEPS INVOVLED IN USING THEIR CMS SYSTEM, THEN I HAVE TO USE MY OWN UNPAID LABOR HOURS TO TRY TO THESE PEOPLE WRITING "HOW-TO" ARTICLES, TO WRITE THEM CORRECTLY SO THAT ANYONE CAN UNDERSTAND THE INSTRUCTIONS. 

YOUR INSTRUCTIONS - Step 3: Copy the file to the /joomla/templates/<your template> directory and name it favicon.ico., MAKES NO SENSE. 
* MAKES NO SENSE.
* MAKES NO SENSE. 
* Do you understand that your Step 3 instructions MAKES NO SENSE? 

When I am looking for "How To" articles on how to use a Content Management System, I need something like this: 

Step 1: Create a 16X16 pixel image. (Etc., etc.)  (NOTE: You use an UPPERCASE X when typing an image size, like this:16X16, NOT 16x16.)
Step 2: Convert to the 16X16 image file to an .ico file extension using free online sites such as: (Etc., etc., etc.)
Step 3: Then in the Joomla! upload your favicon.ico image to the images file folder.
* Click the upper-left hand icon to get to the main Control Panel.
* Look at the left navigation column and scroll down until you see the Media link. (Where you store all your images for your website.)
* Upload your favicon.ico file to the main Images file folder
Step 4: Then click the upper-left Icon to go back to the main Control Panel.
* Look at the left navigation column and scroll down until you see the Templates link. 
* and then continue with your explanation on how to do this. 

Now... I CANNOT FIGURE OUT HOW TO:

1) UPLOAD MY favicon.ico TO THE CORRECT IMAGE FILE FOLDER.
2) UPLOAD THE favicon.ico HTML CODE, TO THE MAIN TEMPLATE  BECAUSE YOU DON'T EXPLAIN HOW TO GET INTO THE MAIN TEMPLATE SO I CAN ADD HTML CODE. 
* DO YOU UNDERSTAND WHY YOUR DIRECTIONS ARE USELESS TO ME? 

WILL SOMEONE PLEASE WRITE THE NECESSARY STEPS (ON YOUR WEB PAGE HERE: https://docs.joomla.org/Changing_the_site_favicon) SO THAT I CAN ADD A favicon.ico FILE TO MY WEBSITE, AND SO THAT I CAN UPLOAD THE CORRECT HTML CODE TO THE MAIN TEMPLATE, PLEASE?

**Comment by hvdmeer** [comment]
STEP THREE MAKES TOTAL SENSE TO ME AND ALSO JUST WORKS FINE
> Copy the file to the /joomla/templates/<your template> directory and name it favicon.ico.

ALSO I HAVE NEVER SEEN ANY DEMANDS FOR USING UPPERCASE IN DIMENSIONS.

**Comment by mikewestcoast** [comment]
I am using my own unpaid labor hours to ask a question. If you had any credibility, you would have posted the EXACT steps to upload a Favicon. If you REFUSE to help people who are asking for help, then don't post anything. Shame on you for your useless comment. Shame on you.

**Comment by hvdmeer** [comment]
I'm sorry Mike but I closing this issue. You're the one with a bad attitude here "asking" a big mouth question. I guess shouting at other volunteers helps? I expect with 20 years of expierence as a webmaster `Copy the file to the /joomla/templates/ directory and name it favicon.ico.` should be easy.

**Comment by hvdmeer** [comment]
I would like to add to this closed issue that the user mikewestcoast (his handle known by me) used my personal twitter profile to send harassment private messages of his point of view.

**Comment by TLWebdesign** [comment]
Wow. Can we ban people like this?
