### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jeffv03** [joomla/joomla-websites#1634]
Hello ^^)
I can't register or the joomla docs site as I can't get that capcha to work!

by ex:

To pass captcha, please enter the...
 7th
sixt (was an image)
fourth (was an image)
...characters in forwards order from the sequence f209a4b59f: 

with that example the result should 4 and 9 but 

all I get is a 'CAPTCHA erroné ou manquant.' error....

what I'm missing there ?

thanks for the answer (never stumble upon such capcha before)
Jeff

**Comment by hvdmeer** [comment]
I think the numbers were shown as an image is to make it harder for the bots to register accounts. So in this case you probably would've succeeded with: b49

**Comment by jeffv03** [comment]
thank you ^^)
this time it worked
