### ISSUE TITLE
[jdocs] Corrupted page https://docs.joomla.org/JDOC:How_to_Contribute_to_Joomla!_Documentation

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-websites#1635]
The page has been last changed on 25 June - it contains text in Chinese, as shown in the attached screenshot.

![corrupted-page](https://user-images.githubusercontent.com/1175079/123498960-6e788380-d633-11eb-8615-fe73a3cce554.jpg)

**Comment by hvdmeer** [comment]
The page has been reverted to the previous version, so this issue can be closed
