### ISSUE TITLE
[downloads.joomla.org] API return of CMS releases are broken.

### ISSUE THREAD

**Issue by Llewellynvdm** [joomla/joomla-websites#1641]
Wanted to get the Joomla versions today from https://downloads.joomla.org/api/v1/releases/cms and the result was a mix of cms and translation values.

After speaking with @wilsonge we realized that we should fix the filter of the values at:
https://github.com/joomla/downloads.joomla.org/blob/master/libraries/api/controller/releases/cms.php#L35

This is just a reminder issue, to double back to this, should it not get resolved.

**Comment by Llewellynvdm** [comment]
Okay @wilsonge these are some of the filters I tried,

```php
->category_id([1,2,3])
```
this returns just the CMS until version 3 but is a painful dependency issues for maintainability.... then I also tried:
```php
->visualgroup_id(1)
```
That seems more successful but some language stuff was still in it... but this is on the staging server so it could be wrong data placement.

I can't see any other simple filter option.

**Comment by Llewellynvdm** [comment]
I left it in that last state... the `->visualgroup_id(1)` so you can see the result.

**Comment by zero-24** [comment]
PR has been created here: https://github.com/joomla/downloads.joomla.org/pull/272 I think we can close here than and deploy the suggested fix?
