### ISSUE TITLE
joomla.org/4 contributors button

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1645]
<img width="638" alt="Screenshot 2021-08-14 at 22 46 03" src="https://user-images.githubusercontent.com/400092/129460843-68672d41-1ee3-4cbe-964d-bd579a6126fc.png">

Clicking the button does nothing as the href is only #   https://www.joomla.org/4/#

```html
<a class="btn btn-light" href="#">Joomla 4 contributors.</a>
```

**Comment by conconnl** [comment]
Correct, the site is not finished. 
indexing not enabled yet. 
All should be finish at launch.

**Comment by PhilETaylor** [comment]
> indexing not enabled yet.

Its live on the public internet! if you dont want people visiting it then it should not be a public facing website until it is finished !!
