### ISSUE TITLE
[jhelp] 404 - RuntimeException when opening Help Screens in 3.10

### ISSUE THREAD

**Issue by LordUber** [joomla/joomla-websites#1649]
404 - RuntimeException

Error fetching page from MediaWiki API: The page you specified doesn't exist

-Getting this message whenever I try to read the help for my joomla site (3.10)

**Comment by zero-24** [comment]
Thanks i have just forwarded this to the docs team to check!

**Comment by LordUber** [comment]
ok ty

**Comment by wilsonge** [comment]
This has been fixed. Sorry for the delay!
