### ISSUE TITLE
[jdown] language packs 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1651]
Look at the webpage and you can not see where to download a language pack from

![image](https://user-images.githubusercontent.com/1296369/130484195-483823ee-5b2e-4e2d-9cdc-6c65699e2454.png)

**Comment by conconnl** [comment]
Thanks for your comment.

Any improvement can be suggested, created, provided in the repository for the component used. 
As you did before, which was very helpful. 
See: https://github.com/joomla-extensions/pkg_languagepack

Please provide a code improvement there if needed, so this can be integrated. 
Thank you.

**Comment by brianteeman** [comment]
thanks - i didnt realise it was a special component

**Comment by brianteeman** [comment]
https://github.com/joomla-extensions/pkg_languagepack/pull/77
