### ISSUE TITLE
[jdown] Joomla 3

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1652]
Do we really want to completely remove J3 from the downloads page?

![image](https://user-images.githubusercontent.com/1296369/130484354-63b7c17b-f246-46d4-a113-0a70ceebb763.png)

**Comment by conconnl** [comment]
@softforge could you please reply on this?

**Comment by softforge** [comment]
I don't see a reason to push J3, downloads have almost doubled since J4. If we have a J3 download we are encouraging people to download something that we have already said is EOL.  People have less than 2 years of support. J4 is also better so why have both?

**Comment by Llewellynvdm** [comment]
We must have both since 90% of all Joomla production websites are still on J3 we must only make it hard to find at EOL not two year head of time.

**Comment by brianteeman** [comment]
No longer relevant
