### ISSUE TITLE
[jshow] sites being rejected

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1659]
Today a site of mine that has been listed on the showcase for 5+years was removed because of a misunderstanding of the trademark rules of OSM. The site has been actively promoted on joomla.org for many years by many joomla departments.

I dont really care as the trademark police continually chose to make up their own rules regarding trademarks that are completely invalid, both in law and in policy. But the language used in the email is rude and offensive, unsigned and cannot be replied to.

I should add that according to the showcase faq 

>  Owner will be informed of the reason and allowed 14 days to either rectify the problem or request removal from the showcase. We reserve the right to permanently remove any listing that is still in conflict with the rules as determined in our sole discretion.
If the editors attempt to contact the owners of a submission or listed firm and no reply is received in 14 days, the resource will be permanently removed from the Joomla Site Showcase.

The email makes no mention of that nor does it offer any means to reply. hence the public post

**Comment by conconnl** [comment]
@hdouglassmith and @jeckodevelopment please look at this!

**Comment by hdouglassmith** [comment]
Can someone point me to the site concerned so I can check it out

**Comment by sebastienlapoux** [comment]
https://www.spreadthejoomlalove.com/

**Comment by brianteeman** [comment]
it is now 24 days since this simple issue was raised

**Comment by Llewellynvdm** [comment]
Who holds the registration of this domain? This is what should be done:
https://tm.joomla.org/registration-of-domain-names.html

Prove of this "Registrant Data" must be submitted to the [TM team](https://tm.joomla.org/tickets.html), and then they will add it to the [approved domain list](https://tm.joomla.org/approved-domains.html).

That is what I had to do... not sure if this issues is any different, because you said:
>...**a site of mine** that has been...

**Comment by brianteeman** [comment]
Thank you for your opinion

**Comment by jeckodevelopment** [comment]
The website was compliant with the rules.
The TM Team never asked for the website removal from JSD.

**Comment by brianteeman** [comment]
So will it now be reinstated?

**Comment by jeckodevelopment** [comment]
No objections from Board or TM team.
Never requested the removal, as said.

**Comment by brianteeman** [comment]
@sebastienlapoux will you please reinstate the site and we can move on.

**Comment by sebastienlapoux** [comment]
@brianteeman back on https://showcase.joomla.org/browse-sites/16331.html

**Comment by brianteeman** [comment]
Thanks
