### ISSUE TITLE
[jshow] New site contrast - forgot password/username

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#166]
The contrast is not enough
![forgot](https://cloud.githubusercontent.com/assets/4639364/11013819/1dd7a612-851d-11e5-9471-4d66d5d0c58e.png)

http://joomla-showcase.octopoos-dev.com/user-login.html

**Comment by Sandra97** [comment]
Can someone please provide us some information about the status and progress about the new version of the showcase?
@mikeveeckmans, @Joomv?

**Comment by mikeveeckmans** [comment]
They committed to launch August 31 2016. If not the team will be unassigned and cjo team will take over.

Sent from my iPhone

On 15 Aug 2016, at 20:30, Sandra Thevenet <notifications@github.com<mailto:notifications@github.com>> wrote:


Can someone please provide us some information about the status and progress about the new version of the showcase?
@mikeveeckmans<https://github.com/mikeveeckmans>, @Joomv<https://github.com/Joomv>?

-

**Comment by MATsxm** [comment]
so by then it may be better to leave open the issues and we'll see later. Thanks

**Comment by oliviernolbert** [comment]
The background of the 3 links has been removed for a better contrast.

![capture d ecran 2016-08-29 a 14 00 55](https://cloud.githubusercontent.com/assets/6637889/18050800/0601776c-6df1-11e6-86e7-aa6e3e514832.png)

**Comment by MATsxm** [comment]
Thanks
closed - reopen if needed
