### ISSUE TITLE
[jhelp] 3.10 Start_Here

### ISSUE THREAD

**Issue by YGomiero** [joomla/joomla-websites#1661]
**Error with Joomla 3.10.1** :

 Help Menu / Joomla! Help

404 - RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist

frame link **help.joomla.org** : https://help.joomla.org/proxy?keyref=Help310:Start_Here&lang=en

**Comment by conconnl** [comment]
See the mentioned issue, it's probably about almost every link which was meant for 3.9 and should now work in 3.10
