### ISSUE TITLE
Joomla Registration-form

### ISSUE THREAD

**Issue by danield0915** [joomla/joomla-websites#1665]
In the latest version. 3.9X or 4.X , there is problem in registration-form. When you creat a menu link to Registration Form"index.php?option=com_users&view=registration" , there is no registration form in the frontend. What you can see is only "Username/password/remember me/login in/ forget your password/forget your user name". Three isn't any "registration" link where you can register a new member account.

**Comment by zero-24** [comment]
Hi,

by default the user registration is not enabled. Please go to the Options of the User Manager and enable user registration in the options.

For all upcomming questions please ask your question in the forum: https://forum.joomla.org/ as this here is the issue tracker for the .org Network of sites managed by the Joomla Project.
