### ISSUE TITLE
I cant recieve Reset password

### ISSUE THREAD

**Issue by MahdiAhazan** [joomla/joomla-websites#1667]
Hi

https://docs.joomla.org/Special:PasswordReset
No email will be sent to me when I request a password recovery on this page. Will be displayed even though a password message will be sent to you.
The sender of the e-mail may have a problem, or the system itself may have a problem. I do not know. But you can check better
![Reset password - Joomla Documentation](https://user-images.githubusercontent.com/19918913/133948053-c388b891-ab1c-4e33-85e5-48e7ddd402e5.png)
 My email address is in Gmail. I also tried another account on my personal domain and did not receive an email.

Best Regards
Mahdi Ahazan

**Comment by conconnl** [comment]
@coolwebcreations please help this user

**Comment by MartijnMaandag** [comment]
I tried this with an email address and with a username. Both function. Mahdi Ahazan do you still have this problem?

**Comment by MahdiAhazan** [comment]
Interestingly, before, the site did not allow me to become a member with this email and said that there is an account with this email. But today I became a member with the same email and the previous account is no longer available!
I managed to create a new account today.
