### ISSUE TITLE
[jshow] Error messages while registering

### ISSUE THREAD

**Issue by carlostester** [joomla/joomla-websites#167]
i got this 2 messages when registering  as a user::
Message 1
Thank you for registering

message 2
Error
You are not allowed to access this resource.

And also i dont recive any welcome message to my email

**Comment by MATsxm** [comment]
@sebastienlapoux
Thank you to take a look.

**Comment by sebastienlapoux** [comment]
Thanks. Fixed.

**Comment by carlostester** [comment]
thanks!

2016-03-21 16:03 GMT-06:00 Sebastien Lapoux <notifications@github.com>:

> Thanks. Fixed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/167#issuecomment-199507449>
>



-- 


*          Libera Tu Mente. **Boutique de TI*
          *Android:*              52+1-55-1821-3774
          *liberatumente:*    Tuits, skype, linkedIn, Instagram, www.

**Comment by MATsxm** [comment]
Thanks!
@sebastienlapoux, could you please check at the issues with the `Showcase` label? 
https://github.com/joomla/joomla-websites/labels/Showcase
I know you are working on the new site, but some could help.
Thanks
