### ISSUE TITLE
[jdev] Error on Coding Standards page

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-websites#1670]
https://developer.joomla.org/coding-standards/basic-guidelines.html currently throws an error due to Github deprecating auth through query parameter on September 8 2021.

400 Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param

**Comment by zero-24** [comment]
Its a "long known but noone found time to fix it yet" issues lets see how it goes: https://github.com/joomla/developer.joomla.org/pull/47 cc @HLeithner

**Comment by HLeithner** [comment]
Solved thanks
