### ISSUE TITLE
[jhelp] Error on Administrator config when debug is turn on

### ISSUE THREAD

**Issue by alexwai** [joomla/joomla-websites#1671]
fresh installation joomla 4.0.3 on  PHP Version 8.0.10. once completed site setup. immediately turn on debug mode in administrator. Site debug is working fine. however the global configuration page now is not accessible with error 500

**Comment by alexwai** [comment]
Apparently after increasing memory_limit   this issue is resolve.

**Comment by pe7er** [comment]
Good to hear that you've solved it. Thanks for sharing your solution!
