### ISSUE TITLE
[jhelp] Docs J4 Article Options wrong

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-websites#1675]
https://docs.joomla.org/Help4.x:Articles:_Options
Editing Layout Tab still shows dropdown with options.
**Help screen**
![Yndi 20211012-700](https://user-images.githubusercontent.com/8941310/136926447-63ef6871-d633-4292-a05b-c49fba33688d.jpg)
**Actual screen**
![Yndi 20211012-702](https://user-images.githubusercontent.com/8941310/136926497-6a393612-3327-4aa4-b5fe-94582af5dc4d.jpg)

https://github.com/joomla/joomla-cms/issues/17399

**Comment by MartijnMaandag** [comment]
I did upload a screenshot of the screen at this moment. Everybody can update the docs if there is something deprecated.

**Comment by conconnl** [comment]
Thanks for the help Martijn.
