### ISSUE TITLE
[jcm] Weird behaviour of short links

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#1677]
There's something wrong with short links.

If you copy/paste a short link, it works fine.
If you enter it manually, it doesn't.

Try with
https://joom.la/rIi
=> open it directly or copy paste it, all fine
=> enter it manually, you're redirected to https://comjrd.sandbox.joomla.org/blogs/community/yourls-test.html

It's an issue on Instagram as links are not clickable

**Comment by Sandra97** [comment]
Got it! Is there a way to exclude letters than can be misinterpreted like l (L)small case that looks like I (i) uppercase?

**Comment by conconnl** [comment]
I will research, I have never really looked at this system. It was build many years ago.

**Comment by Sandra97** [comment]
Thanks Wilco
