### ISSUE TITLE
[joomla.org] /4 site 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1678]
go to joomla.org and you are redirected to www.joomla.org
go to joomla.org/4 and you are redirected to www.joomla.org/4/4 which is a 404

@softforge

**Comment by brianteeman** [comment]
I believe it is something to do with the multilingual plugin settings

**Comment by mfleeson** [comment]
Going to joomla.org/4 on firefox redirects correctly now to https://www.joomla.org/4/
Chrome works the same.
In Microsoft Edge either http://joomla.org/4 or just joomla.org/4 redirects to https://www.joomla.org 

It looks like it's now fixed in Firefox but still broken in edge.
