### ISSUE TITLE
Check Google Analytics code from GA tag manager

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#168]
Ruth has mentioned that a lot of the main website asset GA tags are incorrect.

We will review this at the CLT Summit, placing here so we don't forget.

Google Tag container ID's for the sites, to be configured in the template setting: 
- [x] api.joomla.org: `GTM-NDWJB8`
- [ ] appsserver.joomla.org: `GTM-N5ZHLW`
- [ ] build.joomla.org: `GTM-MC5G3Z`
- [x] certification.joomla.org: `GTM-PFP9MJ`
- [x] community.joomla.org: `GTM-WQNG7Z`
- [x] conference.joomla.org: `GTM-PZWNZR`
- [ ] demo.joomla.org: `GTM-5BKMWT`
- [x] developer.joomla.org: `GTM-WJ36D4`
- [x] docs.joomla.org: `GTM-K6SPGS`
- [x] downloads.joomla.org: `GTM-KR9CX8`
- [x] events.joomla.org: `GTM-KNQ6RP`
- [x] exam.joomla.org: `GTM-TRG37W`
- [x] extensions.joomla.org: `GTM-MH6RGF`
- [ ] feeds.joomla.org: `GTM-PWMVKM`
- [ ] forge.joomla.org: `GTM-MXPCVJ`
- [x] forum.joomla.org: `GTM-TWSN2R`
- [x] framework.joomla.org: `GTM-NX46ZP`
- [x] help.joomla.org: `GTM-NVGP9X`
- [ ] ideas.joomla.org: `GTM-PXZLLT`
- [x] issues.joomla.org: `GTM-M7HXQ7`
- [x] joomla.org: `GTM-WWC8WL`
- [x] magazine.joomla.org: `GTM-WG7372`
- [x] opensourcematters.org: `GTM-5GST4C`
- [x] resources.joomla.org: `GTM-K8CR7K`
- [x] shop.joomla.org: `GTM-NZ9B7F`
- [x] showcase.joomla.org: `GTM-NKT9FP`
- [x] tm.joomla.org: `GTM-KZ7SM9`
- [x] vel.joomla.org: `GTM-NKZPKQ`
- [x] volunteers.joomla.org: `GTM-P2Z55T`

**Comment by pbwebdev** [comment]
Tag to be added


<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MH6RGF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MH6RGF');</script>

**Comment by sanderpotjer** [comment]
Issue in Joomla template repository: https://github.com/joomla/jdotorgtemplate/issues/19

**Comment by sanderpotjer** [comment]
Google Tag container ID's for the sites, to be configured in the template setting: 
- [ ] api.joomla.org: `GTM-NDWJB8`
- [ ] appsserver.joomla.org: `GTM-N5ZHLW`
- [ ] build.joomla.org: `GTM-MC5G3Z`
- [ ] cdn.joomla.org: `GTM-NLL2T9`
- [ ] community.joomla.org: `GTM-WQNG7Z`
- [ ] conference.joomla.org: `GTM-PZWNZR`
- [ ] demo.joomla.org: `GTM-5BKMWT`
- [ ] developer.joomla.org: `GTM-WJ36D4`
- [ ] docs.joomla.org: `GTM-K6SPGS`
- [ ] events.joomla.org: `GTM-KNQ6RP`
- [ ] extensions.joomla.org: `GTM-MH6RGF`
- [ ] feeds.joomla.org: `GTM-PWMVKM`
- [ ] forge.joomla.org: `GTM-MXPCVJ`
- [ ] forum.joomla.org: `GTM-TWSN2R`
- [ ] framework.joomla.org: `GTM-NX46ZP`
- [ ] help.joomla.org: `GTM-T742X9`
- [ ] ideas.joomla.org: `GTM-PXZLLT`
- [ ] joomla.org: `GTM-WWC8WL`
- [ ] magazine.joomla.org: `GTM-WG7372`
- [ ] opensourcematters.org: `GTM-5GST4C`
- [ ] platform.joomla.org: `GTM-WNPNWJ`
- [ ] resources.joomla.org: `GTM-K8CR7K`
- [ ] security.joomla.org: `GTM-TVPSP6`
- [ ] shop.joomla.org: `GTM-NZ9B7F`
- [ ] update1.joomla.org: `GTM-5CBPLM`
- [ ] ux.joomla.org: `GTM-PTVRPP`
- [ ] vault.joomla.org: `GTM-MJXG5T`
- [ ] vel.joomla.org: `GTM-NKZPKQ`
- [ ] volunteers.joomla.org: `GTM-P2Z55T`

**Comment by mbabker** [comment]
Add issues.joomla.org
Add downloads.joomla.org (in development)
Add certification.joomla.org (in development)
Remove update1.joomla.org (that's the server for the CMS' update XMLs; there's an index.html at the root to keep from listing the directories)
Remove build.joomla.org (Jenkins CI server, not public property)
Remove platform.joomla.org (not online anymore)

**Comment by sanderpotjer** [comment]
@mbabker thanks for the updates, the list is updates, as well the google tag manager containers.

**Comment by jeckodevelopment** [comment]
Please add:
- tm.joomla.org (currently under development)
- exam.joomla.org

**Comment by jeckodevelopment** [comment]
tm.joomla.org : `GTM-KZ7SM9`

**Comment by RCheesley** [comment]
exam.joomla.org: GTM-NFQRK6

**Comment by mbabker** [comment]
The GTM code `GTM-T742X9` listed for `help.joomla.org` is no longer valid.  A replacement is required.

Note that though this site has mainly been retired<sup>1</sup>, it is still used to provide the help screens for CMS installs and analytics on the domain should continue to be valid.

<sup>[1]</sup> The old 1.0 install has been taken offline and replaced with a static landing page and some PHP code to detect requests for the old 1.0 and 1.5 help screens to display an appropriate page for those requests going to the main `help.joomla.org` domain.  There's also a sub-install at `help.joomla.org/proxy` which has served all help screens from 1.6 to the current version and continues to be a top traffic source for the `joomla.org` web properties (there were over 115K hits for this subdomain on the main `joomla.org` analytics account (UA-544070-3) for the period May 1 through May 31).

**Comment by aDaneInSpain** [comment]
I have created a new Analytics property for help.joomla.org.

Below is the tracking code:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47728214-10', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by mbabker** [comment]
Err... Who owns this analytics account?  I don't see it on the Joomla account that I have access to.

**Comment by jeckodevelopment** [comment]
why don't include it in GTM? 
@RCheesley

**Comment by aDaneInSpain** [comment]
There are two "Owners" in the account I have access to. "Brad Baker" and "Joomla.org OSM" - I added it to the latter. I have asked for clarification on this and would like to move all properties into the "Joomla" one. Waiting to hear back from @RCheesley - You can see the property if you click on the very last line with grey background when looking on the list

**Comment by aDaneInSpain** [comment]
GTM?

**Comment by mbabker** [comment]
I don't know what's going on in the OSM account, but the one owned by Brad (account ID 544070) has been the primary GA used for .org for some time.  So unless there's a way to migrate data across accounts, I don't think it's a good idea to move everything to a new account.

**Comment by mbabker** [comment]
GTM = Google Tag Manager

**Comment by aDaneInSpain** [comment]
OK. I have deleted the other property and added it again under the Brad Baker account. 

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-544070-34', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by jeckodevelopment** [comment]
@aDaneInSpain I think that @mbabker needs a Tag Manager code for the website, instead of a property code in Analytics.

**Comment by mbabker** [comment]
I'm adding that GA code and removing GTM for now since it's 404'ing anyway.  If someone adds the property back to the GTM account let me know.

**Comment by mbabker** [comment]
Also for reference, the GTM code for `downloads.joomla.org` is no longer good either (404).

**Comment by jeckodevelopment** [comment]
As far as i know only @RCheesley can provide GTM codes

**Comment by aDaneInSpain** [comment]
The following properties are all inside the Joomla account:

- certification.joomla.org (UA-47728214-6)
- exam.joomla.org (UA-47728214-8)
- Joomla.org (UA-47728214-1)
- Lanyrd Team Page (UA-47728214-2)
- shop.joomla.org (UA-47728214-4)
- showcase.joomla.org (UA-47728214-9)
- tm.joomla.org (UA-47728214-7)
- vel.joomla.org (UA-47728214-5)
- volunteers.joomla.org (UA-47728214-3)

Should I report this as a separate issue?

**Comment by mbabker** [comment]
Something for the SEO team to decide but my advice would be to make sure everything's using the `544070` account ID as that one is pre-existing and has historical data.  Then again, my advice with site management as of late has been completely ignored so you can pretend you didn't read this if you wish 😉

**Comment by aDaneInSpain** [comment]
Haha... I agree. We can rename it to something other than "Brad Baker" though. Thank you for your advise.

**Comment by aDaneInSpain** [comment]
I have access to the GTM as well. Let me know what you need.

**Comment by jeckodevelopment** [comment]
@aDaneInSpain 
GTM codes for: `download.joomla.org` and for `help.joomla.org`

**Comment by mbabker** [comment]
A new code for downloads.joomla.org and help.joomla.org

**Comment by aDaneInSpain** [comment]
There is a site called download**s**.joomla.org - is that obsolete?

**Comment by mbabker** [comment]
Downloads with the s is the right one.  There is no download (no s).

**Comment by aDaneInSpain** [comment]
Google tag for help.joomla.org

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WZ46N8"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WZ46N8');</script>
<!-- End Google Tag Manager -->
```

**Comment by jeckodevelopment** [comment]
@mbabker sorry! missed the "s" in my comment!

**Comment by aDaneInSpain** [comment]
Sorry wrong code before for help.joomla.org

**Comment by aDaneInSpain** [comment]
This is for downloads.joomla.org (was created 7 months ago)

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KR9CX8"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KR9CX8');</script>
<!-- End Google Tag Manager -->
```

**Comment by RCheesley** [comment]
GTM-KR9CX8 for Downloads - for reference analytics properties should be set up under the OSM Account and not under Brad Baker, which hosts the historical properties.

**Comment by aDaneInSpain** [comment]
Oh. so I should set up help.joomla.org in that one?

**Comment by RCheesley** [comment]
@mbabker there has been an ongoing process to create new analytics accounts under a generic instead of person-specific account.  So the OSM account is the correct place for NEW analytics accounts to be created.

**Comment by RCheesley** [comment]
@aDaneInSpain please create under the OSM account - you were correct in the first place, that is where new Analytics properties should be created if one does not already exist in either the Brad Baker or OSM account.  Thanks for your help with this :)

**Comment by aDaneInSpain** [comment]
GTM for help.joomla.org

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NVGP9X"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NVGP9X');</script>
<!-- End Google Tag Manager -->
```

**Comment by aDaneInSpain** [comment]
OK, will do.

**Comment by aDaneInSpain** [comment]
Tracking code for help.joomla.org

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47728214-10', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by mbabker** [comment]
I wish someone would communicate these things and migrate existing user accounts between platforms.  I'm sitting here looking at the legacy stuff and apparently completely uninformed.

**Comment by mbabker** [comment]
If `GTM-KR9CX8` is right for downloads then why is the Chrome console reporting a 404 on that code?

**Comment by aDaneInSpain** [comment]
There is no way to move them between accounts

**Comment by RCheesley** [comment]
Sorry @mbabker but this has been in process for 3+ years since I joined CLT, it was a suggestion to move away from it being hosted by one individual's Analytics account over to something that was under a shared account.

We can't move the analytics accounts from the Brad Baker to the centralised account - hence two accounts.

Regarding the Downloads GTM it had not been published because we hadn't got the Analytics tag set up - the container is now published and @aDaneInSpain could you add analytics with the relevant settings? Thanks.

**Comment by mbabker** [comment]
I know you can't move them but you can add users to the new one unless there's some restriction in Google I've never been aware of.  I honestly don't track analytics and whatnot but it's been helpful the couple of times I've needed to get in and look stuff up.

And sorry if it seems like I'm excessively groaning in your general direction, I know there are a lot of moving pieces but as with so much in Joomla world it feels like the communication is sub-par and only select people seem to know what the right page of the right book that we should all be reading is.

**Comment by aDaneInSpain** [comment]
I have renamed the "Brad Baker" account to "Brad Baker - DO NOT ADD NEW PROPERTIES"

**Comment by RCheesley** [comment]
Sure, if you need access then do just ping the SEO team that's not a problem.  

There was a clean up done about a year ago where lots of people were removed from properties and if folk need access we just add them at the relevant level - too many people were given top-level admin access to accounts who only really needed view access.  It's entirely possible that you've never asked for access to anything under the OSM account, hence why you may not have access to it.

Sorry if that is an inconvenience, if you do only require access occasionally just ping the SEO team and we'll be able to sort that out really quickly.  There is a group in Glip for SEO Team Contributors which is the best place to ask.

**Comment by aDaneInSpain** [comment]
I have added a new analytics property as I could not see one for downloads.joomla.org and I have added that Analytics to GTM.

**Comment by mbabker** [comment]
Never asked because I never knew it existed before today.

If someone wants to assume admin control of the properties I have in Search Console, I should have absolutely zero need whatsoever to have access to any of the analytics stuff beyond knowing what the right codes are so that the templates can all be correct.  At least with Brad's GA account I could find all that stuff on my own when that was still what was being used; apparently not possible with the GTM/OSM account setup which is perfectly fine.

In fact it was me looking up analytics when I realized the help site wasn't having any data tracked because the GTM code was 404'ing and the analytics for the legacy GA account stopped on June 1.

At the end of the day all I'm really concerned with is making sure all the stuff's right.  If I can do it myself, even better for me.  If I can at least see the stuff and not have to ping others and hope I get a response, still convenient.  That's at least my mentality on things.

**Comment by mbabker** [comment]
Updated the template for the help screen proxy (help.joomla.org/proxy) with the `GTM-NVGP9X` code and it's still 404'ing.

**Comment by mbabker** [comment]
The GTM code `GTM-NVGP9X` is still resulting in requests to https://www.googletagmanager.com/gtm.js?id=GTM-NVGP9X returning a 404.  Please someone validate that everything is configured correctly and let me know when it is, otherwise I'm just going to remove the code and be done with it.

**Comment by aDaneInSpain** [comment]
The tag for help.joomla.org now loads correctly. Sorry, I thought it was already published.

**Comment by mbabker** [comment]
The only sites without tracking are JWC and the demo.  Can someone nudge the appropriate leads?

**Comment by jeckodevelopment** [comment]
@brianpeat for JWC ?

**Comment by brianpeat** [comment]
I gave this info to Jerri Christiansen

**Comment by JerryChr** [comment]
I am doing the site for JWC, I'll get on it - please mention me if any else.

**Comment by JerryChr** [comment]
Added GTM on conference.joomla.org now

**Comment by Joomv** [comment]
Can we check if the tag is published please?  Got no hits showing in real time whilst I am live browsing the site in another browser.

 

Thanks.

**Comment by jeckodevelopment** [comment]
@JerryChr please look at other issues with the `Conference` label

**Comment by mbabker** [comment]
@Joomv Anything still actionable here or is everything good with tag manager now?

**Comment by Joomv** [comment]
Need to sort out the linkage with demo and also conference.  Will sort that in the next few days then return to close.
