### ISSUE TITLE
Release News - wrong links in "Changes to Update Process that you need to be aware of"

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#1682]
At https://www.joomla.org/announcements/release-news/5850-changes-to-update-process-that-you-need-to-be-aware-of.html
at the bottom under **Translations**

![Screenshot from 2021-10-28 09-38-53](https://user-images.githubusercontent.com/1217850/139209214-9b1dc641-de22-4d47-875b-4df636e8c822.png)

Please change
- Dutch: [Changements importants dans le processus de mise à jour](https://www.joomlacommunity.nl/nieuws/versies/wijzigingen-in-het-update-proces-waar-je-je-bewust-van-moet-zijn)

to:

- Dutch: [Wijzigingen in het update-proces waar je je bewust van moet zijn](https://www.joomlacommunity.nl/nieuws/versies/wijzigingen-in-het-update-proces-waar-je-je-bewust-van-moet-zijn)
- French: [Changements importants dans le processus de mise à jour](https://www.joomla.fr/actualites/changements-importants-dans-le-processus-de-mise-a-jour)

Thanks!

**Comment by conconnl** [comment]
Looks like this is fixed

**Comment by pe7er** [comment]
Thanks!
