### ISSUE TITLE
[jlaunch]  Mobile version of Joomla.com has a buggy menu

### ISSUE THREAD

**Issue by valentinroue** [joomla/joomla-websites#1683]
Please describe the problem or your issue
Browsing to joomla.com from Android 10 mobil phone.
Wanted to explore menu, upper roght, and after i hit the "Download & extend" options apper, like "Download", "Extensions".
It would be nice if when i press Download or Extension to get me to the page.
The buttons, all buttons, are not responding, like the buttons does not have a link.

It could be useful to include an URL of evidence.
https://launch.joomla.org/

Please use a consistent title for your issue.
Ok
![Screenshot_20211028-194820_Chrome](https://user-images.githubusercontent.com/93340781/139300044-1561400b-edb7-433a-ac41-c0329e327942.jpg)

**Comment by conconnl** [comment]
I asked CloudAccess to look at it.

**Comment by Alam9835** [comment]
i want to work on this issue

**Comment by B1TSH3LL** [comment]
As an Gsoc Contributer I wanted to work on this issue. Please Assign it to me

**Comment by HLeithner** [comment]
@Pawel-Panek can you have a look? it seems the mobile menu is not really working

**Comment by Pawel-Panek** [comment]
The menu has been pulled from joomla.org but we are checking if that should be fixed on our end.

**Comment by HLeithner** [comment]
Ok, I checked this again and it behaves a bit different then joomla.org when you use the mouse. Having a page for Download & Extension is not plan from our site at the moment.
@Pawel-Panek please have a look for the strange behavior and I'm closing this issue because it has nothing with launch.j.org to do if I understood it correctly.

thanks

**Comment by HLeithner** [comment]
Thanks works for stock Browser but nicht for Vivaldi. Maybe a Browser problem.
