### ISSUE TITLE
[jcm] broken link in interview

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1685]
at the end of the page of https://magazine.joomla.org/all-issues/october-2021/leadership-interviews-nicola-galgano the link to 

`https://github.com/open-source-matters/contact-us`

actually has a period appended to it 

`https://github.com/open-source-matters/contact-us.`

and thus is a 404 page when clicked.

**Comment by andreagentil** [comment]
Fixed, thanks for reporting.
