### ISSUE TITLE
[jcm] missing module image

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1686]
![image](https://user-images.githubusercontent.com/1296369/140427940-9ff9a61a-78e0-420f-81a9-864880f0e74c.png)

![image](https://user-images.githubusercontent.com/1296369/140427952-d7331910-a5bb-475f-9477-2f8768ca8644.png)

**Comment by andreagentil** [comment]
Fixed.

Thanks for reporting.
