### ISSUE TITLE
[jorg] Where is the shop?

### ISSUE THREAD

**Issue by peterpeter** [joomla/joomla-websites#1688]
I want to replace/rebuy my 10+ year old 'Joomla-Laptop'-Bag in the Joomla!-Shop. The Menulink
https://community.joomla.org/the-joomla-shop.html
points to an article from 2017witch is a simple link to
https://shop.spreadshirt.ie/the-joomla-shop
but after two '301- moved permantently' from spreadshirt.ie
I am landing back at the article again at community.joomla.org

Caught in a loop. So where is the shop?

:)

**Comment by conconnl** [comment]
@softforge any thoughts on this, is the shop still existing?
I will check the site structure this evening.

**Comment by conconnl** [comment]
It seems that spreadshirt changed all their loading addresses.
Or without communicating this or with someone not acting on it.
I updated all our CSP rules, for me it now opens again.

**Comment by softforge** [comment]
The shop has not been working properly since the start of covid. We need to find people willing to do a full overhaul and take this project on as the cost of shipping, places that are shipped too are all different since covid and a multi continent solution needs to be found which also keeps the carbon footprint as low as possible.

**Comment by peterpeter** [comment]
Ok, thanks  @conconnl and @softforge 
The shop is available again.
As I'm located in switzerland (non EU) and had no spare storage room, it makes no sense to offer me as a shipping point, I guess. 
But if I had I would ;-)

**Comment by mfleeson** [comment]
Can I suggest setting up a RedBubble store? They manufacture in europe, australia and the USA and are well set up for all of the shipping facilities. You just upload the artwork and position it on everything from t-shirts to facemasks but there's no outlay for stock and Joomla would receive at least 40% on each item sold. I'd be happy to help.

**Comment by softforge** [comment]
Great idea and those magic words, " I'd be happy to help" as we could sure do with some help in marketing to get these things going.

I am organising Joomla London today but will message direct on Glip over the next few days and we can take this forward. Thank you.
