### ISSUE TITLE
[jed] Lots of pages are blank

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1693]
Hi,

I'm forwarding the [original report](https://github.com/joomla/jed-issues/issues/236) also here: 

> Many pages on JED are blank today e.g. https://extensions.joomla.org/extension/calendars-a-events/events/jevents/ or https://extensions.joomla.org/category/e-commerce/shopping-cart/

It looks like all pages related to com_jed, with the exception of the home, are down.

**Comment by conconnl** [comment]
Original post is closed
