### ISSUE TITLE
[jcomm] expired email

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1695]
This morning I received 80 identical emails as shown below. In addition to the number the text says "Will expire on Expired". Obviously I would have expected a date instead of the word Expired. However logging in and checking it says the entry has expired and unpublished. If you are now setting 365 days  as  the duration of an entry in the Resources section of the website shouldnt there be a notice before expiry? As the site was one of the very first listed it may well be that I am the first to notice this?

![image](https://user-images.githubusercontent.com/1296369/144811567-1acb6c84-659e-4e2c-80a9-c455f0054a73.png)

**Comment by conconnl** [comment]
Thanks for letting us now.
We indeed noticed this bug in the component of the developer. 
First non of the mails were send, enabling the notification mail message (which was disabled for unknown reason) the component created a loop. Non of the expired entries were unpublished. 

The notifications are disabled again and the developer has received a support request. 
I can’t do more then wait and hope that enabling the notifications again doesn’t create another loop after they fixed it.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/144813892-38e20c46-6afa-49b6-b958-ffbd994282bb.png)

**Comment by conconnl** [comment]
That is after you clicked the link.
Not at the moment of expiration.

**Comment by brianteeman** [comment]
I am confused by what you just wrote

> Non of the expired entries were unpublished.

**Comment by conconnl** [comment]
There is a difference between the automatic flow and you clicking the link.
