### ISSUE TITLE
[joomla.org] s/deprication/deprecation 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1699]
Please fix the spelling on https://www.joomla.org/announcements/release-news/5851-joomla-4-0-5-and-joomla-3-10-4-are-here.html

 s/deprication/deprecation

**Comment by softforge** [comment]
Thank you, thats been changed.

**Comment by PhilETaylor** [comment]
"Please note if you show "all errors" there could be deprecation notices on some pages."

Should be rewritten too... There is no such thing as showing "all errors"

"Please note if you set Error Reporting to "development" in Joomla Global Config, then there could be deprecation notices on some pages. We are aware of these and working through them to ensure future full compatibility with PHP 8.1"

**Comment by softforge** [comment]
https://www.php.net/manual/en/function.error-reporting.php
Is not E_ALL not errors all and all errors is a more human way of saying it.
In my plesk panel there is no "development" setting.
It has "The error reporting level." With E_ALL and then various lesser reporting so with out notices & ~E_NOTICE

In Joomla 4 the choice is System Default, None, Simple, Maximum. 
Development is not mentioned so I felt all errors would match more what people set in their error reporting. Again I dont have development mentioned there but perhaps they do in cpanel.
