### ISSUE TITLE
[jcomm] Improve CSS Accessibility Read More Hover

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#17]
The read more hover on the community blogs do now have enough contrast to meet accessibility standards. Please choose a new colour scheme for the buttons that meet WCAG 2.0 AA colour contrast requirements.

![](http://s3.postimg.org/qbsknjydv/Screen_Shot_2015_08_05_at_7_29_49_pm.png)

**Comment by Sandra97** [comment]
Agree.
Except the fact that the look of this button is really "out of date" (I love the 80's but, agree or disagree, we are in the flat design era, and also, a 'hover' style is not needed anymore), a simple change in the a:hover of the readon class (without changing the style) can solve it:
i.e: 
color: #a8c4eb;
text-shadow: 0 1px 0 #000; 
I can't do anything, I don't have an access ;)

**Comment by MAT978** [comment]
BTW, Soren and Crystal are working on a entirely new .org
(Hope they are not fan of the 80's :p )

**Comment by Joomv** [comment]
Changed to white on r/o

**Comment by Sandra97** [comment]
Maybe would be better without the text shadow?

**Comment by Joomv** [comment]
Done.
