### ISSUE TITLE
[joomla.org] Hacked Website (Malware): http://dogs-wellness.saidenz.de/images/stories/Bilder/admin/NotificacaoDER-28747257_2015.rar

### ISSUE THREAD

**Issue by Fraudwatch** [joomla/joomla-websites#170]
[Incident#JJD-179643]
Dear Web Site Administrator

The FraudWatch International Security Operations Centre (www.fraudwatchinternational.com) has received a report of a fraudulent financial web page (illegal Trojan Virus download / data collection) hosted on a website you administer.

** Please be aware that clicking the following link will redirect you to a site which contains malware, we are requesting that you remove this redirection. Please do not download the executable file if you follow this link **

IP Address: 81.88.34.168

URL: http://dogs-wellness.saidenz.de/images/stories/Bilder/admin/NotificacaoDER-28747257_2015.rar
Additional URL's:

** Malware Scan Report:
 https://live.metascan-online.com/#!/results/file/2a4f6cd022474b7e844964695b628494/regular

Client Brand Targeted: Santander Brasil (Banco Santander)

*************************

On behalf of our client, we would greatly appreciate your assistance in:

a) Urgently cleaning, closing or disallowing access to the site listed above as appropriate.

b) obtaining and providing to us additional information regarding this incident, for example relevant logs or file from the host,

*************************

If you are not the correct person to be dealing with this incident, please forward this request to the relevant person.

If you are already aware of this matter, we apologise for any inconvenience. If possible, we would still appreciate a copy of any relevant files from the host, including logs and any php files relevant to the malware site, which may indicate where the stolen login credentials are being sent.

The Anti-Phishing Working Group has published a document that will assist in securing this website and preventing future occurences of this problem. You can find this document here: http://www.apwg.com/reports/APWG_WTD_HackedWebsite.pdf

This incident has been assigned an Incident Number, found in the subject line. We will be monitoring this incident, and tracking its progress to closure. Please use this incident code in the subject line of all correspondence relating to this Incident.

Please contact us should you require any clarification or assistance. We thank you for your urgent consideration of this request.

Regards,
Erfan
Security Operations
FraudWatch International
Tel USA: +1 (415) 449 8800
Tel AUS: +613 9887 6777
Fax: +613 8660 2688
Email: security@fraudwatchinternational.com
http://www.fraudwatchinternational.com

**Comment by sanderpotjer** [comment]
@Fraudwatch the Joomla-project is not administrator/maintaining the mentioned website. Please contact the webmaster/webbuilder of the website.
