### ISSUE TITLE
[jlaunch] 

### ISSUE THREAD

**Issue by IndiaIT360** [joomla/joomla-websites#1705]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.
![joomla issue](https://user-images.githubusercontent.com/97505102/148897663-c336db93-8711-4416-902f-ca44c4a22611.png)
not able to create id on your platform showing issue invalid phone number please see the Attachment

**Comment by igorkaczor** [comment]
@IndiaIT360 what browser are you using and what are the exact steps your taking to fill out the form?
What is the order of the fields you fill in? 
Do you click in them or move through them with [TAB]? 
What do you click after all fields are filled?
Do you submit the form with click or Register or [TAB] to select Register and hit [Enter]?

We can't replicate the issue filling out the form in the usual fashion using this phone number. 
When we click out of phone number field into the next one it fixes the phone number format and validation is ok.

**Comment by HLeithner** [comment]
This problem can't be replicated by cloud access and got no feedback by the issue opener. I'm closing this issue. A new issue can be created at any time.
