### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by MrKiller01** [joomla/joomla-websites#1709]
I try to log in your forum with the credentials I know. All attempts has not worked and I am hopeless at this time.
Can you please send me my username to this e-mailadres so that I can re initiate my password, as this is also unknown by me at this time.

Thanks.

Maybe for future reference, ask if someone has forgotten his password, and if a user has forgotten his name.
Often websites handout e-mailadres and or username to login, this is why it got complicated.
The e-mailadres I use here on this forum is the e-mailadres used on forum.joomla.org, only the data I had was for forum.dutchjoomla.org, but that link does not work anymore. I tried to make a new account under my e-mailadres, but that was already in use, of course it was.   

I hope you can help me...

(The e-mailadress is linked to this account at github, so the message come only to me)

**Comment by pe7er** [comment]
What's your username at Joomla forum? And what email address did you use to register at Joomla forum?

You can contact me via email at peter.martin@community.joomla.org

**Comment by pe7er** [comment]
After 10 days I haven't received a response via email from you. If you still need further help, please contact me.
I'm closing this issue.

**Comment by MsKiller01** [comment]
ehm, I did send you an e-mail!

**Comment by MsKiller01** [comment]
The e-mail was sent from avandel at gmail.com to yours peter.martin at community.joomla.org.... Might it be in your spam folder?
Shall I resend the mail?

**Comment by pe7er** [comment]
Ok, sorry, I just found your email. I'll contact you via email.

**Comment by MsKiller01** [comment]
No worries, happens to all of us, me including... Thanks for helping...

**Comment by pe7er** [comment]
Solved!
