### ISSUE TITLE
[jorg] Move joomla.org into a git repository

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-websites#171]
The joomla.org website should be moved into a git repository for several reasons (like proper staging/live environment, easier contributions without VPN/SFTP access, maintenance etc...). 

This would also allow to start working on integrating the subsites into the main website where possible and reducing the number of installs in the joomla.org property. Future changes to the template will be easier too.

A repository is created for this purpose https://github.com/joomla/joomla.org

The site setup should be changed for a staging and live environment based on the git repo.

**Comment by jessicadunbar** [comment]
Michael and I have been discussing site deployment workflow for a long time. This is how I run deployments at our office, but keeping content in sync is a headache.

What is your thinking on keeping the content on staging and live in sync?

**Comment by sanderpotjer** [comment]
@jessicadunbar in general details still have to be worked out, in a way thats works the best for all of us. Regarding the content: do you mean content as in "articles posted on the live site to staging" or as "database changes from staging to live"? Or both :)

What would be good is to generate at least a sample database that could be used for local developments that does not include sensitive information from the database. 

Any suggestions from the community for the best setup for joomla.org based on experiences are much welcome!

**Comment by mbabker** [comment]
Presumably we'd want staging (think the repo subdomain we were using while upgrading to 3.4) and live to have in-sync databases (if anything staging has newer items not yet posted to live).  For dev, yes we'd want to limit that down (especially the users table).

**Comment by mikeveeckmans** [comment]
We might have a solution soon from deevop, @mbabker i'll ping you by mail.

**Comment by mbabker** [comment]
Closing for now.  We can revisit later or offline.
