### ISSUE TITLE
[jdown] 4.0.6 release date wrong.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1711]
https://downloads.joomla.org/cms/joomla4/4-0-6
<img width="565" alt="Screenshot 2022-01-18 at 08 30 59" src="https://user-images.githubusercontent.com/400092/149899658-527838d9-d688-4c96-9957-4a360d56a2ef.png">

**Comment by zero-24** [comment]
Thanks fixed.
