### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by RobWilkinsonUK** [joomla/joomla-websites#1713]
This code in HelloWorldViewHelloWorld.php in the examples fails with an error. The return from $this->get('Errors') is not countable and throws an exception in PHP 8:
```php
	$this->msg = $this->get('Msg');

		// Check for errors.
		if (count($errors = $this->get('Errors')))
		{
			JLog::add(implode('<br />', $errors), JLog::WARNING, 'jerror');

			return false;
		}
```
edit: Markdown

**Comment by coolwebcreations** [comment]
Can you add the link to the related page in the JDocs please?

**Comment by RobWilkinsonUK** [comment]
My apologies for not being more careful in my post. I should know better.
The page in question is 👍 https://docs.joomla.org/Special:MyLanguage/J3.x:Developing_an_MVC_Component/Adding_a_model_to_the_site_part
The code in question is :

**Comment by RobWilkinsonUK** [comment]
The if (count(x) throws an error in php 8.
I changed it to 👍    $errors=$this->get('Errors');
     if (is_countable($errors ))
        {
            JLog::add(implode('<br />', $errors), JLog::WARNING, 'jerror');
            
            return false;
        }
        
        // Display the view
        parent::display($tpl);
    }

**Comment by HLeithner** [comment]
This has been fixed, closing this, thanks for pointing this out.

If you are interessted help to write more documentation we started a new documentation project at https://manual.joomla.org which is written with docusaurus and markdown and can be edited in [github](https://github.com/joomla/manual)
