### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by krishang** [joomla/joomla-websites#1715]
Please enable my account. Says the account is blocked.  User name KrishanG and email should be kgurusinghe@yahoo.com.

thank you

**Comment by conconnl** [comment]
Hi @krishang 
What is the website for your request?
Joomla.org doesn’t have account for public users

**Comment by pe7er** [comment]
https://forum.joomla.org/ has user accounts. 
However, I couldn't find any account with your user details.

**Comment by pe7er** [comment]
I am closing this issue due to lack of a response.
@krishang Feel free to re-open this issue if you submit more information about your issue.
