### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by dawnjgill** [joomla/joomla-websites#1719]
Please describe the problem or your issu
I am unable to view my site, a screen pops up that reads:

You may not be able to visit this page because of:

an out-of-date bookmark/favourite
a search engine that has an out-of-date listing for this site
a mistyped address
you have no access to this page
The requested resource was not found.
An error has occurred while processing your request.
Please try one of the following pages:

[Home Page](http://godsbehalf.com/index.php)
If difficulties persist, please contact the System Administrator of this site and report the error below.

Using $this when not in object context
It is not my adminstrator, this has happened before and you were able to fix it.  It typically happens when Joomla updates it, which is why I haven;t updated it.  Please repair it, I haven't been able to publish for approximately a week.

Thank you!

Dawn Gill
dawnjgill@aol.com
714-791-7111

**Comment by hvdmeer** [comment]
Please contact the company in charge of your website if you didn't build it yourself or the hosting company to help you. The Joomla Project only provides the CMS your website is built in, we are not responsible for any website it's build with.

This is also the reason why your previous post was closed. Here it is only allowed to post problems regarding the official *.joomla.org website where you can download our software for free.
