### ISSUE TITLE
[joomla.org] /4 redirect

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1720]
It is more and more common not to need to use the www when entering a url - I very rarely do.

joomla.org/4 redirects to www.joomla.org

if you want to go to the /4 landing page you have to type the www

cc @softforge
![PoutGirlGIF](https://user-images.githubusercontent.com/1296369/153231581-5cb93d1d-77b7-4a97-b81c-ae9519ba76ac.gif)

**Comment by brianteeman** [comment]
Please can this be fixed. I never type the www

**Comment by TLWebdesign** [comment]
@brianteeman is this something that can be fixed within the joomla 4 installation? My knowledge says it needs to be fixed in the joomla.org htaccess or on server level, right?

**Comment by brianteeman** [comment]
you are correct

**Comment by TLWebdesign** [comment]
too bad else i could've done something about it.

**Comment by brianteeman** [comment]
no worries - its been a year since I reported it

**Comment by HLeithner** [comment]
fixed

**Comment by brianteeman** [comment]
THANK YOU!!
