### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by 41global** [joomla/joomla-websites#1724]
I think my IP/Username has been blocked and I am unable to login.  I was able to login once and start a thread but unable to get back in for some reason.  Can you please help and unblock me.  Thnx

**Comment by pe7er** [comment]
Do you mean you cannot login into Joomla forum?
The form account with username 41global has not been blocked.

Could you try to login with another browser?
Could you try to reset your password?  https://forum.joomla.org/ucp.php?mode=sendpassword

**Comment by 41global** [comment]
I’ve tried to reset my password but nothing gets sent to my email to reset password for some reason.  This is what I get

***@***.***

Ive also created a new account and it says its inactive “fortyoneglobal”

Dezmond Abrams
41Global
https://www.41global.com<https://www.41global.com/>
***@***.***

**Comment by pe7er** [comment]
Ok, I can reset your password for you. 
To make sure that it's really your account, I'll send an email message to the email address that is linked to your forum account.
Could you reply to that message?

**Comment by 41global** [comment]
Yes sir that would be perfect! I'm just not 100% sure on which email I used but yes please send message. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pe7er** [comment]
I've sent you 4.5 hours ago an email from peter.martin@community.joomla.org to the "live.com" email address that's connected to your Joomla forum account. If you haven't received it already, please check your spam box.

**Comment by pe7er** [comment]
Solved!
