### ISSUE TITLE
[jdev] 

### ISSUE THREAD

**Issue by Tsprott** [joomla/joomla-websites#1725]
Please describe the problem or your issue
When I try to access our website admin page I get the following message

Table './killarn_killarn/atvi6_session' is marked as crashed and last (automatic?) repair failed SQL=INSERT INTO `atvi6_session` (`session_id`, `client_id`, `time`) VALUES ('23vkqkup2cdaip16r4th15c6c6', 0, '[1644880495](tel:1644880495)')

I am unable to access the admin login page

**Comment by Hackwar** [comment]
This is the bugtracker for the websites of the Joomla! organisation, not for the CMS software and especially not a support forum. If you need support, please go to https://forum.joomla.org. If you think you found a bug, open a ticket on https://github.com/joomla/joomla-cms/issues
