### ISSUE TITLE
[jdev] Latest Release

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1727]
Probably a good idea to either replace the J3 icon or to add a J4 icon

![image](https://user-images.githubusercontent.com/1296369/154045711-92175b43-e325-4f45-8e17-3d3b1da15374.png)

cc @softforge

**Comment by HLeithner** [comment]
this has been fixed already. closing it thanks.

**Comment by brianteeman** [comment]
Thanks - forgot about this
