### ISSUE TITLE
[jorg] /4/ shows "Español" two times in "Translations"

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla/joomla-websites#1728]
As title say see screenshot. Better sort alphabetical?

<img width="1152" alt="J4 translations" src="https://user-images.githubusercontent.com/89642616/154257296-6ba9d95b-3962-41df-aea1-dee1bff0f807.png">

**Comment by Franzwohlkoenig** [comment]
Maybe i don't understand correct and its not a issue - no comment let me guess this and closing. If i'm wrong, please reopen.

**Comment by pe7er** [comment]
@Franzwohlkoenig What's the URL of your issue?

At https://downloads.joomla.org/ the 2nd Spanish ``(de Colombia)``

![Screenshot from 2022-06-09 08-49-24](https://user-images.githubusercontent.com/1217850/172783058-4b41fc0d-ca9d-4465-8543-7d09ef36e17a.png)


At https://www.joomla.org/4/en/ there's only one Spanish flag. 
However the languages there are not in alphabetical order

![Screenshot from 2022-06-09 08-55-07](https://user-images.githubusercontent.com/1217850/172783989-3ad33b1a-cf20-4547-86ef-5ff4a7ff96e0.png)

**Comment by Franzwohlkoenig** [comment]
Thanks for your comment @pe7er. I'm talking about the url https://www.joomla.org/4/en/#translations, the screenshot in my first comment shows it, but it was the color of 4.0, now it looks like

<img width="1430" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/172789548-cfa1ba14-8be8-4ce9-931b-04bc17577d30.png">

Both red marked "Espanol" link identical to https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-spanish so i thought its an issue.

**Comment by bembelimen** [comment]
Thank you @Franzwohlkoenig we fixed the issue.
