### ISSUE TITLE
[jlaunch] joomla.com - danger ahead

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1733]
Thought I would give launch.joomla.org another try. Sadly after creating my account and trying to access the site I am greeted with

![image](https://user-images.githubusercontent.com/1296369/156902727-1765042e-8ffc-4ff7-bc9c-25f43a35b14e.png)

**Comment by brianteeman** [comment]
Overnight it appears that the site now has the correct ssl. Not a great experience though.

**Comment by brianteeman** [comment]
serioiusly!!! no one had an ipv6 to test with.

**Comment by brianteeman** [comment]
i see that 8 months later this is still not fixed

**Comment by HLeithner** [comment]
@Pawel-Panek or @dereksca just a heads up on this topic.
