### ISSUE TITLE
[joomla.org] yellow?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1734]
Is this the real design or is it broken? White text on yellow background? Yellow as a dominate colour?

Seems so off brand...

<img width="1536" alt="Screen Shot 2022-03-06 at 16 38 41" src="https://user-images.githubusercontent.com/400092/156932611-be312e9b-3ba5-42ef-aa21-07293a530f56.png">

**Comment by HLeithner** [comment]
I think It's expected @softforge @bembelimen

**Comment by chmst** [comment]
White text on yellow background must be fixed. It is known issue.

**Comment by mfleeson** [comment]
These are the planned colours for recent and forthcoming releases - the decision for Yellow/Gold was made several years ago and the current marketing team were told to use them. 

![image](https://user-images.githubusercontent.com/961654/156934261-c533ea78-555e-46b2-b554-196aef3dde2e.png)

**Comment by PhilETaylor** [comment]
ok - but its so off brand it just looks wrong. whatever.
