### ISSUE TITLE
[japi] Framework api 2.x missing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1735]
It seems the only docs are for the Joomla \ DateTime interfaces and nothing else in Joomla Framework 2.x? 

https://api.joomla.org/framework-2/index.html

**Comment by HLeithner** [comment]
@nibra @wilsonge can you have a look?

**Comment by nibra** [comment]
True story. In a pure volunteers' organisation, however, things not always go the ideal path. We can't do more than try to catch up.

**Comment by PhilETaylor** [comment]
It's called responsibility. Something very lacking in Joomla. Just because someone is a volunteer doesn't mean they are not expected to be responsible and time sensitive.

**Comment by PhilETaylor** [comment]
Also Joomla is NOT a  "pure volunteers' organisation" - you all have clearly defined - appointed roles with grandose titles - badges to wear... those badges come with commitments and responsibilities. You are no longer "just a volunteer"...

**Comment by Hackwar** [comment]
This has been fixed. 
https://github.com/joomla/api.joomla.org/pull/25
https://ci.joomla.org/joomla/api.joomla.org/29
