### ISSUE TITLE
[joomla.org] Minor bug in the mobile menu

### ISSUE THREAD

**Issue by kirilhristov** [joomla/joomla-websites#174]
It can only be closed once. Try opening and closing it several times. You’ll see that it can no longer close after the first time.

![screen shot 2015-11-11 at 6 41 19 pm](https://cloud.githubusercontent.com/assets/15803386/11096811/9e924f7a-88a4-11e5-9e11-61869f70a468.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by mikeveeckmans** [comment]
Indeed, confirmed on Android Phone, using Firefox and chrome.



On Wed, Nov 11, 2015 at 10:14 AM -0800, "Brian Teeman" <notifications@github.com<mailto:notifications@github.com>> wrote:

Confirmed
On 11 Nov 2015 4:47 pm, "kirilhristov" <notifications@github.com> wrote:

> It can only be closed once. Try opening and closing it several times.
> You'll see that it can no longer close after the first time.
>
> [image: screen shot 2015-11-11 at 6 41 19 pm]
> <https://cloud.githubusercontent.com/assets/15803386/11096811/9e924f7a-88a4-11e5-9e11-61869f70a468.png>
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/174>.
>

-

**Comment by mbabker** [comment]
It's working now, no idea when I managed to fix it.
