### ISSUE TITLE
[joomla.org] 4.1 landing page

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1742]
The new 4.1 landing page is using the wrong colours. The colour to use as per the joomla 4 colour pallete document is orange not yellow for 4.1 as clearly shown in the screenshots in that document.

**Comment by ceford** [comment]
@brianteeman can you tell us where to locate the **joomla 4 colour pallete document**? And what exactly is this new Landing Page?

**Comment by TLWebdesign** [comment]
@ceford The color pallette is available for those in the marketing department.I’m from that department and have already have a new tuser.css with the correct colors ready to go. They just need to be implemented. Biggest task is changing all the artwork. Those i’d like to see changed to svg from png.

**Comment by TLWebdesign** [comment]
Oh and the page is joomla.org/4

**Comment by TLWebdesign** [comment]
No it’s just the joomla 4 landing page that is yellow now, but should’ve been orange.

**Comment by chmst** [comment]
I don't know where the colour comes from. Bur orange or yellow  - orange on white or white on orange probably will not have the required colour contrast ratio. As much as I know the colour scheme will change with 4.2 - and we will have an eye on it for colour contrasts.

**Comment by TLWebdesign** [comment]
True hats why the new design doesn’t use white on orange or the other way around. Color contrast is completely wcag 2.0 aa compliant in the redesign to joomla orange.

**Comment by ceford** [comment]
If the white/yellow theme is anything to go by I would not be surprised if there is a storm of protest. My first impression: ghastly!

**Comment by brianteeman** [comment]
@ceford its been like that for almost 2 months

**Comment by ceford** [comment]
I have https://www.joomla.org/ bookmarked and other pages I use (in Docs and the Forums) link to that too so I only encountered the /4/en version today. I imagine lots of others will be in the same boat.

**Comment by sebastienlapoux** [comment]
The concerned page https://www.joomla.org/4/en/ Issues about primary and secondary colors selected. Don't respect accessibility and is ugly.

**Comment by brianteeman** [comment]
closing as its now irrelevant
