### ISSUE TITLE
[jdev] wiki-activity.html show no diagramm

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla/joomla-websites#1743]
In https://developer.joomla.org/wiki-activity.html no diagramm is shown.

**Comment by Franzwohlkoenig** [comment]
Can anyone of the https://volunteers.joomla.org/teams/cms-release-team please have a look?

**Comment by zero-24** [comment]
Looks like the data is missing when checking the browser conse you get the message thata would support that. @HLeithner Can you check how that data is passed to the site? Maybe something there is broken? Maybe after the docs upgrade?

**Comment by Franzwohlkoenig** [comment]
@zero-24 yes, the issue come up after the mediawiki update.

**Comment by zero-24** [comment]
Maybe @wilsonge or @coolwebcreations knows what have changed after the upgrade?

**Comment by Franzwohlkoenig** [comment]
Can someone please delete in https://developer.joomla.org/tracker/volunteer-activity.html below 'Volunteer Activity' the Link 'Wiki Activity'?

This page is empty and if there is no information it should be no link in the meantime.

**Comment by wilsonge** [comment]
I'll go have a dig around. https://github.com/joomla/developer.joomla.org/blob/master/components/com_trackerstats/controllers/wiki.json.php#L41 the endpoint we're using here still works in the browser so it must be something instance specific I guess.

**Comment by wilsonge** [comment]
Fixed https://github.com/joomla/developer.joomla.org/commit/a3b9a061aaabac79f0a61123b42c9f490374eacf
