### ISSUE TITLE
Usage of js eval on the volunteer site

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1745]
https://volunteers.joomla.org/

![image](https://user-images.githubusercontent.com/1296369/159130039-c7076b19-ab98-4c67-aa3f-45b0a4c19f18.png)

**Comment by zero-24** [comment]
in the first step thats the expected behavior. ;-)

 @sanderpotjer can you take a look what eval script runs there? we should not use js eval within our code.

**Comment by sanderpotjer** [comment]
@brianteeman thanks for the report. However can't duplicate this, don't see this error on the Chrome devoots for the mentioned url.

**Comment by brianteeman** [comment]
Very weird. I dont see it in guest mode or incognito mode which would indicate that it is a browser plugin. But then I would expect to get the same error on other sites which I dont. Will try to investigate further

**Comment by brianteeman** [comment]
Found out how to replicate it

IF you have the chrome extension "AdBlock — best ad blocker" then even if it is paused or disabled for the site then the CSP alert occurs.

**Comment by zero-24** [comment]
ok so the issue can be closed here right? And an issue within that adblocker has to be opend?
