### ISSUE TITLE
[joomla.org] Wiki links not correct 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1747]
https://www.joomla.org/announcements/release-news/5857-joomla-4-1-1-and-3-10-7-release.html

<img width="705" alt="Screen Shot 2022-03-29 at 18 33 46" src="https://user-images.githubusercontent.com/400092/160671444-7ff4331c-838d-45e4-a09e-8d1f959a5ac6.png">

**Comment by HLeithner** [comment]
Seems also to be fixed already, thanks
