### ISSUE TITLE
[jvols] Phantom users

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#175]
On some teams pages a phantom member is being displayed in the list. My guess would be that this user has been removed.

Example https://volunteers.joomla.org/working-groups/bug-squad
![screen shot 2015-11-12 at 11 14 52](https://cloud.githubusercontent.com/assets/1110663/11115846/a1610b1c-892e-11e5-816c-d73e3cce3164.png)

**Comment by MATsxm** [comment]
As this one is specific to the Bug Squad, @roland-d or @zero-24 could you take a look please?

**Comment by roland-d** [comment]
Put this person on the Honor Roll :) Can't delete anybody :P

**Comment by MATsxm** [comment]
Thanks @roland-d 
Hope then @sanderpotjer or other will take a look at it.
