### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by JPratt314** [joomla/joomla-websites#1751]
Please describe the problem or your issue

**Comment by JPratt314** [comment]
I can not get into Joomla with my email and password . It says it does not recognize my email .  Now I have it bookmarked and I can get into the control panel . When I go into the users menu all my information is there and it is the same that I am trying to use to get in . This has been going on for months now .

**Comment by Hackwar** [comment]
This is the issue tracker for the websites of the Joomla organisation. For general support, please go to the Joomla forum https://forum.joomla.org However, generally you would have set a username and a password, your email adress is not your username.

**Comment by JPratt314** [comment]
I know my username , my password and my email address . However Joomla does not recognize my email address . I can get into the control panel from the back end however I cannot go into my site from the front end . I have connected multiple people for help and everyone just sends me to another site . I have tried all these things and they do not work .

**Comment by ooffick** [comment]
Are you trying to login to your own Joomla site or to https://forum.joomla.org?

Kind regards
Olaf

**Comment by JPratt314** [comment]
I cannot log into anything because Joomla says that my username and my password does not match and I can’t apply for another password because they say joomla does not recognize my email .

**Comment by Hackwar** [comment]
Again: Where are you trying to login? Your website is NOT connected to our forum. If you created a user account when installing Joomla, that does not create an account with our forum, our extension directory or any other Joomla site out there. Similar to how you creating an account with your hoster does not create an account with Amazon or Google at the same time.

**Comment by JPratt314** [comment]
Now my website was complied on Joomla in 2016 . I have been able to get in before . I can go to the backend and go to the control panel and in the users -manage I am able to get in . My information is listed there .I tried entering another email address and users name and password but that will not work either . 

I have reached out to several people they send me to another site . I have read and did all these things .  No one seems to really know what to tell me .

**Comment by Hackwar** [comment]
So far you haven't even been able to state clearly where you expect to be able to login and as I wrote before: This is the issue tracker for the infrastructure of the Joomla websites, not a general Joomla enduser support forum. I don't have any access to any of your information. You have to register an account at forum.joomla.org and can ask your question there.
