### ISSUE TITLE
[forum.joomla.org] HTML error in footer

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-websites#1752]
The social icon block contains an HTML error. There is a space missing between the rel="" and class="" attribute.

**Comment by ooffick** [comment]
Thanks, it looks like that is a global issue. I will find out who can fix this.

**Comment by Hackwar** [comment]
thanks

**Comment by SuryanarayanaKrishnan** [comment]
can I try and fix this?

**Comment by HLeithner** [comment]
This should be fixed now.
