### ISSUE TITLE
[jhelp] 404 - RuntimeException  JHELP_MENUS_MENU_ITEM_MENU_ITEM_CONTAINER

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla/joomla-websites#1755]
[Please describe the problem or your issue]

keyref=Help310:JHELP_MENUS_MENU_ITEM_MENU_ITEM_CONTAINER
Error fetching page from MediaWiki API: The page you specified doesn't exist.

**Comment by Franzwohlkoenig** [comment]
Can anyone of the https://volunteers.joomla.org/teams/documentation-working-group please have a look?

**Comment by hvdmeer** [comment]
@wilsonge ?

**Comment by Franzwohlkoenig** [comment]
Closing as J3 now only get security updates.
