### ISSUE TITLE
Downloading previous versions of joomla from the site does not work

### ISSUE THREAD

**Issue by barrel10830** [joomla/joomla-websites#1756]
Hello. I can't download Joomla from your official site https://downloads.joomla.org/. The latest version 4.1.2 downloads, but the previous version does not. It just throws an error when the download button is clicked. It also does not download languages. I need Russian language but it is not supported in version 4.1.2. And the version with support for the Russian language 4.1.1 does not download. If you download version 4.1.1 from another site, then it does not download the language from joomla itself either. What could be the problem?

**Comment by pe7er** [comment]
I tried to replicate your issue (using Google Chrome and from my location in The Netherlands) but cannot reproduce your issue. 

**Joomla versions**
At https://downloads.joomla.org/cms/joomla4/ under Joomla! 4.1.1 I can choose "view" files, which links to https://downloads.joomla.org/cms/joomla4/4-1-1 I am able to download Joomla 4.1.1.

**Russian Language Pack**
At https://downloads.joomla.org/language-packs/translations-joomla4 I see "Russian Translation for Joomla 4.x." 
The "Download Language Pack" links to a page: 
https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-russian/4-1-1-1
![Screenshot from 2022-04-25 17-19-54](https://user-images.githubusercontent.com/1217850/165120292-06a790e6-f2d5-48e2-af2a-57cb78f954b8.png)
I am able to download the Russian Language Pack "Version 4.1.1.1" (Released on Tuesday, 29 March 2022).
The download link that I see in my browser: https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-russian/4-1-1-1/ru-ru_joomla_lang_full_4-1-1v1-zip?format=zip

Are you able to download the Russian Language Pack from that direct URL?

Alternatively, could you also try installing the language directly from the Joomla 4 back-end?
(System > "Install" > Languages > [install] Russian | ru-RU | 4.1.1.1)

**Comment by barrel10830** [comment]
Unfortunately, none of the links work. Joomla 4.1.1 cannot be downloaded from this link https://downloads.joomla.org/cms/joomla4/4-1-1. Also, the language pack cannot be downloaded from this link https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-russian/4-1-1-1/ru-ru_joomla_lang_full_4-1-1v1-zip? format=zip. I tried to download from different browsers, from different Internet providers, from different computers, from the phone - it does not download. Also tried different VPN - does not download. It seems to me that there is some kind of ban on downloading from Russia.
![01](https://user-images.githubusercontent.com/104374022/165145537-51d87e3e-bc37-4320-853a-cf2366c4219a.jpg)
![02](https://user-images.githubusercontent.com/104374022/165145552-c2c7c29e-91de-4aa0-b672-99992c5d50fc.jpg)

**Comment by barrel10830** [comment]
Also does not download the language from joomla itself.

**Comment by zero-24** [comment]
Please try: https://github.com/joomla/joomla-cms/releases/download/4.1.2/Joomla_4.1.2-Stable-Update_Package.zip or https://update.joomla.org/releases/4.1.2/Joomla_4.1.2-Stable-Update_Package.zip that are alternative mirrors hosted on different servers. And please always use the latest version of Joomla. You can still install an older language pack on it without any problems.

**Comment by barrel10830** [comment]
Yes, the latest version is downloading, both on the first link and on the second. But the language is not downloaded from the link https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-russian/4-1-1-1/ru-ru_joomla_lang_full_4-1-1v1-zip. And from the program itself also does not download. Can someone throw off an alternative link to the Russian language? Or email me and I'll install it manually.

**Comment by HLeithner** [comment]
The download page redirects to amazon S3 storage. it shouldn't be any different between current and older versions...

here the requested file:
[ru-RU_joomla_lang_full_4.1.1v1.zip](https://github.com/joomla/joomla-websites/files/8557204/ru-RU_joomla_lang_full_4.1.1v1.zip)

**Comment by PhilETaylor** [comment]
> It seems to me that there is some kind of ban on downloading from Russia.

Possibly related to sanctions on Russia for the war in Ukraine. Also the Russian Government is blocking access to some services, including some Amazon services, in retaliation for sanctions.

**Comment by barrel10830** [comment]
Yes, perhaps because of the sanctions. Thanks for the working link to Russian, I think the topic can be closed.

**Comment by barrel10830** [comment]
> The download page redirects to amazon S3 storage. it shouldn't be any different between current and older versions...
> 
> here the requested file: [ru-RU_joomla_lang_full_4.1.1v1.zip](https://github.com/joomla/joomla-websites/files/8557204/ru-RU_joomla_lang_full_4.1.1v1.zip)

Please tell me how to find the Russian language for joomla on GitHub? The link that you wrote from it downloads perfectly, I see a new version has been released on the official website, but it does not download it there.
