### ISSUE TITLE
Joomla Login Problems on Namesco

### ISSUE THREAD

**Issue by cjnotts1983** [joomla/joomla-websites#176]
I've recently installed Joomla on my Namesco domain using 1-click and I'm having problems logging in. Every time I try I get the message "Warning: Username and password do not match or you do not have an account yet."  Despite the fact that I'm using the username and password I created during the 1-click install. How do I get into my Joomla account to build my site?

**Comment by MAT978** [comment]
Hello,
this is the place to report issues that concern **ONLY** official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/
Thanks

**Comment by MAT978** [comment]
CLOSED - off topic
