### ISSUE TITLE
Download button doesn't start the download

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1760]
When you visit https://www.joomla.org/ and click on the Download button, the browser goes to https://downloads.joomla.org/

When you go to https://downloads.joomla.org/ and click on the Download button, again the browser goes to https://downloads.joomla.org/ (even when you are already on the Downloads site)

To align the button action with the label and the user expectation, it would be better to change the button to "Go To Downloads" or a similar idea.

**Comment by avanishkhursange** [comment]
assign this issue to me I'll solve this problem

**Comment by HLeithner** [comment]
That's the cdn header, I think this will be fixed/different with a new template closing this for now.
