### ISSUE TITLE
[jlaunch] User from country, ZAMBIA Unable to submit sign-up form for a domain.joomla.com when i enter my country and (+260) Phone number (Error Mismatch) 

### ISSUE THREAD

**Issue by mchama** [joomla/joomla-websites#1762]
Hello Joomla.org devs, 

I hope i'm reporting this issue on the right platform. <br/><br/> It seems i am not able to sign up for a free Joomla domain as its giving a validation error on my phone number (starting with country code of +260 for ZAMBIA) as not matching with my selected country ZAMBIA. <br/><br/> Please align the form so i can do so as im new to the Joomla CMS and hope to learn more.

**Comment by Niteshmaurya** [comment]
@mchama I think this repository is only for joomla website issues so kindly post your issue in joomla/cms.

**Comment by HLeithner** [comment]
@Pawel-Panek I think that's also a problem for cloudaccess

**Comment by Pawel-Panek** [comment]
@HLeithner we've confirmed the issue. We have an internal task posted to get it fixed. I'll update here once it's done.

**Comment by Pawel-Panek** [comment]
Actually this is not an issue. There is one more additional check that this user was failing on. In case something like this happens again please contact cloudaccess.net via sales chat and we will get you through the account validation.

**Comment by HLeithner** [comment]
thanks for the info, I'm closing this.
