### ISSUE TITLE
the email to confirm my request for a free joomla site on joomla.com does not get to my mailbox. I did not receive it for days. Could you help me?[jlaunch] 

### ISSUE THREAD

**Issue by monicaaraujopasb** [joomla/joomla-websites#1763]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by FirdausJaimi** [comment]
Here are a few steps you can try to resolve this issue:

Check your spam/junk folder: sometimes confirmation emails can get filtered into these folders by mistake.

Ensure the email address you used to sign up for the Joomla account is correct and active.

Try to request the confirmation email again from Joomla.com, or contact their support team to ask if they can resend the email to you.

If none of these steps help, the problem might be with Joomla's servers or email delivery system. In that case, the support team would be your best resource to get this resolved.

**Comment by HLeithner** [comment]
@monicaaraujopasb sorry that this ticket get unnoticed, if you still have a problem please comment here again and I will forward it to the right person. For now I'm closing this ticket.
