### ISSUE TITLE
Permanent link to latest download?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1765]
We have a permanent link to the latest release page https://downloads.joomla.org/latest but not to the latest release package.

Would it be possible to create something like downloads.joomla.org/latest/latest.tar.gz

This would be really helpful for anyone wanting to automate new installs etc

@HLeithner

**Comment by zero-24** [comment]
What should be latest (to be used by automated tools) with the release of 3.10.0 and 4.0.0 beeing released at the same time (similiar will happen with 5 and whatever will be the current 4.x release at that time)

**Comment by brianteeman** [comment]
ok so make it latest3.tar.gz and latest4.tar.gz

next block?

**Comment by HLeithner** [comment]
We talked about this somewhere and decided to changed latest starting with 4.2 because it was missed till now. @roland-d @fancyFranci please not this to your release process of 4.2.0 thanks

**Comment by brianteeman** [comment]
can we not start it now. Would really help

**Comment by zero-24** [comment]
> We talked about this somewhere and decided to changed latest starting with 4.2 because it was missed till now. @roland-d @fancyFranci please not this to your release process of 4.2.0 thanks

Right now the latest URL points to both. I dont think we have to change anything here with 4.2 but Brian asked for an latest.tar.gz and I asked which version it should point to as any major version change will mostlickly break automated scripts. So it might make sense to do a latest3 latest4 latest5 but when do we remove latest3 with EOS? Later? Eariler?

**Comment by HLeithner** [comment]
sorry I mixed this with joomla.org/latest

**Comment by HLeithner** [comment]
@brianteeman so we have a link to the latest release package it's https://joomla.org/latest and this is 3 for the moment and have to be changed to 4.2 when it's released. 
Here is the PR todo this https://github.com/joomla/joomla.org/pull/82

A long time ago I rewrote the latest.php script to support .tar.gz and other formats, but never created a PR.

I'm closing this.

**Comment by brianteeman** [comment]
Thanks @HLeithner is this link documented/published anywhere?

**Comment by HLeithner** [comment]
tbh I have no idea, that's long before my time. But we should document this or make it even more useful (as you wrote, extending downloads.joomla.org/latest with .tar.gz and other formats and maybe also extend it to support /latest-<majorversion>.tar.gz

I would be happy with it if we find someone doing it, I sadly don't have the time at the moment for this.

**Comment by brianteeman** [comment]
perhaps if you re-open this someone will see it and do the script.

**Comment by HLeithner** [comment]
if someone writes a specification what's needed then we can open this or a new one. Just open it without plan doesn't help I think. But could be done of course.
