### ISSUE TITLE
https://www.joomla.org/4/en/[j3] 

### ISSUE THREAD

**Issue by sanskruti2728** [joomla/joomla-websites#1769]
Design :

https://www.joomla.org/4/en/ 
In this website there is UI / frontend issue is there in Joomla4You component of page . Image used in that should be small in size because there is important things which are written below that is not highlighting .but img is quite big in size. So only img is highlighting not the text /information of below .another issue with Image  is attached with drive link .please check.
[](https://drive.google.com/file/d/1Co3MV6QHWkHUAoDb6lBpFuBnfBAvCLy4/view?usp=sharing)
Thank you
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Hackwar** [comment]
This is the bugtracker for the websites of the Joomla! organisation, not for the CMS software and especially not a support forum. If you need support, please go to https://forum.joomla.org. If you think you found a bug, open a ticket on https://github.com/joomla/joomla-cms/issues
