### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by thegroovycloset** [joomla/joomla-websites#1772]
Our business closed so we no longer need her website I managed to take the site off-line but I would like the account removed from joomla if that is possible thank you

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
