### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by fredsotier** [joomla/joomla-websites#1773]
Bonjour,
Je vous informe qu'il existe un gros bug dans joomla,
un article dépublié s'affiche en ligne... Le public voit mes articles dépubliés, j'ai été choqué. Merci de me faire un retour pour savoir ce qui se passe. Merci

Hello,
I inform you that there is a big bug in joomla,
an unpublished article appears online... The public sees my unpublished articles, I was shocked. Please get back to me to find out what's going on. Thanks

**Comment by fredsotier** [comment]
Je vous informe qu'il existe un gros bug dans joomla,
un article dépublié s'affiche en ligne... Le public voit mes articles dépubliés, j'ai été choqué. Merci de me faire un retour pour savoir ce qui se passe. Merci

I inform you that there is a big bug in joomla,
an unpublished article appears online... The public sees my unpublished articles, I was shocked. Please get back to me to find out what's going on. Thanks

**Comment by fredsotier** [comment]
Je vous informe qu'il existe un gros bug dans joomla 4,
un article dépublié s'affiche en ligne... Le public voit mes articles dépubliés, j'ai été choqué. Merci de me faire un retour pour savoir ce qui se passe. Merci

I inform you that there is a big bug in joomla 4,
an unpublished article appears online... The public sees my unpublished articles, I was shocked. Please get back to me to find out what's going on. Thanks

**Comment by Hackwar** [comment]
This is the bugtracker for the websites of the Joomla! organisation, not for the CMS software and especially not a support forum. If you need support, please go to https://forum.joomla.org. If you think you found a bug, open a ticket on https://github.com/joomla/joomla-cms/issues
