### ISSUE TITLE
[japi] No page for Joomla\Input\Input for Joomla 4 API, only Joomla\CMS\Input\Input (and Joomla\Input\Input for J3 API "only")

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-websites#1775]
If I open Joomla 4 API page about ```Joomla\CMS\Input\Input``` (https://api.joomla.org/cms-4/classes/Joomla-CMS-Input-Input.html) , there is deprecation mark ```5.0 Use Joomla\Input\Input instead``` . Also there is ```Joomla\Input\Input``` page for Joomla 3 [3.10] API (https://api.joomla.org/cms-3/classes/Joomla.Input.Input.html) [of course, without deprecation mark]. But there is no page for ```Joomla\Input\Input``` for Joomla 4 API (so, of course, open ...classes/Joomla-Input-Input.html get 404).

Am I wrong?

**Comment by Hackwar** [comment]
That class is described in the framework 2 API documentation. But yes, we should consider adding that to the CMS API docs as well...

**Comment by Hackwar** [comment]
I've been looking into this further and while I would like to have phpdocumentor crosslink to the framework package, that doesn't really seem to be possible except when we duplicate the documentation in both the framework and the cms docs. I doubt that we can fix this.

**Comment by Hackwar** [comment]
I'm sorry, but I'm going to close this as WONTFIX.
