### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Jijbentgespot** [joomla/joomla-websites#1778]
After the update to 4.1.4. we have issues on our RSS feed we using to send to text-tv
On the website the images are displayed but on the RSS feed random the images are missing.

When i check my RSS reader i see the URL is not displayed of the image
![rss feed error](https://user-images.githubusercontent.com/107569530/173872138-d1953129-0adc-46b3-81d5-568a597902e3.jpg)

On the website everything is okay. 
when i check the feed the img urls are missing or displayed at random. 
![error 2](https://user-images.githubusercontent.com/107569530/173872623-fa923b30-e271-4168-b5c5-57e14401a756.jpg)

Website details:
core Joomla 4.1.4
Framework T4

**Comment by Hackwar** [comment]
This is the bugtracker for the websites of the Joomla! organisation, not for the CMS software and especially not a support forum. If you need support, please go to https://forum.joomla.org. If you think you found a bug, open a ticket on https://github.com/joomla/joomla-cms/issues
