### ISSUE TITLE
404 - RuntimeException

### ISSUE THREAD

**Issue by muddauber** [joomla/joomla-websites#1779]
404 - RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist.

License: [Joomla! Electronic Documentation License](https://www.blogger.com/blog/post/edit/12054272/654301376402485996?hl=en#)
Copyright © 2022 [Open Source Matters, Inc.](https://www.blogger.com/blog/post/edit/12054272/654301376402485996?hl=en#) All rights reserved.
[Report an Issue](https://www.blogger.com/blog/post/edit/12054272/654301376402485996?hl=en#) with the help screense describe the problem or your issue

**Comment by muddauber** [comment]
After backing up my system, I attempted to upgrade.
Unable to update Joomla 4.1.2 to 4.1.4 Get the following error message: Server Error Joomla Update encountered a server error when applying the update to your site.

 Your site may not have been upgraded completely to the new Joomla version. and
: 404 - RuntimeException Error fetching page from MediaWiki API:

The page you specified doesn't exist. License: Joomla! Electronic Documentation License Copyright © 2022 Open Source Matters, Inc. All rights reserved. Report an Issue with the help screens I do not have mediawiki on this site, I have it on another site on a shared server.

**Comment by rricetester2** [comment]
I am seeing this too.
<img width="806" alt="Screen Shot 2022-09-06 at 12 46 08 PM" src="https://user-images.githubusercontent.com/42330291/188705134-0bbb05d9-03d8-4c88-8453-b3305c194e45.png">

**Comment by obuisard** [comment]
Thank you for reporting this issue.
It has been addressed in PR https://github.com/joomla/joomla-cms/pull/40670.
