### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Trosvik** [joomla/joomla-websites#178]
Hi, 

I'm not able to login to the admin page: http://vaasankorttelihuolto.fi/yritys/administrator.

I've figured out that the problem is caused by the disabled Joomla Authentication plugin (http://www.itoctopus.com/10-reasons-why-youre-not-able-to-login-to-your-joomla-website/comment-page-1#comment-38642). 

I have enabled the correct plugin: plg_authentication_joomla
While the ones that are not in use are disabled: plg_authentication_Idap and plg_authentication_gmail
However the latter ones were previously enabled. 

Even though the login should now work, I still can't access the backend page. What could the problem be?

There was a note on the help page I used:
Note: When this problem happens, and if other authentications methods (such as ldap) are enabled, then the login process will take a while before redirecting back to the login page (this is because Joomla will be checking the ldap directory, which usually takes some time).

Could this be the cause that I still can't login. In that case, how long is "some time", a few minutes, hours or days?

Many thanks in advance!

Best regards, 
Tintin Rosvik

**Comment by mikeveeckmans** [comment]
Hello,
this is the place to report issues that concern ONLY official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/ 
-https://docs.joomla.org/Main_Page 
-https://issues.joomla.org/ 

Thanks
