### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MelDrake1** [joomla/joomla-websites#1781]
Hello 

I have a website with you that I am trying to update. 

The website is melaniedrake-voicecoach.net

I have fully paid for this site but have requested a new log-in password. I also couldn't remember my user name. This information was supposed to be sent to my email drakemel16@gmail.com but hasn't come through.

Please can you help me get into my site.

Many thanks

**Comment by Hackwar** [comment]
This is the bugtracker for the joomla.org websites of the Joomla! CMS organisation. We don't manager your website, we just provide the software for free. Please either contact your website administrator or if you need support, go to your community forum at forum.joomla.org and ask for help there. Again, we aren't responsible for your website.
