### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by GODpleasers** [joomla/joomla-websites#1782]
Softaculous  app installer gives error when trying to install Joomla 3.9.11 into directory on server.

  T  The following errors were found :

    password_hash() expects parameter 2 to be long, string given

![soft j install error](https://user-images.githubusercontent.com/13956002/175719966-b7e25787-bbd2-4704-835b-3a1f05a2c414.JPG)

**Comment by Hackwar** [comment]
This is a problem of Softaculous, not of Joomla. Please contact the Softaculous people. Since this is the bugtracker for issues in the official Joomla websites, I'm closing this ticket here.
