### ISSUE TITLE
[jdown] Factually Incorrect Release Times (for the third time!) 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#1783]
just like https://github.com/joomla/joomla-websites/issues/1749 and https://github.com/joomla/joomla-websites/issues/1770 last weeks release also did not accurately set the release time 

As I have said before, details matter... history matters. 

As I have said before,  lessons are not being learnt from previous releases.

Is it too hard to put this on the release checklist so that it gets done correctly each time?

<img width="936" alt="Screen Shot 2022-06-30 at 12 49 24" src="https://user-images.githubusercontent.com/400092/176670142-7f2818ae-3c23-4285-9b01-69cb1ec3b527.png">

**Comment by PhilETaylor** [comment]
<img width="1067" alt="Screen Shot 2022-06-30 at 12 52 40" src="https://user-images.githubusercontent.com/400092/176670709-f4a2307f-6423-499c-a882-10b2af6da484.png">

**Comment by PhilETaylor** [comment]
<img width="1058" alt="Screen Shot 2022-06-30 at 12 53 00" src="https://user-images.githubusercontent.com/400092/176670764-a3467182-b3fa-4b07-ba4b-47f59146e067.png">
<img width="1250" alt="Screen Shot 2022-06-30 at 12 53 11" src="https://user-images.githubusercontent.com/400092/176670815-110fb152-80b1-4432-af62-bc6fc2d72968.png">
<img width="970" alt="Screen Shot 2022-06-30 at 12 53 22" src="https://user-images.githubusercontent.com/400092/176670853-ddb49386-35ff-426a-9d
<img width="818" alt="Screen Shot 2022-06-30 at 12 53 40" src="https://user-images.githubusercontent.com/400092/176670907-cb3b5bec-53eb
<img width="910" alt="Screen Shot 2022-06-30 at 12 53 46" src="
<img width="954" alt="Screen Shot 2022-06-30 at 12 54 05" src="https://user
<img width="889" alt="Screen Shot 2022-06-30 at 12 54 19" src="https://user-images.githubusercontent.com/400092/176671042-185f5700-8f06-4e17-9af8-47322b520764.png">
-images.githubusercontent.com/400092/176670979-9811ffb0-1fcd-42c6-ade6-e21304354463.png">
https://user-images.githubusercontent.com/400092/176670921-fa44d42c-a50f-4a43-8ce4-9664dbadc7c8.png">
-4cad-980b-9b3077f1f89d.png">
<img width="861" alt="Screen Shot 2022-06-30 at 12 53 55" src="https://user-images.githubusercontent.com/400092/176670952-83da9d9b-3ceb-4a4a-ab13-4877f9578c2a.png">

8c-f49c98bcb34b.png">
<img width="811" alt="Screen Shot 2022-06-30 at 12 53 32" src="https://user-images.githubusercontent.com/400092/176670884-c9bfb954-78c4-43de-ae14-8215a3482262.png">



etc etc etc etc etc etc etc etc etc etc etc etc etc etc etc

**Comment by PhilETaylor** [comment]
but if you check the db you will see the time HAS PREVIOUSLY been a part of the release and should be maintained as an accurate record 

There are people, and historians, that want that level of details, and if you check you will see that the project has always historically, until recently, provided it. 

To lose the release time now would be a great shame.

**Comment by PhilETaylor** [comment]
Every Joomla 2.5 and 1.5 release has a time.

Every Joomla 3 release had a time up until Joomla! 3.7.2... what changed then? 

Is it really too hard to add the time to the release checklist and update it?

Removing times from the release pages should not even be considered as an option.

**Comment by PhilETaylor** [comment]
I have no idea. I have never been involved with the software that runs the downloads site. 

If Akeeba.com is using its own ARS, then how come it has Times on its releases, and even timezones... E.g https://www.akeeba.com/download/akeeba-backup/8-1-8.html ??

**Comment by wilsonge** [comment]
Cause we're not on the latest ARS version. Support got removed for interfacing directly via S3 in the major release (v5) and since then there's a v6 and v8. We're still back on v4.

But yes this is an artifact of the old version of FOF (and will have been around since we stopped releasing on joomlacode).

**Comment by PhilETaylor** [comment]
Closed? So it’s too much for someone to run a single sql query per release in order to maintain data for history? Wow… might as well go and delete all the times then as they are factually incorrect and facts matter.
