### ISSUE TITLE
Error codes page link for the JED currently returns a blank page

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#1785]
This page - https://extensions.joomla.org/extension/directory-a-documentation/faq/freestyle-faqs/

...has a link "View Error Codes" that is currently returning a blank page for me at...

https://extensions.joomla.org/support/knowledgebase/item/unpublished-extensions-error-codes/

**Comment by HLeithner** [comment]
closing since it's a duplicate of https://github.com/joomla/joomla-websites/issues/1714
