### ISSUE TITLE
Listing in the Providers directory disappeared

### ISSUE THREAD

**Issue by MelsonMarketing** [joomla/joomla-websites#1789]
Hi,
I recognized, that my entry in the Providers directory obviously has been deleted.
https://community.joomla.org/service-providers-directory/listings/185-herzlich-nordisch-melson-marketing-media.html
I even can't login anymore.
On the other hand my entries in the showcase directory remain.
Just like this:
https://showcase.joomla.org/browse-sites/22954.html

It's annoying, as I received New customers via the showcase directory. As you can see, the link to the creator is dead.

**Comment by HLeithner** [comment]
You say it's solved by it self, I'm closing this.
