### ISSUE TITLE
[jforum]  Registration issue

### ISSUE THREAD

**Issue by minusplatinum** [joomla/joomla-websites#179]
I am trying to register with the forum so I can ask question about the issues I'm having with my joomla site.  It wont let me register because of the confirmation registration"Please drag the options to the correct list, to avoid automated registrations."  I sorted the options and it says incorrect.  its not very specific if they have to be ordered correctly, be one answer or multiple.  Ive been trying to register for 2 days and I'm at the point where I want to get rid of Joomla all togeather.

**Comment by mikeveeckmans** [comment]
Hi, 
Did you drag the ones that are incorrect to the right side ? 
Just tested it and it works fine... 
A tip : there are 2 incorrect answers , and 4 correct ones...

**Comment by mikeveeckmans** [comment]
No response, close please.

**Comment by Diana9624** [comment]
I couldn't register either.
[url=https://apkgreat.com/clash-of-clans-hack/] coc mod [/url]
