### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by c0d3-vp** [joomla/joomla-websites#1792]
I cannot find how to add the article to be featured on the home page, let alone below the actual content that is currently there.  Can someone please shed some light?  My work email is virginia@budbreak.com, and I'm trying to add a new article to https://srhsf.org/, below the welcome text with the slideshow.  Can someone please help me?

**Comment by c0d3-vp** [comment]
I can also zoom, etc, with whomever can help.

**Comment by Hackwar** [comment]
This is the bug tracker of the joomla project for its own websites and not a place for general help with your installation of joomla. For end-user help, please visit forum.joomla.org

**Comment by c0d3-vp** [comment]
You have issued a ban on my IP?  Yikes!

**Comment by Hackwar** [comment]
I have done no such thing. I just closed this issue, as this is the absolute wrong place to ask for help. You wouldn't go to a plumber if you had a broken arm. So I told you to go to the right place instead.
