### ISSUE TITLE
[joomla.org] 4.2 broken links and more

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1794]
https://www.joomla.org/announcements/release-news/

Click on the image - the link is broken and goes to https://www.joomla.org/component/content/category/36-project-release-news.html?Itemid=122

The title of the image is **Joomla 4.1.5 Stable**
The alt description of the image is **Joomla 4.2 Release Candidate 1 **

The same is true with the full article image.

Sure I don't need to explain the importance of fixing all this for SEO, Usability and Accessibility

@softforge

**Comment by brianteeman** [comment]
Just noticed the same problem with several other posts on that page

**Comment by softforge** [comment]
Thanks, Brian, I have fixed that one. The articles don't use the image tab but embed them so its in the code. When we move to J4 I would like to use the intro/main image tab as it is supposed to be and that will make it so much easier to spot. I will go back through and check the code of the others now
