### ISSUE TITLE
[idp] Google Tag Manager

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1795]
The GTM is incorrect on the identity portal and produces a 404

**Comment by HLeithner** [comment]
@roland-d if you have time after j4.2 release it would be great if you have a look

**Comment by roland-d** [comment]
@HLeithner What should the GTM be?

**Comment by brianteeman** [comment]
Just going through old open issues of mine to see if they can be closed or not. This one is still valid
