### ISSUE TITLE
[joomla.org] Website Admin Death

### ISSUE THREAD

**Issue by silasrea** [joomla/joomla-websites#1798]
Hello! I work with the Boy Scouts of America, Rainbow Council. One of our affiliated groups, Waupecan Lodge, runs its website through Joomla. We had one person who ran the website. Unfortunately, he passed away last week, and was the only one to have access to our website. How can we go about getting access to https://oa197.org/?

**Comment by zero-24** [comment]
Hi please check this docs page here: https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

Will close here as this is about issues with *.joomla.org Network of sites. When you need more details please check the joomla forum at: forum.joomla.org

**Comment by softforge** [comment]
If you still have problems do say. Often sorted this sort of issue in the London joomla user group
