### ISSUE TITLE
Joomla 4.x _content table import - Articles "No Matching Results"

### ISSUE THREAD

**Issue by dedillman** [joomla/joomla-websites#1799]
I am rebuilding a Joomla 4.x site from another 4.x site.  I have exported/imported all information, users, fields, etc.  The issue comes when I exported the _content table and imported into the new site using myphpadmin.  The new _content table shows 97 articles present.  However, within the new site administration, the >Content >Articles show "No Matching Results."

I have tested numerous times with same results.  I checked admin IDs and both match on both sites.  I have checked DBs and table integrity, all check.  On the frontend of the website, the articles display properly and the menu items resolve correctly.

At this time, I cannot locate nor edit articles in the backend.  Suggestions??

**Comment by drmenzelit** [comment]
This repository is for official websites of Joomla. If you have problems with your own website, please use the forum: forum.joomla.org
Exporting only the _content table is not enough, content is stored in several tables, assets, workflow, etc....
