### ISSUE TITLE
[JORG] Social share links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#18]
The social sharing links are not picking up the title of the page. They all just have the site name
Example from the Requirements page
> Joomla.org https://shar.es/1tfD2X via @sharethis

Example from the Downloads page
> Joomla.org https://shar.es/1tfD2X via @sharethis

**Comment by Hutchy68** [comment]
@Radek-Suski will have to look at the social plugin, who has access to the plugin? It is also causing SSL issues, see #20

**Comment by Radek-Suski** [comment]
I would be happy to help. The YOURLS has API. But I would need access to the used software

**Comment by Hutchy68** [comment]
Awesome, @sanderpotjer who has access to the social plugin on the j.org site. It has several issue that @Radek-Suski has said he will help fix.

**Comment by sanderpotjer** [comment]
I think we should replace that social sharing plugin with a proper one anyway. I would prefer one that doesn't load all the JS-files from all the social networks, and not using "via @sharethis". 

Not sure if anyone knows a JED-module for this type, otherwise I have a custom module that does it basically that way. What social-sharing buttons do we want:
- facebook
- twitter
- google plus (still relevant)
- ?

**Comment by brianteeman** [comment]
Way better if we can use something that doesnt require all the JS.

This one is great https://github.com/tmort/Socialite

On 5 August 2015 at 21:42, Sander Potjer <notifications@github.com> wrote:

> I think we should replace that social sharing plugin with a proper one
> anyway. I would prefer one that doesn't load all the JS-files from all the
> social networks, and not using "via @sharethis
> <https://github.com/sharethis>".
>
> Not sure if anyone knows a JED-module for this type, otherwise I have a
> custom module that does it basically that way. What social-sharing buttons
> do we want:
>
>    - facebook
>    - twitter
>    - google plus (still relevant)
>    - ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/18#issuecomment-128142039>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
This one is pretty awesome as well 
http://kurtnoble.com/labs/rrssb/

**Comment by MAT978** [comment]
+ :100: with the last one ;)
no more comment from me on this topic, I swear!

**Comment by Sandra97** [comment]
+ :100: for the last one

**Comment by jessicadunbar** [comment]
@Radek-Suski I pinged you about the yourls :+1:  you should have access to everything you need.

**Comment by Radek-Suski** [comment]
Gracias. Will try to do my best this weekend. Thanks :)

**Comment by Radek-Suski** [comment]
I checked the plugin we are using and I would probably need to hack it as it does not proved any customisation method. It would however means that it won't be updatable anymore. 
I am not sure if this is intended. Anyway if yes, I would need to get access to FTP/SSH.
Thoughts?

**Comment by MAT978** [comment]
@Radek-Suski 
**Should be** a temporary site... just Saying ;)
but @mbabker  will have a wiser opinion

**Comment by mbabker** [comment]
What are we customizing?

**Comment by Radek-Suski** [comment]
We want to add the joom.la shortener.

**Comment by mbabker** [comment]
I just looked at the code and now I want to go to the bar...

We're better off maintaining a "customized" version of that plugin than worrying about it being updatable.

**Comment by Radek-Suski** [comment]
> I just looked at the code and now I want to go to the bar...

Yeah. I know what do you mean. I don't see any trigger in the core I could use it for this. Maybe you have an idea

**Comment by mbabker** [comment]
The current plugin uses the `onContentAfterTitle` trigger to insert the share row.

**Comment by Radek-Suski** [comment]
So basically the idea would be to use the same trigger and after the URL has been added parse it and replace? A bit complicated but it could work.
Do we have some custom plugin I could use or do we need to create one?

**Comment by mbabker** [comment]
I would seriously just write a new plugin implementing the RRSSB HTML directly with our URL shortener versus writing a second plugin to run after this one to change the URLs.  Seriously, it'll be easier to manage in the long run.

**Comment by Radek-Suski** [comment]
I can do it but someone with design skills would need to help me ;)

**Comment by Sandra97** [comment]
You can't keep the current class?

**Comment by mbabker** [comment]
I'll send you the current plugin code in a few.  You deal with the URL
shortener and I'll clean up the rest.

**Comment by Radek-Suski** [comment]
Sounds perfect.

**Comment by mbabker** [comment]
I've got the revised plugin code at https://github.com/joomla-projects/plg_content_joomlarrssb

It just needs the CSS added from the main template (about to grab that) and the URL shortener function then it's good to go.

**Comment by Sandra97** [comment]
I'll add the CSS to the custom.css in a few minutes

**Comment by mbabker** [comment]
The stuff I found in the repo site's custom.css is in the new plugin at https://github.com/joomla-projects/plg_content_joomlarrssb/blob/master/media/css/joomla.css.  So that should just need to be double checked for accuracy.

**Comment by Sandra97** [comment]
That's it. Thanks. I'll check of course when it's online

**Comment by Radek-Suski** [comment]
Cool.I'll check it tomorrow. And add the necessary functionality. Thanks @mbabker and @Sandra97

**Comment by Radek-Suski** [comment]
Done https://github.com/joomla-projects/plg_content_joomlarrssb/pull/1

**Comment by Sandra97** [comment]
Thanks Radek!
I don't close the issue as a reminder to check everything is ok when it goes live.

**Comment by Radek-Suski** [comment]
Sure thing :-1:

**Comment by mbabker** [comment]
Pull request is merged into the plugin, updated plugin is on the repo site, proper URL is generated on the items I checked.  Good to go here, thanks all!
