### ISSUE TITLE
[jorg] Problem with Backend Menu on Windows Phone

### ISSUE THREAD

**Issue by Mika11** [joomla/joomla-websites#180]
Hey guys,

I have found a little issue in joomla.
I can´t access the second level of the joomla backend menu. That means that the links in the second level doesn´t work,
I can tip on components for example, but after that I can´t click a special compenent. If I do so the menu collapses.
By the way, I found this problem in every browser I used. And I tried a lot of them :)

**Comment by mikeveeckmans** [comment]
Isn't this related to joomla-cms ?

**Comment by MATsxm** [comment]
@Mika11 is this specific to an official *.joomla.org website or is it on a "private" site then an issue to report on: http://issues.joomla.org/ ?
Thanks

**Comment by Sandra97** [comment]
No answer in the last 6 months.
Closing this issue.
Re-open if needed.
