### ISSUE TITLE
404 on upgrade error[jhelp] 

### ISSUE THREAD

**Issue by rricetester2** [joomla/joomla-websites#1801]
During upgrade to Joomla 4.2.2, I encountered a failure. When I clicked on the "more information" button, I got the 404 error.
<img width="806" alt="Screen Shot 2022-09-06 at 12 46 08 PM" src="https://user-images.githubusercontent.com/42330291/188704535-cb75269e-8354-4a0a-8fcb-1e7569e0346b.png">

**Comment by rricetester2** [comment]
Duplicate of #1779

**Comment by alikon** [comment]
could be a server temporary hiccup

**Comment by rricetester2** [comment]
Appears that the doc is missing for all of Joomla 4.1
<img width="553" alt="Screen Shot 2022-09-06 at 1 04 16 PM" src="https://user-images.githubusercontent.com/42330291/188707954-a2e9663f-416f-4b21-b541-3d1abe527042.png">

**Comment by rricetester2** [comment]
One more pic...
<img width="841" alt="Screen Shot 2022-09-06 at 1 21 00 PM" src="https://user-images.githubusercontent.com/42330291/188710037-3955c4b3-00e6-455a-b62d-129a51d35483.png">
