### ISSUE TITLE
Joomla upgrade to 4.2.2 failed

### ISSUE THREAD

**Issue by PaulArvada** [joomla/joomla-websites#1805]
Got this: Upgrade - 404 - RuntimeException Error fetching page from MediaWiki API: The page you specified doesn't exist.

Broke my website

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

    https://forum.joomla.org/
    https://docs.joomla.org/Main_Page
    or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!
