### ISSUE TITLE
Trying to fix joomla fatel error

### ISSUE THREAD

**Issue by MemoBishara** [joomla/joomla-websites#1806]
I have an old joomla website it shows this message when i open it 
 Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /home1/ebalsoc/public_html/ar/libraries/vendor/joomla/registry/src/Format/Json.php on line 12
 trying to fix the fatel error 

 p.s: can't downgrade the php version

**Comment by chmst** [comment]
Sorry, this is the wrong place for your question. Please post on https://forum.joomla.org
