### ISSUE TITLE
[jlaunch] 

### ISSUE THREAD

**Issue by uto4ka101** [joomla/joomla-websites#1807]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Hello!
I registered to demo version
Confirmation Letter on e-mail (phdkasper@gmail.com) has not arrived

**Comment by HLeithner** [comment]
Hopefully that has already been solved... I'm closing this, since it's already several months since the issue has been opened.
