### ISSUE TITLE
[jforum] Upload failed

### ISSUE THREAD

**Issue by jli590** [joomla/joomla-websites#181]
I and apparently some other users on the forums, have noticed the error message ‘upload failed: the file contains html code". Appears randomly but very often when uploading image files to joomla. It’s really affecting my work flow, is there a work-around? Was there talk of a patch for this?

**Comment by mikeveeckmans** [comment]
Is this on forum.joomla.org??

**Comment by MATsxm** [comment]
More than 3 months without answer then Closed.
Please open again if needed
