### ISSUE TITLE
[jlaunch] Joomla version 4.1 ??

### ISSUE THREAD

**Issue by YGomiero** [joomla/joomla-websites#1812]
Only Joomla 4.1 or **4.2 Nightly Builds** ??
https://launch.joomla.org/

![joomlacom](https://user-images.githubusercontent.com/1731681/193484708-d5ec8eed-0516-43e7-ad6b-f8622cd2e7f1.png)

Joomla 4.2.3 is available since 09/27/22.

**Comment by HLeithner** [comment]
this is fixed already,, thanks for the report
