### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-websites#1816]
during a local WAMP stack update it failed and when I asked it for info about the error it threw a 404 
![image](https://user-images.githubusercontent.com/1850089/194475096-c996091a-36e0-4e4a-b7f5-2a70bdab4b67.png)
https://help.joomla.org/proxy?keyref=Help42:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en
This is in 4.2.2 trying to upgrade to 4.2.3

**Comment by max123kl** [comment]
Already reported in #1810
Issue closed
