### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jstudiosbeautycare** [joomla/joomla-websites#182]
I am unable to login my Joomla administration CMS site with correct login name and password. 

"500 - An error has occurred"

http://jstudios.com.sg/administrator/index.php

Please let me know what is the problem and solution. 

Thank you. 

Best Regards,

Arthur Ma

**Comment by brianteeman** [comment]
You have submitted this question i the wrong place. This is the place to report issues with the main joomla.org web sites. Please post your question at http://forum.joomla.org
