### ISSUE TITLE
[Community.joomla.org] Reoccuring Service Provider Add Entry page 

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-websites#1822]
Hey Guys,

URL : https://community.joomla.org/service-providers-directory/add-entry.html 

When you are not logged in and select Drop-down Service Provider, it keeps on regenerating the same page and adds inside the page, it is like infinite times as long as you keep selecting with drop down. 

Here is how it looks like : 
![add-entry- community joomla org](https://user-images.githubusercontent.com/839557/197028278-331535d7-a6c2-4c98-bc9f-98daa099ffbf.png)

![add-entry- community joomla org](https://user-images.githubusercontent.com/839557/197028177-f6b9df5e-51bf-4612-969c-bfe25cfd87a9.png)

**Comment by wilsonge** [comment]
This should be fixed with the extension update we’ve just done
