### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by gigarun** [joomla/joomla-websites#1825]
while updating joomla 4.2.3 to 4.2.4 : Server error
Joomla Update encountered a server error when applying the update to your site.
Your site may not have been upgraded completely to the new Joomla version.
Then click on button "Get help with this error" and open https://help.joomla.org/proxy?keyref=Help42:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en who is on 404 - RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist.

License: [Joomla! Electronic Documentation License](https://docs.joomla.org/JEDL)
Copyright © 2022 [Open Source Matters, Inc.](https://www.opensourcematters.org/) All rights reserved.
[Report an Issue](https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&body=Please%20describe%20the%20problem%20or%20your%20issue) with the help screens

**Comment by chmst** [comment]
Please post your question here: https://forum.joomla.org

**Comment by ceford** [comment]
This is a real bug! Line 58 of administrator/components/com_joomlaupdate/tmpl/update/default contains:

$helpUrl = Help::createUrl('JHELP_COMPONENTS_JOOMLA_UPDATE', false);

But that is not how Help URLs are created in Joomla 4. The actual page title should be used: Components_Joomla_Update
