### ISSUE TITLE
can´t update to joomla 4.2.4 from 4.2.3

### ISSUE THREAD

**Issue by oileboile** [joomla/joomla-websites#1827]
Hi,

the update to joomla 4.2.4 won´t work due to some failure. I am just a user of joomla for my punk band Blanker Hohn.

testspace http://barol.de/

Actual I test the update from version 3 to 4 on my private webspace.

Greeting Oile
![error-update_joomla_4 2 4](https://user-images.githubusercontent.com/117647162/200302981-68d43969-462b-4b4f-97ef-b245f3ff3dd8.jpg)

**Comment by pe7er** [comment]
Hi Oile,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!

**Comment by oileboile** [comment]
the link is created by the error page of joomla

**Comment by oileboile** [comment]
Thanks Peter!

 

Greeting Oile

 

Von: Peter Martin ***@***.***> 
Gesendet: Montag, 7. November 2022 12:57
An: joomla/joomla-websites ***@***.***>
Cc: oileboile ***@***.***>; Author ***@***.***>
Betreff: Re: [joomla/joomla-websites] can´t update to joomla 4.2.4 from 4.2.3 (Issue #1827)

 

Hi Oile,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with Joomla CMS, please go to:

https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/
For this reason, I'm closing your issue here.

Thanks!

**Comment by pe7er** [comment]
Sorry for closing your issue.
I rechecked your screen shot and it seems indeed like a bug with the help site.
I'm reopening this issue.

**Comment by obuisard** [comment]
I am closing the issue as it is fixed with PR https://github.com/joomla/joomla-cms/pull/40670.
Thank you for reporting the issue.
