### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by localjapan** [joomla/joomla-websites#183]
We have a problem browsing our website and also logging into the backend site.
When we try, 5500 or 404 error appears.

**Comment by MAT978** [comment]
Hi,
this is the place to report issues that concern ONLY official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/
Thanks
