### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by wayneGuru** [joomla/joomla-websites#1831]
Please describe the problem
404 - RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist.

License: [Joomla! Electronic Documentation License](https://docs.joomla.org/JEDL)
Copyright © 2022 [Open Source Matters, Inc.](https://www.opensourcematters.org/) All rights reserved.
[Report an Issue](https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&body=Please%20describe%20the%20problem%20or%20your%20issue) with the help screens or your issue

getting this error when trying to update Joomla

**Comment by cmbr** [comment]
It would be helpful to know the URL that fails if you can somehow recreate that scenario.

**Comment by HLeithner** [comment]
hmm no response since 20 days, I'm closing this @wayneGuru please reopen this issue with the url
