### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by LaurentBechir** [joomla/joomla-websites#1834]
Hello,

My pseudo on the forum is LaurentR2D2. I've changed my email from lrathle@gmail.com to laurent.rathle@free.fr, but I don't receive the activation mail.

Best regards

**Comment by pe7er** [comment]
Hi Laurent,
Your new address was indeed added to your forum account.

I did a "force reactivation" on your account.
Did you receive an email now?

**Comment by LaurentBechir** [comment]
No. There is perhaps a problem with my ISP ?

**Comment by pe7er** [comment]
Could be. 
I've just sent an email to your free.fr address. 
Could you please reply so I know that it works?

**Comment by pe7er** [comment]
I've had contact with the user and reactivated his forum account. 
The user is able to login again so I'm closing this issue...
