### ISSUE TITLE
[jlaunch] Joomla.com CloudPanel Plugin

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1836]
When accessing a joomla.com backend, the Cloud Panel Plugin is broken
<img width="932" alt="imagexml" src="https://user-images.githubusercontent.com/828371/204503057-ac20b5a5-deaa-483d-a8a5-8ed8b0d46273.png">

**Comment by Pawel-Panek** [comment]
Not sure what happened here. Must some incompatibility of our plugin with J! 4.2. This one will be fixed on our end.

**Comment by Pawel-Panek** [comment]
There was a problem with XML file for this plugin. It has been corrected and the plugin isn't reporting that error anymore.

**Comment by coolcat-creations** [comment]
Thank you!
