### ISSUE TITLE
[jlaunch] Joomla.com Outdated version

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1838]
Installing a site through joomla.com brings me an outdated version which is not possible to update
(Current Version is 4.2.5, Joomla.com brings 4.2.4)
<img width="1219" alt="image-noupdate" src="https://user-images.githubusercontent.com/828371/204503879-f5dc1dc0-2689-4dec-87a1-8e7b2663f1bb.png">
<img width="934" alt="image-424" src="https://user-images.githubusercontent.com/828371/204503895-8b26322a-6122-47bf-a13c-4a53838c8942.png">

**Comment by Pawel-Panek** [comment]
Looks like the Joomla package deployment didn't work correctly. Will check on it and fix it in case that's a problem on our end.

**Comment by Pawel-Panek** [comment]
I must have missed to update here. There was a similar issue reported with missing/incorrect Joomla Files component version which is the root cause of the problem reported here. That other one has been corrected thus this one can be closed too.

**Comment by HLeithner** [comment]
Thanks
