### ISSUE TITLE
[jlaunch] Joomla.com corrupted Database

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1839]
Installing a Joomla.com website brings me a corrupted database in the fresh install. this issue is not related to the update issue. fixing the database does not help updating Joomla
<img width="1223" alt="image-db" src="https://user-images.githubusercontent.com/828371/204504147-a596313e-72be-4f9c-b617-9540f32c0a18.png">

**Comment by Pawel-Panek** [comment]
That's a problem with installation procedure. We will get it fixed.

**Comment by brianteeman** [comment]
@Pawel-Panek you said the same thing months ago!!

**Comment by Pawel-Panek** [comment]
It will get better in 4.3. Thanks to the @Hackwar hard work Joomla will have a headless installer that will make the provisioning easier.

For this one, we'll check what's wrong and get it fixed.

**Comment by Pawel-Panek** [comment]
The missing manifest version and the bug with manifest being written to Folder field are now fixed. The sites that were provisioned with those bugs are now corrected too.

@coolcat-creations please check on that particular site from the initial post if the problem is resolved.

**Comment by coolcat-creations** [comment]
Issue is solved on my test site, thank you!
