### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by markju** [joomla/joomla-websites#184]
![capture](https://cloud.githubusercontent.com/assets/6368185/11525657/eaea9fde-98cc-11e5-89fc-faee97881f36.PNG)
Please describe the problem or your issue

Hey

Why is one of the templates called isis????
Shouldn't it be removed?

Thanks

**Comment by Radek-Suski** [comment]
No it shouldn't IMHO: https://en.wikipedia.org/wiki/Isis

**Comment by brianteeman** [comment]
This is not the correct place for this discussion. This tracker is for the
management of the joomla.org web sites not the software

On 2 December 2015 at 08:48, Radek Suski <notifications@github.com> wrote:

> No it shouldn't IMHO: https://en.wikipedia.org/wiki/Isis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/184#issuecomment-161223069>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by markju** [comment]
Ok.  Sorry for starting it in here guys  ;)
