### ISSUE TITLE
[jlaunch] Joomla.com after Install messages wrong version

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1840]
The After Install messages show messages from Joomla 3 and not the right ones. Which is very strange, what build is this?
<img width="1217" alt="image-stats" src="https://user-images.githubusercontent.com/828371/204504455-ca5e9284-0f16-4b38-88d0-f2cc48b0b619.png">

**Comment by brianteeman** [comment]
Check again on a clean joomla install locally. These are the correct post installation messages in joomla 4. Nothing wrong with joomla.com this time

**Comment by coolcat-creations** [comment]
Would you see it as Joomla issue then or is this made on purpose like that? Aren't the Joomla 4 messages missing then?

**Comment by brianteeman** [comment]
There is no difference in the post installation messages on joomla.com and the post installation messages in the current install

**Comment by coolcat-creations** [comment]
> There is no difference in the post installation messages on joomla.com and the post installation messages in the current install

ok understood but where are the Joomla 4 after install messages gone?

**Comment by brianteeman** [comment]
I have no idea what messages you are referring to

**Comment by coolcat-creations** [comment]
Aren't those missing?
![Bildschirmfoto 2022-12-06 um 11 27 02](https://user-images.githubusercontent.com/828371/205886519-46de3586-f069-4b5b-a9a1-08120051b5e6.png)

**Comment by brianteeman** [comment]
If you think they should be displayed then please open an issue on joomla-cms

**Comment by coolcat-creations** [comment]
ok
