### ISSUE TITLE
[Community.joomla.org] e-mail has relative link

### ISSUE THREAD

**Issue by superknutsel** [joomla/joomla-websites#1843]
I received an e-mail telling me that my listing in the Service Providers is about to expire.
In this e-mail there is a link to "My Entrie" but it's a relative link without the domain.
Like this : http://index.php/?option=com_rsdirectory&view=myentries&Itemid=xxxx

Would be great if someone can add the domain here.

**Comment by HLeithner** [comment]
should already work thanks for the report
