### ISSUE TITLE
[jcomm] Service Providers Directory

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1844]
1. I received notification today 5.12.23 that my entry in the service provider directory will expire 6.12.23 - a little more than 24 hours would be nice
2. The email says to click on the link in the email to "my entries" but the email does not contain the domain name ![image](https://user-images.githubusercontent.com/1296369/205596820-0a0c97f3-365d-4186-a0fb-76df2bcaef2f.png
3. The email says "To request another term of publication" but there is nothing on the page that I could see that does that. Only the ability to edit/update the entry
4. As soon as the entry is updated it is immediately unpublished so instead of it expiring on the 6th it has now in effect expired on the 5th

**Comment by HLeithner** [comment]
> 1. I received notification today 5.12.23 that my entry in the service provider directory will expire 6.12.23 - a little more than 24 hours would be nice

We have 2022  ;-) but yep I received it also today and I changed it to one week

> 2. The email says to click on the link in the email to "my entries" but the email does not contain the domain name ![image](https://user-images.githubusercontent.com/1296369/205596820-0a0c97f3-365d-4186-a0fb-76df2bcaef2f.png

I hopefully fix this...

> 3. The email says "To request another term of publication" but there is nothing on the page that I could see that does that. Only the ability to edit/update the entry

Yep can't do anything about this atm, you can only edit and save it then the moderators get an email

> 4. As soon as the entry is updated it is immediately unpublished so instead of it expiring on the 6th it has now in effect expired on the 5th

As soon as you change anything (or better save your entry) your entry is unpublished and needs approval, not the best experience but that's how it works at the moment....

**Comment by brianteeman** [comment]
thanks for the speedy reply (and for spotting my own typo). Hopefully 3 and 4 can be added to a todo list

**Comment by HLeithner** [comment]
at least point 1 und 2 should be fixed now, 3 should be part of the redesign and 4 should be keeped in mind for the future of RS!Directory, I'm closing this for now (mainly because 3 und 4 a logical even without issue :-()
