### ISSUE TITLE
[jlaunch] Outdated Screenshots

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1845]
<img width="563" alt="grafik" src="https://user-images.githubusercontent.com/828371/205691392-a3515fb7-2f80-438a-bb7b-3b92ad2e01d9.png">

Can you change the screenshot with new Joomla 4 screens? 
Thank you!

**Comment by HLeithner** [comment]
@Pawel-Panek maybe also something for you

**Comment by dereksca** [comment]
Thank you Elisa, this will be fixed soon

**Comment by Pawel-Panek** [comment]
'What is Joomla?' pictures were updated on Dec 8th. I think we can close this one.

**Comment by coolcat-creations** [comment]
Thank you
