### ISSUE TITLE
[jlaunch] Wrong sentence / grammar 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1847]
This sentence is wrong:

<img width="678" alt="grafik" src="https://user-images.githubusercontent.com/828371/205692343-600ae2db-2963-4e56-9de1-436a4b3b3435.png">

The correct sentence would be:

“How does it work?”

**Comment by Sumit9953** [comment]
Can I work on this issue

**Comment by coolcat-creations** [comment]
@Pawel-Panek

**Comment by brianteeman** [comment]
Technically the grammar is wrong BUT things exactly like this are often seen in headlines.

https://www.google.com/search?q=%22how+it+works%22&newwindow=1&sxsrf=ALiCzsZrWiewfDGrO0urw0JryiPmUQjNgA:1670316434387&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj_s-_NzeT7AhUyQEEAHSRXAdQQ_AUoAnoECAEQBA&biw=1920&bih=929&dpr=1

**Comment by Pawel-Panek** [comment]
Right, please tell us what should it be and we will get it corrected.
I believe the phrase 'How it works?' is common speech and the question mark is in fact optional. Anyways, please work out a consensus and we will adjust the content.

**Comment by dereksca** [comment]
@Pawel-Panek it should be "How does it work?" if it's a question. "How it works" as a statement as @coolcat-creations suggested is AFAIK fine too.

**Comment by Pawel-Panek** [comment]
Updated. It's "How does it work?" now.

**Comment by coolcat-creations** [comment]
Thank you!
