### ISSUE TITLE
[josm] Change from Glip to Mattermost in all relavent places.

### ISSUE THREAD

**Issue by Llewellynvdm** [joomla/joomla-websites#1849]
There are a number of references to Glip, that would need to be converted to Mattermost.

The first page that we can look at is https://www.opensourcematters.org/organisation/directors/policies/296-team-leader-responsibilities-policy.html There may be more, but I noticed these recently.

Let me know if I can help with updating all these... since writing a SQL update script will be fairly simple to do.

**Comment by HLeithner** [comment]
Has been fix thanks for the report.
