### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by lucertola** [joomla/joomla-websites#1850]
Update to 4.2.6 fails.
Up to the previous version no problem.
Are you aware of this problem?
Thank you
![errore_aggiornamento_Joomla](https://user-images.githubusercontent.com/856444/207650172-9d61f3c4-a3a9-4c0b-b4f4-7367243c5952.jpg)
Giuseppe

**Comment by wilsonge** [comment]
Hello. This is the reporting area for issues with our websites. You need to report issues with the CMS at https://issues.joomla.org (or use https://github.com/joomla/joomla-cms). But we are not aware of any update issues at the moment.
