### ISSUE TITLE
[jorg] Add a feature to close drop-down menu on mobile devices.

### ISSUE THREAD

**Issue by Uniquevikash1** [joomla/joomla-websites#1852]
When  dropdown menu is opened, clicking the button doesn't cause it to close.
![WhatsApp Image 2022-12-17 at 7 37 12 PM](https://user-images.githubusercontent.com/96657674/208246281-085b6eff-4d6c-4532-906b-e301f690bc6b.jpeg)

**Comment by Niteshmaurya** [comment]
I want to work on this can I ?
please assign to me

**Comment by Niteshmaurya** [comment]
Can any one one suggest from which line I Can add the solution of this code because it has 750 lines of code

**Comment by Niteshmaurya** [comment]
how can I  find the no. of line of this issue which are in there

**Comment by Niteshmaurya** [comment]
I am Nitesh Maurya. A computer science undergrad. Currently I am at the mid of my second year at VIT Mumbai. I am new to open source contribution but I am well aware of C, C++, Java, Data Structure, HTML, CSS, Javascript. I would love to contribute in this open source organization, I decided many organization too and want to contribute in good first issue but I stuck into large code base of organizations.
please somebody help to figuring out What should I required learn more to solve this type of issue??

**Comment by itssiddhantjain** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by wilsonge** [comment]
We're slowly fixing this with a new template that we're shipping with Joomla 4 upgrades where this is fixed. We won't be looking to work further on the existing Joomla 3 template
