### ISSUE TITLE
[jhelp] Multi-factor Authentication

### ISSUE THREAD

**Issue by gertvan** [joomla/joomla-websites#1854]
The meaning of Multi-factor Authentication is not  documented onthe help page https://help.joomla.org/proxy?keyref=Help42:Users&lang=en
Seems to be an outdated page. Version 4.26

**Comment by itssiddhantjain** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by HLeithner** [comment]
You can find the source of this page at https://docs.joomla.org/Help4.x:Users/en it's a wiki you might want to update yourself. I'm closing this for now.
