### ISSUE TITLE
Website and Back End Editor are Down

### ISSUE THREAD

**Issue by rprovince** [joomla/joomla-websites#1855]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
- Hello, I am a teacher and website manager (barely) for Shelton High School in Shelton, Nebraska. Our website is a Joomla site, and over our Christmas break the website crashed. I tried to enter the website through the back end where I have always gone to store our images and all of the information we put into the website, and it seems to have crashed as well. We had the ESU look into the problem, and our tech supervisor worked with GoDaddy to look into the issue. All that they were able to come up with was it looked like an "Index file possibly deleted". Any help you could provide would be greatly appreciated. We are novice in the website world and need a lot of help getting this site back up and running. Thanks!

It could be useful to include an URL of evidence. 
- School Site - https://sheltonbulldogs.com/main/
- Back End Editor - https://sheltonbulldogs.com/main/administrator/index.php?option=com_menus&view=items&menutype=mainmenu

Please use a consistent title for your issue.

**Comment by drmenzelit** [comment]
@rprovince as the description you quoted in your post state, this place is to report problems with official websites of the Joomla community (joomla.org). You have a problem with your own website, please post the issue in the forum: forum.joomla.org and / or search for an specialist that can help you: https://community.joomla.org/service-providers-directory.html
