### ISSUE TITLE
[jlaunch] Austrian phone number verification doesn't work

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-websites#1856]
Hi @Pawel-Panek and @dereksca

I tried to create an joomla.com website today with my mobile phone number base in austria, but it didn't except the number.
![image](https://user-images.githubusercontent.com/1497730/210759152-9d2070ff-b2d4-4e38-b9cf-b90432f30004.png)

if you need my number please email me harald.leithner@community.joomla.org

**Comment by Pawel-Panek** [comment]
Please just tell us how many digits has your phone number?

**Comment by HLeithner** [comment]
0043 699 +8 digits
Country mobileprovider number

**Comment by HLeithner** [comment]
@Pawel-Panek still not working

**Comment by Pawel-Panek** [comment]
This one is in progress too.
