### ISSUE TITLE
[joomla.org]AdBlock warning should allow being closed, and decision remembered

### ISSUE THREAD

**Issue by isidrobaq** [joomla/joomla-websites#186]
I think the way the ad-blocking message has been implemented is a complete error. It's really annoying forcing people who have chosen to use one to browse any j.org page with a full width red bar fixed at the bottom of the screen. We're almost in 2016, and there are plenty of options to inform people about this without killing their user experience.

At the bare minimum, that warning should be allowed to be closed, and even better if that decision could be remembered somehow.

Some other ideas: 

http://www.makeuseof.com/tag/3-tactics-dealing-adblock-users-site/

Please note that a user who chooses not to display ads in his/her browser maybe is not a heartless egoistic parasite who is getting everything for free. I'm sure the script that detects I'm using an adblocker doesn't check how many hours I contribute to the project, or how much I've given back in the past. Please be sensitive about this, and don't mistreat users just because they chose having an ads free browsing experience. Thanks!

**Comment by aDaneInSpain** [comment]
I don't mind the notice, but I agree that it should be possible to close it. Maybe with a 30 day cookie to remember.

**Comment by phproberto** [comment]
And put a link there to redirect users to a page explaining the why and how people can disable adblock for joomla.org

**Comment by isidrobaq** [comment]
Here you can see a very good implementation of adblockers notification:

http://www.xataka.com/empresas-y-economia/lo-de-zuckerberg-no-es-caridad-sino-una-herramienta-de-inversion-libre-de-impuestos

They display a funny pic integrated in their content, asking you to please disable and prmpting you to click for instructions. Upon clicking, you get displayed clear instructions on how to disable AdBlock in their page, and once you do it, the image is replaced with another one that thanks you for disabling the AdBlocker.

**Comment by brianteeman** [comment]
Interesting idea

On 4 December 2015 at 13:11, Isidro Baquero <notifications@github.com>
wrote:

> Here you can see a very good implementation of adblockers notification:
>
>
> http://www.xataka.com/empresas-y-economia/lo-de-zuckerberg-no-es-caridad-sino-una-herramienta-de-inversion-libre-de-impuestos
>
> They display a funny pic integrated in their content, asking you to please
> disable and prmpting you to click for instructions. Upon clicking, you get
> displayed clear instructions on how to disable AdBlock in their page, and
> once you do it, the image is replaced with another one that thanks you for
> disabling the AdBlocker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/186#issuecomment-161963700>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
Anyone offering to help improve it then?

**Comment by poproar** [comment]
+1 @isidrobaq

**Comment by epatarroyo** [comment]
Here's another solution: https://github.com/owocki/adblock-to-bitcoin

**Comment by MATsxm** [comment]
@isidrobaq where are we about this one?
Thanks

**Comment by isidrobaq** [comment]
@MATsxm 
I'm not a dev, so I'm afraid I can only contribute ideas or, at the most, find code that looks good enough and put the link here :(.

**Comment by MATsxm** [comment]
This is already great and don't even count on me to code it :stuck_out_tongue_winking_eye:  :wink:

**Comment by MATsxm** [comment]
What is the status of this "issue"?

**Comment by mbabker** [comment]
If we're looking for a stateful alert, we need someone to contribute code
for it (that's a lot more JavaScript than I can sanely write).  Beyond
that, if there's going to be no action this can be closed out.

**Comment by isidrobaq** [comment]
Well, as I said I'm afraid I can't contribute code, unfortunately. Maybe someone with time and knowledge could get inspired by this WP plugin

https://github.com/wp-plugins/adblock-notify-by-bweb

I can understand that given our structure and resources, if nobody is going to contribute code to get this done, this should be closed. But please, let's try to find people to get something done. It's just horrible entering official pages of a project like Joomla and finding that intrusive, ugly, aggressive message. It doesn't match very well with the "100% backed by volunteers, no corporate support at all" spirit that makes it unique.

**Comment by C-Lodder** [comment]
Quite simple.

The current HTML markup for the alert is this:

```
<div id="adblock-msg" class="navbar navbar-fixed-bottom">
	<div class="navbar-inner">
		<i class="icon-warning"></i>
        We have detected that you are using an ad blocker. The Joomla! Project relies on revenue from these advertisements so please consider disabling the ad blocker for this domain.
	</div>
</div>
```

which need to be replayed with this:

```
<div id="adblock-msg" class="navbar navbar-fixed-bottom">
	<div class="alert alert-error navbar-inner">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
		<i class="icon-warning"></i>
        We have detected that you are using an ad blocker. The Joomla! Project relies on revenue from these advertisements so please consider disabling the ad blocker for this domain.
	</div>
</div>
```

Then some CSS additions:

```
.navbar .alert {
    position: relative;
    margin: 0;
    padding: 10px 50px !important;
    text-shadow: none;
}
.navbar .alert .close {
    opacity: .9;
    font-size: 30px;
    position: absolute;
    left: 20px;
    top: 10px;
    right: auto;
    text-shadow: none;
}
```

### No JS needed at all

**Comment by mbabker** [comment]
That works for closing it on the current page.  Not so much though if you want it to disappear for a longer period.

**Comment by C-Lodder** [comment]
shit, forgot about the cookie stuff. Gimme 5-10 mins

**Comment by C-Lodder** [comment]
Comment above updated with the JS required.

Here is a basic JSFiddle too: http://jsfiddle.net/rkythezw/

**Comment by mbabker** [comment]
Added this to the template repo, will be included in the next rollout.  As long as I did the JavaScript correctly, this should set the cookie for all `joomla.org` subdomains.  The updated script can be seen at https://gist.github.com/mbabker/64b20d68403b600eb39bd358a5ff4480

**Comment by C-Lodder** [comment]
`$('.subnav-wrapper')` seriously needs to be made a variable. The jQuery object is being created 9 times!
