### ISSUE TITLE
Grammatical errors in beginner docs - 'How To Use Content Tags in Joomla!'

### ISSUE THREAD

**Issue by Arya-Gupta** [joomla/joomla-websites#1862]
There are grammatical errors in: https://docs.joomla.org/J3.x:How_To_Use_Content_Tags_in_Joomla!

'meta data' is a single word.
Missing comma before 'and'.
Missing comma after 'Tags Manager'.
Missing article before 'positioning'.
'css' should be capitalized.

![image](https://user-images.githubusercontent.com/84087089/215330854-bf86c98e-c72e-4b8a-b41f-e417c5b0d788.png)

I can work on this issue. Can I be assigned?

**Comment by cmbr** [comment]
_Assignment_ is not required. Simply edit the article yourself. You'll find the Edit menu item under Actions in the upper right corner of the cited page.

**Comment by Arya-Gupta** [comment]
@cmbr Done!

**Comment by cmbr** [comment]
For more editing guidance, you are invited to review Joomla's [Words to Watch (W2W)](https://github.com/joomla/user-interface-text/blob/master/words2watch.md) page.

**Comment by max123kl** [comment]
The typos reported have been fixed by @Arya-Gupta.
