### ISSUE TITLE
4.2.7 and 4.2.8 are missing from 'Joomla 4.2 version history'

### ISSUE THREAD

**Issue by marcwrobel** [joomla/joomla-websites#1868]
The _Joomla 4.2 version history_ page (https://docs.joomla.org/Joomla_4.2_version_history) is missing releases https://github.com/joomla/joomla-cms/releases/tag/4.2.7 and https://github.com/joomla/joomla-cms/releases/tag/4.2.8.

**Comment by carlitorweb** [comment]
Updated, thank you for the notification
