### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#187]
©2005-2013 Open Source Matters, Inc. All rights reserved

Any chance of this being updated - its almost 2016

**Comment by MATsxm** [comment]
@pe7er
Can you help on this one? - Thanks

**Comment by pe7er** [comment]
Thanks! I've asked someone else with VPS access to the forum server to take care of it.

**Comment by MATsxm** [comment]
Thanks @pe7er 
I will leave it open :wink:

**Comment by ooffick** [comment]
I have changed this to 2016, let me know if that works for you.

**Comment by MATsxm** [comment]
everythings is :+1: 
Thanks for the help @pe7er & @ooffick 
Closed.
