### ISSUE TITLE
[jlaunch] ssl (again)

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1873]
Created a new account and a new site on launch.joomla.com

Once again every page I access gives an ssl error

![image](https://user-images.githubusercontent.com/1296369/222429583-e698cf68-2762-44de-adb7-5f09fa2a2a1c.png)

![image](https://user-images.githubusercontent.com/1296369/222429702-fd4ef589-880d-4de8-ab0e-88f7b057cccc.png)

**Comment by HLeithner** [comment]
@Pawel-Panek can you have a look here?

**Comment by HLeithner** [comment]
Seems the domain does no longer exists, I'm closing this.
