### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by easybreather** [joomla/joomla-websites#1874]
Please describe the problem or your issue
![image](https://user-images.githubusercontent.com/39053370/222672517-aafddad8-d2c9-4a40-bed9-b764ec328216.png)

During update of Joomla 4.2.8
![image](https://user-images.githubusercontent.com/39053370/222672645-039e5eed-a67c-4e73-8833-ca587aa6eda9.png)

**Comment by obuisard** [comment]
I am closing it as we have a PR that fixes the issue. https://github.com/joomla/joomla-cms/pull/40670.
Thank you for the reporting!
