### ISSUE TITLE
[joomla.org] - URGENT HELP REQUIRED

### ISSUE THREAD

**Issue by dialanerd** [joomla/joomla-websites#1878]
I'm the webmaster for dialanerd.nz, the very last change I made to the .htaccess file completely broke the website and I've lost ALL access to the https://dialanerd.nz/administrator/ which means I can't fix the issue.

Please help ASAP, either restore my access or if you are are to just replace the .htaccess with the default file or restore the previous version, I'll hope the fixes my access issue. Alternatively please send me instructions of how to fix the issue

**Comment by drmenzelit** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:

    https://forum.joomla.org/
    https://docs.joomla.org/Main_Page
    or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
