### ISSUE TITLE
Trying to create a new beginner website[jlaunch] 

### ISSUE THREAD

**Issue by IamBrowno** [joomla/joomla-websites#1880]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.
Trying to create a new beginner website - didn't get verification email - you tell me to contact support - you can only contact support with paid account - not very good.  How to lose a potential client...

**Comment by HLeithner** [comment]
please open a chat on cloudaccess.net and the cloudaccess team will validate your account.

Please also contact cloudaccess [support](mailto:support@cloudaccess.net) and provide your phone number there.

i'm closing this issue for now.
