### ISSUE TITLE
[joomla.org] %logintext% error

### ISSUE THREAD

**Issue by Hittitech** [joomla/joomla-websites#1881]
while clicking on the %logintext%  it is showing 400 bad request
https://www.joomla.org/4/en/ here is the link 
![Screenshot (6)](https://user-images.githubusercontent.com/87484115/229561520-d54beb94-8106-472a-8cb9-832721eeb415.png)
![Screenshot (7)](https://user-images.githubusercontent.com/87484115/229561533-00f5de19-7363-4409-8299-3e3d768306df.png)

**Comment by chmst** [comment]
confirmed

**Comment by Hittitech** [comment]
> confirmed
can i work on it ?

**Comment by TLWebdesign** [comment]
I've hidden it for now with some css but since this is pulled in from the CDN it should be fixed by someone that has access to that part.
