### ISSUE TITLE
hamburger(navbar) not working

### ISSUE THREAD

**Issue by Hittitech** [joomla/joomla-websites#1882]
https://www.joomla.org/4/en/
here is the link above
the hamburger icon is not working around width <=766px due to which header content cant be accessed 
if  wanted and confirmed  then I can make it work and  make it show all the header content when button is clicked

**Comment by Hittitech** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/87484115/229571797-a08f8ad9-daa1-4b25-bf4e-d43249b82b75.png)

**Comment by TLWebdesign** [comment]
This is fixed now.

**Comment by chmst** [comment]
Thanks, closing
