### ISSUE TITLE
[jdev] Broken Link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1883]
Probably a result of the joomla upgrade by @wilsonge but the link to the en-gb style guide is broken and takes you to the coding standards manual instead

**Comment by ceford** [comment]
> Probably a result of the joomla upgrade by @wilsonge but the link to the en-gb style guide is broken and takes you to the coding standards manual instead

It is not clear which link you are referring to. Most of the links in the left column of this page are broken:

https://developer.joomla.org/en-gb-user-interface-text-guidelines/introduction.html

**Comment by brianteeman** [comment]
I was referring to this link
![image](https://user-images.githubusercontent.com/1296369/229746785-41da1aa7-e356-471b-a349-41fb4dd0b7ee.png)


The link you accessed directly is suffering from the same problem

**Comment by brianteeman** [comment]
thanks

**Comment by HLeithner** [comment]
I will fix developer.joomla.org now and close the repo

**Comment by HLeithner** [comment]
thanks for your work
