### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by thommangooo** [joomla/joomla-websites#1884]
I reference this page very frequently, but there doesn't seem to be a version of it for joomla 4.  Is one forthcoming?  

https://docs.joomla.org/Selecting_data_using_JDatabase

**Comment by ot2sen** [comment]
Try have a look at the following two articles:
J4.x:Selecting data using JDatabase - Joomla! Documentation
<https://docs.joomla.org/J4.x:Selecting_data_using_JDatabase>
and
J4.x:Inserting Updating and Removing data using JDatabase - Joomla!
Documentation
<https://docs.joomla.org/J4.x:Inserting_Updating_and_Removing_data_using_JDatabase>

**Comment by thommangooo** [comment]
That’s great, thanks!
