### ISSUE TITLE
[jhelp] error 404

### ISSUE THREAD

**Issue by schmidnic** [joomla/joomla-websites#1887]
Please describe the problem or your issue

**Comment by pe7er** [comment]
Could you please give somewhat more information?

What did you do (and where) to trigger that 404 error?
What's the URL of the page that you tried to visit?

**Comment by schmidnic** [comment]
Hi Peter,I‘m actually testing the JoomLMS and the error occured by chance. I don‘t know what caused this failure. I‘m using the 30-days Trial of a demo joomla LMS.Thanks for your help in advanceNicole 😊Von meinem iPhone gesendetAm 18.04.2023 um 08:30 schrieb Peter Martin ***@***.***>:﻿
Could you please give somewhat more information?
What did you do (and where) to trigger that 404 error?
What's the URL of the page that you tried to visit?

**Comment by Hackwar** [comment]
This issue tracker is to report issues with the joomla.org website, not your own installation of the CMS joomla. If you need support, please go to forum.joomla.org or one of the many other support options out there.

In addition, if you are really talking about JoomLMS, I strongly advise against that extension.
