### ISSUE TITLE
[jcomm] j4.3 announcement email

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1889]
the template used by this site to send emauils through acymailing needs to be updated - 

it still says 2021
![image](https://user-images.githubusercontent.com/1296369/233080285-e49ec29f-c420-417e-8394-48c963626ab0.png)

It also says Joomla 4.0
![image](https://user-images.githubusercontent.com/1296369/233080732-db4ee299-87cb-4939-9546-23499492366c.png)

And to go to the launch.joomla.org site to try it out but they only offer 4.2

![image](https://user-images.githubusercontent.com/1296369/233080570-27bad338-62e8-4602-9493-b3fffbace45e.png)

**Comment by HLeithner** [comment]
j4.3 is available at the meantime, I'm closing this. @softforge can we add this to the marketing checklist for 4.4/5.0 please?
