### ISSUE TITLE
[demo] Multilingual Demo site

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#189]
The multilingual demo site is joomla 2.5 - doh

Is the site available somewhere and I will update it to J3

**Comment by MATsxm** [comment]
if you're talking about 
https://demo.joomla.org
note that it links to http://multilingual.demojoomla.com/ that (I may be wrong) was Mastering by JM (or at least it is a clone of JM's site).
Today, I guess SiteGround is in charge of it... not sure.

**Comment by brianteeman** [comment]
Yes I am talking about that site
As to who is in charge or why it hasnt been upgraded thats a topic not for here

So is JM site available somewhere so I can do an upgrade

**Comment by MATsxm** [comment]
I guess the best person to answer IS JM

**Comment by brianteeman** [comment]
Closing while I wait for J-M to decide if he will update it
