### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by shanegildnes** [joomla/joomla-websites#1890]
Hello, i completed the 2nd page of this tutorial (adding a view to the site)
https://docs.joomla.org/J4.x:Developing_an_MVC_Component/Adding_a_View_to_the_Site_Part

After following the instructions, when i try to access the site at:
<joomla>/index.php?option=com_helloworld&view=hello

I get an error

**500 Layout default not found.**

Call stack
#	Function	Location
1	()	JROOT/libraries/src/MVC/View/HtmlView.php:420
2	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:203
3	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/components/com_helloworld/src/View/Hello/HtmlView.php:31
4	JohnSmith\Component\HelloWorld\Site\View\Hello\HtmlView->display()	JROOT/components/com_helloworld/src/Controller/DisplayController.php:32
5	JohnSmith\Component\HelloWorld\Site\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:672
6	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
7	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:355
8	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:208
9	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:249
10	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:294
11	Joomla\CMS\Application\CMSApplication->execute()	JROOT/includes/app.php:61
12	require_once()	JROOT/index.php:32

**Comment by HLeithner** [comment]
did you created `site/tmpl/hello/default.php` ?

Beside that, this repository is issues with the joomla properties it self, if you need help developing joomla components, it's better to ask in the forum or on stackexchange. 

I'm closing this.

**Comment by shanegildnes** [comment]
Thank you Harald
On Apr 21, 2023 at 12:04 AM -0700, Harald Leithner ***@***.***>, wrote:

Closed #1890<https://github.com/joomla/joomla-websites/issues/1890> as completed.
