### ISSUE TITLE
[jlaunch] unable to get verification token to phone in Myanmar

### ISSUE THREAD

**Issue by Alex-phoo** [joomla/joomla-websites#1896]

**Comment by pe7er** [comment]
Are you trying to register a free Joomla website at https://launch.joomla.org/ ?
I'll change the topic of your ticket from "[joomla.org]" to "[jlaunch] unable to get verification token to phone in Myanmar".

The server is located in the USA and I don't know if launch.joomla.org is supported for your country.

In the mean time you could try to setup a Joomla website on a local computer using a local webserver like XAMPP.
For support on that please go to https://forum.joomla.org/

**Comment by Alex-phoo** [comment]
Yes, I am trying to register a free Joomla website at https://launch.joomla.org/ but I cannot so I try registering directly on https://ccp.cloudaccess.net/index.php?m=sms_center&mg-page=clientVerification
However, I get to create the account but had to deal with the verification code error which says "Cannot send verification token to your phone number, please contact support to get help." after clicking the "Resend" button.

**Comment by Pawel-Panek** [comment]
@Alex-phoo please open a chat on cloudaccess.net and our team will validate your account.

Please also contact our support@cloudaccess.net and provide your phone number there.

**Comment by HLeithner** [comment]
thanks @Pawel-Panek I'm closing this here
