### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by mbennett417** [joomla/joomla-websites#1897]
On version 4.3.1, trying to reinstall Joomla Core Files from the button on the Joomla updates component screen. Program halts with "Get Help" "Resume Update" "Restart Update" options. Get help goes to
https://help.joomla.org/proxy?keyref=Help43:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en
and shows a 404 - Runtime Exception

Resume and Restart don't work either, but this report is directed specifically to the help screen.

**Comment by ceford** [comment]
See: https://issues.joomla.org/tracker/joomla-cms/39769

**Comment by obuisard** [comment]
I am closing it as we have a PR that addresses the issue https://github.com/joomla/joomla-cms/pull/40670
