### ISSUE TITLE
[jlaunch] Sign up process incompatible for anyone travelling outside of home country

### ISSUE THREAD

**Issue by ajmas** [joomla/joomla-websites#1898]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

I am trying to create an account, so I can create a test website to explore the functionalities provided by Joomla. I am currently traveling outside of my home country and specifying my phone number and country displays an error:

<img width="562" alt="Screenshot 2023-05-31 at 19 14 25" src="https://github.com/joomla/joomla-websites/assets/682269/8ad3740d-862d-4bb9-9e5c-0b83a50c71bb">

Assuming the website is doing a phone number check on my IP address, I use a friend's local phone number. This works, but reveals the sign up process is not suitable for anyone who needs to continue working, while out of home country.

At the same time, we didn't get a text, so the usefulness of the phone number is questionable.

Further to this, the next step fails with "Something went wrong":

<img width="610" alt="Screenshot 2023-05-31 at 19 28 25" src="https://github.com/joomla/joomla-websites/assets/682269/28bbbf11-4229-498d-b077-071ca417c439">

The console shows errors around Google Tag Manager and bootstrap. I have attached the console output.

[console-output.txt](https://github.com/joomla/joomla-websites/files/11612467/console-output.txt)

Clicking "click here" shows no additional console messages or network activity.

Trying in Chrome 114.0.5735.35 on MacOS 13.3.1.

So turns out no account was created and trying the form submission process again shows:

  - phone number validation is purely front-end
  - no form data is actually sent to Joomla, beyond checking if email is valid and website is available

**Comment by HLeithner** [comment]
@Pawel-Panek can you have a look here please?
