### ISSUE TITLE
[jcomm] 403 issue after submitting a website to the showcase

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#19]
User reported a 403 error after submitting a website to the showcase site.

Reported back in June 13th 2015.

Following up to make sure it is fixed.

**Comment by SniperSister** [comment]
Fixed, apparently related to mod_security rules!

**Comment by pbwebdev** [comment]
Cool I'll start testing.

**Comment by MATsxm** [comment]
Closed
reopen if needed
