### ISSUE TITLE
Cloud Access - wtf

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#190]
https://www.joomla.org/about-joomla/getting-started.html

The text of the entire Test Out the Online Demo section is no longer correct as it is for the old joomla 2.5 cloud access demo (*hasn't been for over a year*)

**Comment by mikeveeckmans** [comment]
Confirmed.
Can we assign this to someone please.

**Comment by mikeveeckmans** [comment]
@MATsxm : as i no longer have access to the backend , i can't do this...

**Comment by MATsxm** [comment]
@mikeveeckmans Just send the text,
Sure @Sandra97 will be sooooo happy to integrate it ;)

**Comment by mikeveeckmans** [comment]
You can really experience the power of Joomla! using our online demo at demo.joomla.org. You'll quickly discover how easy it is to create and manage content as well as learn your way around the Joomla administrator interface.

You can either have a 90-day free Joomla! demo account or do a quick test drive on a 90-minute install. (After 90 minutes it will reset itself) Both demo systems can be found at demo.joomla.org

All user accounts are given Super Administrator access and can perform all functions except those that could be abused. Feel free to use the new demo resource and to share it with others interested in exploring Joomla's capabilities.

For more details about the operation of the demo site, visit demo.joomla.org.

**Comment by mikeveeckmans** [comment]
@brianteeman could you proof the rewrite ?

**Comment by brianteeman** [comment]
I would be tempted to break it into two separate sections
90 minute demo
90 day demo

On 11 December 2015 at 14:33, Mike Veeckmans <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> could you proof the rewrite
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/190#issuecomment-163949597>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mikeveeckmans** [comment]
You can really experience the power of Joomla! using our online demo at demo.joomla.org. You'll quickly discover how easy it is to create and manage content as well as learn your way around the Joomla administrator interface.

<h2>90-day free demo</h2>
You will have 90 days to explore Joomla! Build a complete website for yourself or your company, absolutely free of charge. If you want to keep your website after the demo period is over, you can easily do so by moving it to a standard hosting account.

<h2>90-minutes test drive</h2>
Not sure yet about the 90-day demo? Take a one-time quick Joomla! ride instead. It will give you a good idea about the feel of Joomla! before you start building your own site. The website is set up just for you, so you can make as many changes as you want.
Please note: This install will reset 90 mins after activation and all changes will be lost.

All user accounts are given Super Administrator access and can perform all functions. Feel free to use the new demo resource and to share it with others interested in exploring Joomla's capabilities.

For more details about the operation of the demo site, visit demo.joomla.org.

**Comment by brianteeman** [comment]
Do we have to use the ! everywhere?

**Comment by Sandra97** [comment]
Yes, with exceptions: https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name

**Comment by Sandra97** [comment]
Content updated. Thanks Mike.

**Comment by mikeveeckmans** [comment]
Thank you @Sandra97  !!

**Comment by brianteeman** [comment]
Grrh Sandra I wish you had waited for approval and correction before
updating

**Comment by Sandra97** [comment]
I'm ready for any corrections. And if you prefer, I can still restore the old version

**Comment by brianteeman** [comment]
You can really experience the power of Joomla! using the online demo at demo.joomla.org. You'll quickly discover how easy it is to create and manage content, install extensions and templates, and build a complete website.

## 90-day free demo

With 90 days to explore Joomla! you can build a complete website for yourself or your company, absolutely free of charge. If you want to keep your website after the demo period is over, you can easily move it to a standard hosting account.

## 90-minute test drive

Not sure yet about the 90-day demo? Take a one-time quick Joomla! ride instead. It will give you a good idea about the feel of Joomla! before you start building your own site. The website is set up just for you, so you can make as many changes as you want. (*This install will reset 90 mins after activation and all changes will be lost.*)

**Comment by Sandra97** [comment]
Content updated! Thanks Brian. 
If you have any other corrections, I'm ready!

**Comment by mikeveeckmans** [comment]
Thanks @brianteeman & @Sandra97 !
