### ISSUE TITLE
[jdocs] Help5.x namespace required

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-websites#1904]
To prepare Help screens for the upcoming release of Joomla 5 we need new MediaWiki namespaces, in particular Help5.x for the Help screens. And probably J5.x for tutorials. This article has information on how to do it:

https://www.mediawiki.org/wiki/Manual:Using_custom_namespaces

**Comment by HLeithner** [comment]
I would like to move the help screens to [docs-next](https://docs-next.joomla.org) if possible

**Comment by ceford** [comment]
In my opinion that is not practicable. It would require a huge amount of work that nobody seems interested in doing. I have not had any responses to my posts in the Mattermost group for some time. Enthusiasm seems to have waned! The test translation I created in Crowdin (articles.md in German) has not been included in docs-next so I wonder if the Crowdin route is even working. The proxy would need to be changed to suit. The Help docs in docs-next were from my first conversion attempt - I think they need to be recopied from my latest repo. Just too much to do in too little time with too few people.

Add to my list above: we probably need a Chunk5.x namespace too.

**Comment by ceford** [comment]
@wilsonge Can you help with this? I will be away for a couple of weeks but could work on the Help screens when I get back. 

Also, it would be good to fix the proxy to actually deliver J5 Help screens.

**Comment by wilsonge** [comment]
I think I've sorted it.

**Comment by ceford** [comment]
> I think I've sorted it (help5.x and also chunk5.x). I haven't done this in quite a lot of years - so let me know if anything looks wrong!

@wilsonge  I can see J5.x and Chunk5x in the list of Namespaces but no Help5.x - can you add it?

**Comment by wilsonge** [comment]
Ooops! Only missed the main thing you asked for :D Added
