### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by lastevns** [joomla/joomla-websites#1907]
EVERY time I try to log in to Joomla support forums -- no matter WHAT password I use and no matter how strictly and faithfully I save the password in my app, the password comes up as incorrect when I try to log in. This has been happening for years and it's really discouraging. Can someone help me please?

I have used NUMEROUS emails and credentials to log in (hoping one would work). But that I would use recently (if I could) would be either marketing@songwritersguild.com or websmaster@songwritersguild.com.

Also, this happens on FF, Chrome, Edge and Maxthon.

Hoping you can help,

Laurie

**Comment by ooffick** [comment]
Hi Laurie

You have two accounts, with both of the email addresses. But your usernames are both different.

I can merge the two accounts together, as only one account is allowed and it will make it easier for you by just having one account.

Can you contact me at olaf.offick (AT) community.joomla.org

And I will be able to merge the two accounts and tell you your username. 

Kind regards
Olaf

**Comment by HLeithner** [comment]
I expect this issue is solved because of no response from the creator, I'm closing this for now. please reopen if you still have issues.
