### ISSUE TITLE
[jorg] Siteground affiliate links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#191]
We need to check to make sure that .org is always using the affiliate link when linking to siteground.com

For example on this page https://www.joomla.org/about-joomla/partners.html the text link does not use the code but the image link does. Can someone please update that to use the affiliate link.

(there is also a link with no anchor text to siteground at the beginning of the Cloud Access paragraph that needs to be removed)

**Comment by wilsonge** [comment]
I've copied the link used for the image to the link to the siteground url (I have no access to the code so I'm assuming it's the correct code here on the image). I wasn't sure if it was required for the demo.joomla.org link?

**Comment by brianteeman** [comment]
Thanks - thats all you had to do

**Comment by Sandra97** [comment]
I just logged in to change it too ;) Too late... Thanks George!
