### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by empulsetech** [joomla/joomla-websites#1910]
I cannot log into the forum despite the fact that I have created two accounts, under two different user names.  In order to get a reset link you require both the user name and the email address used to register.  I know both user names but do not know which email address (of the several dozen I have used in the last few years due to changes when an address is compromised by spam bots, etc.)

Can you please just send an email message to each of the following user names so that I can see what email address I used for each so I can then go through the accojunt recovery process.

empulse, empulsetech

Thank You

**Comment by pe7er** [comment]
I've sent an email via the forum to both forum accounts.
Could you please let me know if you received any of them?
Thanks!

**Comment by HLeithner** [comment]
closing this as expected to be solved since no repsonse after 1 month, if you still have an issue please reopen or create a new issue. thanks
