### ISSUE TITLE
[idp] identity SSO login won't recognize my email address!?

### ISSUE THREAD

**Issue by garstud** [joomla/joomla-websites#1912]
Hello,  
I was logged into Mattermost 2 weeks ago.  
I'm having trouble trying to login to https://identity.joomla.org/  

So I try to reset my password, but I get this message:  

![image](https://github.com/joomla/joomla-websites/assets/970021/d288ca26-9483-4160-99fe-8331e83b4280)

I am sure of my email address. Can I send my email address to someone who can check if it still exists?  
(I still receive Mattermost notifications on my email inbox)  

My email address is attached to the following profile:  
https://volunteers.joomla.org/joomlers/336-marc-studer

**Comment by HLeithner** [comment]
I will look at it later today

**Comment by HLeithner** [comment]
Issue should be solved.

**Comment by garstud** [comment]
Hello, i have tried to login, but i have always the same error :

`**Authentication aborted**
Authentication was aborted by the user`

![image](https://github.com/joomla/joomla-websites/assets/970021/2c19ed66-8a37-4430-8526-6e9645414f27)

And when i try to reset my password, my acound is not found (invalid)

**Comment by roland-d** [comment]
Hello @garstud Can you e-mail your e-mailaddress to roland.dalmulder@community.joomla.org and I will have a look.

**Comment by garstud** [comment]
ok @roland-d , done ;)

**Comment by roland-d** [comment]
@garstud I have replied your email.

**Comment by garstud** [comment]
I just answered @roland-d , thank you.
The situation is particular ... I have just done an absurd test:
I tried to log on Identity with what I think is my old login (d.....@g....com) and I have the msg in red as above.= ("Authentication aborted - Authentication was aborted by the user")
And if I log in with a non-existent account, I don't get any message... strange, no?

**Comment by garstud** [comment]
Thank you for your new email @roland-d .
I try to re-connect Mattermost with the new(?) login (m...@s....fr), i have to (re)accept consents ... well, ok!
But after that i get this screen:
"email adress has not been verifyed!"
I don't received any email or spam.
- have you an idea?

![image](https://github.com/joomla/joomla-websites/assets/970021/3fd9b2a1-623b-48af-9d55-0e2290e59802)

**Comment by roland-d** [comment]
@HLeithner Can you help Marc with this? He changed his emailaddress and I know MM does not take kindly to that :-|

**Comment by garstud** [comment]
Well, actually, I don't seem to have changed my email address!? ;) 
But as @roland-d pointed out by email, it is possible that there is something between my **Volunteer account** and my **identity account**!? i don't know.

**Comment by roland-d** [comment]
Hey Marc, there is no difference between the Volunteer account and the Identity account, they are one and the same. That is the whole idea of the Identity platform. Your identity is managed on the identity portal and then synced with the volunteer portal.

**Comment by garstud** [comment]
Arf ok, thank you, so my first thought was the right one ;)
I'm sure I didn't change my login on the identity...but if I did something wrong, I don't know.
It was working before my vacation, and when I came back, i couldn't log in! ?

**Comment by roland-d** [comment]
Marc, something else I am thinking now, you can of course change your email back to the one you want to use or used before in your profile. Logging into mattermost should work again then as well.

You had a very good vacation then :smile: 

I am not aware of any changes done nor why we would change only your emailaddress  :)

**Comment by HLeithner** [comment]
I will activate at the New address again on matter most

**Comment by HLeithner** [comment]
I activated the account again with the email m*.fr

**Comment by garstud** [comment]
Thank you @HLeithner .
Weird, I manage to connect to [Volun](https://volunteers.joomla.org/), but not to Mattermost!?
But, this is the same SSO process behin, is'nt it?

**Comment by HLeithner** [comment]
Yes, it's the same account but we have some issues syncing email address changes.

Does it work now or does the issue still exists?

**Comment by garstud** [comment]
No, i kill my desktop Mattermost App and try to login ... but same error! :(

**Comment by HLeithner** [comment]
On now ;) the CLI application of matter most is a bit confusing

**Comment by garstud** [comment]
Ok, are there any issues listed on github for this CLI?
(but it may be private)
I have already worked on SSO and data sync processes for my Joomla clients via Rest API, if that helps!?

**Comment by HLeithner** [comment]
Does your account work now?

We use saml for authentication between matter most and identity portal.

**Comment by garstud** [comment]
Yeahhhh ! thank you so much @HLeithner . I recover all my data in Mattermost !!!

**Comment by HLeithner** [comment]
Sorry for the inconvenience that took so long.
