### ISSUE TITLE
[jdev] meta title tag

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#192]
Spotted when I shared a link on facebook to https://developer.joomla.org/contact-security-team.html that the facebook and twitter title meta tags are both ROOT

I am guessing its a bug in the social sharing plugin thats generating the tags

**Comment by fititnt** [comment]
@brianteeman  does this problem still exist? Twitter share link is worst than Facebook.

Links to validate this: 
- https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fdeveloper.joomla.org%2Fcontact-security-team.html
- https://cards-dev.twitter.com/validator

![captura de tela de 2016-03-07 16 06 45](https://cloud.githubusercontent.com/assets/812299/13579932/ab4037a6-e47e-11e5-91df-06101b8a5201.png)
![captura de tela de 2016-03-07 16 06 19](https://cloud.githubusercontent.com/assets/812299/13579931/ab3afad4-e47e-11e5-8600-dc414f151c95.png)

**Comment by mbabker** [comment]
No longer an issue with current plugin code.
