### ISSUE TITLE
Creating a joomla account is impossible

### ISSUE THREAD

**Issue by Dorianosaur** [joomla/joomla-websites#1920]
![Screenshot 2023-09-22 161813](https://github.com/joomla/joomla-websites/assets/132022853/3d3372c7-3b8c-4639-81ef-d90de5547d2e)

I'm based in the UK and I'm trying to launch a Joomla site, but I cannot create an account as the form won't accept my number. I've tried 6 different numbers to no avail - see screenshot for exact error message

**Comment by HLeithner** [comment]
@Pawel-Panek can you have a look here please?

**Comment by Pawel-Panek** [comment]
@Dorianosaur 

we would need to know what what number you've tried. Please contact https://cloudaccess.net and provide the info to our support team. The best would be to use the live chat that's available on our site. Thank you.

**Comment by HLeithner** [comment]
closing this
