### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by clayton1964** [joomla/joomla-websites#1923]
Tried to bring up the help for the page I was working on. Was looking for help while on the configuration screen for "JEM - Banner Module"

![image](https://github.com/joomla/joomla-websites/assets/5256170/4f12c014-2873-42a6-ba21-30b8ff677893)

**Comment by ceford** [comment]
I think that is a third party extension with the Help button incorrectly configured. You should ask its Developer for help. It is not a Joomla bug - there is no Help title to return from the Joomla Help proxy.
