### ISSUE TITLE
[joomla.org] Unable to access the joomla.org website

### ISSUE THREAD

**Issue by brucegodden** [joomla/joomla-websites#1928]
I am unable to access the joomla.org website.  This problem has been happening for at least 2 days now.

To be more specific, I can sometimes reach the home page https://www.joomla.org/ if I wait a while (say, 50% of the time). I have not managed to access any other areas of the site; and in particular, https://docs.joomla.org is not responding at all.

I get responses like the following:

```
Hmmm… can't reach this page

docs.joomla.org took too long to respond

Try:

* Checking the connection
* [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
* [Running Windows Network Diagnostics](javascript:diagnoseErrors())

ERR_CONNECTION_TIMED_OUT
```

**Comment by max123kl** [comment]
Unfortunately, several Joomla.org sites are currently unavailable.
There is a serious problem with the server farm at our host Rochen.
Please be patient, as we are, as Rochen is working tirelessly to fix the problem.

The link shows our systems that are currently affected:
https://stats.uptimerobot.com/9Lwmyhmx3n
