### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by ShredDead** [joomla/joomla-websites#1929]
![Screenshot_20231006_070637_Firefox](https://github.com/joomla/joomla-websites/assets/18369457/fd741253-38cb-4044-80c8-42f35a3da22e)
Please describe the problem or your issue

**Comment by HLeithner** [comment]
thanks for your report, we are already aware of this issue and seeking for a solution.

**Comment by HLeithner** [comment]
issue resolved
