### ISSUE TITLE
[jcomm] Issue with media manager

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#193]
When writing an article and trying to select a image from media manager by the browse button the following error shows : 
The server didn't send back a proper XML response. Please contact your system administrator.

XML request error: Forbidden (403)

Requested URL:
/plugins/editors/wysiwyg/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=Image&CurrentFolder=%2F&uuid=1450283910658

Response text:
<!DOCTYPE html>
<html style="height:100%">
<head><title> 403 Forbidden

</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden

</h2>
<p>Access to this resource on the server is denied!</p>
</div></div><div style="color:#f0f0f0; font-size:12px;margin:auto;padding:0px 30px 0px 30px;position:relative;clear:both;height:100px;margin-top:-101px;background-color:#474747;border-top: 1px solid rgba(0,0,0,0.15);box-shadow: 0 1px 0 rgba(255, 255, 255, 0.3) inset;">
<br>Proudly powered by  <a style="color:#fff;" href="http://www.litespeedtech.com/error-page">LiteSpeed Web Server</a><p>Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.</p></div></body></html>

**Comment by MATsxm** [comment]
@mikeveeckmans still relevant?
Thanks
(and if someone would be fine enough to tell me Who I should assign for the Coomunity Site? :wink: )

**Comment by Joomv** [comment]
Not much I can do here, need someone with a brain for this.
I have checked and the image manager in JCE works fine though.

**Comment by Joomv** [comment]
I will be fine enough - I think that person, sadly, is me.
