### ISSUE TITLE
Joomla 5 for joomla.com

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-websites#1930]
@Pawel-Panek can you change the default joomla version to 5.0 starting with 16:00 utc please and remove joomla 3.x please?

**Comment by Pawel-Panek** [comment]
The 3.x is removed. The 5.0 is still marked as Nightly Build. If you say this goes live today I'll try to get someone to update launch site.

**Comment by HLeithner** [comment]
sorry missed the word "tomorrow" at 16:00 utc

**Comment by HLeithner** [comment]
which package do you use? we will replace bz2 with zstd for 5.0+

**Comment by Pawel-Panek** [comment]
@HLeithner when the distribution point https://update.joomla.org/core/list.xml will get updated we will just follow up. Currently the packages are packed with ZIP so if you'd like to discontinue that then we will need to make a small adjustment on our end too. Please confirm.

**Comment by HLeithner** [comment]
zip tar.gz will still be provided only bz2 get removed and zst will be new. list.xml will be updated.

**Comment by Pawel-Panek** [comment]
The Joomla 5 is labeled as Stable now. The package download worked good so we should be able track the updates now.

**Comment by HLeithner** [comment]
thanks, 4.4 is also released ;-) maybe update it and move the 5.0 to the left?

**Comment by Pawel-Panek** [comment]
yes, we did the adjustments for Joomla 4.4.

**Comment by HLeithner** [comment]
perfect thanks
