### ISSUE TITLE
Search for author in community magazine: invalid token

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-websites#1931]
As title says: 

![grafik](https://github.com/joomla/joomla-websites/assets/1035262/257f7c55-8cd0-478c-a702-2236df858ee3)

Result is: invalid token. 

Win11, firefox

**Comment by max123kl** [comment]
confirmed 
Debian 12 FF and Chromium

**Comment by brianteeman** [comment]
duplicate of #1919 ?

**Comment by drmenzelit** [comment]
Closing this as the issue has been reported in #1919
