### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by superknutsel** [joomla/joomla-websites#1937]
Hi, I'm trying to figure out why the listing of my company ( De Linie ICT ) has suddenly been removed.
All I got was an email that this had happened. I'm not aware that I did anything wrong.
Checked my consent in the identity portal, this was all good.

I'm not angry, dissapointed or in a hurry. Just trying to make sense of it and maybe improve something in the process.

As a sidenote, the link in the e-mail you get to the Terms of Service is a relative link so it's not clickable from the e-mail.

Thanks, Nico

**Comment by aboarken** [comment]
Hello @superknutsel,

Thank you for reporting this issue. Please can you submit an ticket using JCM Help Desk: https://community.joomla.org/helpdesk.html

Also please update your entry from here: https://community.joomla.org/service-providers-directory.html?id=109

Looking forward to solve your reported issues.

Regards,
Ahmad Moussa

**Comment by aboarken** [comment]
Hello @pe7er, can you please close this issue. Thank you.
