### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by pappap647** [joomla/joomla-websites#194]
Our website www.stgeorgestheatre.com is not letting customers buy tickets for most the shows.

It is an issue with the security settings and most peoples computers are blocking the page from opening properly.

This is costing us money daily.

**Comment by mikeveeckmans** [comment]
Hi,
this is the place to report issues that concern ONLY official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/
Thanks

**Comment by pappap647** [comment]
It is a joomla website

**Comment by brianteeman** [comment]
Yes but the place you have reported it to is for issues with the actual joomla.org web site and not for sites built with the Joomla software.

I have however taken a quick look at your web site and the checkout process. It appeared to work fine to me although you should note that the booking process is not joomla. It is an external service you are using from https://www.spektrix.com/

Please use the links provided previously if you need any further assistance

**Comment by pappap647** [comment]
its to do with the security issues for the site, the iframe is working perfectly.  Who do I contact at Joomla about further help.  Both Spektrix and Redhotmedia says tis a joomla issue.

**Comment by brianteeman** [comment]
> for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

**Comment by mikeveeckmans** [comment]
or : https://resources.joomla.org/en/providers-by-category/category/technical-support
