### ISSUE TITLE
[jdown] Discover the latest features on 5.joomla.org linking to joomla 4

### ISSUE THREAD

**Issue by devsmax** [joomla/joomla-websites#1940]
On the downloads page: https://downloads.joomla.org/

The button "Joomla! 5 // Discover the latest features on 5.joomla.org" links to https://www.joomla.org/4/en/ instead of 5.joomla.org.

![image](https://github.com/joomla/joomla-websites/assets/14150822/8aac9967-4e5e-4a59-858c-c24f77b74689)

**Comment by Ansh101112** [comment]
okay will fix this asap. But could you provide me the repo and directory where this file is concerned?

**Comment by HLeithner** [comment]
sorry that it took so long, I fixed it, thanks for the report

**Comment by Ansh101112** [comment]
hey could you provide the fixed code where you make changes or just tell the directory??
