### ISSUE TITLE
www.joomla.org Learn more about Joomla! 4

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-websites#1942]
Hi, on the joomla.org website there is a link to Joomla 4 (Learn more about Joomla! 4) , maybe it would be better to link to Joomla 5 (Learn more about Joomla! 5)

![img](https://i.imgur.com/UD6rTUu.png)

**Comment by HLeithner** [comment]
I updated the text, link and video. for this entry. thanks for letting us know.
