### ISSUE TITLE
Unkown Joomla... Cannot load update page

### ISSUE THREAD

**Issue by tsuki27** [joomla/joomla-websites#1947]
I cannot update Joomla nor load the update screen panel. It was fine before but suddenly when I log into backend, it became Unknown Joomla... without stating any error. 

Joomla ver: 5.0.0 (was gonna update to 5.0.1 after template got updated)
Php ver: 8.2.13

I did try some of the tips from the internet, like clearing cache, rebuilding the components, update database structure. 

Photos before and after are included for reference.

Please help cus I don't want to proceed through the web building process in case I had to reinstall everything again :')

![It was like this before](https://github.com/joomla/joomla-websites/assets/74808501/15ebffef-5d42-4656-9fb0-06a77bdbed57)
![Now it's like this](https://github.com/joomla/joomla-websites/assets/74808501/589a9886-c3bf-4491-a334-eb6a18de84b2)
![Screenshot 2023-12-01 145632](https://github.com/joomla/joomla-websites/assets/74808501/4204ec9b-a403-49ff-9fb9-7cfc7100a190)
![Nothing loads on the update page](https://github.com/joomla/joomla-websites/assets/74808501/3da80cd2-60fe-4e34-a680-f9779b1c2e76)

Thank you.

**Comment by tsuki27** [comment]
Update: I'm stupid. I turned on maximum error message and my joomla update page end up dead.

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

In the future for user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

Thanks!
