### ISSUE TITLE
[joomla.org] Website Optimization Issues

### ISSUE THREAD

**Issue by Nzioka2023** [joomla/joomla-websites#1949]
I have a premium Joomla site http://darulkheircommunitycenter.org/
When viewing content via PC, everything shows well but when accessing the website via phone,the words seem to be overlapping one another and it looks very disorganized.

I've even tried many mobile optimization plugins but they don't help.
![Screenshot_20231212-190740](https://github.com/joomla/joomla-websites/assets/125402415/d091397a-5a9a-429f-8817-834eb65935ec)

Please help sort the issue

**Comment by pe7er** [comment]
This repository is ONLY for reporting issues with the official *.joomla.org websites, not about the Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!

**Comment by Nzioka2023** [comment]
Absolutely not helpful at all...Very irrelevant response...all these links you provided are irrelevant...
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

The Joomla team- relevant designation should help address the issue...You can make more sense giving me an email support address or customer care number...some resource to help solve my issue

**Comment by max123kl** [comment]
You are using an **open source CMS**, developed and maintained entirely by **unpaid** volunteers.
If you are looking for a professional service (email support, service hotline or something similar) you are wrong with Joomla and need to look at proprietary systems.
But if you are looking for a friendly (free) assistant for your personal Joomla site, then ask in the forum or read the documentation.
If you want personal assistance, the companies in the Service Provider Directory will be happy to help you for a fee.

**As mentioned above, this GitHub repository is only responsible for problems on joomla.org sites.**
