### ISSUE TITLE
[jcomm] Change of email adress on Forum failed

### ISSUE THREAD

**Issue by dsimonse** [joomla/joomla-websites#1950]
Had a old email assigned to my Joomla Forum profile, and when I updated it it seemed to fail.
The account is "dsimonse" and the old email was "dennis.simonsen@comhem.se" (not existing anymore).
The new adress is "dennis.simonsen@outlook.com" but I didn't recieve the activation email and now I'm looked out.
//Dennis
PS:/I cant open a case at the forum aboutr this since I can't log in./DS

**Comment by dsimonse** [comment]
Hi,
Don't know if you did something, but finally it went through.

**Comment by pe7er** [comment]
I'm closing this issue because it's solved.
