### ISSUE TITLE
Cannot register a new website on joomla website

### ISSUE THREAD

**Issue by jkkvilo** [joomla/joomla-websites#1957]
When trying to register a website (launch.joomla.org) the form keeps refusing to accept a valid phone number for verification. The phone number is Kenyan.
The error is your country, phone number and location data do not match. 

![image](https://github.com/joomla/joomla-websites/assets/63170677/00b6b2d9-71ed-436a-b164-555a99047e64)

**Comment by ceford** [comment]
Is this a general solution to this problem? I recently updated the documentation, see https://docs.joomla.org/How_to_build_your_free_Joomla_Website

Does it need amendment?

**Comment by dereksca** [comment]
Yes, it's the best solution for this problem and having it in the official doc is a good idea

**Comment by ceford** [comment]
Done! https://docs.joomla.org/How_to_build_your_free_Joomla_Website#Step_3:_Create_an_account

**Comment by jkkvilo** [comment]
> Hello, please send an e-mail with your registration details, whether you want Joomla 4 or 5 and what .joomla.com subdomain you'd need to [sales@cloudaccess.net](mailto:sales@cloudaccess.net) - the account will then be created manually

Ok, I will try this as definitely an issue on the website and I cannot create a site.
