### ISSUE TITLE
[jcomm] DPCalender breaks site

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1959]
I wanted to add our JoomlaDagen event to the calendar but when I visited https:community.joomla.org I only got an error page

> 0 Call to undefined method DPCalendar\Helper\DateHelper::setTranslator() 

![afbeelding](https://github.com/joomla/joomla-websites/assets/7062995/d6930e7c-0f8f-425f-9223-6611cf797ba0)

**Comment by wilsonge** [comment]
As an FYI i've bumped several major versions of our extensions up a version tonight (as you noticed one part didn't quite go as planned and meant things were out longer than I initially planned) and I also bumped the PHP version from 7.4 to 8.2 so there may be more less obvious gremlins lurking I didn't catch on the test site. Let me know here if you find anything and I'll fix ASAP.

Thanks for reporting though and apologies for the inconvenience!
