### ISSUE TITLE
joomlacode downloads

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#196]
Looks like 3.4.5 and 3.4.6 were not added to joomlacode
Either that should be closed or they should be added until it can be closed

**Comment by mbabker** [comment]
Ping @wilsonge 

3.4.6 and 3.4.8 aren't listed.

Still need to plan to work on finishing the plan to turn the damn thing off, but until then...

**Comment by wilsonge** [comment]
I'll do these 2 with 3.5 tonight.

Downloads site needs a lot of work but is on my priority list and will rapidly rise to the top after 3.5 is out and ready to go

**Comment by mbabker** [comment]
Still no new uploads and now you're 4 releases behind.

**Comment by mbabker** [comment]
@wilsonge You plan on ever updating these or have we said screw it?

**Comment by MATsxm** [comment]
no excuses... I drunk all his Vodka...

**Comment by wilsonge** [comment]
Tomorrow I promise

**Comment by mbabker** [comment]
We're close on the downloads site, don't worry about it at this point.
