### ISSUE TITLE
[jcomm] Error 403 on selecting image for event

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#1962]
I have found another Gremlin @wilsonge 😅

When submitting a new event, you have the possibility to add the intro and full image. When pressing Select, modal shows an error as can see in the screenshot
![afbeelding](https://github.com/joomla/joomla-websites/assets/7062995/10887b5d-de7d-45a2-b87e-c2d09310a7ce)

**Comment by hvdmeer** [comment]
Any progress on this?

**Comment by osm-operations-dc** [comment]
@hvdmeer this was solved this Summer so we can close this ticket.
