### ISSUE TITLE
[forum.joomla.org] Cannot access fourm account anymore

### ISSUE THREAD

**Issue by ericuhl** [joomla/joomla-websites#1968]
I cannot access my account anymore... I get this error message:

The specified username is currently inactive. If you have problems activating your account, please contact a board administrator.

I'm not sure who the board administrator is and there are no links for me to contact them. Hoping I can get in touch here or be pointed in the correct direction. I'd like to post to the form with a technical question.

**Comment by pe7er** [comment]
I've sent you an e-mail at the gmail address associated with your forum account.

**Comment by pe7er** [comment]
User was able to login again. Closing this issue.
