### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by AltangerelG** [joomla/joomla-websites#197]
Hello, how to delete virus from my web site? Now i'm using joomla 2.5

**Comment by MATsxm** [comment]
Hi,
this is the place to report issues that concern __ONLY__ official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/
Thanks
