### ISSUE TITLE
Cannot insert breaks into template.css

### ISSUE THREAD

**Issue by CaitlinFAOD** [joomla/joomla-websites#1974]
Hi there.  The template.css that came with my organization's Joomla template came with the code in one long, unreadable line.  We need to customize our template's layout, so in order to read the code, I have been going through our template.css file and inserting line breaks so the code can be more easily read.  For example, instead of this:

> #example1 .example2 .example3{font-size:14px}

I've been reformatting so it shows like this:

> #example1 .example2 .example3{
> font-size:14px
> }

I have reached line 2021 and still have a way to go.  However, when I go beyond line 2021 -- even just inserting a break after the open bracket -- I get this error message when I click "Save," "Save & Close," or "Close File":

> "Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at webmaster@xxx.com to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log."

I tried importing the fully formatted code file.  The file imported, but it was blank.  I don't know why because the file was under the data limit.  

I also tried to go to the end of the file and format from the bottom-up.  I was able to save the file without running into this error, but the formatting was totally off and included huge, undeletable spaces in page breaks.

Could someone please tell me how I can continue formatting this file from line 2021 and down without running into this error?  Thanks.

**Comment by pe7er** [comment]
Hi,

This repository is ONLY for reporting issues with the official *.joomla.org websites,
not for your own website that uses Joomla! CMS.

For user support issues with your Joomla CMS website, please go to:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.
Thanks!
