### ISSUE TITLE
Not able to log into admin panel for my joomla site. 

### ISSUE THREAD

**Issue by CutiLikeWhoa** [joomla/joomla-websites#1983]
Hi, 
For my course I had to create a joomla site and I did exactly that even purchasing a subscription. The issue is that I now cannot seem to login to my admin panel. I tried to retrieve my username, but I am not getting any reset emails even though all the confirmation emails are to that account. Any help would be greatly appreciated. Thank you.

**Comment by pe7er** [comment]
Hello,

Joomla is free open source software.
 
What kind of subscription did you buy?
Did you create your website at https://launch.joomla.org/ and bought a hosting subscription?
