### ISSUE TITLE
joomla.org/5

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1987]
Is it intentional that the site is set not to be indexed by search engines?

![image](https://github.com/joomla/joomla-websites/assets/1296369/95b5f623-3cad-4429-a6a8-55ee2e94f7f2)

![image](https://github.com/joomla/joomla-websites/assets/1296369/db607897-1e58-47cb-8c5e-0db846e44a92)

**Comment by crystalenka** [comment]
Fixed. Thank you for the heads up!

**Comment by brianteeman** [comment]
guess its been like that since day 1 - oops
