### ISSUE TITLE
Joomla Newsletter Subscription --

### ISSUE THREAD

**Issue by TheGrayCat-105** [joomla/joomla-websites#199]
People ---

RE: JOOMLA! Security News
AT:   joomla.org

Please change my email address

FROM:   tmc1@execpc.com
TO:     tmc@att.net

I DO NOT see a place where I can do this, myself: the OLD address will
VANISH at the end of this year!
Thanks!

CM

**Comment by JacquesR** [comment]
The security email is sent out via Google Feedburner. Check the link at the bottom of the email to unsubscribe your _old_ email address, and then re-subscribe here:
https://www.joomla.org/rss.html

**Comment by MATsxm** [comment]
Following Jacques's solution - Closing it - reopen if needed.
Thanks
