### ISSUE TITLE
[jcm] Homepage Layout is broken

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-websites#1991]
Hi,
The homepage layout is broken:
https://magazine.joomla.org/
![grafik](https://github.com/joomla/joomla-websites/assets/10774704/48f0cc80-470c-4ab3-b307-9c3982e2e031)

**Comment by pe7er** [comment]
It looks okay now so it might have been a caching issue. 
Maybe in Global Configuration double check the cache settings if "Platform Specific Caching" is enabled?

**Comment by wilsonge** [comment]
Closing for now. But understanding there's no fix applied and it's likely just a cache thing.
