### ISSUE TITLE
Error in Post installation message  4.4.4

### ISSUE THREAD

**Issue by GuyDlP** [joomla/joomla-websites#1995]
Error in Post installation message. 
RewriteRule "\. ss\. etc must be RewriteRule "\.css\. etc ?

.htaccess Update Brotli Compressie

Sinds versie 4.4.4

Voor 4.4.4 ondersteunde de standaard htaccess.txt geen Brotli compressie. Dit kan resulteren in dubbele compressiefouten wanneer Joomla is geïnstalleerd op een server die gebruik maakt van Brotli compressie. Er moeten handmatig de benodigde wijzigingen toegepast worden op een bestaand .htaccess bestand, omdat dit bestand niet automatisch kan worden bijgewerkt.

De oude code:

RewriteRule "\. ss\.gz$" "-" [T=text/css,E=no-gzip:1]
RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]

De nieuwe code:

RewriteRule "\. ss\.gz$" "-" [T=text/css,E=no-gzip:1,E=no-brotli:1]
RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1,E=no-brotli:1]

**Comment by pe7er** [comment]
Hoi,

Deze repository is ALLEEN bedoeld voor het melden van problemen met de officiële *.joomla.org-websites,
niet voor eigen websites die gebruik maken van Joomla! CMS.

Voor gebruikersondersteuningsproblemen met Joomla CMS-websites:
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
of zoek een serviceprovider op https://resources.joomla.org/

Om deze reden sluit ik dit issue hier.
Bedankt!
