### ISSUE TITLE
[joomla.org] domains.joomla.org does not work

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-websites#1999]
I wanted to login to see my domains at domains.joomla.org which should be Abion now.
But the website is not loading.

**Comment by pe7er** [comment]
@webgras Today the website domains.joomla.org loads ok here. 
Maybe it was a temporary issue or it has been solved in the meantime?

**Comment by webgras** [comment]
I contacted the service provider Abion (before: Brandit), they solved the problem on their side after a few days.
So, actually we can close this now. Thanks for bringing it up again!
