### ISSUE TITLE
[ALL] Convert sites to force SSL

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#20]
With the greater internet's push for SSL traffic, the `joomla.org` network needs to get in compliance.  This is a meta issue for tracking the status on all sites; the "tasks" in this issue should be marked complete when the site is running and forcing SSL traffic.

Data as of 27 January 2016:

Website | SSL Status
------- | ------
joomla.org | Forces SSL
joomla.org/3 | SSL certificate installed
api.joomla.org | Forces SSL
appscdn.joomla.org | Forces SSL
cdn.joomla.org | SSL certificate installed (not a live site but should be used for publishing shared media)
certification.joomla.org | Forces SSL, mixed content warnings when browsing the site
community.joomla.org | SSL certificate installed, mixed content warnings when browsing the site
community.joomla.org/showcase | SSL certificate installed, mixed content warnings when browsing the site
conference.joomla.org | SSL certificate installed
demo.joomla.org | Forces SSL
developer.joomla.org | Forces SSL
docs.joomla.org | Forces SSL
downloads.joomla.org | Forces SSL, site in development
events.joomla.org | Forces SSL
exam.joomla.org | SSL certificate installed
extensions.joomla.org | Forces HTTP
forum.joomla.org | Site fails to load
framework.joomla.org | Forces SSL
help.joomla.org | Forces SSL
help.joomla.org/proxy | Forces SSL
issues.joomla.org | Forces SSL
joomlacode.org | Do we have a certificate for this domain?  Scheduled for shutdown
magazine.joomla.org | SSL certificate installed, mixed content warnings when browsing the site
opensourcematters.org | Do we have a certificate for this domain?
resources.joomla.org | SSL certificate installed, mixed content warnings when browsing the site
shop.joomla.org | SSL certificate installed, site in offline mode
update.joomla.org | SSL certificate installed
vel.joomla.org | Forces SSL
volunteers.joomla.org | Forces SSL

Task List:
- [x] joomla.org
- [ ] joomla.org/3
- [x] api.joomla.org
- [x] appscdn.joomla.org
- [x] cdn.joomla.org
- [ ] certification.joomla.org
- [ ] community.joomla.org
- [ ] community.joomla.org/showcase
- [x] conference.joomla.org
- [x] demo.joomla.org
- [x] developer.joomla.org
- [x] docs.joomla.org
- [x] downloads.joomla.org
- [x] events.joomla.org
- [ ] exam.joomla.org
- [ ] extensions.joomla.org
- [ ] forum.joomla.org
- [x] framework.joomla.org
- [x] help.joomla.org
- [x] help.joomla.org/proxy
- [x] issues.joomla.org
- [ ] joomlacode.org
- [ ] magazine.joomla.org
- [ ] opensourcematters.org
- [ ] resources.joomla.org
- [ ] shop.joomla.org
- [ ] update.joomla.org
- [x] vel.joomla.org
- [x] volunteers.joomla.org

**Comment by mbabker** [comment]
I've sent up an e-mail to get the SSL certificate installed on the server hosting dev, issues, and FW sites.  Host is also looking into SSL certificate install for update CDN (similar requirements as our install from web CDN).

**Comment by Kubik-Rubik** [comment]
Great initiative, thank you Michael!

**Comment by Hutchy68** [comment]
Where's all the mixed content coming from? Is that us or are we embedding other content?

**Comment by mbabker** [comment]
CSS & JS references mainly (just browse the sites with dev tools open).  I know on .org the root issue is that social sharing plugin.  For sites like the VEL, they're behind the base template which has the mixed content issues (old version was using hardcoded `http://` for Google Fonts) and a template update would help with a lot.

**Comment by Hutchy68** [comment]
Ok, @Radek-Suski is the social guy. He will need to take a look.

**Comment by Radek-Suski** [comment]
Actually Sigrid is :P
I will check the events site at weekend.

**Comment by mbabker** [comment]
It's the ShareThis plugin, has nothing to do with anyone's teams, unless Radek wrote it (in which case, I'd like to have some choice words with you... :smiling_imp: )

**Comment by brianteeman** [comment]
Like actually make it useful

On 5 August 2015 at 21:39, Michael Babker <notifications@github.com> wrote:

> It's the ShareThis plugin, has nothing to do with anyone's teams, unless
> Radek wrote it (in which case, I'd like to have some choice words with
> you... [image: :smiling_imp:] )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/20#issuecomment-128141447>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Radek-Suski** [comment]
Oh boy. I didn't. No way. :smiling_imp: 
Just to be clear: I am managing the new shortener. I am in the events team and the social media team. If you need anything, let me know ;)

**Comment by pbwebdev** [comment]
Can we consider swapping over to AddThis instead of ShareThis if you want social analytics or writing our own. The on page AddThis social sharing has better accessibility as well from last testing. Keyboard navigation and labels were actually read by screen readers.

**Comment by pbwebdev** [comment]
@mbabker 

Does this include the appscdn.joomla.org domain.

I had a user report this to me.... which is the reason why I suggested starting a github account for all our websites.

#### Steps to reproduce the issue
Attempt to use the Web Installer in the Joomla! Extension Manager (multiple browsers).
-or-
Browse to https://appscdn.joomla.org/webapps/


#### Expected result
Valid SSL Certificate without invalid SSL error.


#### Actual result
Your connection is not private
Attackers might be trying to steal your information from appscdn.joomla.org (for example, passwords, messages or credit cards). NET::ERR_CERT_DATE_INVALID


#### System information (as much as possible)
Certificate downloaded by browsers:
Common Name (CN):  appscdn.joomla.org
Begins On:         14/07/14
Expires On:        17/07/15
SHA-256 Fingerprint:
45:8E:AF:39:9B:DC:A4:99:8E:6C:22:F2:4B:52:E8:DE:F3:49:0E:47:3D:84:CB:4E:39:FA:B0:75:56:3B:10:15

SHA1 Fingerprint:
1B:DC:D0:C9:78:74:83:B6:23:CE:6C:1D:C2:4B:FC:40:00:14:E7:35


#### Additional comments
The invalid SSL certificate appears to cause intermittent issues when attempting to use the Web Installer causing it to return:
COM_INSTALLER_WEBINSTALLER_INSTALL_WEB_LOADING_ERROR="Can't connect to the Joomla! server. Please try again later."

**Comment by mbabker** [comment]
The certificate needs to be renewed but yes that should be included.  Updating the issue.

**Comment by jneubauer** [comment]
fixed mixed content warnings on JWC

problem was with banner images - the banner module specifies the baseurl ($baseurl) instead of just the image url, which, unless the site is set to force SSL, will always load those images over just http.

(side note, is it really necessary to specify the baseurl? do we really need to do that? it already gives the image path which is relative to the application already.)

**Comment by Hutchy68** [comment]
I'd 1000+ AddThis. Their metrics are awesome, we use them on docs 

Tom

**Comment by Radek-Suski** [comment]
I updated the event site but it still reports some error. I have no idea what's the issue. Maybe just cache thingy.
Can you check guys: https://events.joomla.org/

BTW: Why don't we use StartSSL certs? Just wondering ...

**Comment by jneubauer** [comment]
@Radek-Suski this is what I'm seeing as the only problem there - serve this one resource over HTTPS and it should be fine.
"VM110:208 Mixed Content: The page at 'https://events.joomla.org/' was loaded over HTTPS, but requested an insecure image 'http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png'. This content should also be served over HTTPS."

**Comment by Radek-Suski** [comment]
@jneubauer Ahh, I need to update the App then. I know the issue indeed. A huge thanks for checking. Will fix it tomorrow and the set a redirect in htaccess

**Comment by mbabker** [comment]
> BTW: Why don't we use StartSSL certs? Just wondering ...

Bring that up amongst leadership and/or hosting.  FWIW the wildcard one doesn't expire until 2019 so I doubt you'll convince many to change it.

**Comment by Radek-Suski** [comment]
Fixed events site and forced https protocol.

**Comment by mbabker** [comment]
@jessicadunbar @mikeveeckmans @MAT978 when we move repo to www, we need to enforce SSL for the site too and address any content issues that come up from that (can't test SSL on the current server as the certs aren't installed there).

**Comment by wojsmol** [comment]
@mbabker The SSL certificate for demo.joomla.org expired today 2015-09-30 14:48:38 (2015-09-30 12:48:38 GMT)

**Comment by mbabker** [comment]
Issue updated.

@marijkestuivenberg can OSM address this?  I'm going to assume the certificate is the responsibility of the demo site vendor since it isn't using our wildcard certificate.

**Comment by wojsmol** [comment]
@mbabker The SSL certificate for demo.joomla.org is now valid.

**Comment by andrepereiradasilva** [comment]
@mbabker excellent!
Please check also this ones that i see in Joomla code that are not in your list:
- feeds.joomla.org
- build.joomla.org
- contribute.joomla.org

For the ones that you have no certificate (e.g. opensourcematters.org) you can use Let's Encrypt certificates (https://letsencrypt.org/) that are free and can the process can be fully automated.

**Comment by Radek-Suski** [comment]
Looks like SPAM tbh

**Comment by andrepereiradasilva** [comment]
SPAM?

**Comment by Radek-Suski** [comment]
Well, no offence but if you check what you wrote exactly is:
- feeds.joomla.org - is a Feedburner service
- build.joomla.org - is a Jenkins service 

Nobody ever claimed that we have no possibility to have SSL cert but your main point is to use "Let's Encrypt" certificates. There are many other providers offering free certificates so why do you think we need to use this particular one?

**Comment by mbabker** [comment]
Radek we already have a wildcard cert.  Calm down.

**Comment by Radek-Suski** [comment]
> Radek we already have a wildcard cert.  Calm down.

I know. That's my point. :P 
BTW: Wondering what is with OSM website. It shouldn't be that hard

**Comment by andrepereiradasilva** [comment]
No, that has not my main point.
My main point has the 3 domains are not in the list and was alerting @mbabker of that.

The use of certificates from the Let's Encrypt project is a suggestion for the ones that you have no certificate at the moment. Nothing else.
I think you understand my comment the wrong way.

**Comment by Radek-Suski** [comment]
@andrepereiradasilva Then I am sorry ;)

**Comment by andrepereiradasilva** [comment]
@Radek-Suski no harm done :)

**Comment by mbabker** [comment]
Just a matter of someone getting the cert.  Not my job, I just implement it
;-)

**Comment by mbabker** [comment]
There are a lot of installs missing off this list.  For the most part it is
only public facing sites where the project manages the hosting.  So domains
like feeds and ideas are left off because they're hosted on third party
platforms and build isn't intended to be a public facing site.  Eventually
all should be converted, but in terms of priority, there are a handful I
have toward the end of the list.

**Comment by andrepereiradasilva** [comment]
Yes of course. I understand.

**Comment by mbabker** [comment]
I'm closing this.  There's no way it should take 5 months to get every site requiring SSL connections given a wildcard certificate is available (and installed) for most every subdomain.  This indicates there's no priority by the remaining site admins to implement SSL connections.

**Comment by Radek-Suski** [comment]
That's sad

**Comment by mikeveeckmans** [comment]
@mbabker sorry i think i overlooked this one, shop.j.o is forced now

**Comment by wilsonge** [comment]
Just done some updates here. Magazine, certification, community, extensions and conference all appear to be forcing itnow

**Comment by andrepereiradasilva** [comment]
george see also https://github.com/joomla/joomla-websites/issues/231 . i think the list is more updated in that PR
