### ISSUE TITLE
[joomla.org] Zweifaktorenanmeldung

### ISSUE THREAD

**Issue by dhm2023de** [joomla/joomla-websites#2004]
Nach der Fertigstellung von Jommla4xx habe ich die Zweifaktorenanmeldung eingerichtet. Lief soweit reibungslos.
Irgendwann hat IONOS (provider) die Benachrichtigung per 6-stelligen Code geändert, deaktiviert.

Sachlage ist wohl, dass meine Mailadresse als Admin nicht mit der Domainadresse übereinstimmt. Was ja logisch ist.
Fehlermeldung: Could not instantiate mail function.

Ionos und der sog. Support sendet an den Kunden sie sollen sich an den Webadmin wenden. ?¿
Meiner Meinug sollten sie diese Sperre wieder deaktivieren - Punkt.

Tatsache ist, ich komme nicht mehr in die Anwendung um Upates einzuspielen, oder etwas zu ändern. Da geht einfach nichts.
Früher gab es doch die Möglichkeit die Mailadresse in der Datenbank zu ändern.

Frage ist nun, wie kann ich hier ggf. die Kundenmail einsetzen um übrhaupt wieder in die Anwendung zu kommen? Und dann ggf. die Zweifaktorenanmeldung neu zu konfigurieren?

Mit dem Support komme ich jedenfalls so nicht weiter, ich drehe mich hier im Kreis. Gibt es hier überhaupt eine Möglihkeit wieder auf eine Standartanmeldung zu gehen? 
Die Kundin hat einen eingeschränkten Zugang für ihre News. Sie kommt aber nicht ins tiefer ins Backend.

Oder gibt es einen Dienstleister, der das ggf. regeln kann? Danke!

**Comment by max123kl** [comment]
Dieses Repository ist **NUR** für die Meldung von Problemen mit den offiziellen *.joomla.org-Webseiten gedacht, nicht für deine eigene Joomla! CMS-Seite.

Für Benutzer-Support-Probleme mit deiner Joomla CMS Website, gehe bitte zu:
https://forum.joomla.org/ 
https://forum.joomla.de
https://joomla.stackexchange.com/
https://docs.joomla.org/Main_Page
oder finde einen Dienstleister unter https://resources.joomla.org/ oder https://www.joomla.de/dienstleister

Aus diesem Grund schließe ich dein Issue jetzt.
Vielen Dank!
