### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MountainCove** [joomla/joomla-websites#201]
I downloaded a new version of Joomla (2.5.14) to my website (which was created using Joomla) and it seems to have wiped out all of my existing web site data.  How do I get this back?

**Comment by MATsxm** [comment]
Hi,
This repository is __ONLY__ for reporting issues with the <code>*.joomla.org</code> websites, not the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

__NOTE:__ The 2.5.x series is End Of Support and then you MUST upgrade to 3.x (last 3.4.7 and soon 3.4.8)
Thanks

**Comment by MountainCove** [comment]
Thank you.  I will go to proper site.  Still, I just downloaded the 2.5.14
last night.  Is the 3.4.7 not available?

On Thu, Dec 24, 2015 at 1:08 PM, Marc-Antoine Thevenet <
notifications@github.com> wrote:

> Hi,
> This repository is *ONLY* for reporting issues with the *.joomla.org
> websites, not the Joomla CMS.
>
> For user support issues, please go to:
> -http://forum.joomla.org/
> -https://docs.joomla.org/Main_Page
> -https://issues.joomla.org/
>
> *NOTE:* The 2.5.x series is End Of Support and then you MUST upgrade to
> 3.x (last 3.4.7 and soon 3.4.8)
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/201#issuecomment-167143328>
> .
>



-- 
Al Weed
Winegrower
Mountain Cove Vineyards
1362 Fortunes Cove Lane
Lovingston, Virginia 22949
Virginia's Oldest Winery

**Comment by MATsxm** [comment]
Where te hell did you download a 2.5.14... it is not even the last verstion of 2.5 series that ended a year ago.
here's the last one:
https://github.com/joomla/joomla-cms/releases/tag/3.4.8

**Comment by MountainCove** [comment]
I don't seem to have the original telling me to download, which may have
come out of my own website.  Still this is what I got back from Go Daddy.
---------- Forwarded message ----------
From: GoDaddy <donotreply@godaddy.com>
Date: Wed, Dec 23, 2015 at 4:45 PM
Subject: Installation of Joomla 2.5.14 Completed
To: mtncovevyds@gmail.com


Joomla is ready.
<http://www.godaddy.com?isc=gdbb2632&ci=87821&cvosrc=bounceback.2632.gdbb2632>
24/7 Support: (480) 505-8877 <(480)%20505-8877> Al Weed — Customer Number:
51179628
Joomla is ready. Joomla 2.5.14 is installed and ready for your personal
touch.


IMPORTANT INFO

*Joomla login:*
http://mountaincovevineyards.com/administrator/

*Hosting account:*
Log in
<https://hostingmanager.godaddy.com/Login.aspx?isc=gdbb2632&ci=87823&cvosrc=bounceback.2632.gdbb2632>

*My installed applications:*
http://hostingconnection.godaddy.com?isc=gdbb2632&ci=87824&cvosrc=bounceback.2632.gdbb2632

Get online help
<https://www.godaddy.com/help?isc=gdbb2632&ci=87825&cvosrc=bounceback.2632.gdbb2632>
Please
do not reply to this email. Emails sent to this address will not be
answered.

Copyright © 1999-2015 GoDaddy Operating Company, LLC. 14455 N. Hayden Rd,
Ste. 219, Scottsdale, AZ 85260. All rights reserved.



-- 
Al Weed
Winegrower
Mountain Cove Vineyards
1362 Fortunes Cove Lane
Lovingston, Virginia 22949
Virginia's Oldest Winery

**Comment by MountainCove** [comment]
I was trying to reset my joomla password and the notice came up to update.
I have forwarded the response to the download completion.
