### ISSUE TITLE
Joomla translation eu-ES XML fails [jdown] 

### ISSUE THREAD

**Issue by Vitriola** [joomla/joomla-websites#2012]
Hi.
The file:
https://update.joomla.org/language/details4/eu-ES_details.xml

have the code duplicated.

**Comment by HLeithner** [comment]
looks ok for me, not sure what code is duplicated?

**Comment by Vitriola** [comment]
The XML is valid for 4-4-3-5 and 4-4-3-4:

<updates>
<update>
<name>Joomla! 4 - Basque</name>
<description>This is the Basque Language Pack for Joomla! 4.4.3 (v5)</description>
<element>pkg_eu-ES</element>
<type>package</type>
<version>4.4.3.5</version>
<downloads>
<downloadurl type="full" format="zip">https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-basque/4-4-3-5/eu-es_joomla_lang_full_4-4-3v5-zip?format=zip</downloadurl>
</downloads>
<sha256>cf4d5e9234b5b488af51db1b80c1942e0e65487d7894fe3ce3e17d90f0128de0</sha256>
<sha384>41a93a0f7ea245e35962911fcacdc37c446d7d22c8e5398a95c804d0c724417283c7b79da763a2d19922e46ed71cf2ac</sha384>
<sha512>3296b793b1035ab357f537431bb0c2868fbd8e82944e4d5aaa717eefaa891602654a3c4fd64475a6c3eaae13aed25caa9407353c4fa8bac2d8a62bc1b3899688</sha512>
<targetplatform name="joomla" version="4.[01234]"/>
</update>
<update>
<name>Joomla! 4 - Basque</name>
<description>This is the Basque Language Pack for Joomla! 4.4.3 (v4)</description>
<element>pkg_eu-ES</element>
<type>package</type>
<version>4.4.3.4</version>
<downloads>
<downloadurl type="full" format="zip">https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-basque/4-4-3-4/eu-es_joomla_lang_full_4-4-3v4-zip?format=zip</downloadurl>
</downloads>
<sha256>469465e3aebcea2e199dc28a75266a0fbbe51f62c2e97095f2a2ddd349cdc0ff</sha256>
<sha384>c35fde30a590a6b4749b5e3cceda7dbd6229a16c7725fad0f3c583c9426c468e8020dfefe57a7ce952b7e30b22386a44</sha384>
<sha512>89dcc287418d31c17d9f7ad7e4ae7527c81e3beb2823882099b17ba706e045bf3c6d341cfd2223b4d9b7c1bd68c1ee74dec13d899ad41b88d680f8385ab6983c</sha512>
<targetplatform name="joomla" version="4.[01234]"/>
</update>
</updates>



If you download:
https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-basque/4-4-3-5/eu-es_joomla_lang_full_4-4-3v5-zip?format=zip
The version number in:
 pkg_eu-ES.xml
is:
4.4.3.1

**Comment by HLeithner** [comment]
can you please contact the translation coordinator for this language directly?

Joomla! Basque Translation Team trslbrr@gmail.com

I'm closing this here because it's not a joomla website issue

**Comment by Vitriola** [comment]
Thanks
