### ISSUE TITLE
[joomla.org] Html interface error on Joomla V 4.4.6

### ISSUE THREAD

**Issue by kshatriya-18** [joomla/joomla-websites#2014]
Please describe the problem or your issue Joomla 4.4.6 interface issue while logging in to the website unable to edit the articles due to interface issues please refer the image screenshot below
![Joomla Interface error](https://github.com/user-attachments/assets/4ae98472-832f-4d1d-a38d-1dfa858f4ce7)

**Comment by HLeithner** [comment]
Hi, this repo is for joomla.org site issue only. Please ask for help on https://forum.joomla.org I'm closing this.

**Comment by kshatriya-18** [comment]
Absolutely I’ve few been using joomla.org  through cPanel and my query is relevant Is there a customer support who can help we’re hosting multiple sites and having a issue with the user interface Thanks Sent from Rvz's... iPhoneOn Jul 27, 2024, at 4:59 AM, Harald Leithner ***@***.***> wrote:﻿
Hi, this repo is for joomla.org site issue only. Please ask for help on https://form.joomla.org I'm closing this.

**Comment by HLeithner** [comment]
This issue tracker is for joomla.org propertied not for the cms joomla it self. If you host joomla websites you can ask on the forum or an integrator for help.
