### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by harri00413** [joomla/joomla-websites#2016]
Would like to Log in forum.joomla.org but password not recognised. Email as username is not accepted for reset of password and registering gives me that my e-mail address is already in use. 

My e-mail address: frank@resites.nl

**Comment by ooffick** [comment]
Your username is resites.
You will need to activate your account.

Kind regards 
Olaf

**Comment by harri00413** [comment]
Hi, thanks for your reply. 

Have done that, got no e-mail. But, I’ll try again.

Regards,

Frank Harland

**Comment by pe7er** [comment]
We noticed that your forum account has been activated again.
Closing this issue.
