### ISSUE TITLE
forum.joomla.org slow

### ISSUE THREAD

**Issue by SimVT** [joomla/joomla-websites#2019]
Forum.joomla.org has been _very_ slow the past few days or has thrown database errors.

No connection or heavy load timeouts.

**Comment by pe7er** [comment]
I'm closing this issue. Last week the forum has been migrated to another server which should have solved the speed issues. Feel free to reopen this issue if you encounter new performance issues with Joomla forum.

**Comment by SimVT** [comment]
Thank you. I appreciate the hard work everyone does.
