### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by rjdevries** [joomla/joomla-websites#2021]
Can someone please remove my account-data from this topic, especially my emailadres? It is indexed by Searchengines.  
https://forum.joomla.org/viewtopic.php?t=574321

I did try to login with my account, but resetting my password does not seem to work. 
I don't get a e-mail to reset my password with.

**Comment by pe7er** [comment]
I've removed your email address from that topic. 

Did you check your spam box for the password reset email?
