### ISSUE TITLE
[josm] joomla 

### ISSUE THREAD

**Issue by Culminique** [joomla/joomla-websites#2023]
problème de connection mes identifiants et mots de passe ainsi que l'adresse mail sont non reconnue 
je suis automatiquement redirigé sur ce lien

www.aquavera.fr
Véronique Culminique 
je l'ai fait 
Pour les problèmes d'assistance utilisateur avec votre site Web Joomla CMS, veuillez consulter :
https://forum.joomla.org/
https://docs.joomla.org/Main_Page
ou trouvez un fournisseur de services sur https://resources.joomla.org/

**Comment by ghost** [comment]
You can get support at the [forum](https://forum.joomla.org/) as ```This repository is for reporting issues with the joomla.org websites only. ```

Please close the issue.
