### ISSUE TITLE
identity.joomla.org login throws 403 error since ROCHEN move to AWS 05/09/2024 

### ISSUE THREAD

**Issue by superd0ll** [joomla/joomla-websites#2026]
Trying to login to [identity.joomla.org](https://identity.joomla.org/) since the ROCHEN move to AWS on 05/09/2024 throws a 403 error.
Trying to create a new account at  [identity.joomla.org](https://identity.joomla.org/) since the ROCHEN move to AWS on 05/09/2024 throws a 403 error.
As a consequence access to Mattermost is also impossible ([identity.joomla.org](https://identity.joomla.org/) authentication is required). 

Extensive client-side troubleshooting has been performed, including:
Testing across multiple browsers and devices
Using private browsing modes
Clearing browser cache and cookies
Flushing DNS
Attempting access from different networks, computers, mobile devices, remote browsers.

![impossible-tologin-browserling-Joomla](https://github.com/user-attachments/assets/b4ea9224-3e37-43b4-99c7-1c1ebfd2fac5)

![Joomla Register](https://github.com/user-attachments/assets/3ad91376-1694-4ce0-8ca9-c922abe857a4)

**Comment by osm-operations-dc** [comment]
Hi @superd0ll 
I'm really sorry for this inconvenience. We will check with Rochen and we will check the issue.

Can you please provide the IP reported by http://ip4.me/ ? That will help us find the issue.

**Comment by superd0ll** [comment]
Hello @osm-operations-dc 
Thank you for your prompt response. 
Please find my IPv4 address here: 5.68.204.83.

I also tested using a remote browser and still getting a 403 error.  
You might need to contact Browserling about their IP address.
Please find the screenshot below. 

![joomla-Identity-remote-170924](https://github.com/user-attachments/assets/0e6df372-8c05-4127-a9a1-e8fd2c49ae3c)

**Comment by osm-operations-dc** [comment]
Hi @superd0ll 
It's weird because they cannot find any recent attempt to access identity in the logs. Can you please follow these steps:

1. Try to access to identity.joomla.org and get 403. Take a note on the time you do this.
2. Go to http://ip6.me/ and http://ip4.me/ and let me know your IP4 and IP6 addresses.

That should give us all the information we need to fix the issue.

Best!!

**Comment by TLWebdesign** [comment]
@superd0ll can you supply the requested stuff so we can hopefully get you back on mattermost. We need you there!

**Comment by superd0ll** [comment]
@TLWebdesign thank you.

So please find below:
IP4 : 5.68.204.83
IP6: 2a02:c7c:4a99:6600:d876:c8ac:755a:1ce6

Time: 19:28 BST (you can see the time on this screenshot and also on all previous screenshots.)

Please find a relevant screenshot below.

![IDENTITY-JOOMLA-180924-19-28](https://github.com/user-attachments/assets/c677437d-f874-4a4f-b8bb-892f7acc024f)

Thank you very much @TLWebdesign and @osm-operations-dc for your help.

**Comment by superd0ll** [comment]
This is to inform you that it is possible to login to my [identity.joomla.org](https://identity.joomla.org/) account. FYI it is also possible to create a new account at  [identity.joomla.org](https://identity.joomla.org/) from IP4: 5.68.204.83. Everything has been restored back to normal. Thank you very much @osm-operations-dc and @TLWebdesign for your help and support. I will now close this issue.

**Comment by superd0ll** [comment]
Thank you very much @osm-operations-dc and @TLWebdesign for your help and support.
