### ISSUE TITLE
403 error Joomla Community Magazine 

### ISSUE THREAD

**Issue by superd0ll** [joomla/joomla-websites#2028]
Trying to login to Joomla Community Magazine page ([magazine.joomla.org](https://magazine.joomla.org/)) throws a 403 error.

Magazine user: d0LLcoder@gmail.com
Time: 12:24 PM BST
IP4: 5.68.204.83
PI6: 2a02:c7c:4a99:6600:9d99:9a40:9719:c98f

Please find the screenshot below.

![joomla-community-magazine403-21-09-24](https://github.com/user-attachments/assets/947ed0dc-ad30-4c97-9cac-3a7d5b19a122)

**Comment by osm-operations-dc** [comment]
@superd0ll thanks for the info. We are on the case.

**Comment by superd0ll** [comment]
Thank you @osm-operations-dc I appreciate it :)

**Comment by osm-operations-dc** [comment]
@superd0ll this should be fixed now. Thanks for your patience!!

**Comment by superd0ll** [comment]
@osm-operations-dc yes it is fine now. Thank you so much for your help and support.
