### ISSUE TITLE
[forum.joomla.org] Joomla update broke my site.

### ISSUE THREAD

**Issue by Caperton** [joomla/joomla-websites#2029]
I tried to update my Joomla to the newest version, and I thought I did everything right, and it broke my website. I got the attached error screen.

That's all I got. I'm not a computer person. I did the thing, I thought I did it right, and now my site don't work no more.

![Screenshot 2024-09-25 at 1 46 03 PM](https://github.com/user-attachments/assets/2c3d8c7e-d137-402a-9f49-8dca100a9942)

**Comment by Hackwar** [comment]
Hello @Caperton, unfortunately this is only the bugtracker for issues with the forum software used by Joomla. You seem to need support for your website and in that case you should go to forum.joomla.org and ask for help there.
