### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Kazaku** [joomla/joomla-websites#203]
Hi, my site abvgdeika.kz is working, but when I try to go to the address abvgdeika.kz/administrator gives the material a 404 not found - is important.
![not found](https://cloud.githubusercontent.com/assets/16540931/12091160/0eb2909a-b31f-11e5-84c9-1adb690951c1.png)

**Comment by MATsxm** [comment]
Hi,
this is the place to report issues that concern **ONLY** official Joomla's websites
for any personnal issues with your Joomla! site please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/
Thanks

**Comment by Kazaku** [comment]
Thanks
