### ISSUE TITLE
[jcomm] Service Provider Directory Entry waiting for published

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-websites#2037]
My service provider directory entry is waiting for approval since almost 6 months.
Can you please publish it?
Thanks
Sigrid
https://community.joomla.org//service-providers-directory/my-entries/

**Comment by cmbr** [comment]
Many of us are in the same boat.

**Comment by osm-operations-dc** [comment]
@cmbr can you please open a ticket on the site with the name of your company: https://community.joomla.org/helpdesk/service-providers-support/submit-ticket.html ?

**Comment by cmbr** [comment]
My ticket has been successfully submitted

**Comment by pe7er** [comment]
I'll close this issue because it has been fixed.
