### ISSUE TITLE
[jcm] https://magazine.joomla.org/faq dark mode

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-websites#2038]
What needs to be fixed
https://magazine.joomla.org/faq in dark mode

Why this should be fixed
It's not legible

How would you fix it
Change the css to
[data-rlta-element=container][data-rlta-state=ready][data-rlta-theme=neutral][data-rlta-type=accordions]>[data-rlta-element=button]
{
color:black; /* or joomlas own 'black' color*/
background-color: #fff;
transition: background-color 200ms, border 200ms;
}

Side Effects expected
None

**Comment by wilsonge** [comment]
Thankyou for reporting this alongside the fix! We've committed this into the repository that contains the template - it's not going to go live for a little bit longer as there's some other PR's pending before we tag the next release. But probably in the next 1-2 weeks. But be assured this hasn't gone unnoticed!

**Comment by saraheagle** [comment]
I presume this is in hand as well then 

Go to https://magazine.joomla.org/issues
-> Click on a month
-> Click on the title or 'Continue Reading' button

The headings / bullet points of the magazine are there, but not any info or links to the info?
ie [https://magazine.joomla.org/all-issues/ ... issue-2024](https://magazine.joomla.org/all-issues/september-2024/the-september-issue-2024)

S :)

**Comment by wilsonge** [comment]
As in your expecting to see the start of the article? I mean all the article link are clickable too? Not 100% sure I understand what your saying in this case.

Not sure anyone is working on that part though!

**Comment by saraheagle** [comment]
It's been fixed :D

**Comment by wilsonge** [comment]
Accordion fix now rolled out!
