### ISSUE TITLE
website mysteriously unavailable since before christmas with no explanation 

### ISSUE THREAD

**Issue by ReverendGuen** [joomla/joomla-websites#204]
Shortly before Christmas our website went down. While I know that you do not offer tech support for the 1.5 version I deserve an explanation as to why suddenly I can't access any part of our page including the administration login section. There is no reason it should have gone down and if the page had been hacked I would not have access to the cpanel of my webhost which is not the case. I need access to the administration section of my website in order to be able to upgrade the page after backing it up. Without that access I can not access any of the information I need currently. The page is worldtreeministry.org

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

NOTE: using a version EOL since nearly 4 years must be something to dig in ;)
