### ISSUE TITLE
Problem to enjoy Forum and Joomla menu problem

### ISSUE THREAD

**Issue by comprog-ux** [joomla/joomla-websites#2041]
First when trying to login to Joomla Forum i was asked to reactivate.
but Send activation email will not send me any email at all.

Second. In a newly created Joomla site I constructed a couple of articles.
When I try to make Meny Items for them it's impossible.
When try to "Select menu item type" it's all blank.

Regards,
Ralph Höglund

**Comment by pe7er** [comment]
What's your username at Joomla forum?

This joomla/joomla-websites repo is only for *.joomla.org website issues. 
So please post your second question at Joomla forum (after we have helped you to access your account again).

**Comment by comprog-ux** [comment]
My username is ralphot

**Comment by comprog-ux** [comment]
Look at this:
You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.
Username:
Password:
[I forgot my password](https://forum.joomla.org/app.php/user/forgot_password)
[Resend activation email](https://forum.joomla.org/ucp.php?mode=resend_act)
Confirmation code:

RECAPTCHA_EXPLAIN
 Remember me
 Hide my online status this session

**Comment by pe7er** [comment]
@comprog-ux I've reactivated your account and sent you an email with new password.
Please let me know if this works for you.

**Comment by comprog-ux** [comment]
Hi.

Well I got this:
You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.

so it's impossible.

Regards,
Ralph

**Comment by comprog-ux** [comment]
Hi again.

And if I I try to register I am getting:

    The solution you provided was incorrect



So it seems impossible to use joomla forum.

/Ralph

**Comment by comprog-ux** [comment]
What's happen to Joomla Forum?????

**Comment by pe7er** [comment]
@comprog-ux Did you receive my email yesterday with new forum password?
I did not get a reply on it.

Someone reported an issue with Captcha on the Joomla Forum pages: https://github.com/joomla/joomla-websites/issues/2042
Which should be fixed now
@comprog-ux Could you please try again?

**Comment by comprog-ux** [comment]
Now I'm getting The submitted form was invalid. Try submitting again.
When I try again a got:
You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.

What more can I do? Tried with ralphot and password: chaNgeMePlEAse@20241029

**Comment by ooffick** [comment]
Would you be able to try again?

**Comment by comprog-ux** [comment]
> Would you be able to try again?

Yes, now it worked. Thank you.
