### ISSUE TITLE
[jforum]

### ISSUE THREAD

**Issue by comprog-ux** [joomla/joomla-websites#2044]
I can not login or register.
When trying to login I always get this:
You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.

Does not matter how long, has been this for days now.

If I try to register I always getting:
The solution you provided was incorrect

What in the world has happen to the forum???

**Comment by pe7er** [comment]
Could you please not open new issues for existing issues?
Please continue in https://github.com/joomla/joomla-websites/issues/2041
Closing this issue as duplicate...

**Comment by comprog-ux** [comment]
Now I'm getting The submitted form was invalid. Try submitting again.
When I try again a got:
You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to pass the CAPTCHA test.

What more can I do? Tried with ralphot and password: chaNgeMePlEAse@20241029
