### ISSUE TITLE
[forum.joomla.org]

### ISSUE THREAD

**Issue by ChasLarge** [joomla/joomla-websites#2045]
Please describe the problem or your issue

Cannot register, no ReCaptcha image showing, so cannot provide an answer ergo I get the message:

The solution you provided was incorrect

![Image](https://github.com/user-attachments/assets/e2f186c5-29ca-40cd-9395-9cf105c7fd73)

Screenshot of registration screen.

Tried on Chrome and Firefox, running on Windows 11.

Have cleared cookies etc.

**Comment by ghost** [comment]
allready reported #2042, please close this issue.

**Comment by ChasLarge** [comment]
> allready reported [#2042](https://github.com/joomla/joomla-websites/issues/2042), please close this issue.

Reported but not fixed. Maybe an ADMIN/MODERATOR should amalgamate all the queries?
