### ISSUE TITLE
[joomla.org] Not permitted to use that link to directly access that page.

### ISSUE THREAD

**Issue by JamesVeug** [joomla/joomla-websites#205]
Hi,

I have come back after a long break of not using the website and have come across an error that occurs all over the administration section.

When I try to access articles or users in the administration tools section. It comes up with this error and redirects me to the sub-menu.

You are not permitted to use that link to directly access that page (#1).

Cheers,
James Veugelaers

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thanks
