### ISSUE TITLE
[jcomm] expired. Waiting for approval (for a long time afaik :) )

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-websites#2050]
About https://community.joomla.org/service-providers-directory/

Hi,
My own profile [woluweb] is indeed still shown as "expired" (even if a while ago I resubmitted, but apparently it is still waiting for approval)
Txs for helping!
Marc

**Comment by pe7er** [comment]
Hi, 
Same here. My profile [db8] is also still showing as "expired".
Kind regards,
Peter

**Comment by pe7er** [comment]
Fixed! Thanks!

**Comment by woluweb** [comment]
same here, fixed! Txs :)
