### ISSUE TITLE
request to delete site

### ISSUE THREAD

**Issue by RhondaRF** [joomla/joomla-websites#206]
Please assist with deleting www.accessandsuccessforadults.org website. 
No need for joomla website or domain.
Thank you,
Rhonda

**Comment by wilsonge** [comment]
Joomla is just some software installed on your website. We have no way of doing anything with the website you have installed. This tracker is just for managing the websites listed https://github.com/joomla/joomla-websites/blob/master/README.md - not any personal websites using Joomla.
