### ISSUE TITLE
[jorg] 

### ISSUE THREAD

**Issue by RhondaRF** [joomla/joomla-websites#207]
I downloaded a temporary website through joomla - accessandsuccessforadults.org. 
I need this deleted. 
The website domain is owned elsewhere. 
Thank you,
Rhonda

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thanks
