### ISSUE TITLE
[certification.joomla.org] menu issues

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#208]
See screenshot. On iPhone. Not sure who's managing it.

**Comment by Radek-Suski** [comment]
![image](https://cloud.githubusercontent.com/assets/1110663/12246083/ab0858fc-b8ac-11e5-97e1-84205cdeb1a1.png)

**Comment by mbabker** [comment]
If they were running the current version of the template it would be fixed.  Alas, getting new sites (and existing ones) to run the current template is apparently a difficult task.

**Comment by pbwebdev** [comment]
That may have been my fault for not providing them with the right one. @mbabker what template can I point them to?

Site is managed by Sam Suresh - https://twitter.com/sams808 - Part of the Certification team. He also manages the exam.joomla.org website.

**Comment by mbabker** [comment]
Template's still at https://github.com/joomla/jdotorgtemplate (private repo, just need GitHub names to give access).

**Comment by mikeveeckmans** [comment]
Issue is solved , uploaded the new template with Johan today.
