### ISSUE TITLE
The SSL Certificate on apps.joomla.org contains issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#212]
The SSL Certificate on apps.joomla.org contains chain issues. They are sent in the wrong order. 

This server supports weak Diffie-Hellman (DH) key exchange parameters. 

The server does not support Forward Secrecy with the reference browsers. 

see: https://www.ssllabs.com/ssltest/analyze.html?d=appscdn.joomla.org

**Comment by pbwebdev** [comment]
Passed on to Brad for fixing. Waiting response

**Comment by mbabker** [comment]
This has been addressed to the extent possible given what the server is hosting and how its data is consumed.  Any further "upgrades" start blocking out still supported LTS distros (mainly CentOS 5).
