### ISSUE TITLE
[jdev] 404 links for left menu on https://joomla.github.io/user-interface-text/

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#214]
All the menu items of the left sidebar are 404.

**Comment by brianteeman** [comment]
Tested from my phone but everything worked. Which specific link isn't
working

**Comment by Sandra97** [comment]
I have a 404 for every single link of the left menu, not a specific one, all of them.

**Comment by Sandra97** [comment]
Forget it Brian, when I use a VPN it works fine, so it's a problem with our internet provider, not with the links.

**Comment by Sandra97** [comment]
OK, just an operator error, it comes from my habits to always click on the middle button of my mouse to open a link.
