### ISSUE TITLE
[jvols] Unable to register

### ISSUE THREAD

**Issue by megatela** [joomla/joomla-websites#215]
Saludos

He intentado registrarme en el voluntariado de joomla pero dice que estoy bloqueada. Por favor a que se debe esto?

**Comment by MATsxm** [comment]
@megatela 
still an issue?
knowing that a new version is on its way.

**Comment by sanderpotjer** [comment]
@megatela The registration workflow has been improved, hopefully it is working for you: https://volunteers.joomla.org/register.
