### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Birdzview** [joomla/joomla-websites#216]
I cannot login to Joomla :
It does not recognize my email address when logging in
I cannot register then it says the username (my email address) in use.
How to login at Joomla ?!

**Comment by MATsxm** [comment]
Where do you try to log-on?
the forum? the doc? your Joomla! site?

**Comment by Birdzview** [comment]
On the Joomla website

**Comment by MATsxm** [comment]
joomla.org?
Only admins/webmasters are aloowed to connect the site.

What do you want to do exactly?

**Comment by Birdzview** [comment]
yip, joomla.org
I thought I should register or log in to be able to read or see more.
thanks

**Comment by Birdzview** [comment]
thanks. no problem then
