### ISSUE TITLE
PHP 7 Showing up in Technical requirements of Joomla.org before official Joomla 3.5 release

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-websites#218]
https://www.joomla.org/about-joomla/technical-requirements.html

The Tech Req page above is recommending PHP 7+ already. Since J 3.5 Stable is not out yet, we should not be recommending it as yet. 

The Foot note does clarify that 7 is post PHP 3.5  however most ppl might not read that

**Comment by MATsxm** [comment]
Updated until we are sure for the date of the 3.5 release
Closed

**Comment by mbabker** [comment]
5.6+ still implies support for PHP 7.  Either leave it in the tech requirements as supported with the footnote (as 3.5 is in beta phase IMO it's appropriate to begin publishing content related to that release) or remove all references globally and ensure the version constraints make it clear that PHP 7 is 100% NOT supported.

**Comment by MATsxm** [comment]
reverted - thanks
