### ISSUE TITLE
[japi] Missing description for few JHtmlSelect methods

### ISSUE THREAD

**Issue by AdamMadrzejewski** [joomla/joomla-websites#220]
[JHtmlSelect ](https://api.joomla.org/cms-3/classes/JHtmlSelect.html)

JHtmlSelect page is missing description for methods:

- genericlist
- optgroup 
- option
- options
- radiolist

**Comment by mbabker** [comment]
It might be a phpDocumentor bug.  I just regenerated the 3.x docs off the 3.4.8 tag and it's still missing.

**Comment by mbabker** [comment]
OK, I found the problem.  The HTML `<select>` tags are being parsed as literal select tags when the page is rendered (if you view the source the methods are there).  So, we'll need to do some tweaking to how the template processes these items it seems.

**Comment by mbabker** [comment]
I manually patched `JHtmlSelect` on the build server to wrap the `<select>` tags in back ticks to get the markdown parser to properly escape them.  Everything's fine on that page now.

The CMS will need patches for any doc blocks in the `libraries` directory that has HTML tags within them to make the same changes.

**Comment by wilsonge** [comment]
Merged in the CMS

**Comment by MATsxm** [comment]
Thanks both
