### ISSUE TITLE
[jvols] Please add share button for reports

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-websites#221]
Add share buttons such as social share Facebook, Twitter so reports on volunteer portal can be shared by others.

**Comment by mbabker** [comment]
Probably could just add logic to https://github.com/joomla-projects/plg_content_joomlarrssb to make it work with com_volunteers

**Comment by sanderpotjer** [comment]
This is now available, but via a slightly different setup (JLayout): https://github.com/joomla/volunteers.joomla.org/commit/2c5ab70bba8df9e24f91b1ed351a612c09ab1bf1
