### ISSUE TITLE
[jorg] 

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#222]
https://www.joomla.org/about-joomla/contribute-to-joomla.html

Click on "about".  Click on "contribute".  

Content changes, menu item says "about" in both cases.

Small issue but a usability one.  People may think the page hasn't changed or they have navigated to the wrong place.  Just a bit untidy, should be easy to fix I imagine.

**Comment by MATsxm** [comment]
Fixed - Thanks
Closing - Open agian if needed

**Comment by uglyeoin** [comment]
Awesome, that was fast.  Good job.
