### ISSUE TITLE
[jforum] PHP Warning "Delimiter must not be alphanumeric or backslash"

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-websites#226]
The following error displays multiple times in the forum
http://forum.joomla.org/viewtopic.php?f=715&t=827793
``
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 730: preg_replace(): Delimiter must not be alphanumeric or backslash
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 730: preg_replace(): Delimiter must not be alphanumeric or backslash
``

**Comment by MATsxm** [comment]
Seen on Glip that Ken and Olaf are working on it.
Thanks

**Comment by brianteeman** [comment]
Should be fixed now

**Comment by photodude** [comment]
Looks fixed to me, Thanks.
