### ISSUE TITLE
[jevnt] SobiPro incompatiblity with Joomla template

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#227]
The use of SobiPro icon CSS on this site causes CSS rule conflicts with the Joomla template.  This can be seen on the JET application form.

**Comment by Radek-Suski** [comment]
Can you elaborate? It's actually uses FA3

**Comment by mbabker** [comment]
Just look at the mega menu and the missing icons (Joomla logo at the left and globe at the right)

**Comment by Radek-Suski** [comment]
oh, I see it. That's weird. It's actually should be namespaced

**Comment by mbabker** [comment]
It's also fair to point out that Sobi's bootstrap.css is overloading the template's CSS rules (look at your submit button compared to all the flat buttons in the template or inspect the various alerts in a debug console and look at the load order and what's overridden).  In theory you shouldn't be loading your own Bootstrap library here...

**Comment by Radek-Suski** [comment]
Yeah. I since 1.2 we can actually disable it. I will try to do it on weekend but I need to go through all sites then

**Comment by Joomv** [comment]
Dealt with.

 

Turned off FA in Sobi and changed icon call to use built in icon class.

**Comment by mbabker** [comment]
:+1:
