### ISSUE TITLE
[appscdn] ssl certificate 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#228]
See https://github.com/joomla/joomla-cms/issues/9259#issuecomment-190353898

**Comment by andrepereiradasilva** [comment]
i think this is the same has https://github.com/joomla/joomla-websites/issues/212

**Comment by andrepereiradasilva** [comment]
forget my last comment (i erased) that's another server ...

**Comment by mbabker** [comment]
Rochen addressed this.
