### ISSUE TITLE
[jdocs] Template footer obscures content

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#230]
To test go https://docs.joomla.org/Combo_form_field_type
Depending on your browser height some of the content may already be obscured at the bottom. If not manually resize the browser height

![bw6o](https://cloud.githubusercontent.com/assets/1296369/13460556/40b8ea5e-e073-11e5-95b5-44405c039200.png)

**Comment by brianteeman** [comment]
Weird as it doesnt happen all the time but it is repeatable. I think it is something to do with th sharethis code snippet

**Comment by Sandra97** [comment]
Known issue. It happens sometimes on pages with few content.

**Comment by MATsxm** [comment]
@Hutchy68 
still relevant + the issue with the "Twitter Follow us"...

**Comment by Hutchy68** [comment]
do a hard reload of the page to reload resources and let me know if it now fixed :smile:

**Comment by MATsxm** [comment]
I like your "hard" reload :stuck_out_tongue_closed_eyes: 
Works :+1: - Thanks
Closing - reopen if needed
