### ISSUE TITLE
[All] https configuration

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#231]
Following @mbabker unfortunately closed before finalized issue (https://github.com/joomla/joomla-websites/issues/20) made a SSL configuration test to most joomla domains.
Used SSL Labs Server scan for that: https://www.ssllabs.com/ssltest/

Below are the results. Click the links in the grades for detailed results.

| Domain | Forced | Grade | Observations |
| :-- | :-: | :-: | :-- |
| joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=joomla.org&hideResults=on) | Sha-1 intermediates certs |
| api.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=api.joomla.org&hideResults=on) | - |
| appscdn.joomla.org | 🔴 | [**Grade A-**](https://www.ssllabs.com/ssltest/analyze.html?d=appscdn.joomla.org&hideResults=on) | no forward secrecy, incorrect cert order |
| cdn.joomla.org | 🔴 | [**Grade A-**](https://www.ssllabs.com/ssltest/analyze.html?d=cdn.joomla.org&hideResults=on) | no forward secrecy, incorrect cert order, only SNI |
| certification.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=certification.joomla.org&hideResults=on) | - |
| community.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=community.joomla.org&hideResults=on) | - |
| conference.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=conference.joomla.org&hideResults=on) | - |
| demo.joomla.org | ✅ | [**Grade C**](https://www.ssllabs.com/ssltest/analyze.html?d=demo.joomla.org&hideResults=on) | several issues |
| developer.joomla.org | ✅ | [**Grade C**](https://www.ssllabs.com/ssltest/analyze.html?d=developer.joomla.org&hideResults=on) | several issues |
| docs.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=docs.joomla.org&hideResults=on) | - |
| downloads.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=downloads.joomla.org&hideResults=on) | Sha-1 intermediates certs |
| events.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=events.joomla.org&hideResults=on) | - |
| exam.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=exam.joomla.org&hideResults=on) | - |
| extensions.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=extensions.joomla.org&hideResults=on) | Sha-1 intermediates certs |
| extensionscdn.joomla.org | ✅ | [**Grade A-**](https://www.ssllabs.com/ssltest/analyze.html?d=extensionscdn.joomla.org&hideResults=on) | no forward secrecy, only SNI |
| forum.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=forum.joomla.org&hideResults=on) | Only SNI |
| framework.joomla.org | ✅ | [**Grade C**](https://www.ssllabs.com/ssltest/analyze.html?d=framework.joomla.org&hideResults=on) | several issues |
| help.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=help.joomla.org&hideResults=on) | - |
| issues.joomla.org | ✅ | [**Grade C**](https://www.ssllabs.com/ssltest/analyze.html?d=issues.joomla.org&hideResults=on) | several issues |
| joomlacode.org | - | [**Error**](https://www.ssllabs.com/ssltest/analyze.html?d=joomlacode.org&hideResults=on) | Certificate name mismatch |
| magazine.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=magazine.joomla.org&hideResults=on) | - |
| opensourcematters.org | - | [**Error**](https://www.ssllabs.com/ssltest/analyze.html?d=opensourcematters.org&hideResults=on) | Certificate name mismatch |
| resources.joomla.org | 🔴 | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=resources.joomla.org&hideResults=on) | - |
| shop.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=shop.joomla.org&hideResults=on) | - |
| showcase.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=showcase.joomla.org&hideResults=on) | - |
| tm.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=tm.joomla.org&hideResults=on) | - |
| update.joomla.org | 🔴 | [**Grade A-**](https://www.ssllabs.com/ssltest/analyze.html?d=update.joomla.org&hideResults=on) | no forward secrecy |
| vel.joomla.org | ✅ | [Grade A+](https://www.ssllabs.com/ssltest/analyze.html?d=vel.joomla.org&hideResults=on) | - |
| volunteers.joomla.org | ✅ | [Grade A](https://www.ssllabs.com/ssltest/analyze.html?d=volunteers.joomla.org&hideResults=on) | - |
| joom.la | - | [**Error**](https://www.ssllabs.com/ssltest/analyze.html?d=joom.la&hideResults=on) | Certificate name mismatch |

**Comment by mbabker** [comment]
Eh.  Hosting will help to address those issues before JED or JRD get on the
HTTPS only bandwagon.

**Comment by mbabker** [comment]
Reading at more than a quick glance now.  To my knowledge, the project does not have SSL certificates for the `joomlacode.org`, `opensourcematters.org`, or `joom.la` TLD's.  The forum uses CloudFlare for a CDN service which I believe doesn't have any certificate loaded to it.  The rest are basically grouped by service (Grade B is all one server, Grade C is either the demo service through SiteGround or another server with Rochen, JED is on its own server, and each of the CDN endpoints).  Updated the open ticket with Rochen to get what they can update sorted out.

**Comment by mbabker** [comment]
The server with all the Grade B stuff is updated, it just has the SHA-1 intermediates now.  developer/framework/issues are all on an older server which will cap out at a C grade until we get that migrated to the same configuration as the other servers.

**Comment by andrepereiradasilva** [comment]
ok good.

reggarding the sha-1 intermediate cert...

In reality is not an intermediate cert that is with SHA-1 is the root CA cert (GeoTrust Global CA) that the server shouldn't be sending.

The chain of trust is build from the root CA certs installed on every client OS, so every client must have the GeoTrust Global CA certificate for the certificate to be trusted. In conclusion, the server shouldn't send the root CA cert.

**Comment by andrepereiradasilva** [comment]
ok updated the table.

**Comment by andrepereiradasilva** [comment]
Nice to see we have an **A+** now: vel.joomla.org uses HSTS :+1:

**Comment by mbabker** [comment]
@andrepereiradasilva How current is this?

**Comment by sebastienlapoux** [comment]
Added https://showcase.joomla.org into the list. Currently Grade A.

**Comment by andrepereiradasilva** [comment]
- Added tm.joomla.org
- Include a new column (if server support forced HTTPS)

@mbabker all retested today

**Comment by Joomv** [comment]
OpenSource Matters - is now serving SSL.

**Comment by mbabker** [comment]
Everything except JoomlaCode is SSL enforced.  Closing this out.
