### ISSUE TITLE
[joomla.org] Can't update Joomla Version

### ISSUE THREAD

**Issue by ThisIsMeJoana** [joomla/joomla-websites#232]
Hello :) 

Is there any special reason why I can't update my Joomla Site on Vers. 3.4.8?
My Joomla Version installed is 3.4.3. 
The Error says: 
**Update: :Extension: Could not open https://update.joomla.org/core/sts/extension_sts.xml**

Can someone tell me how to fix my problem.

My best wishes,

Joana

**Comment by Kubik-Rubik** [comment]
Hello @ThisIsMeJoana,

this looks like a bad configuration of your server. Does your server use any firewall rules that could restrict loading the update file?

Just take the update package from the official repository and update manually through the installer extension.

To solve the internal update feature, you should check the log files or contact your hosting company!

Greetings

**Comment by ThisIsMeJoana** [comment]
Thanks @Kubik-Rubik :)

**Comment by brianteeman** [comment]
@Kubik-Rubik there IS a problem at our end -  see
https://github.com/joomla/joomla-cms/issues/9281

On 3 March 2016 at 10:22, ThisIsMeJoana <notifications@github.com> wrote:

> Thanks @Kubik-Rubik <https://github.com/Kubik-Rubik> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/232#issuecomment-191695083>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
@brianteeman Yeah, thought that this was fixed already...
@ThisIsMeJoana Okay, it looks like it's not the fault of your server. :-) But you should do the update manually anyway because you use an outdated, vulnerable version.

**Comment by ThisIsMeJoana** [comment]
I know that's why I was looking for help... :D Thanks to both of you @Kubik-Rubik  & @brianteeman 

You're great :+1:
