### ISSUE TITLE
500 Internal Error on submitting form

### ISSUE THREAD

**Issue by InesPaiva** [joomla/joomla-websites#233]
Hi there,

I need help. On submitting my contact form the page returns a 500 internal error. What may be causing this? Thank you

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thanks
