### ISSUE TITLE
[jdev] 

### ISSUE THREAD

**Issue by rushabhmadhu18121987** [joomla/joomla-websites#235]
We have one question ? If We upgrade Joomla 3.1 to 3.4 or 3.5 and for later version, Users table will be truncated or all the data will be as it is ?

Because we are using It so if it has been deleted in the upgrade process we have to store data in another table.

**Comment by MATsxm** [comment]
Hi,
This repository is **ONLY** for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,
Thanks
