### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by lcook7475** [joomla/joomla-websites#236]
I'm trying to use your "Getting Started with Joomla! Guide" https://docs.joomla.org/J3.x:Getting_Started_with_Joomla!#Topics_2 and I can not get any further than the templates section (5.1). I click on "Proceed to Templates" at the bottom of the page which takes me to the Templates section. But there's no where to go once you've finished that page. I went back to the first page (url above) to click on the next topic in the outline (in right hand sidebar) Categories (5.2), and that just takes me to the bottom of that same page where it says "Proceed to Templates". This happens for all categories in that section (Categories, Articles, Menus and Modules). There is no way to get to the other pages.

Please fix this as I found the templates page to be very helpful. I would love to continue reading the rest of the sections.

Thank you

**Comment by Sandra97** [comment]
If you need information about how to use modules, plguin, overrides... You can just use the search system or click on the appropriate links of the Main Page.

**Comment by lcook7475** [comment]
Wow what a rude response. Don't you want to fix the website??? Or would you rather it continue to not work properly?

**Comment by MATsxm** [comment]
It works properly then nothing to fix, at least following your steps and not having a crystal ball to guess what you want to do.
The section 5.1 is just a short summary/glossary of what a template is. 5.2 an anchor to cat and so on.
This is one of the 5,500 pages on the JDoc and for sure there are many about Templates topics.
As said, if you want further information on templates, please try: https://docs.joomla.org/Portal:Template_Management
or pages in Categories in relation with template: https://docs.joomla.org/Category:Template_Management
and the helpscreen pages in relation.

I still do not understand where you want to go once you reach the end of the article but if you have any proposal, please feel free to propose directly on the "Talk page" on the Jdoc or even better, by helping to improve the documentation.
The JDoc is a Wiki system and this way, **YOU** are the editor.

Anyway, this GitHub repository has no vocation to solve content issues on the JDoc. Better tools are available for that on the JDoc.

Thanks
