### ISSUE TITLE
[jmag] CONTRIBUTING AUTHORS THIS MONTH - layout issues 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#238]
See attached screenshot 

![screen shot 2016-03-06 at 20 14 43](https://cloud.githubusercontent.com/assets/1110663/13556360/2b69856a-e3d8-11e5-8c76-2a5250bdfdff.png)

**Comment by JacquesR** [comment]
checking on this thanks

**Comment by helvecio** [comment]
That module is supposed to be displayed on the home-page only.
Assignment fixed. 
Thank you for reporting
