### ISSUE TITLE
[jmag] Article tagged in several cat this causes menu issues?

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#239]
At the moment there are five individual links to this article:
http://magazine.joomla.org/issues/issue-mar-2016/item/2977-three-keys-to-a-successful-joomla-website-building-business

Just wondering if articles should be tagged so much when it is a smaller winter (over here!) issue?

**Comment by MATsxm** [comment]
@helvecio
Could you please take a look at it and tags on the article?
Thanks

**Comment by helvecio** [comment]
The article has been "tagged down" to two itens. Thank you.

**Comment by Hils** [comment]
Thank you @helvecio  & @MATsxm- much better now :)

**Comment by MATsxm** [comment]
Thanks!
