### ISSUE TITLE
[jforum] Error 522

### ISSUE THREAD

**Issue by ribo72** [joomla/joomla-websites#240]
Hello, i am trying to get in to joomla forum and i see this error: Error 522 Ray ID: 27ff5a4f4d4a235a • 2016-03-07 16:17:01 UTC
Connection timed out
It shows:  
You
Browser
Working

Frankfurt
CloudFlare
Working

forum.joomla.org
Host
Error

Can you check it please? thank you

**Comment by MATsxm** [comment]
Looks ok here but I heard there was CDN issues.
Can you still confirm or close?
Thanks

**Comment by ribo72** [comment]
I still have this issue. it shows 
This page (http://forum.joomla.org/) is currently offline. However, because the site uses CloudFlare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by CloudFlare | Hide this Alert

**Comment by xdcc** [comment]
I have the same issue already for about a week now.

joomla.org works fine but as soon as I try to get to the forum I get the 522 Connection timed out error.

**Comment by ribo72** [comment]
Yes it happens only in forum.joomla.org. Also after a test i want to inform that from another internet provider in the same country i can get in, but from the internet provider that i am now i can not.

**Comment by MATsxm** [comment]
@pe7er
I know you were aware about this kind of issues?
Thanks

**Comment by ribo72** [comment]
I am@Ribo in joomla forum
My country is Greece
I made a topic in joomla forum from the another internet provider, but now from this internet provider i can t get in to see if any moderator in the forum saw this issue.

**Comment by pe7er** [comment]
I noticed a similar problem on 2 and 3 March.
In both cases I have created a ticket at the hosting company.

**Comment by ribo72** [comment]
Thank you peter.

**Comment by ribo72** [comment]
Can you open a ticket again please?

**Comment by pe7er** [comment]
Do you have this problem at the moment? Could you please add a screen cap?
Thanks!

**Comment by xdcc** [comment]
Here is a screenshot of the site I keep receiving:

[url=http://postimg.org/image/9ymxf9b49/][img]http://s12.postimg.org/9ymxf9b49/joomlaerror.jpg[/img][/url]

**Comment by xdcc** [comment]
[http://postimg.org/image/9ymxf9b49/](url)

**Comment by ribo72** [comment]
This is when i am not login![1](https://cloud.githubusercontent.com/assets/7744474/13602424/48c0c750-e53f-11e5-8705-8de32a4ffe6c.jpg)
and this is when i login 
![2](https://cloud.githubusercontent.com/assets/7744474/13602440/67e09494-e53f-11e5-910b-a1fa10fca645.jpg)

**Comment by pe7er** [comment]
Thanks! I have just created a new ticket with reference to this topic.

**Comment by ribo72** [comment]
Thank you. If i also see any improvement i will update

**Comment by pe7er** [comment]
Our hosting company Rochen found & removed some firewall blocks within one of CloudFlare's IPv4 ranges. Has the issue been resolved for you?

**Comment by xdcc** [comment]
Yes it works now. Thank you!

**Comment by ribo72** [comment]
Yes it works now, thank you Peter.

**Comment by MATsxm** [comment]
Thanks @pe7er 
I close this issue and open it again if needed.

**Comment by MATsxm** [comment]
Reopen
please see #245

**Comment by pe7er** [comment]
I've created a ticket at the hosting company.
Thanks @MATsxm !

**Comment by MATsxm** [comment]
Seems fixed at this point.
Thanks all
