### ISSUE TITLE
[jrescs] Recaptcha issue on the contact form

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#241]
Hello!

The Repatcha is not displayed on this page: https://resources.joomla.org/en/do-you-need-help

![1](https://cloud.githubusercontent.com/assets/4682328/13584414/ee2be98a-e48c-11e5-84a3-596ad19825e5.png)

**Comment by mbabker** [comment]
The whole site doesn't function correctly using HTTPS.  You must use HTTP until they sort it out.

**Comment by genr8r** [comment]
Needed a component update for our ticketing system to allow nocaptcha.  I also setup new nocaptcha keys tied to the same admin account for JRD gmail.

**Comment by genr8r** [comment]
@mbabker I have the latest jorg template installed and the developer for our georadius component indicated there are updates coming no later than August that include https for all googlemaps urls. In the meantime I am hunting down any other http references on the site that might be causing issues.
