### ISSUE TITLE
[jdev] 503 error when accessing joomla administrators page

### ISSUE THREAD

**Issue by CharishTolentino** [joomla/joomla-websites#242]
Im getting this error after I've login to my website's joomla admin account:

_

**> "Service Temporarily Unavailable
> 
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."**

_

**Comment by rdeutz** [comment]
please use the forum.joomla.org, this repository is for the joomla.org domain website.
