### ISSUE TITLE
[jforum]  Problem with registration and contacting Board Admin

### ISSUE THREAD

**Issue by luiz-bonfa** [joomla/joomla-websites#243]
On March 7 2016 it was impossible to register on Joomla Forum. The widget of choosing the colors matching Joomla Logo did not work at all  (no dragging was available). I tested it on 3 browsers and two computers with the same result. 
Well, next day the bug was fixed. I guess  some people found the way to file their complaint. 

My point is that in cases like this there is no way even to report a problem! Forum does not have well visible contact information for Board Administrator although this "role" is  mentioned hundred times in FAQs. 
I had to address directly Roland Dalmulder, the head of bug team with this complaint and next day he was kind enough to provide the link to github where I had to register again and only then to submit new issue. 

For some reason Joomla makes it extremely difficult for people to provide feedback and bug reports. I believe it is not in the interests of Joomla Community. 

Regards.
Luiz.

**Comment by mbabker** [comment]
Umm... Every (updated) website has a link in the footer directly to this GitHub tracker (or in the case of a couple sites direct to their issue tracking systems) which pre-fills the site you want to report an issue with.  Unfortunately the ones with the older templates don't have this addition, the forum being one of those.

**Comment by MATsxm** [comment]
@pe7er & @ooffick 
Is it also possible to add the "Report an issue" link in the footer?

**Comment by ooffick** [comment]
That has been added as part of the last upgrade.

**Comment by jeckodevelopment** [comment]
@ooffick can we consider fixed the issue?

**Comment by ooffick** [comment]
Yes, the "Report and issue" link is in the footer at the moment: http://forum.joomla.org

**Comment by jeckodevelopment** [comment]
Thank you @ooffick !
