### ISSUE TITLE
[jcomm] Content must be updated by the Translation Team

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#244]
Thanks to the Translation Team to update the page http://community.joomla.org/translations/joomla-3-translations.html and links related.

**Comment by Joomv** [comment]
Mat can you point me at what needs doing?

**Comment by Sandra97** [comment]
Please see with the Translation Team to clean and update the links.

**Comment by Joomv** [comment]
Isn't that you guys? Point me in the right direction.

**Comment by MATsxm** [comment]
https://volunteers.joomla.org/working-groups/translations-working-group

**Comment by Joomv** [comment]
I'm taking it links to joomlacode need updating and links to the forum should point to profiles on VJO?
Let me know exactly and I'll handle it.

**Comment by Joomv** [comment]
email sent to Marijke who I don't seem to be able to tag even though she's on here.

**Comment by marijkestuivenberg** [comment]
First of all, I don't even think I have the permissions needed to edit that page, even though I'm a member of the Translation Coordination Team. I've forwarded your email to MIG who normally maintains this page. Though I don't exactly understand what the issue exactly is, but I figure it might be better to work that out with MIG.

**Comment by infograf768** [comment]
I took myself off the group

**Comment by Joomv** [comment]
Hi @marijkestuivenberg I can sort out permissions or help with the edits.  Let me know which you would prefer.

**Comment by Joomv** [comment]
@marijkestuivenberg  I have checked your permissions by simulating them and I can confirm you have full open and save rights on the Joomla 3 x Translations category where these entries reside.  There are 68 items in that category, The introduction article and then all the languages.  I am happy to help with a chunk of them if someone can tell me what needs doing.  Thanks Rowan.

**Comment by imanickam** [comment]
The page http://community.joomla.org/translations/joomla-3-translations.html has been modified.  The first occurrence of the text string "Translations Working Group" has been linked to the page https://volunteers.joomla.org/working-groups/translations-working-group. 

Other than the above change, it is not clear as to what changes have to be incorporated in both of these pages.  If there are  any specific changes, it would be nice to list them and the team would be glad to review the requested changes and take appropriate actions.
