### ISSUE TITLE
[jforum] PHP Warning "Delimiter must not be alphanumeric or backslash" again

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-websites#245]
Went to this page:
http://forum.joomla.org/viewtopic.php?f=470&t=384884&start=60

Got lots of these:
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 730: preg_replace(): Delimiter must not be alphanumeric or backslash

**Comment by pe7er** [comment]
I've created a ticket at the hosting company.
Thanks for reporting @Bodge-IT !

**Comment by MATsxm** [comment]
Seems ok now
Thanks and closing it

**Comment by pe7er** [comment]
They have restarted the Apache web server & the errors have disappeared.
Thanks!
