### ISSUE TITLE
[jrd] the MailChimp List ID is incorrect... hence, no newsletter

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#246]
Message
COM_CMC_YOU_WERE_NOT_SUBSCRIBED_TO_NEWSLETTER:Invalid MailChimp List ID:

Your Account has been successfully activated. You can now log in using the username and password you chose during the registration.

I did not get enlisted to the newsletter due to an invalid list ID in MailChimp.  You can find it by signing into MailChimp, clicking on Lists > List Settings.  It's top right, you need to copy and paste it into CMC somewhere.  

Bit of a crappy language thing too if you ask me, why is it showing the whole string?

**Comment by MATsxm** [comment]
_Side note: I'll be foreverl amazed that Official J! sites use MailChimp even though they can run one of the best existing newsletter extensions..._

**Comment by uglyeoin** [comment]
I have met resistance this far.  I am developing a template for the JUG team to work with Acy Mailing.  Acy is still pretty good.

**Comment by genr8r** [comment]
@uglyeoin We are between communications coordinators at the moment. I am going to be working hard to get someone new in that role in the next few weeks. When that happens I am going to be making a push for Acy. Would love to have access to your JUG template to work toward a consistent look across Joomla properties and avoid duplicate efforts...

**Comment by jeckodevelopment** [comment]
@genr8r I agree with you about a consistent look across the Joomla properties. 
Please involve @mikeveeckmans and Marketing Team. They can help coming to a common template!

**Comment by genr8r** [comment]
Will do @jeckodevelopment as soon as I have the appropriate personnel lined up on our team for communications. This is my last (currently) outstanding issue for the JRD on github. I am going to leave it open until we have our newsletter items taken care of.  It will likely take a bit as we are only meeting bi-weekly. Feel free to ping me on this if it is sitting too long...

**Comment by jeckodevelopment** [comment]
Thank you @genr8r ;)

**Comment by uglyeoin** [comment]
@genr8r sorry just saw this.  You're welcome to use the template, I got so far as uploading it and trying to test it but the testbed site I was working on couldn't send due to an error.  I'll chase and see if they decided to use it or went elsewhere.  If they're using it then I'll gladly share it, but I'm not 100% sure it will be used.  @mikeveeckmans know's of me, I'll help however I can.

**Comment by genr8r** [comment]
No worries @uglyeoin I am still trying to get a communications coordinator for our team...
1. find someone to own that process
2. switch over to acymailing (with a marketing team compliant template)
3. communicate more effectively with the overall Joomla community about JRD happenings
As soon as I get step 1 taken care of I will start getting peskier about step 2.

**Comment by uglyeoin** [comment]
I think we need an email team in general.  I don't think it should be specific to the JRD happenings. I do email marketing for a living, I have been surprised at the lack of comms from Joomla! and I know many others are too.  

From what I hear we're not allowed to use the data we already have.  That doesn't mean we cannot use new data that arrives if we change our terms or similar.  It's not like I'm asking to sell the data but we can't even communicate with our own stakeholders, many of whom would actually like us to communicate with them (and give us permission).  Moreover these guys are our biggest sales force, and we simply don't empower them properly.  I see it as a fundamental flaw in our marketing effort, but I'm sure there are a 101 good reasons as to why it's not happening that I don't know/understand.

**Comment by brianteeman** [comment]
Pretty much 100% off topic

**Comment by genr8r** [comment]
Uninstalled CMC Mailchimp component
