### ISSUE TITLE
[jconf] link to site is broken

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#247]
https://github.com/joomla/joomla-websites

Click on the conference link.  You get a 404.

As another issue, and this may not be our fault but GitHubs fault.  I submitted an issue, went to the above page, tried to submit a second issue, the first issue still showed.  Despite teh fact I was submitting an issue for a different joomla asset.  Possibly browser cache.

**Comment by MATsxm** [comment]
Fixed - Thanks
Closed
