### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by rosiserem** [joomla/joomla-websites#248]
Could you kindly return the print and email icons to the way they used to be instead of a drop down arrow, which regular users may not easily understand that they can access those icons there. Thanks

**Comment by MATsxm** [comment]
can you please be more specific, on what official Joomla! site?

**Comment by rosiserem** [comment]
On Joomla 3.X

**Comment by MATsxm** [comment]
Then I guess you are refering to a core template feature.

Anyway, this is not the place for this kind of discussion as this repository is **ONLY** for reporting issues with the *.joomla.org official websites, not about the Joomla CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thanks
