### ISSUE TITLE
[jvols] Please add RSS to group reports

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#249]
It would be fun to have RSS feeds in the [Reports page](https://volunteers.joomla.org/reports) (for all reports)  and in specific-team reports page. 
RSS could be integrated on websites, each team can activate a module that shows team's activity in Volunteer portal.

**Comment by sanderpotjer** [comment]
Thanks for the feature request. This is now available for the Reports page and for each team individually:
<img width="1022" alt="screen shot 2016-08-19 at 23 06 53" src="https://cloud.githubusercontent.com/assets/522834/17824355/bf2de30c-6661-11e6-8366-fb76a29ad066.png">
<img width="944" alt="screen shot 2016-08-19 at 23 07 08" src="https://cloud.githubusercontent.com/assets/522834/17824358/c3170c64-6661-11e6-8f35-ae6be0628516.png">

**Comment by jeckodevelopment** [comment]
Great! Thank you @sanderpotjer
