### ISSUE TITLE
[showcase] Showcase website Reset Password Process

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#25]
Error messages on the showcase website shows in the middle of the screen under other "Recently Added" showcase websites.

![Error message](http://s18.postimg.org/v0etf14w9/Screen_Shot_2015_08_06_at_7_12_16_am.png)

Replicate by logging into the website with an incorrect username and password.

**Comment by sebastienlapoux** [comment]
Please close this item it concerns the old site.

**Comment by MATsxm** [comment]
closed on request
