### ISSUE TITLE
[jorg] some layout issues on mobile 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#251]
![image](https://cloud.githubusercontent.com/assets/1110663/13827077/025d1c32-ebbb-11e5-8024-709877731ba4.png)
![image](https://cloud.githubusercontent.com/assets/1110663/13827078/029b42d2-ebbb-11e5-8410-f4b15724289a.png)

See the right margin. Not only it seems to be to large but it's also different in an article than on the main page

**Comment by Sandra97** [comment]
I have the same margin in an article as on the main page. Could you give me your screen resolution, it might help.

**Comment by Sandra97** [comment]
And thanks also to indicate me your browser and what's your phone (OS, I guess)

**Comment by mikeveeckmans** [comment]
Safari , iPhone 6 ....


On 16 Mar 2016, at 21:37, Sandra97 <notifications@github.com<mailto:notifications@github.com>> wrote:


And thanks also to indicate me your browser and what's your phone (OS, I guess)

-

**Comment by MATsxm** [comment]
This is the why :p ;)
@Sandra97 check the link about Tiny

**Comment by Radek-Suski** [comment]
Safari, iPhone 5s

**Comment by Sandra97** [comment]
I'm on it. Will do my best.

**Comment by Radek-Suski** [comment]
Thank you :D

**Comment by Sandra97** [comment]
I'm back. I solved an horizontal scrolling issue. Hope it will be better now, at least for the homepage, still have to work on the article pages.

**Comment by Sandra97** [comment]
@Radek-Suski: good news, we discovered another issue and fixed it. Bad news, I don't know if it will solve your specific issue. Please check (at this point homepage, news page, RC4 and RC3 articles)  and let me know.

**Comment by Radek-Suski** [comment]
It’s perfect now. Thanks a lot :)

Radek Suski
Joomla! Events Team Leader | JET Team Leader | Joomla! Social Media Team Member 
http://events.joomla.org | http://www.joomla.org

Twitter | Facebook | Google+ | : http://radek.sigsiu.net
Blog: http://radeks.coffee
Email:  radek.suski@community.joomla.org / radek@suski.eu

**Comment by MATsxm** [comment]
Thanks
Closed - reopen if needed
