### ISSUE TITLE
[jcertif] Maqma Helpdesk incompatible with Joomla template

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#252]
The Maqma Helpdesk component is loading its own version of Bootstrap which is breaking the Joomla template, as seen on https://certification.joomla.org/support/department/support-services

**Comment by jeckodevelopment** [comment]
If Maqma's version of bootstrap is disabled (from the Control Panel of the Component), buttons of the component don't work anymore.

**Comment by mbabker** [comment]
:facepalm:

I hate hearing about extensions with these kinds of issues...

**Comment by jeckodevelopment** [comment]
Completely agree. A member of the COT is currently looking at this issue. Suggestions are welcome! ;)

**Comment by mbabker** [comment]
I'd say start putting company's feet to the fire and making them write stuff that won't break if you turn off options they provide, but I'm rather cynical and blunt with my opinions about how extensions should work :wink:

**Comment by Joomv** [comment]
I have it running fine on the cjo sandbox.  you just need to work around it.

**Comment by Joomv** [comment]
I also take it that the idea of a centralised helpdesk is now in tatters are people are setting up separate instances of Maqma

**Comment by Joomv** [comment]
Actually I take back the previous posts.  This is in-fact a train wreck all round.  I have contacted Pedro.

**Comment by Joomv** [comment]
[CS-4441822424_component.zip](https://github.com/joomla/joomla-websites/files/179333/CS-4441822424_component.zip)
 Install this and tick the bootstrap 3 fix option.  Can confirm that this renders the buttons working when bootstrap is disabled in the component.  Obviously the layout is still bootstrap 2 but it works.

**Comment by jeckodevelopment** [comment]
we've currently the version 4.2.2.
You uploaded the version 4.2.0. Should we use an outdated version?

**Comment by artisanwebandprint** [comment]
FYI, for the JRD (Resources Directory Help Desk), we left Maqma due to similar issues and received a free subscription to RS tickets pro which works really well. We give them credit on our About page as a contributor to the project (without a link), just a mention.

Best of luck.

**Comment by jeckodevelopment** [comment]
Developers of Maqma granted to the Certification Team a free license of the component, so credit is not an issue :)

**Comment by artisanwebandprint** [comment]
I understand the credit isn't the issue. From what I've read, it's the way the software is built and how it works that is the problem. For the same reason, we had to stop using Maqma and move into RS Tickets which has been wonderful. We have different teams, auto responses and more so the features are great, plus it has bootstrap 3, bootstrap 2, Ukit and their own responsive framework or the ability to choose your own. So I think it's worth looking into.

Best,

Dawn

**Comment by Joomv** [comment]
I was in a hurry this morning - didn't notice the version number.  you are correct.  I've thrown this back at Alex and also asked why Pedro loads his JS and CSS in the body and not in the head (I can hear Michael screaming from here already). 

When you migrated from Maqma to RS was there an import mechanism or did you have to start again from scratch?  CJO may well be stuck with Maqma for historical reasons, but with development at a standstill on it and issues a plenty, the Certification team may well be served by looking at RSTPRO.

**Comment by jeckodevelopment** [comment]
Hi Dawn,
thank you for your suggestions. We'll consider also RS Tickets.
Hi @Joomv , so are you going to provide the fix?

**Comment by Joomv** [comment]
I've thrown it back at Maqma.

**Comment by artisanwebandprint** [comment]
I've created a support ticket to RS Tickets to see if there is an import or migration path. From their forums it does look like we could do a database transfer using something like Roland's component CSV.

Dawn

**Comment by jeckodevelopment** [comment]
We don't need migration tools or methods, we launched our ticket system just few days ago, so no tickets to migrate ;)

**Comment by SpiritJC** [comment]
We (TLWG Team) have the same issue.

**Comment by jeckodevelopment** [comment]
András fixed CSS, now it works properly. I'll close the issue.
