### ISSUE TITLE
[jorg] embedded video and suggestions

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#253]
Hi, can we add the following string to the embedded video code : ?rel=0

So the code will be : 
iframe width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen" src="https://www.youtube.com/embed/HMRM7CTnFAA?rel=0"

It will stop showing suggested video's , especially when one of them is a cheering video for WP ;-)
Thank you @matthewbaylor for spotting this.

**Comment by Sandra97** [comment]
Done Thanks. 
Closed. Re-open if needed.
