### ISSUE TITLE
[joomla.org] Banner image

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#254]
Even if this homepage is supposed to be redesigned, would it be possible for the Marketing Team to provide a temporary new and up to date image for the homepage? Thanks!

**Comment by mikeveeckmans** [comment]
the top image ?

**Comment by Sandra97** [comment]
Yes.

**Comment by mikeveeckmans** [comment]
on it. which size(s) do you need ?

**Comment by Sandra97** [comment]
You can do the new ones with the same size as the current ones: 
- 2000x386
- 1020x386

**Comment by mbabker** [comment]
Even better if you optimize it for each of the 3 template breakpoints it shows on :wink:

**Comment by Sandra97** [comment]
Agree, would be even better! 
@mikeveeckmans, I'll indicate you the exact size for the 3 pics.

**Comment by mikeveeckmans** [comment]
Thank you!

**Comment by Sandra97** [comment]
@mikeveeckmans, here the sizes:  
- Pic 1: 1920x386 (displayed on screens as of 980px)
- Pc 2: 979x386 (screens from 768px to 979px)
- Pic 3 : 767x386 (screens from 481px to 767px)
If possible, when done, could you send me the PSD?

**Comment by designbengel** [comment]
Can we place the text completely in the header module?

**Comment by Sandra97** [comment]
You mean adding HTML text in the module and not putting it on the image? If it's this, I fully agree.
PS: I don't know why, but MAT keeps asking 'pass me the milk'. Weird

**Comment by designbengel** [comment]
please check the draft - open for suggestions!
I think the buttons need at least a bit explanation 

![joomlaorg_header_01](https://cloud.githubusercontent.com/assets/828371/14413444/5af404a0-ff7a-11e5-80cd-197419c625f3.jpg)

**Comment by Sandra97** [comment]
I like the left part (MAT too). Not really fan of the right part. 
I think we should keep some "screens" on the right (not the one we currently have, not modern at all). 
And of course, '50 million' is (hopefully) out of date and no need to mention twice 'extensions' ;)

**Comment by Hils** [comment]
A comment on colours: 
the colours of the two download buttons on that screenshot, and the two demo buttons, really should be the same but I guess you have that planned.

One of our crowning glories is our logo - shouldn't the main logo on the main page be in colour?

**Comment by Sandra97** [comment]
Just a note... We're not in charge of the re-design of the homepage (another team is in charge of it). My concern is to have a header image that can be displayed correctly on smartphones and tablets and which presents up to date information.

**Comment by Hils** [comment]
Understood @Sandra97 - I was replying to this :

"please check the draft - open for suggestions!" from @designbengel

**Comment by designbengel** [comment]
@Hils I think the Logo is also in colour at the top, and i try to leave the new header as solid as possible. Thank you for the remarks regarding the button-colour!

**Comment by Sandra97** [comment]
New header is implemented.
Closing this issue.
Re-open if needed.
