### ISSUE TITLE
[jcertif] [jexam] use of 'Proctor' which means different things in UK & North America

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#257]
Reading the home pages of certification & exam sites; I notice that the word 'Proctor' is used for what an en-GB native speaker would call an Invigilator. As Joomla's official language is en-GB and the fact that a Proctor in the UK is mainly disciplinary, I suggest it would be better to change this for something more appropriate eg Invigilator.  Thank you.
 
**proctor**
1.
BRITISH
an officer (usually one of two) at certain universities, appointed annually and having mainly disciplinary functions.
2.
NORTH AMERICAN
an invigilator at a university or college examination.

**Invigilator**
http://www.dictionary.com/browse/invigilator

**Comment by Hils** [comment]
... or just keep it simple with the widely understood 'Supervisor' ?

**Comment by jeckodevelopment** [comment]
Hello Hils,
thank you for your precious suggestion.
I'll talk about this with the Certification Team and we will decide what to do.

**Comment by Hils** [comment]
Thank you Luca :)

**Comment by jeckodevelopment** [comment]
Hi @Hils 
Certification Operations Team decided to use "**Supervisor**" instead of "**Proctor**". 
Thank you for collaboration!

**Comment by Hils** [comment]
Thank you for considering and implementing that Luca & Team. Noting also how well the Certification Operations Team is working and reporting back to the Community in an efficient & open way - thank you!
https://volunteer.joomla.org/reports/208-certification-operation-team-meeting-notes-24-marc
