### ISSUE TITLE
[jdev] Incorrect trademark use

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#259]
The name of the website is not currently compliant with the Joomla! Trademark rules.
Missing TM indication at the end of the name!

**Comment by mbabker** [comment]
Added

**Comment by MATsxm** [comment]
the TM indica is not a legal obligation unless the TM is registered and then should be used in the first prominent use (see the Joomla! at the top).
BTW, when you claim a property, it is always better to use it even if, legaly speaking, it is just a question of reversing the burden of proof.
