### ISSUE TITLE
Hosting link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#26]
On most sites the footer has the word/logo Joomla Hosting by Rochen - makes sense
On others the footer link is just plain text Joomla Hosting by Rochen Ltd. - OK but not consistent
On some other sites the footer just has the word/logo Rochen without any reference - looks odd and out of context

### Example www
![pvho](https://cloud.githubusercontent.com/assets/1296369/9098900/880d6172-3bc4-11e5-869a-a1194b028f33.png)

### Example /3
![pvho 1](https://cloud.githubusercontent.com/assets/1296369/9098904/9c7e5a12-3bc4-11e5-87bc-c8f9937bb25f.png)

### Example extensions
![zik1](https://cloud.githubusercontent.com/assets/1296369/9098942/d20d9ada-3bc4-11e5-8a7a-2a7b8fcbc522.png)

**Comment by mbabker** [comment]
Part of the original design decision on the 3.x template was to remove the graphics from the footer.  So if we stuck with that, "Joomla Hosting by Rochen" (without the Ltd.) would at least be consistent with how it reads on the sites that haven't upgraded yet.

The Framework site is another one with a "unique" footer setup as far as that goes.

![screen shot 2015-08-05 at 6 02 25 pm](https://cloud.githubusercontent.com/assets/368545/9099123/37cdfe38-3b9c-11e5-9857-6afca22ef358.png)

**Comment by mbabker** [comment]
Since I'm building the "Report an issue" links in to the 3.x template footer, we have a chance to get it standardized in short order.  With the new link and "Ltd" removed from Rochen's link, this is the footer on the developer site (live right now actually):

![screen shot 2015-08-05 at 7 28 38 pm](https://cloud.githubusercontent.com/assets/368545/9100381/466cb40a-3ba8-11e5-8669-cb276f7fba7e.png)

Unless there's some preference from Rochen in how the name is displayed in text, IMO that'd be the way to go.

**Comment by Hutchy68** [comment]
Last I remember, Brad contacted me when Rochen reworked their logo and asked to use it. Not sure if he contacted everyone managing a domain. Another alternative is asking if we can add text to a logo image like this:

![rochen_footer_hosting_by_white](https://cloud.githubusercontent.com/assets/3527469/9150510/7271b448-3daa-11e5-9827-e2800a3e0bce.png)

I like logos, personal choice, as it shows a brand element. Either way, just need to know where Rochen stands on this.

**Comment by mbabker** [comment]
And we updated the logo uses when they launched their new brand.  If they want us to use the logo in the 3.x template then we can figure out how to work that in.  I think either way someone should ask Brad to check with his bosses on the final preference; it is their link.

**Comment by brianteeman** [comment]
Probably should also check first with Joe before Rochen to find out what
the contractual agreement is. No point giving them more than they have paid
for

**Comment by Hutchy68** [comment]
😀

**Comment by Hutchy68** [comment]
Email to Joe sent

**Comment by Hutchy68** [comment]
Update, it is being worked on. Joe is investigating further.

**Comment by mbabker** [comment]
Any word?

**Comment by Hutchy68** [comment]
I'll send a reminder. I think it's been long enough and there should be an answer even if it's "we don't know."

**Comment by mbabker** [comment]
Given the lack of response, the template update is being deployed with the "Joomla Hosting by Rochen" text.  If any changes need to be made a new issue should be submitted.

**Comment by MAT978** [comment]
:+1:

**Comment by mbabker** [comment]
Seems the Capital Team wants to revisit this...
