### ISSUE TITLE
[jed] Bug with the error.php tpl

### ISSUE THREAD

**Issue by inverser-pro** [joomla/joomla-websites#261]
http://extensions.joomla.org/extensions/clients-a-communities/project-a-task-management#
not work menu, log js error!
see this img:
http://f.usemind.org/2016-03-21_211552.jpg

**Comment by jeckodevelopment** [comment]
Let me report this bug in the official JED issue tracker.

**Comment by jeckodevelopment** [comment]
Already in JIRA:
https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-1036

**Comment by MATsxm** [comment]
hehe :wink: 
thanks anyway

**Comment by MATsxm** [comment]
Please follow the process on: https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-1036
Closing it but reopen if needed.
Thanks
