### ISSUE TITLE
[jorg] redundant host names

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#262]
Following issue was reported by google for analytics : 
Redundant Hostnames
Property joomla.org is receiving data from redundant hostnames. Some of the redundant hostnames are:

    joomla.org
    www.joomla.org

Redundant hostnames are counted as separate rows in reports, so hits that are going to the same page on your site from different hostnames will be split into multiple rows. With data split across multiple rows, traffic to specific pages will appear lower than it actually is.

To avoid this problem, consider setting up a 301 redirect from one of your redundant hostnames to the other, or create a search-and-replace filter that strips "www." from hostnames.

Google Tag Assistant Recordings can help you verify that your redirect is setup correctly, or that your filter is working as intended.

**Comment by mbabker** [comment]
There's already a 301 in the .org .htaccess for non-www to www.  The /3 landing page doesn't have said redirect.

**Comment by mikeveeckmans** [comment]
Google is still throwing this issue for the main domain...

**Comment by mbabker** [comment]
So fix it?  The main site's .htaccess already redirects non-www to www, so
if there's still traffic for both, it's coming from the /3 site.

**Comment by mikeveeckmans** [comment]
could you give me access then ?

**Comment by mbabker** [comment]
Use Admin Tools?  I've still got no internet so I can't do much.

**Comment by mbabker** [comment]
Fixed
