### ISSUE TITLE
[j3] Duplicated name of volunteer

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#263]
In this page: https://www.joomla.org/3/joomla-3-5-thankyou
Section: **Our Tireless Contributors & active Bug Squad members**
the name of Nicola Galgano appears 2 times. 
![j3-dupl](https://cloud.githubusercontent.com/assets/733133/13939180/ff21f396-efd2-11e5-9bf1-a1e85df5db74.PNG)

**Comment by MATsxm** [comment]
done - Thanks
