### ISSUE TITLE
[jforum] 

### ISSUE THREAD

**Issue by ribo72** [joomla/joomla-websites#264]
![cap](https://cloud.githubusercontent.com/assets/7744474/13943945/cb80c738-f009-11e5-9d6a-8825e6e848aa.jpg)
Hello, today i tryed to get in the forum and i cant get in,
I have this error: Error 524 Ray ID: 2877958d4f6d1ab1 • 2016-03-22 06:30:15 UTC
The last time i had similar issue @pe7er created a ticket to host and it was a block from firewall. Can you please check it? Thank you

**Comment by ribo72** [comment]
The issue is not the same like the previous time because i can t get in to from different internet provider and maybe was not the same error

**Comment by ribo72** [comment]
I don t know if someone fix this issue but it fixed so i close the ticket

**Comment by pe7er** [comment]
Thanks @ribo72 
This morning I created a ticket when I noticed the forum was down. 
According to the hosting company, it was a DNS related issue and they restarted the service which fixed the problem.
