### ISSUE TITLE
[jdocs] standardize the dates on the version history pages

### ISSUE THREAD

**Issue by mcspencehouse** [joomla/joomla-websites#266]
Would it be possible to standardize how the dates are listed on the version history pages?
Thanks!

**Comment by MATsxm** [comment]
@mcspencehouse 
Hello,
As a Wiki, you are invited to participate/edit/improve the Joomla! Documentation directly on the JDoc website. 
Regarding the content, thank you to make the changes directly on the site or to propose your changes on the "Talk" section of the relevant page.
Thanks

**Comment by mcspencehouse** [comment]
Thank you for your response. I have a script to parse the links at the bottom of the https://docs.joomla.org/Category:Version_History page for each Joomla version and release date. The date format varies depending on the release and I keep having to tweak my script. I just signed up for a Documentation account as you suggested and I will see what I can do to contribute! Thank you for the advice!

**Comment by MATsxm** [comment]
if you mean the format that changed between the 3.2 and the 3.3, then the changes of the support cycle process should be the explanation, please see: https://docs.joomla.org/Release_and_support_cycle

**Comment by mcspencehouse** [comment]
I'm talking about the dates that are printed on each version history page.
For 1.5 through 3.0 it's Day FullMonthName Year
Then 3.1 through 3.4 if Day MonthAbrviated Year
Then 3.5 had the day as "21st" rather than "21"

**Comment by MATsxm** [comment]
@mcspencehouse 
Oh, ok, I've seen your inner change for the "21" and validate it.
When it's ok, Thanks you to close this issue

**Comment by MATsxm** [comment]
Closed - reopen if needed
