### ISSUE TITLE
Stats API is getting very slow

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#267]
Access https://developer.joomla.org/stats

It took 15 seconds just to load the json.

**Comment by mbabker** [comment]
Well aware... https://github.com/joomla-extensions/jstats-server/issues/23

**Comment by andrepereiradasilva** [comment]
ok will close it then

**Comment by mbabker** [comment]
Got the cache layer set up.  Speed's back to a suitable level now.

**Comment by andrepereiradasilva** [comment]
15000 ms to 250 ms ... nothing like a good server side cache ;)

**Comment by mbabker** [comment]
> 250 ms

I wish we could get that server bumped to PHP 7.  With the full stats database on my localhost with PHP 7, a cache hit is served in 30ms.  It could easily be something near 100ms on a remote box.

**Comment by andrepereiradasilva** [comment]
if you use web server (nginx, for instance) or other proxy cache you don't need to upgrade php since the cache process doesn't even uses php.
but, of course, is more hard to manage the caching process.

**Comment by mbabker** [comment]
That's why the hosting companies get paid the big bucks and I just write free software :laughing:

**Comment by andrepereiradasilva** [comment]
:smile:
