### ISSUE TITLE
[jorg] twitter cards update

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#268]
Twitter updated the settings for the twitter cards : https://business.twitter.com/help/advertiser-card-specifications .
Tweet copy: 116 characters are available (24 characters are used for images)

Website title length: 70 characters. Please note - depending on device and app settings this description may truncate. Although not guaranteed, limiting the description to 50 characters should ensure that truncation won’t occur across most devices.

**Image size: 800 x 320 pixels (max 3mb)**

File types: PNG and JPEG are recommended. We do not accept BMP or TIFF files.

**Comment by Sandra97** [comment]
@mikeveeckmans: I guess the MWG will provide the Twitter image and the general description

**Comment by mikeveeckmans** [comment]
We will

**Comment by designbengel** [comment]
oops... found in my todos at the very bottom - will deliver asap!

**Comment by designbengel** [comment]
![joomla_twitter_card](https://cloud.githubusercontent.com/assets/828371/14941850/e408a116-0faa-11e6-9a4d-ba672d5878d6.jpg)

**Comment by mbabker** [comment]
Uploaded... https://cdn.joomla.org/images/joomla-twitter-card.jpg

**Comment by MATsxm** [comment]
Ooops
![096a16960](https://cloud.githubusercontent.com/assets/1972717/14944216/739a40aa-0fba-11e6-9bc9-3191d0b54d6a.png)

**Comment by designbengel** [comment]
![joomla_twitter_card](https://cloud.githubusercontent.com/assets/828371/14944278/a14b8110-0fee-11e6-89eb-0e1b1c492a8c.jpg)

**Comment by mbabker** [comment]
@mikeveeckmans what kind of card did you spec out?  We're using the "Summary card with large image" card type which has different specs than what you posted originally.

**Comment by mikeveeckmans** [comment]
https://business.twitter.com/help/advertiser-card-specifications .

**Comment by Sandra97** [comment]
@mikeveeckmans: We're currently using this: https://dev.twitter.com/cards/types/summary-large-image
As far as I understand, your link is about requirements for advertisers so for the sponsored Tweets.

**Comment by mbabker** [comment]
Mike there are 10 types of cards on that page.  I need a specific type.

**Comment by mikeveeckmans** [comment]
The first one... website card

**Comment by mbabker** [comment]
The website card isn't a valid type per https://dev.twitter.com/cards/types

Our template markup has to follow the dev site's guide to implement cards on the main sites.  These card types don't align with the advertiser card specs.

**Comment by Sandra97** [comment]
@designbengel Could you please provide an image that fits Twitter requirements for "Summary Card with Large image"?
Dimensions: at least 280 px by at least 150 px
Aspect ratio: 1.867:1
Less than 1MB.

**Comment by Sandra97** [comment]
As the new image seems to fit to Twitter requirements, I'm closing this issue.
Re-open if needed
