### ISSUE TITLE
You are not permitted to use that link to directly access that page [joomla.org] 

### ISSUE THREAD

**Issue by ferrefatta** [joomla/joomla-websites#269]
Hi there,

In Gantry 5 in the backend (in the "home" outline as an example), when we click on a module instance and then select "To edit the Module please use the Joomla's Module Manager" in order to be redirected to the module itself inside the "module manager", we are not redirected to the module itself but to the list of the "module manager" receiving the following error:

 "Error
 You are not permitted to use that link to directly access that page (#182)."

We contacted Rockettheme support and we received the following answer:
"This is a bug In Joomla 3.5 that another member also reported. I can reproduce this myself too. You need to report this to Joomla."

Regards,

**Comment by Radek-Suski** [comment]
Hi,

This is a tracker for reporting problems with one of the Joomla website owned by the project, for example: Joomla.org. 
If you need support for your website please us: http://forum.joomla.org

Regards,
Radek

**Comment by ferrefatta** [comment]
Ok thank you.

**Comment by brianteeman** [comment]
FYI it is a Gantry bug
Gantry is generating a link such as
/administrator/index.php?option=com_modules&view=module&layout=edit&id=1

which as you saw does not work

The correct link would be
/administrator/index.php?option=com_modules&task=module.edit&id=1

On 29 March 2016 at 13:10, ferrefatta <notifications@github.com> wrote:

> Ok thank you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/269#issuecomment-202834809>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ferrefatta** [comment]
Dear support,
 
Thank you very much.
 
Regards,
 
Date: Tue, 29 Mar 2016 04:28:35 -0700
