### ISSUE TITLE
[TM] Forward to online brand manual

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#270]
Please change this menu item Brand Manual and Limited Use Logos (https://tm.joomla.org/brand-manual-and-limited-use-logos) to https://docs.joomla.org/Joomla:Brand_Identity_Elements 

Thank you 
@spiritjc

**Comment by jeckodevelopment** [comment]
@mikeveeckmans do you suggest to directly link the Docs page?

**Comment by mikeveeckmans** [comment]
discussing this with @jcspirit , will get back to it on monday or tuesday

**Comment by jeckodevelopment** [comment]
From the [Trademark & Licensing Working Group's meeting report](https://volunteers.joomla.org/reports/211-tlwg-meeting-report-april-05-2016):

> Team discussed about a question from the Joomla! Marketing Team about the publishing of the Official Joomla! Brand Manual. https://github.com/joomla/joomla-websites/issues/270 Trademark website will host the Joomla! Brand Manual and a member of the Joomla! Marketing Team will keep it up-to-date. (Marco will contact Mike Veeckmans)

So @SpiritJC will contact you @mikeveeckmans in order to grant you access to the Brand manual page on the tm website.

**Comment by MATsxm** [comment]
any news?

**Comment by Sandra97** [comment]
@mikeveeckmans, any news?

**Comment by MATsxm** [comment]
TLWG will do what ever they want... 
the fact is that the brand manual is updated, translated and consulted on the doc.
Closing - reopen if needed
