### ISSUE TITLE
[TM] Broken links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#271]
https://tm.joomla.org/joomla-license-faq

There are two links that are broken
http://dev.joomla.org/content/view/2336/102/#does-javascript-included-in-templates-and-extensions-need-to-be-licensed-under-the-gpl
http://dev.joomla.org/content/view/2336/102/#does-the-css-in-my-template-need-to-be-licensed-under-the-gpl

@spiritJC

**Comment by marijkestuivenberg** [comment]
I changed the text slightly and linked to the GPL & JED article, since the other content doesn't seem to exist anymore

**Comment by brianteeman** [comment]
Didn't spot it before but the link marked as [1] is also broken

**Comment by marijkestuivenberg** [comment]
Thanks, changed them as well. Unfortunately there is no anchor on that section of the Article on JED.
