### ISSUE TITLE
[jdocs] change link please 

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#272]
https://docs.joomla.org/Joomla:Brand_Identity_Elements 
change the link "request a trademark-use" to https://tm.joomla.org/conditional-use-logos

**Comment by mikeveeckmans** [comment]
and on the same page : please change "trademark policy" to https://tm.joomla.org/trademark-policy

**Comment by mbabker** [comment]
You know this is a wiki, right?

**Comment by mikeveeckmans** [comment]
Yes i know @mbabker , but @Sandra97  told me not to touch it ;-)

**Comment by Sandra97** [comment]
I have changed the links before you ask ;)
The red one is linked to the homepage and the request a trademark use is linked to the contact page

**Comment by Sandra97** [comment]
I'm closing at this point. Re-open if needed. I'll of course check the all series on jdocs

**Comment by SpiritJC** [comment]
Thanks!

**Comment by mikeveeckmans** [comment]
Thank you !
