### ISSUE TITLE
[TM] Support Desk

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#273]
On the contact form https://tm.joomla.org/contact/submit-ticket
There is a select box for the title but there are no options being displayed

@spiritJC

**Comment by brianteeman** [comment]
Sorry for Title = read Subject of email

**Comment by SpiritJC** [comment]
You mean the subject Brian?
You must first select the department.

**Comment by brianteeman** [comment]
Ah I see what you mean now @spiritJC Maybe the text "please select the subject" should be "select the department first"? 

Anyway just a suggestion - maybe others will be like me - I looked at the subject first without realising

**Comment by SpiritJC** [comment]
Good suggestion Brian. Thanks!

**Comment by SpiritJC** [comment]
Changed!
