### ISSUE TITLE
[TM] Make a list of trade marks

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#274]
There should be a list somewhere of the trade marks the Joomla project is claiming that way everyone's on the same page, and somewhere explaining either why these marks are claimed or how the project has decided to apply a mark on these terms.  Personal opinion, claiming a mark on "Joomla! Trademark & Licensing™" seems really excessive here...

**Comment by brianteeman** [comment]
Not really an issue for this list surely ;)

**Comment by MATsxm** [comment]
a good example:
http://www.apple.com/legal/intellectual-property/trademark/appletmlist.html

**Comment by SpiritJC** [comment]
We'll create a list with trademarks as soon as possible and publish it on the TLWG website.

**Comment by MATsxm** [comment]
Still nothing, then let's start with a proposal to be completed.



## Intro Text

A **trademark** can be a word, phrase, symbol, or design that distinguishes the source of the goods or services.

The following is a non-exhaustive list of Joomla’s trademarks and service marks.

For more information on how to use Joomla’s trademarks, refer to the document available in several languages: [Proper use of the Joomla! name](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name) or contact the [Trademark & Licensing Team](https://tm.joomla.org/contact).

Joomla's Trademarks | Type ®™℠ | Note
------- | ------ | ------
Joomla!® | Registered Trademark ® | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Project™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! CMS™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Framework™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Certification Program™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Community Portal™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Developer Network™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Documentation™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! World Conference™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Events Site™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)
The Joomla! Extensions Directory™ | Trademark ™ | [How to use it](https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name)


**To be continued...**

### Note:
- [ ] Intro text + link to haow to use it properly + text and links to the T&L
- [ ] Complete the list
- [ ] Add logos and visuals trademarked + explaination

**Comment by Hils** [comment]
Just a note. Trademarked & Registered where and by which body? A search for Joomla in the UK site just gives JOOMLA! and Joomla! as being registered. https://www.ipo.gov.uk/tmtext/

(Is the Joomla! Community Magazine registered?)

**Comment by Radek-Suski** [comment]
Some more info: 
https://www.ipo.gov.uk/tmcase/Results/4/EU006911127
https://www.ipo.gov.uk/tmcase/Results/4/EU006899009

As far I know, only Joomla! (word and image) are registered. Nothing more and there is no need for it IMHO

**Comment by jeckodevelopment** [comment]
@Hils the Joomla! word and logo are Registered Trademarks in several countries.
The discussion is about the "derived" forms... like the Joomla! Extensions Directory and so on. They're simple trademarks, without registration.

**Comment by jeckodevelopment** [comment]
@MATsxm please fix the first task: "link to how" now it's "haow".

TM Team was working on a list... here are some TMs to be added to your list:

- Joomla! Trademark & Licensing™
- Joomla! Resources Directory™
- Joomla! Volunteers Portal™ 
- The Joomla! Community Magazine™ 
- The Joomla! Community Showcase™ 
- JoomlaDay™
- JDay™

**Comment by MATsxm** [comment]
@jeckodevelopment 
Glad to hear about... After 3 months, just wanted to be the firestarter... and help to fix a list that need no more than 1 hour to be built.
Please see the: "To be continued" and there are also few more to add than the once you have listed.

@Hils
Please see: 
http://tmsearch.uspto.gov/bin/showfield?f=toc&state=4806%3Aq7gy4n.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_tagrepl~%3A=PARA1%24LD&expr=PARA1+AND+PARA2&p_s_PARA2=joomla&p_tagrepl~%3A=PARA2%24COMB&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query

![screenshot-tmsearch uspto gov 2016-07-25 07-04-51](https://cloud.githubusercontent.com/assets/1972717/17099555/191cd7a4-5237-11e6-9321-4708fed2c0ac.png)

**Comment by jeckodevelopment** [comment]
@MATsxm I know that it took a while... TM Team had some troubles to face... but, we should have the complete list very soon.

**Comment by MATsxm** [comment]
Then I have to conclude that firestarter is not enough?

**Comment by jeckodevelopment** [comment]
Meeting this week. I'll update you after the meeting.

**Comment by MATsxm** [comment]
in progress?
5 months? WOW... that will be a beautiful list!

**Comment by SpiritJC** [comment]
YES!! If you want, you can make a list. :-(

**Comment by brianteeman** [comment]
Calm down please

**Comment by MATsxm** [comment]
@SpiritJC Thoughts this: https://github.com/joomla/joomla-websites/issues/274#issuecomment-234818711 was a good start for the TM Team

**Comment by MATsxm** [comment]
to prevent any duplicate (I know, this comment seems unnecessary), I'll do your work this weekend.

**Comment by brianteeman** [comment]
Why?!!

I am sure you have plenty of things that you are responsible for that you
could do if you have the free time.

No point in having teams and areas of responsibility if people are going to
ignore them and just do their own thing.

**Comment by MATsxm** [comment]
@brianteeman 
Oh don't worry... this will not be under **MY** resposability, they will just have to edit and add their name on it... I hope less than 5 minutes of their precious time.
**WE NEED IT!**

**Comment by mbabker** [comment]
We could set up a "do everything" team for the crazies in the room that do all the things, then technically they are working in their area of responsibility.

**Comment by MATsxm** [comment]
Ok then, this is a draft (this is the why it is a user page at this point).
Thank you to check/edit/comment/whatEver about it.
@brianteeman that would be great if you could proofread my Tarzan franglish but do what you want.

**Comment by MATsxm** [comment]
Oooops
the link: https://docs.joomla.org/User:MATsxm/Joomla_Trademarks_List

**Comment by Hils** [comment]
Hello @MATsxm - good work & thanks!

Just a small thing - VEL always used to refer to Joomla! Vulnerable Extensions™ way before the Volunteer Portal was in being. It might have changed whilst I wasn't looking but it would be worth checking with @mandville

**Comment by Hils** [comment]
Sorry!

Typo : More Information about Dsclaimers - last para heading.

**Comment by MATsxm** [comment]
@Hils Oooops sorry my bad
I added the "VEL" on the wrong line :wink: 
Thanks

**Comment by MATsxm** [comment]
Both fixed - Thanks

**Comment by Hils** [comment]
one more! 

**Joomla!'s trademark** and **Joomla’s Trademarks and Disclaime**rs << inconsistency of exclamation mark - in Note

**Comment by Hils** [comment]
symbols and credit lines and/or disclaimers **helps makes** the public aware should be  symbols and credit lines and/or disclaimers **helps make** the public aware

**Comment by Hils** [comment]
A Trademark can be a word, phrase, **symbol, or design** that distinguishes the source of the goods or services
The Oxford comma has been used which isn't in our style guide. Note that it hasn't been used in the sentence before: ... owns and oversees the Joomla! name, logos and trademarks for...

**Comment by Hils** [comment]
trademarks for The Joomla! Project and softwares.

Software is the plural of software ;)

(I think that is it for now - thank you again)

**Comment by MATsxm** [comment]
About the first

> symbols and credit lines and/or disclaimers helps makes the public aware should be symbols and credit lines and/or disclaimers helps make the public aware

is there a better way to not use the possevive form? or I will remove the !

**Comment by Hils** [comment]
darn it - forgot to correct that! It should be : 
symbols and credit lines and/or disclaimers **help** make the public aware

**Comment by MATsxm** [comment]
sorry... bit tired :smile: 
I was talking about possessive form here: 

> Joomla!'s trademark and Joomla’s Trademarks and Disclaimers << inconsistency of exclamation mark - in Note

**Comment by Hils** [comment]
**Joomla!'s or Joomla’s**

This isn't grammatical and comes under the trademark rules. It used to be that the exclamation mark was only used with the first Joomla on the page but now I don't know! Sorry :D

**Comment by Hils** [comment]
I guessed! I am just back home but I thought it would help you get the job done if I had a quick look for you.

**Comment by Hils** [comment]
Request a Trademark-use :

Might be better as Request the use of a Trademark. We wouldn't hyphenate there.

**Comment by MATsxm** [comment]
> This isn't grammatical and comes under the trademark rules. It used to be that the exclamation mark was only used with the first Joomla on the page but now I don't know! Sorry :D

:rage: that's **WRONG AND NOT A PROPER LEGAL USE**.
This is an urban legend as the registered name, agree or disagree is **WITH** the `!`
This rule concerns **ONLY** the use of Trademarks indicia R or TM
:smile: 

The rule here would be that, because it is in a <p> and in conflict with another punctuation sign we should not add the "!".
My question was just because I don't like using "Joomla" in a possessive format then just wanted to know if another way is possible.

**Comment by Hils** [comment]
You shouted at me in **bold** (hehe)

I like the way it is now:
For more information on how to use Joomla’s Trademarks and Disclaimers, please refer to the document available in several languages: Proper use of the Joomla! name or contact the Trademark & Licensing Team.

We can't avoid using the possessive format of Joomla for ever ;)

**Comment by MATsxm** [comment]
> You shouted at me in bold (hehe)

Believe me, it's not in a bad way :wink: Just because I have to "fight" and bang my head at least twice a day evry single day with this wrong belief (people using the "first prohiminent use of blablabla" for the "!" while this concerns ONLY the Trademarks signs) :smile: 

Thanks for the help!

**Comment by Hils** [comment]
I told you I didn't know! But sorry you are getting hassle. It is good of you to pick this job up amongst all the other things you already do.

**Comment by MATsxm** [comment]
I guess all your changes are ok now (need to wait Fuzzybot to do his job for the BTN **Request the use of a Trademark**).

Thanks again

**Comment by MATsxm** [comment]
No more feedbacks?
Anyway, it will be possible, like for every Wiki pages to make changes even if this one will be "protected"

**Comment by MATsxm** [comment]
Merged and available for translation
https://docs.joomla.org/Joomla:Trademarks
As using the namespace Joomla, the content is protected.

**Comment by jeckodevelopment** [comment]
Add to Joomla! Learning Partner the short forms: "JLP" and "JLPs"

Disclaimer is the following:

> Joomla! Learning Partners™ are officially recognized and licensed by, but not organized or operated by, Open Source Matters, Inc. (OSM) on behalf of The Joomla! Project™. Each Joomla! Learning Partner represents an independent company. Use of the Joomla!® name, symbol, logo, Joomla Learning Partner,™ and JLP™ and related trademarks is licensed by Open Source Matters, Inc.

Thank you

**Comment by MATsxm** [comment]
As derivative, there's no legal need but added ;)

**Comment by Hils** [comment]
> Use of the Joomla!® name, symbol, logo, Joomla Learning Partner,™ and JLP™ and related trademarks **is** licensed by Open Source Matters, Inc.

should be **are** licensed

AND

>  Joomla Learning Partner,™ and JLP™ and related trademarks is licensed by Open Source Matters, Inc.

should be, I think, Joomla Learning Partner™, JLP™ and related trademarks are licensed by...

That removes Oxford Comma which is in the wrong place (and we don't use them anyway) and removes extra 'and'.

**Comment by MATsxm** [comment]
Hehehe
I had already changed few things... but looks like it's not enough :wink: 
@Hils 
- is? isn't it the "use"? that is under license?
- done for the commas

**Comment by Hils** [comment]
It is! Sorry - I took it out of context Mat - must have been full moon :D

**Comment by MATsxm** [comment]
Thanks @Hils
