### ISSUE TITLE
[TM] Sidebar on right?

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#276]
Generally for sites using the Bootstrap based template the sidebar has been on the right side.  The left sidebar is inconsistent with most other sites (there are a couple exceptions).  Would it be too much to suggest changing the location?

**Comment by SpiritJC** [comment]
We moved the menus to the right.

**Comment by mbabker** [comment]
:+1:

**Comment by MATsxm** [comment]
:+1: 
Much, much better and consistent!

**Comment by Sandra97** [comment]
:+1:
