### ISSUE TITLE
[jdev] Contribute

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#278]
https://developer.joomla.org/cms/contribute.html

Username: Enter your user name you registered on the **Joomlacode** website. If you don't have a user name for **Joomlacode**, please create one there before signing this form.

**Comment by brianteeman** [comment]
I guess that should be github now instead

**Comment by mbabker** [comment]
23 items reference JoomlaCode - https://developer.joomla.org/search.html?q=joomlacode - whoever goes in to clean this up should probably update the rest (as relevant) too.

**Comment by brianteeman** [comment]
:)

**Comment by mbabker** [comment]
Updated
