### ISSUE TITLE
[jvel] Improper use of the trademark

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#280]
the VEL site is still **the last** one to use the registered trademark instead of the simple trademark indicia to its title.

'Joomla! ® Vulnerable Extensions List'
should be:
**Joomla! Vulnerable Extensions List™**

For more explanations, please see: https://github.com/joomla/joomla-websites/issues/91#issuecomment-136151424 and **FINALLY **legally act accordingly.

CC/@mandville

**Comment by SpiritJC** [comment]
@mandville please change it to "Joomla! Vulnerable Extensions List™"

Thank you.

**Comment by MATsxm** [comment]
Not the right way but at least... not the wrong
