### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by kristinejburns** [joomla/joomla-websites#281]
I recently googled my business and a google summary in another language appeared at the top of the search. When I tried to access my administrator login an Error 404 appeared. Please advise how I may attend to and resolve this issue. Thank you

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Regards,
Thanks
