### ISSUE TITLE
[joomla.org] Article Meta Options not implemented unless there is a Article Menu Item

### ISSUE THREAD

**Issue by ProfGerdes** [joomla/joomla-websites#283]
When first creating a site and you only have Home in the Main Menu (i.e. not other menu items), and you create Featured Articles that show up on the main page, If you modify the Article Options, the settings are not utilized. 

For example, if you choose to not show the Author, Creation Date, Category, Hits, and then view your site, they are still there.

This issue goes away as soon as you create a Article related menu item, such as Single Article, or Category Blog.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
