### ISSUE TITLE
[jdev] Suggestion improve color usage in stats graphs

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#284]
Right now the stats charts colors (https://developer.joomla.org/about/stats.html) are random.

Joomla could use this graphs to show which versions are most suitable and less outdated.
Using the right colors transmits information too.

Example:
- Database drivers "mysql" be orange and other be "green" colors
- Joomla versions: color scale from green to red with most recent  being "green" colors
- PHP versions: (the same as joomla versions)

Those are just ideas.

Some other suggestions:
- Having the total number of sites who contributed with their data.
- Show the label in the charts (without mouse over) or a notice for the user to mouseover for more info.

**Comment by mbabker** [comment]
PRs welcome - https://github.com/joomla-extensions/joomladata

I'd say though you need to be careful about adding a mapping of fixed color
codes to any version based chart otherwise you risk a maintenance
requirement of updating it on every relevant software release.

**Comment by mbabker** [comment]
Also, the three MySQL drivers are NOT the same and shouldn't be displayed
that way.

**Comment by andrepereiradasilva** [comment]
yes, i understand that are other things to take into consideration.
but do you agree with the concept?

**Comment by mbabker** [comment]
It'd be more consistent to use fixed colors, but short of implementing a
layout per data point or a separate module for each I'm not so sure what
you can do with it.  Right now the modules use an array of defined colors
and repeats that if one of the end points goes over the number of colors.
Also it shouldn't be a module that requires heavy maintenance (if it
requires an update on every software release we've failed miserably).

In general the idea's not bad, but it's not something I see a simple
solution to.

**Comment by andrepereiradasilva** [comment]
i will think about it. If i reach a working and flexible solution i'l post it to joomladata repository.

So will close this.
