### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by gagnonjeanfrancois** [joomla/joomla-websites#285]
Hello :D

I was helping a Joomla user who wish to update her website... I referred her to technical requirements :
https://www.joomla.org/about-joomla/technical-requirements.html ... 

For the section « Requirements for Joomla! 1.6, 1.7, & 2.5 » the « recommended » column for PHP should be updated... It is written that it needs « PHP 5.4+ », but it should replace by « 5.4 - to 5.6.x ». Otherwise some folks in their migration process could think that they could jump to PHP 7.0 and they will get bad surprise...

Otherwise, if this page could be in the doc Wiki, the community could translate it. That could be very useful for people who are not used with English.

Good day!

Forum tread : http://forum.joomla.org/viewtopic.php?f=706&t=917231&p=3386304#p3386304

**Comment by mbabker** [comment]
I made an update after seeing the forum thread.  Should be good to go now.

**Comment by gagnonjeanfrancois** [comment]
Well that was very fast, thanks ;)

**Comment by MATsxm** [comment]
@gagnonjeanfrancois 
There're also different tutos on the JDoc about migration already translated or available for translation.
https://docs.joomla.org/Portal:Upgrading_Versions/fr
Thanks
