### ISSUE TITLE
[jrescs] broken links - JRD Approval Checklist

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#286]
Url of the page: http://resources.joomla.org/en/getting-started-on-the-jrd/jrd-approval-cheklist
Broken/Wrong links in Paragraph: 
**_3.  Is any Joomla trademark used in your branding and is that use approved?_**

http://opensourcematters.org/domain-name-use-request.html (404 error)
New link should be: https://tm.joomla.org/trademark 

http://opensourcematters.org/logo-use-and-name-use.html (404 error)
New link should be: https://tm.joomla.org/joomla-name-and-logo-use 

**_4.  Is the Joomla trademark prominently displayed on your site?  If so, does it meet Conditional Use requirements?_**
http://opensourcematters.org/index.php?Itemid=169 (wrong/non consistent result)
is linked to http://opensourcematters.org/legal/license-copyright.html 

New link should be: https://tm.joomla.org/licensing

**Comment by genr8r** [comment]
All three links are updated and tested.  Thanks for the heads up.

**Comment by jeckodevelopment** [comment]
Thank you Brian!
