### ISSUE TITLE
[josm] Create redirects for old links

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#287]
The following URLs should be redirected to new pages/websites.

- http://opensourcematters.org/legal/license-copyright.html (new URL: https://tm.joomla.org/licensing )
- http://opensourcematters.org/legal/trademark/ (new URL: https://tm.joomla.org/trademark )
- http://opensourcematters.org/legal/trademark/trademark-policy.html (new URL: https://tm.joomla.org/trademark-policy )
- http://opensourcematters.org/legal/trademark/trademark-faq.html (new URL: https://tm.joomla.org/trademark-faq )
- http://opensourcematters.org/legal/license-copyright/licensing-your-extension.html (new URL: https://tm.joomla.org/licensing-your-extension )

**Comment by mikeveeckmans** [comment]
@Saurabh1 could you fix this ?

**Comment by Saurabh1** [comment]
@mikeveeckmans I will check on them and fix

**Comment by Saurabh1** [comment]
Are these links somewhere on the page ? if so can you please provide link(s) of the page.

**Comment by jeckodevelopment** [comment]
@Saurabh1 i have these links in my browser history, since they were the old menu items. To me these links should be added to the Redirect component to preserve old bookmarks and other websites links.

**Comment by Saurabh1** [comment]
@jeckodevelopment Okay, no issues. Will fix them anyways :+1:

**Comment by jeckodevelopment** [comment]
Thank you @Saurabh1 ;)

**Comment by marijkestuivenberg** [comment]
All redirects work now properly. This issue can be closed

**Comment by jeckodevelopment** [comment]
Thank you @marijkestuivenberg

**Comment by SpiritJC** [comment]
Thank you Marijke!
