### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by mcspencehouse** [joomla/joomla-websites#288]
My IP address was banned from Joomla.org due to the fact that I misconfigured a tool that I am developing for work. Is there a way I can get this ban lifted? Thanks!

**Comment by pe7er** [comment]
@mcspencehouse What joomla.org website has banned your IP address? 
Could you please link to the site?

What error do you get?
What tool did you misconfigure?

**Comment by mcspencehouse** [comment]
The site is www.joomla.org

I don't receive an error, the request times out.

It's a custom website profiling tool that made too many requests too quickly

**Comment by pe7er** [comment]
Ok, and the firewall probably saw it as a DDOS or hacking attempts.

I'll contact you privately about your IP address.

**Comment by mcspencehouse** [comment]
I appreciate your help.
