### ISSUE TITLE
[jdocs] Wrong link under "See also"

### ISSUE THREAD

**Issue by janstieler** [joomla/joomla-websites#289]
Hi,
I found an wrong routing on the joomla documentation.
On this site: 
https://docs.joomla.org/JFactory/getConfig
is under "See also" the link to
http://api.joomla.org/Joomla-Framework/JFactory.html#getConfig
declared. But this is wrong and should be changed to
https://api.joomla.org/cms-3/classes/JFactory.html#method_getConfig

Kind regards

**Comment by mbabker** [comment]
docs.joomla.org is a Wiki instance so feel free to make changes as you see fit.  Now with that said, the API doc pages that are on the Wiki relate to the old Joomla 1.5 API so I'd suggest leaving that one alone and perhaps in general adding notices to those pages (https://docs.joomla.org/Category:Framework lists some of them, I don't know what all is there though) and advising to visit api.joomla.org to find the documentation for current versions.

**Comment by MATsxm** [comment]
There are indeed much work and archiving to be done on the docs.joomla site about APIs.
On the todo, 
Thanks for the ping :wink:

**Comment by janstieler** [comment]
Hi,
I logged me in and changed teh URl of this link but after some captcha input with errors I got this Message:

> Diese Aktion wurde automatisch als schädlich erkannt und deshalb nicht ausgeführt. Wenn du denkst, dass deine Aktion konstruktiv war, wende dich bitte an einen Administrator und schildere ihm, was du versucht hast beizutragen. Kurzbeschreibung der verletzten Regel: Generic Link Spammer Test Filter

And now? Was this because my changing was too little or was the multiple wrong chaptcha inputs?

Cheers

**Comment by Sandra97** [comment]
It can happen when you want to add an external link. I just changed the link. It's now ok.

**Comment by MATsxm** [comment]
Closing this one and following @mbabker suggestion, adding to the ToDo to create a Template to link to the dedicated api.joomla.org documentation for current versions.
Thanks

**Comment by janstieler** [comment]
@Sandra97 Thanks.
