### ISSUE TITLE
[jorg] Update joomla.org to the supported Joomla! version

### ISSUE THREAD

**Issue by Hutchy68** [joomla/joomla-websites#29]
There are a lot of issues and some excuses as to why j.org isn't on 3.x yet and still running 2.5. Most answers seem to point to bespoke extensions and let's redesign the whole site. 

Great and lofty answers, but I suggest we take this one step at a time.

1. Identify and then update the bespoke extensions on j.org, switch them out completely or turn them off.
2. Update the site to J3.x
3. Build or redesign the template (which I suppose means for all j sites)
4. After the redesigned template is installed and working start the process of cleaning up what is not needed and reorganising the rest of the content.

Thoughts on breaking up this task into smaller more manageable parts that aren't so daunting.

**Comment by brianteeman** [comment]
What are the "bespoke" extensions. I can only think of anything on www that
is not core

On 8 August 2015 at 14:59, Tom Hutchison <notifications@github.com> wrote:

> There are a lot of issues and some excuses as to why j.org isn't on 3.x
> yet and still running 2.5. Most answers seem to point to bespoke extensions
> and let's redesign the whole site.
>
> Great and lofty answers, but I suggest we take this one step at a time.
>
>    1. Identify and then update the bespoke extensions on j.org, switch
>    them out completely or turn them off.
>    2. Update the site to J3.x
>    3. Build or redesign the template (which I suppose means for all j
>    sites)
>    4. After the redesigned template is installed and working start the
>    process of cleaning up what is not needed and reorganising the rest of the
>    content.
>
> Thoughts on breaking up this task into smaller more manageable parts that
> aren't so daunting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/29>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
joomla.org itself doesn't have any custom code that I'm aware of.  And there is a team working on its migration.

The upgrade issues are mostly tied to the community site (running 1.5).

**Comment by Hutchy68** [comment]
Bespoke - one off extensions a Dev specifically built to use on that site

**Comment by Hutchy68** [comment]
I find it completely ridiculous that we can write documentation on how to upgrade your website to the next version but we can't seem to do it ourselves.

**Comment by brianteeman** [comment]
I know what the word bespoke means - I just dont see any on the site

On 8 August 2015 at 15:03, Tom Hutchison <notifications@github.com> wrote:

> Bespoke - one off extensions a Dev specifically built to use on that site
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/29#issuecomment-128984263>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hutchy68** [comment]
I'm just repeating what I was told quite a while back. Some of it I think centers around the template that's being used. There might be some connector?  For someone when they login to write a blog post that actually places it on the community site? 

This site should've started migration shortly after 3.0 came out.  We are now eight months beyond EOL of 2.5.

**Comment by mbabker** [comment]
The only "bespoke" extension on joomla.org is the support Joomla banner.  Otherwise, without having access to the extension manager, every extension I can see through the other managers and menu system shows everything is basically JED listed.  You're getting the "bespoke" stuff confused with the community site.

Also, the login link on .org redirects to the community site, so you aren't actually logging into .org using that link.

**Comment by brianteeman** [comment]
So nothing more than the fact that a "team" has claimed they are "working"
on it is preventing anything moving forward?

On 8 August 2015 at 15:13, Michael Babker <notifications@github.com> wrote:

> The only "bespoke" extension on joomla.org is the support Joomla banner.
> Otherwise, without having access to the extension manager, every extension
> I can see through the other managers and menu system shows everything is
> basically JED listed. You're getting the "bespoke" stuff confused with the
> community site.
>
> Also, the login link on .org redirects to the community site, so you
> aren't actually logging into .org using that link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/29#issuecomment-128985973>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
It's the group Soren's getting together (see his tweet from the other day) that are doing the work.  I also know of a couple others doing content work for the upgraded site (I know this because I provisioned the working space for them).

**Comment by Hutchy68** [comment]
Yeah I know community is borked big time. So there is one bespoke and login redirects. So, not at you because I know your feelings on it, what is the hold up?  

 There are a lot of problems with the site and mobile viewing. They can mostly be solved by getting us off of 2.5

**Comment by mbabker** [comment]
I think you're seriously getting your signals crossed on the remaining non-upgraded sites.

.org - 2.5, only the support banner is custom, team is working on upgrade
community - 1.5, bespoke stuff and subinstalls all over the place, who knows what the status is
magazine - 2.5, team is working on the 3.x upgrade (migrating content components being part of it)

So what questions remain?

**Comment by Hutchy68** [comment]
No, I know the issues with mag and community. I know Soren is working on a **redesign**. https://twitter.com/sorenbeck/status/628909268574539776

That's great and no pressure on Soren for a redesign. What do am saying is if there is no reason holding us back let's get the migration done asap. We have a usable shared template so let's use it. Step 1. Then that gives us a attainable goal which isn't everything thrown into one pack to carry up the mountain.

**Comment by jneubauer** [comment]
to clarify, as one of the people working on the new site which Soren is heading up

it does involve a redesign
it also does involve an upgrade - in fact, the dev environment we are already working on for this project is already on Joomla 3

it is scheduled to be completed in September (the main joomla.org site is not really that complex, a short development cycle for the combined redesign and upgrade is feasible)

**Comment by brianteeman** [comment]
Small steps help you reach your final goal easier

**Comment by Hutchy68** [comment]
:+1: Brian

**Comment by mbabker** [comment]
Conceptually, I agree fully.  However, being familiar with how .org's content is organized, I can tell you that the upgrade job is not as simple as the UX site was (migrate 2.5 to 3.x, slap the new template in place, and put modules in the right spots).  There are quite a few more "intricacies" to cope with on that site, like the lengthy side menu and the homepage layout.  Not knowing the full details of what Soren's team is doing, I honestly think a 4-week timeframe isn't that much to ask for in this case.

**Comment by Hutchy68** [comment]
Yes, I agree 4 weeks isn't that long or 5 weeks. Just don't want to see the project stall, we really, really need to get j.org upgraded. Now it is on record and can track progress. @jneubauer can you keep this issue updated with progress? It would be greatly appreciated.

**Comment by jessicadunbar** [comment]
Here's the project brief https://docs.google.com/a/community.joomla.org/document/d/18toD_sduJvp8LysuyIQke1kgl4pz35JiRI5n_wk18T0/edit?usp=docslist_api

repository.joomla.org the username and password joomla/joomla

**Comment by mbabker** [comment]
Upgrade is complete, please report issues if any are found.

**Comment by brianteeman** [comment]
Congrats and thanks

On 1 September 2015 at 15:41, Michael Babker <notifications@github.com>
wrote:

> Upgrade is complete, please report issues if any are found.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/29#issuecomment-136745513>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Radek-Suski** [comment]
Great work. Thank you all. :)

**Comment by vdrover** [comment]
Phenomenal! Nice work. Thank-you very much.
