### ISSUE TITLE
[jcertif] pricelist

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#291]
I do not live in Britain
I live in either Great Britain or United Kingdom

**Comment by jeckodevelopment** [comment]
Fixed.
Thank you for your report Brian!

**Comment by brianteeman** [comment]
Thanks

On 7 April 2016 at 20:32, Luca Marzo <notifications@github.com> wrote:

> Closed #291 <https://github.com/joomla/joomla-websites/issues/291>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/291#event-619013101>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
