### ISSUE TITLE
[jcertif] Price list currency

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#292]
US Dollars use a decimal for the separator between dollars and cents (ya, I know, blame us for being different).  Since you're displaying prices in US Dollars I'd suggest using a decimal as that's the currency standard.

**Comment by brianteeman** [comment]
its the same in the UK ;)

On 7 April 2016 at 20:41, Michael Babker <notifications@github.com> wrote:

> US Dollars use a decimal for the separator between dollars and cents (ya,
> I know, blame us for being different). Since you're displaying prices in US
> Dollars I'd suggest using a decimal as that's the currency standard.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/292>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
I always forget there's Europe then there's the UK :stuck_out_tongue_closed_eyes:

**Comment by MATsxm** [comment]
hehe... here we went from 4 official currencies to 3 now then believe me it's not that complicate to deal with decimals :wink:

**Comment by jeckodevelopment** [comment]
thank you for your report. :)
Fixed!
