### ISSUE TITLE
[jed] Free Vs. Commercial 

### ISSUE THREAD

**Issue by mike44** [joomla/joomla-websites#293]
browsing extension with free enabled, I only get free downloads which are not free as you have to pay for copyright removal.
What exactly is copyrighted on gpl stuff? can I simply remove the images and am good to use?
You need to separate copyrighted stuff as it's not free!
Thanks

**Comment by JazParkyn** [comment]
Hi,

These inks should provide more clarification on this issue.

http://extensions.joomla.org/support/knowledgebase/item/free-vs-paid-extensions
http://extensions.joomla.org/support/knowledgebase/item/the-gpl-and-the-jed

Quoted from the first link: "Require payment/subscription/donation to remove visible links (users are able to remove the links themselves)"

If you believe that a particular extension is violating the GPL or the JED TOS, please click on the Report button on the extension's JED listing (only visible when logged in). JED is only able to offer support via tickets - we don't usually check github for things like this. Also, our bug/issue tracker is available at: https://joomlaextensionsdirectory.atlassian.net/secure/Dashboard.jspa

Regards,

Jaz
JED Listing Team Manager

@MATsxm can this be closed please?

**Comment by MATsxm** [comment]
Thanks @JazParkyn
