### ISSUE TITLE
[jcomm] 404 error on "Teams" menu item

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#295]
http://community.joomla.org/blogs/team-blogs.html (404 error)
You can find the "Teams" menu item on http://community.joomla.org/blogs.html and so on.

**Comment by Joomv** [comment]
Someone had deleted the article behind it.  Have unpublished the item.

**Comment by MATsxm** [comment]
could you please redirect the 404?
Thanks

**Comment by Joomv** [comment]
Where to?  Home? Main blogs?

**Comment by Sandra97** [comment]
Redirect to the most relevant. 
What about http://community.joomla.org/blogs.html ?

**Comment by Joomv** [comment]
Done in htaccess.  Closing.

**Comment by jeckodevelopment** [comment]
Thank you! ;)
