### ISSUE TITLE
[jdocs] Error in documentation

### ISSUE THREAD

**Issue by Webmaster-Tenerife** [joomla/joomla-websites#296]
Page: https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_decorations_to_the_backend
Adding this line to "admin/language/en-GB/en-GB.com_helloworld.sys.ini" causes an error and destroys the complete display of the Joomla Admin Panel:
`COM_HELLOWORLD_MENU=" <i class="icon-smiley-2"></i>Hello World!"`

**Comment by MATsxm** [comment]
docs.joomla.org is a Wiki instance so feel free to make content changes as you see fit.
Thanks
