### ISSUE TITLE
[jorg] Video

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#297]
The video is now showing google ads which are hiding a lot of our text during the video.

**Comment by mikeveeckmans** [comment]
on it

**Comment by Hils** [comment]
Thank you :)

**Comment by mikeveeckmans** [comment]
Seems we have a copyright issue on that one because of the used music, dispute opened.

**Comment by brianteeman** [comment]
I get that all the time even when i licence the music

On 11 April 2016 at 10:56, Mike Veeckmans <notifications@github.com> wrote:

> Seems we have a copyright issue on that one because of the used music,
> dispute opened.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/297#issuecomment-208263471>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
can't we host it ourselves, not via YouTube? We did that on the magazine sometimes.

**Comment by mikeveeckmans** [comment]
Fixed. 
Awaiting dispute result , but closing for now.
