### ISSUE TITLE
[jvel] Improper use of the the registered trademark name Joomla!

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#299]
Use indicia ® following the first prominent use of Joomla! as it is a registered TM

# on .org

![efaa9f326a1918f089631154f0ced5eb](https://cloud.githubusercontent.com/assets/1972717/14426952/0beee60e-ffc0-11e5-908a-e476b7976c8a.png)

# on VEL

![c5c052096ac07067a5fa478c936a450b](https://cloud.githubusercontent.com/assets/1972717/14426942/fb0adb40-ffbf-11e5-8b61-2fc395f9c7f4.png)

Please see: https://tm.joomla.org/trademark/226-proper-use-of-the-joomla-name

**Comment by MATsxm** [comment]
This would be an easy fix using the CDN menu like others... just saying

**Comment by mbabker** [comment]
Update the template to the current version, period...

**Comment by btoplak** [comment]
Thanks for your concerns, I'm working on changing the whole template

**Comment by brianteeman** [comment]
Just use the default one for all sites - reinventing the wheel is not
productive

On 11 April 2016 at 21:04, Bernard Toplak <notifications@github.com> wrote:

> Thanks for your concerns, I'm working on changing the whole template
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/299#issuecomment-208532265>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by btoplak** [comment]
Yes, I was talking about changing the (whole) template to default one for official sites. But I wrote the last message in a sloppy way ...
Anyway, the official template is up an running.

**Comment by MATsxm** [comment]
Thank you! - closed
