### ISSUE TITLE
[joomla.org] Need to fix and resubmit the joomla download link to google search

### ISSUE THREAD

**Issue by rakeshmali** [joomla/joomla-websites#300]
"Wrong URL - https://www.joomla.org/download.html?tmpl=component" is showing in google search page for Joomla Download.
Remove the ?tmpl=component from the download link and resubmit the link to google search through google webmaster.

Expected result: The download URL should be- https://www.joomla.org/download.html

PFA screen for the same
![selection_005](https://cloud.githubusercontent.com/assets/8438390/14437663/ecf7fe18-003f-11e6-984a-5e408d2ee0df.png)
![selection_006](https://cloud.githubusercontent.com/assets/8438390/14437664/ed125eca-003f-11e6-81a9-860c37dd2b6d.png)

**Comment by mikeveeckmans** [comment]
who has access to the search console?
@sanderpotjer ?  @RCheesley ? @Radek-Suski ?

**Comment by aDaneInSpain** [comment]
I have demoted the sitelink in the search console. It still shows up, but I guess it is just a matter of time.

**Comment by MATsxm** [comment]
Hmmm still nothing :confused:

**Comment by Sandra97** [comment]
It seems the link in question is not displayed anymore. 
Closing this issue.
Re-open if needed.
