### ISSUE TITLE
[joomla.org] Problem with User Group DataBase Table

### ISSUE THREAD

**Issue by faristizabal** [joomla/joomla-websites#301]
Hi there!!, I need to create a really complex user/article relationship in my website, where i'm able to create articles which only one user may access it, so I created this user logic:

For example:

User: ark602
User Group: ark602 (parent: registered)
Access level: ark602 (inside i choose user group ark602 to have access)

I created an the article and I gave it access to access level ark602.

This looks very simple, but i need to create over than 2800 articles, users, access levels and user groups.

The issue is, I don't know why, when I start created a lot of user groups, the site crashed and i stop being able to save global config or articles. I backed up the data base and when i delete the user group table, the site start working fine again.

My website is: http://stg.abelardoyepes.com

Could you please tell me how to do? or a better way to set up why i  need in the website.

Thanks a lot for your time and sorry about my bad english..

**Comment by designbengel** [comment]
Hi @faristizabal please use the http://forum.joomla.org/ for your website related questions or have a look in the docs: https://docs.joomla.org/J3.x:Access_Control_List_Tutorial
