### ISSUE TITLE
[jvel] SEF URL uses index.php

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-websites#302]
When you go to https://vel.joomla.org/ and click on the link for the Live VEL, you get:
https://vel.joomla.org/index.php/live-vel

The index.php doesn't belong there. This link can be found in the text:
> All known vulnerable extensions are the listed in the LIVE VEL section

**Comment by jeckodevelopment** [comment]
I think that has been fixed. Can't find the wrong link!

**Comment by btoplak** [comment]
Roland, thanks for the heads-up. 
I fixed it a minute ago ;) ... I will close this ticket.
