### ISSUE TITLE
[jdocs] UX improvements

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#303]
https://docs.joomla.org/Joomla:The_Joomla_Websites the report issues column is not there on mobile.  

Also I was unsure how to search for an issue before posting but you specifically asked me to do that at the top of the page.  Perhaps a little instruction would go a long way.

**Comment by uglyeoin** [comment]
I found out how to do the later.  You could make a button or something to make it more obvious.  I agree that web admins have limited time, helping the users to help themselves is a time saver.

**Comment by mbabker** [comment]
@MATsxm Can we do something with this?

**Comment by Sandra97** [comment]
It's on my (really long) todo list

**Comment by Hutchy68** [comment]
https://docs.joomla.org/Joomla:The_Joomla_Websites 

Transformation from Desktop to Mobile views. 

**Desktop**

![capturereportjwebsitedesktop](https://cloud.githubusercontent.com/assets/3527469/24334837/fb1e9552-123f-11e7-98f0-cdf5da162667.PNG)

**Mobile**

![capturereportjwebsitemobile](https://cloud.githubusercontent.com/assets/3527469/24334840/07fc37c0-1240-11e7-823a-8266fa30cbba.PNG)

**Comment by Sandra97** [comment]
Thank you Tom!!!

**Comment by Sandra97** [comment]
Display on my phone is perfect!

**Comment by Sandra97** [comment]
Closing this issue as the table is responsive.
Re-open if needed.
