### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by shannonkelly** [joomla/joomla-websites#305]
I attempted to upload a zip file onto my website an immediately recieved the attached error message. It's saying there is a non object on line 87 which I can only assume is the VirtueMart zip I tried to upload. I can't access the administrator panel to remove the line of code so I was hoping someone here could help. 

Thank you

[screen shot 2016-04-13 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/18449156/14505845/f698d9fc-0188-11e6-9425-910a9c96e850.png)

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Also ask VM support

Regards,
Thanks
