### ISSUE TITLE
Site gone, can no longer log in to Joomla [joomla.org] 

### ISSUE THREAD

**Issue by DylansBurden** [joomla/joomla-websites#307]
Hello there

I ran an update on a plugin on my Joomla CMS and now I can no longer access the Joomla CMS or view the website. My login link is: 
http://www.avalone-guesthouse.com/administrator/index.php 
Could you please assist me with the necessary steps? Or perhaps restore my site to a point in time before the update? 

Best regards,
Dylan

**Comment by designbengel** [comment]
Hi Dylan,
this issuetracker is for joomla.org website related issues.
For help with your site please visit https://forum.joomla.org or https://docs.joomla.org
