### ISSUE TITLE
[jorg] 404 Errors links

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-websites#309]
404 Error for this link: http://community.joomla.org/joomla-user-groups.html  on these pages:

https://www.joomla.org/contribute-to-joomla.html 
Joomla User Group

https://www.joomla.org/about-joomla/create-and-share.html 
Check user groups in your area »

https://www.joomla.org/about-joomla/contribute-to-joomla.html 
Joomla User Group

https://www.joomla.org/announcements/general-news.html?start=111 
Joomla! User Group

https://www.joomla.org/announcements/general-news.html?start=111 
Joomla! User Groups

https://www.joomla.org/announcements/general-news/5165-introducing-communityjoomlaorg.html 
Joomla! User Group

https://www.joomla.org/announcements/general-news/5165-introducing-communityjoomlaorg.html 
Joomla! User Groups

https://www.joomla.org/announcements.html?start=258
Joomla! User Group

https://www.joomla.org/announcements.html?start=258

**Comment by mikeveeckmans** [comment]
Correct link towards JUG overview is : http://community.joomla.org/user-groups.html

**Comment by Sandra97** [comment]
3 first links are corrected.
Note that for the other 404 are related to articles of 2008. Even if we already corrected a lot, all 'old' articles need to be cleaned and reviewed. Lots of articles are talking about topics, sites, companies, awards that don't even exist anymore. While cleaning the inline style, MAT already removed many deprecated links.

**Comment by Sandra97** [comment]
As it seems the Phase 2 will happen the day it will snow in SXM, I have fixed the issues related with external links (No Response - 4xx Responses and 5xx Responses). 
Some broken links may still exist, I'll find them as I'm also cleaning the HTML code of the articles and re-checking the links.
