### ISSUE TITLE
[ALL] Sync sites with master template repo

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#31]
Some of the 3.x based sites are behind the master template in various ways.  Just to name some of the things I've noticed:

- JED needs to update mega menu (doesn't pull from CDN)
- Volunteer Portal still has the jumping submenu
- VEL has the jumping submenu and needs to update mega menu
- JRD has the jumping submenu and needs to update mega menu

Once #26 and #7 are sorted a package is ready to be distro'd to site admins (everyone on the webmasters team for this repo also has access to the template repo to review changes by commit).

**Comment by mbabker** [comment]
Package is being emailed to admins tonight.  @joomla/webmasters anyone who doesn't receive it and should please contact me.

**Comment by mbabker** [comment]
The following sites still require updates:

- Volunteer Portal @sanderpotjer
- Events Site @Radek-Suski
- Vulnerable Extensions List @btoplak @mandville
- Resources Directory (anyone?)
- Joomla Shop @mikeveeckmans

**Comment by Radek-Suski** [comment]
Done

**Comment by mikeveeckmans** [comment]
shop.joomla.org : Done
However i might need someone to have a quick look at some CSS ;-)

**Comment by mbabker** [comment]
The following sites still require updates:

- Vulnerable Extensions List @btoplak @mandville
- Resources Directory (anyone?)

**Comment by Radek-Suski** [comment]
I think it would be @drmmr763

**Comment by drmmr763** [comment]
I'm not really engaged in the JRD team any more. The proper people to contact should be:

- Dawn Russell studio@artisanwebandprint.com
- Chris Neilsen chris.nielsen@resources.joomla.org

The do have some one who can probably help with template code syncing, user name https://github.com/FriendlyHacker

He has access to the template code. The JRD has some significant additional code to the template so it'll be a manual process. 

If there's any official github repos that the above people should be on to get proper notifications for this i recommend reaching out to them and getting their github info so they can be added.

**Comment by Duke3D** [comment]
I'll get it from Michael and pass it on to JRD.  Thanks for the heads-up tweet.

**Comment by btoplak** [comment]
@mbabker I'm working on a bigger revamp of the VEL site, but still not finished. I will try to sync at least those changes you outlined.
P.S. Can you add me to the direct access to the template repo?

**Comment by mbabker** [comment]
The invite for the team is sent; once you accept it you'll have access to the template repo.

**Comment by btoplak** [comment]
Thanks!
