### ISSUE TITLE
[jorg] 404 Errors link

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-websites#310]
404 Errors link leading to http://community.joomla.org/team-blogs/documentation-team/443-six-ways-for-newcomers-to-contribute-to-joomla.html on these pages:

https://www.joomla.org/contribute-to-joomla.html 
newcomers can contribute to Joomla

https://www.joomla.org/about-joomla/contribute-to-joomla.html 
newcomers can contribute to Joomla

**Comment by Sandra97** [comment]
Link removed as useless.
Closing this issue, re-open it if needed.
