### ISSUE TITLE
[jorg] 404 Errors link leading to http://community.joomla.org/user-groups/jug-faq.html

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-websites#311]
404 Errors link leading to http://community.joomla.org/user-groups/jug-faq.html on these pages:

https://www.joomla.org/joomla-in-your-language/5355-pt-br-what-is-joomla-in-brazilian-portuguese.html 
https://www.joomla.org/joomla-in-your-language/5356-pt-pt-what-is-joomla-in-european-portuguese.html 
https://www.joomla.org/joomla-in-your-language/5490-ro-ro-what-is-joomla-in-romanian.html
https://www.joomla.org/joomla-in-your-language/5358-sr-rs-what-is-joomla-in-serbian-cyrilic.html
https://www.joomla.org/joomla-in-your-language/5359-sr-yu-what-is-joomla-in-serbian-latin.html
https://www.joomla.org/joomla-in-your-language/5357-sv-se-what-is-joomla-in-swedish.html 
https://www.joomla.org/joomla-in-your-language/5489-ta-lk-what-is-joomla-in-tamil-sri-lanka.html
https://www.joomla.org/joomla-in-your-language/5361-vn-vn-what-is-joomla-in-vietnamese.html 
https://www.joomla.org/joomla-in-your-language/5362-zh-cn-what-is-joomla-in-simplified-chinese.html 
https://www.joomla.org/joomla-in-your-language/5363-zh-tw-what-is-joomla-in-traditional-chinese.html 
https://www.joomla.org/joomla-in-your-language/5338-da-dk-what-is-joomla-in-danish.html
https://www.joomla.org/joomla-in-your-language/5333-de-de-what-is-joomla-in-german.html 
https://www.joomla.org/joomla-in-your-language/5339-el-gr-what-is-joomla-in-greek.html 
https://www.joomla.org/joomla-in-your-language/5341-hu-hu-what-is-joomla-in-hungarian.html 
https://www.joomla.org/joomla-in-your-language/5329-en-us-what-is-joomla-in-english.html 
https://www.joomla.org/joomla-in-your-language/5342-jp-jp-what-is-joomla-in-japanese.html
https://www.joomla.org/joomla-in-your-language/5343-km-kh-what-is-joomla-in-khmer.html 
https://www.joomla.org/joomla-in-your-language/5332-fr-fr-what-is-joomla-in-french.html 
https://www.joomla.org/joomla-in-your-language/5344-lv-lv-what-is-joomla-in-latvian.html 
https://www.joomla.org/joomla-in-your-language/5365-he-il-what-is-joomla-in-hebrew.html 
https://www.joomla.org/joomla-in-your-language/5353-mk-mk-what-is-joomla-in-macedonian.html 
https://www.joomla.org/joomla-in-your-language/5509-ms-ms-what-is-joomla-in-malaysia.html 
https://www.joomla.org/joomla-in-your-language/5354-nb-no-what-is-joomla-in-norwegian.html 
https://www.joomla.org/joomla-in-your-language/5330-nl-nl-what-is-joomla-in-dutch.html 
https://www.joomla.org/joomla-in-your-language/5488-pl-pl-what-is-joomla-in-polish.html

**Comment by MATsxm** [comment]
Known issue as duplicate with the JDOC and maintained as a wiki by local communities.
Link will be created to the doc.

**Comment by Sandra97** [comment]
Following previous discussions on Glip, it has been decided to link 'Joomla! in Your Language' to the JDocs. 
It's done.
Closing this issue. Re-open if needed
