### ISSUE TITLE
[jdocs] Joomla info page/it-IT - Broken Link

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#312]
Broken link into this page of the documentation: https://docs.joomla.org/Joomla_info_page/it-IT 
Paragraph: _**Eventi Regionali / Joomladays**_
Wrong URL: http://community.joomla.org/events/joomla-days.html (actually a 404 error)
It should be: https://events.joomla.org/joomladays 

And also the link here: https://docs.joomla.org/Joomla_info_page/EN at paragraph _**Regional Events / Joomladays**_ should point to https://events.joomla.org/joomladays instead of the "general calendar".

**Comment by jeckodevelopment** [comment]
Additionally, same page https://docs.joomla.org/Joomla_info_page/it-IT , next paragraph:
the URL: http://community.joomla.org/user-groups/jug-faq.html should be http://community.joomla.org/user-group-faqs.html

**Comment by jeckodevelopment** [comment]
And also: https://docs.joomla.org/Joomla_info_page/de-DE 
Paragraph: **Wo erhält man eine Dokumentation für Joomla?**
Wrong link: http://www.jgerman.de/hilfeserver.html (404 error)

**Regionale Events / JoomlaDays**
Wrong link: http://community.joomla.org/events/joomla-days.html 
Should be: https://events.joomla.org/joomladays

**Comment by MATsxm** [comment]
The JDoc is a Wiki then YOU, as user and collaborator, is in charge of creating/editing/deleting the content as you think it should be and especially when it concerns your own community :wink:

**Comment by jeckodevelopment** [comment]
@MATsxm as new contributor to Docs i'm not allowed to edit links.
My first edit was marked as Spam :-1: 


>     Warning: This action has been automatically identified as spam and your account reset to email unconfirmed.
> 
> Edits of this nature are blocked automatically or quickly reverted. Egregious or repeated editing of this nature will result in your IP address being blocked. If you believe this edit to be constructive, you must re-confirm you user accounts email. It is suggested you first contact a wiki sysop before trying to resubmit the edit. A brief description of the abuse rule which your action matched is: Spam without links - common keywords

**Comment by Sandra97** [comment]
What's your username on JDocs?

**Comment by Sandra97** [comment]
Note that usually, on a wikimedia system, for security reason, a new registered user who posts an external link is automatically considered as a spammer.
You should try again tomorrow ;)

**Comment by Hutchy68** [comment]
Did you read the user account policy? 

https://docs.joomla.org/JDOC:Wiki_policy which also has a specific link to:

https://docs.joomla.org/User:Abuse_filter which gives specifics as to why and how to re-enable your account.

**Comment by jeckodevelopment** [comment]
@Sandra97 my username is luca.marzo
@Hutchy68 yeah, i read the account policy, but i registered to start updating the bad links and I can't do it ;)

**Comment by jeckodevelopment** [comment]
@Sandra97 @Hutchy68 
I created a new account, waited some days, but still can't edit the page. 
Each time i try to edit the links i receive a message telling me i was blocked as spammer.
Please re-activate my account or update links by yourselves! :)

**Comment by MATsxm** [comment]
@jeckodevelopment do you have reactivated your account as mentioned? 
https://docs.joomla.org/User:Abuse_filter
The thing is, if you start your JDoc user experience by changing external links (you won't believe the amount/day of attemps) I guess Fuzzybot will be upset :wink:

**Comment by jeckodevelopment** [comment]
it seems to be active, "Email confirmed"

**Comment by Sandra97** [comment]
Links changed.
Closing this issue.
Re-open if needed.

**Comment by jeckodevelopment** [comment]
Thank you Sandra! ;)
