### ISSUE TITLE
Writing a JHttpTransportCurl request in Joomla

### ISSUE THREAD

**Issue by EdgarAhDzib** [joomla/joomla-websites#313]
Is there a guide to writing in JHttpTransportCurl? The cURL request I use for my current website is not working in Joomla! 3.5.1. (This is for a PayPal API, which I am attempting for a website revision in Joomla.)

**Comment by jeckodevelopment** [comment]
Hi @EdgarAhDzib 
this issue tracker is for joomla.org website related issues.
For help with your site please visit https://forum.joomla.org or https://docs.joomla.org
