### ISSUE TITLE
[jvols] Low quality member picture when displaying single team reports

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#314]
When you see this page https://volunteers.joomla.org/reports , the Author's picture is the 250x250 px thumb.
When you see the member list (of a team), memers picture are 50x50 px thumbs.
When you see a specific group reports page, the author's picture is the 50x50 px thumb, instead of the 250x250 px thumb.

URLs of evidence: 

- https://volunteers.joomla.org/reports (Good quality pictures, 250x250px)
- https://volunteers.joomla.org/working-groups/certification-operations-team (Member list, 50x50px)
- https://volunteers.joomla.org/working-groups/certification-operations-team#reports (Low quality, 50x50px instead of 250x250px).

**Comment by sanderpotjer** [comment]
Thanks! Fixed
