### ISSUE TITLE
[joomla.org] Menu items for Trademark website

### ISSUE THREAD

**Issue by SpiritJC** [joomla/joomla-websites#315]
The TM-team in my opinion is not as present as I'd like it to be in the main menu-structure of the Joomla website(s). Is it possible to add a menu item for the Trademark website to the joomla.org template, perhaps on several submenu's with differrent approaches?

**Comment by jeckodevelopment** [comment]
Maybe you could suggest how to implement it!

**Comment by SpiritJC** [comment]
We can add a menu item to the "Community menu" (Joomla! Trademark)

**Comment by jeckodevelopment** [comment]
"Joomla! Trademark & Licensing"

**Comment by SpiritJC** [comment]
Thanks @jeckodevelopment. I changed my post :-)

**Comment by mbabker** [comment]
Menu updated.  CDN nodes will refresh momentarily.
