### ISSUE TITLE
[jorg] wrong link to trademark information

### ISSUE THREAD

**Issue by SpiritJC** [joomla/joomla-websites#316]
https://www.joomla.org/component/content/article.html?id=259:logo-usage-and-brand-guide

Can someone change the link from Open Source Matters to Trademark website (https://tm.joomla.org)?

> The Joomla! name is also a trademark. Policies for use of the Joomla! name can be found on the **Open Source Matters website**

**Comment by Sandra97** [comment]
Link changed.
Closing this issue. Re-open if needed.
