### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by smith581** [joomla/joomla-websites#317]
I purchased a component from JED site - They are not allowing me to download and this is holding up my project. My browser claims it is an unsafe site. I let them know I was going to report them to you.

Nothing you can do probably but I think I have lost my money......

Order Number : 105898880208
Merchant Order ID : 2339

http://radiustheme.com ( http://radiustheme.com )

Contents of your purchase :
Vendor Product ID : 1389
Product Name : TLP Portfolio PRO for Joomla
Quantity : 1

Total : 14.00 ( USD )

Billing Information
Kelly  Smith
IP: 70.176.20.86     IP Location: Chandler ( United States )
azrideshare@gmail.com

2409 W Marlboro Dr
Chandler, AZ 85224
United States ( USA )

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS or comments regarding the JED that is **NOT** selling any extension.

For user support issues, please directly ask the reseller or report to the JED.
Regards,
Thanks

**Comment by smith581** [comment]
I don’t know how to report to JED this is what came up when I went looking for it

**Comment by mbabker** [comment]
Create an account on extensions.joomla.org and they have a ticket system.

**Comment by smith581** [comment]
thank you
