### ISSUE TITLE
login site

### ISSUE THREAD

**Issue by akemi-akamine** [joomla/joomla-websites#320]
Hi,
I'm having issues because I don't know my user email or password, my friend take care about this and I never needed. Actually the site is important because puclicize a ONG for deficient children. The link is projetosim.org.br.
Please I really need help and my friend is not available.

My contact is akamine.ja@gmail.com

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

And check also this: https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

Regards,
Thanks
