### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by layale** [joomla/joomla-websites#321]
http://pevatech.com/
The pevatech.com page isn’t working

pevatech.com is currently unable to handle this request.
HTTP ERROR 500

When i talk to godaddy they told me that the problem is in joomla files please i need to fix that.
thank you

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thank you
