### ISSUE TITLE
[jdev] Outdated content on Joomla! User eXperience Blog

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#323]
https://developer.joomla.org/cms/user-experience.html

This page shows old JUX Team reports (2013), maybe it would be better to redirect to the Team Report page on the Volunteers Portal.
https://volunteers.joomla.org/working-groups/user-experience-working-group#reports

**Comment by mbabker** [comment]
It was a purposeful choice when `ux.joomla.org` was shut down to copy the blog content to that category on the dev site (and the redirect for that remains in place today).  Cliff has access on the site to publish content, so I guess it's his choice whether to use it or not, but I'm personally not a fan of just completely unpublishing or making content unavailable that once was without good reason (being old isn't necessarily good reason).

**Comment by MATsxm** [comment]
IMHO, this is a blog page that should be used as a blog page. 
If Cliff or JUX Team want to add new content even links to current reports... that would be :+1: 
Just my point of view ;)

**Comment by MATsxm** [comment]
Oooops, it seems I'm the echo on this one :wink:

**Comment by jeckodevelopment** [comment]
By the way, if no new content is being published, you could consider also to add a link or a sort of banner with the URL where new/updated contents are published.
UX Team works, so it's good to see their work and their updates.

**Comment by mbabker** [comment]
Added an alert div with a link.

**Comment by jeckodevelopment** [comment]
Thank you Michael!

**Comment by cpfeifer** [comment]
Thanks for your comments. That is the one area we haven't had a chance to update as of yet. We have been posting in the News section of the developer site with out most recent efforts, and more will be coming soon. Thanks again for your feedback.
