### ISSUE TITLE
[jvols] Can't see old reports in a Team page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#326]
When you open the "Reports" tab, within a specific team page, only last 10 reports are displayed.
There's no pagination and no ability to see old reports of the team.

e.g. https://volunteer.joomla.org/working-groups/certification-operations-team#reports 

The general Reports page has the pagination so, here it is possible to find old reports from all the team. 
https://volunteer.joomla.org/reports 

**Proposal**
It could be useful to have pagination in reports tab of each team, just to find out the evolution of the work of such team. 
Otherwise, we can consider the implementation of a "Team filter" (e.g a Dropdown) in the general reports page.

**Comment by rdeutz** [comment]
@jeckodevelopment please stop assigning issue to me, I will check the list later

**Comment by jeckodevelopment** [comment]
ok Robert! :D 
it was just as reminder :P

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for the suggestion, this has been implemented now.
