### ISSUE TITLE
[jvols] Registration issue + "fake" accounts?

### ISSUE THREAD

**Issue by PDGDev** [joomla/joomla-websites#327]
Registered on volunteers.joomla.org.  Used first name.  The site assigned a profile upon my login.  The email is not mine and I have no ability to edit the profile.  It appears that the Name field is not checked against existing profiles.  If you go to this link about (https://volunteers.joomla.org/joomlers?start=480) and look for any Joomler with the name John or john (there are about 5) and click on it - they all lead to the same profile. I am assuming the existing profile is assigned then there is a permissions issue each time a member registers.

**Comment by sanderpotjer** [comment]
@PDGDev a new version of the Volunteers Portal has been released, addressing this issue. Should no longer cause issues. Thanks for reporting!
