### ISSUE TITLE
[jvols] Permissions issue: a volunteer can delete all the pictures from media manager

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#329]
When writing a Group Report, each volunteer can upload images.
But via the media manager, he/she can delete also pictures all over the volunteers portal, including other members pictures.
In particular, it's possible to navigate all the subfolders and handle pictures (upload, edit, rename, delete). 

A solution could be to add a specific folder for "Reports" and restrict the media manager only to this folder.

**Comment by brianteeman** [comment]
That is super easy to do with JCE and thats what is being used

On 12 May 2016 at 00:44, Luca Marzo <notifications@github.com> wrote:

> When writing a Group Report, each volunteer can upload images.
> But via the media manager, he/she can delete also pictures all over the
> volunteers portal, including other members pictures.
> In particular, it's possible to navigate all the subfolders and handle
> pictures (upload, edit, rename, delete).
>
> A solution could be to add a specific folder for "Reports" and restrict
> the media manager only to this folder.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/329>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jeckodevelopment** [comment]
@brianteeman do you mean that is easy to restrict permission to a specific folder?

**Comment by brianteeman** [comment]
Yes with JCE that is super easy. Or you can make it simply that no one has
the access to delete


On 12 May 2016 at 09:51, Luca Marzo <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> do you mean that is easy to
> restrict permission to a specific folder?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/329#issuecomment-218697519>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Joomv** [comment]
Brian is correct all that needs to happen is a profile set up for the user group and you can customise all of it to high heaven including media folder access and permissions within it.

**Comment by jeckodevelopment** [comment]
Who can do it?
Maybe only @sanderpotjer has access

**Comment by Joomv** [comment]
Correct I believe he is the only person with the permissions to enact on this and other issues on the portal.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting! The settings of JCE have been changed so you can no longer browse other image folders and/or delete images.

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer

**Comment by MATsxm** [comment]
@sanderpotjer 
That would be fine if you could also take a look at: 
https://github.com/joomla/joomla-websites/labels/Volunteers
Thanks

**Comment by sanderpotjer** [comment]
@MATsxm thanks. An update will be rolled out soon that will address the other items too. But this item was an setting one, others not.
