### ISSUE TITLE
[jdev] Include the website name into titles

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#330]
It could be useful to include the website name into titles on developer.joomla.org 
Now page titles are:

- Joomla! Developer Network (correct, it's the home page)
- News
- Development Status
- About

Sometimes this kind of titles are too generic. 
Just activate the option "Display website name" into configuration.

**Comment by mbabker** [comment]
Thanks for the suggestion but I think I'm going to decline it at this time in favor of more clear page titles (which ultimately become the `<title>` tags).  Another option for me would be a plugin to create a "breadcrumb" effect on the `<title>` tags (for example https://developer.joomla.org/framework/downloads.html would have a "Framework - Downloads" tag).  I don't think adding the site name necessarily makes these titles more clear other than sharing what site they're part of, especially considering that both the CMS and Framework categories have Downloads pages on the dev site.

**Comment by jeckodevelopment** [comment]
ok Michael, the aim was to have more clear page titles. The plugin to create the breadcrumb effect on the title is very interesting!
Thank you!

**Comment by mbabker** [comment]
Forgot the CMS, Framework, and Tracker sections all have menu items assigned.  So it's just a matter of working through those to set the browser title and page heading properties to the desired values and things are good to go there.
