### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by MichaelaSBrown** [joomla/joomla-websites#332]
Joomla is not letting me save, add or edit a new article or categories. The buttons just don't respond, even the click button.

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thank you
