### ISSUE TITLE
[jdocs]  404 in Proper use of the Joomla! name

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-websites#334]
Hello
The second link in the `References` section returns 404. IMHO it should lead to http://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md
Regards

**Comment by Sandra97** [comment]
Thanks for the report. Link corrected.
Next time you report an issue, please mention the url for the page containing the issue.
Closng this issue.
Re-open if needed.
