### ISSUE TITLE
[jdev] 

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#335]
Is this link supposed to error 500?  It used to show us the raw data from the tracking.

http://developer.joomla.org/stats/

**Comment by jeckodevelopment** [comment]
Link should be: https://developer.joomla.org/about/stats.html

**Comment by mbabker** [comment]
It's not supposed to 500 but until https://github.com/joomla-extensions/jstats-server/issues/26 is fixed it does.

The link sending the 500 is the base of the API as documented at https://developer.joomla.org/about/stats/api.html while the link @jeckodevelopment shared is a landing page of sorts giving a summary of the collected data.
