### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by mona1961** [joomla/joomla-websites#336]
Deseaba quitar la palabra administrador de cada pagina, la queria ocultar pero como no sabia puse publico, y ahora no puedo ingresar a la pagina. Necesito ayuda

**Comment by mbabker** [comment]
Please use the forums for support.  Also note that renaming core directories will break Joomla and it is suggested you should not do this.

Google Translate: Por favor utilice los foros de soporte. También tenga en cuenta que el cambio de nombre directorios centrales se romperán Joomla y se sugiere que no debe hacer esto.

http://forum.joomla.org

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
