### ISSUE TITLE
Google Tag Manager code being loaded incorrectly on joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#337]
GTM containers should be loaded immediately after the opening body tag, but on joomla.org it is being loaded *after* the *closing* body tag.  This is incorrect - see quick start guide: https://developers.google.com/tag-manager/quickstart

Ideally we need to shift the GTM container to immediately after the body tag opens.

**Comment by mbabker** [comment]
Umm, it is being loaded right after the `<body>` tag opens.  That's how it's coded in the base template.  There are some other analytics things being loaded just before the closing `</body>` tag but not related to GTM.

**Comment by jeckodevelopment** [comment]
If i look to the code, it seems to be in the correct position.

![jord-gtm](https://cloud.githubusercontent.com/assets/733133/15290536/6cdafcb2-1b79-11e6-9824-1db415111710.PNG)

**Comment by RCheesley** [comment]
Yes sorry blonde moment here .. it wasn't that which was being flagged, it was that analytics is being fired outside the tag - if you install tag inspector it's throwing errors:

https://support.google.com/tagassistant/answer/3059154?ref_topic=2947092#move_head
