### ISSUE TITLE
[jorg] Analytics being loaded outside Google Tag Manager on joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#338]
When you look at joomla.org with Google's Tag Assistant it is throwing some errors, because Analytics is being loaded outside the GTM container at the bottom of the page in the footer area.

I'm not sure if we need to be doing this, as the container has got analytics set up within it.  Is there any reason to have it there?

**Comment by mbabker** [comment]
The GA tag was there long before GTM for starters and nobody ever said it should be removed?  Removing it's easy, I just have to find the plugin that's adding it again.

**Comment by RCheesley** [comment]
OK, I think that would make sense.  The GTM containers have analytics set up, using the pre-existing tags which were created.

**Comment by mbabker** [comment]
Removed the GA tags.
