### ISSUE TITLE
[all] Multiple domains loading www.joomla.org analytics tracking

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#339]
I'm not sure if this is a historical thing or if there is a purpose to this, but it seems that our joomla.org analytics profile is being double-loaded alongside a site-specific profile on many of our sites.

![hostnames-with-joomla-org-analytics](https://cloud.githubusercontent.com/assets/2930593/15291981/ace6dbce-1b78-11e6-8be5-0d1834e2b190.png)

If we want to have an overview of all our domains under one property, then I think we should set up a roll-up property (or get analytics premium, but that's oodles of money).

At the moment we have a few issues due to this - firstly we max-out our allowance quite often in terms of the number of sessions, because our joomla.org profile is tracking many of our subdomains.  Secondly, it clouds the data if you don't know to use a filter for the specific domain you are interested in.

While this will largely be resolved with the move toward unifying domains rather than having many subdomains, I think it would be sensible to do a bit of a cleanup operation.

So, my questions are:

- Does anybody know of any reason why we are double-loading profiles
- Is there any reason why we shouldn't move to having all sites load one analytics property via Tag Manager

**Comment by jeckodevelopment** [comment]
@RCheesley is the above one the complete list of sites that double load the analytics profile?

**Comment by RCheesley** [comment]
No, it's not a complete list. I can provide one if needed!

**Comment by mbabker** [comment]
I haven't a clue.  I just plug in whatever code I'm given when asked.  You might have to find folks from circa 2009-2010 to find their reasoning.

**Comment by RCheesley** [comment]
SInce Jan 2016 - https://docs.google.com/spreadsheets/d/1wbiSh94Ri3ok_fo1QLqyFoXha48Fdrf5gCPSJCA-u8E/edit?usp=sharing

Thanks @mbabker I thought that might be the case!

**Comment by RCheesley** [comment]
Domains double-loading have been identified and separate issues raised to address the issue. Discussed with SEO team and all agreed sensible approach is to remove the joomla.org profile.
