### ISSUE TITLE
[jorg] OSM News are missing

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#34]
The OSM News are missing on the Main Site.

OSM site is online see: http://opensourcematters.org/news.html

![osm_news_missing](https://cloud.githubusercontent.com/assets/2596554/9197504/02e4e1d0-4035-11e5-9554-ee7f2a472d1f.JPG)

**Comment by zero-24** [comment]
hmm is back now? Ok so closing here.

**Comment by mbabker** [comment]
Just for reference the feeds from the other domains are cached so if that does happen, I'd suggest an admin try clearing the feed module's cache then start digging into connectivity issues.
