### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by ZloOne** [joomla/joomla-websites#341]
Hello!Encountered an error!When entering the article Manager of Joomla 3.5.1
![1](https://cloud.githubusercontent.com/assets/19428762/15357260/5e88da2e-1d06-11e6-8f03-a1c2f862df3d.jpg)

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
