### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by raviaonhewitt** [joomla/joomla-websites#344]
Hello Team, 

Currently I am using 2.5.9 Joomla version and I want to upgrade it to 3.
But in the administrator window it shows, "Joomla! is up-to-date" and that we are on the latest version (which is clearly not true).
Please see the attached pic for the issue.
I have tried the most of the solutions which are available on net, but unable to upgrade it.
Please advice ASAP.

![pic1](https://cloud.githubusercontent.com/assets/19592458/15577684/268d92ba-237b-11e6-95a8-e2f310c31c43.jpg)

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks

**Comment by MATsxm** [comment]
@raviaonhewitt like @jeckodevelopment said + check the tuto
https://docs.joomla.org/Portal:Upgrading_Versions
