### ISSUE TITLE
[jcomm] 404 error on "License" menu item

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#345]
If you go to http://community.joomla.org/ and click on the "Download" menu item, within the "Getting Started with Joomla" group of links, the link "License & Usage" gives a 404 error.
http://opensourcematters.org/legal/license-copyright/gnu-general-public-license-v2.html 

New url should be: https://tm.joomla.org/licensing 

The top menu in CDN does not have this menu item.

**Comment by mbabker** [comment]
Actually that menu is on CDN though the only properties still using it are the non-3.x installs.  CDN updated.

**Comment by jeckodevelopment** [comment]
thank you @mbabker
