### ISSUE TITLE
[jcertif] Bad english

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#346]
Scanning the site I see many english grammar and spelling errors as well as several sentences that just don't make sense in english. I can only assume that there has not been any proof reading by a native english speaker. 

My greater concern is that if the web site has not been proof read then have the questions been. While errors on the web site are only superficial and look unprofessional errors in the questions can completely change the meaning of the question and lead to mistakes.

**Comment by jeckodevelopment** [comment]
Hi @brianteeman,
would you please help us in the proof reading process?
Or can you report specific pages?

Thank you for your help! :)

**Comment by brianteeman** [comment]
As I said I am more.concerned about the exam being bad English as the
consequences are much greater.

**Comment by jeckodevelopment** [comment]
We had a proof read of the exam questions. A member of the Certification Team has a degree in English and he reviewed all the questions.
But, as I said, if you want to be involved in the review process, your help would be appreciated.

**Comment by brianteeman** [comment]
Did the same person review the web site? In which case I have little faith.

**Comment by r-aa** [comment]
The questions were thoroughly reviewed and should not contain any errors. If you find an error, please report it. I'm not sure expressing concerns without any specifics is helpful.

As for the website, it does need to be proofread.

**Comment by brianteeman** [comment]
@r-aa its impossible for me to comment or report on the questions. As for the web site there is a whole community of native english speakers you can ask

**Comment by RCheesley** [comment]
Perhaps it would be helpful going forward to give site builders a route
through which they can reach out to native English speakers and ask for
support in this way.

I'm not sure if the en-GB working group would be the best place for people
to ask for support, but that might be a sensible place to start - if not
maybe it would be helpful to have a group of people who are willing to help
with this kind of task and a clear way to get in touch with them.

It might be good to give a bit more description on the Get Involved part of
the volunteers portal on the en-GB group explaining how people can reach
out to native English speakers for proof-reading support, for example.
Marketing have a form which people complete to request support, perhaps
something similar would work?

This is something we could potentially document within leadership/marketing
as a step for website builders to go through prior to live deployment.


*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 4 June 2016 at 15:12, Brian Teeman <notifications@github.com> wrote:

> @r-aa <https://github.com/r-aa> its impossible for me to comment or
> report on the questions. As for the web site there is a whole community of
> native english speakers you can ask
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/346#issuecomment-223757809>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACy3oTJjknbsCr_-T__9NJS6bU0MdM7aks5qIYfagaJpZM4Ioap3>
> .
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by brianteeman** [comment]
+100

On 6 June 2016 at 10:08, Ruth Cheesley <notifications@github.com> wrote:

> Perhaps it would be helpful going forward to give site builders a route
> through which they can reach out to native English speakers and ask for
> support in this way.
>
> I'm not sure if the en-GB working group would be the best place for people
> to ask for support, but that might be a sensible place to start - if not
> maybe it would be helpful to have a group of people who are willing to help
> with this kind of task and a clear way to get in touch with them.
>
> It might be good to give a bit more description on the Get Involved part of
> the volunteers portal on the en-GB group explaining how people can reach
> out to native English speakers for proof-reading support, for example.
> Marketing have a form which people complete to request support, perhaps
> something similar would work?
>
> This is something we could potentially document within leadership/marketing
> as a step for website builders to go through prior to live deployment.
>
>
> *Ruth Cheesley*
> *CEO & Co-Founder*
>
> Virya Group Limited
>
> P: +44 (0) 1473 852130
> E: ruth.cheesley@viryagroup.com
> M: +44 (0) 7920 404314
>
> On 4 June 2016 at 15:12, Brian Teeman <notifications@github.com> wrote:
>
> > @r-aa <https://github.com/r-aa> its impossible for me to comment or
> > report on the questions. As for the web site there is a whole community
> of
> > native english speakers you can ask
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/joomla/joomla-websites/issues/346#issuecomment-223757809
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ACy3oTJjknbsCr_-T__9NJS6bU0MdM7aks5qIYfagaJpZM4Ioap3
> >
> > .
> >
>
> --
>
> Be like me, be Carbon free - don't print this and save a tree
> IMPORTANT: The contents of this email and any attachments are
> confidential.
> They are intended for the named recipient(s) only. If you have received
> this email by mistake, please notify the sender immediately and do not
> disclose the contents to anyone or make copies thereof.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/346#issuecomment-223905786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8XtPPKlhalyZSw_x67KnVYMxAFVYks5qI-OHgaJpZM4Ioap3>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
