### ISSUE TITLE
[jcomm] User Groups - Broken links

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#347]
If I search on Google for "Joomla! User Group Bogota" i get a series of results that give me 404 errors.
Broken links are the following:
`http://community.joomla.org/user-groups/colombia/joomla-user-group-bogota.html`
`http://community.joomla.org/user-groups/colombia/joomlabog-community.html`
`http://community.joomla.org/user-groups/colombia.html`

I guess that the JUG has been unpublished and there are no other JUGs in that Region, so also the "Colombia" page gives 404.
Maybe it could be useful to have a redirect for the country page when all the JUG in a region had been unpublished.

**Comment by Joomv** [comment]
This was when I was experimenting (unsuccessfully) with a router.  
This issue no longer exists.
