### ISSUE TITLE
[jcertif] Broken responsive display of the top part

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#348]
Hi,
It seems some CSS for the search box broke the responsive display of the top part of the website, for screen resolutions between 768px and 979px. 
Just add this to your CSS custom file:
```
.navbar-inverse .navbar-search .search-query {
  width: 100px;}
```
And it should solve this issue.
![home - joomla certification program 2016-05-30 08-46-34](https://cloud.githubusercontent.com/assets/4682328/15649973/6c22cff0-2643-11e6-80eb-bd7e531cd08f.png)

**Comment by jeckodevelopment** [comment]
Thank you for your report Sandra.
I just noticed András and he's going to fix the issue.

**Comment by r-aa** [comment]
Got it, thanks.

**Comment by Sandra97** [comment]
Thank you - Closed
