### ISSUE TITLE
[jcertif] Padding removed in your CSS override

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#349]
Hi, 
I noticed on this page https://certification.joomla.org/badge that you don't have any padding in the content part, as it has been deleted in your custom CSS, resulting in a not really nice display.
If you just remove your `padding:0` in your custom CSS, the display should be back to normal and better.
![badge - joomla certification program 2016-05-30 08-55-53](https://cloud.githubusercontent.com/assets/4682328/15650195/d3d6af8a-2644-11e6-9634-cb3ab4f67378.png)

**Comment by jeckodevelopment** [comment]
Thank you for your report Sandra.
I just noticed András and he's going to fix the issue.

**Comment by r-aa** [comment]
Got it, thanks.

**Comment by Sandra97** [comment]
Thank you! 
Closed
