### ISSUE TITLE
[jcertif] Suggestion for the header part

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#350]
Hi, 
Just a suggestion to improve the display.
For screens between 737px and 767px, you should keep the native CSS of the template in order to center the title and buttons (you just have to delete your `!important `overrides to have it centered).
Or if you don't want them to be centered for this strange media query, just add a `float:left` so that both elements can be on the same line.
![3](https://cloud.githubusercontent.com/assets/4682328/15650401/4d676686-2646-11e6-8899-70d366915c1e.png)

**Comment by jeckodevelopment** [comment]
Thank you for your report Sandra.
I just noticed András and he's going to fix the issue.

**Comment by r-aa** [comment]
There's some reason for this which I can't remember right now, but I'll take a look.

**Comment by jeckodevelopment** [comment]
@r-aa do you have any update on this?

**Comment by mbabker** [comment]
Updates?

**Comment by jeckodevelopment** [comment]
Nothing from me at the moment. Let me ask on Glip!

**Comment by Adamzynoni** [comment]
😉

**Comment by r-aa** [comment]
Fixed.

**Comment by jeckodevelopment** [comment]
Thanks.
Closing re-open if needed.
