### ISSUE TITLE
[jcertif] Menu issue

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#351]
Ping @r-aa
Yes, it's me again... 
On this page: https://certification.joomla.org/support/department/support-services
For screen resolutions between 768px and 979px, the hamburger menu is displayed instead of the "normal" menu, reason why you have a blank space at the top (the hamburger menu is supposed to be displayed for screens up to 767px)
![support - joomla certification program 2016-05-30 14-10-16](https://cloud.githubusercontent.com/assets/4682328/15656010/bd9ff75e-2670-11e6-831d-d6ce279a5194.png)

**Comment by r-aa** [comment]
We had some difficulty reconciling the template CSS and the support component's own CSS. It's ok now but not perfect - I'll have another go at it.

**Comment by jeckodevelopment** [comment]
Thank you @r-aa

**Comment by jeckodevelopment** [comment]
@r-aa did you already fixed the menu?
Can i close?

**Comment by Sandra97** [comment]
@jeckodevelopment, if you visit the website, you'll see the issue is still present.

**Comment by jeckodevelopment** [comment]
you're right. And we have also other issues about responsivity on that page.
There's a conflict between Maqma Helpdesk and the standard Joomla! template.
Do you have suggestions?

**Comment by Sandra97** [comment]
Only thing I can find is that the issue seems to be do to a declaration in this file: https://certification.joomla.org/media/com_maqmahelpdesk/css/bootstrap-responsive.min.css

**Comment by Joomv** [comment]
I can help you fix this tomorrow. It is fixed on the cjo sandbox





On Fri, Jun 10, 2016 at 3:11 AM +0200, "Sandra97" <notifications@github.com> wrote:












Only thing I can find is that the issue seems to be do to a declaration in this file: https://certification.joomla.org/media/com_maqmahelpdesk/css/bootstrap-responsive.min.css

**Comment by jeckodevelopment** [comment]
Thank you @Joomv

**Comment by Sandra97** [comment]
Just a reminder... Can someone please have a look to this issue and solve it? Thanks.

**Comment by mbabker** [comment]
The hamburger menu displays at the right resolution now.
