### ISSUE TITLE
[joomla.org] advanced search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#352]
Thanks for switching to advanced search

Can we remove the "author" search filter please as it is not correct. 

For historical reasons when some people had their access to the site removed their usernames were deleted and the content they had created was given the first available user. So for example on j.org you wont find my name as an author although I wrote almost all the early content and instead that content will be tagged with the author as jinx.

**Comment by mbabker** [comment]
Unpublished the author content map, the option's gone now.

**Comment by brianteeman** [comment]
Thanks

On 30 May 2016 at 20:44, Michael Babker <notifications@github.com> wrote:

> Closed #352 <https://github.com/joomla/joomla-websites/issues/352>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/352#event-676304146>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8RA6JlwsjsxnlFN6nStaRp2p3Zguks5qGz4GgaJpZM4Ip_Ux>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
