### ISSUE TITLE
[jcomm] Analytics is double-loaded on community.joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#353]
**The problem**

On community.joomla.org it seems that Google Analytics is being loaded twice - once for the property set up to be used on community.joomla.org and once for the property for the main joomla.org site, which we think is probably a historical attempt to gather all data in one analytics profile.

**Why we need to fix it**

Unfortunately this is causing some problems because there is so much data we can't view it all due to limits imposed by Google Analytics, and also it's confusing for people interpreting the information.

After discussion with other SEO team members, it was decided that we should address this issue by requesting the removal of the Joomla.org tracking code from our subdomains.

**What we need you to help us with**

We would be grateful if you could remove the tracking code containing the ID: UA-544070-3, which is the tracking code for the joomla.org website.  

Going forward we would really like to move over to using Google Tag Manager to deploy analytics tracking codes - the current release of the Joomla template should provide for this.

If this is possible, your container ID is GTM-WQNG7Z - it already contains your Analytics tag. 

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
This has been resolved :)

**Comment by Joomv** [comment]
In future Ruth - I'm here.

**Comment by RCheesley** [comment]
Thanks @Joomv for fixing this :)
