### ISSUE TITLE
[jorg] Analytics is being double-loaded on joomla.org/3

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#356]
**The problem**

On joomla.org/3 it seems that Google Analytics is being loaded twice - once within Tag Manager and once as a separate Analytics tag.

**Why we need to fix it**

Unfortunately this causes some problems, and cause data in Analytics to be inaccurate.

**What we need you to help us with**

We would be grateful if you could remove the tracking code being set outside of Google Tag Manager.

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
@mikeveeckmans not sure if this is one for you to address?

**Comment by Sandra97** [comment]
Separate Analytics Tag removed.
Closing this issue.
Re-open it if needed.

**Comment by RCheesley** [comment]
Thanks for the quick action @Sandra97 :+1:
