### ISSUE TITLE
[jmag] Analytics being double-loaded on magazine.joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#357]
**The problem**

On magazine.joomla.org it seems that Google Analytics is being loaded twice - once for the property set up to be used on magazine.joomla.org and once for the property for the main joomla.org site, which we think is probably a historical attempt to gather all data in one analytics profile.

**Why we need to fix it**

Unfortunately this is causing some problems because there is so much data we can't view it all due to limits imposed by Google Analytics, and also it's confusing for people interpreting the information.

After discussion with other SEO team members, it was decided that we should address this issue by requesting the removal of the Joomla.org tracking code from our subdomains.

**What we need you to help us with**

We would be grateful if you could remove the tracking code containing the ID: UA-544070-3, which is the tracking code for the joomla.org website.  

Going forward we would really like to move over to using Google Tag Manager to deploy analytics tracking codes - the current release of the Joomla template should provide for this.

If this is possible, your container ID is GTM-WG7372 - it already contains your Analytics tag. 

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
@helvecio @JacquesR could you look into this please? Not sure if this will be fixed with the migration or whether it can be addressed now :)

**Comment by JacquesR** [comment]
@RCheesley I have now removed the Analytics code on the JCM, and replaced it with the Google Tag: GTM-WG7372.
I've confirmed that data is coming through to UA-544070-25 OK.
You can close if everything looks OK from your side.
