### ISSUE TITLE
[jrescs] Analytics is being double-loaded on resources.joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#358]
**The problem**

On resources.joomla.org it seems that Google Analytics is being loaded twice - once for the property set up to be used on resources.joomla.org and once for the property for the main joomla.org site, which we think is probably a historical attempt to gather all data in one analytics profile.

**Why we need to fix it**

Unfortunately this is causing some problems because there is so much data we can't view it all due to limits imposed by Google Analytics, and also it's confusing for people interpreting the information.

After discussion with other SEO team members, it was decided that we should address this issue by requesting the removal of the Joomla.org tracking code from our subdomains.

**What we need you to help us with**

We would be grateful if you could remove the tracking code containing the ID: UA-544070-3, which is the tracking code for the joomla.org website.  

Going forward we would really like to move over to using Google Tag Manager to deploy analytics tracking codes - the current release of the Joomla template should provide for this.

If this is possible, your container ID is GTM-K8CR7K - it already contains your Analytics tag. 

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
@genr8r could you take a look at this please?

**Comment by genr8r** [comment]
brief rant - I know asking for things to be included in core is overdone.  That said I think GA is good candidate. This exercise has me thinking of all the ways tracking codes are included in Joomla sites. It can be brought from the template whether as part of a framework or straight entry into index.php. I have several components that I use on a regular basis that do it (sh404SEF and jsitemap among others). My first hit on the JRD was as a module setup in the debug position, but alas it was unpublished: so no joy there. I finally hit on it as custom plugin named without using the words google or analytics. I am not really grumpy about it, just struck me that we might benefit from one "right Joomla way" of doing it. The current state of affairs on this feels like the kind of kludge I expect in WP. /rant

Ok, thanks for bearing with me. I have pulled out the code that you requested. It does leave the UA-544070-21 code still intact.  Let me know if you want that one pulled out right away too or if I should hold off until we get Google Tag Manager in place.

I am going to pull in @aDaneInSpain as he helped significantly with our most recent design updates on the JRD.  I am not sure from where to pull the most recent version of the Joomla template and would be hesitant to update it without getting the go ahead from Søren.  I am sure everything was done in a way that the template can be updated, but it never hurts to double check first.

Feel free to let me know if you need anything else in the meantime.

**Comment by RCheesley** [comment]
Hi Brian,

Actually Michael Babker wrote it into the Joomla template so that it's not
a hassle for people to implement.  GTM gets loaded in pretty easily.  If
you need his guidance on how to do this just ask.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 3 June 2016 at 17:16, Brian Mitchell <notifications@github.com> wrote:

> brief rant - I know asking for things to be included in core is overdone.
> That said I think GA is good candidate. This exercise has me thinking of
> all the ways tracking codes are included in Joomla sites. It can be brought
> from the template whether as part of a framework or straight entry into
> index.php. I have several components that I use on a regular basis that do
> it (sh404SEF and jsitemap among others). My first hit on the JRD was as a
> module setup in the debug position, but alas it was unpublished: so no joy
> there. I finally hit on it as custom plugin named without using the words
> google or analytics. I am not really grumpy about it, just struck me that
> we might benefit from one "right Joomla way" of doing it. The current state
> of affairs on this feels like the kind of kludge I expect in WP. /rant
>
> Ok, thanks for bearing with me. I have pulled out the code that you
> requested. It does leave the UA-544070-21 code still intact. Let me know if
> you want that one pulled out right away too or if I should hold off until
> we get Google Tag Manager in place.
>
> I am going to pull in @aDaneInSpain <https://github.com/aDaneInSpain> as
> he helped significantly with our most recent design updates on the JRD. I
> am not sure from where to pull the most recent version of the Joomla
> template and would be hesitant to update it without getting the go ahead
> from Søren. I am sure everything was done in a way that the template can be
> updated, but it never hurts to double check first.
>
> Feel free to let me know if you need anything else in the meantime.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/358#issuecomment-223623724>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACy3od3i6fjtfiQtBU0WlEcZN_liEoziks5qIFNbgaJpZM4Iq924>
> .
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by genr8r** [comment]
Yup,

I got that from your first message. I am just waiting to confirm that I can update to the latest template version without breaking any of the recent changes to the JRD.

My rant was for Joomla in general rather than the specific implementations of the official Joomla template. I will avoid muddying the waters on future issues, I was just annoyed at the treasure hunt required to find something as simple as tracking codes. Including the codes is always easy, it is just a question of which flavor of easy a particular Joomla instance is using.

Thanks for the quick follow up. I will stay with this until we get GTM running.

**Comment by RCheesley** [comment]
@genr8r I'm sorry to hear you've had difficulties, please do join the SEO Team Contributors group on Glip, that is the quickest way to get in touch with the SEO team who will be able to help with issues like this going forward.

Ruth

**Comment by genr8r** [comment]
thanks Ruth.  I think I have everything I need at the moment.  I should have the GTM code in place within the next 48 hours.

**Comment by genr8r** [comment]
@RCheesley I have the template updated and see that the appropriate GTM is showing up in source. We still have a GA code that is coming in off a plugin that was previously installed. So, that is both a GA code and GTM right now. Am I correct that I should unpublish the GA code so that only the GTM coming in from the template is left?

**Comment by jeckodevelopment** [comment]
@genr8r yes, you should leave only the GTM code coming from the template. 
Please remove the GA plugin.

**Comment by genr8r** [comment]
Done deal. I unpublished the plugin for the old analytics tracking code.  Did a quick confirmation on the homepage source that the GTM is pulled in right the top of the <body> per Michael's code in the template and saw no other Google kruft anywhere. Feel free to let me know if there are any more concerns related to analytics and I will chase it down.
