### ISSUE TITLE
[japi] Analytics being double-loaded on api.joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#359]
**The problem**

On api.joomla.org it seems that Google Analytics is being loaded twice - once within Tag Manager and once as a separate Analytics tag.

**Why we need to fix it**

Unfortunately this causes some problems, and makes the data in Analytics inaccurate.

**What we need you to help us with**

We would be grateful if you could remove the tracking code being set outside of Google Tag Manager.

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by mbabker** [comment]
The template's fixed, at the next deployment (typically with each CMS release) the page contents will be updated.

**Comment by RCheesley** [comment]
Great thanks @mbabker sorry for the plethora of issues this evening :)
