### ISSUE TITLE
[jcomm]Banner Adverts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#36]
I thought it would have been obvious but obviously not.
If the dimensions of an image are in the file name and they are one of the standard banner advert sizes then adblock will block them.

As a result the JWC banner is not being displayed on the community site (maybe others) to anyone using adblock.

It can be fixed in 30 seconds by renaming the name of the image to exclude the dimensions

**Comment by brianteeman** [comment]
For example none of the banners for JAB are blocked by adblock

**Comment by brianteeman** [comment]
You can see the full list of filters here https://easylist-downloads.adblockplus.org/easylist.txt

**Comment by Joomv** [comment]
@mikeveeckmans Making sure you're aware of this when setting up the new ads and closing
