### ISSUE TITLE
[jexam] Analytics tracking not in use on exam.joomla.org

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#360]
**The problem**

On exam.joomla.org it seems that there is no analytics code being used.

**Why we need to fix it**

Tracking visits to our domains gives us useful information on how people find our websites and what they do when they are using the site.  We think it would be beneficial to include Analytics tracking on this domain.

**What we need you to help us with**

We would be grateful if you could please add the Google Tag Manager tracking code, using the following container ID: GTM-TRG37W - the latest version of the Joomla template should allow you to do this.

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
@sam-suresh I think this is one for you?

**Comment by sam-suresh** [comment]
@RCheesley Thank you for reporting this issue.
Could you allow access for Joomla! Template repository? My previous request was with @pbwebdev not worked as he couldn't figure out how to allow access. 
This will allow me to have latest templates as it comes. My current template have no analytics option.

**Comment by jeckodevelopment** [comment]
If you have access to the latest version of the template, GTM code should be automatically included.

**Comment by mbabker** [comment]
If you're in the webmasters team here on GitHub you have access to https://github.com/joomla/jdotorgtemplate.  I also sent out a packaged copy of it a few days ago to most everyone I had contacts for.  Luca you were one of the recipients at your JED address so if you need to pass it forward please do.

**Comment by jeckodevelopment** [comment]
Oh! I didn't see it and after your comment i found it in my spam folder (don't know why).
Thank you!

**Comment by sam-suresh** [comment]
Thank you @mbabker. For future mailing, please add me sam.suresh@community.joomla.org. Thanks

**Comment by sam-suresh** [comment]
Updated to new template.
According to helper file it should pull GTM-NFQRK6 and in your issue you stated GTM-TRG37W. 

Getting 404 at https://exam.joomla.org. 

`GET gtm.js?id=GTM-NFQRK6  404 Not Found googletagmanager.com`

Is the container published for this site @RCheesley ?

**Comment by RCheesley** [comment]
It's the wrong ID, a container was set up in the wrong account.  Please use:


<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TRG37W"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TRG37W');</script>

**Comment by RCheesley** [comment]
GTM-TRG37W
