### ISSUE TITLE
[jforum] Analytics tracking not in use on forum.joomla.org since 2nd May

### ISSUE THREAD

**Issue by RCheesley** [joomla/joomla-websites#361]
**The problem**

On forum.joomla.org it seems that there is no analytics code being used since the 2nd May.

**Why we need to fix it**

Tracking visits to our domains gives us useful information on how people find our websites and what they do when they are using the site.  It seems that the analytics tracking might have been lost with the forum upgrade.

**What we need you to help us with**

We would be grateful if you could please add the Google Tag Manager tracking code, using the following container ID: GTM-TWSN2R.

Please let us know when you make these changes, so we can add an annotation on Google Analytics!

Thanks in advance for your help with this, please don't hesitate to contact us should you need any assistance with any of the above.

**Comment by RCheesley** [comment]
@pe7er can you help with this?

**Comment by pe7er** [comment]
Could you please contact Olaf about this? 
He will be able to add the analytics code to the forum template.

**Comment by ooffick** [comment]
That's implemented now.

Kind Regards
Olaf

**Comment by jeckodevelopment** [comment]
So i'm closing this issue.
Re-open if needed.

Thank you!
