### ISSUE TITLE
[jvols] Group without title and description

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#364]
If you go to volunteers.joomla.org you'll see a group without name and description, with only one member.
Group leader is: Gunjan Patel

The issue is that the "Group name" field should be mandatory. At the moment, if the group leader leave blank the field we have a group like this.

See the attachment.
![jvols-emptygroup](https://cloud.githubusercontent.com/assets/733133/15950997/6efca01a-2eb4-11e6-8f7a-9e729dea71a0.PNG)

**Comment by MATsxm** [comment]
@jeckodevelopment still relevant?

**Comment by jeckodevelopment** [comment]
I think it has been fixed. Can't see the group anymore.
Closing. Thank you! ;)
