### ISSUE TITLE
[jvols] - Porn Profile

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#366]
I know you are working on a "rebuild" but I guess this one may be solved before?
https://volunteers.joomla.org/joomlers/isabella-jones

**Comment by aDaneInSpain** [comment]
LOL What teams are she volunteering on?

**Comment by Radek-Suski** [comment]
Probably marketing. I think GoPappy have similar strategy :P

**Comment by MATsxm** [comment]
UP! after 2 days...

**Comment by jeckodevelopment** [comment]
@sanderpotjer can you look at this??

**Comment by MATsxm** [comment]
This one is closed
