### ISSUE TITLE
[jrescs] Error on submitting "add new listing" form and contact form

### ISSUE THREAD

**Issue by seagul30** [joomla/joomla-websites#367]
I am getting an error after submitting the "Add New Listing" form:
http://resources.joomla.org/en/my-jrd-listing
I click "add item" and "registered provider listing".
I fill in the whole form, when I click submit (obligatory fields are working ;)), then I get an error:
```
> "The requested page can't be found.
> An error has occurred while processing your request.
> ..."
```

Same when i try to click the TOS in the "Add new listings" form.

And when I fill in the contact form --> also some error.

So I cannot in contact with you through the website at all.

**Comment by genr8r** [comment]
@seagul30 thanks for the heads up on this. I have the issue resolved on both forms. Please let me know here if you have any further technical problems.
