### ISSUE TITLE
[jcomm] Unable to login to Joomla Community to add JUG listing

### ISSUE THREAD

**Issue by propellerhuvud** [joomla/joomla-websites#368]
I want to add another JUG for Sweden from this page:
http://community.joomla.org/user-groups/europe/sweden.html

Clicking "Add listing" tells me I need to login, and I have to browse the entire page to find the link att the bottom...
http://community.joomla.org/user-groups/europe/sweden/add.html

The login page just gives me a page header, and nothing more:
http://community.joomla.org/component/user/login.html

I have attached a screenshot if my link's won't show what I see. What can I do now? Is there a broken login page, or is it my Chrome browser making this error appear?

Sincerely
/Bjarne Dahlin, JUG Stockholm (to be added)
![jug-login-error](https://cloud.githubusercontent.com/assets/5646681/16034257/0d84a1f6-3211-11e6-8ef1-cb71cbf513c7.jpg)

**Comment by mbabker** [comment]
Login was purposefully disabled for the moment - http://community.joomla.org/migration-message.html

**Comment by propellerhuvud** [comment]
Thank you for clarification Michael!

Would be good if that information could be read on the login page 
itself, preventing questions like mine :-)

Kind Regards
/Bjarne

_________________
Bjarne Dahlin
Dahlin Studios
Kontor: Brantingsgatan 41
Adress: 115 35 Stockholm, Sweden
Mobil: +46(0)70 845 02 46
E-post: bjarne@dahlinstudios.se
Webb: www.dahlinstudios.se

**Comment by mbabker** [comment]
There was a redirect on that at one point.  Honestly I haven't an idea why that stopped working and considering the upgraded site is about to launch I personally don't care enough to dig too deep into it.

**Comment by propellerhuvud** [comment]
Fully understandable :-) Better prioritize more important stuff. I'll 
wait for it to launch then. Thank you for taking time to answer! :-)

Regards
/Bjarne

_________________
Bjarne Dahlin
Dahlin Studios
Kontor: Brantingsgatan 41
Adress: 115 35 Stockholm, Sweden
Mobil: +46(0)70 845 02 46
E-post: bjarne@dahlinstudios.se
Webb: www.dahlinstudios.se

**Comment by jeckodevelopment** [comment]
So i think we can close this issue.
Re-open if needed.

Thank you
