### ISSUE TITLE
[jvols] Fake volunteers / Non-compliant with rules

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#369]
Following a list of profiles that are non-compliant with Volunteers portal rules.

They don't represent an individual, in some cases they are spam profiles:
- https://volunteers.joomla.org/joomlers/balina100 
- https://volunteers.joomla.org/joomlers/business-ballance 
- https://volunteers.joomla.org/joomlers/ernesto-a 
- https://volunteers.joomla.org/joomlers/amec 
- https://volunteers.joomla.org/joomlers/derek-pierce 
- https://volunteers.joomla.org/joomlers/faresahmmed
- https://volunteers.joomla.org/joomlers/global-it-experts
- https://volunteers.joomla.org/joomlers/ifsccode
- https://volunteers.joomla.org/joomlers/imagosonus
- https://volunteers.joomla.org/joomlers/jeanne-hale
- https://volunteers.joomla.org/joomlers/jame-midfield
- https://volunteers.joomla.org/joomlers/joe-economy
- https://volunteers.joomla.org/joomlers/lisa-henry
- https://volunteers.joomla.org/joomlers/lacomduweb
- https://volunteers.joomla.org/joomlers/rammi-rammi
- https://volunteers.joomla.org/joomlers/softhopperbd
- https://volunteers.joomla.org/joomlers/sosidee-com
- https://volunteers.joomla.org/joomlers/ssasdsd
- https://volunteers.joomla.org/joomlers/strukt
- https://volunteers.joomla.org/joomlers/tendenciaspararopasdemujeres
- https://volunteers.joomla.org/joomlers/tradcatknight
- https://volunteers.joomla.org/joomlers/utente00
- https://volunteers.joomla.org/joomlers/user

They use a logo (or something like that) instead of a face picture:
- https://volunteers.joomla.org/joomlers/dawid 
- https://volunteers.joomla.org/joomlers/a-bo-lee 
- https://volunteers.joomla.org/joomlers/ahmad-taufik
- https://volunteers.joomla.org/joomlers/diego-viegas
- https://volunteers.joomla.org/joomlers/guilherme-shiga
- https://volunteers.joomla.org/joomlers/hilario-guzman
- https://volunteers.joomla.org/joomlers/joao-batista
- https://volunteers.joomla.org/joomlers/jonatas-medeiros
- https://volunteers.joomla.org/joomlers/massimo
- https://volunteers.joomla.org/joomlers/mireia
- https://volunteers.joomla.org/joomlers/nk-shastri
- https://volunteers.joomla.org/joomlers/patrick-toulze
- https://volunteers.joomla.org/joomlers/rifat-wahid-alif
- https://volunteers.joomla.org/joomlers/rob
- https://volunteers.joomla.org/joomlers/vaishali
- https://volunteers.joomla.org/joomlers/webdongle 
People in the list above should be contacted and they should update their profile picture in order to be compliant with the policy of jvols. Otherwise their profile picture should be replaced by the standard placeholder picture. 

This one should be edited to include First name and Last name of the volunteer, since he/she is involved in a team (Bug Squad)
- https://volunteers.joomla.org/joomlers/webdongle

**Comment by aDaneInSpain** [comment]
Good work. That must have taken some time to go through.

**Comment by mandville** [comment]
most of these are existing profiles that were reported back in January and again in march and is an ongoing issue.eg https://volunteers.joomla.org/joomlers/business-ballance is on the list on this post https://github.com/joomla/joomla-websites/issues/98#issuecomment-217525196
i believe therefore that the site is acting as it should allowin people to easiy register the issue is the administration of the website, and possibly the missing "report this spammer" button, uch as there is no bug or technical issue apparent, why is it even on github?

**Comment by aDaneInSpain** [comment]
GitHub is a great centralized place to create, assign, discuss and resolve issues. I agree that this is not necessarily a technical issue, but it is an issue with the site. Does it bother you that it is created here?

**Comment by mandville** [comment]
it seems apparent that the previous mentioned concerns on this website have not been addressed over the last 6/7 months. 

https://volunteers.joomla.org/joomlers/nk-shastri
https://volunteers.joomla.org/joomlers/r-f
https://volunteers.joomla.org/joomlers/pranji-p-s
https://volunteers.joomla.org/joomlers/rkdcjfwhvo
https://volunteers.joomla.org/joomlers/s
https://volunteers.joomla.org/joomlers/silence-programer
https://volunteers.joomla.org/joomlers/seriousjack4
https://volunteers.joomla.org/joomlers/softhopperbd
https://volunteers.joomla.org/joomlers/sosidee-com
https://volunteers.joomla.org/joomlers/tendenciaspararopasdemujeres
https://volunteers.joomla.org/joomlers/ssasdsd

**Comment by wilsonge** [comment]
What actually are the volunteer portal rules. I dealt with the first 2 on mandville's list as they were reasonably obvious spam profiles. However https://volunteers.joomla.org/joomlers/pranji-p-s is an empty account and likely not a Joomla volunteer. BUT having said that I can't find any Volunteer portal rules about profile images etc. (maybe I missed it). Do we actually have a policy on this - or are we just going to be super strict about things?

**Comment by brianteeman** [comment]
You are on holiday. Switch off.

**Comment by mandville** [comment]
the first paragraph of the FaQ states it regarding member. no "realistic"  rules found regarding avatars etc 
is there any input from  https://volunteers.joomla.org/working-groups/volunteers-portal-team 
Q: What is a "Joomler"?
**A: Joomlers are volunteers that contribute to the Joomla project.**

**Comment by jeckodevelopment** [comment]
@wilsonge , there's a rule about profile pictures, you can find it when you try to upload a new profile picture.
![jvols-pic-rules](https://cloud.githubusercontent.com/assets/733133/16555649/0357dba6-41d6-11e6-9d2f-cb7be4aa5f39.PNG)

**Comment by mandville** [comment]
i would consider that blue box a guidance not a rule. 
under that guidance i can upload a picture of a cat/polar bear/voodoo doll
Now if you said "you must upload a picture of yourself, profiles without real people will be removed" is more of a rule.

**Comment by jeckodevelopment** [comment]
Another fake: https://volunteers.joomla.org/joomlers/1327-hlektroniko-tsigaro

**Comment by sanderpotjer** [comment]
As much as possible "fake" / "spammer" users have been removed. Besides that an "Report as Spammer" button is added below a Joomler profile (visible after login) that can be used to report spam profiles. 

<img width="249" alt="screen shot 2016-08-22 at 21 17 56" src="https://cloud.githubusercontent.com/assets/522834/17868273/73c48728-68ae-11e6-8412-98327f19ba93.png">

The registration workflow has been improved too, which should prevent spammers in the first place. For the past days this seems to work well.

**Comment by jeckodevelopment** [comment]
Thank you
