### ISSUE TITLE
[jmag] error in the source for the hreflang

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#37]
Reported by JM on Glip 15/08/11

>http://magazine.joomla.org/es/
>we get for the alternate in the source:
> link href="http://magazine.joomla.org/en/" rel="alternate" hreflang="pl-PL" /
>which is obviously wrong

**Comment by MATsxm** [comment]
@helvecio @JacquesR could you please see with Guillermo about it?

**Comment by JacquesR** [comment]
Fixed. It seems it was a remnant from when a Polish version of the JCM was intended.
There's a different issue in how the alternate hreflang is used on this old site, but we will look at that for the new site.

**Comment by MATsxm** [comment]
Thanks @JacquesR
