### ISSUE TITLE
[jcomm] Login prompted when trying to access the JUG section

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#370]
If i try to access the section about Joomla! User Groups (https://community.joomla.org/user-groups.html) the website prompts me a login popup (not the Joomla one). 
It seems to be the htaccess/htpasswd restriction.
If I close the popup, I can see the destination page without any error.

The popup text is in Italian in the screenshot, because the authentication is demanded to the browser.

![2016-06-16](https://cloud.githubusercontent.com/assets/733133/16114106/cbf7ace6-33bf-11e6-97f4-1751d9988c76.png)

If i access directly a JUG listing page, no popup is shown.

**Comment by mbabker** [comment]
Looks fixed?

**Comment by Radek-Suski** [comment]
Has been. Thanks for reporting

**Comment by jeckodevelopment** [comment]
Thank you @Radek-Suski

**Comment by Radek-Suski** [comment]
It was Rowan actually :)

**Comment by jeckodevelopment** [comment]
So thank you @Joomv
