### ISSUE TITLE
[jcomm] Missing social feeds

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#371]
Can't see the widgets of the social feeds (Facebook and Twitter)

![jcomm-feeds](https://cloud.githubusercontent.com/assets/733133/16114496/d4f28d1e-33c1-11e6-9a6d-4aa6976fcc55.PNG)

**Comment by Joomv** [comment]
Thank you for pointing this out - I completely forgot about those, Facebook and Twitter JS are now enabled on that page and feeds load fine.

I'll make this look better when I have some time.  Will leave this open as a reminder.

**Comment by jeckodevelopment** [comment]
Thank you again for your great work @Joomv :)
