### ISSUE TITLE
[dashboard] Core Developers

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#372]
https://dashboard.joomla.org/

![pre](https://cloud.githubusercontent.com/assets/1296369/16115113/19edeea4-33bd-11e6-9925-594886ca88e5.png)

What/who are Core Contributors? 

We spent quite a lot of time educating people that there is no such thing as a core contributor

**Comment by jeckodevelopment** [comment]
Could we use "Frequent" instead of "Core"? What's your opinion @brianteeman ?

**Comment by brianteeman** [comment]
My opinion is that the entire site is completely broken and uselesss

On 16 June 2016 at 12:26, Luca Marzo <notifications@github.com> wrote:

> Could we use "Frequent" instead of "Core"? What's your opinion
> @brianteeman <https://github.com/brianteeman> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/372#issuecomment-226458670>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8d8HdhCXJ93hbq27-tyxLlrTXaOzks5qMTLhgaJpZM4I3SO->
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I doubt we can change the text but even if we could the question is how is
that term defined. I would guess it is people with github commit access. In
which case neither frequent or core is correct

**Comment by brianteeman** [comment]
My guess was wrong

On 16 June 2016 at 12:45, Brian Teeman <brian@teeman.net> wrote:

> I doubt we can change the text but even if we could the question is how is
> that term defined. I would guess it is people with github commit access. In
> which case neither frequent or core is correct
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jeckodevelopment** [comment]
Closing because Dashboard will be deleted.
See #424
