### ISSUE TITLE
[dashboard] Contributor names

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#373]
https://dashboard.joomla.org/scm.html

![kjua](https://cloud.githubusercontent.com/assets/1296369/16115167/6d4faca4-33bd-11e6-8cc8-229130836038.png)

No idea where those names come from but I am 99.999% certain that I have never misspelled my name anywhere and would appreciate it being corrected

**Comment by jeckodevelopment** [comment]
Closing because Dashboard will be deleted.
See #424
