### ISSUE TITLE
[Dashboard] Undefined

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#374]
Click on any persons name to view there detailed record - eg this one for Michael Babker https://dashboard.joomla.org/people.html?id=9fdbb2055c3bb2a6e7277a1fa35eac8becaf3008 

You will see the title is Undefined

![c2jl](https://cloud.githubusercontent.com/assets/1296369/16115261/da7954ce-33bd-11e6-9366-84f88c076785.png)

**Comment by jeckodevelopment** [comment]
Closing because Dashboard will be deleted.
See #424
