### ISSUE TITLE
[dashboard] search doesnt work

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#375]
The search box on the top right doesnt appear to do anything

Looking in the console I got all these 404

https://dashboard.joomla.org/data/json/all.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/markers.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/project-info.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/projects_hierarchy.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/viz_cfg.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-lists.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-evolutionary.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-static.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-top.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its-quantiles-month-time_to_fix_hour.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-quantiles-month-time_to_attention_hour.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scr-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scr-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mediawiki-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mediawiki-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-demographics-aging.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-demographics-birth.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its-markov.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-organizations.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-repos.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/repos-map.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scm-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scr-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-countries.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scr-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-domains.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scm-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/scr-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-projects.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/its_1-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/mls-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/irc-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/people-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/downloads-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/qaforums-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/releases-people.json Failed to load resource: the server responded with a status of 404 (Not Found)
https://dashboard.joomla.org/data/json/eventizer-people.json Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jeckodevelopment** [comment]
Closing because Dashboard will be deleted.
See #424
