### ISSUE TITLE
[jcomm] Unfloat Login menu item on mobile

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#376]
The login item stands out like a sore thumb on mobile with its float.  Any way that could be unfloated?

<img width="309" alt="screen shot 2016-06-16 at 7 42 01 am" src="https://cloud.githubusercontent.com/assets/368545/16117089/ec2ea69c-3395-11e6-8fe1-e37272c43584.png">

**Comment by Joomv** [comment]
When the shop is enabled shortly, it won't as it is next to a mycart. Log in as a super on the front end to see. I'll unfloat the element for now though.

**Comment by Joomv** [comment]
Actually do we need it up top at all?  The Shop has a different menu and a my account item.  We have login in the footer shall we just kill it in the main? @mbabker

**Comment by mbabker** [comment]
I'd say kill it for the main toolbar personally.  If you need to log in anywhere site wide every site has a standard link in the footer.  Plus you have the login module on the sidebar so I honestly don't think you'd need a menu item for this at all.

**Comment by mbabker** [comment]
* displayed menu item, should still have it so the login page has a SEF URL, but hide it

**Comment by Joomv** [comment]
Moved to hidden.  Closed.
