### ISSUE TITLE
[jcomm] Blogs not showing date

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#377]
At a minimum please show the created/published date for the blog posts as was happening on the 1.5 site.  Optionally the author name could also be shown (it was on the 1.5 site, some may debate the usefulness of this one though).

**Comment by brianteeman** [comment]
Author name is fine to show IF it is the author but for historical reasons the authors in the database are not correct for the older posts

**Comment by Joomv** [comment]
We now have Author & Published Date on everything bar the homepage, @brianteeman can you give me some examples of wrong authors so I can try and find a pattern and at least add aliases so the names are right?

**Comment by brianteeman** [comment]
It "might" just be an issue on www I will need to check but basically what
happened in the past is that users were removed and so the author became
the next available user. For example everything I wrote on www has johan as
the author now

On 16 June 2016 at 15:07, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> We now have Author & Published Date on everything bar the homepage,
> @brianteeman <https://github.com/brianteeman> can you give me some
> examples of wrong authors so I can try and find a pattern and at least add
> aliases so the names are right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/377#issuecomment-226495744>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Wc0PXgURQOV9u6YldIN6EAz7HZBks5qMVi_gaJpZM4I3YpT>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
That might be a separate project in general for www but when we were doing the 2.5 -> 3.x migration I changed the authors on a lot of articles which had no authors over to the generic "Joomla Communications Team" account.  Either way at least on that site and the developer network with how it was recreated when it moved to 3.x user and content continuity seems to have been lost.

**Comment by Joomv** [comment]
I preserved the 1.5 users who "owned" something, be it a listing, an article or a help desk item.  Can't vouch for anything that happened prior to that in the 1.0x days but if you find anomalies, please let me know.  Going to close this issue for now.
