### ISSUE TITLE
[jcomm] Some lang strings are missing 

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#378]
Great work on the new site but i have spot one thing see:

![cjorg_blogs](https://cloud.githubusercontent.com/assets/2596554/16119807/638ad1f6-33dd-11e6-9c66-64e2957e9a6a.PNG)

https://community.joomla.org/blogs.html

**Comment by Joomv** [comment]
Not seeing this my end.
http://www.openscreenshot.com/img/5762b49d7dd9d3-31166289
Checked all major browsers.

**Comment by jeckodevelopment** [comment]
Me neither.
I see all the 321 pages of the blogs without any issue about language strings.
Please check again @zero-24

**Comment by zero-24** [comment]
Hmm. Looks fixed now. Thanks who ever fixed it ;)

**Comment by brianteeman** [comment]
I just saw this problem 

![i9mp](https://cloud.githubusercontent.com/assets/1296369/16122292/6e6e1a64-33de-11e6-9e7c-10e165ab17f2.png)

**Comment by brianteeman** [comment]
Can it be re-opened please

**Comment by Joomv** [comment]
Can you give me some environment stats please?  I'm having an awful job pinning this down, I don't see it neither do some others.

**Comment by brianteeman** [comment]
And now I dont see it happen

Weird


On 16 June 2016 at 16:25, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> Can you give me some environment stats please? I'm having an awful job
> pinning this down, I don't see it neither do some others.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/378#issuecomment-226520241>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8cTCWR2wbLMbEZJNgQjOZiDU5_23ks5qMWr1gaJpZM4I3bo->
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mikeveeckmans** [comment]
can't reproduce

**Comment by Joomv** [comment]
I HATE this kind of bug with a passion - its like playing whack-a-mole

**Comment by brianteeman** [comment]
Yeah I know its a pain but at least two of us have seen it happen at
different times even if it isnt reproducable by us

On 16 June 2016 at 16:29, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> I HATE this kind of bug with a passion - its like playing whack-a-mole
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/378#issuecomment-226521498>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8TweCudVY5MaZp_jbN7MeVoGEPTLks5qMWvTgaJpZM4I3bo->
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mikeveeckmans** [comment]
Ok I was able to reproduce once : 
1. go from homepage to blogs selecting top menu item blogs
2. select on the right menu : community blog
3. at the bottom jump directly to page 8
http://www.screencast.com/t/aWtoP0vZzQI 

I was only able to reproduce once, all testings afterwards gave correct output :-( no clue what's playing here...

**Comment by Sandra97** [comment]
I had the same issue too. Can't reproduce neither

**Comment by mbabker** [comment]
My only suggestion would be try reloading `language/en-GB/en-GB.lib_joomla.ini` since the strings in question are library strings.  Either there's a parse error, some wonky cache issue, or a bad file/override is being loaded.

**Comment by Joomv** [comment]
I've checked the override - pagination call is identical to core.
I've replaced the file.
I still can't replicate it.

**Comment by Sandra97** [comment]
I currently have the issue on this page https://community.joomla.org/blogs.html even if I refresh the page (I tested it with Firefox, Chrome and Edge)
![joomla community leadership blogs 2016-06-17 13-37-49](https://cloud.githubusercontent.com/assets/4682328/16159442/d1c96a5c-3490-11e6-8035-c9c250e5e630.png)

**Comment by Joomv** [comment]
Can you humour me and try again please. That screenshot shows me that the override I put in the the pagination results has killed that error - I've just put in overrides for start and end too - I am hoping that this gets past this.  It appears to be a caching issue.

**Comment by MATsxm** [comment]
@Joomv 
as @Sandra97 is having fun with Morpheus right now, I checked and everything looks ok to me.
Thanks

**Comment by Sandra97** [comment]
I'm back... It's ok now! Thanks.

**Comment by zero-24** [comment]
Looks good to me too. Thanks :+1:
