### ISSUE TITLE
[jmag] Googlebot cannot access CSS and JS files on http://magazine.joomla.org/

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#38]
I received the following message from googles search console:
Googlebot cannot access CSS and JS files on http://magazine.joomla.org/

To: Webmaster of http://magazine.joomla.org/,

Google systems have recently detected an issue with your homepage that affects how well our algorithms render and index your content. Specifically, Googlebot cannot access your JavaScript and/or CSS files because of restrictions in your robots.txt file. These files help Google understand that your website works properly so blocking access to these assets can result in suboptimal rankings.

**Here's how to fix this issue:**

**1. Identify blocked resources**
Use the "Fetch as Google" feature to identify those resources that robots.txt directives are blocking.

**2. Update your robots.txt file**
Remove the restrictions on your site's CSS and JavaScript files from your robots.txt directives and test the changes with the Robots.txt tester. Then update your revised robots.txt file on your site and submit it to Search Console.

**3. Validate the fix using “Fetch as Google”**
Fetch and Render your page with the “Mobile: smartphone” option selected to double-check that Googlebot for smartphones renders your content properly.

**Comment by Radek-Suski** [comment]
Wondering if it makes sense to report issues for sites that are actually in re-do. Or is the new Jmag project on ice now?

**Comment by MAT978** [comment]
@pbwebdev is THE one able to answer that question.

**Comment by matthewbaylor** [comment]
We had this problem on the JED even with the correct robots.txt configuration. Took awhile until we realized if you're using any type of file versioning with CDN files (a setting in the nonumber cdn plugin) for some reason Google can't see them.

**Comment by jessicadunbar** [comment]
Radek  because there is a site in development means we need to maintain two sites ;)  and because of the reasons Matt lists best to figure it out now so its one less headache after the launch.

**Comment by Hutchy68** [comment]
From a tracking standpoint I would rather see at least one issue thread for a site in re-do. It's a "where are we" tracking point. Also, allows reference to issues existing which might be missed as pointed out. Can be a place to call for help too. eg, hey we are having problems with y & z does anyone have a few hours to help? Etc.

**Comment by Sandra97** [comment]
@JacquesR @helvecio, please can you tell us if this has been solved?

**Comment by mbabker** [comment]
http://magazine.joomla.org/robots.txt says it's still an issue.

**Comment by JacquesR** [comment]
Resolved. Replaced robots.txt with the standard Joomla one
