### ISSUE TITLE
[jorg] Missing Community News and Leadership Blog in home

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#380]
After publishing the new `community.joomla.org`, on the main website joomla.org the **Community News** and the **Leadership Blog** feeds don't show any post.

They should be linked to the new feeds.
![jorg-issue](https://cloud.githubusercontent.com/assets/733133/16120548/1b97a182-33e0-11e6-945f-8ab977d089b0.PNG)

**Comment by mbabker** [comment]
Someone with access to `feeds.joomla.org` needs to check that aspect of things and sort it.

I changed the feed modules on .org to point direct to the RSS feeds at https://community.joomla.org/blogs/leadership.feed and https://community.joomla.org/blogs/community.feed (same way we have the feed at https://developer.joomla.org/news.feed pulled in) but it's still giving the not found response.

@Joomv any ideas?

**Comment by jeckodevelopment** [comment]
@mbabker who is responsible for `feeds.joomla.org` ?
Can't find anything about feeds here https://docs.joomla.org/Joomla:The_Joomla_Websites

**Comment by Joomv** [comment]
What is the link to the page you are referencing @jeckodevelopment

**Comment by Joomv** [comment]
Ignore that - multitasking found it - looking to see if I can do anything from my end now.

**Comment by mbabker** [comment]
@jeckodevelopment I have no idea.  That thing predates me.

**Comment by jeckodevelopment** [comment]
If we find who is in charge for this, we can add him/her name to the docs page to keep things up-to-date

**Comment by Joomv** [comment]
Bizarre caching issue?  That's my best bet.  The feed links above work fine.

**Comment by jeckodevelopment** [comment]
I still see `Feed not found` message for both feeds.

**Comment by mbabker** [comment]
I've flushed the cache on the entire site, made sure the feed's accessible, still nothing.

**Comment by mbabker** [comment]
Now I've got cache off on .org for the moment.  So that isn't even a factor.

**Comment by brianteeman** [comment]
I see feed not found as well

![b59g](https://cloud.githubusercontent.com/assets/1296369/16121814/a02afe48-33dc-11e6-8e94-cfbb440cdfda.png)

**Comment by Joomv** [comment]
Checked admin tools nothing.  Feed link loads fine in a browser, have to say bit stumped on this one.

**Comment by mbabker** [comment]
I don't get any SSL related errors on the site or the RSS feeds.

**Comment by mbabker** [comment]
The Exception the module's catching has the message "No registered feed parser for type html."  So something's not coming back right.  Debugging...

**Comment by mbabker** [comment]
Feeds are working again.  Need the author data set correctly now though so that the names and avatars will display correctly.

**Comment by brianteeman** [comment]
What was the problem?

**Comment by mbabker** [comment]
Apparently https://community.joomla.org/blogs/leadership.feed is sending a HTML document when PHP's XMLReader (used by mod_feed) is requesting the feed but https://community.joomla.org/blogs/leadership.html?format=feed sends the right RSS feed.

**Comment by mbabker** [comment]
Everything's G2G.

**Comment by jeckodevelopment** [comment]
Great, thank you @mbabker
