### ISSUE TITLE
[jcomm] Accessibility unique names for links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#381]
Using "read more" means that we have multiple links with identical meaningless names for multiple links. If we use part of the title in the readmore then the links are unique and accessible.

Many a11y tools present a list of links to navigate through so obviously its not good to have several with the same name. Also it makes audio navigation fairly meaningless as this vide can show https://www.dropbox.com/s/g82fyzp8fdoj1pr/accessibility.mp4?dl=0  

(ignore the quirk about womens clothes)

**Comment by brianteeman** [comment]
It should be enough to just set "Show Title with Read More" in the options to Show

**Comment by Joomv** [comment]
2 options here.

1. As suggested above - now implemented on homepage.
2. Or adding a title to the read more as implemented at blog level.

**Comment by brianteeman** [comment]
I assumed that either would satisfy a11y but retesting with VoiceOver only
option 1 works

On 16 June 2016 at 15:57, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> 2 options here.
>
>    1. As suggested above - now implemented on homepage.
>    2. Or adding a title to the read more as implemented at blog level.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/381#issuecomment-226511031>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8ZpNAf5sPgJy7M9nRdbucUvvRSlgks5qMWRtgaJpZM4I3dXy>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Joomv** [comment]
Ok 1 it is

**Comment by brianteeman** [comment]
Thanks!!!

On 16 June 2016 at 16:14, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> Ok 1 it is
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/381#issuecomment-226516523>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8WBpcZ5PxsDVh1bXZKbIvYYFwl9gks5qMWhTgaJpZM4I3dXy>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Joomv** [comment]
I've left 2 at blog level (readlesstext is installed due to lack of historical read more breaks) and added 1 without a string length strip to it.  Closing.

**Comment by jeckodevelopment** [comment]
Thank you @Joomv
