### ISSUE TITLE
[jorg] Home page buttons

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#382]
Not a real issue, but a question.
Why do we have different sizes for buttons in home page?
![jorg-buttons](https://cloud.githubusercontent.com/assets/733133/16135639/50d27684-3425-11e6-9ab3-03a747e33e92.PNG)

They are also right aligned to the center of the page (on my screen). 

Additionally, we have some responsive issues when the screen size decrease.
![jorg-buttons 2](https://cloud.githubusercontent.com/assets/733133/16135729/d7213ad6-3425-11e6-8be1-618da33a0700.PNG)
![jorg-buttons 1](https://cloud.githubusercontent.com/assets/733133/16135730/d722ed4a-3425-11e6-88c0-c2314a6b62e1.PNG)

Please note that if the screen size decrease again, the issue disappear.
![jorg-buttons 3](https://cloud.githubusercontent.com/assets/733133/16135747/ec83c75e-3425-11e6-984e-32aa238dbcf5.PNG)

**Comment by Sandra97** [comment]
- Could you give me your screen resolution for your screenshot 1 (I can't reproduce, could be a cache issue as I changed the size of the buttons, could you refresh the page and tell me if the sizes are still diferents)
- For screenshots 2 and 3, can have you refresh the page and tell me if the buttons are ok or not (could just be a cache issue)? 
- For the last screenshot, I wrote a different display for screens under 480px

**Comment by jeckodevelopment** [comment]
First screenshot: 1366x768 (15.6" notebook screen)

**Comment by jeckodevelopment** [comment]
![jorgbuttons](https://cloud.githubusercontent.com/assets/733133/16137429/82d06a52-3433-11e6-9c51-0522bfd59a19.PNG)

Now at full resolution I see as the image above (and it's ok!)

![jorgbuttonn2](https://cloud.githubusercontent.com/assets/733133/16137463/e5528534-3433-11e6-933a-25cfdf4737cb.PNG)

But at lower sizes: menu and buttons issues.
![jorgbuttonn3](https://cloud.githubusercontent.com/assets/733133/16137459/e1dae28e-3433-11e6-9301-48d5df37d8ff.PNG)

**Comment by Sandra97** [comment]
I have the same resolution as you for 1st screenshot but display is ok for me:
![joomla the cms trusted by millions for their websites 2016-06-16 20-33-25](https://cloud.githubusercontent.com/assets/4682328/16137465/a1f448f4-3401-11e6-97ec-32be2a74d0bb.png)

**Comment by jeckodevelopment** [comment]
In fact, first is perfect now (and wonderful!)

**Comment by Sandra97** [comment]
For the last one, I can't reproduce neither for the buttons :( 
Display is correct for me (tried on several mobile devices):
![screenshot_2016-06-16-20-37-35](https://cloud.githubusercontent.com/assets/4682328/16137532/742ed74e-3402-11e6-9294-1b1adc24066b.png)

**Comment by jeckodevelopment** [comment]
Latest image, with wide buttons is ok. I sent it just for reference.

**Comment by Sandra97** [comment]
Question: did you test the responsive display on different mobile devices or with an emulator?

**Comment by jeckodevelopment** [comment]
Tested with mobile and it's ok:
`Google Chrome on Samsung Galaxy J5, 720 x 1280`

Other tests from Mozilla Firefox (latest) on Windows 10.

**Comment by jeckodevelopment** [comment]
Width: 492 px
![jorg492](https://cloud.githubusercontent.com/assets/733133/16151197/f9abf9c6-349b-11e6-9f65-444fdf033c54.PNG)

Width: 466px
![jord466](https://cloud.githubusercontent.com/assets/733133/16151212/07ae0424-349c-11e6-9917-e53cd90cc889.PNG)

Menu items displayed in a second row (without background) and buttons issue.
Can we use the method for mobile also for these size?

**Comment by Sandra97** [comment]
Are you doing these tests from your laptop?

**Comment by jeckodevelopment** [comment]
Desktop PC

**Comment by Sandra97** [comment]
On PC, you can do only "tests", it's just a simulation. Responsive display has to be verified from mobile devices, not from a laptop/PC.

**Comment by jeckodevelopment** [comment]
ok :)

**Comment by mbabker** [comment]
After you downsize the browser you really need to refresh the page.  There are other little quirks (like the JavaScript to handle sizing/sticking the menu bar) that just aren't responsive to someone resizing their browser in every possible direction (and as someone who can barely write JavaScript to save his life and finally started getting LESS when everyone went SCSS, the furthest I go when testing responsive stuff is "does it work at this viewport", not "does it work when you start at this viewport and downsize by 600 pixels").

**Comment by jeckodevelopment** [comment]
I think we can close this issue. Re-open if needed.
Thank you :)
