### ISSUE TITLE
[josm] Obsolete links / 404 Links

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#383]
Page: http://opensourcematters.org/joomla/the-joomla-community.html 

News portal link - `http://news.joomla.org `(I guess that this website no longer exists).

`please submit your short story, article, announcement or review`... links to 
`https://www.joomla.org/component/option,com_submissions/Itemid,75` and it's a 404

**Comment by jeckodevelopment** [comment]
@marijkestuivenberg can you look at this?

**Comment by Sandra97** [comment]
Closing this issue as it's a duplicate of #132
