### ISSUE TITLE
[jorg] Blog post order (Community/Leadership)

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#384]
Community News and Leadership Blog show old posts (from 2010) instead of new blog posts.
![jorg-blogs](https://cloud.githubusercontent.com/assets/733133/16146917/ce9387ba-3480-11e6-93c8-662c914a2b72.PNG)

**Comment by Joomv** [comment]
Give me 10 minutes.

**Comment by mbabker** [comment]
They're fixed.

Considering the modules are only showing items from an RSS feed, the source has to have the current content to display.  Unless mod_feed got a lot smarter overnight and supports paginating however far back 6 years has to go 😆

**Comment by jeckodevelopment** [comment]
Thank you Michael!
