### ISSUE TITLE
[jorg] One page = two different URLs

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#385]
The page **Contribute to Joomla!** is accessible from two different URLs, this creates duplicate contents on the website.

Top menu item **Contribute** has the URL: `https://www.joomla.org/contribute-to-joomla.html` 
The page is available also from the URL: `https://www.joomla.org/about-joomla/contribute-to-joomla.html` 
(a link to this page is also included in this page of OSM: `http://opensourcematters.org/joomla/support-joomla.html` )

**Comment by Sandra97** [comment]
Will see what I can do.

**Comment by jeckodevelopment** [comment]
Thank you @Sandra97 
But, who can update the link at OSM? @marijkestuivenberg ?

**Comment by Sandra97** [comment]
I don't know. But don't worry, if I succeed, I'll add a redirection ;)

**Comment by Radek-Suski** [comment]
@Saurabh1 ??

**Comment by Sandra97** [comment]
It's done and https://www.joomla.org/about-joomla/contribute-to-joomla.html redirected to https://www.joomla.org/contribute-to-joomla.html so no 404 from OSM website or from Google.
Closing this issue.
Re-open if needed
