### ISSUE TITLE
[jcomm] Author/Date not needed in "Translations" page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#386]
`https://community.joomla.org/translations/joomla-3-translations.html`

I think that we can hide publishing date and author in the translation blog view.

![jcomm-author](https://cloud.githubusercontent.com/assets/733133/16151747/fa80935e-349e-11e6-9525-9864495c62d4.PNG)

**Comment by Joomv** [comment]
Done
