### ISSUE TITLE
[jcomm] 404 error on "JoomlaSocial" menu item

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#387]
If I click on the "JoomlaSocial" menu item (right menu) under the "Connect" page, i receive a 404 error.
URL: `https://community.joomla.org/connect/joomlasocial.html`

**Comment by Joomv** [comment]
Fixed and closed.

I had to reimport the content this morning due to some ID issues that I hadn't noticed.  I'm now running a screaming frog scan but I think I've found all the issues that caused.

**Comment by jeckodevelopment** [comment]
Good job. Thank you!

**Comment by jeckodevelopment** [comment]
@Joomv , i think we can hide the author and date also here.

**Comment by Joomv** [comment]
Done
