### ISSUE TITLE
[jevnt] Unused column in event list view

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#388]
In the following pages, we have an unused column: "_End_"
`https://events.joomla.org/joomladays`
`https://events.joomla.org/user-group-meetings`
`https://events.joomla.org/joomla-conferences`
`https://events.joomla.org/archive`

This because the date of start and end of the event is shown in the "_Start_" column.
Proposal: Why don't we rename it to "_Date_" and hide the "_End_" column?

**Comment by Radek-Suski** [comment]
I don't know if it make sense to change it now as we are planning to move the events site into community.j.org very soon. I guess @Joomv will probably improve the templates as well

**Comment by jeckodevelopment** [comment]
We can consider it for the next version :)

**Comment by mbabker** [comment]
Is this still an issue with the migrated version?

**Comment by jeckodevelopment** [comment]
Not relevant now.
Closing. Thanks!
