### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Cathy15** [joomla/joomla-websites#390]
Hi,
My name is Cathy and I run the website for the Alpha Phi Fraternity. Our website stopped working out of no where when I was updating it and I know I didn't press anything wrong. It seems as if the website is gone! I don't know what to do. This is all that appears when I try to go to the joomla login for the admin.

<img width="500" alt="screen shot 2016-06-18 at 2 54 55 am" src="https://cloud.githubusercontent.com/assets/20010711/16169776/424d47f2-3500-11e6-83f7-40cbfb3f9a9c.png">

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks

**Comment by genr8r** [comment]
You can also look for a professional Joomla service provider at https://resources.joomla.org
