### ISSUE TITLE
[jcomm] Old account login removed?

### ISSUE THREAD

**Issue by propellerhuvud** [joomla/joomla-websites#391]
Hi,
I'm trying to login to the community portal (For translation of docs and upcoming JUG registration).
Now that the login is updated for 2-factor use, It looks like my old account is no longer working.
Can anyone explain what has happened, and what I should do. Can the old account be reactivated, or do I have to create a new account? None of my email addresses works for restoring passwords.

Sincerely
/Bjarne Dahlin,

**Comment by MATsxm** [comment]
Hello @propellerhuvud 
Just FYI, if you want to help in translating the JDocs, you should not login via the Community portal but directly on the Documentation site.
Please see: https://docs.joomla.org/JDOC:Documentation_Translators and welcome aboard!
Regards,

**Comment by Joomv** [comment]
For the community portal, if you didn't own an article, jug listing or support ticket, your account was not brought over.  Please register again.  Thanks.

**Comment by propellerhuvud** [comment]
Thank you for the clarification Marc!
I thought the login was centralized after the remake.
I will follow your instruction! :-)

Regards
/Bjarne

_________________
Bjarne Dahlin
Dahlin Studios
Kontor: Brantingsgatan 41
Adress: 115 35 Stockholm, Sweden
Mobil: +46(0)70 845 02 46
E-post: bjarne@dahlinstudios.se
Webb: www.dahlinstudios.se

**Comment by propellerhuvud** [comment]
Thank you for the response Rowan!
I'll fix a new account to register my JUG :-)

Regards
/Bjarne

_________________
Bjarne Dahlin
Dahlin Studios
Kontor: Brantingsgatan 41
Adress: 115 35 Stockholm, Sweden
Mobil: +46(0)70 845 02 46
E-post: bjarne@dahlinstudios.se
Webb: www.dahlinstudios.se

**Comment by jeckodevelopment** [comment]
@Joomv should we publish a notice about the "account issue" on CJO?

**Comment by Joomv** [comment]
It could be worth it – but I don’t actually see an issue here,

 

The OP in this case was looking to log into the wrong project property anyway (he needed to be in docs.) and didn’t actually own anything historically on the site, therefore his user was not brought across.

 

Historically this property has had a rather “haphazard” approach to user accounts with above registered permissions and as current webmaster of this property I’m looking to change that and by doing so minimise the user base to those who actually have a need for an account.

 

Hope this makes sense.

 

Rowan

**Comment by jeckodevelopment** [comment]
Completely agree with your opinion ;)
