### ISSUE TITLE
[jcomm] Meta data and twitter data

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#392]
https://community.joomla.org/Translations.html

The metadata is outdated 
>meta name="twitter:description" content="Please find here a list of the Joomla!™ Translation Teams with direct links to the Joomla!™ 1. 5 language packs Joomla!®1. 6 language packs will be soon available here: Joomla! 1. 6 Translation P" 

>meta name="description" content="Please find here a list of the Joomla!™ Translation Teams with direct links to the Joomla!™ 1. 5 language packs Joomla!®1. 6 language packs will be soon available here: Joomla! 1. 6 Translation P"

**Comment by Joomv** [comment]
I've dealt with this, but I am still waiting on the Translation Team to sort their section out properly.  I believe the issue has been open over 3 months.

**Comment by brianteeman** [comment]
OK - thanks - it came up while testing a core bug so thought I should
report it. Guess I should have searched first - naughty me

On 22 June 2016 at 09:45, Rowan Hoskyns Abrahall <notifications@github.com>
wrote:

> I've dealt with this, but I am still waiting on the Translation Team to
> sort their section out properly. I believe the issue has been open over 3
> months.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/392#issuecomment-227680687>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8YyoA4StEMfiSrCZ7DOxzjG1qPPJks5qOPYSgaJpZM4I7glJ>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Joomv** [comment]
Wasn’t having a pop.  I am more than happy to fix stuff like this if it is found, I was merely lamenting the fact that this section has been neglected by the team responsible for it.

 

If you find stuff like this on CJO – tag me in it and I’ll sort it.

 

Rowan.
