### ISSUE TITLE
tutorials.joomla.com is appearing as may be hacked site in google search results.

### ISSUE THREAD

**Issue by pro2512** [joomla/joomla-websites#393]
tutorials.joomla.com is appearing as may be hacked site in google search results.
http://screencast.com/t/fcJi6G0XMYl
just saw it now and wanted to inform you guys.
Thanks

**Comment by jeckodevelopment** [comment]
@pro2512 [whatever].joomla.com is not directly managed by the Joomla! Community.
joomla.com and subdomains are managed by Siteground.

@MATsxm how to report issues with joomla.com ?

**Comment by brianteeman** [comment]
Report to @mveekmans

**Comment by jeckodevelopment** [comment]
@mikeveeckmans can you please look at this?

**Comment by pro2512** [comment]
i wasn,t sure how to report to siteground guys.

**Comment by MATsxm** [comment]
@Sandra97 also sent a message to our contact... it's sunday :wink:

**Comment by mikeveeckmans** [comment]
Forwarded also ;-)

**Comment by kirilhristov** [comment]
Here is what Google detected as malicious on tutorials.joomla.com (taken from their webmaster tools): 
![screen shot 2016-06-27 at 1 52 33 pm](https://cloud.githubusercontent.com/assets/15803386/16377524/3a7416d4-3c6f-11e6-9fae-1bdcde2139e8.png)

We cleaned these files months ago, but I guess Google has an old snapshot. 

I've marked these issues as fixed and requested the site to be reviewed by them again. The form said it could take several weeks. 

We've also made sure the Joomla! installation and all extensions on tutorials.joomla.com are up to date.

**Comment by Sandra97** [comment]
Thank you very much @kirilhristov 
Closing this issue.
Re-open if needed

**Comment by kirilhristov** [comment]
Just to follow up here - everything now seems to be fine. Google's webmaster tools show no security issues for tutorials.joomla.com. The "hacked" label is also gone from Google's index. Thanks for reporting!

![screen shot 2016-07-05 at 12 57 04 pm](https://cloud.githubusercontent.com/assets/15803386/16581021/09792884-42b0-11e6-98cc-765917d39410.png)

**Comment by jeckodevelopment** [comment]
Thank you @kirilhristov

**Comment by pro2512** [comment]
thanks guys.

i was just trying to help
