### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by abchapel** [joomla/joomla-websites#395]
Our previous pastor at Ashville Bible Chapel had set up a site with your company. He has left our church on unpleasant terms and has left the website up with no means for use to update and revise. We either need access to the site or it needs to be terminated. Please advise on how to proceed. Steven K. Sawyer, Ashville Bible Chapel, Corporate President. abchapel@yahoo.com

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
