### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-websites#396]
The Subform Link ist wrong on this site: https://www.joomla.org/announcements/release-news/5660-joomla-3-6-beta-1-released.html
Right link: https://github.com/joomla/joomla-cms/pull/7829

thx for fixing!!!

**Comment by MATsxm** [comment]
looks already fixed?

**Comment by MATsxm** [comment]
ok... @wilsonge was Buzz Lightyear on this one :stuck_out_tongue:
