### ISSUE TITLE
[ALL] PHP Version Upgrade on Joomla Sites

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-websites#397]
I have requested the host to upgrade PHP version from 5.4.28 (End of Life) to 5.6+.

Please check if your site listed below is compatible with PHP 5.6+

api.joomla.org [OK]
appsserver.joomla.org [OK]
certification.joomla.org [OK]
community.joomla.org 
conference.joomla.org 
docs.joomla.org 
events.joomla.org 
exam.joomla.org [OK]
help.joomla.org 
joom.la 
magazine.joomla.org 
opensourcematters.org 
resources.joomla.org 
shop.joomla.org [MERGED - OK]
showcase.joomla.org 
training.joomla.org 
tm.joomla.org [OK]
ux.joomla.org [OK]
vel.joomla.org 
volunteers.joomla.org [OK]

**Comment by sam-suresh** [comment]
certification.joomla.org  - OK
exam.joomla.org  - OK

**Comment by rdeutz** [comment]
api.joomla.org - is static html - OK
appsserver.joomla.org - doesn't seems an aktive site
ux.joomla.org - is a forward to developer.joomla.org
volunteers.joomla.org - OK

**Comment by Sandra97** [comment]
shop.joomla.org is merged to community

**Comment by mbabker** [comment]
The server CAN NOT be upgraded until `showcase.joomla.org` is migrated off of Joomla 1.5.

**Comment by SpiritJC** [comment]
tm.joomla.org - OK

**Comment by mbabker** [comment]
@rdeutz:

> appsserver.joomla.org - doesn't seems an aktive site

That's the install from web's subdomain (the one that's not mapped behind a CDN).

Also, I'm just going to be flat out blunt here.  If there is code on any of our sites that is not Joomla 3 and/or PHP 5.6 compatible today, July 2016, then quite frankly that code deserves to break and whoever is maintaining said sites needs to be looking for a replacement ASAP.  Even the magazine should be compatible as the only potential B/C concern with PHP 5.6 was mitigated in the last 2.5 release.

**Comment by mbabker** [comment]
Also, this has been an outstanding issue on this tracker alone for the last 10 months.  https://github.com/joomla/joomla-websites/issues/127

**Comment by rdeutz** [comment]
@mbabker oh that site, then it is quite clear what to do next: RUN

**Comment by sam-suresh** [comment]
Any team working on showcase.joomla.org upgrade?

**Comment by wilsonge** [comment]
The SEBLOD team have - they had made good progress at JAB. Mike V was the contact there and he's currently on holiday so I guess we need to wait for him to return for progress update

**Comment by Joomv** [comment]
I will speak to seb in the morning, see where we are at





On Mon, Jul 4, 2016 at 10:32 PM +0100, "George Wilson" <notifications@github.com> wrote:












The SEBLOD team have - they had made good progress at JAB. Mike V was the contact there and he's currently on holiday so I guess we need to wait for him to return for progress update

**Comment by sam-suresh** [comment]
At this moment we have upgraded to 5.4.45 from 5.4.28.

**Comment by wilsonge** [comment]
We also lost APC caching on our sites which took down magazine and events. Please can we do better testing and communication on this than just posting after the event and leaving us to pick up the pieces ;)

**Comment by mbabker** [comment]
Closing, continue impatient waiting for `joomla.org`'s last remaining 1.5 install to be upgraded at #127
