### ISSUE TITLE
Auto Tweet Broken

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#399]
Whatever service is set up to handle auto tweets of content posted to various sites (the .org news categories, community site blogs, developer site news) isn't picking up the community site anymore.  Today's post never auto tweeted.

**Comment by Joomv** [comment]
I will look into this tomorrow, currently about to board a plane.

**Comment by Radek-Suski** [comment]
There is no way to fix it for some reason. Can't we use something own instead of some 3rd party service?
![screen shot 2016-07-25 at 15 16 28](https://cloud.githubusercontent.com/assets/1110663/17102663/0045855c-527b-11e6-8aba-23268f72e777.png)

**Comment by mbabker** [comment]
Why do we need to reinvent the wheel when we're already using a third party service and one that had been working reliably until the community site's upgrade?

Use this address: https://community.joomla.org/blogs.html?format=feed

I don't know why that works and the correct feed addresses are causing 404 HTML pages right now but it does so roll with it.

**Comment by Radek-Suski** [comment]
kk, fixed it.

> Why do we need to reinvent the wheel when we're already using a third party service and one that had been working reliably until the community site's upgrade?

Because it's limited to 5 feeds only and we already at the limit. If we would like to add something we would need to upgrade

**Comment by mbabker** [comment]
We shouldn't be anywhere near the limit except for the fact that Joomla is subdomain drunk happy and every team thinks they require a top level subdomain for their efforts which is why we have dozens of active installs and many of them constantly abandoned or outdated.

**Comment by Radek-Suski** [comment]
Maybe I screwed something. Never mind. It works 

> oomla is subdomain drunk happy and every team thinks they require a top level subdomain

Don't get me started ...
