### ISSUE TITLE
List of sites

### ISSUE THREAD

**Issue by Hutchy68** [joomla/joomla-websites#4]
Update the list of sites and add links for reporting to them.

**Comment by MAT978** [comment]
in PR #24 I added some sites.
note:
some have no interest to be added like: cdn, help...
And some have their own way for reporting issues: forum, extensions, issues...
but of course if you think there's an interest to list them... just call for MAT ;)

**Comment by brianteeman** [comment]
Other sites to be added are /3 and sponsor

**Comment by MAT978** [comment]
+:100:
that was the only reason for the "Language" tag :D

**Comment by MAT978** [comment]
Done, just waiting for the official launch and the new URL for the sponsor site.
Thanks
