### ISSUE TITLE
[j3] thai language appears badly on chrome

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-websites#40]
Chrome Version 44.0.2403.155 m 
**NO ZOOM**

Thai language is splited in 2 lines

@Sandra97 what the **** have you done?

![joomla 3](https://cloud.githubusercontent.com/assets/1972717/9390850/a8f694de-4741-11e5-8dce-2f21fb9fc8d2.png)
Please describe the problem or your issue

**Comment by Sandra97** [comment]
I don't know who has written originally the CSS of this part, but I'll make no comment...
It's now solved.
