### ISSUE TITLE
[jcomm] Facebook share images

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#400]
Its a real shame that we are hardcoding the og:image and twittercard image for the entire site when we have such great artwork for the blog posts.

For example try to share https://community.joomla.org/blogs/3062-help-to-spread-the-joomla-3-6-love.html and the share looks like 
![08wr](https://cloud.githubusercontent.com/assets/1296369/16618863/71cba87a-4383-11e6-873f-9397de380748.png)

### It would be so much nicer 
(and likely to be shared more if it looked like)
![dii3](https://cloud.githubusercontent.com/assets/1296369/16618954/daf49708-4383-11e6-8e66-c1c5e10f0ba3.png)

Apologies for the image distortion it was a quick mockup

**Comment by mbabker** [comment]
The `og:image` tag uses a default value in the base template if nothing else adds that metadata and the social sharing plugin only scrapes images from the article contents right now.  So if the intro/full image fields are being used to set these images, it's not matching the plugin's parse rules so the custom image never gets used.

https://github.com/joomla-projects/plg_content_joomlarrssb - pull requests welcome

**Comment by mbabker** [comment]
Same thing will apply also on the `twitter:image` metadata.  The same scraping logic is used to assign the values for both of those tags.

**Comment by brianteeman** [comment]
Thanks for the explanation I will see if u can do a pr

**Comment by yvesh** [comment]
@brianteeman sorry just saw that comment, hope you are not working on it right now. Made a at the repo for it..

**Comment by brianteeman** [comment]
No problem I'm watching the tennis

**Comment by Joomv** [comment]
I have a sandbox up and running of CJO if anyone wants to use it for testing, let me know.

**Comment by Joomv** [comment]
These are now being called properly.  There's a duplication issue in the tags, but as this is now being addressed and is almost fixed.  Closing.
