### ISSUE TITLE
Website Problems

### ISSUE THREAD

**Issue by KieferToolandMold** [joomla/joomla-websites#401]
To Who it may concern,

Yesterday I reported an issue to Joomla that I was unable to log in to edit my website content, now the whole website is down. Please advise what my next step is to get my website back up and running so I can reach my customer base and so I can edit my content as well. Thank you, the link for my website is www.kiefertool.com

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks

**Comment by KieferToolandMold** [comment]
Thank you for your help.

On Thu, Jul 7, 2016 at 8:54 AM, Marc-Antoine Thevenet <
notifications@github.com> wrote:

> Hi,
> This repository is ONLY for reporting issues with the *.joomla.org
> websites, not the Joomla! CMS.
>
> For user support issues, please go to:
> -http://forum.joomla.org/
> -https://docs.joomla.org/Main_Page
> -https://issues.joomla.org/
>
> Regards,
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/401#issuecomment-231068912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATZYNoXJV9f7eiKAoz9tHpT-JkenoFCVks5qTPcUgaJpZM4JHCrx>
> .
>



-- 
Thomas Kiefer Jr.
Mechanical Engineer,
Kiefer Tool & Mold
3855 W. 150th St. Cleveland Oh 44111
Ph: (216) 251-0076, Fx: (216) 251-0087, Cell: (440) 227-3186
