### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Turar91** [joomla/joomla-websites#402]
Hello, how to change your password and login to the control panel?

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

All the answers are on the doc.

Regards,
Thanks
