### ISSUE TITLE
Label consistency for issues in this repo

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#404]
Just because I like standards...
I have three different (inconsistent) ways to filter for issues related to the Joomla project that I work on (the resources directory). I have [jrescs] and the "Resources" label. I just recently discovered some old unresolved items labeled for our team under [jres].
Internally, our team usually uses JRD.  I can never remember or make sense of jrescs.  I am not sure where the cs part comes from other than randomly selecting letters out of the word resources.
Anyway, in the spirit of standards can I recommend using the github labeling system exclusively and creating the labels based on the subdomain of the various websites?
I know internally we all talk about "the jed" or whatever, but I think there could be a lot more clarity and consistency if all projects are identified using full labels. Perhaps things are moving in that direction already as I think the "Resources" label is relatively new???

**Comment by mbabker** [comment]
404 Standard Not Found ;-)

**Comment by genr8r** [comment]
OK - Realizing only contributors can add labels...
https://github.com/isaacs/github/issues/148
...I am still wondering if we can standardize the [bracketed] suggestions that are auto-populated by the reporting urls in the readme.md

**Comment by mbabker** [comment]
Personally speaking, I've got no issue changing the code if you'd like something different.  Just make sure I'm aware if it does change because the same shortcodes are used in the `joomla.org` site template to build the "Report an Issue" links in the footer.

**Comment by jeckodevelopment** [comment]
I guess that JRD is generally recognized as the standard acronym for Joomla! Resource Directory. We can adopt it as default [bracketed] code for issues. 
The label can remain "Resources".

**Comment by genr8r** [comment]
Thanks @jeckodevelopment.  I have been meaning to put together PR's for the template and the Readme.  Just haven't had a chance yet.

**Comment by MATsxm** [comment]
The Tag labels (on the right) are mainly for Stats purpose, and also a way to sort issues by topics....
but anyway and as I think we ALL have better things to work on, `jrd` (lowercased for consistency with others) is used for tag labels AND Template despite the fact I disagree that `JRD` makes any sense for 99% of Joomla! users.
Closed and re-open if needed
