### ISSUE TITLE
[jrescs] Two pages, same features

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#407]
The home page of the JRD shows the "**Joomla! Providers by Category**" section and it's very useful.
`https://resources.joomla.org/en/`
But we have also a dedicated page, under the "Providers by Category" top menu item that shows the same list of categories.
`https://resources.joomla.org/en/providers-by-category`

Why do we have the same feature/content in two different pages?

**Comment by genr8r** [comment]
Thanks you for catching this @jeckodevelopment.  When we first setup the current JRD the primary interface for identifying providers was a map with pins.  We provided the menu item for those that would prefer to filter by category.  Having changed the frontpage to the same interface so the menu item is now redundant. I removed it.

**Comment by jeckodevelopment** [comment]
Thank you @genr8r :)
