### ISSUE TITLE
[jcomm] Wrong profile image

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#408]
On `https://www.joomla.org/` the **Joomla! 3.6 is here** blog post shows as author `Chris Paschen` but it features the picture of Mike Veeckmans.
I guess that @mikeveeckmans wrote the blog post, but maybe there's an issue with the profile association.

![jorg-pic-issue](https://cloud.githubusercontent.com/assets/733133/16788230/6dae36de-48a3-11e6-8a51-812b813bec8a.PNG)

**Comment by mbabker** [comment]
To be expected.  The layout we're using for the feed module pulls avatars via Gravatar and grabs the email from the RSS feed items.  So if you do author aliases as Joomla supports, it doesn't work quite right if something parses the email address.

The fixes?

1) Create an option in Joomla that lets you alias the email address the same as the name
2) Create an account for Chris on the site and correctly associate the article with his account (even if it's just a "stub" account that he doesn't have username/password for)

**Comment by Joomv** [comment]
Apologies - missed this have contacted Chris for a Gravatar enabled email address and will set up the account for him the moment I have this 

@mikeveeckmans if you need more aliases please let me know so I can set them up for you.

**Comment by mikeveeckmans** [comment]
Sorry my bad , i inputted the article but added Chris as author. If he activated gravatar, we need to switch the user then.

**Comment by Joomv** [comment]
I've done this.

**Comment by mikeveeckmans** [comment]
Thank you!!

Sent from my iPhone

On 28 Jul 2016, at 16:23, Rowan Hoskyns Abrahall <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #408<https://github.com/joomla/joomla-websites/issues/408>.

-
