### ISSUE TITLE
[jorg] Design suggestion for Download Page

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#409]
Can we update/pimp the Download page layout a bit?
It´s not the highend solution but maybe a step forward?

I think that´s quite an important page...

I can also throw it in the Designergroup so maybe someone has time to think about it...

![joomla_download](https://cloud.githubusercontent.com/assets/828371/16802031/a5d74d74-48fe-11e6-9690-62ef75e7dd52.jpg)

**Comment by Sandra97** [comment]
We can work on it together.

**Comment by mbabker** [comment]
Unless you get approval from Arvixe, do NOT touch their advertisement banner.  I assume it is what it is for a reason...

**Comment by Sandra97** [comment]
Of course not ;) A bit of design improvement ok, we can have a look, but all elements on the page have to say there.

**Comment by mbabker** [comment]
I just saw the change in the mockup and felt it appropriate to point out that regardless of how ugly and outdated their graphic is it's their advertisement and we probably shouldn't be changing it regardless of how ugly and outdated it is.

**Comment by mbabker** [comment]
Closing.  We're close on getting the downloads site running and it's got a refreshed homepage design.
