### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by bitisGabonica** [joomla/joomla-websites#410]
Hello, I tried to sign up for your forums, but I got the following message:

"You have been banned from this board until Thu Jul 14, 2016 5:38 pm.
Please contact the Board Administrator for more information.
Reason given for ban: Found in the Stop Forum Spam database
A ban has been issued on your IP address."

I don't know why I was banned for spamming? I think I might have posted a couple of uninformed questions back months ago when I was new to Joomla! and didn't know any better; does that count as spamming though? I just have one question related to how Bootstrap is affecting my menu module, could I please be unbanned?

**Comment by jeckodevelopment** [comment]
Hello,
please submit your Unban request using this form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by jeckodevelopment** [comment]
Closing. Re-open if needed.
