### ISSUE TITLE
[jorg]Error in the page: https://www.joomla.org/announcements.htm

### ISSUE THREAD

**Issue by davidemessia** [joomla/joomla-websites#413]
Hi,
the page: "https://www.joomla.org/announcements.html"
with windows 7 on Chrome - Version 51.0.2704.106 m
shows the error message:

Notice: unserialize(): Error at offset 28633 of 28639 bytes in /home/joomla/public_html/libraries/joomla/cache/controller/view.php on line 63

**Comment by MATsxm** [comment]
@davidemessia  
Should be ok now. thanks
Closing, reopen if needed

**Comment by davidemessia** [comment]
ok thanks a lot
Davide
