### ISSUE TITLE
[josm] improvement of the a11y and UX

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#414]
Taking http://opensourcematters.org/joomla/the-joomla-community.html as an example.
IMHO, it would be great to change Styles for the links to highlight them in a way of better UX and respect a11y rules.
Thanks

@Saurabh1 are you able to help on thais one?

**Comment by jeckodevelopment** [comment]
Agree, contrast is not so "high"

**Comment by Saurabh1** [comment]
@MATsxm I agree and it is done.

**Comment by MATsxm** [comment]
WOW... not even a day to fix it? 
<sarcasm>Slow down please or some will believe it's possible</sarcasm> :wink: 
Thanks a lot @Saurabh1
