### ISSUE TITLE
[jrd]  resources.joomla.org - can't edit my entry

### ISSUE THREAD

**Issue by cpaschen** [joomla/joomla-websites#416]
I've logged in and gone to my entry, then clicked the Edit button but no form appears (just a Save/Cancel buttons)

**Comment by cpaschen** [comment]
Hmm ... also, when I clicked the report a problem link at the bottom of the resources.joomla.org page, it took me here and inserted "[jrescs]", instead of "[jrd]".

(Does the JRD team need more help than the marketing (maybe I could be 'traded' from one team to another? :-) )

**Comment by MATsxm** [comment]
About the:
"[jrescs]", instead of "[jrd]".
Known issue and will be fixed later.

**Comment by genr8r** [comment]
@MATsxm thank you for your follow up on #404 I agree that it is somewhat trivial, but the fact that half of _this_ issue is wrapped up in the confusion validates the request.  I really appreciate your taking care of it.

@cpaschen if your offer for assistance is serious we are actually looking for someone to head up resolution of tech issues on the site. I have been working aggressively to stay on top of issues reported here and through tickets on the site.  Feel free to ping me if you are looking to help.

As to the entry edit issue at the center of this post, I am not sure what you mean by the "edit" button.  We have a "My Listings" menu item in the sidebar once you are logged in.  That takes you to a list of your "listings" with a edit pencil icon on the right of each item.  We are running Zoo for the directory and this is the default display for listings on how to edit them.  Do you have more info/screenshot of where the confusion is?

**Comment by genr8r** [comment]
This has been open for about a month and a half with no clarification on the issue. I am closing it. Re-open if needed.
