### ISSUE TITLE
[jmag] Wrong picture for Author

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#418]
If you go to the "About" page of the Joomla! Community Magazine, at the end of the article you will be a nice picture of a wonderful woman, that is definitely not our Paul Orwig.
There's a wrong association between the picture and the author.

URL of evidence http://magazine.joomla.org/about

Wrong Paul:
![wrongpaul](https://cloud.githubusercontent.com/assets/733133/17122375/539a6104-52db-11e6-8956-ffc149c175e1.PNG)

And Paul should look like the following one:
![rightpaul](https://cloud.githubusercontent.com/assets/733133/17122381/60cbab1c-52db-11e6-9a5f-f60773918522.PNG)

You can see the right Paul's picture here: http://magazine.joomla.org/issues/item/698-Meet-Paul-Orwig-An-Interview-with-the-New-OSM-President

**Comment by JacquesR** [comment]
fixed, thanks

**Comment by jeckodevelopment** [comment]
thank you @JacquesR
