### ISSUE TITLE
[jdev] JoomlaCode Archive Cleanup

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#42]
When JoomlaCode's data was finally exported, it picked up some of the spam activity after the migration to our GitHub based system.  Need some help in cleaning up the database tables for this.

com_code doesn't have an admin UI to manage this so someone will have to go through the database and delete the rows.  For bonus points, the last modified date and user should be adjusted too (this generally should map to the last response in the issue_responses table).

Also, the descriptions and titles used for the trackers can be cleaned up some; they don't need to map 1-to-1 for what they were on JoomlaCode.  There is a minimal admin UI for this part.

**Comment by brianteeman** [comment]
As said before "Happy to help to on this"

On 22 August 2015 at 22:28, Michael Babker <notifications@github.com> wrote:

> When JoomlaCode's data was finally exported, it picked up some of the spam
> activity after the migration to our GitHub based system. Need some help in
> cleaning up the database tables for this.
>
> com_code doesn't have an admin UI to manage this so someone will have to
> go through the database and delete the rows. For bonus points, the last
> modified date and user should be adjusted too (this generally should map to
> the last response in the issue_responses table).
>
> Also, the descriptions and titles used for the trackers can be cleaned up
> some; they don't need to map 1-to-1 for what they were on JoomlaCode. There
> is a minimal admin UI for this part.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/42>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
I remember, just brain dumping here so I don't forget to do something with it (or let it go unnoticed by others).

**Comment by MAT978** [comment]
If:
I have the skill to,
You want,
You wait at least next WE,
I'm still alive next WE,

I can help
