### ISSUE TITLE
[jcomm] Missing the post from the leadership blog

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#420]
If you go to the Joomla! Community Blogs page, the latest item from the Joomla! Leadership blog is missing in the main blog page: https://community.joomla.org/blogs.html 
The leading entry is "Spanish (Colombia) Language Pack Added to Joomla! 3.6" (July, 13), the latest Leadership Blog post has been published on July, 25, so it should be displayed as first item.

Maybe it's necessary to fix the category order or include the Leadership Blog in the main blog view.

**Comment by Joomv** [comment]
Actually not quite right.  The issue was that the leadership post was not set as featured.  The front page shows featured items.  I have featured the leadership blog now to give it more prominence.

**Comment by jeckodevelopment** [comment]
Thank you Rowan, i didn't know that it shows only featured items.
