### ISSUE TITLE
[jcomm] Missing menu and twitter module on GSOC blog

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#421]
If you go to the Blogs (and both Community and Leadership) the right sidebar looks like the following image:
![blogsrightmenu](https://cloud.githubusercontent.com/assets/733133/17122574/f7f45808-52dc-11e6-9d6d-e5268be19bc5.PNG)
and it includes: Search box, Quick Links menu, Twitter module, Login module.

If you go to the GSOC - 2016 page ( https://community.joomla.org/gsoc-2016.html ) from Quick Links, you will see a right column like the following:

![gsocmenu](https://cloud.githubusercontent.com/assets/733133/17122606/333d3bb4-52dd-11e6-9326-415287eeab9b.PNG)

It includes only the Search Box and the Login module.
It would be better to have a consistent interface and include the missing modules.

Furthermore, the "GSOC - 2016" menu item looks like a top level menu item, in fact it's not under the Blog (that's why modules are not shown).

**Comment by Joomv** [comment]
GSOC is an alias on the main menu, it won't be current forever unlike Leadership/Community Blogs.  
It was set up so that when it goes to archive, the links will all still work and there will be minimal upheaval.
I've worked around it however to give the same effect as you asked for above.

**Comment by jeckodevelopment** [comment]
Thank you!
