### ISSUE TITLE
Contributor images [jvols] 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#423]
https://volunteers.joomla.org/reports

The width and height relationship seems to have been lost on resizing which is making everyone look rather thin!

**Comment by sanderpotjer** [comment]
@Hils which browser are you using?

**Comment by Hils** [comment]
Just checked IE FF & Chrome latest and the problem seems to arise on FF when the browser window is even slightly less than full screen. 
<img width="159" alt="fullscreen" src="https://cloud.githubusercontent.com/assets/736887/17132498/ea34024e-5319-11e6-8573-d66551c7f035.png">
<img width="134" alt="narrow" src="https://cloud.githubusercontent.com/assets/736887/17132501/f36f959e-5319-11e6-895e-b7f586d87ca5.png">

Thanks for checking Sander

**Comment by jeckodevelopment** [comment]
It can be linked also to #314

**Comment by Hils** [comment]
Thank you Luca @jeckodevelopment & Sander @sanderpotjer . I was going to close this in favour of #314 but it is different so thought I had better leave it as is. Please feel free to close if you decide it should be. Thanks.

**Comment by jeckodevelopment** [comment]
Please leave this open :)

**Comment by Hils** [comment]
:sun_with_face:

**Comment by sanderpotjer** [comment]
@Hils this is fixed now, thanks for reporting!
