### ISSUE TITLE
[jcertif] Browser in Browser in Browser

### ISSUE THREAD

**Issue by RichardR2H** [joomla/joomla-websites#425]
Prior to the start of the exam you can click "I agree to the Terms.....etc." so the terms will be opened. When you click on the nav-button "Start Exam" you see the introduction text again are able to click on the Terms-link again. In this way you can create Browser in Browser in Browser.

![2016-07-26 12 50 56](https://cloud.githubusercontent.com/assets/7460406/17137389/392db432-533b-11e6-8072-63f1bfb671c4.jpg)

**Comment by jeckodevelopment** [comment]
Did you experienced this issue in Safe Exam Browser?
Can you give further details about the workstation? software versions, etc. ?

**Comment by sam-suresh** [comment]
This is fixed by removing hyperlink in the exam and added in profile update page to prevent such behavior. It is because the key encrypted not to open new tab. I have tested it and it is solved.

**Comment by jeckodevelopment** [comment]
Thank you @sam-suresh
