### ISSUE TITLE
[jvols] I had an old Volunteers account  and created a new one as requested by the JED group

### ISSUE THREAD

**Issue by webgobe** [joomla/joomla-websites#427]
The problem is, when I log in with my new username (denes.szekely, email denes.szekely@extensions.joomla.org) I see in My Profile link the old one (webgobe, with email webgobe@gmail.com, and obviously can't edit it. I have nothing against merging the two profiles, or having a way to edit the old one. But currently can't do anything.

**Comment by sanderpotjer** [comment]
@webgobe thanks for reporting the issue. Not sure why the JED team requested to create a new profile, but I've merged both profiles and you should be able to edit it with your new username. Please let me know if not. 

This problem will also be solved in the new version of the Volunteer Portal that will be available soon.
