### ISSUE TITLE
[jorg] h2 tags on the repo

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#43]
http://repository.joomla.org/about-joomla/the-project.html The article title needs to be an h1
<img width="1110" alt="screen shot 2015-08-23 at 12 07 41 pm" src="https://cloud.githubusercontent.com/assets/1581195/9429257/b0051e80-498f-11e5-9ec2-25187577860d.png">

**Comment by jessicadunbar** [comment]
Thank you.

**Comment by mbabker** [comment]
It's not fully done, but a lot of it is handled in the menu item configs.

Every single article menu item is changed to show the page heading and hide the article title.  This gives all of those pages `<h1>` tags and hides the `<h2>` tag where the article title was displayed.  Category blog pages are going to be trickier to deal with.  Joomla's core behavior is if you turn on the page heading option, it basically uses the menu item name unless you specify custom text.  Those pages would show the menu item/category item name as the `<h1>` tag with the article title still in the `<h2>` (basically everything under `/announcements`.
