### ISSUE TITLE
[jorg] https://www.joomla.org/about-joomla/honor-roll.html

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#430]
The URL to Tarr Consulting under Andrea Tarr redirects to http://dohod-3000.blogspot.nl/ and qiwi.help  ...
Maybe disable the link , as tarrconsulting.com itself is forwarding to that site...

**Comment by Sandra97** [comment]
URL removed. 
Closing this issue. Re-open if needed

**Comment by mikeveeckmans** [comment]
Thank you @Sandra97 !
