### ISSUE TITLE
[jconf] "No item found" message

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#431]
In this page: http://conference.joomla.org/venue
After the room's picture and before the Main Sponsor, you can see the message "_No item found_", left aligned.

![jconf-noitemfound](https://cloud.githubusercontent.com/assets/733133/17311464/d2867ff0-584b-11e6-8271-7ed0bef47b27.PNG)

**Comment by mbabker** [comment]
Looks fixed.
