### ISSUE TITLE
[jconf] Responsivity issues with Sponsor logos

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#432]
All over the conference.joomla.org website
If you look at the website using a smartphone or just resizing your browser, some of the Sponsor logos would be stretched.
Some logos are displayed correctly, adapting their size according to the page size.
Some logos are displayed wrongly: Ark, TechJoomla, JoomlaShine, Stackideas, Joomlart.

![jconf](https://cloud.githubusercontent.com/assets/733133/17311637/15dfd246-584d-11e6-9fc4-09fc6689d838.PNG)

Looking at the code, images that are displayed correctly don't have fixed size:
![jconf1](https://cloud.githubusercontent.com/assets/733133/17311661/396d9464-584d-11e6-82f7-cda1aba696b9.PNG)
The others have a fixed size:
![jconf2](https://cloud.githubusercontent.com/assets/733133/17311676/5ec84cf4-584d-11e6-9866-5b6986811c8f.PNG)

**Comment by mbabker** [comment]
Looks like it was addressed with their upgrade.
