### ISSUE TITLE
[jdocs] - dead link, decision to take.

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#433]
https://docs.joomla.org/LDAP

link `getting started from scratch with LDAP` is outdated as should be: http://sammoffatt.com.au/jauthtools/LDAP_Tools/OpenLDAP_HowTo (but 1.5)

On the toDo, waiting for proposals on the Glip JDoc room.
* [ ] Someone to build a tuto for 3.x taht could be linked
* [ ] link to "under construction page
* [ ] Delete the dead link

**Comment by jeckodevelopment** [comment]
Is this the article?  https://community.joomla.org/46-gsoc-2009/lalitanand-dandge/908-joomla-ldap-authentications-plugin-window-2003-server-active-directory-configuration.html

**Comment by mikeveeckmans** [comment]
@jeckodevelopment nice catch ;-)

**Comment by MATsxm** [comment]
Thanks @jeckodevelopment 
Added it and also the "NEEDS UPDATING" Warning.
This is enough at this point as it is now the regular updating process - Closed, reopen if needed

**Comment by jeckodevelopment** [comment]
you're welcome ;)
