### ISSUE TITLE
[josm] Missing "Leadership Blog" feed

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#436]
If you go to: `http://opensourcematters.org/news.html`
The "Leadership Blog" module shows the following message:
>  Feed not found.

![osmdeadfeed](https://cloud.githubusercontent.com/assets/733133/17386757/e8e4d80c-59ed-11e6-898a-e2408b192d77.PNG)

**Comment by Saurabh1** [comment]
Can someone provide me the correct Feed link please ? 
The one I have and inserted is : http://feeds.joomla.org/JoomlaCommunityCoreTeamBlog 
I don't see any other option that can make this issue.

**Comment by jeckodevelopment** [comment]
Is this? https://community.joomla.org/blogs/leadership.feed

**Comment by Saurabh1** [comment]
I just tried this link , It's not working either.

**Comment by jeckodevelopment** [comment]
@Joomv what is the correct feed URL ?

**Comment by mbabker** [comment]
https://community.joomla.org/blogs/leadership.html?format=feed

**Comment by mbabker** [comment]
Don't ask.  It's just quirky with the "right" URL.

**Comment by jeckodevelopment** [comment]
Thank you Michael

**Comment by Saurabh1** [comment]
Done! 
Thanks @mbabker :)
