### ISSUE TITLE
[jorg] Unwanted intro text in announcements

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#437]
On www.joomla.org 
Each announcement intro text contains: 

> facebook twitter google+ linkedin pinterest

![jorg-ann](https://cloud.githubusercontent.com/assets/733133/17387494/ac7e7be6-59f4-11e6-93ec-4b0046380cb0.PNG)

**Comment by mbabker** [comment]
I'll fix the plugin later.  It's because of [this bugfix](https://github.com/joomla/joomla-cms/commit/bb28dc99e27ac2cf034a593b242df418b1dccc9f) in 3.6.1.

**Comment by jeckodevelopment** [comment]
thank you Michael

**Comment by mbabker** [comment]
Fixed.  Updated plugin is available via https://github.com/joomla-projects/plg_content_joomlarrssb/releases/tag/2.0.0 and will be updatable via extension manager going forward.

**Comment by MATsxm** [comment]
Great job! - thanks!
