### ISSUE TITLE
[jorg] Missing social media icons (I guess)

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#438]
Just take a look at the beginning of each news.
 
![screen shot 2016-08-04 at 09 14 12](https://cloud.githubusercontent.com/assets/1110663/17393481/20df00c6-5a24-11e6-9b8b-f1457a86ad6e.png)

**Comment by JacquesR** [comment]
Social share icons text should not be showing in the Announcement feed (intro) or it will cause issues elsewhere too.

Suggest moving them down to below the content as it us done on the Community site.
(no need for share icons for each item in a category view either)

**Comment by jeckodevelopment** [comment]
already reported as #437

**Comment by Radek-Suski** [comment]
You're too fast

**Comment by jeckodevelopment** [comment]
It was a long long night @Radek-Suski  :)
