### ISSUE TITLE
[jorg] pages that need fixes

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#44]
Here are pages that need to be fixed
http://repository.joomla.org/core-features.html
<img width="1187" alt="screen shot 2015-08-23 at 12 10 48 pm" src="https://cloud.githubusercontent.com/assets/1581195/9429266/07f4d900-4990-11e5-9b21-4dbfc8a917a0.png">

**Comment by jessicadunbar** [comment]
http://repository.joomla.org/about-joomla.html

**Comment by mikeveeckmans** [comment]
Fixed : Core-features & about-joomla

**Comment by MAT978** [comment]
Closed as done.
IMHO, it's not the best place to talk about repo. issues we are working on. there're [bed]rooms for that ;)
