### ISSUE TITLE
[jcomm] Pinterest share URL broken

### ISSUE THREAD

**Issue by JacquesR** [joomla/joomla-websites#440]
Pinterest share URL broken on Community site. 
That share option does not seem to be used much?

Related minor issue: the Email share option has +'s in-between the text. Thunderbird retains it. Does any email client need that kind of format?

**Comment by mbabker** [comment]
The email thing was discussed at https://github.com/joomla-projects/plg_content_joomlarrssb/issues/8 a bit ago with no action.  As for Pinterest, first I've heard; I'll look at the plugin later.

**Comment by Joomv** [comment]
Pinterest works fine for me.  
@JacquesR  could you give us steps to replicate please?

**Comment by JacquesR** [comment]
My description was not accurate enough. It's the first part of the media param that's broken:
media=https%3A%2F%2Fcommunity.**joomla.orgimages**

The same issue is not present on the joomla.org implementation of the plugin.

**Comment by Joomv** [comment]
I've installed the version of the plugin that's on github.  I have successfully shared a blog post to my ghost town of a pinterest account with the correct media and link being displayed.

Could you please check again @JacquesR ?  Thanks

**Comment by Joomv** [comment]
As no response.  Closing.

**Comment by JacquesR** [comment]
@Joomv  Sorry I was sick and missed your previous reply. If the sharing is working OK, then Pinterest was perhaps using the _og:image_ instead of the broken image link in the Pinterest share link.
I do see that the media link is now showing correct as:  media=https%3A%2F%2Fcommunity.**joomla.org%2Fimages**.....  previously the %2F was missing (only on the community site) as posted above.  
So issue seems resolved.
