### ISSUE TITLE
[jtrain] Use of the Joomla! word

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#443]
The bang for Joomla! is missing nearly everywhere in the content. Please add it where it is compulsory. It's a legal issue.

**Comment by Hils** [comment]
please note that it is an 'exclamation mark' not an 'exclamation point'. If we are using en-GB the h1 (?) should also use the exclamation mark and not 'bang' which is en-US

**Comment by Hils** [comment]
Is this whole paragraph 'correct usage' please?

"How can I get involved with Joomla?
Anyone can contribute on any level, even newcomers can contribute to Joomla. You can get started by answering questions on the Joomla! Forums™ and joining the Joomla! Bug Squad™, Joomla! User Group™ or other Joomla! working groups. You can also write for our official magazine, the Joomla! Community Magazine™, or organize a Joomla! event.

**Comment by MATsxm** [comment]
@Hils 
Yes!!!!!!!!!!!!

**Comment by Hils** [comment]
Oh poodles! So a heading doesn't need an exclamation mark? (I know if it is the second or more time on a page we don't have to use TM or R.

**Comment by MATsxm** [comment]
heading is not a paragraph

**Comment by Hils** [comment]
oh dear - I wish I was a newcomer as I don't know why this isn't exclaimed ;)

"even newcomers can contribute to Joomla."

**Comment by mikeveeckmans** [comment]
Thank you @Sandra97 & @MATsxm 
Forwarded to @stevejburge

**Comment by stevejburge** [comment]
Sorry, guys. I'm not following. What specifically do we need to change?

**Comment by mikeveeckmans** [comment]
![joomlabang](https://cloud.githubusercontent.com/assets/4589318/17440468/032fc1be-5b2d-11e6-8c67-a24737f5dca7.png)
Add the '!' behind Joomla ;-)

**Comment by stevejburge** [comment]
Oh wow. That won't be easy.

I thought Joomla.org policy was just to put the ! on the first use on the page?

**Comment by MATsxm** [comment]
@stevejburge 
this would be to easy :stuck_out_tongue_closed_eyes: 
Please see: https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name
Also, if you want, I will check this part once I will have access to it...
And do NOT hesitate to ask if you need.

_Side note: I ***** hate this ***** "!" but when it's a legal issue, no exception should be allowed contrary to what some claim_

**Comment by Radek-Suski** [comment]
> Side note: I ***** hate this ***** "!" 

I love it. It's like Yahoo! or Jeb! :P

**Comment by MATsxm** [comment]
even more @Radek-Suski when you are talking about a version or series, it shoud me considered as a TM as it refers to the "product". `Joomla! 3` is 'de facto' a TM.

Yahoo! hates his "!" as they will remove it :stuck_out_tongue_closed_eyes: 
no + points and thousands of -

**Comment by stevejburge** [comment]
Yahoo! or Jeb! .... we're in good company :)

OK, I'll see what I can do. We may have to get a patient intern or a smart SQL query.

**Comment by Joomv** [comment]
Worst comes to worst, I can just run a re-replacer on all of it.

**Comment by Sandra97** [comment]
Can be easier. 
You'll have then to remove it where it's not supposed to be added. 
After a quick check, I think there's only one string to edit in the classes after running the re-placer: https://community.joomla.org/joomla-training.html?ostm_view=course&ostm_pathway_id=48&ostm_course_id=198
"What is Joomla?" should stay like it is and not "What is Joomla!?"

**Comment by stevejburge** [comment]
I'd appreciate Re-Replacer.

I had a similar discussion before when writing two official books (Joomla Explained and Joomla 3 Explained).

The legal advice we got then was only the first mention in each chapter.

**Comment by MATsxm** [comment]
What are you talking about?
the Registered trademark (indicia®) **OR** the '!'
_about Trademark:_ **Right**
_About the '!':_ **Wrong** as the name REGISTERED IS with the '!' not without.
Agree or disagree, this is a legal point.
I guess, like many, you confuse the two.

everything is explained here:
https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name
and your "The legal advice" can/must **NOT** have said a different way.

**Comment by stevejburge** [comment]
Ok, I'm not getting into an argument about what we were told.

Tell me what you want me to do and I'll do it.

**Comment by MATsxm** [comment]
no argument is admissible when it comes to copyright or a long time that I would have removed this "!" absurdity and I have never seen Apple, Microsoft, Nike,........ Yahoo! or what ever use their BRAND mark identity (we are not talking about VISUAL identity) in an improper way.

> Tell me what you want me to do and I'll do it.

Nothing more, nothing less than what's written here: https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name

If you want, send me the taxt, I will proofread it ONLY on this topic as my tarzan franglish won't allow me to do more :wink:

**Comment by stevejburge** [comment]
Looks like that page is only 1 year old. Let's just say that advice has changed.

I'll make the updates as best I can, but if anyone wants to use ReReplacer, that would be welcome.

**Comment by MATsxm** [comment]
Oh Boy....
Nope... nothing as changed for decades about Trademarks...
I wish it was the case.

**Comment by mikeveeckmans** [comment]
@stevejburge @Joomv : how will we solve this ? replacer or not? Steve, taken in general the courses on ostraining should have the exclamation mark as well...

**Comment by MATsxm** [comment]
Why the hell do we need a script to add a ! where it should be???
Are you all serious?

**Comment by mikeveeckmans** [comment]
Read last line of my previous answer ;)

Sent from my iPhone

On 10 Aug 2016, at 13:33, Marc-Antoine Thevenet <notifications@github.com<mailto:notifications@github.com>> wrote:


Why the hell do we need a script to add a ! where it should be???
Are you all serious?

-

**Comment by stevejburge** [comment]
Ugh, I'm honestly so tired after 10+ years of discussions just like this one.

I'll ask our team to start adding the ! where appropriate.

**Comment by mikeveeckmans** [comment]
OStraining did changes on the courses and descriptions. Should be ok now.
