### ISSUE TITLE
[jtrain] Usability Improvement

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#445]
On the homepage, the link for the title and the link for the "start this class" are different. 
I'm afraid that people may not notice this and will just click on the button and won't reach the content of the page linked from the title (this is just my opinion, I may be wrong)

**Comment by mikeveeckmans** [comment]
Ok, i see what you mean @Sandra97 , thank you.
@stevejburge Is there a possibility to change that? It's scripted in the component of OStraining.
![jtraininglink](https://cloud.githubusercontent.com/assets/4589318/17429817/18efeda8-5af1-11e6-806e-cab4310777ed.png)

**Comment by stevejburge** [comment]
Hey guys. That was a change based on our feedback from our users.

The title goes to the overbiew of the whole class
The "Start this class" button does just that ... let's people dive right in

**Comment by mikeveeckmans** [comment]
@stevejburge , Ok, thank you for your feedback.

**Comment by MATsxm** [comment]
disagree

**Comment by Sandra97** [comment]
disagree too.

**Comment by stevejburge** [comment]
That's what we thought too, and that's how we had it.

But real-world usage taught us differently.

**Comment by MATsxm** [comment]
I know I'm living outside the Matrix :stuck_out_tongue_closed_eyes:
