### ISSUE TITLE
[jtrain] Homepage Improvement Suggestion

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#446]
Just my opinion... When visiting the homepage, I think it should be nice to have a short intro text to present the goal of Joomla! Training. It's a bit harsh to just put the videos and not to "talk" to the users.

**Comment by mikeveeckmans** [comment]
Agreed.
@stevejburge : can we add such text to the component or do we have to do it with a custom module ?

**Comment by stevejburge** [comment]
Sure, we could add a module position. Where do you want the text to be?

**Comment by mikeveeckmans** [comment]
Above the first banner ?

**Comment by stevejburge** [comment]
Ok, so over the top of the OSTraining banner?
![screen shot 2016-08-05 at 10 57 42 am](https://cloud.githubusercontent.com/assets/3868028/17440650/8305085e-5afb-11e6-8fb8-8e22d512227d.png)

Does the Community template itself have a module position there?

**Comment by mikeveeckmans** [comment]
@Joomv do we have a position there ?

**Comment by mbabker** [comment]
Should just be able to use the banner position.

**Comment by Sandra97** [comment]
With org templat,e we are supposed to have the banner position

**Comment by mbabker** [comment]
There's also position-3 which is before the component output and message container in the same Bootstrap span as the main component section.

**Comment by mikeveeckmans** [comment]
@mbabker & @Sandra97  : Thank you for the feedback. 
@stevejburge : no need to add it to the component then.

**Comment by mikeveeckmans** [comment]
Module placed, copywriting still to do

**Comment by Joomv** [comment]
Ok if we can kill the revive ad within the component (this will be easier and better to place within module positions on the site) and also change the heading from Joomla.org Training to Available Classes.  I think we'll have nailed it.

**Comment by Joomv** [comment]
![joomla training 2](https://cloud.githubusercontent.com/assets/5618499/17447509/ac821514-5b46-11e6-9864-a5a4896469b3.png)

**Comment by mikeveeckmans** [comment]
@stevejburge could you have a look at the suggestion @Joomv made? Thank you!

**Comment by stevejburge** [comment]
Sure thing. We have a heavy cache on the extension, but when it resets, that should be updated.

**Comment by mikeveeckmans** [comment]
hi @stevejburge , how heavy is that cache ? The ads are still showing.

**Comment by stevejburge** [comment]
@mikeveeckmans Sorry, I was referring to "Available classes" text.

I do still see a second ad box ... for Acquia

![screen shot 2016-08-10 at 7 13 05 am](https://cloud.githubusercontent.com/assets/3868028/17551765/f66760ea-5ec9-11e6-81d0-b5fa19671ca8.png)

**Comment by mikeveeckmans** [comment]
@stevejburge yes, me too ;-)
But i believe this ad box is pushed by your code... could you delete that code ? thank you.

**Comment by stevejburge** [comment]
Sure, we can do that today

**Comment by jeckodevelopment** [comment]
It's strange to see Drupal banners on the Joomla! tranining portal. :P

**Comment by mikeveeckmans** [comment]
double banner has been removed by @stevejburge , thank you.

**Comment by mikeveeckmans** [comment]
@Joomv could you integrate side banner?

**Comment by Sandra97** [comment]
The intro text has been added, the ad box has been removed and a side banner added (currently JWC).
So I'm closing this issue.
Re-open if needed.
