### ISSUE TITLE
[jorg] Download button, 3.6.1 instead of 3.6.2

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#447]
URL : https://www.joomla.org/download.html

Download Button for Full Packages refers to 3.6.1 instead of 3.6.2

![361inst362](https://cloud.githubusercontent.com/assets/733133/17422473/98ea90e2-5ab2-11e6-917f-2759cc24fdd6.PNG)

**Comment by MATsxm** [comment]
Sandra is on it

**Comment by MATsxm** [comment]
Sandra is on it but @mbabker do not trust in her then he fixed it :stuck_out_tongue_winking_eye:

**Comment by jeckodevelopment** [comment]
Thank you all! :D
