### ISSUE TITLE
JED - 503 error and database updates not executed after J3.6, 3.6.1 and 3.6.2 upgrades

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#448]
Hi,

I have successfully upgraded JED to the latest Joomla versions and the site is running fine.

However, SQL scripts associated with version database updates are not executed. 

It could be related with a server time restriction to execute SQL scripts. It seems that UTF8 conversion takes a long time and the job is killed or MySQL restarted.

## Extensions: Database

Warning

Warning: Database is not up to date!

3 Database Problems Found.

* Table 'wqyh6_menu' does not have index 'idx_client_id_parent_id_alias_language'. (From file 2.5.0-2011-12-24.sql.)
* Table 'wqyh6_redirect_links' does not have index 'idx_old_url'. (From file 3.5.0-2016-03-01.sql.)
* The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

If I try to **Fix**, the issue is found again, the job is killed or MySQL restarted.

What is the best way to solve this case?

**Comment by mbabker** [comment]
Run https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281 via command line.

**Comment by jeckodevelopment** [comment]
@anibalsanchez have a look!

**Comment by anibalsanchez** [comment]
Great, on Monday I will test it.

**Comment by anibalsanchez** [comment]
Hi,

@matthewbaylor adjusted the connection settings and the regular database fix run Ok.

Solved!
