### ISSUE TITLE
Please remove following expired sponsors from https://www.joomla.org/current-sponsors.html

### ISSUE THREAD

**Issue by Martijn-Boomsma** [joomla/joomla-websites#449]
@mikeveeckmans:  Please remove the following expired sponsors from https://www.joomla.org/current-sponsors.html

BESLIST.NL - Silver Global Sponsor

Community Sponsors:
Digital Exits
FUTURE TV

**Comment by mikeveeckmans** [comment]
Done

**Comment by Martijn-Boomsma** [comment]
@mikeveeckmans: These also please https://www.joomla.org/current-sponsors.html

Community Sponsors:
Digital Exits
FUTURE TV

Thanks!

**Comment by mikeveeckmans** [comment]
oops sorry thought it was about silver only, will do it tomorrow

**Comment by Martijn-Boomsma** [comment]
No worries, thanks.

**Comment by Sandra97** [comment]
I just removed Digital Exits and FUTURE TV.
Closing this issue. Re-open if needed

**Comment by Martijn-Boomsma** [comment]
@Sandra97 Thank you!

**Comment by mikeveeckmans** [comment]
@Sandra97 thanks ;-)
