### ISSUE TITLE
[jorg] Update Conditional Use Logos for Updated Brand Manual

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#45]
Graphics on http://www.joomla.org/about-joomla/the-project/conditional-use-logos.html need to be updated to follow the revised brand manual.  One of the graphics was changed in the CMS repository already (https://github.com/joomla/joomla-cms/blob/staging/images/powered_by.png).

**Comment by MAT978** [comment]
last elements and texts can be found here:
https://docs.joomla.org/Joomla:Brand_Identity_Elements

**Comment by Sandra97** [comment]
Don't you think that it would be easier to redirect this page to the JDocs or do an embedded? The good thing is also that JDocs series is translated.
 And if some text needs to be kept and are not currently present in the JDocs series, I can add it, no problem.

**Comment by mbabker** [comment]
As long as it gets updated I'm not particularly concerned what site(s) it gets displayed on.

**Comment by Sandra97** [comment]
I'll update the page.

**Comment by Sandra97** [comment]
This page is the responsability of the Trademark team and has to be updated by them, following the new process defined or to define.

**Comment by MAT978** [comment]
Message sent & received to Marco Richer as Member of the "Trademark Team" and as it's their responsibility.

**Comment by MAT978** [comment]
Still waiting then marked 'Phase 2'

**Comment by MAT978** [comment]
Still waiting

**Comment by SpiritJC** [comment]
I also think that a link to the docs is a good solution. 
As Sandra said, at jDocs we've a translation of it.

**Comment by Sandra97** [comment]
I redirected the menu link to the JDocs and disabled the article on j.org
Issue closed. Reopen if needed
