### ISSUE TITLE
[jmag] something gone wrong? 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#450]
It says its the July 2016 edition but all the content is from 2010

![2lru](https://cloud.githubusercontent.com/assets/1296369/17452931/53047fec-5b6c-11e6-8074-3c9540a33f06.png)

**Comment by jeckodevelopment** [comment]
Home page is empty for me
![jmag](https://cloud.githubusercontent.com/assets/733133/17453067/6f2d20ca-5b76-11e6-9fe9-717d8a727b49.PNG)

**Comment by brianteeman** [comment]
i see its been set offline now. obviously someone is working on it

**Comment by jeckodevelopment** [comment]
In fact :)
