### ISSUE TITLE
[jorg] Add community sponsor

### ISSUE THREAD

**Issue by mdemop** [joomla/joomla-websites#451]
Please add the sponsor below as a community sponsor on https://www.joomla.org/current-sponsors.html (should be a no follow link)

Sponsor is paid and contract signed. 

Business name: Dealslands

Business website URL: http://www.dealslands.co.uk

**Comment by MATsxm** [comment]
@Martijn-Boomsma ?

**Comment by jeckodevelopment** [comment]
@MATsxm , @mdemop should be Mike, the new OSM Treasurer... I guess he knows :D

**Comment by Martijn-Boomsma** [comment]
@MATsxm @mikeveeckmans Yes, please add. @mdemop is busy bee: https://volunteers.joomla.org/joomlers/mike-demo-demopoulos

And he meant to say that Sponsor HAS paid :)

**Comment by mikeveeckmans** [comment]
added

**Comment by Martijn-Boomsma** [comment]
Thanks!

**Comment by mdemop** [comment]
Due to miscomunsion with the sponsor we need to remove the no follow tag please.

**Comment by Sandra97** [comment]
@mdemop, I removed no follow tag for Dealslands' link
