### ISSUE TITLE
[joomla.org] Dhurringle PS website 

### ISSUE THREAD

**Issue by AHolleran** [joomla/joomla-websites#452]
My school website www.dhurringileps.vic.edu.au is not accessible using the passwords originally set up. I am the new school principal and I cannot log into the site to update it. I have tried to reset the password to no avail. Can anyone help me before I close it down and create a new one?

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

All the answers are on the doc.

Regards,
Thanks

**Comment by MATsxm** [comment]
Also check
https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F
