### ISSUE TITLE
[jspons] Add Bronze Sponsorship Tier

### ISSUE THREAD

**Issue by mdemop** [joomla/joomla-websites#453]
Add Bronze Sponsorship Tier to: https://www.joomla.org/sponsor.html#packages

Content is same as Silver, just without Press Release for $5k per year. Please also make it a option on the form.

@mikeveeckmans ?

**Comment by mikeveeckmans** [comment]
@mdemop i need some specific CSS created, requested to @Sandra97 .
Changed the order already to Silver - Gold - Platinum

**Comment by Sandra97** [comment]
No problem. I'll take a look in a moment.

**Comment by mikeveeckmans** [comment]
Thank you !!

**Comment by Sandra97** [comment]
CSS created and Bronze sponsor added following your instructions.

**Comment by mikeveeckmans** [comment]
Thank you for your help @Sandra97 !! 

Form done also.
