### ISSUE TITLE
[josm] Possible typo in menu

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#455]
On opensourcematters.org

Top menu: `About > Board Directors`
Left menu: `Board Directors`
Page title: `Board Directors`

The proper name should be "`Board of Directors`"

Otherwise, if we are referring to the members of the board, we could use simply "`Directors`".

@brianteeman am I right? Can you please double check?

**Comment by Saurabh1** [comment]
@jeckodevelopment  It was there since the previous site, I am not sure if we have to change it. But it sounds right to me that it should have been changed to "Board of Directors". I will wait for another opinion before making any change.

**Comment by brianteeman** [comment]
The full term is "Board of Directors"
Acceptable shorter terms are "The Board" and "Directors"

**Comment by Saurabh1** [comment]
Done!

**Comment by jeckodevelopment** [comment]
thank you
