### ISSUE TITLE
[josm] Out of date content / Duplicate page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#456]
On opensourcematters.org there's a page called "Sponsorship" that is practically useless since we have a Sponsorship page on Joomla.org and the one on OSM has out of date content.

![josm-spons](https://cloud.githubusercontent.com/assets/733133/17609722/f124955c-6037-11e6-8724-9c7c88e80f17.PNG)

Furthermore, the page on OSM doesn't have any Call-to-Action and/or links, so it's almost useless.

We can redirect thae menu item `About > Sponsorship` to `https://www.joomla.org/sponsor.html` that is the brand-new page about Sponsorhips and it include also CTAs and all the available sponsor packages.

**Comment by Saurabh1** [comment]
I am aware about it and we are building a page. Mike Demo from financial team has asked to put a page as we have a request by Sponsor who wants to sponsor OSM and needs some text on the site. Further more you can talk to Mike Demo about it.

**Comment by Martijn-Boomsma** [comment]
Ha! Good and quick find Luca. It's work in progress and so far only there for a week or so. It should or could have the same CTA as on Joomla.org. It was only created because a sponsor is interested in being on that webiste with a link too.

**Comment by jeckodevelopment** [comment]
ok :) so you can close this issue!
