### ISSUE TITLE
whitehat stored xss on web site joomla by @M0h4mm33d

### ISSUE THREAD

**Issue by SIMO07** [joomla/joomla-websites#458]
Xss stored

http://www.noelshack.com/2016-32-1471044225-13884521-1623633604632921-229245530-n.jpg
mail for rapport thanks

**Comment by mbabker** [comment]
Fixed.

**Comment by SIMO07** [comment]
if you want say to me thanks  in https://hackerone.com/m0hamm33d :) 
thanks !

**Comment by SIMO07** [comment]
ewa layn3al rabkom

**Comment by SIMO07** [comment]
thanks joomla
