### ISSUE TITLE
[jvols] Error 403 instead of 404

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#459]
On `volunteers.joomla.org`
if I try to look for a non-existing profile (maybe removed) I get a 403 error (Access forbidden) instead of a 404 (Not found).

In the image: `https://volunteers.joomla.org/joomlers/fake-link`

![jvols-403](https://cloud.githubusercontent.com/assets/733133/17648285/3ab9b0ca-620f-11e6-8b11-cff94f21392c.PNG)

**Comment by mbabker** [comment]
The new version's a little more... Interesting...

**Comment by sanderpotjer** [comment]
Showing 404 now, but something weird with the language strings on the error page

**Comment by mbabker** [comment]
`JDocumentError` doesn't load the template's language file.  I'll push a fix for that to the template repo.  Maybe someone should do one for core Joomla.

**Comment by jeckodevelopment** [comment]
Can we close it?

**Comment by sanderpotjer** [comment]
Yes, has been fixed.
