### ISSUE TITLE
[jrd] Need some space before the button

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#461]
On `https://resources.joomla.org/en/`

If you try to search for providers (just set up a radius and click on search in the home page search engine)
there's no space between results and the button "Click here for more results"

![jrdspace](https://cloud.githubusercontent.com/assets/733133/17674724/0d27188c-6327-11e6-8363-b78a33c605a8.PNG)

**Comment by genr8r** [comment]
15px of UI deliciousness served with a smile :)
I wish all of them were this easy.

**Comment by jeckodevelopment** [comment]
Thank you @genr8r
