### ISSUE TITLE
[jorg] Joomla! RSS News Feeds Page needs to be review

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#462]
This page [https://www.joomla.org/rss-news-feeds.html](https://www.joomla.org/rss-news-feeds.html) needs to be completely reviewed. Lots of link are obsolete.
Can someone help me to correct the links?

**Comment by MATsxm** [comment]
You already know my position about this...
but seriously... kill this: https://community.joomla.org/connect/73-french.html

**Comment by Sandra97** [comment]
I asked @Joomv if she was possible for her to do something for that as it's completely outdated.

**Comment by Joomv** [comment]
I've done a quick kill on the CJO feeds in Connect.  Anything empty or not updated in last 6 months has been unpublished.  If that means an empty category, that's been unpublished too.

**Comment by Sandra97** [comment]
Thanks Rowan!

**Comment by Sandra97** [comment]
@mikeveeckmans, can you help me reviewing this page?

**Comment by mikeveeckmans** [comment]
@Sandra97 Can do this tomorrowevening (CEST) with you ? 
Someone starts at the top, other at the bottom?

**Comment by Sandra97** [comment]
Yes. Ping me when you're available and I'll leave my paint brush for a while ;)

**Comment by MATsxm** [comment]
kill it!

**Comment by jeckodevelopment** [comment]
don't be evil @MATsxm

**Comment by Sandra97** [comment]
I upated the content of the page.
If some are missing or wrong, please let me know and I'll amend the page.
