### ISSUE TITLE
[jorg] Link errors on Joomla! Press Page

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#463]
On this page https://www.joomla.org/joomla-press-official-books.html, all the book links are dead.
Do we still have a partnership with Pearson?
What can we do to update this page? 
@mikeveeckmans, can you help with this? 
Thanks.

**Comment by mikeveeckmans** [comment]
At the moment we don't have any active contracts with Pearson or another... Amazon changed it's policy and we don't have anything active there anymore.

I hope CLT can pick it up when the team is at full force again. 
I'll write copy to replace the current page

**Comment by sanderpotjer** [comment]
@mikeveeckmans @Sandra97 in the past the books were arranged by OSM because of the Pearson contracts. Wasn't aware of the contract being expired. What is needed for this from the CLT now?

**Comment by mikeveeckmans** [comment]
As we have nothing, anything would do ;-)

**Comment by mbabker** [comment]
They're still there, i.e. http://www.informit.com/store/joomla-templates-9780321827319

Maybe the affiliate links aren't good anymore?

**Comment by mbabker** [comment]
http://www.informit.com//store/joomla-programming-9780132780810
http://www.informit.com/store/joomla-explained-your-step-by-step-guide-9780321703781
http://www.informit.com/store/official-joomla-book-9780321821546

Just change the affiliate links to the direct links for each book.  Then look into why the affiliate links aren't working anymore.  If we get the affiliate links back, then update the references, but if not then there's nothing really lost as we're still at least linking to those sources.

**Comment by Sandra97** [comment]
I changed the links by the direct links as I don't know how to solve the issue with the affiliate links. If anyone knows, tell me and I'll change them again.
Note that Steve Burge's book is not available for sale. Would you like me to remove it?

**Comment by Sandra97** [comment]
On the 4 books mentioned on the page, one is not for sale anymore, 2 are out of stocks. @mikeveeckmans, what can we do in order to have a page with more relevancy?

**Comment by mikeveeckmans** [comment]
I'll check with the different teams and get back as soon as I get some information.

**Comment by mikeveeckmans** [comment]
Reply : 
> Hi Mike,
> 
> All the links works here.
> There is a contract with Person from 2009, which i have attached here for informational purposes.
> I have CC'ed Mike Demopoulos also as if there is still active income from the contract i imagine there must be some sort of financial trail.
> On a sidenote i do not believe old books of little relevance to Joomla 3.6 and beyond serves ud much great in being on those pages, i would rather seek new opportunities.
> A possibility could be a Amazon Affilliate program -> https://affiliate-program.amazon.com/welcome

Checking on the amazon store and if possible we'll add to shop and it can be used as well for the mentioned page

**Comment by mbabker** [comment]
The page was redesigned, this still require any work?

**Comment by Sandra97** [comment]
The page has been fully updated this week. We're good now.
Closing this issue.
Re-opne if needed
