### ISSUE TITLE
[jorg] Typo in menu item

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#464]
If you go to 
`https://www.joomla.org/about-joomla.html` or any other internal page of joomla.org you'll see the sidebar menu "Contributing to Joomla"

The "**Volunteer Portal**" menu item, should be "**Volunteers Portal**". 

![contributingtoj](https://cloud.githubusercontent.com/assets/733133/17719312/f8be4e6c-6419-11e6-879e-c1c1b6bb4924.PNG)

**Comment by MATsxm** [comment]
done

**Comment by jeckodevelopment** [comment]
Thank you :)
