### ISSUE TITLE
[jcomm] Search box position

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#465]
Most of the Joomla properties show the search box using the dedicated position in the jorg template: `position-0`

![search-jorg](https://cloud.githubusercontent.com/assets/733133/17721012/105decbe-6427-11e6-9297-f60273d587b6.PNG)

In the new community.joomla.org the search box is in the sidebar.
![search-cjo](https://cloud.githubusercontent.com/assets/733133/17721017/181da5ac-6427-11e6-869f-544361dbdf40.PNG)

Do we have a particular reason for that?

**Comment by Joomv** [comment]
Moved.
