### ISSUE TITLE
[jcomm] Mega menu too tall

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#466]
After moving the search box to the position-0, the mega menu height has grown

![cjotop](https://cloud.githubusercontent.com/assets/733133/17730608/b5ae225a-6469-11e6-961b-255fa10efa36.PNG)

**Comment by Joomv** [comment]
Dealt with.

**Comment by jeckodevelopment** [comment]
Thank you!!!! :)
