### ISSUE TITLE
[jcomm] shop.joomla link fails

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-websites#467]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by jeckodevelopment** [comment]
@mandville do you mean the link to the shop? 
shop.joomla.org (Still under construction)
or shop.joomla domain?

**Comment by mbabker** [comment]
If it was because of the MySQL error on the server, that's been long addressed.

Anything else, please re-open with additional details.
