### ISSUE TITLE
[jorg] https://www.joomla.org/about-joomla.html

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#468]
Who uses joomla? -> delete harvard please, they switched to drupal

**Comment by designbengel** [comment]
eiffel tower uses joomla :-)

**Comment by mbabker** [comment]
Deleted.

**Comment by mikeveeckmans** [comment]
Thank you @mbabker

**Comment by MATsxm** [comment]
And keep on thinking that kind of list and/or logos present more disadvantages than advantages...

**Comment by mbabker** [comment]
If only there were a place we could direct people to **showcase** superb sites built with Joomla...

**Comment by MATsxm** [comment]
Shhhh
**I** am supposed to be the bad guy :stuck_out_tongue_closed_eyes:

**Comment by mikeveeckmans** [comment]
@mbabker @MATsxm : i fully agree...
