### ISSUE TITLE
[jvols] String in the footer

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#470]
If you go to `https://volunteers.joomla.org/` you'll see that the string in the footer is not displayed... in fact there's a `%s` and it should be `Open Source Matters, Inc.`

![jvols](https://cloud.githubusercontent.com/assets/733133/17832154/6662db4c-66fc-11e6-9afc-ccb4348a57c8.PNG)

Maybe an update of the template will solve this issue.

**Comment by MATsxm** [comment]
already fixed

**Comment by jeckodevelopment** [comment]
Thank you @MATsxm , i missed 469!
