### ISSUE TITLE
[jrd] Bad alignment "Go" button

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#471]
If you go to `http://resources.joomla.org/en/` and look at the bottom of the page, in the "**Find a Resource Provider**" module, the "_**Go**_" button has a bad vertical alignment.

![jrdbad](https://cloud.githubusercontent.com/assets/733133/17876012/2128341e-68d7-11e6-8125-010a8cf640cc.PNG)

**Comment by genr8r** [comment]
unnecessary margin-top removed

**Comment by jeckodevelopment** [comment]
Thank you Brian
