### ISSUE TITLE
[jvols] The login module told us to login via Mail but we need to login via username

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#473]
The login module told us to login via Mail but we need to login via username

![image](https://cloud.githubusercontent.com/assets/2596554/17893201/1bdc9e28-6945-11e6-9b62-02971c18bae9.png)

**Comment by sanderpotjer** [comment]
@zero-24 it should work with your email too. I understand this wasn't the case for you?

**Comment by zero-24** [comment]
Ahh both works i have just tryed the wrong mail sorry @sanderpotjer
