### ISSUE TITLE
[jcomm] search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#474]
Client reported this to me today that they thought it was odd that on community we use com_search but on www we use com_finder and that the best (only) place he could go to search all the properties was docs.joomla.org

**Comment by mbabker** [comment]
It's inconsistent in general.  Considering all the sites are separate installs, using core's search extensions limits to that site.  Docs has a custom search set up which apparently isn't scope limited (we have a custom search on the API site but that's configured to search only that site).

It'd be nice if we had a global search somehow and made that the search that's in the mega menu, then each site could implement one of the core search extensions (I'm biased to Smart Search personally, YMMV) or something specific to that platform (keeping in mind our non-CMS properties) to search that site specifically.
