### ISSUE TITLE
[jmag] Share module - Suggestion

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#476]
In order to try to keep some consistency through Joomla! properties, would it be possible to use joomlarrssb plugin instead of the one current used?
Thank you!
![2](https://cloud.githubusercontent.com/assets/4682328/17912346/f5e0379a-6960-11e6-9169-4bb6f297672e.png)

**Comment by MATsxm** [comment]
Please see: 
https://github.com/joomla-projects/plg_content_joomlarrssb

**Comment by mbabker** [comment]
It's not supporting K2 right now though...

**Comment by MATsxm** [comment]
oh... "great" forget about it...

**Comment by mbabker** [comment]
It's our plugin, we can make it work.  Some sacrifice to the sanity keepers
required.

**Comment by MATsxm** [comment]
and saving my vanity... language files are available on Crowdin :wink: 
https://crowdin.com/project/joomla-patchtester

**Comment by jeckodevelopment** [comment]
@MATsxm you should use a generic name for that Crowdin repo... it's not only patchtester

**Comment by MATsxm** [comment]
I'm working on it already :stuck_out_tongue_closed_eyes:

**Comment by jeckodevelopment** [comment]
@MATsxm you've now Italian for the plugin.

**Comment by JacquesR** [comment]
Note that we are not using the plugin on the JCM, but only some of the code and some of the CSS, and it's been customised to work in K2 articles.

@Sandra97 I prefer the version that we are using on the JCM. It is not as overwhelming as the large size icons that  are used on the other sites.  

Apart from the colours, the JCM version looks the same as the icons on the other sites when viewed on a smaller screen, as we are using the same (small version) icons.  I can change the colours if that's a big issue.

Users don't have to be told that the Twitter icon is for "TWITTER". They will know it if they use it.

**Comment by Sandra97** [comment]
@JacquesR, in my opinion, it's not a question about if the icons look nice or not, but to try to create the maximum of consistency  into our overall web presence.

**Comment by JacquesR** [comment]
The icons we use are not inconstant with what is used on the other sites. It only behaves differently on a larger views (not showing the text next to the icons).  It would be hard to argue that this affects the consistency of our web presence. Again, I'll change the colours if that's a major issue, but not planning to change the large view look.  Please allow for some individuality on sub-sites.

**Comment by Sandra97** [comment]
Did I ever say I don't "allow" customization? I gave you my opinion, as I think it can be constructive to share different point of views.

**Comment by JacquesR** [comment]
Thanks for sharing your opinion, and I agree that it is good to share different points of view.
I'll rewrite that sentence to make it clearer: We should allow/accommodate some individuality on sub-sites.

**Comment by mbabker** [comment]
Some, yes.  To the extent that the same elements on different sites are massively different or the sites have major styling differences or have made so many customizations that they cannot update the template anymore, I don't agree with.  But that's just me being anal retentive about ensuring there's a consistent look and feel for the brand on its domains.

**Comment by JacquesR** [comment]
Michael, I don't disagree, but these social share icons, that I would suggest are _not_ integral to our brand, and that the JCM _is_ using a style that is the same as that of the mobile view on other sites (so not round or glossy or other design of icons), seems to be (in my opinion) a minor issue.

I have now updated the CSS so that the icons use the same colours as on the other J sites.
