### ISSUE TITLE
[jvols] Can't add group reports anymore (403 error)

### ISSUE THREAD

**Issue by yvesh** [joomla/joomla-websites#477]
When trying to submit a new group report on volunteers portal i now get a 403 error.

<img width="1214" alt="screenshot 2016-08-24 17 40 28" src="https://cloud.githubusercontent.com/assets/897638/17937303/ea3f3294-6a21-11e6-963d-c0bd454e5e0b.png">

**Comment by jeckodevelopment** [comment]
@sanderpotjer can you look at this?

**Comment by sanderpotjer** [comment]
@yvesh thanks for reporting the issue! It should be fixed now.

**Comment by yvesh** [comment]
Thank you @sanderpotjer - can confirm it's working now 👍

**Comment by sanderpotjer** [comment]
@yvesh great, thanks for confirming!
