### ISSUE TITLE
[jevnt] 404 on Previous/Next month buttons

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#479]
If you go to `https://events.joomla.org/all-events` and click on "July" or "September" buttons (Prev/Next) both at the top or the bottom of the calendar, you'll receive a 404 error for each click on these buttons.

Target URLs are:
`https://events.joomla.org/all-events/at,2016.7`
`https://events.joomla.org/all-events/at,2016.9`

**Comment by Radek-Suski** [comment]
I would love to but https://vpn.joomla.org seems to be down :(

**Comment by Radek-Suski** [comment]
Anyway, I set the site currently offline until VPN works again so I can check it

**Comment by sanderpotjer** [comment]
@Radek-Suski i've submitted a ticket at Rochen to get the VPN fixed

**Comment by Radek-Suski** [comment]
Thanks @sanderpotjer  :)

**Comment by sanderpotjer** [comment]
@Radek-Suski should work again!

**Comment by Radek-Suski** [comment]
Thanks. All fixed now.

**Comment by jeckodevelopment** [comment]
thank you :)
