### ISSUE TITLE
[jrepo] Gravatar default image not displaying on home page

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#48]
gravatar override is not displaying default image
https://www.evernote.com/l/ADdYqPAdmj9JeYcffJMJfEhE-166AIZUO1c 

like here
https://www.evernote.com/l/ADe1FRueA4lNEbFsv-D4JfasmF1CdwccJbM

this will be working once we push live, and I have requested all leaders to add their email to gravatar. I will follow up individually today.

**Comment by MAT978** [comment]
+ default Icon to check
@Sandra97

**Comment by mbabker** [comment]
It'll be fine at launch.  Gravatar is hitting the htpasswd on the site so it can't load the image.  The other option is to just hardcode the base URL instead of using `JUri::root()` in the layout file.
