### ISSUE TITLE
[jdocs] Question about colours

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#480]
If you go to `https://docs.joomla.org/Main_Page` you can see the follwoing Joomla! Logo (CMYK):
![jdocs](https://cloud.githubusercontent.com/assets/733133/17952705/71df1930-6a6d-11e6-9e06-357716367d12.PNG)

It's darker than the "official" one (RGB). 
![joomla-brandmark-flat-rgb](https://cloud.githubusercontent.com/assets/733133/17952788/01abb802-6a6e-11e6-968e-8a52253dff0f.png)

Question is, why do we use the CMYK version there and the RGB version on the other properties?

**Comment by jeckodevelopment** [comment]
Furthermore, looking at the position of the `TM` indica, i can deduct that the one of Docs is not the latest version.

**Comment by MATsxm** [comment]
Note that there's no rule for the `TM` position
fix in progress ;)

**Comment by Sandra97** [comment]
Good catch Luca! I'll change it tomorrow morning as I don't have Adobe Illustrator on my laptop.

**Comment by MATsxm** [comment]
she doesn't even have the "underscore" on it... justSaying :stuck_out_tongue_closed_eyes:

**Comment by Sandra97** [comment]
If it was just one key missing... Buy me a new one!

**Comment by jeckodevelopment** [comment]
@MATsxm you should buy her a new one :P 
Btw thank you both!

**Comment by MATsxm** [comment]
@jeckodevelopment me alive... NEVER!
life must be challenging in the Caribbean :stuck_out_tongue_closed_eyes:

**Comment by Sandra97** [comment]
Pfff.... I'm too nice, logo is changed.
Thanks again Luca and no thank you for MAT of course.
Closing this issue. 
Re-open if needed

**Comment by MATsxm** [comment]
you can't reopen it as you don't have enough keys for that...

**Comment by Sandra97** [comment]
:finger:

**Comment by jeckodevelopment** [comment]
:D i'm wondering about the missing "finger" icon

Thank you both, again!
