### ISSUE TITLE
[jmag] Authors page

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#481]
Niether the page navigation at the bottom nor the alphabetical filtering is working

**Comment by JacquesR** [comment]
I'll check with @wilsonge 
He did fix that previously for us, and it is still working on the test site, so something on the live site is causing the issue.

**Comment by wilsonge** [comment]
This is some sort of caching issue. turning caching off fixes things.

**Comment by wilsonge** [comment]
Removed caching *shrug*
