### ISSUE TITLE
[jtm] inconsistency in the use of trademarked names

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#483]
1. Here: https://tm.joomla.org/disclaimers
in the JUG part
![1472241597985screensave](https://cloud.githubusercontent.com/assets/1972717/18018761/c28a2462-6ba6-11e6-96c3-350a2bb9437a.png)
3 times and 3 different uses.

2. Here: https://tm.joomla.org/conditional-use-logos
in Conditional Use Logos part
![1472241793635screensave](https://cloud.githubusercontent.com/assets/1972717/18018909/6ea1b42c-6ba7-11e6-909b-b094b08a3aa9.png)
* `the Joomla! Project` should be: **T**he Joomla! Project**™**
* `The Joomla! logo` should be: The Joomla!® name and logo...

**Comment by Joomv** [comment]
Can you point me at the right usage for JUGS and I’ll make sure the JUGS Team get their part in this sorted.

 

Thanks.

 

Rowan

**Comment by jeckodevelopment** [comment]
@MATsxm it should be ok now. I reviewed and changed. Please check if i missed something!

**Comment by jeckodevelopment** [comment]
@Joomv it should be: https://tm.joomla.org/disclaimers#JUGs

**Comment by MATsxm** [comment]
@Joomv 
TBH, I guess ALL the content should be proofreaded and I just saw those because I need them working on The Trademarks and Disclaimers list see #274 
Maybe one day I will take a deeper look but it's not on the Top of my toDo.
Of course, if you need a specific info, just ask.

@jeckodevelopment 
Thanks.
Note: technically speaking, the indicia is not needed for the second singular `Each Joomla! User Group™, along...` as a judge would consider it as a derivated TM from the plural ones claimed.
But this is NOT an improper use (with or without here, is not a problem)
* The 3rd one (still in JUGS part): In English following local language, if different: `Joomla User Groups™ ` needs the Bang !
* Also in the same <p, the `The Joomla Project™` need the bang too.

**Comment by jeckodevelopment** [comment]
@MATsxm i guess i'm done. Please check again :)

**Comment by MATsxm** [comment]
@jeckodevelopment 
Thanks - looks fine to me!
At least for this part only and before my :coffee: #2
Note that I will have to fix on my draft of the list.

**Comment by jeckodevelopment** [comment]
great. Thank you for reporting these issues/typos.
I'm closing this, re-open if needed. 
Next time, for missing typos on TM website, you can directly assign me ;)
