### ISSUE TITLE
[jdocs] Logo consistency

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#484]
`https://docs.joomla.org/Main_Page`

The docs template shows a logo at the beginning of the top menu.
![jdocs-logo](https://cloud.githubusercontent.com/assets/733133/18027357/df11b8e6-6c61-11e6-803a-bea712c45d6e.PNG)

Actually the logo is the CMYK version.
It should be the RGB one, as for the logo in the center of the page.

The path of the actual image is: `https://docs.joomla.org/skins/foreground/joomla_logo_small.png`

Thank you :)

**Comment by Sandra97** [comment]
I wish I could change this one....

**Comment by jeckodevelopment** [comment]
I'm not at my notebook to provide you a 32x32 px PNG logo

**Comment by MATsxm** [comment]
+ the menu fixes but........................ :rage:

**Comment by jeckodevelopment** [comment]
@MATsxm but? 
Is this template unlinked from the standard one?

**Comment by Sandra97** [comment]
I can provide easily the logo at the right size, but I can't change it.

**Comment by mbabker** [comment]
> Is this template unlinked from the standard one?

That should be somewhat obvious :chuckle:

**Comment by jeckodevelopment** [comment]
@mbabker sometimes i love asking stupid questions :P

**Comment by MATsxm** [comment]
Fixed
Thanks
closed - reopen if needed

**Comment by jeckodevelopment** [comment]
good job @MATsxm ;)
Thank you
