### ISSUE TITLE
[jshop] testers required

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#485]
Who wants to have a test run on the shop? 
Ping me if you don't have access at the moment. Thank you!

**Comment by Sandra97** [comment]
Just my 2 cents... 

I think it could be a good idea to re-integrate (or re-create) the 2 banner images we had before the merge into cjo for screens under 480px, the readibility was better.

Previous:
![a](https://cloud.githubusercontent.com/assets/4682328/18030830/208aabc4-6c95-11e6-8365-fd799d752d94.png)

Current:
![after](https://cloud.githubusercontent.com/assets/4682328/18030832/2b658e7e-6c95-11e6-8a71-056fb4f822fb.png)

Also, I personally prefer the previous version of the Joomler's showcase:
![joomlers](https://cloud.githubusercontent.com/assets/4682328/18030776/94d2bb90-6c93-11e6-92a6-aeab2094144d.png)

Than the current one:
![6](https://cloud.githubusercontent.com/assets/4682328/18030815/a6a23692-6c94-11e6-85dd-bba29c9088ea.png)

On the contact page, there are display issues with the 2 buttons, issue we didn't have previously:
![before](https://cloud.githubusercontent.com/assets/4682328/18030799/2257c56e-6c94-11e6-8d68-a75284467d8b.png)

Now:
![now](https://cloud.githubusercontent.com/assets/4682328/18030800/2a39bef4-6c94-11e6-805e-c2bb9392ad4d.png)

Also, ReCaptcha is not responsive anymore. And on "normal" screens, could be better to align the Recpatcha to have a better display?

Thank you!

**Comment by jeckodevelopment** [comment]
@mikeveeckmans if needed, just give me access.

**Comment by Joomv** [comment]
Hi Sandra,

1. Shop Banners are done.
2.  It made sense to make it Sobi.  I have done a little work on it but happy for you to either take over or give me some directions.
3. I thought I'd fixed the contact form, must have dreamt it.  I've done some now to address the issues.  Please take a look and let me know if that's ok.

Thanks

**Comment by Sandra97** [comment]
Hi Rowand and thank you. 

Yes, it makes sense to make it with SP and not to add another extension just for this and the contact form. 

You haven't dreamt about the contact form, you have already worked on it and now corrected these 2 details remaining. 

2 more details:
- the breadcrumbs on the contact page: the font size is not the one it's supposed to be
- something went wrong with the banner on the FAQ page: image is not displayed anymore (or is it my cache?) (the hompeage banner on mobile is now better).

**Comment by Joomv** [comment]
I hadn't closed a small tag in the module above.  Now breadcrumbs are right size.

Check now, I have updated the paths.

**Comment by Sandra97** [comment]
Both are now ok. Thanks Rowan!

**Comment by mikeveeckmans** [comment]
Thank you @Joomv & @Sandra97 !
