### ISSUE TITLE
[josm] Please active https/ssl

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#486]
Would it be possible to activate https for this domain? thank you!

**Comment by mbabker** [comment]
You'd have to work out getting a certificate for the domain.  The only one we have is for `joomla.org`.

**Comment by zero-24** [comment]
Is Let's encrypt a possible solution?

**Comment by mbabker** [comment]
Someone would have to take that up with Rochen.  It's always an option, just depends how much work folks are willing to do since the certificates renew more often or how much money people are willing to spend for other options.

**Comment by zero-24** [comment]
https://www.rochen.com/blog/2016/02/introducing-free-ssl-certificates/

>Domain validated SSL certificates issued by Let’s Encrypt are valid for 30 days but will be automatically reissued and installed on the server before expiring. So there is nothing for you to manage. Your site now has HTTPS protection completely free of charge.

>It is possible for Managed Cloud Servers (MCS) customers to take advantage of the Let’s Encrypt project but custom configuration is required. Please contact our 24/7 technical support team through the My Rochen portal to discuss further.

**Comment by mikeveeckmans** [comment]
@Saurabh1 please activate Let's encrypt at the moment

**Comment by mbabker** [comment]
This isn't something Saurabh can just do on a whim.  If you want SSL enabled this needs to be coordinated with Rochen.

Also, we are using MCS systems.  Further requiring coordination with Rochen.

**Comment by mikeveeckmans** [comment]
ok, thank you for the feedback @mbabker .
Can you or someone communicate this with Rochen ?

**Comment by Joomv** [comment]
This should be done shortly, will return to close when it is.

**Comment by Joomv** [comment]
This is done!
