### ISSUE TITLE
[jshow] Generate aliases from Title instead of URL

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#487]
If you look at the new Joomla! Showcase Directory, item aliases are currently generated from the Website URL instead of the listing title.

e.g. `https://showcase.joomla.org/new/browse-sites/www-liptonicetea-com.html#desc`
`https://showcase.joomla.org/new/browse-sites/www-recrutement-terre-defense-gouv-fr.html`

**Comment by oliviernolbert** [comment]
It's a choice that has been made. One reason is that a domain name is less often changed than a site name/listing title.

Is it an issue or can it be one once website will be live?

**Comment by Radek-Suski** [comment]
I think a url within the alias doesn't make much sense. Otherwise those aliases can get veeeeeery long.
As for changes, you can always set canonical href.

**Comment by jeckodevelopment** [comment]
yes, otherwise, just use an ID in the alias. The URL sometimes is very very long.

**Comment by sebastienlapoux** [comment]
Thanks!
Changed. Using the ID only.

**Comment by jeckodevelopment** [comment]
Thank you @sebastienlapoux
