### ISSUE TITLE
[jshow] Top menu height unstable when clicking on submenu

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#488]
If you click on items that have a submenu, while on submenu items the height of the top menu bar changes.

![jshow-topmenu](https://cloud.githubusercontent.com/assets/733133/18033745/d2e9bf84-6d2c-11e6-8edd-b5cda5de0d35.gif)

**Comment by Sandra97** [comment]
This issue should be solved by using the latest version of jorg template

**Comment by sebastienlapoux** [comment]
Fixed. Thanks!

**Comment by MATsxm** [comment]
ok here thanks
Closed -reopen if needed

**Comment by Sandra97** [comment]
Solved but still not using jorg template...
