### ISSUE TITLE
[jshow] Typo in team name

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#489]
If you go to https://showcase.joomla.org/new/about-jsd/team-members.html
Title is `Meet the JSS Team` instead of `Meet the JSD Team`

![jss-jsd](https://cloud.githubusercontent.com/assets/733133/18033752/29c53f0e-6d2d-11e6-964d-de8412a534d9.PNG)

**Comment by oliviernolbert** [comment]
Done, thank you.

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
