### ISSUE TITLE
[jrepo] social sharing buttons and social sharing not working

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#49]
Mike Veekmans is fixing
social share needs to be added on all pages 
https://www.evernote.com/l/ADcjpSJKyb9ASJ4nHsH98oJoAQTLtPlwoLQ

sharing does not work and is missing the title see https://github.com/joomla/joomla-websites/issues/18 for suggestions

**Comment by MAT978** [comment]
IMHO, nothing but this: 
http://kurtnoble.com/labs/rrssb/
Thanks Brian for the ping

**Comment by jessicadunbar** [comment]
Closing this
