### ISSUE TITLE
[jshow] Proper use of the markup

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#490]
If you go to https://showcase.joomla.org/new/about-jsd/disclaimer.html

Paragraph titles are just normal `<p>` underlined.
It could be more consistent to use headers instead of the underline.

![badmarkup](https://cloud.githubusercontent.com/assets/733133/18033858/27753e42-6d2e-11e6-91e6-e08b68f95aaf.PNG)

**Comment by oliviernolbert** [comment]
Done, thank you.

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
