### ISSUE TITLE
[jshow] Log you?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#491]
If you go to https://showcase.joomla.org/new/register
The warning message says:

> If you had an account on the previous showcase site please try to log you.

It should be:

> If you had an account on the previous showcase site please try to **log in**.

![logyou](https://cloud.githubusercontent.com/assets/733133/18033881/c79ab488-6d2e-11e6-8241-cd7401ee03a5.PNG)

**Comment by oliviernolbert** [comment]
Done. Thank you.

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
