### ISSUE TITLE
[jshow] FAQ or FAQs

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#492]
Generally people write "**FAQs**" because it means "Frequently Asked Questions", in the plural form.
Actually JShow says "**FAQ**".

![faq](https://cloud.githubusercontent.com/assets/733133/18033913/b28e4c20-6d2f-11e6-8c51-b58e5228668a.PNG)

**Comment by oliviernolbert** [comment]
Done. Thank you.

**Comment by MATsxm** [comment]
Thanks
Closed - Re-open if needed
