### ISSUE TITLE
[jmag] Pagination without style

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#493]
If you go to: http://magazine.joomla.org/
Pagination is displayed without any style.

![badpagination](https://cloud.githubusercontent.com/assets/733133/18035773/5cc9ac4e-6d5c-11e6-82ea-42261eac2331.PNG)

**Comment by JacquesR** [comment]
I'm guessing that you are seeing that when the incorrect front page is showing?  (when it is showing the old content instead of the latest month)
Could you confirm?

**Comment by jeckodevelopment** [comment]
Confirm

**Comment by JacquesR** [comment]
I'm not seeing the same. I was looking now at that page (before clearing the cache again), and the navigation looked styled. Like it is on this page:  http://magazine.joomla.org/issues/issue-aug-2016/itemlist/category/243-2016-august

**Comment by jeckodevelopment** [comment]
if I go to your link, it works now :)

**Comment by wilsonge** [comment]
This should no longer be an issue - i think i've cleared all the pagination styles to be consistent with the template
