### ISSUE TITLE
[jmag] Empty page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#494]
I just pressed on the "2" link on the pagination to view 2 page and i got an empty page.
URL is: http://magazine.joomla.org/?start=8

![jmagempty](https://cloud.githubusercontent.com/assets/733133/18035788/c892c820-6d5c-11e6-8e53-4306dbe9f6e8.PNG)

**Comment by JacquesR** [comment]
Where was the navigation? Which page were you on?

**Comment by jeckodevelopment** [comment]
I clicked on the "2" button of the pagination

**Comment by JacquesR** [comment]
OK, I still don't know which page you were on? There's no navigation on the front page, unless you looked at it while is was showing the wrong articles. (the other bug)

**Comment by jeckodevelopment** [comment]
I guess that it was linked to the other issue.
Closing this because now i can't replicate the error again.
Thank you @JacquesR
