### ISSUE TITLE
[jshow] Horizontal scrolling on the fronpage

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#496]
Hello, 

On the frontpage, for screens up to 1178px, something on the page is creating an horizontal scrolling. Would be nice to fix this.

Thank you

**Comment by Sandra97** [comment]
Ping @oliviernolbert

**Comment by sebastienlapoux** [comment]
Hi Sandra, can you please post a picture? Can not reproduce it.

**Comment by Sandra97** [comment]
Here it is (it happens for portrait as well as landscape display)
![14139260_1435547826461013_195647646_o](https://cloud.githubusercontent.com/assets/4682328/18109986/0298f454-6ee3-11e6-90cc-5fd68e3e0896.png)

**Comment by Sandra97** [comment]
@sebastienlapoux, the horizontal scrolling is due to the position of the side arrows of the featured websites => right:-120px and left:-120px. 
If you adapt these 2 in your media queries, it should solve the issue.

**Comment by sebastienlapoux** [comment]
Thanks to check again.

**Comment by Sandra97** [comment]
No more horizontal scrolling! Thank you Sébastien.
Closing this issue.
Re-open if needed.
