### ISSUE TITLE
[jshow] Wrong thumbnail size on responsive display

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#497]
For screens unders 768px, the thumbnails for the recently added part are blurred because of an inadequate size (320px, a width of 700px should solve this issue)
![index](https://cloud.githubusercontent.com/assets/4682328/18049741/08045284-6db8-11e6-8902-6dc7d07abd7a.png)

**Comment by Sandra97** [comment]
Ping @oliviernolbert

**Comment by Sandra97** [comment]
Note that it's not only on the recently added part of the frontpage but everywhere you're using these thumbnails

**Comment by sebastienlapoux** [comment]
Thanks Sandra. On which device do you test please?

**Comment by Sandra97** [comment]
On my tablet (Samsung Galaxy tab3)

**Comment by sebastienlapoux** [comment]
@Sandra97 thanks to check again on your tablet

**Comment by Sandra97** [comment]
Display is good now on my tablet.
Closing this issue.
Re-open if needed.
