### ISSUE TITLE
[jshow] Drupal website

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#498]
Please remove the website of the French Ministry Defence Land Force. It is powered by Drupal...

**Comment by Sandra97** [comment]
Ping @oliviernolbert

**Comment by Sandra97** [comment]
Already mentioned in #156

**Comment by oliviernolbert** [comment]
Will be done, thank you

**Comment by oliviernolbert** [comment]
Website unpublished and so removed from public view.

**Comment by MATsxm** [comment]
Thanks
closed - re open if needed

**Comment by Sandra97** [comment]
Is it just me or is it still displayed (I'm not log in and cleaned my cache)?

**Comment by MATsxm** [comment]
agree.
Still here and.... still a Drupal :stuck_out_tongue_closed_eyes:

**Comment by oliviernolbert** [comment]
Ok, found why. It will be fixed today (the visibility issue, not the Drupal issue)

**Comment by mikeveeckmans** [comment]
checked, not visible anymore
