### ISSUE TITLE
[jshow] Can't edit a website

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-websites#499]
Hi
Seems we can't edit an already posted website. The SAVE button is missing

thanks

cyril

**Comment by Sandra97** [comment]
I had the same issue. You can edit but not save your changes.
@sebastienlapoux, @oliviernolbert, could you have a look?
Thanks.

**Comment by mikeveeckmans** [comment]
Same here, side note : my submission is still in review

**Comment by oliviernolbert** [comment]
Currently checking...

**Comment by oliviernolbert** [comment]
'Save' and 'Save & Close' buttons should now be available on site edition.

**Comment by Sandra97** [comment]
I confirm and it works fine. Thanks Olivier.
Closing this issue.
Re-open if needed.
