### ISSUE TITLE
[jrepo] Menu Name Change for Main Navmenu

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#50]
Menu name title needs to be updated 
https://www.evernote.com/l/ADd3oEFLbYBJSZU8szNmoBNkuJd6wRQ-Lzk

**Comment by mbabker** [comment]
Personally, I'd move those last two items into the About Joomla menu and kill that third one off.

**Comment by MAT978** [comment]
+1

**Comment by Sandra97** [comment]
+1

**Comment by mikeveeckmans** [comment]
+1

**Comment by MAT978** [comment]
Done & closed - Thanks
