### ISSUE TITLE
[jshow] Quote - Suggestion

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#500]
Regarding the Quote field when submitting an entry, I noticed this field is required. 
IMHO, it should not be as this element can be confidential. Or at least, if you really want to have it as required, could you change the price range (under 10k, between 10k and 50k, above 50k or something like that?).

Thank you

**Comment by Sandra97** [comment]
Ping @oliviernolbert

**Comment by sebastienlapoux** [comment]
Thanks Sandra. We added 5000 - 10000.

Currently this field is just requested on submission. The value is not used in public. The JSD team wish to estimate if this field is pertinent or not.

**Comment by Sandra97** [comment]
Goog thing it's not publicly available. IMHO, I still think it should not be a required field. Most of the time, this element is confidential.

**Comment by MATsxm** [comment]
+1

**Comment by mbabker** [comment]
I'm just going to throw my 👍  on making it optional data.  If JSD wants to collect it for whatever reason I think that it should be made clear what it's used for and that it's not public data, but it shouldn't be a mandatory field.

**Comment by Radek-Suski** [comment]
That's pretty personal information. Not to mention that I couldn't say how high the "Quote" would be for our company website.

**Comment by Joomv** [comment]
Something it could be replaced with, rather than "what it cost" is the sort of site it is along the lines of

Hobby/Personal Site.
Small Business.
Corporate.
Enterprise.

**Comment by brianteeman** [comment]
Golden rule of forms. Don't ask questions if you dont have a use fir the answers

**Comment by sebastienlapoux** [comment]
Thanks for your feedback.
Currently we removed the quote field.
@Joomv, thanks, why not, already category and tag. Will launch like this and discuss opportunity of additional fields later.

**Comment by sebastienlapoux** [comment]
Thanks to close the issue after your confirmation.

**Comment by Sandra97** [comment]
I confirm the field has been removed.
Closing this issue. 
Re-open if needed.
