### ISSUE TITLE
[jforum] Unstick JWC 2014 post

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-websites#501]
Can we get this post UNstuck so it's not at the top of the Event forums? It's badly out of date now and not relevant.

thanks!

http://forum.joomla.org/viewtopic.php?f=306&t=840792

**Comment by jeckodevelopment** [comment]
@pe7er can you look at this, please?

**Comment by pe7er** [comment]
Done!

**Comment by MATsxm** [comment]
Thanks
Closed - reopen if needed
