### ISSUE TITLE
[jshop] contact form

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#502]
After submitting an email you are redirected to a page which has a 404

**Comment by Joomv** [comment]
Dealt with.  Now shows message.

**Comment by brianteeman** [comment]
Thanks

**Comment by mikeveeckmans** [comment]
@Joomv 
Just one more question : when the form arrives it has the no-reply as sender and reply address. Could this be the address from the person who sends the form? 
Thank you. 
(looked at it, but couldn't find it, nor in the documentation of chrono)

**Comment by mikeveeckmans** [comment]
checked, not visible anymore

**Comment by Joomv** [comment]
The reply to is set to the sender.  If this isn't working out I can change.
Also were we not going to use the helpdesk for this eventually?
Might be an idea to switch that now?

**Comment by mikeveeckmans** [comment]
Yeah let's switch it...
