### ISSUE TITLE
[jshop] banner image on mobile

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#503]
On mobile devices the banner is on top of the image. This can be fixed by updating custom.css with

```@media only screen and (max-width: 480px)
.bannerpm {
    display: block;
    margin-top: 30px;
}```

**Comment by Joomv** [comment]
Fixed

**Comment by brianteeman** [comment]
Thanks - Looking at it again I think it needs to be less than 30px

**Comment by mikeveeckmans** [comment]
Thank you
