### ISSUE TITLE
[jshop] help desk

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#504]
When you are logged in there is an html error somewhere breaking the layout
![hx2o](https://cloud.githubusercontent.com/assets/1296369/18064452/74d7a928-6e27-11e6-965a-65cc46b5f6d7.png)

**Comment by Joomv** [comment]
Bizarrely its just the shop user group.
I'll look at this in the morning.

**Comment by brianteeman** [comment]
OK - thanks

**Comment by mikeveeckmans** [comment]
@brianteeman still happening?

**Comment by brianteeman** [comment]
Sorry I didn't check when Rowan said it was just for a restricted usergroup

**Comment by mikeveeckmans** [comment]
no prob ;-) 
think it's fixed, if not please re-open ;-)
