### ISSUE TITLE
[jshop] shop support menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#505]
https://community.joomla.org/helpdesk/shop-support.html 

There is duplication on the menus

![gmrh](https://cloud.githubusercontent.com/assets/1296369/18064509/a3f06b96-6e27-11e6-849e-9b450fbf8022.png)

**Comment by Joomv** [comment]
Dealth with

**Comment by brianteeman** [comment]
Looks like you have resolved this one as well - thanks

**Comment by mikeveeckmans** [comment]
Thank you!
