### ISSUE TITLE
[jmag] Article in list layouts breaks responsive display

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#507]
On the homepage or the issue pages where you have a list of articles, the row in the article "card" with the date, author, and comments button isn't responsive and displays full width, causing a massive horizontal scroll on mobile.

**Comment by JacquesR** [comment]
Thank Michael. 
I've fixed this in the test install, by moving the layout around a bit, and will have it fixed soon on the live site. (need to add the micro data stuff back in)

**Comment by JacquesR** [comment]
@mbabker I've updated the html and CSS for the category view, to resolve the issue on handheld views.

Please have a look if it looks better now.

**Comment by mbabker** [comment]
Looked fine when I glanced last night, thanks!
