### ISSUE TITLE
[jshow] Display broken for Browse sites and its menu items

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#508]
The display on these pages is broken because of the text of JAB website. If you can limit the number of characters displayed on these pages, it will solve this issue.
![index](https://cloud.githubusercontent.com/assets/4682328/18086237/de60e5e4-6e7c-11e6-8e36-0f09ecf9a962.png)

**Comment by Sandra97** [comment]
Ping @oliviernolbert & @sebastienlapoux

**Comment by oliviernolbert** [comment]
Work In progress. Thank you Sandra.

**Comment by oliviernolbert** [comment]
The extra text has been hidden with some css. So, full text is available on mobile (1 item per line). thanks for testing.

**Comment by Sandra97** [comment]
I confirm the display has been corrected and is now ok. One line displayed.
Closing this issue. 
Re-open if needed
