### ISSUE TITLE
[jtrain] add to CDN menu please

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#509]
@mbabker can you add Joomla! Training to the CDN menu please? Thank you!  
Either under support or community (prefer support)
url : training.joomla.org or https://community.joomla.org/joomla-training.html

**Comment by jeckodevelopment** [comment]
I'll do it!

**Comment by mikeveeckmans** [comment]
@jeckodevelopment thank you

**Comment by jeckodevelopment** [comment]
done! :D 
@mikeveeckmans you're welcome

**Comment by jeckodevelopment** [comment]
Closing since we have a PR for this.
