### ISSUE TITLE
[jrepo] Menus are different

### ISSUE THREAD

**Issue by jessicadunbar** [joomla/joomla-websites#51]
menus are not consistent throughout the site
https://www.evernote.com/l/ADd3oEFLbYBJSZU8szNmoBNkuJd6wRQ-Lzk

**Comment by mbabker** [comment]
The About and Contributing side menus are now set to show on all pages but the homepage and contribute landing page.  Just leaves that navmenu module with the Joomla Press and In Your Language items to sort out.

**Comment by Sandra97** [comment]
Regarding the little module 'Do you want to contribute?', could it be a good idea to add the Volunteer Portal to the Contribute side menu and delete the 'Do you want to contribute?' module?

**Comment by MAT978** [comment]
Done & closed - thanks
