### ISSUE TITLE
colours [jorg] 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#510]
https://www.joomla.org/

I still don't see the logic of having different colours doing the same thing on the buttons. I can see that the blue, green, organge & red sequence makes sense as they are the order the colours appear in the logo. But why have different colours in the buttons above when they link to the same location?

<img width="419" alt="button-colour-jorg1" src="https://cloud.githubusercontent.com/assets/736887/18089184/9cabe362-6eb6-11e6-83d4-60600124fbc5.PNG">

<img width="186" alt="button-colour-jorg2" src="https://cloud.githubusercontent.com/assets/736887/18089197/a7ba9870-6eb6-11e6-8c52-fb0bad64c6a3.png">

I did mention this before but haven't seen any solution or logical reason why it should stay as it is.

**Comment by mbabker** [comment]
The buttons on the top bar have always been those colors and long predate .org itself being on 3.x or using the current banner section.  Short of hiding the top bar's buttons on the homepage or redoing the button sequence on the homepage banner, there's going to be a small bit of inconsistency.  And considering how long those buttons on the top bar have been displayed the way they have (and considering we have some sites that are slow to make template updates), I wouldn't touch that section at all.

**Comment by Hils** [comment]
Fair comment. I can accept it if it's a technical problem - just a shame it looks so graphically inconsistent!

**Comment by Sandra97** [comment]
I changed the color of the buttons of the banner position so now Download buttons are both orange and Demo blue.
Closing this issue.
Re-open if needed.

**Comment by Hils** [comment]
Brilliant! Thank you very much for doing that @Sandra97 - it looks tons better :)
