### ISSUE TITLE
[ALL] Update Joomla! Template

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#512]
Please update Joomla! standard template to version 2.1.0
It includes a series of improvements and a brand-new CDN menu.

@mbabker sent already a copy of the template to each webmaster of the J.org properties.
Please give a notification when updated.

- [x] api.joomla.org
- [x] certification.joomla.org
- [x] community.joomla.org 
- [x] developer.joomla.org 
- [x] download.joomla.org 
- [x] exam.joomla.org 
- [x] extensions.joomla.org 
- [ ] forum.joomla.org 
- [x] help.joomla.org 
- [x] issues.joomla.org 
- [x] joomla.org 
- [x] joomla.org/3
- [x] magazine.joomla.org 
- [x] resources.joomla.org 
- [x] showcase.joomla.org 
- [x] tm.joomla.org 
- [x] vel.joomla.org 
- [x] volunteers.joomla.org

**Comment by mbabker** [comment]
Edited the site list.  ideas and framework don't use this template...

**Comment by jeckodevelopment** [comment]
Thank you :)

**Comment by jeckodevelopment** [comment]
@mbabker demo should update the CDN menu, right?

**Comment by mbabker** [comment]
Preferably they should sync the menu, yes.  But, I don't have any dealings with SiteGround so that's on whomever to arrange that.

**Comment by mandville** [comment]
can the name of the template reflect the issue date.

**Comment by jeckodevelopment** [comment]
This should be done again for the release 2.1.0.1

**Comment by Joomv** [comment]
Done for CJO.

**Comment by wilsonge** [comment]
Done for magazine

**Comment by jeckodevelopment** [comment]
@sam-suresh can you do it for Exam?
@genr8r can you do it for JRD?
@sebastienlapoux can you do it for Showcase?
@Joomv what to do with Events? Should we wait the integration with CJO?

**Comment by Radek-Suski** [comment]
We are going to move events to community.joomla.org probably this weekend so I'll skip this time ;)

**Comment by jeckodevelopment** [comment]
great news! Thank you @Radek-Suski !

**Comment by sebastienlapoux** [comment]
@jeckodevelopment , yes in progress in the new showcase site. Will be ended in next 2 weeks.

**Comment by jeckodevelopment** [comment]
@sebastienlapoux thank you!

**Comment by jeckodevelopment** [comment]
@xyzulu are you in charge for the Forum?

**Comment by xyzulu** [comment]
@jeckodevelopment no
What is the issue? I can sure I can point you to the right person.

**Comment by jeckodevelopment** [comment]
update the CDN menu also on the forum! :)

**Comment by xyzulu** [comment]
Have you contact someone from the CLT to request this? In any case, I ask someone I know there to look here.

**Comment by jeckodevelopment** [comment]
I tagged you because on the forum you're reported as Group leader.
BTW, i guess that @pe7er should be able to help

**Comment by xyzulu** [comment]
I've emailed Peter, Olaf and someone from the CLT for you (David). I am sure between them they we get this done.

Thanks

**Comment by jeckodevelopment** [comment]
Thank you Brad!

**Comment by ooffick** [comment]
I have received the details for the changes to menu and footer for the forum from both Peter and Brad and will work in it. What is the time frame for this change?

**Comment by Radek-Suski** [comment]
> What is the time frame for this change?

Yesterday :P

**Comment by jeckodevelopment** [comment]
@ooffick as soon as possible :) thanks

**Comment by wilsonge** [comment]
Pinging @jeckodevelopment :P what's the status of exam.joomla?

**Comment by jeckodevelopment** [comment]
Thanks @sam-suresh and @anibalsanchez  :)
So, only one remaining!

**Comment by MATsxm** [comment]
@jeckodevelopment I was thinking about adding a new subdom? :smiling_imp: :stuck_out_tongue_winking_eye:

**Comment by jeckodevelopment** [comment]
@MATsxm ...  what???

**Comment by mbabker** [comment]
NOT ANOTHER ONE DANGIT¡!¡

**Comment by mbabker** [comment]
Closing.  Everyone's updated except the forum so for me that's good enough (knowing full well the forum isn't running the "pure" template and has its own issues with using it thanks to the phpBB styling).

**Comment by ooffick** [comment]
Added the new menu and footer for the forum. Sorry about the delay.
