### ISSUE TITLE
[jshow] Arrows of the recently added are not working

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#513]
On the front page, recently added module, it seems clicking on the arrows has not effect, can't scroll.
@sebastienlapoux, @oliviernolbert, could you have a look to this?
Thank you.

**Comment by sebastienlapoux** [comment]
already on it...

**Comment by oliviernolbert** [comment]
Should now be ok.

**Comment by Sandra97** [comment]
I confirm it now works. 
Closing this issue.
Re-open of needed.
