### ISSUE TITLE
[jshop] Books Store publishing infos

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#514]
![image](https://cloud.githubusercontent.com/assets/2596554/18096818/d8969366-6edb-11e6-84be-a77d01501611.png)

Page: https://community.joomla.org/books.html

Any reason to show this info?

**Comment by jeckodevelopment** [comment]
@MATsxm sorry, i wrongly removed the label!!!!

**Comment by brianteeman** [comment]
I've fixed this

**Comment by zero-24** [comment]
we have still: 
![image](https://cloud.githubusercontent.com/assets/2596554/18101508/36fb5618-6eef-11e6-9581-f9de44f1d531.png)

**Comment by zero-24** [comment]
Gone .Thanks :+1:
