### ISSUE TITLE
[jshop] FAQ (select the sales team)

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#515]
I some FAQ answears you to the user to `select the sales team`

```
If the item is faulty please use the contact form and select the sales team.
```

There is no select for a sales team just `sales questions`

https://community.joomla.org/shop-faq.html

**Comment by mikeveeckmans** [comment]
This Will be solved by referring to the helpdesk

Sent from my iPhone

On 30 Aug 2016, at 20:07, zero-24 <notifications@github.com<mailto:notifications@github.com>> wrote:


I some FAQ answears you to the user to select the sales team

If the item is faulty please use the contact form and select the sales team.


There is no select for a sales team just sales questions

-
