### ISSUE TITLE
[jshop] Add to the cart is open just for a few secconds

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#518]
- Go to https://community.joomla.org/the-joomla-shop/product/must-have-t-shirt.html
- klick on `Add to cart`
- wait just one or two secconds (without clicking anything)
- the popup is gone without any action by the user

**Comment by brianteeman** [comment]
Thats the intended behaviour in hikashop afaict

**Comment by mikeveeckmans** [comment]
That is indeed the intended behaviour.
