### ISSUE TITLE
[jrepo] Add a 'report an issue' link to the footer

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-websites#52]
Add a 'report an issue' link to the footer, like on the JDocs
maybe you should see with @mbabker coz I don't know how it works exactly ;)

**Comment by mbabker** [comment]
It's built into the base template already (see #7), pending feedback on Rochen link (see #26) before an update is issued to all admins so these things can be taken care of in one quick action.

**Comment by MAT978** [comment]
yup!
should have checked before
