### ISSUE TITLE
[jshop] Where is the helpdesk the contact form is pointing too?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#520]
https://community.joomla.org/shop-contact.html?view=form

Where is the helpdesk if I'm logged in?

![image](https://cloud.githubusercontent.com/assets/2596554/18097584/aaf3c50c-6ede-11e6-9884-030260d223b0.png)

Under `My Account` (where the link sends me) is also no helpdesk:

![image](https://cloud.githubusercontent.com/assets/2596554/18097609/c7ef9316-6ede-11e6-8dec-7ff0786109a8.png)

Or I'm missing something?

**Comment by mikeveeckmans** [comment]
You're not missing it, it's not enabled for public yet

Sent from my iPhone

On 30 Aug 2016, at 18:23, zero-24 <notifications@github.com<mailto:notifications@github.com>> wrote:


https://community.joomla.org/shop-contact.html?view=form

Where is the helpdesk if I'm logged in?

[image]<https://cloud.githubusercontent.com/assets/2596554/18097584/aaf3c50c-6ede-11e6-9884-030260d223b0.png>

Under My Account (where the link sends me) is also no helpdesk:

[image]<https://cloud.githubusercontent.com/assets/2596554/18097609/c7ef9316-6ede-11e6-8dec-7ff0786109a8.png>

Or I'm missing something?

-

**Comment by zero-24** [comment]
So we can close here as it is currently expected?
