### ISSUE TITLE
[jshop] I have got an error message after the first next step

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#522]
![image](https://cloud.githubusercontent.com/assets/2596554/18097748/887f01c0-6edf-11e6-8a6d-588a4a891e72.png)

and after clicking the button i got the same error agian:
![image](https://cloud.githubusercontent.com/assets/2596554/18097786/a32fe052-6edf-11e6-9110-fa6548468698.png)

PS. I have added dummy adress etc. maybe that is the reason?

**Comment by zero-24** [comment]
There is also no `X` to close that popup :smile:

**Comment by brianteeman** [comment]
I havent seen that error in my tests
@mikeveeckmans any idea what error 1211 is?

**Comment by mikeveeckmans** [comment]
Don't use dummy addresses please, the API is checking the address in real time

Sent from my iPhone

On 30 Aug 2016, at 20:03, Brian Teeman <notifications@github.com<mailto:notifications@github.com>> wrote:


I havent seen that error in my tests
@mikeveeckmans<https://github.com/mikeveeckmans> any idea what error 1211 is?

-

**Comment by zero-24** [comment]
I have done it just with my `real address` and it works. Do we have any change to show a better error than this? If not we can close here as expected behavior ;)

**Comment by mikeveeckmans** [comment]
the error is generated by the API :-/  I have to check with them to see if we can have it changed
