### ISSUE TITLE
[jshop] Why do we need a Address 2 field?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#523]
On checkout we go ask to add a optional Address 2 field but why do we need that? The normal Address field has no limit i have seen that could be a problem or i miss something?

![image](https://cloud.githubusercontent.com/assets/2596554/18097940/5e32448a-6ee0-11e6-99a2-64b61cb9c487.png)

**Comment by jeckodevelopment** [comment]
it's a common practice have an address 2 field, in order to allow people to write further info

**Comment by zero-24** [comment]
ok :smile: Maybe we can change the name than to `Additional Address` or `More Address` something similiar?

**Comment by mbabker** [comment]
Most shipping forms use Address and Address 2 as the labels (or "Address (cont.)").  It's a pretty standard convention.

**Comment by zero-24** [comment]
Than i think `Address (cont.)` much better :smile:  Just my personal opinion

**Comment by brianteeman** [comment]
It was me that added it. My own address is on two lines so I needed it ;)

**Comment by Sandra97** [comment]
Mine too so I need them

**Comment by zero-24** [comment]
ok. But we can rename it to `Address (cont.)`? If not just close ;)

**Comment by Hils** [comment]
Is it normal to have the telephone number in the middle of the address? ...and I am assuming that Country & State will change location on the form and State will change to county if one selects UK as the country (or England depending on the shop set up).

**Comment by brianteeman** [comment]
@zero-24 its a fairly standard format

@Hils When the shipping API creates the shipping label it formats it in the order required.

**Comment by Hils** [comment]
really not wanting to be picky but that means the customer puts it in in the wrong order & leaves the api to sort it all out? Seems the long way round!

**Comment by brianteeman** [comment]
I have moved telephone to the end
I have removed the required field for it

**Comment by brianteeman** [comment]
> and I am assuming that Country & State will change location on the form and State will change to county if one selects UK as the country (or England depending on the shop set up).

It doesnt change the label but the content is indeed county

**Comment by Hils** [comment]
thank you Brian :)

**Comment by brianteeman** [comment]
Can this one be closed now?

**Comment by mikeveeckmans** [comment]
Don't worry about this, I'll check when back at home

Sent from my iPhone

On 30 Aug 2016, at 21:58, Hils <notifications@github.com<mailto:notifications@github.com>> wrote:


really not wanting to be picky but that means the customer puts it in in the wrong order & leaves the api to sort it all out? Seems the long way round!

-

**Comment by Hils** [comment]
Brian has sorted it Mike

**Comment by mikeveeckmans** [comment]
Thank you @brianteeman
