### ISSUE TITLE
[jshop] My Carts list two cols without function?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#524]
For me it looks like they have no function? Or I'm missing something?

![image](https://cloud.githubusercontent.com/assets/2596554/18098088/e8fd5b22-6ee0-11e6-9cbd-15c22619b9f5.png)

**Comment by brianteeman** [comment]
Nope - i cant see what they are for either

**Comment by mikeveeckmans** [comment]
This is when you have multiple carts, disabling the function at the moment. 
Fixed
