### ISSUE TITLE
[jshop] Joomlers Showcase

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#525]
![image](https://cloud.githubusercontent.com/assets/2596554/18098176/630688b2-6ee1-11e6-902c-7ea6a63a17ee.png)

On the menü we say `Joomlars' Showcase` on the Text we use it without `'` I don't speak english native but  i think we should use it consistent with or without `'`?

**Comment by zero-24** [comment]
The `Agree the terms button` looks missplaced?

**Comment by zero-24** [comment]
I'm not sure about the stars on the contact for we use smal red * here bigger blue stars?

![image](https://cloud.githubusercontent.com/assets/2596554/18098402/5c6a1748-6ee2-11e6-999b-b69c4ea4963d.png)

Do we explain the stars are required? we don't do that on the contact form too?

**Comment by mikeveeckmans** [comment]
@Joomv  could you have a look at the "The Agree the terms button looks missplaced?" please? Thank you.

**Comment by mikeveeckmans** [comment]
Thank you @Joomv !!!

**Comment by zero-24** [comment]
Thanks 👍
