### ISSUE TITLE
[jshop] login redirect to the shop?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#526]
I'm not sure if that is something you want? But why not set up a plugin that redirects the shop users (i expect them to have a spezial usergroup or similiar) to the shop instead of the profile?

**Comment by mbabker** [comment]
IMO more complicated than it's worth.  How do you cope with admin users logging into the frontend from different source pages as an example?

It's a consequence of having a single site with a lot of functionality (training, shop, helpdesk, soon to be events, etc.).
