### ISSUE TITLE
[jshop] remove text-decoration: underline; on the plus button :focus

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#527]
![image](https://cloud.githubusercontent.com/assets/2596554/18099066/276e5f4c-6ee5-11e6-9404-0304a9a633de.png)

If you hit the plus button we got `text-decoration: underline;` is this expected? It looks like this comes from the global CSS shipd with the template.

**Comment by mikeveeckmans** [comment]
Mmmm haven't seen it yet, have to check it

Sent from my iPhone

On 30 Aug 2016, at 19:11, zero-24 <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/2596554/18099066/276e5f4c-6ee5-11e6-9404-0304a9a633de.png>

If you hit the plus button we got text-decoration: underline; is this expected? It looks like this comes from the global CSS shipd with the template.

-

**Comment by zero-24** [comment]
Let me know if you need help to reproduce it.

**Comment by mikeveeckmans** [comment]
I can reproduce it, but i can't find a solution , as text decoration is already set to none... 
Let me investigate a bit further

**Comment by mikeveeckmans** [comment]
ok got it ;-)

**Comment by mikeveeckmans** [comment]
Thank you @Joomv for fixing

**Comment by zero-24** [comment]
Thanks :smile:
