### ISSUE TITLE
[jshop] add to cart looks not so nice on a phone

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#528]
![wp_ss_20160830_0002](https://cloud.githubusercontent.com/assets/2596554/18099299/2310dfc8-6ee6-11e6-90aa-85e9aea5584e.png)
Maybe we can move it a bit?

**Comment by mikeveeckmans** [comment]
What os and browser are you using?

Sent from my iPhone

On 30 Aug 2016, at 19:15, zero-24 <notifications@github.com<mailto:notifications@github.com>> wrote:


[wp_ss_20160830_0002]<https://cloud.githubusercontent.com/assets/2596554/18099299/2310dfc8-6ee6-11e6-90aa-85e9aea5584e.png>
Maybe we can move it a bit?

-

**Comment by zero-24** [comment]
IE edge & WP10 ;)

**Comment by mikeveeckmans** [comment]
Get a real phone ;) just kidding... I'll check

**Comment by zero-24** [comment]
I'm sure that can be reproduced with a other phone too ;) Edge is not a IE anymore ;)

**Comment by mikeveeckmans** [comment]
could you retest please?

**Comment by zero-24** [comment]
Hmm i cant see a difference

![wp_ss_20160901_0001](https://cloud.githubusercontent.com/assets/2596554/18172946/e61ec890-7067-11e6-96e2-d07522a1c75a.png)

**Comment by mikeveeckmans** [comment]
Sorry, didn't save, please try again.

**Comment by zero-24** [comment]
Thanks works great :smile: :+1:
