### ISSUE TITLE
[jshop] There is a big free place after the books iframe is that expected?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#529]
![image](https://cloud.githubusercontent.com/assets/2596554/18099420/bbefc2cc-6ee6-11e6-93fe-330f8ad279cf.png)

https://community.joomla.org/books.html

**Comment by mikeveeckmans** [comment]
This is a iframe from Amazon , will be changed

Sent from my iPhone

On 30 Aug 2016, at 19:26, zero-24 <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/2596554/18099420/bbefc2cc-6ee6-11e6-93fe-330f8ad279cf.png>

https://community.joomla.org/books.html

-

**Comment by zero-24** [comment]
Thanks

**Comment by brianteeman** [comment]
Sorry i broke this 
I tried to fix it but with my permissions it strips the iframe . 

Sorry Someone else will have to fix your bug and my attempt at fixing it

**Comment by brianteeman** [comment]
I've disabled this for now. We're going to look at some other options for the books as an iframe isnt working correctly.

**Comment by brianteeman** [comment]
This issue can be closed

**Comment by zero-24** [comment]
Done thanks.

**Comment by mikeveeckmans** [comment]
Just a follow up, the link for the books will be going to an external service as we cannot provide this service ourself without big investment.

**Comment by brianteeman** [comment]
@mikeveeckmans see comments in glip
