### ISSUE TITLE
[jrepo] Table on mobile devices is broken 

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-websites#53]
So I can't seem to add screenshots from a mobile (thanks GitHub!) but if you go to the technical requirements page on a mobile (I'm using chrome for iPhone specifically) the table is completely broke

**Comment by MAT978** [comment]
What site @wilsonge?
repo?

**Comment by Sandra97** [comment]
Yes, known issue :wink: 
We have several questions about this page: keeping it on j.org, redirecting it to the JDocs page or embedding the JDocs page into the j.org page, if doable
The thing is that it depends more on a choice about a "content" issue. The team in charge of the content will have to take a decision about this. If it's decided to keep it like it is currently, then I'll do the CSS.

**Comment by mbabker** [comment]
It'd probably help to put the `More information` columns in a `hidden-phone` class, at least then it isn't as bad.

**Comment by Sandra97** [comment]
Yes, it helps. Hidden-phone class added. Display is now ok.

**Comment by Sandra97** [comment]
I close this issue. You can open it again if needed.
