### ISSUE TITLE
[jcomm] Dummy banner under my profile?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#531]
I'm not sure which site it is but i got a dummy banner under my profile ;)

![image](https://cloud.githubusercontent.com/assets/2596554/18099647/ceae3a28-6ee7-11e6-91f7-79f7c53f7f57.png)

**Comment by Joomv** [comment]
Because you're logged in under a user group that is in the "Special" group.  A normal visitor won't see these.  They are placeholders whilst we work out ad placements.

**Comment by zero-24** [comment]
Ok thanks for checking.
