### ISSUE TITLE
[jshop] Redirect after the payment

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#535]
After i have add all correct data to buy a t-shirt i got redirected to a clean page.

![image](https://cloud.githubusercontent.com/assets/2596554/18120565/91290e0c-6f60-11e6-810d-f96d86b5d32b.png)

maybe we can / should redirect them to the main shop site?

**Comment by mikeveeckmans** [comment]
Can you tell me what URL you are forwarded to ?

**Comment by zero-24** [comment]
This is the URL i got redirected to:

https://community.joomla.org/index.php?option=com_hikashop&ctrl=checkout&task=after_end&order_id=28&Itemid=363

**Comment by mikeveeckmans** [comment]
looking into it

**Comment by mikeveeckmans** [comment]
@zero-24 this should be fixed , could you retest ?

**Comment by zero-24** [comment]
works now. Thanks :+1:

**Comment by mikeveeckmans** [comment]
Thanks for testing
