### ISSUE TITLE
[jshop] FAQ / FAQs

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#536]
Same as https://github.com/joomla/joomla-websites/issues/492 for the Shop. We use currently FAQ in the shop.

![image](https://cloud.githubusercontent.com/assets/2596554/18121660/ed593c7e-6f65-11e6-9751-2ac608e367b6.png)

**Comment by mikeveeckmans** [comment]
Menu already changed 
Imagery will follow

**Comment by mikeveeckmans** [comment]
@designbengel can you share the psd of the FAQ please ? thank you

**Comment by designbengel** [comment]
[joomla_shop_images.ai.zip](https://github.com/joomla/joomla-websites/files/467131/joomla_shop_images.ai.zip)

**Comment by mikeveeckmans** [comment]
fixed
