### ISSUE TITLE
adverts [jshow] 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#537]
Is it right to have a display of 'other' websites in such a prominent position on the site without the word 'Advertisements' at the top of the module? Screenie from my laptop.

<img width="789" alt="showcase" src="https://cloud.githubusercontent.com/assets/736887/18121864/86d371a6-6f5e-11e6-8c1a-9d588218e6a2.png">

**Comment by sebastienlapoux** [comment]
Thanks Hils. 
I don't know
Without notification on Advert http://magazine.joomla.org/ , http://extensions.joomla.org/ 
With a notification http://resources.joomla.org/en/

Please what must be done?

**Comment by Hils** [comment]
Hello Sebastien.

If we have to have advertising (and we do as it generates most of our income) and...
if we have to give the best 'action area' of our site away...
I think a small, neat word saying they are advertisements isn't detrimental to the rest of the page - example:
<img width="733" alt="golden" src="https://cloud.githubusercontent.com/assets/736887/18160989/d5aa9a74-7027-11e6-96f1-4e5b27c37f91.png">

Good work Sebastien! Thank you.

**Comment by sebastienlapoux** [comment]
Hello Hils,
Thank you! We will follow your recommandation. Thanks again.

**Comment by sebastienlapoux** [comment]
Hi Hils,
Added.
Thanks again.
