### ISSUE TITLE
[jshow] SEO

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#539]
If I'm right, it seems the same meta description is used throughout the website: 

> The Joomla Community Showcase is a collection of sites that show off the power and beauty of Joomla

As far as possible, each page should have a custom meta description.

@oliviernolbert, @sebastienlapoux, thanks to have a look at this.

**Comment by sebastienlapoux** [comment]
@Sandra97, for site page meta description is currently set with description of the site and keyword with category and tags assigned to the site.
Thanks to check and close the issue if ok for you.

**Comment by Sandra97** [comment]
Checked this. 
Regarding the browser title of the detail page view, it's just the title of the presented website, so for example "Lazarex". Could you at least add before it the title of the website?
And for the meta desciption, well, they are really long and contains HTML code like br, not sure it's a good thing (and for the keywords, well, I don't use them anymore for a long time).

**Comment by sebastienlapoux** [comment]
Like you know Sandra, in any case all this is not very useful about SEO... it's more about information displayed on result page of search engine (so title and description) and the description if not here is taken into the page.

Meta title is currently including Site name too. Not before but after. Because to have all pages having same title into your navigator tab is boring and not useful.
We will delete html code from description.

**Comment by mbabker** [comment]
> not very useful about SEO... it's more about information displayed on result page of search engine

Hmm, I thought SEO stood for **Search Engine** Optimization?

**Comment by sebastienlapoux** [comment]
@mbabker :-), I made the difference about information using by the search engine algorithm -> commonly it's more the purpose of SEO (increase your visibility), than about information using just to be displayed such as meta description. It's just a point of view / arbitrary. Of course you can say it's about SEO too because displayed on result page. But I will answer you not really because it's not a requirement, the search engine will get alone a description (if nice html structure).

**Comment by sebastienlapoux** [comment]
@Sandra97 html code deleted from description.
Thanks to close this issue.

**Comment by Sandra97** [comment]
Title is important for SEO, Meta Description is important too but in a different way as it' important more for the users than for SEO reasons. 
Honestly, if if Google will only displays part of the description, I don't think Google will be really "happy" with a Meta Description like this: 
> Lazarex Cancer Foundation, where “IT’S ABOUT LIVING.” =========================================  At Lazarex Cancer Foundation we improve the outcome of cancer care, giving hope, dignity and life to end stage cancer patients and the medically underserved by providing assistance with costs for FDA clinical trial participation, identification of clinical trial options, community outreach and education.  We provide resources for cancer patients who have been told they have no other options, but who are not yet done with their journey in life and refuse to give up.  * We help patients of all ages and walks of life, with all forms of cancer. * We help patients take advantage of medical breakthroughs today, because they may not have a tomorrow. * We believe that the size of a patient's checkbook should not stand between them and the choices they make or the treatments they need. * We present clinical trials as an alternative to hospice care for those who want to remain engaged in their fight against cancer.

**Comment by sebastienlapoux** [comment]
Thanks Sandra.
Agree to cut the description about 150 characters. Ok for you? Do you see another point?

**Comment by Sandra97** [comment]
Yes, ok. last point regarding this title/meta topic: 
Do you have a way to remove the "=====" in order to display a clean description in Google results?

**Comment by sebastienlapoux** [comment]
There is no title/meta topic, only a description field. We will removed characters +_= . Do you think about other characters?

**Comment by Sandra97** [comment]
Yep: les guillemets et astérisques ;) 
(when I was saying title/meta topic it was just to mention it was my last point about this question of description tag and browser title -which has been discussed in another issue)

**Comment by sebastienlapoux** [comment]
@Sandra97 thanks to check again. https://showcase.joomla.org/new/browse-sites/16359.html

**Comment by Sandra97** [comment]
Better now, I confirm.
Closing this issue.
Re-open if needed.
