### ISSUE TITLE
[jshow] Small responsive issue

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#540]
On the frontpage, the "more" link is not well located for screens between 768px and 979px (tested on my Galaxy Tablet):
![index](https://cloud.githubusercontent.com/assets/4682328/18125238/6f70b20a-6f43-11e6-958f-587777dc13aa.png)
Thanks to have a look.

Ping @sebastienlapoux

**Comment by sebastienlapoux** [comment]
Thanks to check again.
* thanks to delete your navigator cache before to test

**Comment by Sandra97** [comment]
Display is now ok.
Closing this issue.
Re-open if needed.
