### ISSUE TITLE
[jshow] Responsive display of tags and rating

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#541]
For screens under 768px, the alignment of tags and ratings could be improved (it seems the overrides of span6 seems to break the rating display):
![index](https://cloud.githubusercontent.com/assets/4682328/18125703/aacfa6ba-6f45-11e6-9f37-6265f5e7ce00.png)

@oliviernolbert, @sebastienlapoux, could you give a look? Thanks.

**Comment by sebastienlapoux** [comment]
Hi Sandra,
Thanks to check again.
* thanks to delete your navigator cache before to test

**Comment by Sandra97** [comment]
Hi Sébastien, 
I confirm the alignment is now ok.
Closing this issue.
Re-open if needed.

**Comment by Sandra97** [comment]
@sebastienlapoux, seems the rating is center align on screen up to 767px and the others are left align. Is this intentional?
If not, just add in your media queries for screens up to 767px this: 
```
.row-fluid .span3-12 {
  width: auto;
} 
```
It should do the job and center align them all.
