### ISSUE TITLE
[jdev] Development status out of date

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#542]
https://developer.joomla.org/development-status.html

Current Release 3.6.0

and should we still list 2.5.28

**Comment by zero-24** [comment]
Maybe this can be moved to a automagic script? So no manual action needed there?

**Comment by zero-24** [comment]
>and should we still list 2.5.28

btw the download button points to https://www.joomla.org/download.html and there is no 2.5.x download anymore ;)

**Comment by sanderpotjer** [comment]
Have a look at https://github.com/n9iels/mod_joomlaversions, it is using the https://update.joomla.org/core/list.xml information to display the latest version. If changes are need I'm sure that @n9iels is happy to help :)

**Comment by n9iels** [comment]
I think we can show Joomla! 2.5 with the message it is deprecated without the download button.
The information of the last release can be displayed automatically. But there is no XML file about upcoming releases as far as I know?...

**Comment by zero-24** [comment]
>But there is no XML file about upcoming releases as far as I know?...

No. As it is a decision by the PLT to publish 3.6.4 or 3.7.0 etc i guess it is everytime a manual action needed. A XML file (on the e.g. the Dev or Org site) would allow to show that info on other sites e.g. the local joomla sites too.

**Comment by mbabker** [comment]
So instead of manually updating one webpage with every release we manually update one XML file.  I can't be the only one who chuckled at that.

**Comment by zero-24** [comment]
But if you update a xml everyone can use it. The website don't need to be manually updated than. Or you let the XML generated from the UI ;)

**Comment by mbabker** [comment]
That's exactly what the update system XML files are for.  There isn't much value in XML for projected future releases IMO.  And IMO it's overkill to install an extension to update one version number reference on one website.

**Comment by zero-24** [comment]
Maybe you know how it is implemented currently? Just a HTML Table? via a Editor?

**Comment by mbabker** [comment]
That page is just an article in the Joomla install.  FWIW I've fixed the current version number already.

95% of the content in the Joomla install on that domain that isn't the JoomlaCode archive is Joomla articles.  The rest of it is the old release notes pages and the Wiki activity charts and those are in our custom components.

**Comment by brianteeman** [comment]
Thank you @mbabker for doing all that was needed to be done.

**Comment by zero-24** [comment]
Thanks.
