### ISSUE TITLE
[jshow] We have still a place with FAQ

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#543]
![image](https://cloud.githubusercontent.com/assets/2596554/18126692/a7f9ee00-6f7c-11e6-911a-d139f67804c0.png)

FAQ's in the Modul, Titel & URL but on the site i it still FAQ. see https://github.com/joomla/joomla-websites/issues/492

**Comment by sebastienlapoux** [comment]
Thanks you!
Fixed.

**Comment by MATsxm** [comment]
Thanks
Closing - reopen if needed

**Comment by MATsxm** [comment]
Thanks @zero-24 :stuck_out_tongue_winking_eye:
