### ISSUE TITLE
[jshow] Is there a automatism to remind that this site is still a Joomla site? Or can sites expire?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#544]
On the German Glip Chat we got the question for an automatism or expire date for an entry but I'm not sure if or how this should be implemented maybe someone can have a look here.

maybe there come a time that this site is not longer a Joomla site?

Thanks.

**Comment by jeckodevelopment** [comment]
Do you mean to show a message like: "This has been a Joomla! website from XXXX to YYYY" where XXXX and YYYY are the start and the end date?

**Comment by mbabker** [comment]
You can't automate checking if a site is still Joomla unless you're going to have a crawler in the JSD.

Having sites expire or require renewal would at least mandate listings be reviewed every so often, that's probably the furthest you could go with it though.

**Comment by zero-24** [comment]
e.g. or unpublish that site if that is not a Joomla site anymore (as the rules told use we can only have Joomla webseites there what makes sense) but if no one is checking that I'm sure with the time there will be sites that are not Joomla but Drupal or similiar.

**Comment by zero-24** [comment]
@mbabker with automate i mean a automate reminder to re-check that site. Not check if it is Joomla via a crawler.

**Comment by jeckodevelopment** [comment]
It's a task for the "Listing Team" of JSD

**Comment by mbabker** [comment]
Remind who, the JSD team or the listing owner?  I don't think a reminder system like that is going to work or be an efficient use of anyone's time.  Even with all the giveaways that something is a Joomla site, it's still pretty easy to build stuff using Joomla-isms in the HTML to fool crawlers or page viewers.  I honestly think you're better off programming the listings to require renewal after a given period of time and require the listing owner to at least confirm it's still valid.  No confirmation, it falls off the page.  Mix that with regular reporting features and it should be fine.

**Comment by jeckodevelopment** [comment]
A reporting feature could be good!

**Comment by zero-24** [comment]
>I honestly think you're better off programming the listings to require renewal after a given period of time and require the listing owner to at least confirm it's still valid. No confirmation, it falls off the page. Mix that with regular reporting features and it should be fine.

@mbabker that is exact the seccond idea with the expire date.

**Comment by brianteeman** [comment]
@jeckodevelopment the reporting feature exists
![tmjv](https://cloud.githubusercontent.com/assets/1296369/18129993/27c38242-6f85-11e6-82a0-ca59b1495304.png)

**Comment by HLeithner** [comment]
Expire per date with renewly mail would be better then waiting till some checks if its still a Joomla site or the same site.

Other thing is to force poster to add a confirmation file on the webhost like google hostmaster tools or SSL certificate verification. Normally when a site is recreated the old webhost will be deleted and a new replaces the old one without the file. But this would depend on a crawler.

**Comment by genr8r** [comment]
This functionality would also be beneficial for the Resources Directory. We do not yet have a policy for renewing existing approved listings. We have discussed it. An automated confirmation process would be a great addition for us.

**Comment by jeckodevelopment** [comment]
@genr8r i guess that is really difficult to have an automated verification process for JRD.

**Comment by genr8r** [comment]
Yes but even something similar to what is being discussed in the thread would be a start.  I know of a couple of JRD listings where the developer has closed up shop. So, even if there were an auto renewal sent to their email and we got no response we could unpublish and it would keep us closer to maintaining clean and relevant listings.

**Comment by zero-24** [comment]
@genr8r can you open than a issue for `[jrd]` As i guess you use a different system than the showcase and have different webmasters & install etc.

**Comment by jeckodevelopment** [comment]
JRD uses zoo

**Comment by brianteeman** [comment]
Oh well I guess that can't be helped

**Comment by genr8r** [comment]
Yes. sorry for any confusion.  I am the team lead/webmaster for the JRD.  I was jumping in on this in the event that the solution could be used for our purposes too.  DRY and all that.  :)  No need to open a JRD issue.  It is already on the radar for us.

**Comment by jeckodevelopment** [comment]
@brianteeman question for you.
I saw the report function and after the submission what does it happen? 
Do they use a ticket system as in JED or just an email to the team?

**Comment by brianteeman** [comment]
No idea. Better to ask someone on that team.

**Comment by AlisonAMG** [comment]
I would have no problem with being asked to return to confirm my listings say once per year.

**Comment by sebastienlapoux** [comment]
Thanks everybody.

@jeckodevelopment , currently JSD team is receiving an email notification to process the report from report manager
![reportmanager](https://cloud.githubusercontent.com/assets/13470265/18543378/d76e8074-7b2f-11e6-9be7-0a7840663cf5.png)
by editing the report, process it by sending an email answer
![reportedition](https://cloud.githubusercontent.com/assets/13470265/18543397/edff5ebc-7b2f-11e6-9b98-48871baee750.png)

This Report Application will be able to become a ticket system if needed in the feature.

About validation in long term of any site item, we're more on the way of @mbabker -> "renewal after a given period of time and require the listing owner to at least confirm it's still valid" .

Thanks!

**Comment by jeckodevelopment** [comment]
@sebastienlapoux very nice application. Maybe it could be useful for other com_jed based websites.

**Comment by zero-24** [comment]
So we can close here?
