### ISSUE TITLE
[jshow] Jump up icon break

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#546]
It is a bit tricky. :smile: 

go to the page: 
![image](https://cloud.githubusercontent.com/assets/2596554/18130995/7974a164-6f91-11e6-856a-40322fa3d213.png)

It works.

Scroll down:
![image](https://cloud.githubusercontent.com/assets/2596554/18131012/868f1212-6f91-11e6-93b8-e2599288e344.png)

It breaks.

F12 told me if it works:
![image](https://cloud.githubusercontent.com/assets/2596554/18131058/b084b0f4-6f91-11e6-9e21-0b6b3e3386bd.png)

and if not:
![image](https://cloud.githubusercontent.com/assets/2596554/18131096/d829768a-6f91-11e6-8eeb-82f579922a03.png)

**Comment by sebastienlapoux** [comment]
Hi,
Template totally changed. Thanks to try again.
* thanks to delete your navigator cache before to test

**Comment by zero-24** [comment]
Thanks @sebastienlapoux hmm it looks like there is now no `back to the top` button anymore :smile: Thanks!
