### ISSUE TITLE
[jdev] Integrate Nightly Builds into CMS install

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#548]
- [x] Create an article in the CMS install for the nightly builds
- [x] Create a plugin to parse the nightly build data from the upload directory
    - [x] Indicate the build time for the package (in case the Jenkins job doesn't run correctly for whatever reason each night)
    - [x] Indicate the commit hash the build is based on for a better point of reference
    - [x] Visually split the packages by branch
- [x] Remove the bleeding edge section, for this page there isn't any real benefit

**Comment by jeckodevelopment** [comment]
@mbabker let me know if I can help with the article

**Comment by mbabker** [comment]
If someone wants to write content for the page it'd be appreciated.  I basically was going to take the text that's already on https://developer.joomla.org/cms-packages/ and use that as the starting point.  Which honestly is almost nothing but it's enough to start a page from.

**Comment by jeckodevelopment** [comment]
Let me try do something

**Comment by jeckodevelopment** [comment]
Proposal

> From this page you can download "development" version of Joomla! that are daily generated from the CMS code that is currently in development.
These builds are intended for testing purposes only and may be unstable. 
Generally, nightly builds contain fixes and new features not yet available in the Stable Releases.
If you want to help us testing Joomla! and ensure painless public releases, just download the desired build and have fun!
If you encounter an issue, please check wheter it has been already reported on https://github.com/joomla/joomla-cms/issues otherwise, just open an issue and let us know where we're going wrong.
Thank you for the help.

**Comment by mbabker** [comment]
This is a working stub; neither the content nor code live anywhere outside my laptop yet so don't go looking for it.

<img width="1212" alt="screen shot 2016-09-02 at 7 24 29 pm" src="https://cloud.githubusercontent.com/assets/368545/18221446/fba4b7b6-7142-11e6-8fd3-180f8727975f.png">

If anyone wants to make revisions on the content, here's the article's HTML:

```html
<p class="lead">Help test the latest Joomla! code.</p>
<div class="alert alert-warning"><strong>Warning!</strong> These builds are intended for testing purposes only and should never be used on production websites.</div>
<p>The nightly builds are snapshots of the <a href="https://github.com/joomla-joomla-cms">development activity</a> for upcoming Joomla! releases and include new features and bug fixes scheduled for these releases. These releases are made available to make it easier for users to test their websites and extensions for potential issues with an upcoming release or to test new features and provide feedback on ways to improve them before being released to the Joomla! community.</p>
<p>As these builds are snapshots of the latest code, it is more likely you may encounter an issue compared to the stable releases. If you have encountered an issue, please check <a href="https://issues.joomla.org">our issue tracker</a> to see if it has already been reported; if a report hasn't been made, please report it so our community members can review the issue and make any needed fixes.</p>
<p>{nightlybuilds}</p>
```

**Comment by zero-24** [comment]
Looks cool :+1:

**Comment by mbabker** [comment]
https://developer.joomla.org/nightly-builds.html
https://github.com/joomla-projects/plg_content_nightlybuilds

I've still got to tweak the Jenkins job to get it to add the additional data seen in the above screenshot (right now the page is using the fallbacks for when it doesn't exist for whatever reason) but it's all there now.

**Comment by zero-24** [comment]
There is a typo in the development activity link currently it gives a 404 https://github.com/joomla-joomla-cms

**Comment by mbabker** [comment]
Fixed.

**Comment by zero-24** [comment]
What do you think about a redirect from https://developer.joomla.org/cms-packages/ to the new page?

**Comment by mbabker** [comment]
I'm trying but Joomla's redirect manager won't cooperate with me.

**Comment by mbabker** [comment]
OK, got it.  There was an entry in the trash.  Should be redirected now.

**Comment by zero-24** [comment]
:+1:

**Comment by mbabker** [comment]
I'll leave this open through the weekend for feedback, otherwise this is complete.

**Comment by zero-24** [comment]
can we make the  `please report` a link to create a new issue on the Tracker or Github?

**Comment by zero-24** [comment]
maybe we can add it as button to this page too? https://developer.joomla.org/development-status.html

**Comment by mbabker** [comment]
I purposefully didn't link direct to the report form because a few words earlier we link to the tracker with instructions to first search for an issue.  I'd rather not direct link to the report form as that encourages folks to report without at least glancing at the open issue list.

**Comment by zero-24** [comment]
ok. it was just a random idea :smile:
