### ISSUE TITLE
[jrepo] social media icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#55]
The social media icons look unbalanced to me. The youtube icon is not square like the others and the twitter icon is in a completely different style

**Comment by MAT978** [comment]
HA!
+1

**Comment by Sandra97** [comment]
I'll manage it tomorrow (if we have electricity and internet and no hurricane :wink: )

**Comment by mbabker** [comment]
The full iconset that we have available right now is at http://developer.joomla.org/icomoon/demo.html

I also have access to the IcoMoon app and the JSON resource to re-generate the font set with additional icons if there are more suitable options there.

**Comment by brianteeman** [comment]
So please use  icon-twitter2
Not sure what to suggest for youtube as they are both the wrong size

On 25 August 2015 at 23:18, Michael Babker <notifications@github.com> wrote:

> The full iconset that we have available right now is at
> http://developer.joomla.org/icomoon/demo.html
>
> I also have access to the IcoMoon app and the JSON resource to re-generate
> the font set with additional icons if there are more suitable options there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/55#issuecomment-134758266>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
There are two other YouTube icons available but I'm not sure if either of them are going to be any better.

![screen shot 2015-08-25 at 6 27 03 pm](https://cloud.githubusercontent.com/assets/368545/9481297/f642f976-4b56-11e5-8903-f1b30c7f5d4a.png)

**Comment by mbabker** [comment]
The footer is updated in the base template repo with this:

![screen shot 2015-08-26 at 10 57 17 pm](https://cloud.githubusercontent.com/assets/368545/9511553/e9d0cdc2-4c45-11e5-82a5-7a25e1e73a39.png)

I think this is good to go and will be rolled into the .org update as well as the other sites when the template update is pushed out.

**Comment by brianteeman** [comment]
Million times better. Thanks

**Comment by mikeveeckmans** [comment]
you tube icon missing ... http://www.screencast.com/t/aozDwuytwsS9

**Comment by brianteeman** [comment]
Sandra said that's resolved in the live template

**Comment by mbabker** [comment]
It's compiled in the updated template (the CSS updates aren't on the CDN yet, which is where the repo site is pulling from for the base template CSS and the fonts unless we turn debug mode on).

**Comment by MAT978** [comment]
@mikeveeckmans
please see above Mike's comment ;)

**Comment by mbabker** [comment]
Updated media is deployed to CDN, waiting (impatiently) for the fonts to refresh then this item can be marked complete.

**Comment by mbabker** [comment]
CDN media has yet to refresh, CSS in the .org site has an override to load the local fonts.  Consider this one closed out.
