### ISSUE TITLE
[jshow] My submitted site is now gone from my listing. 

### ISSUE THREAD

**Issue by AlisonAMG** [joomla/joomla-websites#550]
What the heck. The site I loaded is now gone. 

http://waynemallows.com is the URL for the site I posted.

**Comment by oliviernolbert** [comment]
Hi Alison,

The site should now be back in your listing. Sorry for the inconvenience.

Olivier

**Comment by AlisonAMG** [comment]
Thanks Oliver 

Is there an approval problem?

**Comment by oliviernolbert** [comment]
No, I just moderated and approved it!

Cheers,

Olivier

**Comment by AlisonAMG** [comment]
Awesome thanks. I'll get myself busy and add others also.

**Comment by MATsxm** [comment]
Thanks
Closed - reopen if needed
