### ISSUE TITLE
[jshop] display broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#552]
As of this morning the display is broken - see screenshot

![lwqc](https://cloud.githubusercontent.com/assets/1296369/18161620/8f108d3c-702a-11e6-942f-0cdf4354b60c.png)

**Comment by Sandra97** [comment]
It's due to line 34 of the custom.css remove it and the issue will be fixed.

**Comment by Joomv** [comment]
This css was from the original css in the shop, when I migrated it.
This will be the template upgrade.
I've removed that line.

**Comment by brianteeman** [comment]
All good now - thanks
