### ISSUE TITLE
[joomla.org]  Add joomla.com to top 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#554]
If we really want to promote joomla.com (it has the potential to bring a lot of revenue) then it would be better if we added a prominent link on **all** pages (see screenshot for an example)

Currently there is only a link on a few pages and a few sites

![po04](https://cloud.githubusercontent.com/assets/1296369/18162674/4bb849e4-702f-11e6-94da-2897c51ef644.png)

**Comment by mbabker** [comment]
Some feedback on this would be nice.  Initially I'm reluctant to support the link in that spot; something just doesn't feel right about a link to .com being a primary CTA on every page of every site.  I know full well we need to market .com much better but right now I'm leaning more toward this not being the "right" way to go about it.

**Comment by jeckodevelopment** [comment]
I guess that it could be better to have also the MWG opinion and vision about this.
Ping @mikeveeckmans

**Comment by mikeveeckmans** [comment]
At this point i don't fully support this, SG still has no full support channel for .com , i would like to see that first... Discussion about this is ongoing. 

But let's make it clear, this is MY personal point of view. will put it on MWG agenda for next week.
