### ISSUE TITLE
[japi] Refresh homepage

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#555]
Refresh/improve the API site homepage

**Comment by Sandra97** [comment]
If I can be of any help, don't hesitate.

**Comment by mbabker** [comment]
If anyone's got ideas, I'm all eyes since I can barely design my way out of a brown paper bag.

The only things I know for sure right now are:

1. It should probably be a little more clear WHAT the user is looking at
2. It's probably time to retire the link for the 2.5 API docs off the homepage (we can keep them indexed on Google for now, it'll still come up in search results that way at least)

**Comment by MATsxm** [comment]
I won't be able to help on content but if you need few `-ar` or `-et`*
I'm your guy 😉 
(* or other in my skills)
