### ISSUE TITLE
[jorg] Add JWC banner to the home page

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-websites#557]
Since we don't have the ad server completely set for the home page, I'm making this ticket instead.

We need the JWC banner added to the Joomla.org home page. I'm not sure where it can go, but based on the way back machine it was below "Look who's using Joomla!" and above the row of community and developer links.

This years banner is bigger than 2014 but small than 2015 (last years was massive). Let me know if it doesn't work or you need a different size. Would love this to go up ASAP as early bird is expiring very soon.

The banner will link to this page:
https://conference.joomla.org/buy-your-ticket

![728x210-joomla-org](https://cloud.githubusercontent.com/assets/10532158/18180890/7c2187f2-704e-11e6-9c99-b9d87f453f76.jpg)

Thanks!

**Comment by Sandra97** [comment]
@brianpeat, banner added in the same position as usual.
Closing this issue.
Re-open if needed.

**Comment by zero-24** [comment]
@Sandra97 did you push the wrong button?

**Comment by brianpeat** [comment]
Looks good to me. Thanks!

**Comment by Sandra97** [comment]
@zero-24 What did I do? Just after adding the banner & closing this issue, we had an electricity outage (is this a coincidence?)

**Comment by Sandra97** [comment]
Ah ah ah, got it! Closing it now

**Comment by brianpeat** [comment]
So, the JWC team requested we swap out that banner with one that has a border around it. Can someone do that for me? Please and thank you :)
![728x210-joomla-org](https://cloud.githubusercontent.com/assets/10532158/18206166/0e6333f8-70eb-11e6-8ad2-bbf60635f802.jpg)

**Comment by MATsxm** [comment]
@sandra will but this afternoon

**Comment by MATsxm** [comment]
Should be ok.... 
reopen if needed
