### ISSUE TITLE
[jshop] Shipping method is missing on the site

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#559]
This is a ship of the order details where the shipping method is missing:

![image](https://cloud.githubusercontent.com/assets/2596554/18181963/1abe802e-708e-11e6-8379-3d1f0b6f360b.png)

But in the mail the shipping method is there:
![image](https://cloud.githubusercontent.com/assets/2596554/18182009/4a3b6132-708e-11e6-8db5-045116e94b74.png)

**Comment by mikeveeckmans** [comment]
Looking into this, should be solved by tomorrow and good to launch then ...

**Comment by hikashop-nicolas** [comment]
Hi,

I found the solution. It comes from the fact that the BPost shipping plugin works in a particular way which wasn't done so far for other shipping plugins and that case wasn't handled for the display of the shipping method name of an order.
Add the code:
		if(is_numeric($id)){
			$class = hikashop_get('class.'.$this->type);
			$method = $class->get($id);
			$name = $this->type.'_name';
			if(!empty($method->$name))
				return $method->$name;
		}

before the line:
return '';
in the file administrator/components/com_hikashop/types/plugins.php and that will work.
We're gonna add the patch for next release of HikaShop.

**Comment by mikeveeckmans** [comment]
Works like a charm now ;-)
@hikashop-nicolas thank you !
@Joomv Thank you for editing !
