### ISSUE TITLE
[jrepo] No search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#56]
I dont see any search possibilities

**Comment by jessicadunbar** [comment]
Me either, I don't know who has access to edit the menu.

**Comment by mbabker** [comment]
Moved the search module to `position-0` (which is the search position used across other sites).

**Comment by MAT978** [comment]
Yurk ;)
@Sandra97 rectangle please

**Comment by Sandra97** [comment]
I'll adapt the design of the search button tomorrow.

**Comment by Sandra97** [comment]
Look of the search button is now ok.

**Comment by MAT978** [comment]
merci
