### ISSUE TITLE
[jvols] FAQ / FAQs

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#560]
Generally people write "FAQs" because it means "Frequently Asked Questions", in the plural form.
Actually jvols says "FAQ" but on the page it says `Frequently Asked Questions`

Similiar to https://github.com/joomla/joomla-websites/issues/492

![image](https://cloud.githubusercontent.com/assets/2596554/18184187/27911eba-7098-11e6-812e-071d074cdd8a.png)

**Comment by sanderpotjer** [comment]
Changed it. Looks like some bigger names need to do the same in that case https://www.whatsapp.com/faq/ https://www.microsoft.com/en-us/software-download/faq ;)

**Comment by zero-24** [comment]
Thanks just to have it consistent over the joomla.org sites ;)
