### ISSUE TITLE
[jorg] JWC Banner

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-websites#561]
Hi there,

I see that we have a banner on the home page of Joomla.org to promote the Joomla World Conference. **This is great.**

What would make it even better is if the banner were _above the fold_ on the home page. Since the JWC is one of the main events of the year for the Joomla project it would be good if we are giving it the most optimum exposure possible.

Can we have the JWC banner ad moved to a position above the fold on the home page?

**Comment by Sandra97** [comment]
Hi Joe, 
I can move the banner above the "Look who's using Joomla!" module but not above the video/announcements part. We're here on joomla.org site so we should first promote Joomla, not an event.
I can also propose to add a small banner in the side bar of some inner pages to give more visibility to JWC.

**Comment by MATsxm** [comment]
+1
I see that the border is already better but IMHO should be #c17400 (even if I'm not a designer)

**Comment by Sandra97** [comment]
Border changed again to a light #c17400 and the 300x250px banner is now displayed in the sidebar on the inner pages.

**Comment by Sandra97** [comment]
![index](https://cloud.githubusercontent.com/assets/4682328/18213817/08b5bd0e-7118-11e6-8d2a-6741b8b21a8a.png)

**Comment by jeckodevelopment** [comment]
Good job Sandra

**Comment by Sandra97** [comment]
Thanks Luca :)

**Comment by Sandra97** [comment]
JWC banners displayed on joomla.org.
Closing this issue.
Re-open if needed.
