### ISSUE TITLE
[jdev] Review Volunteer Activity Area

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#562]
https://developer.joomla.org/tracker/volunteer-activity.html and the links under the "Volunteer Activity" sub-menu on the side.

Most of this content has been migrated to the issue tracker (all except the Wiki chart).  Redirects for those pages would probably be good?

**Comment by jeckodevelopment** [comment]
I agree on Redirects

**Comment by Sandra97** [comment]
I agree too.

**Comment by MATsxm** [comment]
4 against the world I guess it's enough for a :+1:

**Comment by Sandra97** [comment]
Let's do it!

**Comment by mbabker** [comment]
JDN Address | Issue Tracker Address
------------- | -------------
https://developer.joomla.org/activity-by-contributor.html | https://issues.joomla.org/activity/user/joomla-cms
https://developer.joomla.org/total-activity-by-time-period.html | https://issues.joomla.org/activity/total/joomla-cms
https://developer.joomla.org/total-open-issues-by-time-period.html | N/A (we aren't snapshotting the tracker state to collect this data)
N/A (there wasn't a snapshot chart showing current overall state) | https://issues.joomla.org/activity/snapshot/joomla-cms
https://developer.joomla.org/open-closed-issues.html | https://issues.joomla.org/activity/project/joomla-cms

**Comment by Sandra97** [comment]
Linked changed. Please check to be sure I did it correctly and didn't miss something.

**Comment by mbabker** [comment]
Looks fine.  Can we redirect the old URLs?  Right now they're going to a categories view page and it doesn't look all that great.

**Comment by Sandra97** [comment]
We can!

**Comment by Sandra97** [comment]
And I did ;)
