### ISSUE TITLE
[jconf] Inconsistent date for early birds

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#564]
In this news, the date in which the price will grow is inconsistent:
first time it says on September 1st, two lines below it says September 2nd.
So, when?

![1stor2nd](https://cloud.githubusercontent.com/assets/733133/18231599/d719b9e2-72bd-11e6-97cb-7ae4985d3f81.PNG)

Furthermore, there's a typo:
`September 2st`

**Comment by jeckodevelopment** [comment]
@brianpeat can you look at this?

**Comment by brianpeat** [comment]
They changed the date, but I think the team is working on it. If this was on the News page on the conference site, then they've already taken it down.

**Comment by jeckodevelopment** [comment]
It was in the news, can't find it anymore. Thank you
