### ISSUE TITLE
[jrd] Missing ! in the title

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#566]
If you look at the title in the browser it says `Joomla Resources Directory` instead of `Joomla! Resources Directory`
http://resources.joomla.org/en/

![jrdtitle](https://cloud.githubusercontent.com/assets/733133/18245446/8201846e-7365-11e6-862b-dcfd99554142.PNG)

**Comment by MATsxm** [comment]
+1

**Comment by genr8r** [comment]
Full tm satisfaction.

**Comment by genr8r** [comment]
Full tm satisfaction.

**Comment by jeckodevelopment** [comment]
Thank you @genr8r
