### ISSUE TITLE
[jrd] Missing ! in categories

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#567]
In the JRD homepage: http://resources.joomla.org/en/ 

Some categories don't have the bang after the word Joomla!
`Joomla! Security` , `Joomla! Learning Partner`

![jrdcat1](https://cloud.githubusercontent.com/assets/733133/18245533/0a51aee8-7366-11e6-9b2f-2500c019df38.PNG)

![jrdcat2](https://cloud.githubusercontent.com/assets/733133/18245573/46f9b714-7366-11e6-8e14-2e477b8fa2df.PNG)

![jrdcat3](https://cloud.githubusercontent.com/assets/733133/18245577/4c240dca-7366-11e6-9ff2-c3905a36fbcf.PNG)

**Comment by MATsxm** [comment]
+1

**Comment by genr8r** [comment]
bang, bang. done.

**Comment by jeckodevelopment** [comment]
Thank you @genr8r
