### ISSUE TITLE
[org] Internationalisation Menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#57]
The fairly obscure menu is even harder to find now with the globe icon being located even further away from anything. Either drop it or make it part of the menu - right now its a "hidden secret"

**Comment by jessicadunbar** [comment]
we don't have access to edit that menu. I'm not sure who handles that.

**Comment by mbabker** [comment]
That top menu is part of the CDN'd menu shared with other sites (volunteer portal, dev network, etc.).  Because the site doesn't use the 960px max width, things are spread out a lot here.  Maybe we put the header contents back in a 960px window and leave the body full width?

**Comment by Sandra97** [comment]
I'll see what I can do about this tomorrow.

**Comment by mbabker** [comment]
So in this screen shot this locks the header row widths to the max-width of the template viewports (so for my screen 1170px).  I purposefully grabbed this screen cap to show the body content expanding full width (as it does now) with the header narrowed down a bit to try and give an idea how it would look as a user scrolls.

![screen shot 2015-08-25 at 6 53 29 pm](https://cloud.githubusercontent.com/assets/368545/9481720/a7fde92a-4b5a-11e5-9799-1eb5b2acc770.png)

**Comment by Sandra97** [comment]
The body, as well as the header part, are both currently set with a max-width of 1920px. If I apply 1170px to the header part only, it does not look nice (my opinion) on large screen (and applying this width of  1 170px to the whole body is even worse and my brain does not accept this option).

**Comment by mbabker** [comment]
With the narrowed header back on .org, this specific issue is fixed.  Follow #64 for a global fix.
