### ISSUE TITLE
[jconf] Typo & TM in disclaimer

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#570]
Just a small typo in the disclaimer.
Now it says:

> © Joomla! World Conference 2016 is brought to you by a team of volunteers and the Joomla! Project. Joomla!® is the trademark of Open Source Matters, Inc. in the United States and other countries.

it should be:

> © Joomla! World Conference 2016 is brought to you by a team of volunteers and the Joomla! Project™. Joomla!® is a registered trademark of Open Source Matters, Inc. in the United States and other countries.

It should be "**a**" trademark, not "**the**" trademark. Furthermore it's a registered one.
And we need a ™ after the "Joomla! Project"

![jconftm](https://cloud.githubusercontent.com/assets/733133/18255368/6a601e30-73a9-11e6-8ebe-fbfb257716af.PNG)

**Comment by Sandra97** [comment]
As the Conference will occur in 5 days, I think we can close it as it won't be fixed.
Re-open if needed.
