### ISSUE TITLE
[jconf] TM compliance tips

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#571]
If you check the "**Convince your Boss**" document, there're some trademark mistakes.

https://conference.joomla.org/images/Convince-Your-Boss.pdf 

**Section 1.**
`people that make Joomla the world-class software` should be `Joomla!`

**Section 2.**
Title: `I’ll Connect With The People Who Make Joomla Happen` also here: `Joomla!`
`of Joomla that always` should be `Joomla!`
`With over 500 Joomla developers`  should be `Joomla!`

**Section 3.**
`next generation of Joomla is planned,`  should be `Joomla!`

**Section 4.**
`JWC brings the Joomla community together,`  should be `Joomla! Community`

**Section 5.**
`the global Joomla community means`  should be `Joomla! Community`
and then `Joomla! community for` `Joomla! Community for`

**Comment by MATsxm** [comment]
to be fair, I have of course noticed that the `!` had been added to the logo :smile: :wink: 
Great!

**Comment by jeckodevelopment** [comment]
I'm not sure if we have to use the ® the first time we say "Joomla! World Conference"

**Comment by MATsxm** [comment]
WHAT???? :rage:

**Comment by jeckodevelopment** [comment]
just joking :P

**Comment by mbabker** [comment]
@ronnikc Can someone on your team take a look at this (and other issues tagged for the conference site)?

**Comment by Sandra97** [comment]
As the Conference will occur in 5 days, I think we can close it, it won't be fixed.
Re-open if needed.
