### ISSUE TITLE
[jconf] Wrong link in a button

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#572]
If you go to https://conference.joomla.org/about 
the button: **Check out the team of volunteers** in the **Who is arranging JWC?** section has the following URL: `https://conference.joomla.org/about/team?lang=en` that includes the `?lang=en` parameter.
The correct link should be: `https://conference.joomla.org/about/team`

**Comment by Sandra97** [comment]
Issue is still here.

**Comment by JerryChr** [comment]
Fixed

**Comment by jeckodevelopment** [comment]
Thanks
