### ISSUE TITLE
[jconf] More about TM

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#573]
https://conference.joomla.org/call-for-speakers 

`Thank you for your interest in presenting at Joomla World Conference 2016!` -> "Joomla!"
`How to better utilize the built in features of Joomla` -> "Joomla!"
`How to master something that’s web related that can be applied to a Joomla site (like CSS, jQuery, plugins, php, etc).` -> Joomla!
`How to build a successful marketing site with Joomla` -> "Joomla!"
`Thinking outside the box - non-traditional ways to use Joomla and / or extensions.` -> "Joomla!"

**Comment by Sandra97** [comment]
As the call for speakers is closed, the page is not available anymore.
Closing this issue.
Re-open is needed.
