### ISSUE TITLE
[jconf] Wrong link on the anchors

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#574]
If you point your mouse over the **down arrow** below the "Tickets available now!" link, it links the following URL: 
`https://conference.joomla.org/component/reditem/reditem/categorydetail/11:buy-your-ticket?Itemid=193`

If you click on the arrow, you'll go down to the content of the page.

If you try to open the above mentioned URL it gives a test page (or something like that).

Why the anchor link has such URL?

**Comment by Sandra97** [comment]
It seems to have been fixed.
Closing this issue.
Re-open if needed.
