### ISSUE TITLE
[jconf] Missing ! in the title

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#575]
If you look at the title in the browser it says` Joomla World Conference` instead of `Joomla! World Conference`

https://conference.joomla.org/

![jwctitle](https://cloud.githubusercontent.com/assets/733133/18256703/3115405a-73b9-11e6-8e3b-9d26ffc53940.PNG)

**Comment by Sandra97** [comment]
Seems it has been fixed.
Closing this issue.
Re-open if needed.
