### ISSUE TITLE
[jconf] Low contrast for the top menu

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#576]
If you look at the JWC home page, the top menu items are almost invisible due to low contrast with the background image.
Obviously, when you scroll down, it works because of the background added to the menu.

![badcontrast](https://cloud.githubusercontent.com/assets/733133/18256728/8a3b76d6-73b9-11e6-96cd-ef1f1d39f219.PNG)

**Comment by Sandra97** [comment]
As the Conference will occur in 5 days, I think we can close it, it won't be fixed.
Re-opne if needed.
