### ISSUE TITLE
[jvols] Question about domain name

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#577]
In this page: 
https://www.joomla.org/contribute-to-joomla.html

We have links to `volunteer.joomla.org` 
`https://volunteer.joomla.org/joomlers`
`https://volunteer.joomla.org/teams`
`https://volunteer.joomla.org/reports`

and one to `https://volunteers.joomla.org/register`

Generally we refer to the "Volunteers Portal" (plural) and in the top menu we link to `https://volunteers.joomla.org/`

In order to avoid duplicates, why we don't use only one subdomain and setup a redirect on one of them?

**Comment by mbabker** [comment]
Even better why are both subdomains there?

BTW the same issue exists with the TM site and its 3 subdomains.

**Comment by jeckodevelopment** [comment]
i don't know tm subdomains... can we setup a redirect?

**Comment by mbabker** [comment]
license, trademark, and tm all point to the same subdomain all with no
redirects.

**Comment by jeckodevelopment** [comment]
didn't know that before. 
@SpiritJC , @marijkestuivenberg can we setup a redirect of the subdomains to tm.joomla.org ?

**Comment by Sandra97** [comment]
I just corrected the link on the Contribute page. They should all be now volunteers and not volunteer.

**Comment by jeckodevelopment** [comment]
Thank you @Sandra97 !
BTW, we should fix the duplicate domain names

**Comment by sanderpotjer** [comment]
Thanks for noticing! 

volunteer.joomla.org is now redirecting to volunteers.joomla.org

And @Sandra97 thanks for correcting the on the contribute page.

**Comment by jeckodevelopment** [comment]
Thanks @sanderpotjer
