### ISSUE TITLE
[jideas] Why do we have still this domain name?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#578]
**ideas.joomla.org** has been closed long time ago, why do we have this domain name with this old looking page still now?

We should point this to a forum or completely close it.

**Comment by mbabker** [comment]
It was only "closed" in the last couple of months.  I would have reskinned
it to start using it again but was advised there was a plan to replace it
so I stopped.

**Comment by jeckodevelopment** [comment]
Thank you Michael.
TBH i think that it could be a good idea start using it again.
Let's see the new plan

**Comment by brianteeman** [comment]
wow - someone noticed

**Comment by mbabker** [comment]
Only took 62 days.

**Comment by MATsxm** [comment]
@helvecio was on it?

**Comment by joo7** [comment]
Direct http://ideas.joomla.org to https://forum.joomla.org/viewforum.php?f=575 ?

Or leave a notice:

Sorry, this ideas pool is no longer continued.
Please visit the [Joomla! Ideas Forum](https://forum.joomla.org/viewforum.php?f=575) for supporting the Joomla! project with your valued ideas.

**Comment by mbabker** [comment]
It's offline, text changed, nothing else happening here since there's no interest in following through on the action that was once proposed of having a new system to replace this.
