### ISSUE TITLE
[jmag] Do we need article publishing data on static pages?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#579]
There're some static pages on JCM that show publishing data like date of publishing, category and author name. I guess that we could unpublish these details for static pages.

- http://magazine.joomla.org/browse-topics
- http://magazine.joomla.org/contact-us
- http://magazine.joomla.org/subscribe
- http://magazine.joomla.org/all-intl-articles
- http://magazine.joomla.org/about

![topics](https://cloud.githubusercontent.com/assets/733133/18258177/4311fa7e-73d1-11e6-8cee-0a6c79c59b70.PNG)

![contacts](https://cloud.githubusercontent.com/assets/733133/18258182/4d044ee2-73d1-11e6-9a9e-f06d1ae7246c.PNG)

![about](https://cloud.githubusercontent.com/assets/733133/18258193/69b535d8-73d1-11e6-9461-afb045a1c109.PNG)

![subscribe](https://cloud.githubusercontent.com/assets/733133/18258194/69b5c05c-73d1-11e6-881c-f630b291241a.PNG)

![lang](https://cloud.githubusercontent.com/assets/733133/18258195/69b922c4-73d1-11e6-96d1-c7e2d8811b07.PNG)

**Comment by JacquesR** [comment]
No, that info is not needed there. It's on the to-do list, but low priority.
As we update the views and reorganise some of the old content, that will be changed over time.
