### ISSUE TITLE
[jrepo] youtube video

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#58]
You should use the ability of youtube to set a custom thumbnail to have a more appropriate image

**Comment by Sandra97** [comment]
Agree with you. I'll see it with Mike.

**Comment by mikeveeckmans** [comment]
Will do ASAP

**Comment by mikeveeckmans** [comment]
FIXED

**Comment by MAT978** [comment]
Thanks @mikeveeckmans 
I'm closing this issue - feel free to open it again if needed
