### ISSUE TITLE
[jcomm] Training 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#581]
Is it provided by ostraining or joomlashack - it says ostraining in the text and joomlashack in the new banner

**Comment by jeckodevelopment** [comment]
until yesterday i saw OsTraining banners

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it with @stevejburge

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it with @stevejburge

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
It's Joomlashack, we had a small conversation about it

**Comment by mikeveeckmans** [comment]
oops something went wrong

**Comment by genr8r** [comment]
github is registering button clicks at the moment but not refreshing the page to show the change.

**Comment by mbabker** [comment]
> oops something went wrong

We noticed 😛 

![screen shot 2016-09-06 at 4 30 52 pm](https://cloud.githubusercontent.com/assets/368545/18291710/6ea71ac4-744f-11e6-8221-005dad71e8f2.png)

**Comment by brianteeman** [comment]
@mikeveeckmans so the text needs to be updated ;)

**Comment by mikeveeckmans** [comment]
done
