### ISSUE TITLE
[jrd] Random order on languages

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#582]
If you go to JRD home page, the "Find a Resource Provider" module, allows you to filter results by languages. 
The list of languages is displayed without any order.

![jrdlist1](https://cloud.githubusercontent.com/assets/733133/18293726/f9fa35d0-7494-11e6-949a-582653bf40be.PNG)

![jrdlist2](https://cloud.githubusercontent.com/assets/733133/18293725/f9fa0a7e-7494-11e6-84cb-86db61dc18c4.PNG)

![jrdlist3](https://cloud.githubusercontent.com/assets/733133/18293727/f9fd2466-7494-11e6-92ac-6c411469e94f.PNG)

Languages should be displayed using the alphabetic order, so people can easily find the desired language.

**Comment by Sandra97** [comment]
@genr8r, could you please have a look to this issue and display the languages in alphabetical order, if possible?
Thank you!

**Comment by Sandra97** [comment]
@genr8r, could you have a look to this? Thank you.

**Comment by Sandra97** [comment]
@genr8r, the "Find a Resource Provider" module is not displayed anymore on the homepage. 
If it's expected, please close this issue. 
If not, well, it's a new issue.
Thanks.

**Comment by genr8r** [comment]
Resolved per #154
