### ISSUE TITLE
[jrd] TM review of "JRD Approval Process"

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#583]
Just tried to review this page: http://resources.joomla.org/en/jrd-approval-process in order to ensure the compliance with the TM rules.
Many of the `Joomla!` occurences don't have the `!`.
When the bang is needed, the word has been underlined (red/blue)

![jrdapp01](https://cloud.githubusercontent.com/assets/733133/18294430/4d2d4068-7499-11e6-8d38-5ed9e1162e37.PNG)
![jrdapp02](https://cloud.githubusercontent.com/assets/733133/18294429/4d295f16-7499-11e6-83f6-f4112ddd656b.PNG)
![jrdapp03](https://cloud.githubusercontent.com/assets/733133/18294422/4cc90cd8-7499-11e6-8b14-51eee0fb3aea.PNG)
![jrdapp04](https://cloud.githubusercontent.com/assets/733133/18294425/4cd22ad4-7499-11e6-877a-f7c1b7ebc042.PNG)
![jrdapp05](https://cloud.githubusercontent.com/assets/733133/18294424/4ccf76f4-7499-11e6-9bd4-8cc99de54273.PNG)
![jrdapp06](https://cloud.githubusercontent.com/assets/733133/18294423/4ccc51d6-7499-11e6-8e1e-03a24e5c9d40.PNG)
![jrdapp07](https://cloud.githubusercontent.com/assets/733133/18294427/4cecaf30-7499-11e6-9c3f-a203e5d27204.PNG)
![jrdapp08](https://cloud.githubusercontent.com/assets/733133/18294426/4cebf07c-7499-11e6-9a16-e0dae0f09d68.PNG)

Furthermore: `JoomlaDay` is one single word.

**Comment by Radek-Suski** [comment]
BTW: it's JoomlaDay™ not Joomla! Day

**Comment by jeckodevelopment** [comment]
That's what i said:

> Furthermore: JoomlaDay is one single word.

**Comment by Radek-Suski** [comment]
ups. Sorry. Speed-reading ;)

**Comment by jeckodevelopment** [comment]
;) no problem!

**Comment by Sandra97** [comment]
@genr8r, could you please have a look and solve these issues?
Thank you!

**Comment by MATsxm** [comment]
@genr8r please!

**Comment by PolishedGeek** [comment]
Hello - This is Deb, from the JRD team. I used to be active on both the Trademark team along with the JRD, and I used to be the official TM representative on this team. It is my understanding that the bang (!) and the TM only have to appear the FIRST time Joomla is used on a page. This was discussed at length back in the day with Duke Speer and it was agreed that overuse of the bang and TM only serves to negatively impact readability (and thus usability) of a page. 

Has this official TM policy changed? If so, can we have a link to the supporting TM documentation that specifies that we need to have "Joomla!" over 70 times on the page instead of the more reader-friendly "Joomla" name?

**Comment by MATsxm** [comment]
@PolishedGeek 
https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name
# ***BUT**
since then some decided to change it again then I guess tis issue should be closed...

Have fun!

**Comment by Sandra97** [comment]
I think we are supposed to keep the bang in graphics and trademarks. 
But well, who knows ;)

**Comment by Hils** [comment]
> #2017/044 - The Board officially declares that it is not necessary to use the bang in Joomla name for blog posts/copy. It does not affect the logo, brand name and registered trademarks.
> 
> Proposed by Radek Suski, seconded by Yves Hoppe.
> 
> The motion passed with unanimous consent.**
> 

https://volunteers.joomla.org/board-of-directors/reports/567-osm-inc-full-board-meeting-june-22-2017

I can't see a date on the doc that @MATsxm linked to, which I think is critical especially on policy documents which change over time.

**Comment by genr8r** [comment]
Thanks for weighing in @Hils. Based on conversation from our team meeting last week and the feedback above, it sounds as though we are in compliance on this. Please reopen if I am in error.

**Comment by Hils** [comment]
Oh dear - we spoke too soon! 

> Lawyers will be contacted to clarify the situation about the use of the bang in the project name.


OSM, Inc - Full Board Meeting - July 20, 2017
https://volunteers.joomla.org/board-of-directors/reports/602-osm-inc-full-board-meeting-july-20-2017

@genr8r

**Comment by MATsxm** [comment]
@Hils
OFC as it is a legal topic whatever some self-proclaimed jurists think...

**Comment by Hils** [comment]
Let's just hope that we all stay awake long enough, or live long, enough to implement the !rulz!

**Comment by genr8r** [comment]
I am good with whatever. Just seeking clarity. Thanks for the follow ups.
