### ISSUE TITLE
[jevnt] Wrong event name

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#584]
The name of JoomlaDay Israel is now `Joomla! Day Israel` instead of "JoomlaDay Israel"

![jday](https://cloud.githubusercontent.com/assets/733133/18310432/a4bdee76-74fe-11e6-8e53-1ed721edf858.PNG)

![jday2](https://cloud.githubusercontent.com/assets/733133/18310433/a7badd14-74fe-11e6-8f8f-4a4574142a6d.PNG)

**Comment by Radek-Suski** [comment]
Corrected. Thanks

**Comment by jeckodevelopment** [comment]
Thank you Radek!
