### ISSUE TITLE
[jconf] Red "Test" and top menu rendering problem on homepage

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#585]
![screen shot 2016-09-07 at 10 10 34 am 2](https://cloud.githubusercontent.com/assets/1870522/18326514/bb9060e0-750b-11e6-96ee-90b168e08705.png)

**Comment by wilsonge** [comment]
I believe they got thrown off guard by the PHP Server upgrade and moved to the WIP server earlier than planned. Anyhow this seems to now be fixed. Thankyou for reporting tho!
