### ISSUE TITLE
[Suggestion] Enable 2FA on all sites as able

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#586]
Joomla core supports two factor authentication as an additional security mechanism on user accounts, and the third party software we use also has extensions to support this.  The project [requires 2FA for `*.joomla.org` email accounts](https://community.joomla.org/blogs/community/1905-two-factor-authentication-becoming-mandatory-for-all-official-project-email-accounts.html).  Consistent with this policy and enabling user security to the highest extent possible, I would like to suggest that two factor authentication be enabled on all websites, but not as a mandatory requirement at this time (it can be revisited later if desired).  This will primarily impact our CMS installs, our docs wiki, and the phpBB forum; the issue tracker would not use this as it uses an OAuth based login mechanism through GitHub and obviously this cannot be enforced on our sites with no login mechanisms.

**Comment by Radek-Suski** [comment]
I actually tried to enable it on e.j.org and as far I remember it just gave me a white page every time. 
Need to check if it works now

**Comment by mbabker** [comment]
Make sure PHP's `mcrypt` extension is installed.

**Comment by wilsonge** [comment]
I'm guessing this won't be compatible with K2 for magazine?

**Comment by mbabker** [comment]
Well, unless K2 hijacks the core users component, it should be fine.

**Comment by JacquesR** [comment]
Here's the link with instructions to set up 2FA:
https://docs.joomla.org/J3.x:Two_Factor_Authentication
(for my own benefit and other who may have forgotten how to do this) :)

**Comment by mbabker** [comment]
Seems like this is going nowhere.  OK then.
