### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by iZOOlabs-GSOC** [joomla/joomla-websites#587]
Hello,

The enclosed URL is a phishing site that is targeting our client.

Please can you remove this URL and all related folders as soon as possible.

The URL is fraudulent and is being used in a phishing attack.

URL: http://escalemusicale.free.fr/logs/incrd.html

Type : Phishing

This phishing site is causing our client a financial implact so we appreciate you treating this incident with urgency.

We are looking forward to your immediate response with this site take down.

Please let us know if you have any queries.

Global Security Operation Centre

+44 20 3734 2726
izoolabs@izoologic.com
www.izoolabs.com

**Comment by Radek-Suski** [comment]
Hi,

we are not responsible for this website. The only connection to use is the fact that this website is using (a very, very, very old version) of the software this Open Source projects provides. 
We cannot do anything about it. I would recommend to contact the owner of the site or the hosting provider.

Regards,
Radek

**Comment by iZOOlabs-GSOC** [comment]
Hello

do you know how to contact Bruno Piguet as he is the one who created the site

Thanks

**Comment by Radek-Suski** [comment]
Hi,

no I am sorry. As I wrote before, we have no connection whatsoever to owners of the website.
They are just using our software which is freely available to download.
As this website seems to be located on some free server I would rather try to contact the hosting provider. 

Regards,
Radek

**Comment by sebastienlapoux** [comment]
Hi,
Free.fr is the french telecom operator which is proposing free sites to their customer.
You need to contact Free company itself http://www.free.fr/freebox/informations/signaler-un-contenu.html

Hope it helps.
