### ISSUE TITLE
Joomla 3.4.1 menu item type pop-up is empty

### ISSUE THREAD

**Issue by kd9000** [joomla/joomla-websites#588]
Hi, Please see error here:
http://mediasvc76mwd0vnlqz3l.blob.core.windows.net/errors/ScreenCapture_9-10-2016%202.51.00%20PM.mp4

I have checked these option online but nothing works for me
http://stackoverflow.com/questions/31483303/joomla-menu-item-article-list-blank?noredirect=1&lq=1
http://stackoverflow.com/questions/31417895/joomla-menu-item-type-pop-up-is-empty
http://stackoverflow.com/questions/29274383/there-is-no-images-links-tab-in-joomla-3-4-back-end?rq=1 

1)I increased my error detection and have everything else correct header x options etc as per suggestions above.... but I get nothing besides what is in the video above.

2) I have Joomla 3.4.1 but I cannot upgrade my Joomla to the new 3.6 because one of my main components is not compatible. Is there a way to upgrade to Joomla 3.6 and then downgrade it back to 3.4.1 ?

3) Or is there a way I can just reload the Joomla 3.4.1 I have ....just like I can do it with my softwares I have in my computer when I go to "control panel" and select "change/fix" instead of "uninstall. Is there a way to do that for Joomla?

**Comment by MATsxm** [comment]
Hi,
This repository is **ONLY** for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
