### ISSUE TITLE
[jmag]  improve responsive view of buttons

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#589]
Suggestion

Why don't we move the "leave a comment" button on the same line of the "issue number"?

Actually on the responsive view they are displayed on two different lines.

![screenshot_2016-09-11-21-21-56](https://cloud.githubusercontent.com/assets/733133/18419900/02a6c412-7866-11e6-8232-90a62f7497bd.png)

**Comment by JacquesR** [comment]
The Leave a comment button appears on the same line on most devices, but we run out of space on mobile views that are 360px or less.

I've removed some padding to solve it on the 360px one, but on 320px you will still have the same issue.
Perhaps the "Comments) text in brackets can be removed so it uses up less space.
Example: 
Leave a comment (3) 

Not sure.  If there's another quick-fix solution I can try it.

**Comment by jeckodevelopment** [comment]
@JacquesR I think that the example you provided will work :)
` Leave a comment (3) `

**Comment by JacquesR** [comment]
@jeckodevelopment  Which is better?
Leave a comment (3)
or
(3 Comments)  << That's what I changed it to now.

The second one removes the action text, but it does not really make sense to direct someone to comment before they've even read the article.

**Comment by jeckodevelopment** [comment]
I agree with you.
So let's stay with "3 comments", thank you @JacquesR

**Comment by JacquesR** [comment]
I'll still tweak the style a bit, but closing since original issue is resolved. Thanks

**Comment by jeckodevelopment** [comment]
Thank you :)
