### ISSUE TITLE
[jtrain] increase space between course image and title

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#590]
In order to improve the User experience on mobile devices it could be useful to increase the space between the course image and title.

![screenshot_2016-09-11-21-28-35](https://cloud.githubusercontent.com/assets/733133/18419928/c6e0c6ac-7866-11e6-841d-65c4bf7d8f37.png)

**Comment by Sandra97** [comment]
@stevejburge, any news about this request?

**Comment by htmgarcia** [comment]
I just submitted a small update to add a spacing between the image and the title in mobile. It should be working in an hour or so, once the cache refresh itself.

**Comment by Sandra97** [comment]
The space has been increased.
Closing this issue.
Re-open if needed.
