### ISSUE TITLE
[jtrain] suggestion to link to each class instead of direct to first video

### ISSUE THREAD

**Issue by JacquesR** [joomla/joomla-websites#593]
The links from the JTraining home page takes you direct to the first video of a class.
This is confusing, specially on mobile. It is not immediately clear that there's more videos.

Would it not be better to link to each class' page?
So instead of linking to:
https://community.joomla.org/joomla-training.html?ostm_view=lesson&ostm_pathway_id=48&ostm_course_id=198&ostm_lesson_id=3253
You could link to:
https://community.joomla.org/joomla-training.html?ostm_view=course&ostm_pathway_id=48&ostm_course_id=198

**Comment by Joomv** [comment]
See here for the reasoning - https://github.com/joomla/joomla-websites/issues/445

**Comment by mikeveeckmans** [comment]
Hi @JacquesR does this refers to #445

**Comment by JacquesR** [comment]
Thanks for the link. Just giving feedback on what I thought when I first used the site. (on my phone)
Perhaps change the buttons instead? 
Next Lesson instead of Next?  
If someone clicks around long enough, or happen to click on the Class link, they would find the rest of the videos, but some might also leave the site without noticing there's more.
Skipping an index does not make much sense, but perhaps just how may brain likes information.

**Comment by Joomv** [comment]
I agree with you @JacquesR and as you can see from the other thread so do others, but their user testing said differently.

**Comment by JacquesR** [comment]
Last comment from me on this: Perhaps they should consider further user testing on the live site, and specifically on mobile. (or solve with better buttons)

**Comment by MATsxm** [comment]
following #445 and no news for 6 months - closing
reopen if needed
