### ISSUE TITLE
[jcomm] suggestion to have unique subnavs for some Community sub-sites.

### ISSUE THREAD

**Issue by JacquesR** [joomla/joomla-websites#594]
Where the choice is made to have a sub-site merged within the Community site, instead of having it on a sub-domain, I think it's important for such a site to have its own title and own second level menu.

Examples would include Jtraining, JUG, Shop, etc.

Even if these links are the same as  the side quick menu, otherwise on mobile such sites would have no site-specific links at the top.

**Comment by Joomv** [comment]
You have a valid point and I'm working on a solution for this.
Bear with me!

**Comment by Joomv** [comment]
JUGs have always been part of CJO they were not merged in.

**Comment by JacquesR** [comment]
Same logic would apply though. I was thinking about this when viewing the Training site.
I'm also re-thinking the links we use on the JCM to avoid too many lines of links on mobile.

**Comment by Joomv** [comment]
I have implemented a responsive drop down menu system on CJO now.
The only RHS menu left is the homepage quick links which is a separate menu altogether.
