### ISSUE TITLE
[jshow] No effect after clicking on some menu items

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#595]
When visiting the site using my tablet, clicking on the 2 menu titles which have sub-menus (Browse Sites and About JSD) has no effect. Sub-menus work fine.
Can someone else check it to be sure it's not my finger which does not work properly? ;)

**Comment by MATsxm** [comment]
@Sandra97 Could you speak for once fr-FR please :stuck_out_tongue_closed_eyes:

**Comment by Sandra97** [comment]
@MATsxm Nope I prefer my awful Franglish

**Comment by alexandrelapoux** [comment]
Hi Sandra,
Could you test again, i finish the responsive yesterday. That works like a charm on ipad and ipad-mini (landscape and portrait).

**Comment by sebastienlapoux** [comment]
@Sandra97

**Comment by Sandra97** [comment]
Hi Sébastien,
On portrait display, it works fine (with the hamburger menu).
I still have the issue with the landscape mode.
I'll do a test with another tablet

**Comment by Sandra97** [comment]
Test done with another tablet (still a Samsung). Unfortunately, same result, no effect when clicking on Browse site and About JSD. 
Would be nice to have more testers for this.

**Comment by sebastienlapoux** [comment]
@Sandra97 I understood only now your point! On tablets you can no more click on the first level of a menu link with sub links. We can reproduce it.
Come back to you!

**Comment by alexandrelapoux** [comment]
Ok i change the JS, now on first click that open the submenu, on second click we go on the link.

**Comment by sebastienlapoux** [comment]
@Sandra97 can please check?

**Comment by Sandra97** [comment]
I confirm it works at 2nd click, for both menus.
Closing this issue.
Re-open if needed.
