### ISSUE TITLE
[jdown] Missing bangs on tips

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#596]
Tips of the main download buttons miss the "`!`" after `Joomla`
They should be:
`Download Joomla!` and `Download Joomla! Update Packages`

![jdown1](https://cloud.githubusercontent.com/assets/733133/18534156/a5fcb156-7ae8-11e6-8372-0b06ed91c64a.PNG)
![jdown2](https://cloud.githubusercontent.com/assets/733133/18534157/a5ff8fde-7ae8-11e6-920a-63945c09b3a8.PNG)

**Comment by jeckodevelopment** [comment]
![jdown3](https://cloud.githubusercontent.com/assets/733133/18534211/16ad471c-7ae9-11e6-82b9-95b8df2661ff.PNG)
![jdown4](https://cloud.githubusercontent.com/assets/733133/18534214/16e9a536-7ae9-11e6-972e-dbeec6d6d6fd.PNG)

**Comment by jeckodevelopment** [comment]
In the page: https://downloads.joomla.org/documentation

![jdown8](https://cloud.githubusercontent.com/assets/733133/18534431/6179a32e-7aeb-11e6-811b-1d70cdcfead5.PNG)
![jdown9](https://cloud.githubusercontent.com/assets/733133/18534433/618155b0-7aeb-11e6-91a5-812c72ffeca1.PNG)
![jdown10](https://cloud.githubusercontent.com/assets/733133/18534432/617f517a-7aeb-11e6-8b1d-c484e3d5a05d.PNG)

**Comment by MATsxm** [comment]
Known issue (that is not as a possible exception)
In fact, the "!" was breaking the strings in the t9n process.
Not decided yet what will be the best option.

**Comment by jeckodevelopment** [comment]
Thank you @MATsxm 
Which options do we have?

**Comment by MATsxm** [comment]
Depends the format we choose as we won't have issues with `.ini` files but with `.html`
Depends also if we will use an automated process (I'm not a fan)... 
There are so many criteria to be taken into account
still under investigation, but one thing on my todo and as said...  not a "real" issue as it is for Titles.

**Comment by MATsxm** [comment]
Labelled Phase 2 as we will need tests with translators when the site will be live.

**Comment by MATsxm** [comment]
as @Sandra97 and I are dealing with those strings and are spending already enough time to correct/integrate "real issues", _Alt_ like _titles_ will stay without the bang for the downloads site.
closing - reopen if needed
