### ISSUE TITLE
[jdown] Wrong number

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#597]
We say:
![jdown5](https://cloud.githubusercontent.com/assets/733133/18534245/4b2c3750-7ae9-11e6-9588-c1301a88f385.PNG)

But JED counters at https://extensions.joomla.org/ says: 7855
So they're less than 7900 (unfortunately)

![jedtotal](https://cloud.githubusercontent.com/assets/733133/18534254/646cd076-7ae9-11e6-8dcd-47f32c4579cb.PNG)

**Comment by MATsxm** [comment]
let's wait 2 more weeks :stuck_out_tongue_winking_eye: 
In other news, IFAIR, we have 2 different numbers in 2 different places...

**Comment by jeckodevelopment** [comment]
Yes in another page, it says around 8000.
JED doesn't have such a huge queue of listing to be approved in 2 weeks :P

**Comment by mbabker** [comment]
How often do we want to be updating this text?  I'd say just leave it at 7000 for now and when it goes over 8000 do the updates (same when we get to 9K).  Going down to the hundreds is going to mean updating the text (and all translations) more often.  Unless there's a way to just read this number out of the JED via API.

**Comment by jeckodevelopment** [comment]
I agree!
Let's stay on thousands.

**Comment by Sandra97** [comment]
I'm on it.

**Comment by Sandra97** [comment]
Number of extensions changed to indicate 7,000.
Closing this issue.
Re-opne if needed.

**Comment by jeckodevelopment** [comment]
Thank you @Sandra97
