### ISSUE TITLE
[jdown] Do we need the filter?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#599]
Do we need the filter after the files of each release?
By default we show all the files part of a release, why do we should have a filter?
All files are relevant and there's no big advantage using pagination and filters here.

![jdown7](https://cloud.githubusercontent.com/assets/733133/18534394/cb507e7c-7aea-11e6-98be-be8e2627ef51.PNG)

**Comment by mbabker** [comment]
It's hidden on the English menu item now.  We'll have to work through the rest to make the updates.

**Comment by Sandra97** [comment]
I'm hidding it for the other languages.

**Comment by Sandra97** [comment]
Done for all the languages currently set up.

**Comment by jeckodevelopment** [comment]
Thank you @Sandra97
