### ISSUE TITLE
[jrepo] platform millions ...

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#60]
This block is not truly responsive. Screenshot below is from my nexus 7
![screenshot_2015-08-25-23-01-33](https://cloud.githubusercontent.com/assets/1296369/9480870/922d16ac-4b7d-11e5-9ea5-07eb8dfca954.png)

**Comment by Sandra97** [comment]
Know Issue. I'm waiting for a new background image for large smartphones and small tablets.

**Comment by mikeveeckmans** [comment]
Will do ASAP

**Comment by Sandra97** [comment]
A new background image has been added to fit to screens between 481px and 980px. CSS have been adpated. 
@brianteeman Please check and close if it's ok.

**Comment by brianteeman** [comment]
Wow I hadnt realised that the text was part of the image :facepalm:
