### ISSUE TITLE
[jdown] 404 on "Download Language Packages"

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#600]
I'm sure that you already know that, but, the button "`Download Language Packages`" in the home page gives a `404 Article not found` error.
Target page:  https://downloads.joomla.org/translations

**Comment by Sandra97** [comment]
It's an expected behaviour as this section is not yet published ;)

**Comment by jeckodevelopment** [comment]
yeah, i was pretty sure of that :D

**Comment by mbabker** [comment]
For now we'll need to point that over to https://community.joomla.org/translations.html

Once upon a time I dreamed of launching this site with all the translation stuff done already.  But there's just too much to do to get that going and I don't want to wait another year.

**Comment by jeckodevelopment** [comment]
Good move @mbabker 
I suggest also to add a "Translation" or, better, "Language Packs" menu item in the subnav.

**Comment by MATsxm** [comment]
@jeckodevelopment 
supposed to be a Menu (unpublished for the moment)

**Comment by mbabker** [comment]
A moment of silence for the unpublished menu items missing as part of our final push for the initial launch.

<img width="1070" alt="screen shot 2016-09-14 at 7 47 44 pm" src="https://cloud.githubusercontent.com/assets/368545/18534778/3431d936-7ab4-11e6-8297-aaab04115f91.png">

**Comment by MATsxm** [comment]
"Language Packages"
fixed as Menu and added as string to translate on Crowdin.

**Comment by MATsxm** [comment]
see #614 
Closing - reopen if needed
thanks
