### ISSUE TITLE
[jcomm] Translation Page - TM Review

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#601]
URL: https://community.joomla.org/translations/joomla-3-translations.html

![lp04](https://cloud.githubusercontent.com/assets/733133/18534810/1a7ac71a-7aef-11e6-8355-ae02bca8405d.PNG)

The ® symbol is not needed at each occurence of the word `Joomla!`. Rule says to use it just at _the first prominent use_.
### Missing bang

Please remember that it should be `Joomla!` instead of `Joomla`
![lp02](https://cloud.githubusercontent.com/assets/733133/18534764/cb505cae-7aee-11e6-9c36-2c8f23f55f69.PNG)

![lp03](https://cloud.githubusercontent.com/assets/733133/18534788/ef5f52d0-7aee-11e6-8faa-d173bb07d945.PNG)

**Comment by Joomv** [comment]
Please tag the translation team on this.  I do not manage this content.

**Comment by jeckodevelopment** [comment]
Who can i tag, @Joomv ?

**Comment by MATsxm** [comment]
@Joomv **ABSOLUTLY NO EMERGENCY** but stiil no access to this content?

**Comment by Joomv** [comment]
No need to shout! - Do you need access to this content @MATsxm ?
Currently these users have access.
![users - joomla community portal - administration](https://cloud.githubusercontent.com/assets/5618499/23553896/afccdb72-001a-11e7-88c8-7442b2b49b5e.png)

**Comment by MATsxm** [comment]
AH! I see, I see... 😄 
yes please, a temporary one, things should be done - thanks

**Comment by Joomv** [comment]
Your user is now in the translation team user group you should be able to access everything you need now.

**Comment by MATsxm** [comment]
nope and has usual with J properties... not even able to log on... WTF I only have probs with J sites 😠 😠 😠

**Comment by MATsxm** [comment]
the vital changes were made
we could have expected the "official" Team (except Marijke of course) to do the job earlier regarding this page is the second most viewed on the site...
I won't go deeper in the different packs sections as it is not my job!
