### ISSUE TITLE
[jcomm] Search icon alignment

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#602]
If you go to community.joomla.org the icon of the magnifying glass is not aligned properly.

Inactive

![cjoglass01](https://cloud.githubusercontent.com/assets/733133/18534958/7155a66c-7af0-11e6-8285-4cee5dbb8761.PNG)

Active

![cjoglass02](https://cloud.githubusercontent.com/assets/733133/18534959/715ba88c-7af0-11e6-9b81-e837b3f4ff50.PNG)

**Comment by Joomv** [comment]
Legacy from when it was in the right sidebar.  Removed icon inline with other sites.

**Comment by jeckodevelopment** [comment]
Thank you Rowan!
