### ISSUE TITLE
[jdown] Dropdown: top menu vs subnav

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#603]
If we look at the dropdown menus we have a sort of inconsistency between the top menu and the subnav menu.
The top menu (CDN) shows dropdown with rounded borders
The subnav menu shows dropdown with squared borders.

![topmenu](https://cloud.githubusercontent.com/assets/733133/18535054/43de5160-7af1-11e6-831f-1bf45bf44022.PNG)
![subnav](https://cloud.githubusercontent.com/assets/733133/18535053/43dd08a0-7af1-11e6-8161-df90589a8ed6.PNG)

**Comment by Sandra97** [comment]
But if I bring back the border-radius to the language dropdown, its display won't be nice as we don't have any border radius for the menu items of the site. (And note that nobody can open 2 dropdowns at the same time ;) )
![index](https://cloud.githubusercontent.com/assets/4682328/18535239/6166dda0-7ac0-11e6-872d-42d78362c155.png)

**Comment by jeckodevelopment** [comment]
Why don't we have the same effect of the topmenu with the "linking triangle" to the main menu item?

**Comment by MATsxm** [comment]
why should we need it?

**Comment by Sandra97** [comment]
You're asking too many questions. ;) 
I don't see any interest in adding this little old school triangle

**Comment by mbabker** [comment]
By design it looks like that menu doesn't use the carat/triangle thingy.  See the issue tracker, API docs, and 3.x landing page as other examples of sites using a dropdown there.

**Comment by jeckodevelopment** [comment]
Ok, thank you for the notes.
