### ISSUE TITLE
[jcomm] Community Helpdesk Trademark Review

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#604]
URL: https://community.joomla.org/helpdesk.html

### Missing bangs
`Joomla` should be `Joomla!`

![help01](https://cloud.githubusercontent.com/assets/733133/18535212/761e6f56-7af2-11e6-8fae-105f4be6ce17.PNG)

Furthermore, it could be useful to use a "better" title for the page. 

![help02](https://cloud.githubusercontent.com/assets/733133/18535235/a22e9378-7af2-11e6-8a16-27d8400bf2e4.PNG)

If you look at the browser it says a generic `Helpdesk`. 
It could be `Joomla! Community Helpdesk`

**Comment by Joomv** [comment]
Done

**Comment by jeckodevelopment** [comment]
> This department handles new Joomla User Group Registrations. 

should be `Joomla!`

thanks

**Comment by jeckodevelopment** [comment]
Title is still only `Helpdesk`

**Comment by Joomv** [comment]
Check now.

**Comment by jeckodevelopment** [comment]
Just this:
![jtm01](https://cloud.githubusercontent.com/assets/733133/18562711/31713c2e-7b85-11e6-81ed-43132ff35c10.PNG)

**Comment by Joomv** [comment]
There's always 1.
Done.

**Comment by jeckodevelopment** [comment]
Thank you Rowan :)
