### ISSUE TITLE
[jdown] Anchor menu or not?

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#605]
Asking myself about the real need of the anchor menu on the HP...
Thoughts?
During the testing process and as example, the fr-FR version is **WITH** the anchor menu and the en-GB is **WITHOUT** the anchor menu.

**Comment by jeckodevelopment** [comment]
We should involve also UX Team, in order to have also their opinion

**Comment by MATsxm** [comment]
Removed as this is not an improvement and also add an unnecessary step for translation.
closing - reopen if needed
