### ISSUE TITLE
Downloads - Language Packages and Download Language Packages links are inconsistent

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#606]
Joomla! Downloads looks great.

In my testing, I find that:

* "Language Packages" menu item redirects to https://community.joomla.org/translations.html. It is located at the same level than the rest of local menu items. It would be better to open a new window and move it as the last item of the list.
* In home page, "Download Language Packages" button is linking to this broken Url: https://downloads.joomla.org/translations

Regards

**Comment by zero-24** [comment]
confirmed.

**Comment by zero-24** [comment]
Same applys for the Dokumentation there is also the old link
![image](https://cloud.githubusercontent.com/assets/2596554/18543929/8dda02dc-7b32-11e6-8cfa-c50fe7618f89.png)

**Comment by jeckodevelopment** [comment]
At the moment, they're working to move the "translation download infrastructure" to the new downloads website. So in the first phase, it will continue linking to the old page on community website.
https://github.com/joomla/joomla-websites/issues/600

**Comment by Sandra97** [comment]
I'll change these 2 links for all languages currently displayed on the site.

**Comment by MATsxm** [comment]
Also agree for the `_blank` and would be happy to change them but as some "experts" disagree... </whistling>

**Comment by MATsxm** [comment]
Point 2: link fixed for the `Download Language Packages` BTN
and also on the FAQs page as reported by @zero-24 
_Changes only for the en-GB source content and will be pushed for t9N in a few days_
Thanks

**Comment by mbabker** [comment]
Let's keep one issue for this particular set of links please.  See #600.
