### ISSUE TITLE
[jdown] Technical Requirements 

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#607]
Please move some links to https on the Technical Requirements page

old Link | new link 
------------ | -------------
`http://www.php.net` | `https://secure.php.net` 
`http://www.mysql.com` | `https://www.mysql.com`
`http://www.postgresql.org/` | `https://www.postgresql.org/`
`http://www.apache.org/` | `https://www.apache.org/`
`http://www.zend.com/` | `https://www.zend.com/`
`http://www.php.net/manual/en/install.windows.php` | `https://secure.php.net/manual/en/install.windows.php`
`http://dev.mysql.com/doc/refman/5.7/en/windows-installation.html` | `https://dev.mysql.com/doc/refman/5.7/en/windows-installation.html`

**Comment by MATsxm** [comment]
Thanks
Done for en-GB (will be the source content for t9n)
Note that the source file will be pushed in few days after reviews. Meanwhile, the changes won't appear for other languages.

**Comment by MATsxm** [comment]
Thanks
Closing - Reopen if needed

**Comment by jeckodevelopment** [comment]
Thank you

**Comment by zero-24** [comment]
:+1:

**Comment by mbabker** [comment]
@MATsxm `https://www.php.net` needs to be `https://secure.php.net` (there's some long drawn out reason why www doesn't support HTTPS if you care to dig long enough).

**Comment by MATsxm** [comment]
done (en-GB see above for the why)
Thanks
