### ISSUE TITLE
[jrepo] left aligned subheadings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#61]
The subheadings on the home page are all left aligned. eg Joomla! Top Features
While thats a design choice on the desktop it looks like an error on mobile. Screenshot below is from a nexus 7 where they are still left aligned but on an even smaller screen they are (correctly) centred

![screenshot_2015-08-25-23-02-30](https://cloud.githubusercontent.com/assets/1296369/9480904/eb4c2a16-4b7d-11e5-99df-a501a9c53fb3.png)

**Comment by Sandra97** [comment]
Agree. I'll center the titles for screen under 768px.

**Comment by brianteeman** [comment]
Personally I would center for all screens

On 25 August 2015 at 23:12, Sandra97 <notifications@github.com> wrote:

> Agree. I'll center the titles for screen under 768px.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/61#issuecomment-134757162>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Sandra97** [comment]
I'll test for all screens

**Comment by Sandra97** [comment]
'Features' and 'Look who's' headings are now centered on all screens.
Please check.

**Comment by brianteeman** [comment]
Looks much better
