### ISSUE TITLE
[jdown] No need for the warning i guess?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#610]
On the old download site we have the waring about 3.5.0 updates. I personaly don't think we need to include it on the new site but i want to bring it up here.
![image](https://cloud.githubusercontent.com/assets/2596554/18544432/d7c34afa-7b34-11e6-820b-607689896662.png)

**Comment by jeckodevelopment** [comment]
It's not present at the moment

**Comment by zero-24** [comment]
Yes but I'm also not sure if we realy need it. ;)

**Comment by jeckodevelopment** [comment]
I guess that if it's not in place now, it won't be later :P

**Comment by Sandra97** [comment]
Like you, I don't think we need it on the new site. 
This button has been exceptionally added due to the issue with this update, but usually we don't have it.

**Comment by zero-24** [comment]
Closing than. Thanks
