### ISSUE TITLE
[jdown] Redirect old sites for the todo list if not there already ;)

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#611]
Current Link | New Link | Comment
------------ | ------------- | -----
`https://www.joomla.org/about-joomla/technical-requirements.html` |  `https://downloads.joomla.org/technical-requirements` | N/A
`https://www.joomla.org/download.html` | `https://downloads.joomla.org/latest` | At the top of each site and on the buttons the link should be changed. But i guess a redirect is also needed as we maybe have 3prtys that link to that site.
`http://joomlacode.org/gf/project/joomla/*` (so any site the link to the project) |  `https://downloads.joomla.org/` | If possible. Maybe a htaccess redirect ;)

If i found more i can add it here.

**Comment by jeckodevelopment** [comment]
> At the top of each site and on the buttons the link should be changed. But i guess a redirect is also needed as we maybe have 3prtys that link to that site.

Button could be changed in the CDN/template. A redirect is needed anyway.

**Comment by Sandra97** [comment]
It's already on our todo list ;)

**Comment by mbabker** [comment]
The odds of us getting JoomlaCode redirected are slim to none.  We tried last year after we set up the issue archive on the developer site and that hunk of crap ignored every Apache directive we put in at every level of the server.

**Comment by zero-24** [comment]
i guess if it is final closed we can redirect the complete domain. That should work?

**Comment by mbabker** [comment]
It's not going anywhere for a long time still (gotta get the translations moved over).

**Comment by JacquesR** [comment]
You may already have considered this, but the current download page has very high traffic value. That's why there's someone paying to have their banner on it. So any redirect changes have to keep this in mind.  :)

Related (and without knowing what your further plans are with this new subsite), in the screenshot I don't see the user help-text and advertising banner that we have on the current download page. Where will that go?

**Comment by mbabker** [comment]
The banner's on the homepage and the right folks are already in the loop to
make sure it's displayed per agreement.  It is one of the things I did keep
in mind going through with this even when others felt it lesser priority.

The FAQ section has its own (translated) page now, and some of the text is
integrated into the homepage banner.  The only thing we didn't really pull
in was the orange alert box.

**Comment by mbabker** [comment]
Closing.  We've already got tasks on the site's repo for each phase of bringing the site up.

- https://github.com/joomla/downloads.joomla.org/issues/30
- https://github.com/joomla/downloads.joomla.org/issues/36
- https://github.com/joomla/downloads.joomla.org/issues/44
- https://github.com/joomla/downloads.joomla.org/issues/49
