### ISSUE TITLE
[jdown] The download icon loads not that fast

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#612]
I'm not sure if we can do anything here but it takes a few secconds to load the download icons (on the first page view per sesssion).

![image](https://cloud.githubusercontent.com/assets/2596554/18544996/7938b454-7b37-11e6-9370-a6423cf4ee6b.png)

**Comment by mbabker** [comment]
It's coming off the CDN the same as every other site, there's no reason for it to be slow except for a slow overall connection I'd assume.

**Comment by MATsxm** [comment]
Some one call me? :stuck_out_tongue_closed_eyes:

**Comment by mbabker** [comment]
YOU TAKE YOUR INTERNET PROVIDER BACK!

**Comment by zero-24** [comment]
Closing than. Thanks.
