### ISSUE TITLE
[jdown] Language Packages?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#614]
What is the propose of the Language Packs in download sites?

![image](https://cloud.githubusercontent.com/assets/9630530/18555155/b6d645f2-7b5e-11e6-8986-158e83846081.png)

I find it confusing since we can't download the language packs there and we are redirected to Translations.

IMHO or we have the language packs for download there or we remove the menu item or we make a simple clean tutorial saying how to install language packs directly on joomla.

**Comment by mbabker** [comment]
We started without it, then it got added through https://github.com/joomla/joomla-websites/issues/600 based on feedback.  Personally I agree with you in keeping it off that menu until we have the language section, but we all know what opinions are like 😆

**Comment by MATsxm** [comment]
you mean disabling this menu?
I totally agree **BUT** please, please.... PLEASE!!!!! let me know as I'm actually headbang with this ***** process to batch them on other languages!!! :stuck_out_tongue_closed_eyes:

**Comment by MATsxm** [comment]
anyway... as a "hub", we will need them be on a site named "Downloads" as it is one of the first extension that should be available for download, even if it is possible from the site...
In an other way, why having a JED if we have an install from web?

**Comment by mbabker** [comment]
Honestly, it could go either way.  Just pick one and stick with it.  If we leave this to design by committee it'll be another year before we can move the site to the next phase.

**Comment by MATsxm** [comment]
IMHO: first step disabling this Menu as linked to Jcom (better for my sanity :p and most of all we should not delay the launch just because of this topic) but keep on thinking about the way to make them downloadable from here the way was the first tests  @mbabker made (don't care about HIS sanity).

**Comment by andrepereiradasilva** [comment]
agree

**Comment by Sandra97** [comment]
I agree to keep off the Language Packages until we have them on the site and regarding the links located in the FAQs and in the homepage article, just temporary link them to cjo.

**Comment by MATsxm** [comment]
ok... I will unpublish them

**Comment by MATsxm** [comment]
done- thanks
Closing - Reopen if needed
