### ISSUE TITLE
Add link to Crowdin in template

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#615]
Between the project's newly announced partnership with Crowdin and the space arguably having a high volume of activity for translations, we should add a link to our space there.  It doesn't necessarily need to be more extravegent than any GitHub links we already have but the more we internationalize the project beyond the CMS the more visible the collaboration hub for this should be.

x-ref https://github.com/joomla/jissues/issues/824

**Comment by Sandra97** [comment]
Here are 2 proposals to add it in the footer menu:

Icon:
![icon](https://cloud.githubusercontent.com/assets/4682328/19020588/75a33160-887b-11e6-96b8-0fcc3e2b40f8.png)

Text:
![localisation](https://cloud.githubusercontent.com/assets/4682328/19020591/80416538-887b-11e6-949c-12cec4d7cf41.png)
Not sure if "localisation" is the perfect term. If someone has a better idea, do not hesitate to make suggestions.

**Comment by MATsxm** [comment]
to me option 2
with "`Help to translate`" (or the idea in a better en-GB) but not `Localisation` (nor `Translation`)
In this case, I would prefer the more generic term: `Internationalization` oooops sorry, I mean: `Internationalisation` 😉

**Comment by brianteeman** [comment]
help translate
Or
Help us translate this
Or
Help to translate this

But never 
Help to translate.

**Comment by MATsxm** [comment]
IMHO, "**this**" would be not relevant as the link will be to a generic "portal" https://crowdin.com/projects/Joomla
(where "info" should be updated... </whistling>)

**Comment by brianteeman** [comment]
In which case it is just "help translate" as you cant have the "to" without a "something"

**Comment by mbabker** [comment]
"Help Translate" good enough for me.  I've added it to the footer layout in the template repo, we'll push it up to Crowdin shortly then work it into deployment.
