### ISSUE TITLE
[jdown] Split downloads in "New installations" and "Updates"?

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-websites#616]
First of all: great work on the downloads site, thanks!!

I'm wondering if it would be good to split the download page for a release (e.g. https://downloads.joomla.org/cms/joomla3/3-6-2) into two sections, something like:
![downloads](https://cloud.githubusercontent.com/assets/522834/18577649/59ec4930-7beb-11e6-8bd8-d8decfd62d10.jpg)

Mainly for new users to better understand the differences between all the available downloads on the page.

**Comment by jeckodevelopment** [comment]
I like the idea!

**Comment by mbabker** [comment]
This has been implemented.

**Comment by sanderpotjer** [comment]
Great! Thanks @mbabker!

**Comment by MATsxm** [comment]
and strings added on Crowdin for t9n

**Comment by jeckodevelopment** [comment]
Good job :)
