### ISSUE TITLE
[jshop] Change temp image on joomler showcase

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#620]
https://community.joomla.org/joomler-shop-showcase.html change temporarily image

**Comment by Sandra97** [comment]
@mikeveeckmans, is this has been done or not?

**Comment by jeckodevelopment** [comment]
@mikeveeckmans and @Sandra97 the URL leads to a 404 error
https://community.joomla.org/joomler-shop-showcase.html

`Category not found`

**Comment by Sandra97** [comment]
The correct URL is https://community.joomla.org/the-joomla-shop/joomler-shop-showcase.html

**Comment by Sandra97** [comment]
@mikeveeckmans, seems temporary image has not been changes. Any news?

**Comment by mikeveeckmans** [comment]
replaced with a temp image
