### ISSUE TITLE
[jforum] Blank space before the TM symbol

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#621]
If you go to http://forum.joomla.org/
the site title has a blank space between the site name and the TM symbol
`The Joomla! Forum ™`

![jforum01](https://cloud.githubusercontent.com/assets/733133/18608726/8ab52742-7cf1-11e6-9d82-1bbef97c3881.PNG)

**Comment by ooffick** [comment]
Fixed

**Comment by jeckodevelopment** [comment]
Thank you!
