### ISSUE TITLE
[jdown] 

### ISSUE THREAD

**Issue by bosyrih** [joomla/joomla-websites#622]
- [ ] in https://downloads.joomla.org/
there is missing 
Downloaded over 0 times!
in Arabic & Fransaic (Canada).

- [ ] It take to long to download Home page telling in status bar tranfering data from googletagmanager, and connectin to arvixe.com.

- [ ] the link to Arvixe web hosting dosn't work.

- [ ] in Technical Requirements in Arabic , in the top "This page is not yet available in your language. Make a gift to your community by translating it! Click here to start."

- [ ] if you click the start it take you to crowdin, but all translation is complete there, that mean the site did not take translation to Arabic for this page.

- [ ] in Download link in Arabic the page is whole translated but the page still tel that "This page is not yet available in your language. Make a gift to your community by translating it! Click here to start."

**Comment by Sandra97** [comment]
Hi Hussein, 

Thank you for your feedback.

Regarding the missing translations on the site, they will be of course merged (the ones you are talking about are merged manually). I just saw you ended all the translations in Arabic, we'll merge them today. 
Of course, we'll remove the notice at the top of the fully translated pages.

Regarding Arvixe, the link is working for me, but we are waiting for the requirements about this ad.

For the download speed of the site, don't worry, as we're still in beta testing process, all caches are not yet enabled.  

Did you already see any issue with the display in Arabic or everything seems to be ok?

**Comment by MATsxm** [comment]
Please, do not too much take care of the content at this point as it may subject to changes.

Most important is to check RTL's layouts as Michael did a huge work on it fixing issues.

Thanks

**Comment by mbabker** [comment]
During this first testing round we don't have cache or the CDN system enabled purposefully.  During the next testing round it will be enabled so we can better gauge performance and work out whatever issues we need to.  This first round is really aimed more for validating content and workflows and lesser emphasis on performance.

**Comment by bosyrih** [comment]
Every think is OK for RTL.
RTL layout is OK

All landpage is perfect Form layout and RTL align.


Great work
Thanks All

**Comment by MATsxm** [comment]
Thanks
I guess we can close this one.
Reopen if needed
