### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by fabclan1998** [joomla/joomla-websites#623]
Hi! my problem is login to Joomla! Control Panel
![default](https://cloud.githubusercontent.com/assets/22323215/18673325/13207082-7f54-11e6-8cc9-0af944ec1c5f.png)
Pls help me

**Comment by zero-24** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
