### ISSUE TITLE
[jdown] joomla downlad

### ISSUE THREAD

**Issue by bosyrih** [joomla/joomla-websites#624]
the link for Download Language Packages in Arabic is broken it's  take us to https://downloads.joomla.org/translations. but the in English page it's take us to https://community.joomla.org/translations.html.

**Comment by zero-24** [comment]
Confirmed

**Comment by MATsxm** [comment]
The new ar-AA t9n and then links have not been pushed yet, then a known issue.
Thanks

**Comment by Sandra97** [comment]
This has been solved.
Closing this issue.
Re-open if needed.
