### ISSUE TITLE
[jshop] Login Modul misses the TFA login

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#625]
![image](https://cloud.githubusercontent.com/assets/2596554/18687960/b9231042-7f82-11e6-99bf-b2254c3e0ca8.png)

On this site i'm unable to login with my account as i use TFA for my community account.

### How to come to this site

- go to shop.joomla.org
- select an item
- Add to chart
- checkout

**Comment by Joomv** [comment]
i've disabled the shop for now.  

@mikeveeckmans  Could you have Nicholas look at this?  There appears to be no 2fa support in hika.

**Comment by zero-24** [comment]
I'm sorry that i found it just now but on testing we need to login to access that pages so this issue don't come up :(.

**Comment by obsidev** [comment]
Hi,

Just disable the "login" in your HikaShop configuration (Configuration > Checkout > Login & Registration) and put a Joomla login module which will just be displayed for the "checkout" menu.
So you will have a TFA login and also a way to register.

Regards,

**Comment by mbabker** [comment]
Looks like this is addressed?
