### ISSUE TITLE
[jevnt] Duplicate URLs for events

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#628]
If you click on `JoomlaDay Poland 2016` link from this page: https://community.joomla.org/events/joomladays.html 
the event URL is: https://community.joomla.org/events/joomladays/2444-joomladay-poland-2016.html 

if you click on `JoomlaDay Poland 2016` link from the event home page: https://community.joomla.org/events.html 
the event URL is: https://community.joomla.org/component/sobipro/2444-joomladay-poland-2016.html?Itemid=0 

If you click on `JoomlaDay Poland 2016` link in the pointer on the map, you'll go to https://community.joomla.org/events/joomladays/2444-joomladay-poland-2016.html same as the one in JoomlaDays page.

This issue occurs for each event.

**Comment by Radek-Suski** [comment]
Thanks for reporting. I think it is a deeper issue. We discussed it concerning the certification site as well. 
I will need to investigate it but to be honest I do not have much free time at the moment. I will be probably able to fix it first after we are back from Greece. 
I think however that the issue itself is not that grave as the canonical URL is correct so Google won't index those wrong URLs

**Comment by jeckodevelopment** [comment]
No problem @Radek-Suski , yes we noticed that also on Certification.
I reported here to keep that in mind. Thank you :)

**Comment by Radek-Suski** [comment]
Should works now

**Comment by jeckodevelopment** [comment]
Thanks!
