### ISSUE TITLE
[jrepo] To » Or Not To »

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#63]
Many of the side menus have » characters at the end of the name, some don't.  Make it consistent one way or the other.

**Comment by MAT978** [comment]
Agree, but don't forget that it's supposed to be a "temporary" site and all the design should be supported by the Team in charge of the future new .org.
Thanks @Sandra97

**Comment by Sandra97** [comment]
Shit. Why these >> have not been added thanks to CSS. Would have been faster for me.

**Comment by MAT978** [comment]
and FYI those signs has never been 'arrows' but what we call "Guillemets à la Française"
(french quotation marks) 
https://en.wikipedia.org/wiki/Guillemet

**Comment by mikeveeckmans** [comment]
I'll take the >> out

**Comment by Sandra97** [comment]
Done! If one is stil present, not my fault, beer fault :wink:

**Comment by mikeveeckmans** [comment]
Thank you @Sandra97

**Comment by MAT978** [comment]
Thanks
I'm closing the issue - feel free to open it again if needed
