### ISSUE TITLE
[jevnt] A way to prevent an empty page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#630]
If you go to https://community.joomla.org/events/user-group-meetings.html
you'll likely find no planned User Group meeting.
So why don't we have a friendly message here?
Something like: 

> No User Group meeting planned yet, do you want to add your next meeting?

![jempty](https://cloud.githubusercontent.com/assets/733133/18693695/03f0131a-7fa4-11e6-8ce7-055793c40cd2.PNG)

**Comment by mbabker** [comment]
Does this still require action or was a condition added for a "no upcoming meetings" state?  @Joomv @Radek-Suski
