### ISSUE TITLE
[jvols] About CLT

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#631]
I just went to the CLT page on Volunteers Portal and i noticed two changes:
https://volunteers.joomla.org/leadership/community-leadership-team#members

![jlead](https://cloud.githubusercontent.com/assets/733133/18693622/79f4da6a-7fa3-11e6-8cba-6db74ee5e9f7.PNG)

1. @MATsxm has been added to CLT. No announcement on that and no calls. Is that correct?

2. @Sandra97 you're listed as Team Leader. As far as I know, Leadership members are all with the same "position", no Team Leaders, but just all Leadership members. Furthermore Leadership members have all permissions for current LT (in which he/she is involved) and for LT subteams.

**Comment by MATsxm** [comment]
I would say just a bug relative to the addition to the Community T9N Team
@sanderpotjer will have a look on it ;)

**Comment by mbabker** [comment]
I kinda like it this way though 😈

**Comment by jeckodevelopment** [comment]
@MATsxm damn, i already bought a champagne bottle!

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks, that was indeed not correct. Nevertheless, I hope you enjoyed your bottle of champagne!

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer
