### ISSUE TITLE
[jcomm] Top menu consistency

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#632]
If you look at the top menu on CJO, the appearance is not really consistent with the standard joomla.org properties.
Actually it lacks `focus` and `active` styles.

Furthermore, menu items look different.

![cjo](https://cloud.githubusercontent.com/assets/733133/18693941/1e4c1900-7fa6-11e6-841e-115b4bbf098f.PNG)
![jorg](https://cloud.githubusercontent.com/assets/733133/18693942/1e4c695a-7fa6-11e6-93b4-4e00df50d8b2.PNG)

**Comment by Joomv** [comment]
This was done a while ago.  I was still working on the responsive menu.

**Comment by jeckodevelopment** [comment]
Thank you!!!!
