### ISSUE TITLE
[jforum] No sticky top forum menu

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-websites#633]
The forum specific topmenu would be useful to have sticky on page scroll similar to the behavior of the menu at all the other joomla websites.
Today the Home and other menu items get out of sight constantly.

**Comment by ooffick** [comment]
That's fixed now.

**Comment by jeckodevelopment** [comment]
Thanks @ooffick

**Comment by mikeveeckmans** [comment]
Thank you !
