### ISSUE TITLE
[jevnt] mobile view for the events on the main page

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#634]
On the main page the modul for the events looks broken on mobile
![wp_ss_20160921_0001](https://cloud.githubusercontent.com/assets/2596554/18704307/c266919e-7fe9-11e6-95bf-a68d0cfa8519.png)

**Comment by Radek-Suski** [comment]
Why it has been closed?

**Comment by zero-24** [comment]
I did hit the button for the wrong issue.

**Comment by Radek-Suski** [comment]
Don't drink and Github :D

**Comment by zero-24** [comment]
I don't drink anytime. Maybe i was just to tired :)

**Comment by Sandra97** [comment]
Display is still like on Tobias' screenshot.
@Radek-Suski, @Joomv  anything you can do about that?
Thank you!

**Comment by Joomv** [comment]
Did a bit of work on this, its much better now.
