### ISSUE TITLE
[jevnt] is there a reason for the dublicate twitter link?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#635]
On the detail view it looks like there is a dublicate twitter link as button and link is that expected?
![wp_ss_20160921_0003](https://cloud.githubusercontent.com/assets/2596554/18704564/b5b523ba-7fea-11e6-975a-b2a4817ebec4.png)
![wp_ss_20160921_0002](https://cloud.githubusercontent.com/assets/2596554/18704565/b5b92622-7fea-11e6-9671-5068c9fc2f9c.png)

**Comment by Radek-Suski** [comment]
Ups. Never work on a live site. Sorry. Thanks. Fixed

**Comment by zero-24** [comment]
Thanks 👍
