### ISSUE TITLE
Untranslated text with white sidebar

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-websites#638]
Opening the link from this tweet https://twitter.com/joomla/status/778288369696665600 results with this screen on my phone

![screenshot_20160921-145336](https://cloud.githubusercontent.com/assets/251072/18711788/cd8b4e76-800b-11e6-8c40-3d76f54a5130.png)

**Comment by Sandra97** [comment]
It seems this issue has been fixed.
Closing this issue. 
Re-open if needed.
