### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by clccolombia** [joomla/joomla-websites#639]
My Web site is dead HELP 

http://www.fundacionsocialclc.org/

**Comment by zero-24** [comment]
Please use the forum for individual support http://forum.joomla.org this is the repo to report issues with the official sites.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
