### ISSUE TITLE
[template] Globe Menu Position

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#64]
As Brian pointed out in #57 the internationalization menu has a rather awkward "spot" in the 3.x mega menu (it's a bit better on the 2.5 sites, the icon's more prominent).  For sites that don't use a search bar, it's even worse as it almost looks like it's off in its own little world.  Once and for all do something about it's spot.

**Comment by MAT978** [comment]
AGREE!!!!
to be polite, I'll just ask what is the oportunity to use a simple icon instead of a word, in a menu like it should be, especially if this icon has many different meanings...
it's a total nonsense!
However, I believe that this issue must be resolved by the team in charge of the next .org

**Comment by jessicadunbar** [comment]
should we add a search to the repo site?

**Comment by mbabker** [comment]
It's already there.

**Comment by jessicadunbar** [comment]
oh, great! You guys are fast! Thanks
