### ISSUE TITLE
[jevnt] Duplicate URL for Events

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#640]
Actually we are using two URLs to access the Events Website.

`https://community.joomla.org/events/` used by redirect from events.joomla.org
`https://community.joomla.org/events.html` used by menu in CJO

It would be better to use just one URL.

**Comment by Joomv** [comment]
@Radek-Suski is this done?

**Comment by Radek-Suski** [comment]
Hey, I am just trying to get back on track. And we have a holiday in Germany :P
Anyway, my local server crashed and I need to get it working first because I need to get a local copy of the community site to check what's going on. Give me few days please

**Comment by Joomv** [comment]
@Radek-Suski it is just the redirect you have on events.joomla.org - not on the community site, just needs the .html put on the end of the redirect.  I don't seem to have ftp access to events, or I'd of done it.  No rush, when you've got a moment.  (Sorry to hear about the server ouch!)

**Comment by Radek-Suski** [comment]
Should be fine now

**Comment by jeckodevelopment** [comment]
Still see both URLs working

**Comment by Radek-Suski** [comment]
Damn. Wrong issue

**Comment by Joomv** [comment]
Both URL's will work.  Both are correct.  This is what happens when you turn a suffix on.  
I don't understand why we use them.

**Comment by Radek-Suski** [comment]
> I don't understand why we use them.

I am wondering too. I don't think it has any kind of relevance

**Comment by Radek-Suski** [comment]
Fixed.

**Comment by jeckodevelopment** [comment]
Thanks!
