### ISSUE TITLE
[jdown] S:MyLanguage tag to link to the doc

### ISSUE THREAD

**Issue by m-b-o** [joomla/joomla-websites#642]
Please use "**/Special:MyLanguage/**" for the links to the **Joomla! Docs** like: https://docs.joomla.org/Special:MyLanguage/J3.x:Updating_Joomla_(Install_Method).
It ensures, that the visitor is redirected to the translated page in his langage (if available).

**Comment by MATsxm** [comment]
I guess it's time now for it :stuck_out_tongue_closed_eyes: 
## MAT's todo
en-GB
- [ ] HP
- [ ] FAQs
- [ ] https://www.youtube.com/watch?v=vCadcBR95oU on Crowdin

**Comment by MATsxm** [comment]
done

**Comment by MATsxm** [comment]
@m-b-o 
Also done for de-DE
(and ar-AA, en-GB, en-US, fr-FR, fr-CA)
