### ISSUE TITLE
Meta referrer=origin-when-crossorigin

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#643]
Hi, 

A JED user reported a drop in referred traffic in Google Analytics.

I've checked out the case and confirmed that the issue is associated with the HTTPS-HTTP transition. By default, no information is shared from a secure channel to an unsecure channel.

Even if a target site also has HTTPS, extensions have links with or without HTTPS. So, there is also HTTPS-HTTP transitions in these cases. For example: in my extensions, I defined them with a mix of http/https links.

Since this is an unintended impact in the HTTPS implementation (and there is no simple way to check if a target site has HTTPS to convert links) we have disabled temporarily the SSL-only mode and visits can continue in HTTP or HTTPS.

Rowan gave me tip to solve the case with **referrer=origin-when-crossorigin** or **referrer=unsafe-url**

Ref: [The Meta Referrer Tag: An Advancement for SEO and the Internet](https://moz.com/blog/meta-referrer-tag)

Since this issue is common to all sites running now on SSL and redirecting traffict from HTTPS to HTTP. It would be great to implement the meta referrer in the template itself.

In the next week, we'll test it and confirm with numbers if it solves the issue.

**Comment by mbabker** [comment]
Already done.  https://github.com/joomla/jdotorgtemplate/commit/d329a462daac25dc550f5b6d9bab0babf39ae469
