### ISSUE TITLE
[JED] Login modal unusable on mobile

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#644]
![img_1540](https://cloud.githubusercontent.com/assets/368545/18807672/e38fd1d2-8255-11e6-9912-2f80dd2fa258.PNG)

**Comment by jeckodevelopment** [comment]
@mbabker can you please report it in the JED issue tracker?
https://joomlaextensionsdirectory.atlassian.net/secure/MyJiraHome.jspa

**Comment by mbabker** [comment]
I can't.  JIRA won't load on my phone.

**Comment by jeckodevelopment** [comment]
I'll do it for you!

**Comment by jeckodevelopment** [comment]
Done! Thank you @mbabker 
https://joomlaextensionsdirectory.atlassian.net/browse/JEDIST-19
