### ISSUE TITLE
[josm] Change CTA target

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#645]
If you go to: http://opensourcematters.org/about/sponsorship.html
the green button CTA has a mailto link to: `sponsors@opensourcematters.org`

It should link to: https://www.joomla.org/sponsorship-application.html

**Comment by Saurabh1** [comment]
@jeckodevelopment It was requirement from Mike Demo for client who wanted to sponsor OSM specifically hence it is created with mailto.
