### ISSUE TITLE
[jtm] banging

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#646]
Great work - thank you for doing this!

Exclamation mark or exclamation point? https://en.oxforddictionaries.com/definition/exclamation_mark

This paragraph: **When to bang your Joomla "!"** That header is OK as a 'hook' to get us to read it :) But reading further down, mark and point are used when references really should be for mark, not point.

**Comment by jeckodevelopment** [comment]
Thank you @Hils

**Comment by jeckodevelopment** [comment]
Done! Thank you!
