### ISSUE TITLE
[jtm] use of exclamation mark in html

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#647]
<title>Proper use of the Joomla! name - Joomla! Trademark &amp; Licensing</title> <<< that is the title in html for this tm docs page: https://tm.joomla.org/trademark/226-proper-use-of-the-joomla-name

In the instructions for usage of our trade mark, it says:
" Another exception is for "Joomla!" used as a title for a page on the JDoc as it may affect the search engine." ...so should those exclamation marks be there in the code? (I have only checked this one page).

**Comment by jeckodevelopment** [comment]
If i understood correctly, you're asking whether we need to use the exclamation marks in the title of the page, right?

**Comment by Hils** [comment]
yes. It is more of a question than a statement! Is it going to affect search engine function, for example, as mentioned in that JDoc?

**Comment by jeckodevelopment** [comment]
My opinion:
Since the exclamation mark is part of the Joomla! project name we should include it in titles and headers.

**Comment by Hils** [comment]
> " Another exception is for "Joomla!" used as a title for a page on the JDoc as it may affect the search engine."

So should this be changed?

**Comment by mbabker** [comment]
MediaWiki (docs site) is a special case because the page title is part of
the URL.  So when you put punctuation into the titles there it causes
issues.

For regular page titles and headings it's fine.

**Comment by Hils** [comment]
thanks for the clarification Michael, therefore it should be removed from this page - right?

https://tm.joomla.org/trademark/226-proper-use-of-the-joomla-name

**Comment by Hils** [comment]
view-source:https://tm.joomla.org/trademark/226-proper-use-of-the-joomla-name

**Comment by mbabker** [comment]
Haven't looked at the page at all, but since that's a regular Joomla site there should be no issues.  It's fine to have punctuation in the `<title>` tag.  But from a technical perspective as that exclusion states you need to leave it out on the docs wiki since that title becomes a URL segment.  Look at Joomla's page on Wikipedia as an example.

**Comment by MATsxm** [comment]
If I understand well: the title (that became the URL) ON the JDoc
example: `trademark/226-proper-use-of-the-joomla-name`

**Comment by Hils** [comment]
Thanks for the answers :) I thought that page would be on the docs wiki, erroneously.

**Comment by MATsxm** [comment]
it is...
but not a big deal as it is an EXCEPTION, an advice, not a requirement

**Comment by Hils** [comment]
you have now made me ask a supplementary @MATsxm - WHY in two locations?

**Comment by MATsxm** [comment]
because the TMTeam wanted so and because the Doc is a Participative Wiki, translatable and with a better ranking...

**Comment by Hils** [comment]
not sure what the avatar for 'shaking one's head in amazement' is but please pretend I just used it.  I shall refrain from commenting further on having two versions of the almost same thing in two different locations for the same audience.
