### ISSUE TITLE
[jtm] spello en-GB/en-US

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#648]
http://dictionary.cambridge.org/dictionary/english/emphasize

should be emphasise (three lines down, last para)

(last one from me just now ;)

**Comment by jeckodevelopment** [comment]
@Hils thanks.
Can you please let me know the page?

**Comment by Hils** [comment]
https://tm.joomla.org/trademark/226-proper-use-of-the-joomla-name

> (three lines down, last para)

sorry Luca!

**Comment by jeckodevelopment** [comment]
found and fixed. Thank you! :)
