### ISSUE TITLE
[jdown] wrong translation in download

### ISSUE THREAD

**Issue by bosyrih** [joomla/joomla-websites#649]
in https://downloads.joomla.org/latest in Arabic there is wrong translation in how many times download
times mean how many times and not time.
this occurred also in 
https://downloads.joomla.org/ar/cms-ar/joomla3 for
Joomla! 3.5.1 
Joomla! 3.4.5
Joomla! 3.0.3
Joomla! 3.0.0
Joomla! 1.5.22

in Viewed . 
the wrong translation in meaning of time that must be 'مرة'  mean once if more than one but the error is for time and not times must be 'مرة' instead of "الوقت" for just on time, the times translation is wright  but time is wrong. 
like attach file

how can i correct it i can't find it.
we must collect this sentence in all documents that's uses frequently, in one translation .

**Comment by MATsxm** [comment]
@bosyrih 
As I don't follow you on this one, could you please make the changes on Crowdin and/or comment on it?
thanks

**Comment by brianteeman** [comment]
Time as in hours and minutes
Times as in downloaded thirty times

**Comment by mbabker** [comment]
Has this been addressed?

**Comment by MATsxm** [comment]
IMHO non need as we have (or will have for few) more than 2 downloads :wink:

**Comment by MATsxm** [comment]
@bosyrih is it still an issue as there're now more than 1 download everywhere (have not checked everything but...)?

**Comment by Sandra97** [comment]
As we don't have any release with just one download, I think we can consider this issue as solved.
Closing it.
Re-open if needed.
