### ISSUE TITLE
[jdocs]exclamation mark 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#650]
When to bang your Joomla "!" :

> Our registered trademark[1] is "Joomla!" including the exclamation point. (The exclamation point is sometimes also called a "bang" from both copy editing and comic book usage.) The proper and complete use of our name is WITH the exclamation point.e describe the problem or your issue

Please note that en-GB is exclamation mark, not exclamation point.https://en.oxforddictionaries.com/definition/exclamation_mark

**Comment by MATsxm** [comment]
As this page is a protected Namespace, I will make the change.
Thanks

**Comment by MATsxm** [comment]
done.
closing - reopen if needed
Thanks
