### ISSUE TITLE
[jdown] Release announcement opens in the same window

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#653]
On FAQs there are three buttons.
Joomla Documentation and Technical Requirements open in a new window.
Release announcement opens in the same window.

**Comment by mbabker** [comment]
I've changed it for the English article.  @MATsxm will need to do relevant updates for the translation workflow.

**Comment by Sandra97** [comment]
I changed it also in the other languages available on the live site.

**Comment by MATsxm** [comment]
yeah... then you all mean I'm the only one still with it on my todo :tongue:

**Comment by MATsxm** [comment]
reopen as a reminder for me

**Comment by MATsxm** [comment]
pushed on Crowdin
closing -reopen if needed
Thanks
