### ISSUE TITLE
[jshop] correct url? 

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#654]
In the community top nav: https://community.joomla.org/the-joomla-shop.html  (https://community.joomla.org/blogs/community/3080-shop-j)

In the docs: https://shop.joomla.org/
(https://docs.joomla.org/Joomla:The_Joomla_Websites)

which should we use please? Where is our sitemap please?

**Comment by mbabker** [comment]
> Where is our sitemap please?

What sitemap?  😆 

Training and Shop were originally set to (re-)launch on their own subdomains before merging to the community site and those subdomain URLs redirect correctly.

Personal opinion, but my preference is the absolute URL with no redirects (so the cjo/shop URL).  But the redirected subdomains will be fine too.

**Comment by mikeveeckmans** [comment]
both are correct , shop.joomla.org is redirected

**Comment by Hils** [comment]
I realise that they both 'work' but is this good practice? ...and the sitemap?

**Comment by Hils** [comment]
> What sitemap? 😆

how can we organise so many sites, redirects & duplicates without having a sitemap!

**Comment by MATsxm** [comment]
I wanted to say the Doc is a Wiki then help yourself BUT...
this Doc page is protected....
ok, one more thing on MY todo :wink:
