### ISSUE TITLE
[jorg] [TO DISCUSS] Improvement for the .org home page

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#656]
[TO DISCUSS]

Despite some accusations (still giggling), I'm not against creating links to even 3rd-part websites if and only if it makes sense, there's an interest and most of all if it gives a **real** good and up to date image of The Joomla! Project and softwares.
For this purpose, it seems to me important to improve the "BTN section of the .org homepage changing the title for the btn link to the new Showcase site and adding an explicit one linked to the training website.

Thoughts and proposals?

This is just as a starting point:
![1 joomlatraining](https://cloud.githubusercontent.com/assets/1972717/18872788/351d3824-848a-11e6-9833-391da531eb7b.png)

**Comment by mbabker** [comment]
👍👍

**Comment by Sandra97** [comment]
+1

**Comment by mikeveeckmans** [comment]
+1

**Comment by jeckodevelopment** [comment]
+1
Even if i would add some text before the buttons.

**Comment by MATsxm** [comment]
@jeckodevelopment any proposal?

**Comment by jeckodevelopment** [comment]
I guess that @mikeveeckmans could be really better with this :)

**Comment by Sandra97** [comment]
Done.
Closing this issue.
Re-open if needed.
