### ISSUE TITLE
[jvols] Mark clusterer issue

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#657]
When there are two Joomlers at the same locations the map behaves weird
See https://www.dropbox.com/s/wtaejq7mx5fqy0a/jvols.mov?dl=0

**Comment by sanderpotjer** [comment]
@Radek-Suski just slightly move the coordinates of your location by editing your profile ;-)

It a default clustering script, so will need to check if we can fix it without modifying the original script.

**Comment by sanderpotjer** [comment]
@Radek-Suski the issue should be fixed now (for reference: https://github.com/joomla/volunteers.joomla.org/commit/947306f1bc01b4e3e9993632b3647e80d73372c8) . Once multiple markers are at the same location they will be spread once you click on it:
<img width="894" alt="screen shot 2016-10-04 at 23 53 28" src="https://cloud.githubusercontent.com/assets/522834/19093983/eae71478-8a8d-11e6-8010-4a1aeabc4858.png">

Thanks for reporting!

**Comment by MATsxm** [comment]
I live in an other country than @Sandra97 😄 😄 😄
