### ISSUE TITLE
[jdown] Downloaded over 0 times!

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-websites#659]
"Downloaded over 0 times!" is the lead text on https://downloads.joomla.org/

**Comment by mbabker** [comment]
Yep.  Because I didn't feel like importing the counts for all 2016 files, run a test round, and import them all again.  It'll be done for the live launch.

**Comment by mbabker** [comment]
I've loaded it since after getting the script finalized it only takes a couple of minutes to process everything.  This also gives a chance to make sure there aren't any UI related issues with the longer number strings.
