### ISSUE TITLE
[jdown] german translation translate this message

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#662]
![wp_ss_20160927_0003](https://cloud.githubusercontent.com/assets/2596554/18883296/f3fbca64-84e2-11e6-9fd9-400d58ca0b1f.png)
Same as dutch the site should be 100% translated and than there is no need for that message correct?

**Comment by Sandra97** [comment]
The message is still displayed because some strings are still displayed in English. Example: [https://downloads.joomla.org/de/cms-de/joomla25/2-5-28](https://downloads.joomla.org/de/cms-de/joomla25/2-5-28)

**Comment by zero-24** [comment]
![wp_ss_20160927_0004](https://cloud.githubusercontent.com/assets/2596554/18884833/6ba9cd08-84e9-11e6-8f27-f305891b90ee.png)
Same apply for dutch & french which don't show this message ;) let me know where we can translate these strings

**Comment by zero-24** [comment]
see here for the dutch report: https://github.com/joomla/joomla-websites/issues/652

**Comment by MATsxm** [comment]
Those strings are not yet available for t9n and mod_ for the warning message will be removed in time.

**Comment by zero-24** [comment]
:+1:

**Comment by MATsxm** [comment]
As the strings to make available for t9n is a more complex task than it appears and already on the roadmap and the WARNING is disabled, I'm closing the issue.
Can be reopen if needed.
