### ISSUE TITLE
[jdown] info/help for MD5 and SHA1 signatures

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-websites#663]
It is great to have MD5 and SHA1 signatures [here](https://downloads.joomla.org/cms/joomla3/3-6-2)
I would suggest to give (tooltip?) or link info/help for people not familiar with this.

**Comment by zero-24** [comment]
What about something like this for the FAQ:

MD5/SHA1:
The MD5 and SHA1 hashes also known as checksum for a file, is something like a fingerprint of the file. This feature can be useful both for comparing the files and their integrity control.

**Comment by mbabker** [comment]
Quick edit for English and expanding it a little bit:

What are MD5 and SHA1 signatures?
The MD5 and SHA1 signatures, also known as a checksum for a file, is
something like a file's fingerprint. These signatures can be used to
validate the integrity of the file and helps you ensure that what you have
downloaded has not been altered in any way.

**Comment by MATsxm** [comment]
:+1: 
I will add it and then push for t9n once and only once we will be sure not a single coma will be changed.

**Comment by brianteeman** [comment]
What are MD5 and SHA1 signatures?
The MD5 and SHA1 signatures, also known as a checksum for a file, are like a file's fingerprint. These signatures can be used to validate the integrity of the file and helps you ensure that what you have downloaded has not been altered in any way.

**Comment by joo7** [comment]
just another tweak :)

What are MD5 and SHA1 signatures?
The MD5 and SHA1 signatures, also known as checksums, are like fingerprints. These signatures can be used to validate the integrity of a downloaded file and help you to ensure that it has not been altered in any way.

**Comment by MATsxm** [comment]
@brianteeman 
thanks to check if we are ok with the last one or the previous?

**Comment by brianteeman** [comment]
The last one by @joo7 is fine

**Comment by MATsxm** [comment]
Pushed on source (en-GB) on live site + available for t9n on Crowdin.
Closing - reopen if needed
Thansk
