### ISSUE TITLE
[jcomm] JET typo

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#666]
> We are going to publish a list of all selected recognised community members and we your permission for it.

==>

> We are going to publish a list of all selected recognised community members and we **need** your permission for it.

**Comment by Joomv** [comment]
Will sort, was a bit sun blind. Thanks for the catch





On Wed, Sep 28, 2016 at 12:12 PM +0300, "Brian Teeman" <notifications@github.com> wrote:













We are going to publish a list of all selected recognised community members and we your permission for it.




==>




We are going to publish a list of all selected recognised community members and we need your permission for it.

**Comment by Joomv** [comment]
Done
