### ISSUE TITLE
[jdocs] update information page

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#667]
https://docs.joomla.org/J3.x:Informations_about_the_Update_to_3.6.3

**Heading: Informations about the Update to 3.6.3 - information is plural so informations is incorrect.**

"Since the Securtiy change in com_joomlaupdate with 3.6.2 it was a bit difficult to update to the last version. With 3.6.3 there is a fix in place that make this much more easy."

**Since the security change in com_joomlaupdate with 3.6.2, it was difficult to update to the last version. With 3.6.3, there is a fix in place that makes this easier.**

The rest of the document really needs proof reading with, for example, relogin changing to re-login. I don't understand a lot of it, so a Joomla technical proof reader is essential. Another example: "In 3.6.3 we have a fix in place that works like now follows:"

Sorry to trash this as it is obviously written by a non-native English writer, but it does need sorting!

**Comment by MATsxm** [comment]
@Hils 
The JDdocumentation is a wiki. 
Users are the editors and maintainers of the content.
Thank you for applying the changes on the live site, the same way you would do with Wikipedia :wink:

**Comment by Hils** [comment]
quite happy to do that but should that doc be open when it is providing core joomla info? ...and, my old login for this isn't working! (it is easier just to correct than have to type corrections out!)

**Comment by zero-24** [comment]
Sorry hils i'm not a native speaker.

**Comment by MATsxm** [comment]
@zero-24 
neither do I...
this is not a problem.... I guess :wink:

**Comment by MATsxm** [comment]
@Hils 

> quite happy to do that but should that doc be open when it is providing core joomla info?
Yes it is...
sensitive information are protected by namespace with different access rights.

> my old login for this isn't working!
just follow the steps like for every other site or create a new one.

thanks :wink:

**Comment by Hils** [comment]
not a problem @zero-24 - you have other skills :) that we need.  Please feel free to ping me if you ever feel you need something checking!

**Comment by Hils** [comment]
Thanks @MATsxm - I can do it this evening :) For the future, how can I tell which is editable and which isn't? Trial & error? is there some kind of label? (pardon my ignorance!)

**Comment by MATsxm** [comment]
@Hils 
np at all... like for every contributor, once you will try to edit/create a content, you will have a message saying the page is protected and then how to proceed.
In most of the cases, the solution (like for every Wiki) is to discuss, ask for a change on the "Talk" "Discussion" page for the specific page you want to work on.

I also always have an eye on what's going on. Especially with new accounts that are much more "under controlled" and currently quickly blocked for security reasons. If it is case, and like the message will say: just contact me and I'll be there to help and proceed the appropriate way.

**Comment by Hils** [comment]
Thanks @MATsxm  I passed the automatic reset password test, just about!, and will return later ;)

**Comment by MATsxm** [comment]
you know where  you can find me :wink:

**Comment by MATsxm** [comment]
Thanks @Hils 
Closing - reopen if needed

**Comment by Hils** [comment]
Thanks to alexred for checking the technical details - I had no idea we ever needed to log-in three times during an update! Now I know ;)

**Comment by zero-24** [comment]
btw.

>I had no idea we ever needed to log-in three times during an update! Now I know ;)

Only if you come direct from a very old version to 3.6.3 ;)

**Comment by MATsxm** [comment]
@Hils 
@zero-24 is the right guy at the right place for that :wink:

**Comment by Hils** [comment]
@zero-24 wrote the original so he must be right! (I get confused when people don't use their real names :D )
