### ISSUE TITLE
[jdown] Link on FAQs (button Technical Requirements) in Dutch does not work

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#668]
On this page: https://downloads.joomla.org/nl/faqs-nl The link from the button "Technische vereisten" does not work right. In other languages it is ok. Maybe I did something wrong translating ;-)

**Comment by Sandra97** [comment]
Thanks for the report Martijn. It's not you who did something wrong, it was me! It's corrected now and works fine.
Closing this issue.
Re-open if needed
