### ISSUE TITLE
User Registration issue

### ISSUE THREAD

**Issue by GDMEDICALGROUP** [joomla/joomla-websites#669]
When new members create a new account on the website the system does not activate or enable the account until admin manually activates account.  I have clicked the options drop down in the USER / Manage field and have tried all 3 options " None, Admin, & Self"  and all have been unsuccessful.   No matter what this field the members cannot login until admin manually approves and activates new account. I have just updated to the newest version of joomla hoping to correct this issue and still having issues.   I would like new members to be able to login and use the site after registration has been completed.  Any information would be greatly appreciated and look forward to resolving this issue.

-Respectfully,
L.S. 
info@GreenzDirectDelivery.com

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
