### ISSUE TITLE
[jrepo] Duplicate buttons on frontpage when using mobile devices

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-websites#67]
The "Download" and "Demo" buttons seems to be duplicate when the frontpage is opened on mobile. Let's hide on set of them and show our beautiful logo instead?
![voila_capture 2015-08-26_12-15-05_nachm](https://cloud.githubusercontent.com/assets/498096/9491021/4adbf7c2-4bec-11e5-961a-2df31f3742c7.png)

**Comment by Sandra97** [comment]
Agree. 
The two top buttons have been hidden on mobile. 
We're gonna look for the logo.

**Comment by MAT978** [comment]
Closing as the duplicate issue is solved and Logo part will be a Phase 2 issue
Thanks
