### ISSUE TITLE
[jdown] FAQs menuitem

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#670]
Something about the FAQ menu.
There are three buttons on this page. Two are going to another (sub)domain (Documentation and Release Announcement). One (Technical Requirements) is going to the same subdomain, but the same link is in the menu, so it is a duplicate.
I suggest: or we remove the Requerements button or we open the link in the same window (we stay on the site).

**Comment by MATsxm** [comment]
Fixed in the source language (en-GB)
will be pushed for t9n later.
Thanks

**Comment by MATsxm** [comment]
closing - thanks
reopen if needed
