### ISSUE TITLE
[jshop] the mobile menu has a misplaced external link indicator

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#671]
I hope it is clear what i mean if not please ask;) it is about the external link indicator on the mobile site for the books on amazone link:
![wp_ss_20160930_0001](https://cloud.githubusercontent.com/assets/2596554/18974672/d580913c-86a4-11e6-8d0e-16574b1d3f2a.png)
I think it should be next to the text?

**Comment by mbabker** [comment]
Looks like that's by design right now (the icons all float right but on desktop it's much less noticeable).

**Comment by Joomv** [comment]
Tweaked this, looks much better.  I will change the icon to an svg at some point soon so it can be black at desktop and white at mobile view.  Leaving open to remind me.

**Comment by zero-24** [comment]
:+1:

**Comment by zero-24** [comment]
For me it looks ok as it is. Black at the mobile and desktop is fine for me.
