### ISSUE TITLE
[jcomm] missing login form on mobile 

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#672]
If you go to the helpdesk from mobile you can't see the login form in the page.

![screenshot_2016-09-30-07-37-18](https://cloud.githubusercontent.com/assets/733133/18981699/097a21e2-86e1-11e6-97f8-993b884a4894.png)

**Comment by Joomv** [comment]
Done.

**Comment by jeckodevelopment** [comment]
Good job!
