### ISSUE TITLE
[jdown] Date Last Updated Technical Requerements

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#673]
I updated the translation in Dutch in Crowdin of this page, but the page is not updated. Is this a manuel proces?

**Comment by zero-24** [comment]
Yes it is a manuel proces.

**Comment by MartijnMaandag** [comment]
The change is operational now.

**Comment by zero-24** [comment]
Thanks to the great translation admins!

**Comment by MATsxm** [comment]
@MartijnMaandag it is always the same process: 
https://github.com/joomla/joomla-websites/issues/663#issuecomment-250501357

1. edits en live site only for the source (en-GB)
2. edits pushed on Crowdin for the source files (en-GB) then they are available fro t9n
3. t9n are manually reported on live site (+QA/QC) for the `.HTML` files (content)
4. ARS.ini file is pushed manually

This process is more work and more time but far ahead a better quality.
