### ISSUE TITLE
[jdown] Optimize Images

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#674]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdownloads.joomla.org%2F&tab=desktop

**Comment by zero-24** [comment]
Where we can find the original (maybe github repo) images to send a pull request with the optimized Images? I have not found one. ;)

**Comment by mbabker** [comment]
It's a private repo (I know some are going to groan about that, but we have pro versions of extensions installed and GPL or not I don't feel comfortable making that code so easily accessible as it feels somewhat disrespectful of those developers' work).  https://github.com/joomla/downloads.joomla.org

If you want to do it and attach a ZIP here we can easily merge that into the site/repo.

**Comment by zero-24** [comment]
http://www.jah-tz.de/downloads/download.php?file=Downloads_page.zip&folder=media/joomla/

**Comment by zero-24** [comment]
I cant fix: https://www.arvixe.com/campaigns/creatives/4163.png  this should be done by the upstream?

**Comment by mbabker** [comment]
Don't worry about that one, just the stuff we can handle on our domain is enough.

**Comment by Sandra97** [comment]
Thank you @zero-24, I'm gonna replace them now.

**Comment by Sandra97** [comment]
Done!

**Comment by zero-24** [comment]
Thanks! Just that external one is still there.

**Comment by Sandra97** [comment]
All the images are now optimised. As we can't do anything for the ad image, I'm closing this issue.
Re-open if needed.
