### ISSUE TITLE
[jdown] Item Translatability

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#675]
Everyone wants to find a solution for the untranslated item titles and descriptions.  So here's the brainstorming area to do it.

Problem: There is not data in ARS to dynamically build these things.  The only thing the items are aware of is the current release number through the associated release record.  That works to an extent (mostly for the titles and the "to" version in descriptions).

There isn't an efficient way to extrapolate the "from" version, or to tell the package type, short of string parsing the titles or the filenames.  ARS just doesn't track this level of data.  And I'm personally reluctant to hack it in; I'd like to keep our hacks to the minimum essential for what we're using the system for and I'm not convinced right now we need to add fields for these things (essentially the file type (full, patch, upgrade) and from version(s) on the non-full packages).

Right now the solutions are to string parse the titles, descriptions, or filenames to extract this data or to create language strings for every one of these.  Nobody wants 2000 language strings to translate with mostly duplicated text, so that option's off the table.  I'm reluctant to rely on the string parsing method; it's too human error prone and will require very specific text to be used each time to make the system work correctly.

The floor is your's.

**Comment by brianteeman** [comment]
Can you give an example of the specific strings you are taking about please

**Comment by mbabker** [comment]
https://downloads.joomla.org/cms/joomla3/3-6-2

Each item's title and description (`Joomla! 3.6.0 to 3.6.2 Patch Package (.zip)` and `This package is for performing updates from Joomla! 3.6.0 to 3.6.2`).

**Comment by MATsxm** [comment]
See for example on the fr-FR

![1475263712864screensave](https://cloud.githubusercontent.com/assets/1972717/19004229/d7c4b68e-8722-11e6-813c-3bedaa98e761.png)

**Comment by brianteeman** [comment]
I probably wouldn't translate the title
For the description can we not use a consistent set of descriptions with
sprintf for the numbers

**Comment by mbabker** [comment]
We can, but again, it's going to lean on whomever is entering the data to copy/paste exactly the requisite text and extracting the key elements out of the titles (using those so we know what type of package we're dealing with, and the from versions for all the upgrade related things).  And I honestly feel like relying on this is too error prone (someone omits a space, uses a stray character, or the titles change completely, and all of that processing is broken easily).

**Comment by ot2sen** [comment]
Looks like title tells the version numbers, so why not just keep the subtitle to text, meaning omitting the version number there. This would give a less error prone interaction with those translating it.
Suggested subtitle for translation: This is the full download package.

**Comment by ot2sen** [comment]
And keep the title as is. This is how it is named and what people will download, so no issue in keeping it intact

**Comment by brianteeman** [comment]
+10

**Comment by Sandra97** [comment]
I agree with @ot2sen solution, if it can be done without too many hacks.

**Comment by mbabker** [comment]
I think for our full downloads it's fine, and actually the upgrade packages should be generally OK (we honestly would need three strings for these; one for 3.x (upgrade from 2.5 and all 3.x), one for 2.5 (upgrade from 1.7), and 1.7 (upgrade from 1.6)).

I think the main problem is in the various patch packages.  These should be used for very explicit version scenarios and are the ones that need the most processing to figure out versions to display, and as such need the most explanation.

**Comment by mbabker** [comment]
@JacquesR and I have gone through this a few times before but he's commented that the file names on their own (which is what the titles are derived from) aren't always clear on how they should be used.  That's part of the reason I feel like the descriptions need to be adequate.  If we can find a way to write them without version numbers that's the best option, but I also feel like we'd lose some clarity there.

**Comment by ot2sen** [comment]
From what I can see at the site, the patches do hold the information needed and would only double if used in subtitles too. Suggest same approach here as the full packages.
For example:

"Joomla! 3.6.0 to 3.6.2 Patch Package (.zip) 
This package is for performing updates from Joomla! 3.6.0 to 3.6.2"

Could basically be: This package perform updates from one version to another.
Then you could recycle the use of 1 single string

**Comment by ot2sen** [comment]
For the wider update packages you could modify the text to keep it neutral of last number.
This package is for performing updates from Joomla! 2.5 and previous 3.x releases to 3.6.2
could become:
This package is for performing updates from Joomla! 2.5 and previous 3.x releases to latest release. (See filename for specifics)

**Comment by Sandra97** [comment]
I don't think replacing 3.6.2 by "Latest release" would be a solution, as it means, for example, in the sentence below, that 3.6.1 would be replaced by "latest release" which is of course incorrect: 

> This package is for performing updates from Joomla! 2.5 and previous 3.x releases to 3.6.1

**Comment by mbabker** [comment]
> This package is for performing updates from Joomla! 2.5 and previous 3.x releases to this version.

Instead of using "latest release"

**Comment by Sandra97** [comment]
True, it works better like that

**Comment by MATsxm** [comment]
still not convinced by any proposal but I have nothing better to suggest.
The Title is IMHO not a real problem if it stays like this even if I know some Community will "ask" about it...
TBH, at this point, I will leave this issue open and will call for ideas on few channels

**Comment by zero-24** [comment]
What is about the following.

We can extend extensions field list per plugin (no hack into the original extension required): https://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin (To be checked if com_ars support this)

If com_ars support this we can add the fields that let us choose the type and that allows us to create any input we need to build language strings.

Sure we still relay on user input but it is not any input (e.g. add one space more that expected) it is just a list (dropdown or radio) that limit the implemented strings.

With that additional fields we can build our translation strings and add the correct versions to the sprintf.

If there is not all infos to build the language string we can still fallback to the original desc field.

If we choose this way it should not be droped just because we need to edit all releases i can help with that. Or we just run a script that does everything for the default strings (just once) and we need to fix than just the releases that can be auto corrected (maybe a wrong comment etc)

Any ideas?

**Comment by mbabker** [comment]
ARS AFAIK (@wilsonge might have to clarify more here, I'm not a FOF pro) doesn't support extending forms that way.  I'm trying to not add fields unless we absolutely need them (the field to declare an ARS category (how we're grouping our major versions) as unsupported was a major need and affects a lot of our presentation) and I don't think adding fields for the sake of translatability falls under an absolute need.

**Comment by zero-24** [comment]
hmm :(

Ok one more: we let everything as it is in com_ars and just use the desc field.

There we need to include just: "COM_DOWNLOADS_FULL_PACKAGE|3.6.3" -> Done. Just a explode by | and sprintf with string and version.
And for the 1.5 patch -> patch updates: COM_DOWNLAODS_UPDATE_PATCH_TO_PATCH|1.5.20|1.5.21

If there is a wrong syntax or anything is broken we just show a default string

COM_DOWNLOADS_UPDATE_DEFAULT="This package allows you to update Joomla" (without any version etc as they are in the package name and titel)

**Comment by mbabker** [comment]
At the end of the day though that still boils down to string parsing something.  If we're sure the filenames have used the exact same convention since 1.0.0 it can work using the filenames since those are NOT human generated (unless George has been secretly renaming things on us...), otherwise we're going to need category (or potentially release) specific rules.  Anything else though ultimately is either going to boil down to yet another hack of ARS or too easily screwed up by human entry (the change on all 2016 item titles required 3 layout changes, and that was for one word).

Pulling up https://docs.google.com/spreadsheets/d/11eqHWrY69YC4gPUBZr8OFdJl0XVStyjcAmmv3tET6c8/edit?usp=sharing and looking just at the first few 1.0 releases, I see inconsistencies already with the full packages.  So that already makes the string parsing option harder as we need specific rules for at least two releases.

I'm not saying the ideas are bad by any means, but one of my main concerns is what we're gaining by adding code that's only use is to build language keys with proper sprintf.  If we had ways to make use of the package type options, I'd be more willing to add that to the ARS items.  So far we don't have a strong argument for using that data other than language keys.
