### ISSUE TITLE
[jexam] Mobile friendly

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#677]
I just visited the exam page on my phone and got a page that's not mobile friendly.
I'm using Chrome on Android 6.0.1.

Screenshot:
![screenshot_20161003-080415](https://cloud.githubusercontent.com/assets/7062995/19030368/939c698e-894d-11e6-943b-eb6045fd3093.png)

**Comment by jeckodevelopment** [comment]
Known issue! Thank you for reporting.

**Comment by sam-suresh** [comment]
Thank you for reporting.
We are completely aware of that and working on new frontend. 
However at the moment we have to work on some other high priority tasks. 
This will be completed soon.

**Comment by sanderpotjer** [comment]
@sam-suresh may I suggest to leave the issue open until resolved, also prevents duplicate reports

**Comment by sam-suresh** [comment]
The directory is now mobile friendly. 
![screen shot 2016-11-13 at 6 40 09 pm](https://cloud.githubusercontent.com/assets/5198092/20244997/b9f2d480-a9d0-11e6-8f51-22e021e3788e.png)
