### ISSUE TITLE
[jdocs] problem with edit of Help36:Site_Global_Configuration

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#679]
I try to change this document:
https://docs.joomla.org/Help36:Site_Global_Configuration
I can change the screenshot, but when i try to edit the text in "Site" I can't. It says "This is a translation of https://docs.joomla.org/Chunk30:Help-3x-global-configuration" 
When I try to edit this it says "It does not exist"

**Comment by MATsxm** [comment]
You should be able to reach:
https://docs.joomla.org/Chunk30:Help-3x-global-configuration
(then edit/translate it the way you want)
When you are working on Helpscreens, it's always better to work directly from the concernened url (not the edit on frontend) as they are so many Chunks and includes that sometimes the t9n tags are cut and then issues occure.
(note Fuzzybot will have to crawl again this page but you should be able to already work on the chunk: https://docs.joomla.org/Chunk30:Help-3x-global-configuration )

**Comment by MartijnMaandag** [comment]
Yes, thanks, I see now that i must use the edit button on top, not the one in a subsection.

**Comment by MATsxm** [comment]
There was an issue anyway with the language Tag. Thanks
