### ISSUE TITLE
[jrepo] Background image on frontpage cut off

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-websites#68]
On viewports between 480px and 980px the background image on the frontpage is cut of on the left and right. Looks like a "background-size: contain" is missing.

![voila_capture 2015-08-26_12-17-14_nachm](https://cloud.githubusercontent.com/assets/498096/9491056/8c461094-4bec-11e5-8345-d7672dea30f7.png)

**Comment by MAT978** [comment]
Known issue thanks - see #60 
Thanks

**Comment by MAT978** [comment]
Closed as duplicate
