### ISSUE TITLE
[jshow] 

### ISSUE THREAD

**Issue by Mareblu** [joomla/joomla-websites#680]
Regarding J show

Mandatory fields not marked with red if not filled: responsive and framework.

It is demanding smallest size of image 687px (I think) and if you make smallest then it is mandatory to crop it. Didnt understood the process. Croping is mandatory!? Can I make exact size?

**Comment by sebastienlapoux** [comment]
Hi @Mareblu ,
Thanks for your feedback about responsive and framework fields. Fixed
Can you please try again?

About croping, I don't follow you. It's not requesting smallest size. Where do you read this please?

Thanks.
