### ISSUE TITLE
Category total does not match actual shown entries in showcase.joomla.org

### ISSUE THREAD

**Issue by webilicious** [joomla/joomla-websites#681]
At the bottom of the showcase.joomla.org home page, the total number of entries in each category is shown but when I browse the category, the number of entries is sometimes less than this.

E.g. the Travel category currently has a total of 5 entries but only 3 are shown.

![showcase](https://cloud.githubusercontent.com/assets/5836876/19057439/911f2c86-8a1b-11e6-8a19-c7bb4fc01ad2.png)

I assume that some entries are awaiting moderation but it might be better to show the total number of approved entries rather than including unmoderated entries in the total number which is confusing.

**Comment by oliviernolbert** [comment]
Hi,

It should be fixed. Thanks to check and close if ok.

Olivier

**Comment by Sandra97** [comment]
I confirm it's fixed.
Closing this issue.
Re-open if needed
