### ISSUE TITLE
[jshow]  showcase submit

### ISSUE THREAD

**Issue by jflash** [joomla/joomla-websites#682]
On site https://showcase.joomla.org after submitting my website i get an error:
Error
Invalid Parent ID
An error has occurred.
My username jflash and tried it three times now. I fill all fields, uploaded picture, cropping it and push the button for submit. Webpage reloads with this error and website does not submitted.

**Comment by sebastienlapoux** [comment]
Hi jflash,
Thanks for your feedback.
Can you please let us which category you choose?

Can you please try again and let us know?

Thanks

**Comment by mscruse** [comment]
I'm not sure if this will reopen this bug but I am having the same problem.  I've successfully submitted one, but any others fail with the Invalid Parent ID error.

The category I'm trying to post in is Finance.

I've tried several times on different days - same issue.

(mscruse is my Showcase ID).

**Comment by sebastienlapoux** [comment]
Thanks you!

So sorry... Not easy to reproduce and to solve...

Please try again.

**Comment by mscruse** [comment]
Thank you Sebastien. The problem seems to be resolved. I was able to successfully add the entry I was having trouble with, plus 4 other new entries.
