### ISSUE TITLE
Site showcase validation

### ISSUE THREAD

**Issue by micker** [joomla/joomla-websites#683]
hello i site showcase when we submit site its a nightmare with validation
1 if we submit item without good information system was blocked impossible to continu, we can correct it but we can't use submit button
ex : forgot to set responsive => form say you need this, but you can't resubmit
if we use a too light description same behavior, we can correct it but don't submit
2 if we upload image crop and re order at first attempt same things validation is dead
thanks for this tools but need to smoother submission

**Comment by sebastienlapoux** [comment]
Hi @micker,
Thanks. Can you please try again?

**Comment by micker** [comment]
yes better !
thanks for fast correction
