### ISSUE TITLE
[jshow] Unable to submit a new site

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#684]
I tried to submit a new site and it was impossible as many of the fields said they were required even though they were filled out.

I was using latest Chrome browser and looked in inspector and there were no JS errors.

http://i.imgur.com/g5dJEXF.png

Maybe selecting "none" for template framework kicked it off?

**Comment by sebastienlapoux** [comment]
Hi @aDaneInSpain,
Thanks a lot!
Can you please try again?
Sebastien.

**Comment by jflash** [comment]
Works!
