### ISSUE TITLE
showcase.joomla.org - submitting new site - Error (not authorised)

### ISSUE THREAD

**Issue by photografx** [joomla/joomla-websites#686]
simply does't work ... for me (?)

My Account > my Sites > + Add New Button (or link below)
just brings me to the homepage with folowing error message

**Error
You are not authorised to view this resource.**

**Comment by Sandra97** [comment]
I just had the same issue

**Comment by Sandra97** [comment]
It now works for me. 
@photografx, could you please try again and confirm it works for you too.

**Comment by sebastienlapoux** [comment]
Hi @photografx yes thanks. We closed the submission form during some time to fix an issue.
Please try again.

@Sandra97 the Joomla menu submit site link has been set visible only for admin. But has been changed again by someone who is not me or Olivier.

**Comment by mikeveeckmans** [comment]
@sebastienlapoux me, sorry for that. it gave the errors when people were submitting or tried to submit, didn't know you diabled it to fix another issue.

**Comment by sebastienlapoux** [comment]
thanks @mikeveeckmans! 
Like you know not possible to work like this. It's very confusing. Please contact me on glip, on skype or by email before such action. Thanks!
