### ISSUE TITLE
[Crowdin] Update general information on Crowdin

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#689]
Both intro text for the main "Joomla's projects" and the sub-project "Joomla! CMS" need to be updated.

**Comment by Sandra97** [comment]
One month later, still need to be updated. As well as the link to download which should be now https://downloads.joomla.org

**Comment by jeckodevelopment** [comment]
who is in charge for that?

**Comment by MATsxm** [comment]
that's the question; who knows... 😈 
seriously, @Bakual used to do the job (always a reliable and great help on this topic) but since, AFAIK, he wants to be aside from the PLT mission, I guess we should not bother him and the PLT (regarding the CMS project that is under its responsability) should find someone who can help (personally, I would like Thomas to stay in charge of it but I can understand he doesn't want anymore) or replace Thomas then... good luck.

**Comment by jeckodevelopment** [comment]
I'll try to help with this. But i need to have access to crowdin.

**Comment by Bakual** [comment]
PLT is in charge of the account, which actually is written when you look how the "Owner" is named. I shared the access credentials a few times already in the maintainer chat and they should also be in the vault to my knowledge 😄 
Javier should get the emails from that account, but since it's a forwarding email one could add other recipients as well.

But just contact me if you need a reminder or guidance or anything updated. I don't have an issue maintaining Crowdin on behalf of the PLT 😄

**Comment by jeckodevelopment** [comment]
Thank you @Bakual :)

**Comment by jeckodevelopment** [comment]
I updated the link to downloads.joomla.org
let me know if I have to update other text/descriptions.

**Comment by MATsxm** [comment]
@Sandra97 will, thanks...
off topics but as it concerns also @Bakual and you @jeckodevelopment, just a reminder about the fr-CA core pack that looks "dead" since 3.5.1 (not even sure it was a "real" fr-CA but more a fr-FR) and that Jean-François Gagnon (I will help him) would like to reactivate on Crowdin.
I don't know what the process is (I know he contacted the coordinator already (no answers)) but following the PLT's decision, I guess this one is a good candidate 😉 
In any case, if you decide to open it on Crowdin, Jean-François thinks (I agree) that it would be better to start from scratch.
Thanks

**Comment by Sandra97** [comment]
Here it is! 
Just few changes: 2 links edited and ! added to Joomla ;)

Joomla! is an open source content management system (CMS), which enables you to build Web sites and powerful online applications.
Download: https://downloads.joomla.org

A list of the available language packs can be found at http://community.joomla.org/translations/joomla-3-translations.html

This project is set up so anyone can contribute by suggesting translations and voting on existing suggestions.
The language coordinators will then proofread the suggestions and approve/reject them.
The generated language packs will only contain approved translations to ensure a high quality of the translations.
The language packs generated by Crowdin can be downloaded in the translation overview (or using the URL https://crowdin.com/download/project/joomla-cms.zip) and should be able to be installed in the Joomla! Extension Manager.

**Comment by jeckodevelopment** [comment]
done! Thanks!

**Comment by Sandra97** [comment]
Thanks Luca!

**Comment by jeckodevelopment** [comment]
you're welcome.
Closing this, re-open if needed
