### ISSUE TITLE
[jrepo] CSS alignment

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#69]
CSS alignment 
http://repository.joomla.org/announcements.html

![Alignment](http://s17.postimg.org/l2b1n44fj/Screen_Shot_2015_08_26_at_7_42_06_am.png)

Might be able to remove the words "Details" as well?

**Comment by Sandra97** [comment]
CSS alignment corrected, "details" removed. 
Please check.

**Comment by pbwebdev** [comment]
I'm happy
