### ISSUE TITLE
[jdocs] translation tags visible

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#690]
Hello @MAT.
I am trying to update the help screens.
Now I have a problem creating new chunks and translation tags.
In this item I wanted to create a new chunk: https://docs.joomla.org/Help36:Site_Maintenance_Clear_Cache
The chunk I created is "Delete All" near the bottom: https://docs.joomla.org/Chunk30:Help_screen_toolbar_icon_Delete_All
I will have done something wrong with the translation tags because they are visible in het original document.
Question: What do I do when I create a new chunk, not disturbing the translations.

Another question: I want to rename an existing chunk (because the original text is changed). How can I find the places where the chunk is used, so I can change the use everywhere?

**Comment by MATsxm** [comment]
@MartijnMaandag 
nothing has changed with this process.
please do **NOT** deal with t9n tags, ask me for it.

> Question: What do I do when I create a new chunk, not disturbing the translations.

be really carefull to chack that it doesn't exist, even with another prefix.
If you really want to create it then do it the way you did and let me know (I will have a notif anyway but just in case) for the t9n tags/marks

> I want to rename an existing chunk (because the original text is changed). How can I find the places where the chunk is used, so I can change the use everywhere?

**NEVER** rename a chunk even if the title is wrong. We don't care about it and could even call it 1 - 2 or 3, we don't care.

Also and about the Chunk you want to work on. The "Template way" it is create `{{{1|items}}}` is absolutly NOT adapted to the t9n process as there're so many possibilities of variables that impact gender, plurals, grammar and even the word ordering. This was made before the Doc being available for t9n.
I never thought anyway that this process is an help and as we have a good TranslationMemory system, it's not a big deal to translate a string used in several places without this "template feature" that is more a - than a +.
better for my sanity and the one of the translators :stuck_out_tongue_closed_eyes: :wink: 

`*'''Delete All:''' Deletes all the items. Works with all items.`

*********
Anyway. Fixed here - thanks
Closing - reopen if needed
