### ISSUE TITLE
 [jshow] Is someone checking these submissions?

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#693]
Having just taken two sites from the showcase, at random, it is disappointing that the descriptions look as though they have been submitted by non-native en-GB speakers and that these entries have not been grammar-checked. Is there some formal method of moderation by the showcase team? Are we making everyone submit in en-GB?

**Comment by sebastienlapoux** [comment]
Hi @Hils,
Thanks! Already discuss about this.
If you have an idea how to manage this it's welcome. We have no enough native english speaker into JSD team. If you can join the team to manage this it would be so nice.

Thanks again.
