### ISSUE TITLE
[jshow] Nederland

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#694]
In en-GB we use Nederlands and not Nederland. https://showcase.joomla.org/nederland.html

**Comment by sanderpotjer** [comment]
@Hils the main menu says "By Country", and it looks like (most) of the subitems are by the local native language name of the country. In that case "Nederland" is correct (the country), and "Nederlands" is incorrect (the language).

**Comment by Hils** [comment]
Thank you Sander. So those sub-items are in the lang of the relevant country whereas everything else seems to be in en-GB? (always a tricky decision!)

**Comment by sebastienlapoux** [comment]
Thanks @Hils and @sanderpotjer!
@Hils, additional information on https://github.com/joomla/joomla-websites/issues/695 
It seems for you a tricky decision, sorry for that!
Maybe the idea of theses pages is bad, let discuss about this.
Thanks.

**Comment by Hils** [comment]
@sebastienlapoux 

> Maybe the idea of theses pages is bad, let discuss about this.

Absolutely not bad! It is a very good idea and something we have been looking forward to and it is looking very good. I just did a little research just now to see how others dealt with this and, if the decision to submit in English has been made (which it seems to have) we must expect that some submissions will just not make sense unless they are moderated. But again, the non-moderation for submitted text must have already been made and it would seem too late to change this. 

We also give a lot of opportunity for submitters to send a lot of info about their sites. Other ones I have checked, like Drupal, don't:

https://drupalsites.net/submit-your-drupal-site

My main point I think is that if we as Joomla are showcasing these sites to show how good Joomla is, we need to check things like the submitter's grammar - at the very least to check it makes sense.  If it is just a place where people can show what their Joomla site is like and how they used joomla, cool - we don't need to check grammar. I don't know what the criteria is for this.

> It seems for you a tricky decision, sorry for that!

I think you may have misunderstood me! It is always tricky, for example on the BBC News, whether a UK person uses the local name for a city or country rather than the one the UK is accustomed to using. Guessing that happens in all countries, not just the UK - that's what makes it tricky with our internationalisation. (big subject ;).

But everything else in those menus and sub-items is in en-GB. There is nothing to alert a person to change to another language - all we are shown is that we can browse a country. If the site was localised in various languages, then it would be a different matter and, if it was localised in nl-NL, the menu should say Nederland (thanks Sander) rather than Netherlands in a en-GB item.

You and your team must have spent hours thinking about all this so I apologise for mentioning things at this late hour!

**Comment by brianteeman** [comment]
> In en-GB we use Nederlands and not Nederland.

Actually in en-GB it is Netherlands

**Comment by Hils** [comment]
Of course Brian, thank you! and usually we say The Netherlands. Excuse my temporary muddlement!

**Comment by MartijnMaandag** [comment]
I agree with Hils, so Deutschland must be Germany also (I am not native speaking)

**Comment by sebastienlapoux** [comment]
Thanks @Hils .

Agree. Countries have been changed with English term.

Concerning english check, please continue on the other issue.
I closed this one.

**Comment by ot2sen** [comment]
@sebastienlapoux  Guess 'French' should also be changed to 'France' then to reflect country as the others in the list.

**Comment by sebastienlapoux** [comment]
lol! thanks @ot2sen . Fixed
