### ISSUE TITLE
[jshow] "Odd" search filter display

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#695]
https://showcase.joomla.org/deutschland.html (or any of the country pages)

The country filter is removed from the search section and it leaves a very obvious empty spot.

**Comment by sebastienlapoux** [comment]
Thanks @mbabker!
Related to https://github.com/joomla/joomla-websites/issues/694#issuecomment-251698542

Yes, the purpose of these pages are to provide a dedicated page for local countries and so to navigate only into sites of the concerned country.

Yes, the "empty" space in search section can be avoid.

Any idea to improve these pages are welcome!

**Comment by sebastienlapoux** [comment]
We alternated position of Country field with Featured one.
The white space is now on the right which less confuse.
I close this issue. Re-open it if needed.
