### ISSUE TITLE
[jshow] Request to increase inactivity timeout to allow additional time to submit entries

### ISSUE THREAD

**Issue by cogliano** [joomla/joomla-websites#698]
With several text fields to enter for a site submission, I have been logged out a few times when submitting a new site.  I request increasing the inactivity timeout in order to have a better chance of completing the submission. Also, notifying users of how long they have to enter a site before they are logged out would be helpful too.

**Comment by digglescreative** [comment]
Yes please.

**Comment by sebastienlapoux** [comment]
Hi,

Thanks for your comments.

We will not changed the session lifetime to keep standard web statistics.

In the next update of the site (today or monday), the site will use the Joomla mechanism about "Keep-alive behaviour forced on Admin/Site Form views.".

It will solve your issue.

I'm closing this issue.
