### ISSUE TITLE
[jshop] Adjust padding in the Cart icon

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#699]
If you look at the "cart" icon in the menu, it seems to be cut.

![cjocart](https://cloud.githubusercontent.com/assets/733133/19131253/0d7ab3e8-8b4f-11e6-9eff-094e22c4e172.PNG)

**Comment by Joomv** [comment]
Done

**Comment by jeckodevelopment** [comment]
Thanks!!!!
