### ISSUE TITLE
[ALL] Add links report links

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#7]
Add in the report links linking to github for users to login and report issues about the websites.

This is a requirement across all Joomla website assets.

e.g link in the footer of the joomla.org website should be

[Report an Issue](https://github.com/joomla/joomla-websites/issues/new?title=%5Bjorg%5D%20&body=Please%20describe%20the%20problem%20or%20your%20issue)

**Comment by mbabker** [comment]
I'll do this for the base 3.x template and share out a package via e-mail in the next couple of days.

**Comment by jneubauer** [comment]
done for JWC (http://conference.joomla.org) - lower right footer on all pages

**Comment by mbabker** [comment]
This is the footer setup I'm rolling with unless someone screams otherwise :wink:

![screen shot 2015-08-05 at 7 22 13 pm](https://cloud.githubusercontent.com/assets/368545/9100302/59667b0a-3ba7-11e5-95d3-dd6d546ec2ac.png)

**Comment by jneubauer** [comment]
![NOOOO!!!](http://38.media.tumblr.com/d423a44b264d872d3ddccd8ae7df802c/tumblr_mnfwx3nT6w1rynk4uo4_250.gif)

**Comment by jneubauer** [comment]
is this footer similar to the header menu in that it comes from the CDN, not the local site?
if so, the link Pete provided (coming from the template in the README it looks like), specifies the site in the title ([jorg], [jwc], [jcomm], etc) - does this footer allow that?

**Comment by mbabker** [comment]
The footer is built into the template and not managed by CDN.  For those with access, https://github.com/joomla/jdotorgtemplate/commit/0cf66dda9823a6dc2c1ddb5c54a04bcb019bd717 has the full commit with the template changes to build the links.  For those without, [this helper](https://gist.github.com/mbabker/27d1c9b8f72a76562292) is building the link with the right tag and also deciding if a site has a custom tracker and linking to that instead (I know that applies mostly to non-CMS installs, but the behavior is there).

**Comment by jneubauer** [comment]
nice! thanks!

**Comment by Hutchy68** [comment]
thanks @mbabker 

Since docs is a custom written template by me to match the rest of the sites I added the link.

![image](https://cloud.githubusercontent.com/assets/3527469/9150586/2311e47c-3daf-11e5-9a46-2c4b87695e31.png)

I added "with this website" to the text too. Visions of support questions... how do I do this with Joomla! dancing in my head. :smiley:

**Comment by mbabker** [comment]
Link is in updated template being shared with admins.  Someone else can decide whether this stays open until all sites are compliant.

**Comment by MAT978** [comment]
Thanks for that!
I hope that some will follow the great intiative and even better, adopt the common footer!

**Comment by MATsxm** [comment]
closing as many (not enough are using the CDN menu) - 
Open an issue for individual sites that do not provide the report link
