### ISSUE TITLE
[jrepo] Vertical spacing after images

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#70]
Images without captions need more spacing and padding
http://repository.joomla.org/announcements.html

![](http://s17.postimg.org/vb3isxshb/Screen_Shot_2015_08_26_at_7_42_14_am.png)

**Comment by Sandra97** [comment]
A small bottom margin has been added to the blog images.
Please check.

**Comment by pbwebdev** [comment]
I'd double it personally.

.blog img {
    margin-bottom: 10px;
}

**Comment by Sandra97** [comment]
Agree on the principle, but as it's applied to all blog images, I have first to check the "side effects"

**Comment by Sandra97** [comment]
.blog img {
margin-bottom: 10px;
}
has been applied.
