### ISSUE TITLE
[jshow] Country: menu items and select field don't match

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#700]
If you go to: https://showcase.joomla.org/ you have a "by Country" view in the top menu that shows just 5 countries using native names.
But in the module `Find the site you're looking for` you'll have a "Country" dropdown that shows 29 Countries.
I know that it could be difficult to keep up-to-date the dropdown list in the top menu and it will become also unuseful when it will show such an huge number of countries.

In my opinion, the dropdown "By Country" should be removed from the top menu and "By Country" should be clickable and linked to the list of countries available. 

![jshowcc](https://cloud.githubusercontent.com/assets/733133/19131576/3d5fb9cc-8b50-11e6-9937-5df803878b80.PNG)

![jshowcc1](https://cloud.githubusercontent.com/assets/733133/19131600/4cdecb68-8b50-11e6-9925-675bba27fa3e.PNG)

**Comment by sebastienlapoux** [comment]
Hi @jeckodevelopment ,

The rule is: when a country has more than 20 sites, the country is added to the drop down list.
We made an arbitrary choice about the first 5 countries listed which received biggest number of site during first days after launch.

I'm closing this issue. Please open it again if needed.

**Comment by jeckodevelopment** [comment]
Just my personal opinion: you should allow a "List of countries" view, when clicking on the "Country" menu item.
