### ISSUE TITLE
[jcomm] community Page looks down

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#701]
Error displaying the error page: Application Instantiation Error: Could not connect to MySQL.

Maybe MySQL is down on the server?

**Comment by MATsxm** [comment]
not the only one... ;)
ticket's on its way

**Comment by mbabker** [comment]
MySQL is down on the server.  Waiting for someone to answer the ticket.

**Comment by zero-24** [comment]
:+1: Thanks.

**Comment by MATsxm** [comment]
odc and JCM are back
other should follow

**Comment by zero-24** [comment]
`Error displaying the error page: Application Instantiation Error: Table '#__session' is read only SQL=DELETE FROM `#__session` WHERE `time` < '1475700593'`

**Comment by zero-24** [comment]
on community

**Comment by mbabker** [comment]
> it appears that your /home partition was maxed out. Additionally, it is looking as if we might need to restore the databases due to InnoDB corruption

Keeping open

**Comment by zero-24** [comment]
now: Error displaying the error page: Application Instantiation Error: Error initialising the session.

**Comment by MATsxm** [comment]
same on volunteers

**Comment by mbabker** [comment]
Everything but www, update, downloads, JED, forum, developer, framework, and issues is on that server.

Don't need a site by site list 😉

**Comment by mbabker** [comment]
> The MySQL service is up and running under force recovery 6, which is not optimal. I am working on restoring the databases to ensure that the data loss is minimal or avoided entirely.

So sit tight everyone.

**Comment by wilsonge** [comment]
😢 😆 😨

**Comment by mbabker** [comment]
> The restores are still underway, but about 50% done at this time from what I am able to see.

**Comment by mbabker** [comment]
Everything but the OSM and Community Portal sites are back online.  A second database restore is being run for those sites since the first wasn't complete.

**Comment by sam-suresh** [comment]
Current status:
- Ticket Update -
Hello,

We had to stop the restore due to some disk space issues, We have resolved them and restarted the restore, We will update you once done. Thank you.

----
Abizer R.
Rochen Limited

**Comment by sebastienlapoux** [comment]
Any news Sam please?

**Comment by sam-suresh** [comment]
Rochen working on it and they are the one able to fix it. 
So we have to wait for them now!

**Comment by sam-suresh** [comment]
Restoration Completed and all sites loading properly

**Comment by sanderpotjer** [comment]
For https://volunteers.joomla.org/ we still have issue, but will follow up with the ticket at Rochen

**Comment by sam-suresh** [comment]
Yes looks like on volunteers portal still showing SQL error now

**Comment by sanderpotjer** [comment]
For your information, if any data/changes on your database are missing: 
>Today's backup (generated on October 5, 2016 8:00:17 PM CDT) is corrupted, so I restored the the databases from October 4, 2016 8:00:15 PM CDT.

So please be aware that data is lost!

**Comment by sam-suresh** [comment]
For those have self backup newer version than 4th October, you can restore it asap if there important data in there between 4th - 5th Oct. 

Let your team members know about this for possible work recovery.

**Comment by sebastienlapoux** [comment]
Sorry but stop!

Please explain reasons of the amazing huge outage.
Please explain reasons of losing data.

**Comment by sam-suresh** [comment]
This is a question only Rochen can answer.
But for now they have to fix other issues that in list.
I guess CLT members will ask them what really happened

**Comment by sanderpotjer** [comment]
We have contacted Rochen for more details on the issue. As soon as we have more information we will post it here.

**Comment by sebastienlapoux** [comment]
Thanks @sam-suresh and @sanderpotjer! Waiting your feedback.

**Comment by sebastienlapoux** [comment]
Issues are back!!!

**Comment by Radek-Suski** [comment]
Is anybody using Uptime Robot? I mean someone who has the possibility to write a ticket. It could spare us a lot of time

**Comment by sanderpotjer** [comment]
Thanks all, contacted Rochen again to get it fixed.

I do receive monitoring myself, but that was 2 min ago and submitted the ticket before responding here.

**Comment by Radek-Suski** [comment]
Thanks

**Comment by sanderpotjer** [comment]
Sites are up again, hopefully for a very long time now....

**Comment by wilsonge** [comment]
Magazine is still dead.....

**Comment by zero-24** [comment]
Error displaying the error page: Application Instantiation Error: Table './magazine_mag2016/#__session' is marked as crashed and should be repaired SQL=SELECT `session_id` FROM `#__session` WHERE `session_id` = 'e17a692a3ee0617ef7367dad15254082' LIMIT 1

**Comment by sam-suresh** [comment]
Ticket updated.

**Comment by sanderpotjer** [comment]
Asked Rochen to repair that table

**Comment by sam-suresh** [comment]
I have created a public monitor to see the sites status:
https://stats.uptimerobot.com/oVJJqSrX7

If you are a webmaster, please post your email/twitter handle so I can add to receive notification. You also can post these info in the Glip chat webmaster group.

**Comment by zero-24** [comment]
So all up again? And we can close here? Or is anything still open?

**Comment by sam-suresh** [comment]
Yes. The monitor I posted above gives you live status.

**Comment by zero-24** [comment]
community is missing there? And i guess some more like downloads etc?

**Comment by zero-24** [comment]
I guess this list: https://github.com/joomla/joomla-websites#websites is nearly complete ;)

**Comment by sebastienlapoux** [comment]
@sam-suresh can you please add me on webmaster glip group?

**Comment by sam-suresh** [comment]
@zero-24 I have updated all sites now. Let me know if missed any: https://stats.uptimerobot.com/oVJJqSrX7
@sebastienlapoux added. This group was created by @mbabker

**Comment by zero-24** [comment]
Closing than. Thanks!
