### ISSUE TITLE
Website submissions disappeared from My Sites.

### ISSUE THREAD

**Issue by digglescreative** [joomla/joomla-websites#704]
Yesterday, I added 3 websites through the My Sites control panel. I was able to see that they were listed as pending. Today they are gone.

**Comment by mbabker** [comment]
It might have to do with yesterday's outage that required some rollbacks in
the databases.

**Comment by digglescreative** [comment]
Assuming that means I need to redo them?

**Comment by mbabker** [comment]
I'd wait for Sebastien to confirm but I'd say yes you'll most likely need
to.  I'm not 100% sure which sites lost data.

**Comment by digglescreative** [comment]
Hey thank you!

On another note, while researching today I ran across a github project that you were working on. It is related to SEF Advanced Mode. Removing the ID from Joomla URLs. The thread was from 2014 I believe. Curious to know what progress has been made on that.

Sorry if this is not the right place to ask a question about something unrelated to my OP.

**Comment by sebastienlapoux** [comment]
Hi,
Thanks @mbabker.

So yes and so sorry @digglescreative. Please submit again your sites.
Thanks a lot for your understanding!

We're adding another backup system to no more facing this situation.
