### ISSUE TITLE
[jdown] Alternate Language meta tags have bad URLs

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#705]
- https://downloads.joomla.org/cms
- https://downloads.joomla.org/ar/cms-ar

The meta tags for the alternate languages are incorrect, for example from the English page:

```html
<link href="https://downloads.joomla.org/fr/cms" rel="alternate" hreflang="fr-FR" />
```

The link should be `fr/cms-fr`

Taking the language code off the alias would fix it for the downloads section.  Since ARS doesn't natively support associations I think this section is relying on the menu item associations to compute that, but even that seems to be calculating things incorrectly.

**Comment by Sandra97** [comment]
Yep, for theses pages, the best solution would be to remove the language codes at the end of the menu items.

**Comment by MATsxm** [comment]
do it... (or I will later)
I will send you the bill of my psychiatrist :wink:

**Comment by Sandra97** [comment]
I remove the language code at the end of the alias for all Latest release and CMS menu items, corrected the links on the FAQs pages and do necessary redirections for these menu item.
Minion will have fun with managing all the other upcoming 404 linked to these menu items 😝 
I'm closing this issue.
Re-open if needed.
