### ISSUE TITLE
[jdown] ARS sections missing alternate language meta

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#706]
- https://downloads.joomla.org/latest
- https://downloads.joomla.org/ar/latest
- https://downloads.joomla.org/cms/joomla3
- https://downloads.joomla.org/ar/cms/joomla3

The latest release page and any of the subpages in the downloads section lacks the alternate language metadata.  Part of this is probably related to ARS not supporting associations natively, part of it because the entire ARS repository isn't actually using language codes for its data (everything is saved for all languages for I hope obvious reasons).

**Comment by mbabker** [comment]
I've gotten this hacked together.  A cursory glance over the affected views looks like everything is good.

- https://downloads.joomla.org/latest
- https://downloads.joomla.org/cms/joomla3
- https://downloads.joomla.org/cms/joomla3/3-6-2

If someone could confirm there aren't any issues this is completed.

**Comment by Sandra97** [comment]
I checked these pages as well as others, everything looks good now. Thank you!

**Comment by MATsxm** [comment]
me like!
