### ISSUE TITLE
[jorg] Move technical requirements

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#707]
When the new downloads.joomla.org will be out of the beta period, the link "Technical Requirements" in joomla.org that now goes to `https://www.joomla.org/about-joomla/technical-requirements.html` should go to: `https://downloads.joomla.org/technical-requirements`

![techreq](https://cloud.githubusercontent.com/assets/733133/19213301/db41dac0-8d68-11e6-8365-854f1b4c0009.PNG)

**Comment by MATsxm** [comment]
already on toDo 😉

**Comment by jeckodevelopment** [comment]
you're too efficient :P

**Comment by Sandra97** [comment]
For information, I started a todo list for the links to change on October 17. 

Template
- [ ] Top menu
- [ ] Top button

Joomla.org
- [ ] redirection of the Download page
- [ ] redirection of the Technical Requirements

Joomla.org Homepage
- [ ] replace video by Download visual
- [ ] banner button 'Download'
- [ ] publish announcement
- [ ] getting started: change links of Joomla Download Page (and its name) and Technical Requirements

Joomla.org About us:
- [ ] last paragraph: link in the 1st sentence + image

Joomla/3
- [ ] Change link of the Download button for every languages

Dev
- [ ] CMS Download page: change link and name of the link in the 1st paragraph

JDocs
- [ ] link of the top button
- [ ] Menu link
