### ISSUE TITLE
Create "Optional" Requirements Page

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#708]
See https://github.com/joomla/joomla-cms/issues/12362

Create a page somewhere that we can list out "optional" technical requirements; dependencies needed to run different internal APIs but aren't required to actually install and run Joomla.  Some of what I'm thinking is listed at https://github.com/joomla/joomla-cms/issues/12362#issuecomment-252491844

**Comment by jeckodevelopment** [comment]
Should we write here the requirements for each feature?

**Comment by mbabker** [comment]
Sub-Requirements:
- Application
    - JApplicationDaemon: Requires PHP's `ext/pcntl` and `ext/posix`
- Archive
    - BZ2: Requires PHP's `ext/bz2`
    - GZip: Requires PHP's `ext/zlib`
    - Zip: Requires PHP's `ext/zip` or `ext/zlib`
- Cache
    - APC: Requires PHP's `ext/apc` on PHP 5.3 or 5.4, `ext/apcu` on PHP 5.5 or 5.6, unsupported on PHP 7.x (someone may need to validate me on this one)
    - APCu: Requires PHP's `ext/apcu` on PHP 5.3+
    - CacheLite: Requires the PEAR Cache_Lite package (tested on 1.7.16, will work OK with 1.8)
    - Memcache: Requires PHP's `ext/memcache` and a Memcache server
    - Memcached: Requires PHP's `ext/memcached` and a Memcached server
    - Redis: Requires PHP's `ext/redis` and a Redis server
    - Wincache: Requires PHP's `ext/wincache` (Windows only)
    - XCache: Requires PHP's `ext/xcache`
- Client adapters
    - LDAP: Requires PHP's `ext/ldap`
    - HTTP/Curl: Requires PHP's `ext/curl`
    - HTTP/Socket: Requires PHP's `fsockopen()` function be enabled
    - HTTP/Stream: Requires PHP's `fopen()` function and `allow_url_fopen` enabled
- Cryptography
    - JCrypt: Requires PHP's `ext/mcrypt`
    - JKeychain: Requires PHP's `ext/openssl`
- Database
    - Microsoft SQL Azure: Requires PHP's `ext/sqlsrv` (Windows only)
    - Microsoft SQL Server: Requires PHP's `ext/sqlsrv` (Windows only)
    - MySQL: Requires PHP's `ext/mysql` (unsupported on PHP 7.x)
    - MySQLi: Requires PHP's `ext/mysqli`
    - Oracle: Requires PHP's `ext/pdo` with Oracle support (available for 3PD only; the CMS won't run with it)
    - PDO MySQL: Requires PHP's `ext/pdo` with MySQL support
    - PostgreSQL: Requires PHP's `ext/pgsql`
    - SQLite: Requires PHP's `ext/pdo` with SQLite support (available for 3PD only; the CMS won't run with it)
- Image
    - Requires PHP's `ext/gd`
- Session
    - APC: Requires PHP's `ext/apc` on PHP 5.3 or 5.4, `ext/apcu` on PHP 5.5 or 5.6, unsupported on PHP 7.x (someone may need to validate me on this one)
    - Memcache: Requires PHP's `ext/memcache` and a Memcache server
    - Memcached: Requires PHP's `ext/memcached` and a Memcached server
    - Wincache: Requires PHP's `ext/wincache` (Windows only)
    - XCache: Requires PHP's `ext/xcache`

Optional Improvements
- String
    - Enable PHP's `ext/mbstring` for the `phputf8` library to use native functions

**Comment by demis-palma** [comment]
Could you please notify here when this page will be published?

**Comment by Sandra97** [comment]
Here's the temporary page on Jdocs: [https://docs.joomla.org/User:Sandra97/Optional_Technical_Requirements](https://docs.joomla.org/User:Sandra97/Optional_Technical_Requirements).
The page will be published in a few days so if you have any change to do or something to add before it goes live, just tell me.

**Comment by MATsxm** [comment]
[Question]
What about adding a Q/A in the FAQs on [Downloads site](https://downloads.joomla.org/faqs) with a link to it?

**Comment by MATsxm** [comment]
BTW: https://docs.joomla.org/Optional_Technical_Requirements

**Comment by mbabker** [comment]
Looks fine to me.  I'd say incorporate a link from the tech requirements page on the downloads site to it and we're good to go (I say that over the FAQs as it's directly related, it can be in the footer with all the other extra info).

**Comment by Sandra97** [comment]
I'll incorporate a link of the tech requirements page this afternoon.
