### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by bigmarko88** [joomla/joomla-websites#709]
I am the Head of ICT in my organisation, I have not been able to access our backend CMS page, and the login in details are very correct... 
The website is, www.birs.gov.ng. The CMS login details are 
Please can you help me rectify this issue?

**Comment by Radek-Suski** [comment]
[edit] Removed credentials.

This issue tracker is only for reporting issues with official Joomla! websites. If you are looking for support please ask for help at: https://forum.joomla.org

And please, never, ever post your access data in a publicly available website.

Regards,
Radek
