### ISSUE TITLE
[jrepo] Mobile home page - Overlap call to action Links

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#71]
Positioning and vertical alignment.

![](http://s17.postimg.org/ka8dnx08f/Screen_Shot_2015_08_26_at_7_44_02_am.png)

**Comment by Sandra97** [comment]
Could you give me your screen size/resolution so that I can reproduce the issue?

**Comment by pbwebdev** [comment]
Strangely it was on an iphone5, safari landscape 

I can't reproduce it again.

**Comment by MAT978** [comment]
Closed - feel free to reopen if needed
Thanks

**Comment by mbabker** [comment]
The template uses the same type of JavaScript to try and push the body into the right place as is used on the J3 admin template which is known to have the occasional quirk with Safari.  I see it a fair bit on the API site, but usually one refresh and it's good for the rest of the session (in Chrome anyway).  I think there's a pull request on the CMS repo tweaking the script a bit for Safari so it is more consistently correct, I might need to test that on the template here too.
