### ISSUE TITLE
[jshow] Stretched images look blurry and embarrasing

### ISSUE THREAD

**Issue by lyquix-owner** [joomla/joomla-websites#710]
The photo galleries of the showcase sites stretch images from their natural size of 687x412 to 693x416, making them blurry.

Is there a reason to not allow high-resolution images? 

As a showcase site we should be able to have a lightbox that shows the screenshot in detail. 687px wide is so 1999. If we are trying to showcase Joomla sites, the image galleries are definitively letting everybody down.

**Comment by sebastienlapoux** [comment]
Hi @lyquix-owner,

Will have a look on your first point.

Not agree with the rest of your comment. 
What's a high-resolution images about a site when the majority of site is no more than 1200px width?

Thanks.

**Comment by sebastienlapoux** [comment]
First point fixed. Thanks!
I closed this issue. Please open it again if needed.

**Comment by lyquix-owner** [comment]
Thanks for fixing the stretching!
