### ISSUE TITLE
[jexam]  Character ^ don't work in SEB

### ISSUE THREAD

**Issue by patjun** [joomla/joomla-websites#711]
I can't enter my password in the Save Exam Browser, because my password includes the character ^ and it seems the SEB does not allow this character.

**Comment by Radek-Suski** [comment]
I am a bit confused; what's SEB?

**Comment by patjun** [comment]
Save Exam Browser

**Comment by sam-suresh** [comment]
I have tested this password `PassTest^123` and it is working. 
As SEB not allow copy&paste, you need to type the ^ sign by pressing SHIFT+6 on Mac. 

Please check again.

**Comment by patjun** [comment]
Hi Sam,
thanks for your answer. I tried again.

- I started the SEB with the with the start1909.seb
- I can use the character in the Username and in the Secret Key field, but not in the Passwort field. If i try i always get this nice, annoying Ping. ;-) 

Maybe it happens because of the different keyboard layout. They key is in the upper left below the ESC Key on the german keyboard. Please look at the attached photo.

![img_20161018_092645](https://cloud.githubusercontent.com/assets/226981/19468539/2ab1306e-9517-11e6-8e19-da622f9a6e0c.jpg)

**Comment by sam-suresh** [comment]
I have created a new user `passtest` password is `PassTest^123`
Can you try this one if it work in your keyboard layout.
