### ISSUE TITLE
Top Navigation menus missing

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-websites#713]
All menus on top of Joomla.org is missing.

https://www.joomla.org/

http://screenshot.net/d86mzfl

**Comment by mikeveeckmans** [comment]
Menu's show perfect here...

**Comment by sam-suresh** [comment]
Looks like menus are back without explanation.

**Comment by mikeveeckmans** [comment]
Ok, if occur again please re-open

**Comment by mbabker** [comment]
Just for reference the file that loads from gets cached by the template and there's a hardcoded 2 second timeout on the request to load it.  So if for whatever reason the CDN node's being slow to respond it can cause the header and/or footer to disappear for a short period of time.
