### ISSUE TITLE
[jdocs]  translate tag

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#714]
https://docs.joomla.org/Customising_the_Login_Form_module

Are all those translate tags supposed to be visible

**Comment by MATsxm** [comment]
Fixed - Thanks 
(WOW... last update in 2012 :dizzy_face:)

Note: Martjin and I are currently working on this topic (mainly on helpScreens), but thanks to let me know when you find such a page.
Closing - reopen if needed
