### ISSUE TITLE
[jenkins] Automate docker-joomla deployment

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#717]
To deploy updates on the https://github.com/joomla/docker-joomla repo, I have to:
- SSH into `developer.joomla.org` and edit the https://developer.joomla.org/latest_version.json file
- SSH into the Jenkins box and run the `update.sh` script from the `docker-joomla` repo (the `sed` commands it uses don't work right on Mac), commit and push the changes
- Fork and edit https://github.com/docker-library/official-images/blob/master/library/joomla with the result of the `generate-stackbrew-library.sh` script from the `docker-joomla` repo and issue a pull request for the update

The first two steps can be automated.  Probably the third step too using GitHub's API.  Let's try to improve this.

**Comment by zero-24** [comment]
> SSH into developer.joomla.org and edit the https://developer.joomla.org/latest_version.json file

Is is a requirement to host that on developer.joomla.org or can this be moved to update.joomla.org ? So it can be included in the release preperation PRs?

**Comment by zero-24** [comment]
> SSH into the Jenkins box and run the update.sh script from the docker-joomla repo (the sed commands it uses don't work right on Mac), commit and push the changes

Can jenkins run a script after we have tagged a stable release?

**Comment by mbabker** [comment]
> Is is a requirement to host that on developer.joomla.org or can this be moved to update.joomla.org ? So it can be included in the release preperation PRs?

Not a requirement, I just needed something I could easily use as a source for the current version.  Most optimal would be to use the XML files themselves, but I am terrible with shell scripts and went for what I found to be the quickest and easiest solution.  It's quicker and easier to get into the dev site than it is the update CDN so that's where I dumped it.

> Can jenkins run a script after we have tagged a stable release?

If we set up a job to run things after a tag is pushed to the repo we probably could.  Or take the automated "run when a tag is pushed" condition out of it and just require someone to log into the server and click the "build now" button.  It has to be done after the packages are published since it includes a SHA1 generation step.

**Comment by zero-24** [comment]
>It's quicker and easier to get into the dev site than it is the update CDN so that's where I dumped it.

I mean that it don't need one additional step to login into anything ;)

So it can be included in the regular PR to update the XML files and is included into the git push (or anyother upload method we use)

>and just require someone to log into the server and click the "build now" button. 

Would be one step less and does not require SSH access to anything :smile:

**Comment by mbabker** [comment]
Like I said, a lot of it was just me throwing stuff together in the quickest way possible.  I found using the dev site quicker than the update CDN, in part because of the file refresh times (we'd probably need to edit the `.htaccess` there to not cache that file for very long, same as we do for the XML files).

**Comment by zero-24** [comment]
IIRC we just need to include 'JSON' here: https://github.com/joomla/update.joomla.org/blob/master/www/.htaccess#L1-L3 ?

**Comment by mbabker** [comment]
Yes that'd deal with the file caching.

Another option, which would improve the Dockerfile generation and also expose more data in a useful programmatic manner would be to tweak the JSON API that ARS already has and build where we don't have it already.  So part of the reason that `latest_version.json` file exists is so I don't have to either manually edit the update scripts or run them specifying a version parameter and so that can be used to download the full ZIP package to write the SHA1 into a variable there.  If the latest release and a SHA1 of the packages could be pulled from the downloads site completely that'd eliminate some of the manual work at the expense of more code work on our side.

Though, to be quite honest, I actually think it would be good for us to expose the JSON API in ARS in a publicly consumable manner, especially for the checksums.  Plus that data could be used elsewhere either by the project or by third parties.

I just need another 18 hours in the day to find time to work on that.

**Comment by mbabker** [comment]
This is in better shape now.

The repo has a `update.php` file which will fetch the latest version and the SHA1 signature for the `Full_Package.zip` from the downloads site API and use those values to update the `Dockerfile` of each variant.

The only thing that isn't automated is the pull request on the official-images repo.

**Comment by mbabker** [comment]
Jenkins box is dead.  Closing, will integrate this into a replacement system.
