### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by respirarsalud** [joomla/joomla-websites#718]
I do not remember my password and when I try to restore it  dosent  allows me because it dosent  gives the password to  superusers but that is the only user in there.

http://www.respirarsalud.com/administrator/index.php

**Comment by zero-24** [comment]
Please post to the forum.joomla.org there a ways to reset the PW using the database see: https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

**Comment by MATsxm** [comment]
Thanks @zero-24
