### ISSUE TITLE
[jdev] 

### ISSUE THREAD

**Issue by steinsson** [joomla/joomla-websites#719]
The latest update of Joomla (3.6.3) breaks 'Custom Module' editing mode.
Firefox - Module editing mode opens up, but no buttons work
Chrome - Only a white page appears with the name of the module in a 'drop-down' box
Tested on 2 websites hosted at Siteground
![module_broken_1](https://cloud.githubusercontent.com/assets/9568847/19513420/5372e3bc-95df-11e6-8311-163865a1bed2.png)
![module_broken_2](https://cloud.githubusercontent.com/assets/9568847/19513419/5371adb2-95df-11e6-8e23-7235ca9258ec.png)
![module_broken_3](https://cloud.githubusercontent.com/assets/9568847/19513418/536fad78-95df-11e6-8e2b-75a619063712.jpg)

**Comment by mikeveeckmans** [comment]
This repo is for reporting issues with the joomla websites only. 
You can find more information about your issue on : https://docs.joomla.org/J3.x:Can%27t_edit_modules_after_update_to_3.6.3 

Thank you.

**Comment by steinsson** [comment]
Thank you Mike :)
