### ISSUE TITLE
[jrepo] Banner Responsive Issues

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#72]
Banner needs to be replaced.

Change out with proper CSS and HTML text rather than the image

![image](https://cloud.githubusercontent.com/assets/3688954/9492392/715ec106-4c3a-11e5-98b8-8638ed05e447.png)

**Comment by MAT978** [comment]
Agree with the "text" note but this is a restyling/rebuiling feature.
here we are talking about an upgrade
Thanks

**Comment by MAT978** [comment]
Closed as duplicate - please see #60 
Please reopen if needed
