### ISSUE TITLE
[jhelp] joomlaupdate help page

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#720]
https://help.joomla.org/proxy/index.php?keyref=Help36:Components_Joomla_Update

Shows **Help35:Components Joomla Update** in the title

**Comment by MATsxm** [comment]
Fixed thanks
Closing - reopen if needed



_(NOTE to self: force a change via the t9n system what will force FuzzyBot to crawl the page and then will propose a new "title")_

**Comment by brianteeman** [comment]
Thanks
