### ISSUE TITLE
[jdocs] Dead links

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#721]
On this page: https://docs.joomla.org/J3.x:Updating_from_an_existing_version 
There are two dead link to a page (Known upgrading issues and solutions) which is deleted by @MATsxm

**Comment by MATsxm** [comment]
After the restoration of the page, I now remember why I had deleted this page whose architecture is **NOT** compatible with the multilingual system.
For now, I leave it active but this page will need to be completely rebuilt with a new table architecture listing the links only in en-GB and let the `S:MyLanguage` works the way it should be.

Closing at this point - reopen if needed
