### ISSUE TITLE
Save Failed error on 'Joomler' registration - volunteers.joomla.org

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-websites#722]
Fill in all stared fields @ https://volunteers.joomla.org/register and click 'Create your Joomler profiles' returns the following error...

**COM_VOLUNTEERS_REGISTRATION_SAVE_FAILED**

**Comment by sanderpotjer** [comment]
@ciar4n thank you for reporting the issue! This should be fixed now and you should be able to register now.
