### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by GalenMcK** [joomla/joomla-websites#727]
After installing a new version my capacity to edit modules is go. Click on a module get a small box with the name of the module. Go back to the modules screen that module is locked. What can I do?

**Comment by zero-24** [comment]
Please use the forum for support https://forum.joomla.org. 

I don't understand your problem. If you mean the joomla update please clear you joomla / browser cache. if that don't help please contact the forum at https://forum.joomla.org.

This is the tracker for issues with *joomla.org webseites ;)

**Comment by GalenMcK** [comment]
Sorry, I updated Joomla on a site. After the update I am no longer able to access modules for editing. When on the Modules page I click a module (example Main Menu) and I get this screen.



When I click the back arrow, I get back to the Modules page and the Main Menu is locked 

I tried clearing cache and that didn’t help.

Thanks.
