### ISSUE TITLE
[jdocs] Please create a new page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#728]
After the decision taken by PLT during last meeting, the content in the file CREDITS (that is out of date) will be removed.

This file contains all the names of the old contributors before moving to GitHub.

PLT decided to move all the content to a dedicated Joomla! Documentation page.

> This topic came out in the CMS Maintenance Team. The CREDITS file is out of date and it includes all the contributors before the migration to Github. https://github.com/joomla/joomla-cms/commits/staging/installation/CREDITS . PLT decided to remove the content from the file and move it to a page in the Joomla! Docs. Credits file will include a link to that page.

From https://volunteers.joomla.org/leadership/production-leadership-team/reports/353-plt-meeting-october-20-2016

CREDITS file will include a link to the JDocs page with the old content and a link to the GitHub page where all the current contributors are shown.

Current CREDITS file is: https://github.com/joomla/joomla-cms/blob/staging/installation/CREDITS

Thanks.

**Comment by Sandra97** [comment]
Luca, it's a wiki so you can create this page by yourself ;)

**Comment by MATsxm** [comment]
@jeckodevelopment just let me know when the page is ready, then I will "namespace" it

**Comment by jeckodevelopment** [comment]
Thanks! @Sandra97 is helping me to create a good looking page 📄

**Comment by Sandra97** [comment]
You're welcome!

**Comment by MATsxm** [comment]
https://docs.joomla.org/Joomla:Joomla_Version_Credits
Closing - Reopen if needed

**Comment by zero-24** [comment]
You did not close ;)

**Comment by MATsxm** [comment]
seriously??? 😉

**Comment by zero-24** [comment]
:+1:

**Comment by jeckodevelopment** [comment]
Thank you
