### ISSUE TITLE
[update.joomla.org] 

### ISSUE THREAD

**Issue by cserem** [joomla/joomla-websites#729]
The SSL certificate chain for  "update.joomla.org" is wrong. Some SSL libraries are failing to verify the certificate, and thus making it impossible to update use joomla's build in updater.

Could you look into this?

**Comment by mbabker** [comment]
Please describe how it's "wrong".  FWIW the certificate was just renewed and if I'm not mistaken the configuration is the same as it was previously.

**Comment by cserem** [comment]
The current certificate order for update.joomla.org is joomla-geotrust-rapidssl. It should be joomla-rapidssl-geotrust just like on www.joomla.org

**Comment by mbabker** [comment]
Thanks.

**Comment by mbabker** [comment]
From hosting:

> It does not appear that the order of the CA bundle is the issue, as I updated the order according to your bug report thread and that did not make a difference on the SSLLabs results. I've reached out to our SSL vendor to see if the SSL can be reissued under a SHA2 root, as I see it's currently using a 'GeoTrust Global CA SHA1' root. 

> I'll let you know once we've heard back from the SSL vendor.

**Comment by cserem** [comment]
Despite the weak SHA1 certificate, now that the order of the certificates have changed my update problem is resolved.
