### ISSUE TITLE
[jrepo] vertical spacing

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#73]
Adding this in content area
http://repository.joomla.org/about-joomla/contribute-to-joomla.html

White space is nice

LESS/CSS

.item-page{
    padding-bottom: 4em;
    
    h2 {
        font-size: 22px;
        line-height: 24px;
        margin-top: 1.5em;
    }
}

![image](https://cloud.githubusercontent.com/assets/3688954/9492459/1e55dd7c-4c3b-11e5-9a9a-8de0bb1fd985.png)

**Comment by pbwebdev** [comment]
I suggest adding also 

.item-page{
padding-top:2em;
}

**Comment by Sandra97** [comment]
Agree with you for adding some white space before and after.
I added a top padding of 1em, and a bottom padding of 2em. (IMHO 2em and 4em were a bit too much).
Please check.

**Comment by MAT978** [comment]
Please @pbwebdev check before closing ;)

**Comment by pbwebdev** [comment]
I like the whitespace. Personal taste I guess @Sandra97 

What about the margin-top: 1.5em?

h2 {
   margin-top: 1.5em;
}

**Comment by Sandra97** [comment]
The margin-top of all h2 of item-page has been applied.
@pbwebdev Please check and close if it's ok for you

**Comment by MAT978** [comment]
Solved then closed - Thanks
Reopen if needed
