### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by miosadm** [joomla/joomla-websites#730]
I get this error in Swedish then i upgrade from 3.6.3 to 3.6.4
Det senaste anropet nekades eftersom det innehöll ett felaktigt igennkänningstecken. Uppdatera sidan och försök igen.

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
