### ISSUE TITLE
[jdown] Sponsor Question

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#731]
On this page: https://downloads.joomla.org/faqs, in "hosting", Arvixe is mentioned as sponsor.
@JoeJoomla, do we have to replace it by Bluehost?
Thanks!

**Comment by JoeJoomla** [comment]
Wow, good find.

I would change it to Bluehost.

Do you have access?

Kpe

**Comment by Sandra97** [comment]
I'll change Arvixe into Bluehost.
For the link, is it this one: https://mailtrack.io/trace/link/77d78fb6ad707f78bb53011dedda4b36365c32f4?url=http%3A%2F%2Fbluehost.com%2Ftrack%2Fjoomlaorg&signature=e46edbe739b0411d

**Comment by Sandra97** [comment]
@JoeJoomla, can you confirm me the link so that I can do the changes?

**Comment by mikeveeckmans** [comment]
As far as i've seen this is correct

**Comment by JoeJoomla** [comment]
Hi Sandra,

Alfred says the link is OK but we can just use this if we like:

http://bluehost.com/track/joomlaorg <http://bluehost.com/track/joomlaorg> 

Best regards,


Joe Sonne
eMail: joe.sonne@opensourcematters.org

**Comment by Sandra97** [comment]
Hi Joe, 
It should be https and not http, right?

**Comment by Sandra97** [comment]
Changes are done on download page of jorg and Downloads site.
Closing this issue.
Re-opne if needed.
