### ISSUE TITLE
[jdocs] Helpscreens

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#734]
Helpscreens are driving me crazy.
We do have this screen: https://docs.joomla.org/Help36:Menus_Menu_Item_Contact_Single_Contact
I want to change the text "Menu Location" into "Parent Item"
There is a chunk, Menu Location which is called:
{{chunk30:colheader|Menu Location/<translate>
en</translate>}}
I changed the chunk two days ago: https://docs.joomla.org/Chunk30:Help_screen_column_header_Menu_Location
The text is now: Parent Item
It does not show in the first screen.

**Comment by MATsxm** [comment]
Fixed - explaination will come later :wink: 
![giphy 1](https://cloud.githubusercontent.com/assets/1972717/19779090/91d6a7e6-9c4d-11e6-9d64-d81dbe158e8e.gif)
