### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Sharzeh** [joomla/joomla-websites#736]
The [https://forum.joomla.org] is down. Any visibility when it becomes on?

**Comment by Sandra97** [comment]
Forum is working for me. @Sharzeh can you check again?

**Comment by zero-24** [comment]
https://stats.uptimerobot.com/oVJJqSrX7/778232605 At least the ping works.

**Comment by Sandra97** [comment]
Closing this issue.
Re-open if needed.
