### ISSUE TITLE
[joomla.org] downloads announcement

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#738]
Really tiny issue but there is a missing dash 
> Andre Pereira da Silva Arkadiy Sedelnikov `

Should be

> Andre Pereira da Silva - Arkadiy Sedelnikov

**Comment by MATsxm** [comment]
done thanks

**Comment by brianteeman** [comment]
Thanks. Only a little thing but you now how people can get when their name
is wrong

**Comment by mbabker** [comment]
Not a clue what you're talking about, Brain.

**Comment by brianteeman** [comment]
More than happy with that typo. Joomla.org has done it many times
