### ISSUE TITLE
Jhackguard error when uploading jpeg & PNG

### ISSUE THREAD

**Issue by ANDarby505** [joomla/joomla-websites#739]
I am following same process for uploading images to my website as in the past, but now I am getting an error that states "File upload denied by JHackGuard. Cymru malware hash database hit.".

Please advise on how to move past this and get my image uploaded

Thank you
Adarby
![joomla error](https://cloud.githubusercontent.com/assets/23242666/19975662/075f1550-a1aa-11e6-99bd-69ce64ead0b8.PNG)

**Comment by Radek-Suski** [comment]
Please only use this repository to report issues with `*.joomla.org` websites.
