### ISSUE TITLE
[jrd] 

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#740]
Hi,

After been logged on JRD site, I can see the edit link of my ressource but after clicking on it I see

![jrd-edit-listing](https://cloud.githubusercontent.com/assets/13470265/19979616/62521a10-a1fb-11e6-8442-b6b72ad31cc0.png)

Thanks for your help.

**Comment by Sandra97** [comment]
@sebastienlapoux Do you still have this issue? If not, thanks to close it.

**Comment by sebastienlapoux** [comment]
Thanks @Sandra97 . It's working now and I can edit my listing.

**Comment by Sandra97** [comment]
Merci Sébastien !
Closing this issue. 
Re-open if needed.
