### ISSUE TITLE
[josm] Homepage outdated elements

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#743]
Could you please update the screenshot as well as the number of downloads?
We're over 77 millions.
Thank you!
![index](https://cloud.githubusercontent.com/assets/4682328/20037047/299beb92-a3ef-11e6-9dbe-4be7871f73b8.png)

**Comment by Saurabh1** [comment]
I am on it. Updated in Designers team to give me new Image. Changed the text with 77 MIllion though. Thanks for catching it :-)

**Comment by Saurabh1** [comment]
@Sandra97 Updated site with new graphics provided by Elisa. Please check and let me know. I had to change the text to match the site graphics with 75 Mil as per your talk with her. 
Closing the task.

**Comment by Sandra97** [comment]
Thanks @Saurabh1 & @coolcat-creations. It looks good now!  👍
