### ISSUE TITLE
[josm] Edit proposal for Joomla! Page

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#744]
In the website lists, could you please add the new Downloads portal: https://downloads.joomla.org

Also, te "bang" is not correctly used in the intro.
It should be:

> (...) Joomla! is created as an open-source project where individuals and teams contribute their skills to its development as well as its supporting systems.
While Joomla! is packed with features, its greatest quality is that it is extremely extensible. Because of its extensible structure, there aren't many things you cannot do with Joomla. 

Also, except Resources site, all the websites are now https, can you make the change?

Thank you!

**Comment by Saurabh1** [comment]
@Sandra97 Can you please provide me URL where I should add this change & add this new Download portal link ? 

About SSL(https) part, I do not have more details about it how to change in there. So I have to check for that.

**Comment by Sandra97** [comment]
@Saurabh1 It's on this page: http://opensourcematters.org/joomla.html
And for the site list, they are all https except resources which is still http.

**Comment by Saurabh1** [comment]
I checked Resources and it looks like updated. 
Updated Text with Bang ;) 
I have updated all links with https and also added Download portal in there. 
Closing the issue. Reopen if needed.

**Comment by Sandra97** [comment]
Thanks @Saurabh1 

Resources give an error with https (that's why I indicate http for it and not https).
And still one little issue with the bang (in the 2nd paragraph):

`Joomla!.`

As there's a punctuation mark just after the word Joomla, the bang should not be present.

Seems I missed also some other little things on this page (sorry):

- Wikipedia line: The bang is missing "Joomla is released under the"   (and the Wikipedia link should be also https)
- It's Volunteers Portal (with an "s")
- Extensions Directory (with an "s")
- The Documentation is for all users, not only end-users so better maybe just mention "Joomla! Official Documentation"

Thank you!

**Comment by Saurabh1** [comment]
@Sandra97 Somehow it worked for me with https for Resources site. 
Fixed the rest. 
Thanks

**Comment by Sandra97** [comment]
Thanks Saurabh!
