### ISSUE TITLE
[jshow] No review after issues fixed?

### ISSUE THREAD

**Issue by lyquix-owner** [joomla/joomla-websites#745]
A few weeks ago I submitted multiple sites. Some of them were rejected because some issues with the screenshots.

The issues have been resolved but it doesn't look like the sites have been reviewed again.

I don't see a way to re-submit or ask for a new review. Am I missing something?

https://showcase.joomla.org/my-account/my-sites/form/showcase_items.html?id=16860&return=aHR0cHM6Ly9zaG93Y2FzZS5qb29tbGEub3JnL215LWFjY291bnQvbXktc2l0ZXMuaHRtbA==
https://showcase.joomla.org/my-account/my-sites/form/showcase_items.html?id=16859&return=aHR0cHM6Ly9zaG93Y2FzZS5qb29tbGEub3JnL215LWFjY291bnQvbXktc2l0ZXMuaHRtbA==
https://showcase.joomla.org/my-account/my-sites/form/showcase_items.html?id=16858&return=aHR0cHM6Ly9zaG93Y2FzZS5qb29tbGEub3JnL215LWFjY291bnQvbXktc2l0ZXMuaHRtbA==

**Comment by jeckodevelopment** [comment]
Hey @lyquix-owner 
this is not the right place to ask for support with your listings.
You should use the "Report" button within JSD to ask for support.

**Comment by lyquix-owner** [comment]
Can you provide a link? When I click on "Report an Issue" I am directed here.

I don't see any other method to get in touch with the admins.

**Comment by lyquix-owner** [comment]
This is in regards to sites that have not been approved yet. There is no "Report" button when I edit them.

**Comment by jeckodevelopment** [comment]
I asked also the JSD Team to publish an easier way to get support.
By the way, please use the "Report" button in other listings.

**Comment by lyquix-owner** [comment]
Thanks!
