### ISSUE TITLE
[jcomm] FAQ's to FAQs

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#747]
Typo in a dropdown menu item on the JUG section of CJO
https://community.joomla.org/user-groups/rules-and-faqs.html

![jugfaqs](https://cloud.githubusercontent.com/assets/733133/20065683/4311ef92-a50f-11e6-92d1-dcb4bdfb707f.PNG)

and also in the title
`FAQ's` should be `FAQs`

![faqx](https://cloud.githubusercontent.com/assets/733133/20065690/48dc670e-a50f-11e6-9b65-512f7dec4c8a.PNG)

**Comment by brianteeman** [comment]
Good spot. It's a common mistake.

**Comment by Sandra97** [comment]
Fixed.
Closing this issue.
Re-open if needed.
