### ISSUE TITLE
[jorg] Inconsistent use of cases for announcements headings

### ISSUE THREAD

**Issue by alexsmirnov73** [joomla/joomla-websites#748]
Just a heads up on inconsistent use of cases in headings on our main page at joomla.org: some words start from upper case and some are in lower. 
![inconsistent_use_of_case_in_headings](https://cloud.githubusercontent.com/assets/1631532/20101865/abbbe51e-a5bb-11e6-9ca0-d836f1cabe6e.png)

Cheers,

Alex

**Comment by Sandra97** [comment]
Even if Americans use uppercase nearly everywhere, I don't see any reason to capitalize "only".
Closing this issue.
Re-open if needed.
