### ISSUE TITLE
[jorg] Feature Request: Joomla.org button for community chat!

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-websites#749]
This is not really a issue but more like a feature request. I together with a lot of others are hoping to get the Joomla community more connected via the excellent Gitter chat room that is already available and has been for quite some time. 

Sadly only a few are familiar with it. So my request is to make a big button on the joomla.org website guiding people to this chatroom. It should mention something like: Joomla Community Chat.
(Joomla.org is not responsible for content written in this chat!) or something similar. I am sure the Legal team can come up with something.

The chat room in question:

https://gitter.im/joomla/joomla-cms

The more people are available on this chat the more people can help each other especially for the quick questions the chat is ideal. Hopefully this is considered and approved.

**Comment by MATsxm** [comment]
@hennysmafter 
Another channel?
What more than Glip?

**Comment by hennysmafter** [comment]
@MATsxm Alright then if it is Glip where Joomla Users can chat with each other and solve problems then put a big fat Glip Chat button on the site. Forum/GoogleMailing does not work at all. You post a question and if you are lucky someone looks into it.

So this chatting functionality is important it is quick and easy for everyone to understand. I am not familiar with Glip but if it allows to chat and let users login with their twitter/github accounts then yeah good alternative. 

But what is the problem for users to be part of the Gitter chat aswell. There is a reason why this chat is created in the first place. It is not something I just came up with. We just need more traffic going to it so more questions get answers and more questions are asked.

So if it is Gitter or Glip doesn't really matter. The point is to get the community to know of these channels. Currently when you go to the Joomla.org website you see nothing about any chat.

**Comment by jeckodevelopment** [comment]
Please don't add other channels :)
Glip is the tool used throughout the Joomla! Community to chat with people and within teams.

But @hennysmafter the chat in general is not intended to ask for support. People should use the forum for this.

**Comment by Sandra97** [comment]
The Forum is here to answer any questions and help fixing issues. No need to add another channel to our already long list of channels/properties.
I'm closing this issue.
Re-open if needed.

**Comment by LukeDouglas2** [comment]
I miss the Joomla Google Groups as that was a much better place to keep threads isolated. :(
