### ISSUE TITLE
[jrd] Public profil link

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#750]
Hi,
Why such link http://resources.joomla.org/en/component/zoo/item/sebastien-lapoux are public?
If public from where can we access this link on the site?

Why such link have no good URL rewriting?

Is it normal to see "zoo" in all links?

Thanks.

**Comment by Sandra97** [comment]
@genr8r Could you please answer to Sébastien?
Thank you!

**Comment by sebastienlapoux** [comment]
@genr8r please answer.

**Comment by genr8r** [comment]
My apologies for not hitting this much sooner.  What page created this link? When I browse to your individual listing from the frontend of the site I get...

https://resources.joomla.org/en/item/sebastien-lapoux

**Comment by sebastienlapoux** [comment]
Thanks!
If I click on the https://resources.joomla.org/en/item/sebastien-lapoux and then on edit item link
![image](https://cloud.githubusercontent.com/assets/13470265/23745955/82160592-04ba-11e7-9dcb-5c09057d6b83.png)
I have the message
![image](https://cloud.githubusercontent.com/assets/13470265/23745983/9d5eab9c-04ba-11e7-978a-7e453f23530a.png)

Do you alert the user that some information from profil are public?

**Comment by Sandra97** [comment]
@genr8r @sebastienlapoux What's the status of this issue?

**Comment by genr8r** [comment]
@Saeedghb from our team is wanting to resolve this. Is there a way that I can have him added as someone to which I can assign issues. thank you.

**Comment by sebastienlapoux** [comment]
I unsubscribed notification to this issue. @genr8r please make this issue yours.

**Comment by genr8r** [comment]
The JRD rebuild will consider carefully the URL structure and make sure we are following SEO best practices. I am going to close this item as it already a part of our work on the new version of the site. Please reopen or post questions if there are any outstanding concerns.
