### ISSUE TITLE
[Media Manager Options] Maximum Size (in MB)

### ISSUE THREAD

**Issue by kokbira** [joomla/joomla-websites#751]
On the site of my work, I had to upload a almost 32MB PDF.

On Contents > Media, I tried to upload it, but an error appears informing that file exceeds maximum size, that was 256MB. On that screen, choosing Options, there is a field called Maximum Size (in MB). I changed that one to lots of values - for example, 32, 320, 3200, 32000, 320000 - with no effect.

I could upload the file only after reducing its size (I reduced it to 3MB).

I think it is an issue. One friend told me that Joomla did not change the php.ini on that case...

---

Informações do Sistema
Configuração	Valor
 
PHP executando em	<Somewhere Over the Rainbow> 
Versão do Banco de Dados	5.1.73
Colação do Banco de Dados	latin1_swedish_ci
'Collation' da conexão com o banco de dados	utf8_general_ci
Versão do PHP	5.5.29
Servidor Web	Apache/2.2.15 (CentOS)
Interface PHP com servidor Web	apache2handler
Versão do Joomla	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Versão da Plataforma Joomla	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navegador do Usuário	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please visit:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page

Thanks
