### ISSUE TITLE
[jdev] external github pages sites

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#752]
We have several sites linked to from the developer site that operate on github pages

There is an extension now that works really well at dynamically pulling that content into a regular joomla site. The content stays on github and in markdown so the "reasons" for it being on github are not lost but now the site content is on property and styled to match

At least for the content I am responsible for I would like to do this?

**Comment by brianteeman** [comment]
Oops forgot to link to the extension https://www.flycart.org/index.php/products/joomla/jmarkdown

**Comment by mbabker** [comment]
I've got no real issue with it as long as the extension's not of a questionable quality.

**Comment by brianteeman** [comment]
Do you want to review it? I have a copy

**Comment by mbabker** [comment]
That'd be good.  I always scrutinize a little more closely extensions for .org sites just because of it being that domain, it's nothing against any extension provider but it's just an extra step I usually look at.

**Comment by brianteeman** [comment]
Sent you  a link directly

**Comment by brianteeman** [comment]
Closed as this has now been implemented - thanks @mbabker
