### ISSUE TITLE
JoomlaCode Registration Broken

### ISSUE THREAD

**Issue by TimHerbert** [joomla/joomla-websites#753]
Joomla.org new user registration not sending email. It stores my username and everything as I can't fill out the form again but I filled it out last night and again under a new username and email and haven't gotten any email to be able to finish registration.

**Comment by mbabker** [comment]
Which subdomain are you referring to?  Many of the subdomains don't support user registration.

**Comment by TimHerbert** [comment]
http://joomlacode.org/gf/account/?action=UserAdd

**Comment by mbabker** [comment]
JoomlaCode's registration process last I was aware was pretty broken, we also discourage registering for the site as we're in the process of decommissioning it.

**Comment by TimHerbert** [comment]
Well I needed to download Joomla 2.5.19 as I inherited a Joomla site that I discovered has a Trojan Horse virus in one of the core files and don't want my server to find it and shut down the hosting for it. Is there anywhere else I can go to download that file? As It was making me register to get to that.

**Comment by mbabker** [comment]
https://downloads.joomla.org/ has all of the CMS downloads as was announced last week.  https://volunteers.joomla.org/teams/webmasters-team/reports/363-downloads-site-launched-joomlacode-shutdown-update explains it a little more.

**Comment by TimHerbert** [comment]
Thanks, I am new to Joomla. I am mainly a Wordpress developer. Our company inherited this site and I am tasked with maintenance so I'll be learning more about Joomla for sure if we can't convince them to make the switch. Thanks for all the help!

**Comment by mbabker** [comment]
No problem!
