### ISSUE TITLE
[jorg] Add Volunteers Portal Feed for Reports

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#754]
Now that the Volunteers Portal has a RSS feed for reports, I'd suggest we could add that to the homepage module showing the other news feeds.  This would have to be done either without avatars or ensuring the default Joomla logo avatar is used since the feed uses `admin_no_reply@joomla.org` for the item's author email instead of individual emails.

**Comment by sanderpotjer** [comment]
We could change the feed user emails to the actual users if needed. Only downside of this is that the emails are publicly available in the feed, but if people don't have big issues with that we can change the feed output.

**Comment by mbabker** [comment]
I can't speak for everyone but I know a lot of folks' Joomla emails are plastered all over the place and I'd venture to guess a lot of those publishing reports are registering with those, so it's not the worst thing out there.  Might be something you'd want to have a notice in profiles though if you did make the switch.

**Comment by mbabker** [comment]
Replaced the OSM feed since it has become low traffic and IMO the team reports are probably more reflective of what's happening in the project right now.  Since the portal still uses the no-reply email for the feed, avatars aren't associated but there's an issue on the portal's repo to address that.  Closing.

**Comment by sanderpotjer** [comment]
Volunteers can now set to display their email in the profile settings on the volunteer portal. So once set to "display" the emails can be used to match an avatar.
