### ISSUE TITLE
[jexam] Certified User description update not possible

### ISSUE THREAD

**Issue by studioinvento** [joomla/joomla-websites#755]
Hi, I have inserted some info inside my Certified User panel (name, town, picture, ecc...). I would like to revise my description since I noticed few typos but the description field is not present in the Profile Update page.

**Comment by jeckodevelopment** [comment]
Hi @studioinvento ,
Description won't be displayed in the personal page in Certified Users Directory.

Furthermore, lot of changes are coming to improve the CUD. Stay tuned!

**Comment by sam-suresh** [comment]
@studioinvento Description feature removed as people start to write anything they want and will gives us additional job to moderate, We will consider to have it in the future.
