### ISSUE TITLE
[jexam] IMG path?

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#756]
Please see:
(Yup... I use Chrome 😉 )

![screenshot-exam joomla org 2016-11-13 14-16-07](https://cloud.githubusercontent.com/assets/1972717/20247807/6acb65f8-a9ac-11e6-9785-ac80e6074231.png)

**Comment by jeckodevelopment** [comment]
@MATsxm knonw issue.
Thank you for noticing.
@sam-suresh is already aware and will fix it asap!

**Comment by sam-suresh** [comment]
Thank you for reporting. Fixed.

**Comment by jeckodevelopment** [comment]
Thanks
