### ISSUE TITLE
[jdocs] Typo fix

### ISSUE THREAD

**Issue by bootFairy** [joomla/joomla-websites#759]
I found the tutorials found here very helpful:
https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_a_view_to_the_site_part#File_Details

Something I did notice however that there seems to be a typo on the line referenced in: #File_Details
6 	Create: default.php 	<path_to_joomla>/components/com_helloworld/views/helloworld/tmpl/default.php

Looking further down at the documentation, with the specific code you need to write into the default.php file, it shows a different path:

site/views/helloworld/tmpl/default.php

I am of course assuming that the first reference to the file was incorrect? I also appreciate how typos can arrise when large documents are being written which is why I'd rather highlight it than just leave it for someone else. 

Cheers,
bootFairy

**Comment by MATsxm** [comment]
@bootFairy 
Thanks for the poke but as the JDoc is a Wiki, you, like all other contributors, are the content mainteners.
Feel free to fix what needs to be directly on the JDoc.
Thanks for your help.

**Comment by MATsxm** [comment]
following my previous comment - Closing
