### ISSUE TITLE
[jrepo] Padding top and bottom on sub menu items

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#76]
Tiny bit of padding above and below the submenu items would be nice and line-height for each list item can be increased a bit for readability and finger pointing on mobile. Will be impossible to click links... well at least hard.

Might look at JS open sub menu items on clicking parent menu item too if not too long.

![image](https://cloud.githubusercontent.com/assets/3688954/9492575/18cd80ac-4c3c-11e5-89cf-05c18ced14a3.png)

**Comment by Sandra97** [comment]
Agree with you. I'll look at it today.

**Comment by Sandra97** [comment]
Line-height of the sub-menus items has been increased.
@pbwebdev thanks to check and close if it's ok for you.

**Comment by jessicadunbar** [comment]
Looks great, nice job, I'm closing
