### ISSUE TITLE
[jexam] Broken images and Rewrite not enabled

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-websites#760]
1) Google Chrome show many 404 errors in console when i load the page https://exam.joomla.org/index.php/component/certification/
![image](https://cloud.githubusercontent.com/assets/1375730/20276681/8d11482a-aa9d-11e6-8ad1-24af0ad92f09.png)
Probably some images, css and JS are missing.

2) The site doesn't have the rewrite enabled, so we see "index.php" and "component" in the url: this is not good to see in the site that show certified administrators.

Thanks

**Comment by sam-suresh** [comment]
Thank you for reporting. Broken images fixed. 
Rewrite cannot be enabled at this moment for some other technical reasons. We will get these done in next update.

**Comment by sam-suresh** [comment]
#

**Comment by sam-suresh** [comment]
#756

**Comment by sam-suresh** [comment]
This is completely fixed now
