### ISSUE TITLE
[jdocs] Links on manifest links to svn

### ISSUE THREAD

**Issue by 810** [joomla/joomla-websites#761]
https://docs.joomla.org/Manifest_files

on the bottom the links are go to the svn, but we haven't that anymore

**Comment by jeckodevelopment** [comment]
@MATsxm just because i'm sure you know where to find the files

**Comment by zero-24** [comment]
hmm i would just drop the files / links. Or repleace it with banners and weblinks. As i guess if we found them they will be very outdated :smile: Any opinions?

**Comment by MATsxm** [comment]
If some wanna play with it... yes, you know, it is a **WIKI** **WIKI** **WIKI** :stuck_out_tongue_closed_eyes: help yourself or I will take a look later :wink:

**Comment by zero-24** [comment]
I hop i did not break everything on that site now..  https://docs.joomla.org/Manifest_files#Examples

**Comment by MATsxm** [comment]
Thank you @zero-24 
seems :+1: 
Just fixed few t9n tag issues (not from you... it's an "old" page)
Closing - reopen if needed
