### ISSUE TITLE
[joomla.org]    http://joomlacode.org/

### ISSUE THREAD

**Issue by sandicelje** [joomla/joomla-websites#762]
I have register me an I don't recived any email, please halp
my user name is "sandicelje" e-mail: sandicelje@gmail.com

**Comment by Radek-Suski** [comment]
Hi, 

the joomlacode.org website is not longer active. If you want to report issues please use https://issues.joomla.org 

Regards,
Radek 

PS: @mbabker we could maybe write some message about it at joomlacode

**Comment by mbabker** [comment]
The site's still active, but registration is broken and the site is being phased out.  Joomla's downloads and issue tracker archives have been migrated to other sites and language packages do not require login to download.  If you're trying to set up a space for a new project, here on GitHub gives you everything you need.
