### ISSUE TITLE
[jshop] Typo and unwanted text in the Joomlers Showcase

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#763]
If you go to the "Temporary Joomler" in the Joomlers Showcase at: 
https://community.joomla.org/the-joomla-shop/joomler-shop-showcase/1250-testing.html

there's a typo: `Pictue` instead of `Picture` and there's a dummy text `testing testing` that could be changed with something more useful.

![pictue](https://cloud.githubusercontent.com/assets/733133/20394902/67bee4ec-ace1-11e6-999c-f8c95d152c25.PNG)

**Comment by mikeveeckmans** [comment]
@jeckodevelopment thank you for spotting. 
Corrected. 

Closing, re-open if needed.

**Comment by jeckodevelopment** [comment]
Thank you @mikeveeckmans
