### ISSUE TITLE
[jdown] Mb (Megabit) or MB (MegaByte)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#764]
I think the image speaks for itself.

![image](https://cloud.githubusercontent.com/assets/9630530/20398245/8f3a2178-ace4-11e6-8a0f-1ded8abe567b.png)

https://en.wikipedia.org/wiki/Megabit
https://en.wikipedia.org/wiki/Megabyte

**Comment by mbabker** [comment]
Changed that layout to use `JHtmlNumber::bytes()` versus the ARS file size helper.  Any further bugs with that belong to core 😉
