### ISSUE TITLE
[jdown] Multilingual decimal points

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#765]
For instance, in Portugal, we use, `5,87 MB` not `5.87 MB`.
The decimal point is `,` and the thousands separator is `.` which, IIRC, it's the opposite of the english format.

Looking at https://downloads.joomla.org/pt/cms/joomla3/3-6-4 we have for the portuguese version `5.87 MB` which is not correct.

Is just a detail, but still an issue.

**Comment by zero-24** [comment]
Is this not something the language files ships? Maybe Ars does not support that info from the language packs?

**Comment by mbabker** [comment]
It's not using ARS anymore as pointed out in #764 

There are either two options:

1) Us wrap calls to `JHtmlNumber::bytes()` in a helper to be able to post-process the returned number to get the correctly formatted number

2) Fix `JHtmlNumber::bytes()` to return a number formatted with language awareness

**Comment by mbabker** [comment]
Or option 3 is to overload it using JHtml's override system, but that still only fixes the issue for one site.

**Comment by zero-24** [comment]
If we agree it should be configured via the language pack we should fix the core. Or is there anything against that?

**Comment by mbabker** [comment]
It's already something configurable by the language packs, using language strings.  For example:

```php
$formattedDownloadCount = number_format($item->hits, 0, JText::_('DECIMALS_SEPARATOR'), JText::_('THOUSANDS_SEPARATOR'));
```

`JHtmlNumber::bytes()` doesn't number format the returned value AND returns it as a string with the format appended.  So post-processing that isn't a very easy thing to do.

Like I said, we can override the JHtml helper for the downloads (but it only "fixes" this one site) to change its return to something like:

```php
return number_format(round($oBytes / pow($base, $i), (int) $precision), (int) $precision, JText::_('DECIMALS_SEPARATOR'), JText::_('THOUSANDS_SEPARATOR'))  . ' ' . $suffix;
```

The proper fix is to fix core if core will accept the change.  I'm not looking to create overrides of core functions here unless absolutely necessary.

**Comment by andrepereiradasilva** [comment]
ok let's close here since it's the core thta needs to be fixed

**Comment by andrepereiradasilva** [comment]
just additional info PR submit to core https://github.com/joomla/joomla-cms/pull/12929
