### ISSUE TITLE
[jextensions] CDN certificate expired

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#766]
Certificate expired
See https://extensionscdn.joomla.org/

**Comment by MATsxm** [comment]
Known issue thanks.
@Sandra97 any news about it?

**Comment by anibalsanchez** [comment]
I have submitted a ticket (187876) to Rochen.... but I have no control over certificates... So this issue should be assigned to who can renew it.

I read previous tickets and it seems that it has to be approved by admin j.org.

**Comment by brianteeman** [comment]
I guess this can be closed now

**Comment by jeckodevelopment** [comment]
It's ok now.
Closing. Re-open if needed.
