### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Sybergypsy** [joomla/joomla-websites#769]
Hello!

I've 'inherited' this website (www.ladismith.org.za) from previous staff and am in the process of updating it. It is in dire need of a version upgrade: currently it is still on V1.1.15!! I am struggling though to update this: I keep getting errors saying 'could not find a Joomla XML setup file in the package'. I have tried the latest version (3.6.4) as well as recommended version 3.6.0 but all with no luck. This is quite frustrating: please help soonest? Thanks!
![joomla](https://cloud.githubusercontent.com/assets/23627796/20474417/0a7f94d4-afcf-11e6-8aae-0dd94f581eda.jpg)

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,
Thanks
