### ISSUE TITLE
[jorg] Logos, still relevant?

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#77]
Are these companies still using Joomla? I think I asked this in another issue.

![image](https://cloud.githubusercontent.com/assets/3688954/9492660/d0cbddac-4c3c-11e5-9eec-f5bb8eb2d602.png)

**Comment by jessicadunbar** [comment]
I did some research and found some possible new ones. I'm going to assign this for phase 2 and follow up after launch.

**Comment by MATsxm** [comment]
UNRIC & Peugeot.com are ok.
https://nookdeveloper.barnesandnoble.com/ is down and no info about Ebay intranet (2010) 
a decision should be taken:
Keep the idea alive with some some institutional sites that have a meaning for everyone (linux.com (1.5) or gsas.harvard.edu (2.5) etc) or just link to the showcase site.
Thoughts?

**Comment by MATsxm** [comment]
To my point of view, adding logos just the way they are here doesn't make sens and even more here, regarding the brands and the reality of the sites concerned, the message sent is negative.

**Comment by jeckodevelopment** [comment]
What's your opinion about them @MATsxm ? 
Should they be removed or pointed to some "case-studies"? 

Your opinions? @mikeveeckmans @designbengel

**Comment by MATsxm** [comment]
removed without a single doubt... but who am I for saying so...

**Comment by jeckodevelopment** [comment]
Maybe when the new "showcases" will be up and running, we can feature some websites from showcases

**Comment by mbabker** [comment]
When's that supposed to be?

**Comment by jeckodevelopment** [comment]
good question Michael!

**Comment by mikeveeckmans** [comment]
Pinged the team that's taking care of the showcase. 
@jeckodevelopment i like the idea of publishing showcase entries instead of the logo's

**Comment by jeckodevelopment** [comment]
I guess that @sebastienlapoux is responsible for showcase

**Comment by MATsxm** [comment]
I would like to remove the logos and replace them with a link to the showcase as soon as it is launched.

**Comment by Sandra97** [comment]
Fully agree.

**Comment by mbabker** [comment]
Just do it and ask for forgiveness later.

**Comment by Sandra97** [comment]
Done. Forgive me.
