### ISSUE TITLE
[jexam] Active menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#770]
Doesnt matter which of the three menu items you are on it is always the Home that is highlighted

**Comment by jeckodevelopment** [comment]
Thank you for reporting this.

**Comment by sam-suresh** [comment]
This only happens to certification directory and all other menus works as expected. 
Currently we are building new components for certification directory and will be fixed soon.

**Comment by sam-suresh** [comment]
This is completely fixed now
