### ISSUE TITLE
[jexam] Reset password?

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-websites#771]
In the preparation steps for the certification exam it is suggested to set an "easy" password to remember it for the Safe Browser exam login as tools like 1Password, Lastpass can't be used. But after logging in there is no way to edit your password (if you don't know the direct URL of the change profile page).

So suggest to add a link to "edit account" or something like that.

**Comment by sam-suresh** [comment]
There is "Edit My Profil link" on your dashboard under "Quicklinks" which you can edit all fields. 
Now its possible to change your passwords too.
