### ISSUE TITLE
[jexam] "payment failed" after successful payment

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-websites#773]
After purchasing the JWC certification exam I was redirected back to a page stating "payment failed", while the PayPal payment was successful. I heard this from other participants too. Not sure if this was a JWC specific issue or a generic one.

**Comment by sam-suresh** [comment]
There is some delays in IPN validation or to get response from paypal.
However it does not states payment failed. Here is full error message;

> Thank you for your payment! Unfortunately your payment has not yet been fully processed, and you are not yet registered to enter the exam "{$a->fullname}". Please try continuing to the exam in a few seconds, but if you continue to have trouble then please alert the {$a->organizer} or the site administrator.

It works fine in sandbox account. So I made some real test and requested treasurer to check transactions to identify the delay. However I was told by treasurer OSM's paypal having some issues and cannot be checked. 

This is JWC specific issue and I'm closing this issue.
