### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jrdiaz69** [joomla/joomla-websites#774]
I'm receiving A LOT of emails of weird usernames signing up to my website, clear enough is SPAM and someone crack into my website in Joomla. Now, I need to access my account to clean that up and it doesn't let me login into my account from administrator page. How can I regain access to my account?

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
