### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by mojoAdmin** [joomla/joomla-websites#775]
I can't seem to find any UI for creating a new post on the Joomla forums. I'm not sure if this is a JS issue or a permissions issue. I am logged into the forum and have be able to submit posts in the past. Am I missing something?

**Comment by mikeveeckmans** [comment]
pinging @ooffick

**Comment by ooffick** [comment]
Hi, 

can you tell me your username for the forum so I can check your permissions.
Is there a particular forum board you want to post?

You might want to try to fill out the following form:
https://community.joomla.org/helpdesk/forum-un-ban-request.html

Kind Regards
Olaf

**Comment by mojoAdmin** [comment]
My user name is for forum.joomla.org is: lomas

Thanks!

**Comment by ooffick** [comment]
Thanks, your permission are fine. Can you please tell me in which topic your want to post a message? 

Kind regards 
Olaf

**Comment by mojoAdmin** [comment]
Well maybe this is just a UX issue.

My question could fall under general, or security or even administration.

Not to be mysterious, here it is.

Is there a way to tie CSS appearance to ACL?

A simple use case would be to gray out (but not hide) menu items for users
who are not registered?

Thanks!

**Comment by ooffick** [comment]
Hi 

I am confused, so you logged in and want to create a post, but cannot find the post button? Which button do you want to grey out. 

Please make sure you login, once you logged in you can post in any of the boards you mentioned. 

Kind regards 
Olaf

**Comment by mojoAdmin** [comment]
There was no UI that I could see to allow me to initiate a new post. I read
the help section and it was referencing UI that I could not find. I may st
be missing something obvious.

**Comment by ooffick** [comment]
Ok, so let's say you want to post a link in the General Questions/New to Joomla! 3.x Forum:
https://forum.joomla.org/viewforum.php?f=706

You can see a New Topic button, which leads to this page; (this button is also visible when you are not logged in) 

https://forum.joomla.org/posting.php?mode=post&f=706

Does that work for you? 

Kind regards 
Olaf

**Comment by mojoAdmin** [comment]
US Thanksgiving, today. I'll give it a whirl when I get back to my desk.

Thank you!

**Comment by mikeveeckmans** [comment]
@mojoAdmin any follow up?

**Comment by mojoAdmin** [comment]
Mike,

I guess I was just confused about how to start a post. It seems pretty
straight forward today, but could not find a new topic button anywhere when
I first asked for help.

Perhaps I was running up against a memory issue in my browser or something
similar. Or just as likely, I'm an idiot! :-)

Thanks for the follow up.

Best, SL


Steve Lomas
CEO | Idea Mechanic
866.346.1105 office
615.830.6451 mobile
sl@mojomediapros.com


*Creating better outcomes by design.*
