### ISSUE TITLE
[jhelp] Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by ramanakirubagaran** [joomla/joomla-websites#776]
Hi I get the following error when i try and "fix" the databse via the GUI. I've searched on the internet with many conflicting solutions. Could someone please help as to what is ideal to do?

thanks,

Error
Specified key was too long; max key length is 767 bytes SQL=ALTER TABLE `#__contentitem_tag_map` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

> 

> 

Error
Specified key was too long; max key length is 767 bytes SQL=ALTER TABLE `#__contentitem_tag_map` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

Warning: Database is not up to date!

The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

Database schema version (in #__schemas): 3.5.1-2016-03-29.
Update version (in #__extensions): 3.5.1.
Database driver: mysqli.
93 database changes were checked successfully.
145 database changes did not alter table structure and were skipped.

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
