### ISSUE TITLE
Joomla error makes me unable to edit pages

### ISSUE THREAD

**Issue by Hoveling** [joomla/joomla-websites#778]
When I want to edit a module, I can open it once for editing. The second time I get this error:
YOU ARE NOT AUTHORIZED TO USE THIS LINK FOR DIRECT ACCESS TO THIS PAGE (# 116).

This makes it impossible to edit my website properly.

Your help will be appreciated!

<img width="1440" alt="schermafdruk 2016-11-24 10 03 38" src="https://cloud.githubusercontent.com/assets/23717248/20592404/86914fda-b22d-11e6-8a64-f9db5b3be7d2.png">

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,
Thanks
