### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by info-skonline** [joomla/joomla-websites#779]
I can't change or save anything on my website.
I'm the administrator and there are no other accounts registered to this website!

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by MATsxm** [comment]
https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F
