### ISSUE TITLE
[jrepo] iPad Mini 2

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#78]
![image](https://cloud.githubusercontent.com/assets/3688954/9493167/262efe2e-4c41-11e5-98e4-938de73ffd42.png)

**Comment by Sandra97** [comment]
Can't reproduce the issue. Culd you give me the screen size/resolution?

**Comment by jessicadunbar** [comment]
I can't reproduce. Browser info and screen size please :)

**Comment by Sandra97** [comment]
OK, I think I found the problem : a weird behavior at 768px. (everything was ok for 767px, ok for 769px).
Display for 768px is now ok. 
@pbwebdev Please check and close if it's ok for you.

**Comment by MAT978** [comment]
Solved then closed - Thanks
Reopen if needed
