### ISSUE TITLE
[jorg] Add two more announcements to reduce white space

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#780]
In joomla.org with the new teaser image promoting Joomla! Downloads, it could be better to add 2 more announcements in the right list to balance the space in the page and reduce the empty space.

![jorg](https://cloud.githubusercontent.com/assets/733133/20625426/ad19eaae-b313-11e6-89de-c5edf049a67d.PNG)

**Comment by MATsxm** [comment]
4 is more than enough here :stuck_out_tongue_closed_eyes: 
let me know.
(BTW I added the read more to the road map article but even without it, 4 articles were enough)

![a41a613baf092d5f7df7a3a4a9008ed5](https://cloud.githubusercontent.com/assets/1972717/20625808/e0d91b9e-b2eb-11e6-939f-db1a8f73a440.png)

**Comment by zero-24** [comment]
:+1:

**Comment by jeckodevelopment** [comment]
Thank you!

**Comment by MATsxm** [comment]
what I thought but **YOU WERE NOT HERE!!!** to do the job :stuck_out_tongue_closed_eyes:

**Comment by Sandra97** [comment]
I know, I should not be allowed to leave my screens...
