### ISSUE TITLE
[jcomm] Increase the contrast of read more

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#781]
If you look at Read More buttons at community.joomla.org they have low contrast.

![cjo](https://cloud.githubusercontent.com/assets/733133/20642302/227417a4-b40c-11e6-8b0d-8d79cb07f05d.PNG)

Read more buttons are darker in the joomla.org homepage

![jorg](https://cloud.githubusercontent.com/assets/733133/20642306/35deeb3e-b40c-11e6-9b97-2f50e1f7fa71.PNG)

Imho, darker buttons are better for readability.

**Comment by mbabker** [comment]
CJO uses the Bootstrap button markup.  Our homepage is using custom CSS.  I don't see an issue here, if there's an issue with contrast it should be fixed in the template for all sites.  And if anything the homepage should remove the custom CSS in favor of Bootstrap buttons.

**Comment by Joomv** [comment]
This passes AAA for contrast and is therefore a non-issue, closing.
