### ISSUE TITLE
[jorg] Add hover effect to read more in home

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#782]
Read more buttons at joomla.org (See announcements) haven't any hover effect.

![jorg](https://cloud.githubusercontent.com/assets/733133/20642338/88f25e32-b40c-11e6-8ec7-2b6516647f9d.PNG)

**Comment by mbabker** [comment]
So?  The mouse becomes a pointer to correctly indicate it's a link.

**Comment by MATsxm** [comment]
c'mon... please stop with your oldSchool hovers...
play with it on your smartphone and let me know :stuck_out_tongue_closed_eyes:

**Comment by mbabker** [comment]
The read more button buttons site wide are adjusted back to the default markup/styling of the template.  If we want to customize these, it should be done in the template, not on a per-site basis please.
