### ISSUE TITLE
Used contact form without any answer

### ISSUE THREAD

**Issue by joomlaproffs** [joomla/joomla-websites#784]
**Please describe the problem or your issue**
I have emailed twice on https://showcase.joomla.org/about-jsd/contact/form/seb_feedback.html?thanks=seb_feedback form but no reply. I have a feeling its not going anywhere?

**It could be useful to include an URL of evidence.**
https://showcase.joomla.org/about-jsd/contact/form/seb_feedback.html?thanks=seb_feedback

**Comment by Radek-Suski** [comment]
@sebastienlapoux could you please take care of it. People are already complaining at twitter https://twitter.com/Joomlaproffs/status/805001975712673793

**Comment by sebastienlapoux** [comment]
Hi,
The contact form is working as expected and contact requests are processed. In regards of the specific case, it can take more times.
Thanks.
