### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by vnay231** [joomla/joomla-websites#785]
I want to add zoom feature in the images which i add using the easy discuss extension in joomla. Can anyone help me out how can i achieve this on my website.

Easy discuss have been used in my website for discussion forum where people upload image but the image which has been uploaded cannot be seen so i want that image where in zoom in and out can be done So is there any way by which it can be achieved.

Urgent help is appreciated.

**Comment by zero-24** [comment]
Please use the forum for support. This is just for issues on joomla.org websites :) https://forum.joomla.org
