### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by tcjackson2016** [joomla/joomla-websites#788]
Ages ago I worked for a church which used Joomla to make a very nice web site. To learn Joomla I made a site (The Rev. Thomas C. Jackson). I now work for another church but I continue to receive these messages:
-----
Hello Administrator,

A new user has registered at The Rev. Thomas C. Jackson.
This e-mail contains their details:

Name: drmirljjy
E-mail: bkrqzbok@007game.ru
Username: drmirljjy

Please do not respond to this message. It is automatically generated and is for information purposes only.

---

I do not have an active Joomla log in so I can't adjust the settings on the site to stop these emails. I don't even know where it is hosted or I would remove it. 

If there's no harm done by these spambots signing up for an abandoned website then I will just let them go on their merry way.

But I thought I should check and see if there is anything else that should be done.

Thanks!

**Comment by zero-24** [comment]
You can disable the registration in the backend BE -> System -> Global Configuration -> Users -> allow registration.

Please use for any future questions https://forum.joomla.org

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by tcjackson2016** [comment]
Actually, since I no longer have a joomla account and don't have access to
the email at my former church there's still not much I can do about this
'closed issue.'
