### ISSUE TITLE
[jtm] Joomla! Logo Download Year

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#789]
https://tm.joomla.org/brand-manual-and-limited-use-logos

Please remove the year or pull the current year. Thank you!!

![image](https://cloud.githubusercontent.com/assets/828371/20869271/1dae4d5c-ba6f-11e6-858b-0fedab44ea47.png)

**Comment by jeckodevelopment** [comment]
Done, thank you.
BTW, the folder on Google Drive has still 2015 in its name.

**Comment by coolcat-creations** [comment]
renamed ;) Link works still! thx

**Comment by jeckodevelopment** [comment]
it works! thank you Elisa!
