### ISSUE TITLE
[org2] IE8 on XP, overkill for testing? :)

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#79]
![image](https://cloud.githubusercontent.com/assets/3688954/9493219/8354764c-4c41-11e5-883a-888ae3ea2038.png)

**Comment by MAT978** [comment]
I thought for a minute that my father was on gitHub :fearful:

**Comment by mbabker** [comment]
The last time I remember hearing numbers for .org traffic, IE was the top browser (not sure on versions).  So, probably not overkill, but that's going to make some lives miserable to say the least.

**Comment by jessicadunbar** [comment]
Here's a small data set from analytics. This month over 4k sessions were from I.E. 8 & 3,700 are new. 

IE is one of our top browsers
https://www.evernote.com/l/ADc6Uk-CocBEhbdeXNcm4K7pFm6by-1tAhc  

versions of I.E.
https://www.evernote.com/l/ADexMiRoHudIcJx6M1zP5DGHHuJeVZ2ZX_0

Decline of I.E. 8 from Jan 2014 
https://www.evernote.com/l/ADe1GbJIlsNMlqpmk9RjPmmQuTl6b2xEiCQ

What do you think based on that information?

**Comment by mikeveeckmans** [comment]
Does anyone has the possibility to test why the header is not showing ?

**Comment by MATsxm** [comment]
My father is the last one concerned.
Closed

**Comment by mbabker** [comment]
0.2% of traffic to .org is on IE8.  I'd say it's overkill at this point.  Agree with MAT.
