### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by Cherished1** [joomla/joomla-websites#790]
Our Website Cherishedgowns.org.uk is missing module SiteGround – Social module under Extensions -> Module Manager

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
