### ISSUE TITLE
[jexam] english corrections

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#791]
The following paragraph is not in good english
_Currently exams are offered at Joomla! Learning Partners, JoomlaDays or JUGs. If you are taking this exam at Joomla! Learning Partner, no registration is required. If you taking the exam at JoomlaDays or JUGs, please register and buy exams. Links to buy exam for JoomlaDays or JUGs available at their official website._

**I would suggest the following**
_Currently exams are offered at Joomla! Learning Partners, JoomlaDays or JUGs. If you are taking this exam at a Joomla! Learning Partner then no registration is required. If you are taking the exam at JoomlaDays or JUGs then please register and purchase the exam. Links to purchase the exam for JoomlaDays or JUGs are available at their official websites._

**Comment by sam-suresh** [comment]
Thank you for the improvement. Updated.
