### ISSUE TITLE
[jcomm] Bad link redirection in "Joomla! User Group Support"

### ISSUE THREAD

**Issue by gagnonjeanfrancois** [joomla/joomla-websites#792]
In https://community.joomla.org/helpdesk/user-groups-support/department/joomla-user-group-support.html

The links for « FAQs and Rules For Submission », « also available in Spanish » and « the User Groups Terms of Service » redirect to https://community.joomla.org/user-groups.html , but they should point to their own section.

**Comment by gagnonjeanfrancois** [comment]
I don't know if I should open a new ticket... But we can find the same problem at this page :  https://community.joomla.org/user-groups/rules-and-faqs.html#basic-rules

In the first paragraph the link  « Terms of Service » also redirection to https://community.joomla.org/user-groups.html

**Comment by Joomv** [comment]
Thank you for reporting this, all fixed!
