### ISSUE TITLE
[jdocs] code display align to right in RTL

### ISSUE THREAD

**Issue by rbismut** [joomla/joomla-websites#793]
when i view the jdocs site it display the site align to right (detecting my location ??) which is ok. but the code examples are also aligned to the right which makes it unreadable.
i suggest to add in the css to pre elements : direction: ltr; which solve the problem

**Comment by Sandra97** [comment]
It is now fixed by adding a ltr direction to `<pre>` elements.
Closing this issue.
Re-open if needed.
