### ISSUE TITLE
[jhelp] The S5 template doesn't show pictures from Media Manager

### ISSUE THREAD

**Issue by JaneZhilina** [joomla/joomla-websites#794]
The S5 template doesn't show pictures from Media Manager. Before this happened, Joomla showed message Invalid token. Joomla version 3.4.3. Can't update, because the template won't work

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
