### ISSUE TITLE
[jrd] Outdated Banner / TM missing, Joomla without !

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#795]
Can we propose a redesign of this banner?
The TM is missing and Joomla is written without !

If so i´d need the siteground Logo

thx

![image](https://cloud.githubusercontent.com/assets/828371/21017184/cf7bc342-bd68-11e6-8f90-8cae8e905114.png)

**Comment by genr8r** [comment]
@Joomv this is on the JRD homepage. Who owns this? Are they paying for it? The banner is setup as a simple module. So it is easy to update. I just need to get information on what the banner is or should be.

**Comment by genr8r** [comment]
I don't believe that there is anyone in charge of this banner at the moment. I am also not aware of it being any part of an ongoing relationship with Siteground. I have unpublished it. We can either fill that slot with something from the Capital Committee, Upcoming Events, or...

@adaneinspain reached out to me regarding items for the new sponsorship page. We could list (or rotate) high level sponsors.

Not looking for something new. Just letting folks know that I pulled the old out of date banner and am open to other possibilities  if someone steps forward.

**Comment by MATsxm** [comment]
could you please check with the Capital Team (Joe @joejoomla) and/or Soren (@adaneinspain) before disabling a sponsorship banner ?

**Comment by JoeJoomla** [comment]
Hi there,

Siteground is both the official Joomla demo and the Joomla.com partner for the project.

The agreement about the banner is that we are to give them as much exposure as we can to keep this partnership win/win.

The Joomla ad server is getting some more attention these days and when the Capital Team meets this month we will be talking about strategies for ad campaigns. That banner/module space should be replaced with code from our ad server. I'll talk to Soren about that spot and see how quickly we can do this.

**Comment by genr8r** [comment]
Sounds great @JoeJoomla. Do you want me to turn the old banner back on in the interim? I got pinged on it as it has trademark issues. I will let you guess what is missing ;)

I love sg. I just wasn't sure what I needed to do to get this issue off my todo list.

**Comment by JoeJoomla** [comment]
Yes, please do put the old banner back. I'd like to also check the link on it to see where it's going.

**Comment by genr8r** [comment]
done

**Comment by aDaneInSpain** [comment]
I will look at this tomorrow.

**Comment by aDaneInSpain** [comment]
We should be showing a general banner on all our sites (that is work in progress for me). Today I got banners added on community.joomla.org, last week on documentation. For JRD I can prepare a code for you to add where needed. We have two banner sizes 728 x 90 and 300 x 200 (which can be scaled down to 270 x 125 for the right hand module position of the template).

If you let me know which of these positions we need and where then I can create the zones on our ad server and give you the code for publishing.

If we have agreed to "do what we can" for SiteGround we should add their banner to our rotation on all sites, not just the JRD. I will discuss with the rest of the Capitals Committee on our next meeting on the 14th.

**Comment by genr8r** [comment]
Thanks @aDaneInSpain.  Feel free to drop the code here or if you want to swap it in for the "Advertisement" module on the JRD.  I believe you have access.  I happy to help as needed.

**Comment by aDaneInSpain** [comment]
I have created an ad zone for you in the ad server. Please replace the SiteGround banner with our ad serving code according to this guide: 

https://github.com/aDaneInSpain/joomla-websites/blob/9e8ca4ab74b3c1f3b4461f2c4e7ae43b00fcb158/documentation/guide-for-adding-banner-ads.md

Your ad zone is: 63

I am adding the SiteGround banner with a 5% viewing throughout all of our sites.

**Comment by genr8r** [comment]
Hey @aDaneInSpain, I finally got this set. I turned off the old ad and have your code running at the bottom of all pages. Let me know if you need anything else on this.

I look forward to our continuing the sponsorship discussion from earlier this week.
