### ISSUE TITLE
[jdev] Finish JMarkdown integration

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#796]
The integration will need to be transferred from using Brian's GitHub credentials to a bot account and whatever outstanding issues there were with finishing the transition of the coding standards manual to the JMarkdown extension need to be addressed with the extension developer so we can complete this task.

**Comment by mbabker** [comment]
x-ref https://github.com/joomla/joomla-websites/issues/768

**Comment by mbabker** [comment]
And just as I expected, the content is now broken thanks to a rushed and poorly communicated action...

https://developer.joomla.org/en-gb-user-interface-text-guidelines.html

**Comment by wilsonge** [comment]
The en-GB is now using the bot credentials.

**Comment by mbabker** [comment]
I think I've got this done right if someone could review and compare with the existing page.

- https://developer.joomla.org/coding-standards.html
- http://joomla.github.io/coding-standards/

If this is good, https://github.com/joomla/coding-standards/pull/141 can be merged and the old branch deleted.

**Comment by MATsxm** [comment]
AFAIC just has to say thank you

**Comment by zero-24** [comment]
Should the part `Contributing to this manual` (under `Introduction`) not be changed if we delete the `gh-pages` branch?

**Comment by mbabker** [comment]
Well, obviously some of the content will need updated.  The files were just copy/pasted between branches without content updates (some of the links are broken too because old paths are referenced).

**Comment by zero-24** [comment]
:+1:
