### ISSUE TITLE
Integrate .com into navigation

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#797]
Continuation of https://github.com/joomla/joomla-websites/issues/554

**Comment by Sandra97** [comment]
If we add .com to the top menu, we should so also add demo? I know we already have the button for demo but the buttons are not displayed on exam and demo websites.

**Comment by jeckodevelopment** [comment]
I've an idea.
Will make a PR for that

**Comment by Sandra97** [comment]
I'm always worried when someone has an idea ;)

**Comment by Sandra97** [comment]
As demo and .com have been added to the CDN menu (in the upcoming version of the template), I'm closing this issue.
Re-open if needed.
