### ISSUE TITLE
[josm] Accessing over HTTPS

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#798]
When trying to reach this website over HTTPS this content is being displayed 

<img width="1649" alt="screen shot 2016-12-10 at 12 29 41" src="https://cloud.githubusercontent.com/assets/1110663/21073016/b68817ec-bed4-11e6-9ed2-c303a9c1b44a.png">

Additionally there is a warning about invalid certificate

<img width="583" alt="screen shot 2016-12-10 at 12 23 53" src="https://cloud.githubusercontent.com/assets/1110663/21073025/cda2e10a-bed4-11e6-8e54-7e4ea64c159b.png">

It wouldn't be maybe an issue if not the fact that some browsers are suggesting to access it that way 

<img width="694" alt="screen shot 2016-12-10 at 12 31 28" src="https://cloud.githubusercontent.com/assets/1110663/21073030/ecce8070-bed4-11e6-8dae-de6935993aa8.png">

Referring to: https://opensourcematters.org/

This looks very suspicious and may confuse people.

**Comment by Hils** [comment]
Chrome from the UK
<img width="554" alt="osmchrome" src="https://cloud.githubusercontent.com/assets/736887/21073281/cfd82d2a-bed1-11e6-9a31-1434bf4291e8.png">

**Comment by mbabker** [comment]
We don't have a certificate for this domain, as has been said numerous times over the years (including all open HTTPS related tickets).

Closing, see https://github.com/joomla/joomla-websites/issues/486 where there is an outstanding task specific to this domain.

**Comment by Radek-Suski** [comment]
I know we don't have it but even with the wrong certificate this website should server the correct content I think
