### ISSUE TITLE
[META] Framework Website

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#799]
The [Framework website](https://framework.joomla.org) is a small website which was originally designed as a single landing page; we integrated an "about" page (a static list of contributors based on the 2013 release announcement) and a status section (a rollup of code coverage and latest versions basically since this isn't a monolithic framework stack and we had no other place to have a consolidated section like this).

The site itself is [a small Framework app](https://github.com/joomla/framework.joomla.org) to have a functional example of a smaller Framework website, but the structure it's based on is rather old and has quite a few issues.  Additionally, I'm the only one maintaining this resource either as the main code contributor/maintainer or "publishing" the content (the status reports all come from my laptop and are therefore biased to my system configuration).

The site is a low traffic resource (~3K hits/month) and 95% of the traffic is the actual homepage or the package listing page, everything else per analytics has a minimal blip at best.

Given the reception of the Framework as a whole within Joomla and the PHP community, the fact that this website is a one-man shop, and that it is a low traffic site, is there value in continuing to maintain this subdomain or are we better off just merging it into the Developer Network and calling it a day?

**Comment by mbabker** [comment]
Anyone?  Or am I talking to myself again?

**Comment by jeckodevelopment** [comment]
Imho it could be merged in developer website.

**Comment by mbabker** [comment]
@wilsonge this is your team so some input would be welcome when you get some time.

If this site is going to keep being maintained, it needs to be rewritten to current standards (basically the same way the help site and stats server are done).  What's there now, while it works, is subpar and doesn't reflect fairly on our code or structures.

I've got a list of content, deployment, and structure related issues on the site's repo - https://github.com/joomla/framework.joomla.org/issues - whether the site stays standalone or merges back into the developer network, the content and structure will need a review and cleanup (especially on the developer network, I don't think anything's been touched there since David launched that version of the site).

No matter the outcome, this needs to be something people other than me pay attention to and maintain.  Its purpose as a single page landing site has long been outlived.

**Comment by mbabker** [comment]
Site's still running and getting more features.  Until I'm told to stop.
