### ISSUE TITLE
[jorg] DISCUSSION -current supported version

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#800]
IMHO, on the .org main page, we need to have a **VISIBLE** mention of the current supported version, a box or whatever, but something clearly saying kind of: 

> The current supported version of the Joomla! CMS is 3.5.X

Thoughts and proposals are welcomed

**Comment by mbabker** [comment]
👎 

IMO, this is not something that goes on the absolute front page of the website.  Of course I always seem to disagree when it comes to content so go ahead and have a healthy discussion.

If you want to integrate this somewhere, it should be a link to https://developer.joomla.org/development-status.html which notes the full status of all software and versions.

**Comment by MATsxm** [comment]
I would prefer something more generic and "hightlighted" as a reminder even if there's a link for further information like the page you mentioned 
What's on the Doc as a side note (not what I think suits for org):
![e5c2849f0b59ad93d38adf02971c3b51](https://cloud.githubusercontent.com/assets/1972717/21162066/d6d2a64a-c161-11e6-9c4b-0931a4a1a334.png)

**Comment by MATsxm** [comment]
even something more "marketing" like:

> are you sure you ar using the latest 3.6.4 Joomla! version?

with a link to a page explainig how to check the current version of a J! install

**Comment by mbabker** [comment]
For the documentation it makes sense to have that block.  I just personally don't see a use case for the homepage having a "(this is|these are) the latest version(s) of Joomla" block.  That should be steered by the download button and making that clear in whatever pages are referenced from there.

**Comment by mbabker** [comment]
Look at the major competitors in both the CMS and framework space, none of them advertise this specific statement on the homepage beyond either a release announcement or including the version number in a download link/button.  IMO that is a correct decision.

Symfony lists their roadmap section in their nav footer and this is where they show this type of data.

WordPress has a release section but in clicking around a few pages the closest thing I could find to a comparable statement was their release archive.

We have a docs page listing all this stuff as well as our dev status page, so we already have the resources, they just aren't easily referenced from outside (the dev status is prominent on the dev site but no place else, and the docs wiki has that statement on its homepage and the full matrix "somewhere" (sorry, didn't do a search for this one to see how quickly it's referenced)).

So to be fair, yes I believe this should be easy to find.  No, I do not believe the homepage "proper" is the place to make this statement.

**Comment by MATsxm** [comment]
k
re-open if needed 😝
