### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by thorhalla** [joomla/joomla-websites#801]
Good day

 I am having trouble with the school web side. It stared after lunch yesterday - nobody had been doing anything with it. (www.blonduskoli.is)  I have been trying to figure out the problem to day and have not had any luck. What has happened now is that my username/password seem to not been working - I have it saved to the account and have not done anything to change it.  

the error is: **Strict Standards: Only variables should be assigned by reference in /vefir/gaman987/public_html/plugins/system/rokextender/rokextender.php on line 32**
(there is also problem with line 14 and 23)

hope to get some help

sincerely 
Thuridur

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
