### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-websites#802]
JOOMLA.ORG forum account reminder emails are not going out ( been 15 minutes now...)

Also, created new account, and activation email is nowhere to be seen (after ten minutes...)

**Comment by Sandra97** [comment]
@rotech1 Do you still have this issue or not?
If not, thanks to close this issue.

**Comment by MATsxm** [comment]
no answer - old issue
closing -reopen if needed
