### ISSUE TITLE
No confirmation on default contact form!

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-websites#803]
The default Joomla contact form works fine ( sends out an email), but it returns with blank form, and **no indication that the send was successful.**

Only noticed this since 3.6.5 update, but problem could stem from earlier version. 

It used to work, not too long ago!

contact-us is the URL...

**Comment by zero-24** [comment]
Can you please check with a clean install and a default template? If there is still the same issue please post a detailed report here: Https://issues.joomla.org else please use the forum for support. Thanks :+1:
