### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by alicemazorra** [joomla/joomla-websites#806]
Hi:

I have a really old (ugly) website, that I will migrate soon, but am leaving it up as is for a little bit longer.
I have hundreds of unauthorized users swamping my user manager list, no matter how complicated of often I change my username and password. Tonight it was like three hundred in ten minutes.
Help.

Alice Mazorra
Cannonball Press

www.cannonballpress.com

**Comment by Radek-Suski** [comment]
Hi,
This repository is **ONLY** for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-http://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Radek
