### ISSUE TITLE
[jdev] Roadmap https://developer.joomla.org/cms/roadmap.html

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#807]
This page https://developer.joomla.org/cms/roadmap.html is out of date, makes no mention of com_fields and is in general not fit for publication at the moment. 

This is what the public see as Joomla's future - it should be a magical page with unicorns and rainbows, or at the very least factual information that excites someone to start using Joomla, as an investment, knowing that the future of Joomla is secure, exciting, and long term. 

Also the page, hosted on the developer.joomla.org should be angled towards Developers and a different page should be on www.joomla.com angled towards end users... At the moment both developers (from outside of Joomla ecosystem) and new visitors looking for a new CMS both get a bad experience from this page. If indeed they ever find it...

**Comment by mbabker** [comment]
Because efforts aren't duplicated enough on the properties (which is why navigating them is pure hell)...

https://docs.joomla.org/Joomla_CMS_Development_Roadmap

**Comment by mbabker** [comment]
@joomla/cms-release-team it should be safe to assume someone from this team could take charge of coordinating what will be the canonical source for the release roadmap and either ensuring all pages are updated or communicating what changes are needed to those with access?

**Comment by MATsxm** [comment]
updated on the Doc also.
I guess it can be closed - reopen for the next roadmap 😝

**Comment by rdeutz** [comment]
I updated the developer article and added "Admin Menu Manager" to the wiki

**Comment by Sandra97** [comment]
Thanks Robert!
