### ISSUE TITLE
[jvols] can't change password 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-websites#808]
Unless I am totally blind there is no way to change user's password at this website

Regards,
Radek

**Comment by Joomv** [comment]
Confirmed.  Obviously you can do a password reset, but there should be a way to change it when logged in.

**Comment by ashutoshvct** [comment]
You can change user password by making changes in database.
https://docs.joomla.org/Resetting_a_user_password

**Comment by sanderpotjer** [comment]
Apologises, missed this issue earlier in this repo. But you can change your password in the profile meanwhile. Thanks for reporting!
