### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by jessemullinax** [joomla/joomla-websites#809]
Forum.joomla.org will not let you log in. When you can log in and you click view my topics it makes you re-log in. It seems that every time you click a link you have to re-log in. I hope this helps:)

**Comment by JansenInternetservice** [comment]
Logout, empty browser history and try to login again

**Comment by Sandra97** [comment]
@jessemullinax Do you still have this issue?
If not, please close this issue.

**Comment by MATsxm** [comment]
no answer - old issue
closing - reopen if needed
