### ISSUE TITLE
[j3] Russian translation

### ISSUE THREAD

**Issue by b2z** [joomla/joomla-websites#81]
At the end of may I've submitted a proper Russian translation that was discussed with Russian community. Before that submission I've contacted Mike Veeckmans and got his pre-approve.

But old translation is still there :disappointed:

**Comment by mikeveeckmans** [comment]
@b2z I lost track of this, i'm sorry.
However we need translation for J3.5 landing page soon, it would be great if you could help us out on that. 
@MAT978 will contact you for this.

**Comment by MAT978** [comment]
I will in november :wink: 
Closed - feel free to open again if needed.
