### ISSUE TITLE
[Downloads API]CMS version format

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-websites#810]
The site https://downloads.joomla.org/api-docs/ describes the endpoint for retrieving hashes but it is unclear in which format the Joomla version number needs to be for /v1/signatures/cms/{version}. I have tried the following:
/api/v1/signatures/cms/3.6.0
/api/v1/signatures/cms/3.0.0
/api/v1/signatures/cms/2.5.28

The answer is {"error":{"code":404,"message":"Version not found"}}

Perhaps improve the documentation with the format of the version number.

**Comment by mbabker** [comment]
For the signatures endpoint it uses the alias (so 3-6-5, 2-5-28, etc.).  On the download counts endpoint the version branches uses 10, 15, 25, and 30.

Apparently there's some reason we couldn't just use dotted version numbers that @wilsonge can explain better than me.

**Comment by roland-d** [comment]
@mbabker Thanks, that version number works.

**Comment by wilsonge** [comment]
Reason is dots in urls' can really suck. For example in a sample php script i wrote I ended up having to do the following just to trick PHP into finding my correct email......

```
rawurlencode(str_replace('.', '%2E', 'george.wilson@example.com'))
```
