### ISSUE TITLE
[joomlacode] Joomlacode.org is blacklisted by the Sucuri Malware Labs

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#811]
https://sitecheck.sucuri.net/results/joomlacode.org

![image](https://cloud.githubusercontent.com/assets/2596554/21403485/3a828fc8-c7bd-11e6-905e-8adfedc856fc.png)

All links are 404 / closed links that don't download anything maybe they just need to be contacted that they remove us from that blacklist?

**Comment by infograf768** [comment]
what is important i guess is to find out if it is the site itself which is concerned and not some specific files that can be downloaded.
is there a way to know that?

**Comment by zero-24** [comment]
As per the screenshot i would guess it is about the three files that they are pointing too. But all three are not longer there. So i guess they can just remove is from there list.

**Comment by infograf768** [comment]
Someone from PLT should contact these people (Google I guess), and stop this blacklist.

**Comment by zero-24** [comment]
hmm i'm not 100% sure but IIRC Sucuri Malware Labs is not Google ;)

http://labs.sucuri.net/?about

The Problem is i don't know how to contact them about that without doing a subscription ;)

**Comment by jeckodevelopment** [comment]
I tried to contact the founder via twitter.

**Comment by zero-24** [comment]
all green now:
![image](https://cloud.githubusercontent.com/assets/2596554/21461087/941f88f0-c94e-11e6-86d5-34f4d0b8fe84.png)

**Comment by zero-24** [comment]
Thanks @jeckodevelopment

**Comment by jeckodevelopment** [comment]
happy to help and to see it green :P
