### ISSUE TITLE
[jexam] Edit profile not possible

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#813]
I´m not listed on the exam page when you filter by germany. 
Can´t edit my profile too:
![image](https://cloud.githubusercontent.com/assets/828371/21425714/14c270bc-c84b-11e6-8197-49d3fa457493.png)

Seems that other users have the same issue...

thanks,
Elisa

**Comment by Joomv** [comment]
I can confirm this.  It also appears that SSO between Moodle and Joomla! is broken.
I logged into Joomla! and then got the Moodle login in an Iframe then I got the same screen as Elisa above.
@sam-suresh

**Comment by sam-suresh** [comment]
@Joomv Its not true SSO broken. On the image Elisa posted, you can see in the footer that SSO working. 

@coolcat-creations Sorry for this. There has been a bug in user role. I have fixed it. Unfortunately a password reset is required. Sorry for that.

**Comment by Joomv** [comment]
@sam-suresh I was relating to my own experience.  This also seems to be fixed now.  When I went to test this, logged in through Joomla! but when I clicked on my profile I was presented with the moodle login form in the iframe.  All good either way now.  Thanks.

**Comment by coolcat-creations** [comment]
thank you all!
