### ISSUE TITLE
[jorg] our own logo breaches our own brand guidelines on the main site

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#815]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

https://www.joomla.org/ the wording next to the logo "joomla" has a text shadow which breaches our own brand guidelines.  https://issuu.com/joomladocs/docs/20150308_joomla_brandmanual_basic_d/1

This CSS:

.page-title {
    margin: 0;
    font-size: 30px;
    font-weight: normal;
    line-height: 50px;
    color: white;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.8);
}

should have the text-shadow part removed in order to resolve the issue.  I have already spoken to Sandra Thevenet about this on Glip, so she may already be handling it (or this may go to her).

**Comment by Sandra97** [comment]
Shadow removed!
Closing this issue.
Re-open if needed.
