### ISSUE TITLE
[jdown] 404 error page language strings..

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#816]
goto a page that generates a 404 https://downloads.joomla.org/cms/joomla3/erfeferferferferf

Note 
ARS_CATEGORY_NORMAL
ARS_CATEGORY_BLEEDINGEDGE

@mbabker

**Comment by mbabker** [comment]
That's not even a 404 page.  That's the routing in ARS not handling the 404 condition at all.

**Comment by PhilETaylor** [comment]
Ah well - Im sure you will find a way to sort whatever kind of page it is ;-) I believe in you - Christmas is cancelled until this is done right?

**Comment by mbabker** [comment]
Tell that to my boss who has me working even though I'm not in the office for the next week 😉

**Comment by PhilETaylor** [comment]
Yeah my boss is an asehole too... I'll be physically in the office after church on the 25th :)
