### ISSUE TITLE
[joomla.org] - CSS for CDN

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-websites#817]
The Joomla main menu on www.joomla.org got a strange background-color: #eee; for :focus.
.nav > li > a:hover, .nav > li > a:focus {
    background-color: #eee;
    text-decoration: none;
}
For :hover it is overwritten by nav-pills, but not for :focus. So with the focus on an menu item, the background-color is #eee and font-color is #fff. Which is whitish on white. 

To solve this, :focus could be added to the nav-pill to use the same color like for hover.
.subnav .nav-pills > li > a:hover {
    background-color: #103b60;
    border: 1px solid #092034;
    box-shadow: 0 -1px 0 rgba(255, 255, 255, 0.2) inset;
}
Adding .subnav .nav-pills > li > a:focus in the above should do the trick. Or a different color and background-color only for :focus.

**Comment by Sandra97** [comment]
Thanks @StefanSTS, your change proposal is applied on joomla.org.
Closing this issue.
Re-open if needed.

**Comment by StefanSTS** [comment]
That was fast, thanks. Looks nice now.

**Comment by StefanSTS** [comment]
Just seeing on this page: https://www.joomla.org/3/ it is still with the white background.
There are two different custom.css in play. I have no idea how the pages are organised, might be good to add that in a main template CSS that is used for all pages.
Sorry for the Xmas work. ;-)

**Comment by Sandra97** [comment]
It's applied on joomla.org only for the moment. 
It will be applied later on all websites, as it requires a CSS change in the template used on all properties. So it will take more time.

**Comment by StefanSTS** [comment]
Thanks for the info, thank you so far.

**Comment by mbabker** [comment]
The change has been incorporated into the template repo and will be included in the next rollout.
