### ISSUE TITLE
[jvel] 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-websites#818]
https://vel.joomla.org/ is not diplaying well.
Have a look at https://vel.joomla.org/live-vel

**Comment by mandville** [comment]
Please define your statement.

**Comment by MartijnMaandag** [comment]
Did somebody resolve the problem? What you saw was only the left column (no details).

**Comment by ot2sen** [comment]
Does look like they fixed it since this morning. Then there was blank space at 'live vel', 'resolved' and 'articles'. Now it does show text

**Comment by mandville** [comment]
Apparently along with many other J.org sites, there were performance and caching issues.
