### ISSUE TITLE
[jvel] Error at frontpage

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-websites#820]
VEL site is down, not loading content area, with the following error at FrontPage:

Warning
Error loading library: joomla, Library not found.

**Comment by alikon** [comment]
see #819

**Comment by MATsxm** [comment]
closing as duplicate with #819

**Comment by ot2sen** [comment]
Speed of light Alikon were seconds faster :) As long as it get fixed

**Comment by alikon** [comment]
@ot2sen it seems affecting *.joomla.org
