### ISSUE TITLE
Media not displaying in admin view[jrd] 

### ISSUE THREAD

**Issue by lkhohn** [joomla/joomla-websites#823]
When logged into my Joomla admin account, the files in Media do not display. Other assets like Articles are displayed and everything is loading correctly on the site. Why are the images in Media not showing up? Help because I am unable to make any changes to my site!

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
