### ISSUE TITLE
Joomla! Forums login issues

### ISSUE THREAD

**Issue by adspedia** [joomla/joomla-websites#824]
Hi there!

I am trying to recover my forums password. The recovery form says my email is not registered.
If I try to register a new account, it says this email is already in use.
Can you help?

**Comment by ChiefGoFor** [comment]
Hi there! I'm happy to help you. I've reached out to you on Twitter via PM.

**Comment by ChiefGoFor** [comment]
This issue can be closed.

**Comment by jeckodevelopment** [comment]
Thank you @ChiefGoFor
