### ISSUE TITLE
[jcomm] No picture when sharing on Twitter

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-websites#826]
I shared the [Thank-You blog](https://community.joomla.org/blogs/community/3094-thank-you-joomla-community.html) on twitter today but in there's no picture in the tweet, just a placeholder.

https://twitter.com/joomla/status/819204726558375936

What goes wrong here?

**Comment by MATsxm** [comment]
¯\_(ツ)_/¯

**Comment by JansenInternetservice** [comment]
Be sure to use the correct image size: twitter cards expects 160x160

**Comment by Sandra97** [comment]
I don't think it's a size issue. 
And we're using Summary Card with Large Image so the images for "this Card should be at least 280px in width, and at least 150px in height", and not 160x160.

**Comment by Sandra97** [comment]
It's now solved. I just did several tests and images are now correctly displayed. 
Closing this issue.
Re-open if needed.
