### ISSUE TITLE
[META] Gravatar for "Joomla! Marketing Team" seems "fat"

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#828]
When you look at the "external" feeds on the `www.joomla.org` homepage, the avatar used for the marketing team seems a little distorted and "fat" (for lack of better terms) compared to the other black logo avatar which is used as a default when the user email doesn't exist on Gravatar (screenshot of the relevant section below).  Can someone check this and upload a good image?

<img width="453" alt="screen shot 2017-01-14 at 11 32 45 am" src="https://cloud.githubusercontent.com/assets/368545/21956757/49aee3fa-da4d-11e6-864d-09a185a52a9c.png">

**Comment by Sandra97** [comment]
Yes, that's true! You definitely have bionic eyes! 
What is strange to me is that even if the links to the image are different, both seems to call the same pic 'images/blog_noavatar.40.png'

**Comment by mbabker** [comment]
That path is the default if the email address (which is MD5 hashed) isn't registered on Gravatar.  So whatever email is associated with the marketing account on CJO is registered there.

**Comment by Sandra97** [comment]
I registered the email address and changed the default avatar.

**Comment by Sandra97** [comment]
I think we're good now, but I don't have bionic eyes ;)

**Comment by jeckodevelopment** [comment]
They're good now.
Good job Sandra! ;)
