### ISSUE TITLE
[jrepo] Use of Social Icons seems inconsistant

### ISSUE THREAD

**Issue by ChiefGoFor** [joomla/joomla-websites#83]
We have social icons on pages like:
Code of Conduct: http://repository.joomla.org/about-joomla/the-project/code-of-conduct.html

But not on pages like:
What is Joomla: http://repository.joomla.org/about-joomla.html
Get Involved: http://repository.joomla.org/about-joomla/contribute-to-joomla.html
Technical Requirements: http://repository.joomla.org/about-joomla/technical-requirements.html

What is the criteria behind what pages to put these one?
Thanks!

Edit: Great work everyone! It looks awesome!

**Comment by mbabker** [comment]
Personal opinion (and how I do it with my own sites), news content type pages should have the sharing icons whereas static type content (code of conduct, tech requirements, honor roll, leadership team, etc.) would not have those icons.

I've updated it for that configuration (the plugin was actually configured to only render for the "About Joomla" category which doesn't include the news).  We can tune it from here.

**Comment by ChiefGoFor** [comment]
Thanks Babker.
