### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by IrvingPuc** [joomla/joomla-websites#830]
[Hola buen día. Tengo problemas al momento de ingresar al servidor o al administrador de una de las paginas que conforman el gurpo de trabajo. Lo que pasa es que fue creada pero se nos perdieron los accesos. Que información requieren para verificar? ](http://www.sji.com.mx/)

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
