### ISSUE TITLE
Registration failure

### ISSUE THREAD

**Issue by xandrani** [joomla/joomla-websites#834]
1. I register for a demo Joomla site
2. I get an email verification (and click on the verification link, it works)
3. I save my login details in a password manager
4. I successfully view the demo page, and visit the administrator panel

All great so far.

5. I get logged out automatically (weird and annoying)
6. I try to login again (using the password manager) - it fails
7. I go to reset password, but I'm told the email isn't registered - it's the SAME email where I received the verification link
8. The demo website is still viewable, I just can't access the administrator page
9. I try to report the error in the forums... but... errr... can't login!
10. As I can't login, I'm told to contact the board administrator (which can apparently be done clicking on the link)
11. The link says there is no board administrator. Oh dear.

If you can't get registration sorted then you've got serious problems! Zero credibility in your platform. Sorry to say it, but this is a huge issue.

**Comment by kirilhristov** [comment]
Hello,

We've tested everything mentioned here and cannot recreate any of the bugs on a platform level. The auto-login can get glitchy if you are using an unusual/unstable network setup. 

Please contact SiteGround Support (https://www.siteground.com/contact_us.htm), as we are the official provider of the Demo. That way we can identify your account and provide specific details on your case.  

Thanks!
Kiril

**Comment by MATsxm** [comment]
Thanks - closing and see the link above if needed
