### ISSUE TITLE
Css via CDN not loading for any Joomla Properties (At least via my ISP in Pune, India) 

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-websites#835]
The CSS file https://cdn.joomla.org/template/css/template_2.1.1.min.css does not load for me.. 

Your connection is not private

Attackers might be trying to steal your information from cdn.joomla.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

![selection_096](https://cloud.githubusercontent.com/assets/673176/22406667/01d1ebfe-e67d-11e6-9b40-ba4b8591f0d5.png)

**Comment by ashutoshvct** [comment]
@parthlawate Their Official website also has some CSS issues. I cleared my cache and still their website is not loading properly.
![joomlacssbroken](https://cloud.githubusercontent.com/assets/16873740/22413295/b075ac36-e6dc-11e6-8461-271b40528cc8.png)

**Comment by nayemmajhar** [comment]
@parthlawate Try different server rather than Indian; we are facing the same issue from Bangladesh. I have checked different servers ( using https://gtmetrix.com/ ) are located in the different region in the world ( Canada, USA, China, etc.), and the site is working fine. What's the problem could happen?

**Comment by nayemmajhar** [comment]
Ohh, Problem solved, sites are working.

**Comment by nayemmajhar** [comment]
It is not working again.

**Comment by ashutoshvct** [comment]
@parthlawate @nayemmajhar It is an ssl issue you can try the URL without https and it will work.

**Comment by Radek-Suski** [comment]
@nayemmajhar , @parthlawate could you check the certificate information? I am wondering what's invalid about it.

**Comment by nayemmajhar** [comment]
@Radek-Suski Yeah. SSL certificate information is perfect. When people browser site using a server from India, get above issue ( Screenshot posted by @parthlawate ) then if I went forward using unsafe browsing, I saw Nginx server of CDN site stop responding.

Now, site is working fine.

**Comment by nayemmajhar** [comment]
<img width="1201" alt="screen shot 2017-01-30 at 4 32 31 pm" src="https://cloud.githubusercontent.com/assets/3455568/22419829/653963b6-e709-11e6-8f84-c1e81c8225ed.png">
<img width="1118" alt="screen shot 2017-01-30 at 4 32 47 pm" src="https://cloud.githubusercontent.com/assets/3455568/22419830/653d6dda-e709-11e6-9783-9d7e9ae0adc4.png">


Still these logo is not showing in site
https://cdn.joomla.org/images/Joomla_logo.png
https://cdn.joomla.org/rochen/rochen_footer_logo_white.png

**Comment by parthlawate** [comment]
Working fine for me now  !

**Comment by mbabker** [comment]
It's not fixed.  The template on many of the sites was edited to load the CSS file from the local domain versus the CDN.  Are you getting the Rochen logo in the footer?  That's coded into the CSS to always load from the CDN, it's not domain relative.

**Comment by parthlawate** [comment]
Hi,

I can see the logo .. You are right about the css its loading locally not from the CDN.. but the logo is from the CDN

**Comment by mbabker** [comment]
The API site being all static HTML files would probably be a good test bed here.  If that's working fine, we might be good to switch the sites back to the CDN.  The https://help.joomla.org main page too.

**Comment by parthlawate** [comment]
Ok Confirmed that it is NOT FIXED. https://cdn.joomla.org/template/css/template_2.0.0.min.css still giving an error due to ssl.. 

help.joomla.org as well as the api sites are broken as well 

Parth

**Comment by mbabker** [comment]
Thanks for that note!

**Comment by mbabker** [comment]
Just an FYI from the CDN provider:

> We have managed to replicate the issue and are investigating the root cause of it.

So, progress.

**Comment by parthlawate** [comment]
Seems to be sorted now .. Thank you !!
![selection_097](https://cloud.githubusercontent.com/assets/673176/22450849/a50aa9c4-e78f-11e6-94f4-8aa808ebcaf1.png)
