### ISSUE TITLE
Weird layout issue on https://www.joomla.org/sponsor

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#838]
When I look at:

https://www.joomla.org/sponsor

I see: 

![image](https://cloud.githubusercontent.com/assets/4998032/22554313/ef58598c-e95f-11e6-820a-979d9c10b0b8.png)

The buttons are too low. 

I am not sure who are in charge of this site. Maybe Joe?

**Comment by Sandra97** [comment]
Thanks for reporting. I think it happened when I changed org homepage. I'm gonna correct it asap

**Comment by Sandra97** [comment]
Display corrected!
I'm closing this issue. 
Re-open if needed
