### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by bcraigie** [joomla/joomla-websites#842]
RuntimeException

Error fetching page from MediaWiki API: The page you specified doesn't exist

https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help36:JHELP_COMPONENTS_com_dpcalendar_OPTIONS

**Comment by mbabker** [comment]
`com_dpcalendar` isn't a core extension and as such wouldn't have any pages on the Joomla Documentation Wiki.  Also, there's a known issue with hitting the help button from a component's configuration page which causes it to always try to load help screens from the wiki versus whatever source an extension developer may have specified.

Closing as not a website issue.
