### ISSUE TITLE
[jcomm] Login-Fields "Username", "Password" to long

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#843]
Please look at Screenshot, start at around 1198px till 980px.

![screen shot 2017-02-07 at 10 08 13](https://cloud.githubusercontent.com/assets/8235763/22684764/07793c54-ed1e-11e6-8b83-1f9f76e38267.JPG)

**Comment by zero-24** [comment]
It comes from `input#modlgn-username, input#modlgn-passwd` in the custom.css

**Comment by Joomv** [comment]
Fixed

**Comment by franz-wohlkoenig** [comment]
Thanks
