### ISSUE TITLE
extensions.joomla.org does not use our ad server but serves ads directly from AdSense

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#844]
I think that @anibalsanchez is aware of this and it will be fixed in an upcoming re-design. I am just logging it here so we do not forget.

**Comment by anibalsanchez** [comment]
Hi,

We are on our way to deliver the update. To be ready, we only have the ad tags for the JED homepage, so we need the rest of the required tags.

These are the current Ad tags:

**Publisher ID** ca-pub-xxx8555
**Homepage Google Ads** = xxx7058
**Access & Security Category Ads** = xxx8657
**List Page Banner Google Ads** = xxx8657
**Extension Page Google Ads** = xxx8657

And, we have the new tags zoneid=2 and zoneid=62 for new Homepage Google Ads 300x250 and 720x90

Please, send me the rest of the associated new tags for 1. **Access & Security Category Ads** (300x250 and 720x90), 2. **List Page Banner Google Ads** (300x250 and 720x90) and 3. **Extension Page Google Ads** (300x250 and 720x90)
