### ISSUE TITLE
forum.joomla.org is not serving ads through our ad server

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#846]
I would like to work with whoever is in charge of the forum to get them migrated to serving ads through our ad server instead of serving banners directly through Adsense.

**Comment by JacquesR** [comment]
I think Olaf @ooffick can help.

**Comment by ooffick** [comment]
Please sent me the details so that I can implement it. 

Kind regards 
Olaf

**Comment by ooffick** [comment]
That's implemented now.
