### ISSUE TITLE
[jcomm] Login-Module: Button on wrong Place; different Field-Length

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#847]
Please have a look at Login-Module on [community.org](https://community.joomla.org/)
![1](https://cloud.githubusercontent.com/assets/8235763/22873586/52138416-f1c1-11e6-9e9d-d049b0e76b13.png)

**Comment by Joomv** [comment]
Hi,
They are all the same width.  The secret key has a helper icon but if you run a straight ruler down the side they are all the same.

**Comment by franz-wohlkoenig** [comment]
@Joomv as i don't understand really should i close this?
