### ISSUE TITLE
[jdocs] Broken Links / How to Organize a JoomlaDay™

### ISSUE THREAD

**Issue by SpiritJC** [joomla/joomla-websites#848]
Broken link to OSM Website:

https://docs.joomla.org/How_to_Organize_a_JoomlaDay%E2%84%A2#Requesting_a_JoomlaDay.E2.84.A2

"......You can do that over a simple form at the OSM Website"

That Form doesn`t exist anymore.

The Domain Request Form schould be linked to the TM website https://tm.joomla.org/contact

**Comment by Sandra97** [comment]
Hi Marco!
JDocs is a wiki, so everyone can edit the content, so feel free to change it
Thank you!

**Comment by MATsxm** [comment]
Made the change **BUT** like Sandra said, the Mainteners for the content of the Doc are the users...
