### ISSUE TITLE
[volunteers.joomla.org] Missing Report

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#851]
Report https://developer.joomla.org/news/670-production-department-team-lead-meeting.html
isn't shown in https://volunteers.joomla.org/departments/production (Tab "Reports").

**Comment by mbabker** [comment]
It wasn't published on the volunteer portal as a report (it was published before the departments were set up there actually, which is why it's on the developer network instead).

**Comment by franz-wohlkoenig** [comment]
had expect to find Report in Tab "Reports".
