### ISSUE TITLE
[jorg] /mailing-lists: old PLT-Info needs update

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#853]
in joomla.org are old infos, they need update for new Structure:
![1](https://cloud.githubusercontent.com/assets/8235763/23082175/82e4e900-f558-11e6-898b-8e1a732ffada.png)

**Comment by Sandra97** [comment]
Request has been sent to the marketing team to update this page.
Closing this issue..

**Comment by franz-wohlkoenig** [comment]
Thanks @Sandra97
