### ISSUE TITLE
[JED] Unable to Submit a Review

### ISSUE THREAD

**Issue by nobicycle** [joomla/joomla-websites#854]
Hi,

My username is nobicycle on joomla.org. I would like to submit a review for Breezing Forms Pro. Though my review appeared to be accepted, in that it appeared as the latest review on the page, today I see it has disappeared. I understand your system may consider reviews written in the middle of Borneo as spam, but really it was a genuine review following 3 months of usage. Please advise.

Best wishes

**Comment by Sandra97** [comment]
Hi,

I presume your issue is related to extensions.joomla.org and not joomla.org.
Could you please submit it here: https://github.com/joomla/jed-issues/issues

Thank you.
