### ISSUE TITLE
[jrd] Issue after trying to change company logo

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#855]
Hi,
Was working nicely until I changed the logo of my listing, then I can no more edit and I have the screen below:

![image](https://cloud.githubusercontent.com/assets/13470265/23172908/b6aa1c5e-f857-11e6-80b2-ad4f09165905.png)

**Comment by genr8r** [comment]
Hey @sebastienlapoux it looks like CSS is missing. I know there were a couple of issues getting it to load from the CDN properly not too long ago. (e.g. #835)

I just tried updating the logo for my listing and was not able to replicate your problem. Can you please check yours again in the event it was just a glitch in loading the CSS from the CDN?

**Comment by genr8r** [comment]
@sebastienlapoux is this still an issue for you? I believe this is addressed in #881 reopen if needed

**Comment by genr8r** [comment]
I was mistaken. This issue persists in spite of the fix for #881. I am reopening this until I fully resolve it.

**Comment by Sandra97** [comment]
@genr8r Is this issue solved?

**Comment by Sandra97** [comment]
Any update?

**Comment by genr8r** [comment]
@Saeedghb was able to resolve the CSS issues that was breaking pages. There was an issue with the size of the logo image that @sebastienlapoux had uploaded. I don't have all the details yet from Saeed other than that it is taken care of. I am also still not able to assign github issues to @Saeedghb. If someone is able to correct that I can loop him into these conversations directly. thanks all!
