### ISSUE TITLE
[jdev] Content Refresh

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#856]
The dev site could use a content refresh for its non-news and security areas.  Things like the roadmap for each "featured" project, about page, etc.

Some of it will probably be updating links and terms for the new structure.  Some of it may be full rewrites or content archiving.

**Comment by mbabker** [comment]
Punchlist:

- [ ] Move https://developer.joomla.org/cms/contribute.html to https://developer.joomla.org/contribute.html (this is the JCA page, it's not specific to any single aspect of Joomla)
- [ ] Update https://developer.joomla.org/cms/roadmap.html (there needs to be one canonical source for this info, I know there's a page on the docs wiki too)
- [ ] Move https://developer.joomla.org/cms/development-strategy.html to https://developer.joomla.org/development-strategy.html (this is a project wide strategy, should be annexed by each product if needed)
- [ ] Review all content at https://developer.joomla.org/framework.html and in its category (some of this should probably be pushed over to https://framework.joomla.org honestly)
- [ ] Review all content at https://developer.joomla.org/tracker.html and in its category
- [ ] Either find a new home for the release notes menu module on https://developer.joomla.org/tracker.html or just unpublish it (all the links from the https://www.joomla.org release articles are still valid)
- [ ] Do a review on the Smart Search index, found several articles that should've been long unpublished still accessible

**Comment by Sandra97** [comment]
For the Framework, we could already redirect:

- https://developer.joomla.org/framework/contribute.html -> https://framework.joomla.org/contribute
- https://developer.joomla.org/framework/support.html -> https://framework.joomla.org/#involved
- https://developer.joomla.org/framework/downloads.html -> https://framework.joomla.org/#go

For https://developer.joomla.org/framework/report-an-issue.html
We can include its content to Framework, or if keeping it on dev, we should at least adding a link to GitHub ;)

**Comment by mbabker** [comment]
The GitHub link is https://github.com/joomla-framework (that's the best link to give, each individual package has its own issues/PRs, there isn't a single repo to direct to)

**Comment by Sandra97** [comment]
Link added.

**Comment by mbabker** [comment]
One more simple item.  I think the homepage uses one of the articles modules to show the latest news and the top block is a single article.  Let's either turn this into a category blog view and have the three product boxes be a custom module so we have an "adequately" cached component view or at least change the module to not use sliders and probably limit it to the latest 2 or 3 news items (also, give it a heading so it's clear what's in the sliders; right now it's just random titles and text).

**Comment by Sandra97** [comment]
I don't like the accordions. Keeping the 2/3 last news is enough. Agree for a title. And I wanted to try to improve also the look of the top 3 blocks, they are really not nice.
I'll look at it as soon as you'll keep me less busy ;)

**Comment by mbabker** [comment]
Well, the intent isn't just for you to do all the busy work 😉

**Comment by Sandra97** [comment]
But the end... Well, you know

**Comment by Sandra97** [comment]
What about merging the Development Status Page into the new roadmap page? 
And, IMHO, we don't need anymore to keep 2.5 information.
We could have the menu renamed Developement Satus & Roadmap so that the roadmap could be found in an easiest way (and of course taking care of not creating too many 404)
