### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by thecitizens** [joomla/joomla-websites#857]
Fatal error: Class GJFieldsFormField contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (JFormField::getInput) in /home/theciti1/public_html/libraries/gjfields/gjfields.php on line 18

**Comment by thecitizens** [comment]
Please help me fix it

**Comment by zero-24** [comment]
this does not sound like a issue with jdocs please move this questions to https://forum.joomla.org Thanks.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
