### ISSUE TITLE
[jforum] No Active State on the items of the Menu-Bar in "Joomla-Forum" websites

### ISSUE THREAD

**Issue by nileshprasad137** [joomla/joomla-websites#858]
Hover on the items work , but the active-state on the items vanish as soon as the website is loaded.

![joomla_reg](https://cloud.githubusercontent.com/assets/16336390/23312860/48311a2a-fae1-11e6-9a0d-5f2cd9d3a394.png)

![joomla_iss](https://cloud.githubusercontent.com/assets/16336390/23312871/58315c5a-fae1-11e6-934b-ca90ffecf28e.png)

**Comment by nileshprasad137** [comment]
Is there no repository for Joomla Forum?

**Comment by Sandra97** [comment]
@nileshprasad137
Is this issue still valid?

**Comment by Sandra97** [comment]
Closing this issue as its author didn't answer.
