### ISSUE TITLE
Updating Readme file 

### ISSUE THREAD

**Issue by nileshprasad137** [joomla/joomla-websites#859]
There maybe some minor modifications which are needed in README.md .
The website corresponding to Coding Standards and Help has been moved to some other destinations.
Take a look !
[Old Link to Coding Standards](https://joomla.github.io/coding-standards/)
[Old Link to Help Site](https://help.joomla.org/)

Can I proceed to fix this?

**Comment by mbabker** [comment]
The help site is still correct.  That domain is still in use.

It used to have two separate CMS installs on it.  The old Joomla! 1.0 site has been archived which is why you see the offline page, but the help screen system is still served through it so the domain is still valid.

**Comment by mbabker** [comment]
Specifically, https://github.com/joomla/help.joomla.org

**Comment by nileshprasad137** [comment]
Okay, what about Coding Standards website?

**Comment by mbabker** [comment]
That's moved as noted in https://github.com/joomla/joomla-websites/issues/796

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-websites/pull/860
