### ISSUE TITLE
[jstand] Changing Contributing to this manual

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#861]
The part `Contributing to this manual` (under `Introduction`) should be changed. As noted in https://github.com/joomla/joomla-websites/issues/796

**Comment by mbabker** [comment]
It's already updated.

Also, it reads live from GitHub (it's not content saved in the CMS install).  So feel free to tweak https://github.com/joomla/coding-standards/tree/master/manual as needed.

**Comment by zero-24** [comment]
hmm looks like i have missed it. Thanks.
