### ISSUE TITLE
[jforum] Move issues.joomla.org to https.

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#863]
Please change the URL from http://issues.joomla.org to https://issues.joomla.org 😄 

![image](https://cloud.githubusercontent.com/assets/2596554/23326831/fba0880e-fb02-11e6-964c-654031694574.png)

https://forum.joomla.org/viewforum.php?f=579
https://forum.joomla.org/viewforum.php?f=728

**Comment by zero-24** [comment]
same for this page: 
![image](https://cloud.githubusercontent.com/assets/2596554/23326846/4f47e0f6-fb03-11e6-81cb-037f53b706ba.png)

**Comment by ooffick** [comment]
This is fixed now

**Comment by jeckodevelopment** [comment]
Thanks

**Comment by zero-24** [comment]
:+1: @ooffick
