### ISSUE TITLE
[jdev] Combine Dev Site Extensions to One Repo

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#864]
Create a repository at https://github.com/joomla/developer.joomla.org and merge the repositories for each of the site's extensions into that new repo.

- https://github.com/joomla-projects/com_code
- https://github.com/joomla-projects/com_trackerstats
- https://github.com/joomla-projects/plg_content_nightlybuilds

**Comment by zero-24** [comment]
@mbabker can you create that repo than i can prepare pull requests for that repo with the content of the 3 old repos.

**Comment by mbabker** [comment]
Done.

Please keep the file structure matching the CMS structure (like the com_code repo does now).  This makes it easier to clone the repo and drop a full CMS install in or if we decide later on to drop a clone of the entire site (like the volunteer portal) into the repo (still to be decided on that one, IIRC we have at least Akeeba pro extensions and I prefer to respect the companies with pro versions of extensions, even if GPL, and not make those versions so easily accessible).

**Comment by zero-24** [comment]
@mbabker please see: https://github.com/joomla/developer.joomla.org/pull/1
