### ISSUE TITLE
[jdocs] Link to 404 on https://docs.joomla.org/JDocument/addStyleSheet

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#867]
https://docs.joomla.org/JDocument/addStyleSheet
The Link to the API in the footer leads to a 404

**Comment by MATsxm** [comment]
The JDoc is a Wiki then *YOU* are the maintener 😉 
You can just log the JDoc, edit the page.
Not sure but I guess the nex link should be: https://api.joomla.org/cms-3/classes/JDocument.html#method_addStyleSheet

**Comment by coolcat-creations** [comment]
If i would have find the right link i wouldn't have used the "report an issue" link. ;-)

**Comment by MATsxm** [comment]
fixed

**Comment by mbabker** [comment]
Actually, these API docs are for Joomla! 1.5.  It'd be nice if they were marked as such so they could be archived and fall off the face of the internet.  I've changed the link as such.

**Comment by MATsxm** [comment]
@Hutchy68 could you take a look at Michael's comment 😉 
Thanks

**Comment by Hutchy68** [comment]
No 😈

😉 But I'll make a new task, "take old API links on a one-way trip to nowhere land."

**Comment by MATsxm** [comment]
pffff
😝
