### ISSUE TITLE
[jdocs] update links or archive API pages

### ISSUE THREAD

**Issue by Hutchy68** [joomla/joomla-websites#868]
There are a lot of pages with external links that are broken to the J 1.5 API. 

- update links
- delete pages 
- archive pages

**Comment by MATsxm** [comment]
Btw... thank you to explain your minion @Sandra97 the archive process, she has nothing to do... 😉

**Comment by mbabker** [comment]
It's all at https://api.joomla.org/1.5/ as a short term fix the broken links thing.

**Comment by Sandra97** [comment]
Minion is on strike.

**Comment by Hutchy68** [comment]
The pages in the main namespace were duplicates of those found in namespace API15: ..... which are archived and set for "noindex,nofollow" and I will double check that. I don't know why they were missed when the original batch was nuked 3 years ago. They are all gone now. 

![capture_jwikibot](https://cloud.githubusercontent.com/assets/3527469/23373402/d174aa14-fced-11e6-99c2-4ef09afa5b93.PNG)

**Comment by Hutchy68** [comment]
Ok, the API15 and others are not being blocked with a ```<meta name="robots" content="noindex,nofollow">```. I can make some setting adjustment it to block the API15: pages from being indexed by Google. I have them set at a low weight of indexing in the sitemap we provide Google but they still appear in search results.

Let them be indexed, block them? If I block them, I might as well delete them.

**Comment by Hutchy68** [comment]
Since no one answered me... I made the following adjustments. 

- all API pages are now locked from editing unless you are a sysop
- updated message at top... It exists only as a historical reference, it will not be improved and its content may be incomplete and/or contain broken links. Even made it orange for @wilsonge 
- all transclusions into those pages have been subst with hard text so they are static
- left the sitemap settings alone so they are still searchable by Google
- not searchable by Google CSE on site

**Comment by Sandra97** [comment]
Thank you Tom!!! The orange notice is great ;)
I'm closing this issue.
Re-open if needed.
