### ISSUE TITLE
[jdocs] Typo on codeline

### ISSUE THREAD

**Issue by deenison** [joomla/joomla-websites#87]
Hi guys, just found a typo [here](https://docs.joomla.org/J3.x:Using_Tags_in_an_Extension#Prepare_the_view).

On the section "**6. Prepare the view**", the second line of code is:
```php
$item->tags->getItemTags('com_newsfeeds.newsfeed.' , $this->item->id);
```

but it should be:
```php
$item->tags->getItemTags('com_newsfeeds.newsfeed' , $this->item->id);`
```

Note the dot in the end of the first parameter.

Thanks.

**Comment by MAT978** [comment]
Hello and thank you for pointing.
As a Wiki, The Joomla! Documentation! is a participatory system and allows all registered users to correct, update or create new content.
To register, please fill out the following form and then you will be able to contribute with your change:
https://docs.joomla.org/index.php?title=Special:UserLogin&type=signup
If necessary, do not hesitate to contact me.
Thank you in advance .

**Comment by MAT978** [comment]
Thanks a lot deenison.
I'm closing this as fixed

**Comment by deenison** [comment]
I was writting here just now. Lol.

Thank you @MAT978
