### ISSUE TITLE
[jcode] Remove spam

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-websites#871]
I have received a warning from Google Adsense that they might suspend our account (and all our Adsense income) unless we ensure that our content is safe.

It has flagged this page as having "Adult content" which I do not personally see, but I can only asume that it has flagged the spam.

http://joomlacode.org/gf/project/joomlaxplorer/news/?id=3911

So can we please have this kind of spam removed **immediately**?

**Comment by mbabker** [comment]
The only person I know who has admin access on that system told me last night his key was being rejected by the server.

**Comment by mbabker** [comment]
Ken's suggestion FWIW was to just remove JoomlaCode from the AdSense account.  I honestly don't know if that's practical or desired at this point, but if we're really left with nobody who has admin credentials to that system (and GForge left us high and dry years ago), what options do we have left?

**Comment by sam-suresh** [comment]
If JoomlaCode is not making a desireable income, we should consider to remove adsense ads from JoomlaCode as it is not actively maintained. Previously some files reported unsafe from JoomlaCode which is another violation of adsense terms.

**Comment by Joomv** [comment]
@aDaneInSpain as that site is pretty much abandonware - I think the best is to remove it so as not to jeopardise everything else.

**Comment by aDaneInSpain** [comment]
So who can remove it? We can't block it from the AdSense side, we have to remove the code.

**Comment by mbabker** [comment]
Well considering the only person I know who had admin access apparently can't get into the server to remove the spam, I doubt someone has access to modify the template or any other aspect of the global GForge install right now...

**Comment by mbabker** [comment]
We've reacquired access into the server.  I'm still trying to find my way around the system, but I've managed to find the base template file and comment out the loading of the AdSense JavaScript in the head, so ads are no longer loading into the site.

**Comment by mbabker** [comment]
Managed to elevate my user account to a site admin.  Deleted the spam content.

Closing, task complete.
