### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by truittcontrol** [joomla/joomla-websites#872]
Hi,

I'm properly updated to 3.6.5.  I use a security plugin to hide my login area, and my work systems are quite secure (I have a small number of systems, all password protected and under a solid security system after hours).

I have reason to believe that there is some kind of leak, as I found an unknown super user had created an account in my organization's main site, and also managed to do so without creating a log entry as to when they actually created the account.  I have since deleted it, but I thought someone might want to be aware.  

Only two people have FTP or MySQL access in my organization, and we  take our security seriously.

For security purposes, I prefer to not give identifying factors away as to my site, but I can show you some screenshots with sensitive info removed:

![screenshot1](https://cloud.githubusercontent.com/assets/26126052/23485161/dbfa2834-fe9f-11e6-91a1-b4d1d5ef1325.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/26126052/23485166/e08ef23a-fe9f-11e6-9438-c4a0f5f09989.jpg)

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
