### ISSUE TITLE
[jorg] Put Custom Code Into Repo

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#874]
After 3.7 launches and we've updated the site assets, merge custom stuff (layout overrides, extensions, etc.) for the main www domain into the https://github.com/joomla/joomla.org repo.

This should also cover the `/3` subsite.

**Comment by mbabker** [comment]
Seeded the repo with the main site's custom stuff.  Will do `/3` after the 3.7 page launches.

**Comment by Sandra97** [comment]
We didn't do it after 3.7. Should we wait and do it after the launch of the 3.9 LP?

**Comment by Joomv** [comment]
Did this ever happen?
