### ISSUE TITLE
cmd click menu opens in current tab and new tab

### ISSUE THREAD

**Issue by rwbarg** [joomla/joomla-websites#875]
In /administrator, cmd + click (mac) on Menus > [any menu] opens up that menu in a new tab AND goes to that menu in the current tab. I obviously want it to just go there in the newly opened tab.

I often open multiple tabs in /administrator so I can look at a menu item, a module assigned to it, and a K2 item assigned to the module. I often start in a module because then I can see what menu item it is assigned to. I have gotten so used to this bug that it is muscle memory to open cmd + click [menu] then press the browser back button right away.

Happens in Chrome, Firefox, Safari on Mac.

**Comment by franz-wohlkoenig** [comment]
confirmed. 
#### The Result of cmd-click is different:
Starting Point is "Control Panel"
- cmd-click on "Users>Manage" or "Menus>Manage" or "Content>Articles" ... shows in both tabs same Screen,
- cmd-click on "System>Global Configuration" or "System>Global Check-in" shows only new Screen in new Tab.
### Test on
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by franz-wohlkoenig** [comment]
@MATsxm ups, haven't looked repository.

**Comment by franz-wohlkoenig** [comment]
see [14317](https://github.com/joomla/joomla-cms/issues/14317)
