### ISSUE TITLE
[jrd] Broken page for https://resources.joomla.org/en/joomla-learning-partners

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#877]
Hi @genr8r ,
The page https://resources.joomla.org/en/joomla-learning-partners is broken (css?), just few items displayed.
No mean to list all JLP currently. Not good at all for Certification Program.

Please fix this quickly!
Thanks.
<img width="1440" alt="screen shot 2017-03-08 at 08 45 29" src="https://cloud.githubusercontent.com/assets/13470265/23699731/85805112-03f0-11e7-9594-38063ee0bc6e.png">

**Comment by sebastienlapoux** [comment]
It's the same on some others pages such as Project Management https://resources.joomla.org/en/category/project-management

**Comment by franz-wohlkoenig** [comment]
Can't confirm:
![bildschirmfoto 2017-03-08 um 11 28 28](https://cloud.githubusercontent.com/assets/8235763/23700213/70a53724-03f2-11e7-8aa1-1f2d3855e933.JPG)

**Comment by sebastienlapoux** [comment]
It has been fixed! I have no more the issue too.
Thanks.

**Comment by franz-wohlkoenig** [comment]
maybe a cdn-Issue. Close?

**Comment by genr8r** [comment]
I am also not able to re-produce the problem.  I will close. Please re-open with steps to reproduce if it recurs.

**Comment by sebastienlapoux** [comment]
![image](https://cloud.githubusercontent.com/assets/13470265/24365267/a593a92a-1315-11e7-917b-e2488898e804.png)
Always the same, even if using incognito windows on Chrome. Same on chrome, firefox, safari (wifi). Same on smartphone with 4g connection.

**Comment by Sandra97** [comment]
I can confirm, same issue for me
Note that the <head> is totally empty

**Comment by Hutchy68** [comment]
```
Request URL:https://resources.joomla.org/en/joomla-learning-partners
Request Method:GET
Status Code:500 
```

**Comment by mbabker** [comment]
The page is still returning a 500 error code...

**Comment by zero-24** [comment]
We have just got another report see #962 thanks.

**Comment by genr8r** [comment]
Yes. The dev working on it does is not on github. He is the member of certifications that set up the page.  I will check status on this with him via email now. I am on the webmasters team and get pinged on all issues. So, I saw the full thread for #962

**Comment by genr8r** [comment]
I have converted this page to a standard Joomla article. I will let the certifications team know that they can either maintain the JLP information manually or correct the underlying issue on this page. I have retained the original external link menu item trying to pull zoo items by tag ala http://yootheme.com/support/question/22546
