### ISSUE TITLE
[jrd] is it fair to display on top always same companies?

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#878]
Hi,
Due to the fact that all list are ordering alphabetically and that there is a pagination, it's always same companies displayed on top, exemple:
https://resources.joomla.org/en/category/creative-strategy
https://resources.joomla.org/en/category/training-education
https://resources.joomla.org/en/category/technical-support

Is it fair? How it can be improved?

Thanks.

**Comment by genr8r** [comment]
@sebastienlapoux we have been working through this concern internally. Zoo does not provide random listing order as an option. We are working to see if we can address that in the short term. Longer term we are laying the groundwork to develop a custom component for the JRD to more effectively handle the listings.

@jeckodevelopment is there somewhere we can push this to feature request as it is not truly a technical problem with the site?

**Comment by mbabker** [comment]
This repo works for both issues and feature requests.  We don't have separate tracking for that, best you could do is add a feature request label.

**Comment by sanderpotjer** [comment]
We recently created a kind of similar directory for a client, see https://www.byte.nl/partners This randomly loads the items, and offering several filtering options. 

If the decission is made for a custom component we are happy to offer what we've created for the JRD.

**Comment by genr8r** [comment]
Thank you @mbabker.

@sanderpotjer I really appreciate that. I just started conversations with @aDaneInSpain last week. We were going to have him take point on development after we have a chance to spec out exactly what we want.

I have also been tracking recent conversations about consolidating all of these types of items into a consolidated repo for Joomla projects.  I believe this qualifies as I know that Søren was already looking to post everything to github.

**Comment by sebastienlapoux** [comment]
Thanks. Showcase site has all these features too. SEBLOD natively propose Random or Shuffle or Random + Shuffle.

**Comment by genr8r** [comment]
Hey @sebastienlapoux, we included this concern in the working specification for the next iteration of the JRD. We will be posting the spec for review when it is completed. I am going to close this feature request. Feel free to let me know if you need anything further on this.
