### ISSUE TITLE
[jrepo] Clean up

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-websites#88]
@Sandra97 please check the `<div>` on:
http://repository.joomla.org/about-joomla.html

**Comment by Sandra97** [comment]
Shitty HTML code. It's corrected.

**Comment by MAT978** [comment]
Same here
http://repository.joomla.org/about-joomla/the-project/mission-vision-and-values.html

I still think it's weird to discover new ones after so many checks...

**Comment by Sandra97** [comment]
HTML code of this page has been cleaned.
