### ISSUE TITLE
[jrd] style issue on logged interface

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#880]
We can not read company name or user name on my listings, my profil
![image](https://cloud.githubusercontent.com/assets/13470265/23700476/31112144-03f3-11e7-8303-e6df6c4c0095.png)

**Comment by MATsxm** [comment]
@sebastienlapoux feel like you wanna take the JRD in charge? :wink: 
thanks for volunteering </meHide>

**Comment by genr8r** [comment]
Thanks @MATsxm we are definitely looking for volunteers!  I will check the CSS on the bar for your listings @sebastienlapoux

**Comment by sebastienlapoux** [comment]
Lot better like this
![image](https://cloud.githubusercontent.com/assets/13470265/23746084/f5c0aa42-04ba-11e7-8880-cee38c290ba8.png)

Thanks!
