### ISSUE TITLE
[jrd] no more able to edit my listing

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/joomla-websites#881]
When I click on edit 
![image](https://cloud.githubusercontent.com/assets/13470265/23700682/da257956-03f3-11e7-88d1-8e4cdf088d2c.png)
No field is displayed
![image](https://cloud.githubusercontent.com/assets/13470265/23700705/f18b5c6e-03f3-11e7-882d-2dea57def434.png)

Thanks.

**Comment by sebastienlapoux** [comment]
If I click on edit button from
![image](https://cloud.githubusercontent.com/assets/13470265/23700768/437db544-03f4-11e7-93f8-ccb1c335d48c.png)
I go on
![image](https://cloud.githubusercontent.com/assets/13470265/23700776/4f1edea0-03f4-11e7-838b-aa96bfe1919e.png)

Seems to be the same issue that JLP page

**Comment by genr8r** [comment]
@sebastienlapoux is this two separate issues?

Where are you finding the Edit Item link? We are using zoo and the default access for editing an item is the small pencil on the right.

Also we have JCE setup as the default editor. Did you override that in your account settings? Or it looks like the page is not completely loaded in your last screenshot.  There is no CSS and the entire Joomla TPL is missing.  Is this likely the CDN issue that I acknowledged at #855 for you?  Also, could you please update that issue with any feedback that you have or let me know that it can be closed?

**Comment by sebastienlapoux** [comment]
@genr8r thanks for your feedback.

Like described below with the screenshot, yes by clicking on the edit icon into the dark blue bar (now white bar -> better :-)).
The error is always here.
If you need take the hand on my account by changing the password and send me an email when I can change again my password.

the same on Chrome or Firefox.

**Comment by aDaneInSpain** [comment]
Bump @genr8r 

Was this ever resolved?

**Comment by Sandra97** [comment]
@genr8r Any news about that? Is it solved?

**Comment by genr8r** [comment]
@sebastienlapoux There was a field set incorrectly (Joomla contributions) on your listing that should have prevented it from showing altogether. Regardless, I set it correctly and it seems to have corrected the problem. I did reset your password to login so I could re-create the problem. I will send you the updated access.
