### ISSUE TITLE
[jrd] Joomla! and not Joomla

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#882]
Our registered trademark is "Joomla!" including the exclamation mark. The proper and complete use of our name is WITH the exclamation mark. 
https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name

Please add the bang: 
![index](https://cloud.githubusercontent.com/assets/4682328/23700928/054a62b4-03cb-11e7-9aab-28f7d7cd5675.png)

Thank you

**Comment by genr8r** [comment]
done

**Comment by Sandra97** [comment]
Thank you!

Also, still in this text, shouldn't it be `Joomla! ResourceS Directory` intead of `Joomla! Resource Directory`?

**Comment by genr8r** [comment]
Yes, good catch @Sandra97. This text was resurrected recently when I switched which component was rendering the frontpage.  So, I appreciate the review.
