### ISSUE TITLE
[jrd] Get listed display problem

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#883]
https://resources.joomla.org/en/category/design-development/3

The display isn't right! In FF and Chrome latest.

![jrd](https://cloud.githubusercontent.com/assets/736887/23713617/6bcc80e6-041e-11e7-93a8-dea5b3ad0f5b.png)

**Comment by genr8r** [comment]
Hi @Hils can you please double check? I just loaded your URL from both FF and Chrome without incident.

I think there has been an issue with CSS loading from the CDN for some Joomla propoerties.  It looks like that issue from your screenshot.  If it is related to that item I will have to kick that to higher powers as I don't have any control over how the CSS loads.

**Comment by Hils** [comment]
Hello @genr8r you will be pleased to know that the CSS has just kicked back in! I had loaded the page with cleared browser cache many times before posting so I guess it maybe needs watching for a while?
Thanks Brian :)

**Comment by franz-wohlkoenig** [comment]
@genr8r have tested after @Hils  report and it was loaded like wrote, now works. Siilar Report was yesterday i guess about cdn.

**Comment by genr8r** [comment]
Thanks for double checking.
