### ISSUE TITLE
[jrd] advert below map

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-websites#884]
There is only about 1px, if that, between the advert and the location map at the bottom of a listing page. It is barely OK when it is the usual Artisteer advert but when others appear which don't have a top border, it almost covers the bottom of the map. Because of the randomness of the adverts, I can't 'catch' one non artisteer ad to show you, sorry!
![jrd2](https://cloud.githubusercontent.com/assets/736887/23714060/d452c3e0-041f-11e7-9f21-473973015807.png)

**Comment by genr8r** [comment]
No worries. fixed.
