### ISSUE TITLE
[joomla.org] No listing of Officers

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-websites#886]
It seems no listing of officers in org and OSM site. 
However both sites have listing of Board of Directors. 

https://www.joomla.org/about-joomla/the-project/leadership-team.html
http://www.opensourcematters.org/about/organization/directors.html

**Comment by mbabker** [comment]
https://www.joomla.org/about-joomla/the-project/leadership-team.html does list the officers.  If anything, the page/article title is misleading on what is actually included.

**Comment by sam-suresh** [comment]
Yes. Treasurer is there.
So I guess it better renamed "Joomla! Officers and Board of Director"

**Comment by Joomv** [comment]
Currently working on the OSM site.  Many duplicated items are being pointed at their proper source bear with me

**Comment by sam-suresh** [comment]
Thank you Rowan!

**Comment by Sandra97** [comment]
Note that I updated this page on jorg on March 3rd, just after the name of the VP has been announced. Officers are there since then.
Joomla! Officers are part of the Board of Directors so it does not make sense to me rename it "Joomla! Officers and Board of Director".

**Comment by sam-suresh** [comment]
@Sandra97 Thank you for updating that page.

As I can read in ByLaws;
J. “Director” means a Department Coordinator (as defined in Sections 3.01(C) and
5.01)

S. “Officers” means the President, Vice President, Secretary and Treasurer (as
defined in Section 6.01).

So it make sense to have have renamed or at least have officers then board of directors unless you have a reason behind the ordering you have now.

**Comment by Sandra97** [comment]
So it means this picture posted for each announcement is giving false information:
![index](https://cloud.githubusercontent.com/assets/4682328/23832788/ade29bf4-0712-11e7-8c8d-689d73af4dcf.png)
as well as the announcements
"The Officers sit on the Board of Directors""
"The Department Coordinator Team Leaders sit on the Board of Directors "
