### ISSUE TITLE
[jrepo] Limit Pages Social Links Show On

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#89]
Need to add an exclude rule for the social share links to limit to certain categories/menu items.  On http://repository.joomla.org/about-joomla/the-project/leadership-team.html there's a set of links for every article (one per LT member).

**Comment by Sandra97** [comment]
Exclude rule has been applied to Leardership Team and Hornor Roll categories. 
If you see another cat. to exclude, please inform.
