### ISSUE TITLE
[jorg] No Authors Picture in Feed

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#890]
In News-Feed Authors-Picture is a joomla-Logo:
![bildschirmfoto 2017-03-16 um 15 15 53](https://cloud.githubusercontent.com/assets/8235763/24000457/92c9f1e0-0a5b-11e7-8db9-d5ed8424dd90.JPG)
In Report Authors-Picture is shown:
![bildschirmfoto 2017-03-16 um 15 16 04](https://cloud.githubusercontent.com/assets/8235763/24000488/a43b680a-0a5b-11e7-87fe-714b530dd741.JPG)

**Comment by mbabker** [comment]
This is a user option in the volunteer portal.  As it requires the user exposing their email in the RSS feed which is used to fetch their avatar from Gravatar.  FWIW, the avatars go away on the redesigned homepage.

![screen shot 2017-03-16 at 9 18 44 am](https://cloud.githubusercontent.com/assets/368545/24000574/957b6cde-0a29-11e7-88cd-b81111c63828.png)

**Comment by franz-wohlkoenig** [comment]
thanks for Info @mbabker

**Comment by sanderpotjer** [comment]
And for volunteers that don't have the option set to allowed do see a notice when posting a report.
