### ISSUE TITLE
[jorg] Broken Link in "The next version of Joomla! is just around the corner"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#891]
at the End of Article https://www.joomla.org/announcements/release-news/5699-the-next-version-of-joomla-is-just-around-the-corner.html is:

> Share the news!
We have a wide range of teaser imagery available for sharing, which can be found here, as well as a teaser video **here**.

The Link for "here" is broken.

**Comment by AlexRed** [comment]
I can confirm the problem

**Comment by Joomv** [comment]
This has been fixed

**Comment by franz-wohlkoenig** [comment]
thanks @Joomv
