### ISSUE TITLE
[joomla.org] Feed not found.

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-websites#893]
HI 

on Joomla front page the Feeds is missing here:

This is what missing:

Volunteer Reports
Feed not found.

Leadership Blog
Feed not found.

Community News
Feed not found

This have happened 2 times now so better check up whats the error cause..

Cheers!

**Comment by ssnobben** [comment]
Hmmm after a cache refresh I got it to work som it seems to be something from old cache issues then..

So close this if it work for others..

**Comment by franz-wohlkoenig** [comment]
Known Issue #889

**Comment by Sandra97** [comment]
Closing this issue as it's a duplicate
