### ISSUE TITLE
A ban has been issued on your IP address[jcomm] 

### ISSUE THREAD

**Issue by chavab1** [joomla/joomla-websites#895]
I'm new to Joomla! and I'm trying to register for the developer forums. I've tried a couple of times to register with my work email address but I keep on getting denied with the reason being that my email address in the Spam database. I assure you that I am not a spammer. I work for a non-profit national organizations. Our organizations has several Joomla! sites that I now must maintain. I tried looking for a contact email address but I couldn't find anything; This was the only place where I could submit my problem.

My work email address is sbernal@ncjfcj.org. Any help would be appreciated.

Thanx

**Comment by MATsxm** [comment]
@ooffick ? - thanks

**Comment by ooffick** [comment]
Hi, 

Would you mind filling out the following form :

https://community.joomla.org/helpdesk/forum-un-ban-request.html

Thanks. 

Kind regards 
Olaf

**Comment by Sandra97** [comment]
@chavab1 Could you tell me if your issue is fixed? If yes, I'll close this issue.
Thank you!

**Comment by chavab1** [comment]
@Sandra97 Yes, @ooffick emailed me after I submitted the form to inform me of the problem and how it was fixed. I was then able to successfully register afterward.

Thank you very much to both of you for your help.

**Comment by disislyf** [comment]
oik?
