### ISSUE TITLE
[jdocs] SSL-Docs

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#896]
What are SSL Docs - visible in the search results. Seems to be the same as Documentation but the number of results is different so there must be a hidden difference

<img width="372" alt="screenshotr23-00-09" src="https://cloud.githubusercontent.com/assets/1296369/24125535/0ed4d882-0dc1-11e7-8f20-0076830420c3.png">

**Comment by Hutchy68** [comment]
SSL - Docs was a way to force CSE and then track population the links when we went from http to https only. Any differences could be from filtering. I removed it and made other tweaks.

**Comment by brianteeman** [comment]
Closing
