### ISSUE TITLE
[jdev] Roadmap/Project Dashboard

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#897]
Replace https://docs.joomla.org/Joomla_CMS_Development_Roadmap and https://developer.joomla.org/cms/roadmap.html with a single canonical roadmap source.

This should become a dashboard type system that can be used to indicate items in different phases (planning, development, testing, etc.), show team(s) working on items, have some sort of loose timeline mapping releases to dates, show the release lead and their support team (if one is present), and whatever else we need to effectively communicate development plans.

As a step one this should focus on the CMS.  For step 2, this should expand to include the Framework.

Details can be worked out about the implementation (put it all on the docs site, put it all on the dev site, use com_content as is the case now, build a custom component, whatever) by the team/individual(s) (hopefully not just me) working on this.

**Comment by nibra** [comment]
Would be a perfect home for the RfCs (currently working on a procedure proposal).

**Comment by Sandra97** [comment]
Temporary page for updating the roadmap:
https://docs.joomla.org/User:Sandra97/roadmap

Anyone is invited to edit, update this page and help providing clear information. 
It's currently just a draft. 
When ready, the content will be merged on JDocs or Dev, and this page will be deleted.

**Comment by mbabker** [comment]
I've gone through Sandra's page and given it some structure, basically the very high level things I think we should be communicating at a minimum (doesn't necessarily need to be this verbose or repeated in some cases, but hopefully the general idea is conveyed).  We can worry about looks and content next; looks is going to be dependent on our Bootstrap template versus the one in use on the wiki and the content is basically derived from the existing pages and just linking to the CMS' GitHub repo.

An area I want to try and highlight a little more in here is the "in development" area I've got in the 4.0 release.  This would be the spot where we have teams actively working on projects (Media Manager, the J4 UI folks, etc.) and that makes reference to a working space (either a GitHub repo or Volunteers Portal) so someone could pick up on a project's state and be able to jump in or at least follow along with its effort.  Once the RfC stuff is sorted out we would add two additional sections (feature proposals and accepted proposals which haven't started work yet) for that content.

**Comment by mbabker** [comment]
New page published.  We can work on it in iteration for continual improvements.
