### ISSUE TITLE
[jforum] Log issue

### ISSUE THREAD

**Issue by Warolf** [joomla/joomla-websites#899]
Hi,

I have a account in the https://forum.joomla.org/ but when i try to login ou rest it say that it does not exist but if i create whit the same user and e-mail it say that the account exist.

**Comment by MATsxm** [comment]
@ooffick ? - thanks

**Comment by ooffick** [comment]
Hi Warolf,

Would you mind submitting the following form:
https://community.joomla.org/helpdesk/forum-un-ban-request.html

I say you have to choose a different username as the one you have chosen already exists, but I can give you more feedback once I know your username, email address and IP address. So your best option is to fill out the form.

Kind Regards
Olaf

**Comment by MATsxm** [comment]
thanks... I will add this then to my auto-responder ;)

**Comment by MATsxm** [comment]
closing - reopen if needed
