### ISSUE TITLE
[jorg] Banner on home page

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#9]
Banner on the home page should switch to a responsive version or not display on mobile. Preference is to not show to focus on UX

![home page banner](http://s22.postimg.org/mbmny0vg1/IMG_0860.jpg)

**Comment by MAT978** [comment]
Closing as it should be solved on [jrepo] - Thanks
Thank you to reopen if needed
Note that @mikeveeckmans is in charge of the JWC banners
