### ISSUE TITLE
[jrepo] benefit of the fan art page?

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-websites#90]
I know we are not in charge of the content but are we really sure about this?http://repository.joomla.org/joomla-fan-art.html

**Comment by MAT978** [comment]
without answer until next Sunday, the page will be unpublished.
Thanks

**Comment by Radek-Suski** [comment]
Well with the only one example it doesn't make much sense

**Comment by Sandra97** [comment]
+1

**Comment by mikeveeckmans** [comment]
unpublish +1 , link towards Pinterest account

**Comment by Hutchy68** [comment]
+1000

On Sun, Aug 30, 2015 at 4:00 PM, Mike Veeckmans <notifications@github.com>
wrote:

> unpublish +1 , link towards Pinterest account
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/90#issuecomment-136178858>
> .
>



-- 
----
Tom Hutchison

**Comment by Sandra97** [comment]
As I don't think we'll have somebody who will wants to keep it, no need to wait one week to unpublish it. So, it's now unpublished. 
Issue closed.
Thanks. 
Re-open if needed.
