### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by CreateWebNZ** [joomla/joomla-websites#900]
On the page: https://docs.joomla.org/Supporting_plugins_in_your_component the link:  https://api.joomla.org/Joomla-Platform/Plugin/JPlugin.html in the paragraph "Joomla! Observer Implementation" is dead (404)

**Comment by Sandra97** [comment]
JDocs is a wiki, so feel free to edit the page and correct this dead link. 
Thank you!

**Comment by Hutchy68** [comment]
Fixed
