### ISSUE TITLE
[jdev] Issues with blog post images

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#904]
The image should be resized when displayed in two columns layout

![jdev](https://cloud.githubusercontent.com/assets/733133/24333250/e48e9ff2-1254-11e7-92c7-f7992b4eced1.PNG)

**Comment by Sandra97** [comment]
I can't reproduce. Clean your cache Luca, it should solved the issue

**Comment by jeckodevelopment** [comment]
Thanks
