### ISSUE TITLE
[jdown] Bottom ads not displayed anymore

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#906]
Hello!
The bottom ads is not displayed anymore on the homepage of the Downloads site.
@aDaneInSpain could you take a look at this please?

**Comment by mbabker** [comment]
It's still working.  Just "funny".

I've seen a bunch of "advertise here" ads the last week.  Just now on one of four requests I got an ad.

**Comment by Sandra97** [comment]
I noticed it on other properties too.
The ad is displayed sometimes for me too.

**Comment by Hutchy68** [comment]
because when ads display they have valid returning json

```
{"revive-0-0":{"html":"......."iframeFriendly":true}}
```

and when they don't it is because the json returning is invalid

```
_bsap.interpret_json({"zones":[{"id":....."a.adhere:hover{border:1px solid #999;background:#ddd;color:#333;}"]}]});

**Comment by aDaneInSpain** [comment]
The ads are served through BuySellAds. I will get them involved to figure out what is going on.

**Comment by chrsm** [comment]
Hi folks - Chris from BuySellAds here.

Can you paste the entire output you get when you see invalid JSON? Pastebin or a gist would work great.

I've disabled the "advertise here" ads for your site (it's a setting on each zone), so you should no longer see them in a few minutes.

Thanks,
Chris

**Comment by Hutchy68** [comment]
no ad resource link

https://srv.buysellads.com/ads/get/ids/CVAIKK7E/?r=1490713200000

```
bsa_CVAIKK7E("\u000D\u000A\x3Cstyle type=\"text/css\"\x3E\u000D\u000Adiv.bsap_1306680{width:100%;display:block;}div.bsap_1306680 a{width:728px;}div.bsap_1306680 a img{padding:0;}div.bsap_1306680 a em{font-style:normal;}div.bsap_1306680 a{display:block;font-size:11px;color:#888;font-family:verdana,sans-serif;margin:0;text-align:center;text-decoration:none;overflow:hidden;};float:left;}\u000Adiv.bsap_1306680 img{border:0;clear:right;}}\u000Adiv.bsap_1306680 a.adhere{color:#666;font-weight:bold;font-size:12px;border:1px solid #ccc;background:#e7e7e7;text-align:center;}}\u000Adiv.bsap_1306680 a.adhere:hover{border:1px solid #999;background:#ddd;color:#333;}\u000Adiv.bsap_1306680 iframe{display:block;font-size:11px;color:#888;font-family:verdana,sans-serif;margin:0;text-align:center;text-decoration:none;overflow:hidden;};float:left;}div.bsap_1306680 a{line-height:100%;}div.bsap_1306680 a.adhere{width:728px;height:90px;line-height:720%;}html\x3Ebody div.bsap_1306680 a.adhere{width:726px;height:88px;}div.bsap_1306680 img.s{height:0;width:0;}div.bsap_1306680{line-height:9px;}div.bsap_1306680 .bsap_adhere2,div.bsap_1306680 iframe{float:left;}div.bsap_1306680 .bsap_adhere2 a{height:90px;width:20px;background:url(http:\\/\\/s3.buysellads.com\\/ac\\/ah20x90_1.gif) no-repeat 0 0;text-indent:-9999px;}\u000D\u000A\x3C/style\x3E\u000D\u000A\x3C!-- no ad --\x3E\u000D\u000A\x3Cscript data-capture-write=\"false\" type=\"text/javascript\"\x3E if (typeof(BSACallback) !== \'undefined\') BSACallback(); \x3C/script\x3E");
```

**Comment by chrsm** [comment]
Thanks, Hutchy. Sometimes our system takes a bit longer to get things pushed - from the serving percentages, I can say that we should no longer be seeing "advertise here" banners.

If you do continue to see these, please let me know.

**Comment by Sandra97** [comment]
Ad is now correctly displayed since the last days.
Closing this issue.
Re-open if needed.
