### ISSUE TITLE
[jorg] 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-websites#909]
please update the release date for joomla 3.7 in "road to joomla 3.7"-document

https://www.joomla.org/announcements/release-news/5692-road-to-joomla-3-7.html

**Comment by Sandra97** [comment]
We don't edit already published article (except of course any typo or broken link). It was the scheduled release date when the article has been published last November. 
Even if the dates are not valid anymore, I don't think it's a good idea to apply changes in published articles.

**Comment by dneukirchen** [comment]
Perhaps a small update below the text (with a link to the Statement about the router) would be good in this case. We dont have to change the text. 

I agree with sandra, but this is an important information for many users and companies and we should keep them up2date.

```
Update 23.03.2017: 
Because of the time we have spent on the router we will delay the 3.7 release, details will be published soon. More information: https://developer.joomla.org/news/674-statement-about-the-new-router-feature-for-3-7-0.html
```

**Comment by mbabker** [comment]
It does not need an update banner.  It should have been published with our standard notice about release dates being subject to change.  Add that to the text and it is fine.  Otherwise we find ourselves editing every date on every blog post every time something slips.

> The schedule for upcoming releases is subject to change depending on the availability of volunteers, stability of the code, and circumstances beyond our control.

**Comment by laoneo** [comment]
IMO it is absolutely valid to add update notices for old posts as long as it is clearly marked. It doesn't mean we always have to scan all posts, but when we get a hint from some community members, we should listen to them.

**Comment by brianteeman** [comment]
Not as if Joomla doesnt have the functionality to display a modified date on the article by default ;)

**Comment by mbabker** [comment]
It is supposed to always be said in these types of posts that the timelines are not final.  That simple statement (quoted above) eliminates the need for someone to go back in and add update notices to old posts.  Otherwise we basically need to have a full time content manager for the websites.

If we'd do the job right the first time we wouldn't be having this discussion at all.

**Comment by ot2sen** [comment]
Wouldn´t take much effort to post a brand new blog item with revised
schedule. Then people know and all are happy.
Better than a 50 arguments pro/con thread here :)

**Comment by mbabker** [comment]
Part of what we're doing with https://github.com/joomla/joomla-websites/issues/897 (which should have the first version published over the weekend) is making the roadmap page the canonical source for this type of information.  So even if a blog post with static dates does get out of sync, at that point all that would need to be said is "note, this schedule is subject to change, see the project roadmap for the most up-to-date schedule".

![screen shot 2017-03-29 at 9 04 57 am](https://cloud.githubusercontent.com/assets/368545/24458547/db6e86ba-145e-11e7-9486-71b2fe023e8c.png)

**Comment by ahz66** [comment]
Michael, just try:

https://www.google.de/search?q=joomla+3.7+release+date&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=u7_bWJPNEYzb8Aeqy4GYDg

**Comment by mbabker** [comment]
I've never seen Google do that kind of rich snippet before.  Even if the article were edited, that doesn't necessarily mean the snippet gets updated in a timely manner, or that the first result has something useful.

Out of curiosity, your -1 reaction on my last comment is for?

**Comment by ahz66** [comment]
my reaction is my opinion. if i use google to find out more about the release date of joomla! 3.7 -> i get the document, mentioned in the initial post. i will not search for articles and posts on other websites/blogs/whatever.

If you think: having wrong statements on the official website is the right way... go ahead with it, but dont expect supoort from people like me.

**Comment by mbabker** [comment]
I'm not saying we should have wrong statements.  I'm saying that the blog post is a reflection of the plan as of the time it was published and that there should be a note saying "it may change" included in any post that has a timeline.  We don't have the resources to go into every post that has a timeline for every release and change it so it always lines up with whatever is happening in real time, whether that post is 4 weeks or 4 months old.

I'm also saying that we should have a single canonical resource that is always current (like how https://www.google.com/search?q=drupal+8.3+release+date&oq=drupa&aqs=chrome.1.69i60j69i59j69i60l2j69i59j69i57.1423j0j7&sourceid=chrome&ie=UTF-8 points to a release cycle overview page, not a "teaser" blog post).  So with our new roadmap page pushed live, in theory that should be the page that ranks first when it comes to searching "joomla x.y release date" and hopefully gives the same rich snippet.

**Comment by mbabker** [comment]
The blog post is a reflection of how things were at the time it was published.  Things have changed.  Those changes should be reflected somewhere.  Preferably, in a living resource that contains the most up-to-date information.  We don't have that type of resource right now, we will this weekend.

I personally am not a fan of revising static texts after they're published.  If that page were the master resource on all things 3.7, then yes it would be updated and it would be more geared toward providing 3.7 resources than it currently is (right now it is nothing more than a marketing teaser).

All I'm saying is I don't think it's appropriate to revise all published blog posts (which are static by nature) every time a timeline shifts.  I do think it is appropriate to have a disclaimer in any post that includes a timeline noting that things can and probably will change and providing a link to the resource that will ALWAYS contain current information.

**Comment by dneukirchen** [comment]
Lets just add a 1-liner and everyone is happy (like a suggested ~100.000 words above).

That does not mean that anybody needs to update or scan older posts for the rest of his life and its not worth the bytes (and time) we spent here...

**Comment by franz-wohlkoenig** [comment]
@mbabker 's solution start next Weekend, in the Meantime take @dneukirchen 's 1liner.

**Comment by dneukirchen** [comment]
[![Asterix: Public Services spoof (Obtaining Permit)](https://img.youtube.com/vi/TM9xZSJO4is/0.jpg)](https://www.youtube.com/watch?v=TM9xZSJO4is)

**Comment by Sandra97** [comment]
As I added a link to the dev roadmap in this blogpost and as it's mentioned that the `schedule [..], as always this depends on availability of volunteers and the support of the community [..]`, I'm closing this issue.
