### ISSUE TITLE
[jvel] please change EVERYTHING!

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#91]
It's impossible to fairly list all the issues.
Even the name is incorecte.
At this level and to save time, it would be better to rebuild it from scratch and take the opportunity to integrate the VEL site natively to .org. 
This would make the monitoring and management so easier and effective.
Thanks

**Comment by mandville** [comment]
please take the time to list the issues you have or feel free to send them to the vel team, or use the ask vel form.

**Comment by MAT978** [comment]
Just check the site please...
correct what is more than obvious, and then it will be possible to start working the way it should be.

**Comment by mandville** [comment]
The title is as stated by OSM Trademark Team. 
The rest of your response provides no clue as to how you think the site should work.

**Comment by MAT978** [comment]
1-Impossible or it would be so much worse than just an incorrect use, but for having worked so many times with Duke about the topic... I can't believe it a second!
2-What didn't you understand in 'Everything'?
"At this level and to save time, it would be better to rebuild it from scratch and take the opportunity to integrate the VEL site natively to .org."

**Comment by mbabker** [comment]
Just in a few minutes, here is my hitlist:

- Template is not using latest version (evidenced by template.css not being pulled from CDN, mega menu using CDN'd resource, and the Google font having a hardcoded `http://` prefix)
- Is there a more efficient way to show whatever information is in the `<marquee>` element?  That does not seem like the best way of communicating news or relevant content to me.
- HTML structures are... Interesting...

```html
<h2>
    <span id="How_to_use_this_list" class="mw-headline">
        <strong>How to use this site</strong>
    </span>
</h2>
```

- Capital "S" for the "search" menu item is preferred

**Comment by Sandra97** [comment]
Call me when you reach the question of having a clean and relevant  UX/UI. A bit (hmm hmm) work to do http://vel.joomla.org/articles

**Comment by btoplak** [comment]
@MAT978  Thanks for the suggestions and the remarks about indicia signs, @mandville can clear that with OSM. We can't just change everything, but we are working on several frontend and backend improvements, but also on VEL API. VEL site is almost 2 years old and some aging shows...

@mbabker the suggestions are valid. 
HTML isn't perfect on some places, but as of your code snippet, it's technically valid ;) ... unfortunately, that can't be said for many other Jooma (sub)domains, where validator screams

@Sandra97 be free to post all your UX/UI suggestions

**Comment by brianteeman** [comment]
The module on the left and right has a problem with the down arrow appearing above the text
![n oy](https://cloud.githubusercontent.com/assets/1296369/9591233/f1b4d93a-5031-11e5-9ae1-53913fb15b69.png)

**Comment by jessicadunbar** [comment]
Hi The UX team is really enthusiastic help out in this area. Some of them are new to the project and GitHub.

**Comment by pbwebdev** [comment]
I was going to rip apart some accessibility things but that scrolling marquee is actually considered accessible!

**Comment by brianteeman** [comment]
Is it? I was always taught the opposite

https://www.webaccessibility.com/best_practices.php?best_practice_id=441
http://webaim.org/techniques/textlayout/
http://webaccessibility.cita.illinois.edu/rule/91/
http://www.washington.edu/accessibility/checklist/dynamic-content/
http://www.webbie.org.uk/Veli-Pekka/web_access.html

On 1 September 2015 at 10:15, Peter Bui <notifications@github.com> wrote:

> I was going to rip apart some accessibility things but that scrolling
> marquee is actually considered accessible!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/91#issuecomment-136645384>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by btoplak** [comment]
@jessicadunbar how can we move forward with UX team to work on improvements on VEL team?

**Comment by MATsxm** [comment]
still incorect use of the TM indica
see above!

**Comment by MATsxm** [comment]
Closing this one as too general.
Please see #280 that is still waiting for action after more than 6 months.
Reopen  if needed
Thanks
