### ISSUE TITLE
old joomlacode links are broken

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#910]
The links in the 
Joomla 1.5 > File Upload Security Patch
are pointing to joomlacode (broken)

https://docs.joomla.org/Security_hotfixes_for_Joomla_EOL_versions

I would have used the wiki to update or correct them, but I am not sure where the links should be pointing and if the security patch in question is still needed (I am guessing yes) or available.

**Comment by zero-24** [comment]
What about linking to: https://github.com/PhilETaylor/Joomla1.5.999/commit/0f795894aa10e78a430a83591ed4a1b3f1df677c and
https://github.com/PhilETaylor/Joomla1.5.999/commit/8328ddb5068d951d21e8d5449167a36dcf40c5fd

?

**Comment by mbabker** [comment]
The wiki can point to that, we aren't issuing official releases.

See https://github.com/joomla/joomla-websites/issues/892 for the broken links thing.  That server is such a hunk of crap it's pretty much impossible to do anything with it in the Apache config for some reason.  Sad face.

**Comment by Hutchy68** [comment]
Beyond JDocs control, noted link is dead on page. Repost for site where link is dead, i.e. Joomlacode.  Besides it's Monday and I am sure @mbabker needs a laugh. Closing.
