### ISSUE TITLE
[jdocs] Bug_Tracking_Process isn't uptodate

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#912]
For Example: 

- Article talks about "Open", "Open/New"-Status, shown in Tracker-Dropdown is "New".
- "Change status to Unable to confirm", Dropdown shows "Unconfirmed Report"

**Comment by Sandra97** [comment]
Hi Franz,
You didn't mention which page ;)
Anyway, if you see anything which needs to be updated, feel free to make the changes yourself. It's a wiki, everybody can apply changes/update.
Thanks!

**Comment by franz-wohlkoenig** [comment]
its the "Bug_Tracking_Process"-Article, now i can do it by myself – haven't noticed about wiki.
