### ISSUE TITLE
[jcertif] JLP Form expected to be offline?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#913]
https://certification.joomla.org/jlp/jlp-application-form

Maybe we want to add a message "this form is offline for reason xxx" or bring it back online ;)

**Comment by zero-24** [comment]
![image](https://cloud.githubusercontent.com/assets/2596554/24648466/fe72d9e4-1923-11e7-8ae7-3ec94d114d57.png)

**Comment by franz-wohlkoenig** [comment]
works now.

**Comment by zero-24** [comment]
still offline for me?

**Comment by sam-suresh** [comment]
working fine in my end too. 
can you try in different browser?

**Comment by Sandra97** [comment]
Works fine for me

**Comment by zero-24** [comment]
same result in chrome incocnito mode and IE. But if it is just an issue on my end I'm fine :)

**Comment by jeckodevelopment** [comment]
Will look into it :) thanks
