### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by Henrieta23** [joomla/joomla-websites#915]
.

**Comment by Sandra97** [comment]
@Henrieta23 Ghost issue? ;)
Please describe your issue or I won't have any other choice than closing it
Thank you

**Comment by Henrieta23** [comment]
>
> Hy,
> Can you tell me why this webpage (http://www.sportmixta.hr/) stopped
> working? I have an idea - maybe because of incompatible plugin, but can you
> tell me how can I repair it? Is there any chance that it is lost forever?
>
> Thank you a lot :)




Lp,

Henrieta

2017-04-05 22:46 GMT+02:00 Sandra Decoux <notifications@github.com>:

**Comment by franz-wohlkoenig** [comment]
@Henrieta23  Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites.
