### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by jraff1** [joomla/joomla-websites#916]
In the Joomla Forum - How does one ask a question of the group?
I can find NO way to ask a question.
When I attempt to search for information about "creating a menu"
I get ridiculous comments of search too common!
I need to create a menu and Joomla will not let me with some comment about picking
"Please first make a selection from the list." - What selection from what list?!?!?!?!
------------------
Another issue, your login and password change form one page to the next, VERY CONFUSING?!?!?!

**Comment by jraff1** [comment]
How does one exit the comment system!?!?!?

**Comment by hvdmeer** [comment]
This repository is for only used for problems with the joomla.org websites. Regaring your problem, try reading this: https://docs.joomla.org/J3.x:Adding_a_new_menu
Again, your questions should be asked in forum.joomla.org, good luck.

@franz-wohlkoenig or anyone else, can you close this issue?

**Comment by franz-wohlkoenig** [comment]
anyone else, have Rights for /tracker/joomla-cms
