### ISSUE TITLE
Joomla Docs - duplicate page Retrieving request data using JInput deleted

### ISSUE THREAD

**Issue by JorgeGama** [joomla/joomla-websites#917]
I don't know if this is an issue or not, but when I try to visit https://docs.joomla.org/Retrieving_request_data_using_JInput the page has been deleted.

> This page has been deleted. The deletion and move log for the page are provided below for reference. 12:58, 27 February 2017 JoomlaWikiBot (Talk | contribs) deleted page Retrieving request data using JInput (duplicate)

The problem is that I am unable to find the "original" page and using the provided link to search for the page title gives no relevant results. I have noticed that a few more pages have "disappeared" as well.

My question, where can I find this page?

**Comment by Hutchy68** [comment]
Restored.

**Comment by JorgeGama** [comment]
Thank you.
