### ISSUE TITLE
forum down and cdn?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#918]
10:33 UK Time
### Forum
This site can’t be reached

The web page at https://forum.joomla.org/ might be temporarily down or it may have moved permanently to a new web address.

**Comment by brianteeman** [comment]
All other sites are missing the footer - I see the following message
Could not load template section.

**Comment by Sandra97** [comment]
We are facing some CDN issues, all our properties are impacted

**Comment by brianteeman** [comment]
ok - good to know you are on it. Its not so obvious on the non forum properties as they load

**Comment by aDaneInSpain** [comment]
Was this closed because it was resolved or because people are looking at it? The issue is still there (or back?)

**Comment by MATsxm** [comment]
reopen as still in progress

**Comment by Sandra97** [comment]
FYI we just tweeted this: https://twitter.com/joomla/status/850309547650682884

**Comment by Joomv** [comment]
Both are back up - both were separate issues.
I am monitoring to ensure they stay that way.

**Comment by MATsxm** [comment]
Merci @Joomv

**Comment by brianteeman** [comment]
@aDaneInSpain I closed it as it was stated that it was known and was being dealt with.

**Comment by brianteeman** [comment]
@joomv Right now the forum is faling to render correctly due to a 403 on https://cdn.joomla.org/template/css/v3_template.min.css?v1.3.3

 Failed to load resource: the server responded with a status of 403 ()

**Comment by Joomv** [comment]
Sorry for delay stepped out for a couple of hours.  
Showing fine now here. 
Back to monitoring.

**Comment by MATsxm** [comment]
thanks - closing 
reopen if needed
