### ISSUE TITLE
[navigation - joomla.org] 'Could not load template section.'

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-websites#919]
cdn.joomla.org is down?

![jorg1](https://cloud.githubusercontent.com/assets/2803503/24798038/e2929826-1b8b-11e7-85af-fb6627cff6f9.png)

> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by MATsxm** [comment]
duplicate with #918
