### ISSUE TITLE
[jvel] rss issues

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-websites#92]
rss feed not resolving http://feeds.joomla.org/JoomlaSecurityVulnerableExtensions

**Comment by btoplak** [comment]
just to be clear, VEL team can't fix that, another joomla team manages Feeds subdomain, marketing team?

**Comment by Radek-Suski** [comment]
> rss feed not resolving http://feeds.joomla.org/JoomlaSecurityVulnerableExtensions

How do you mean that? I can see all news

**Comment by btoplak** [comment]
I see "failedloginattempts v1.0.1 Posted:Sun, 07 Dec 2014 17:12:55 +0000" as the newest post.
That should be the source http://vel.joomla.org/live-vel

**Comment by Radek-Suski** [comment]
Not sure what the issue was. I just changed source from RSS to Atom and it seems to work now. 
Please watch the feed, especially when you publish new article and let me know if it worked for you.

**Comment by btoplak** [comment]
Looks good now, thanks for the fast fix. We'll let you know if anything breaks again

**Comment by MAT978** [comment]
Closed as fixed - Thanks
Reopen if needed

**Comment by btoplak** [comment]
Feedburner is having some random.old-post-email-resend episodes. 
And VEL team gets accused for it ;) https://twitter.com/blueflameit/status/644860192065253376
Anyone with Feedburner management rights have any idea about it ?
