### ISSUE TITLE
Ramdom order for Articles

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-websites#920]
When you create a menu item for Category Blog, in the Tab Blog layout, in Article Order,  it's possible to choose Random order, ok, but when you create a menu item for Featured articles, in the Tab Blog layout, in Article Order, NOT is possible to choose Random order.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
