### ISSUE TITLE
[jexam] Pagination 

### ISSUE THREAD

**Issue by Joomill** [joomla/joomla-websites#922]
When i view the CERTIFIED USERS DIRECTORY and select Country "The Netherlands" 
I see 26 users.
The first page is 20 users, but when i go to page 2 the country filter is gone and i can't see the next 6 people.

**Comment by MATsxm** [comment]
@sam-suresh if you can't help, thank you to tell me who I should ping fro it?

**Comment by sam-suresh** [comment]
@MATsxm Do mind we all not living in same timezone. 😀.
I will look into it and update here.

**Comment by sam-suresh** [comment]
@Joomill Thanks for reporting. This is now fixed.

**Comment by MATsxm** [comment]
merci @sam-suresh

**Comment by sam-suresh** [comment]
No mention @MATsxm!
