### ISSUE TITLE
[jdocs] 

### ISSUE THREAD

**Issue by simarock** [joomla/joomla-websites#923]
New menu items i created dont show up in frontend. 
 I've tried fixing database, updating all the extensions possible, clearing cache, updating php from 5.3 to 5.6, updating Joomla version from 3.3. to 3.6.5, backing up any php file i ever touched, backing up "mod_menu" and "com_menus" folders. 
Any ideas?

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
