### ISSUE TITLE
[jrd] 

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-websites#924]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

I'm trying to update my business profile in the JRD. First I tried to edit my personal profile, then I tried to edit my listing. Saving either one always hangs the site and it never saves. Can someone test this and see if it's just me or if there's something wrong with the site that's making it fail on save?

**Comment by brianpeat** [comment]
ARGH, It looks like this might just be a Safari issue. It worked fine in Chrome just now. I want to love Safari, I really do, but it continues to fail me.

**Comment by genr8r** [comment]
Hi @brianpeat. I am sorry that I did not address your concern sooner. I just tested the process you outlined above in Safari and do not get the same behavior that you described. Perhaps a recent update in Safari addressed the concern??? Do you mind testing again in Safari on your end and letting me know if it is still a problem?
Thanks.

**Comment by brianpeat** [comment]
I haven't had a chance, but I'd still close this. Safari, especially in the beta of the OS, sometimes just fails until you restart it. I just forget that it has issues, so I hit a snag and freak out and then finally realize I need to just try Chrome instead. I doubt it's an issue with the site at all, it's completely a Safari thing and it comes and goes (and could be just an issue with the beta OS I'm running).

**Comment by genr8r** [comment]
Hey @brianpeat thanks for looping back on this.  I appreciate the extra info.
