### ISSUE TITLE
[jcomm] Different "Upcoming Events" on different Sites

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#926]
#### On [community.joomla.org](https://community.joomla.org):
![community joomla org](https://cloud.githubusercontent.com/assets/8235763/25311165/0ad8b3ae-27fa-11e7-8352-c63758cef335.JPG)
No chronical order, not up to Date (Norway):

- Italy: 14 October
- Russia: 17 June
- Norway: 21 April
- NY: 23 April
- Poland: 23 September
#### On [joomla.org](https://joomla.org)
Wrong Header "April/May" where only JoomlaDays in May are shown:

![joomla org](https://cloud.githubusercontent.com/assets/8235763/25311253/15c2f94e-27fc-11e7-8cd5-2c8d97c291b7.JPG)
#### On [community.joomla.org/events](https://community.joomla.org/events)
All works fine:
![community joomla org events](https://cloud.githubusercontent.com/assets/8235763/25311257/3f309782-27fc-11e7-8d78-16cba09198af.JPG)

**Comment by Sandra97** [comment]
For jorg, I removed yesterday JD Norway which was on April 21st and forgot to remove 'April' in the title. It's done now.
