### ISSUE TITLE
[jconf] Update the JWC logo on Facebook

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-websites#927]
Like the title says: The logo should be  JJoomla! with the **!**
Thanks
![eee3b8b868665937657c4e324e48cb6f](https://cloud.githubusercontent.com/assets/1972717/25399199/97372772-29bc-11e7-8007-a10e6d0f14e9.png)

**Comment by Sandra97** [comment]
Go to the beach and leave me alone!!!! ;)

**Comment by Sandra97** [comment]
Same for Twitter & Instagram

**Comment by Sandra97** [comment]
Ex-husband gonna be happy.
I added the bang to Joomla. 
Ok now on Facebook and Twitter. Will change it on Instagram when I have access. 
Closing this issue.
Re-open if needed.
