### ISSUE TITLE
John Klaphake

### ISSUE THREAD

**Issue by jklaphake** [joomla/joomla-websites#928]
I have tried to update Joomla! from version 3.6.5 to 3.7.0 and also a fresh install when that produced the same error. It appears the install or update does not complete properly.

![screenshot-devel souvenirfactoryshop co nz-2017-04-26-12-04-11](https://cloud.githubusercontent.com/assets/7573294/25412663/8ab08c52-2a78-11e7-9181-686885b62daf.jpg)

john@hyperlink.net.nz

Thanks
john

**Comment by Hutchy68** [comment]
Please post your question in forum.joomla.org. This issue tracker is for *.joomla.org websites only.
