### ISSUE TITLE
[jrepo] Component error on Technical Requirements page

### ISSUE THREAD

**Issue by JacquesR** [joomla/joomla-websites#93]
Error on Technical Requirements page
about-joomla/technical-requirements.html
Warning
Error loading component: , Component not found.

**Comment by Sandra97** [comment]
I don't see any error displayed on this page. 
Please check again and detail the error.

**Comment by JacquesR** [comment]
The Joomla Warning, quoted above, was showing at the top of that page.
It's not showing the warning any more, so the issue seems to be resolved.

**Comment by MAT978** [comment]
Closed - Thanks
please reopen if needed
