### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by redbeorg** [joomla/joomla-websites#931]
In Joomla 3.7 ->Extensions/modules
No longer added in search tools of modules, the filter does not appear: "Select Page"

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
