### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by christmaslyric** [joomla/joomla-websites#932]
I have a website goodnaturedohio.com that is in disrepair after I completed a Joomla update.  The site is hosted by Siteground who has tried to fix the problem but says I need to contact Joomla.  I really would like to speak to a person about this but cannot find a phone number.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like http://joomla.org.

**Comment by christmaslyric** [comment]
Is there a phone number for JOomla support?

**Comment by Sandra97** [comment]
No, there's no phone number. 
Please, post your question on the forum as mentioned by Franz. I'm closing this issue as not related with the Joomla! properties
