### ISSUE TITLE
[joomla.org] Serious security issue

### ISSUE THREAD

**Issue by mavrosxristoforos** [joomla/joomla-websites#933]
Just today, an issue arised with a Joomla 3.6.5 installation I have.

A user was seeing other connected users' details. Something went wrong with the session table (I suppose, because I checked and there were more records than I expected) and all of a sudden, this user was able to see and edit other user data, but only in specific pages.

It looked as if it went back and forth between this user's and another user's session.

Then I updated to Joomla 3.7.0 and another issue came up: Some menu items are "external URLs" which I use as text separators, due to some issues I had with iPads. Their external URL is just a hash (#), to work as a text separator, thus pointing to my home page.
When someone clicks on that link, they are taken back to the home page and the page looks as if they were logged-out, and a prompt to login is back there. If you click on it, nothing happens and you have to use a menu item to navigate back to the site, where you find out that you are still logged-in.

Now I cleared the session table, but when I login with one user, I cannot logout. Then, I cannot access all pages of my website, because I am redirected to login, but I see the logout page, because I am logged in.

When I manage to logout, I login with another user, and then again I get this back and forth to the other user that was connected some time ago.

It is completely unstable at this point and I have no idea what to do.

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like joomla.org.

**Comment by mavrosxristoforos** [comment]
I apologize. I thought the link was to report an issue with the CMS.
