### ISSUE TITLE
Training not connecting to API

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-websites#934]
@stevejburge 
Please could you look at this urgently.
![joomla training provided by os training](https://cloud.githubusercontent.com/assets/5618499/25550160/d68ad22a-2c6e-11e7-8107-08a4eb7a10c1.png)
Thanks

**Comment by stevejburge** [comment]
Oh, yikes. Was this site update to Joomla 3.7?

Steve

**Comment by Joomv** [comment]
No not yet, was about to when I saw Jay's post.  
So this is unrelated to 3.7 could you take a look please?

**Comment by stevejburge** [comment]
OK, should be fixed now.

What was the problem? ... it broke because we upgraded our site to Joomla
3.7. With 3.7, Joomla has implemented a class method that's almost exactly
the same as what we're doing at OSTraining, but it was also incompatible.

**Comment by Joomv** [comment]
You star.
Thank you.
