### ISSUE TITLE
[joomla.org] Demo site

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#935]
On demo-site https://demo.joomla.org/ click "Launch Test Drive".

https://github.com/joomla/joomla-cms/issues/15672

**Comment by Sandra97** [comment]
Issue reported to SiteGround yesterday.

**Comment by Sandra97** [comment]
Issue solved by SiteGround.

I also asked them if they can:
- Update to PHP 7: on their todo list, they will keep me informed. They already removed the backend warning
- Multilingual Section:  links to joomlacode will be remplaced by the right cjo links before the end of the week and we will see together for the multilingual demo which is currently a 2.5 install.

**Comment by brianteeman** [comment]
PHP 7 upgrade still outstanding

**Comment by Sandra97** [comment]
PHP 7.0.20 for Demo. At least, it's PHP 7 ;)
Closing this issue.
Re-open if needed.
