### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by dkivogtland** [joomla/joomla-websites#936]
Hello,
after the update to version 3.7.0 I have the problem that articles with umlauts (ä/ö/ü) are no longer displayed. This seems to hang with the cache. The effect occurs only after 900 seconds. If you delete the Joomla cache, it goes again for 900 seconds. With the modules, the problem does not seem to exist

URL: https://www.die-kinderinsel.de/blog-die-kinderinsel/bücherflohmarkt
https://www.die-kinderinsel.de/spenden/buecher-spenden

Regards,
Mathias

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like joomla.org.

**Comment by franz-wohlkoenig** [comment]
theres a Thread also on github related to issue: [#15674](https://github.com/joomla/joomla-cms/issues/15674)

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
