### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by mathandcs** [joomla/joomla-websites#937]
I registered for a forum account but never received an email.  I have tried to have it resend the email to me but I have not received it.  I tried to click on the Board Administrator link but it say The board administrator contact page has been disabled.  Please let me know how I can otherwise activate my account.  thanks.

**Comment by Sandra97** [comment]
@ooffick Could you help with this? Thanks!

**Comment by ooffick** [comment]
Hi

Would you be able to fill out the following form:
https://community.joomla.org/helpdesk/forum-un-ban-request.html

Kind regards 
Olaf
