### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by JimGreiner** [joomla/joomla-websites#938]
Menu items from front end now appearing under "Components" in back end after upgrade to Joomla 3.7... these menu items also still appear in the front end where they are supposed to.... Need a patch to be able to remove menu items that should not be routed to back end menus and without requiring us to delete out rebuild our front end menus...

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
