### ISSUE TITLE
[jdev] Adapt Project Roadmap

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#939]
After Release of 3.7 [Roadmap](https://developer.joomla.org/roadmap.html) needs Update (3.7.1 coming or starting with 3.8).

**Comment by Sandra97** [comment]
We already applied some updates on April 25th
![1](https://cloud.githubusercontent.com/assets/4682328/25576401/aae0aed2-2e2c-11e7-9d9a-9e1526a67398.png)
![2](https://cloud.githubusercontent.com/assets/4682328/25576402/aae5d95c-2e2c-11e7-9752-fd7c3cc393e3.png)

**Comment by franz-wohlkoenig** [comment]
Meant delete not neccessary Informations like "Schedule", "Release Lead", ... so its clear whats next (3.7.1 or 3.8) and when.

**Comment by Sandra97** [comment]
We will do more updates on the page soon.

**Comment by franz-wohlkoenig** [comment]
thanks @Sandra97
