### ISSUE TITLE
[org] Anyone else thinking we have new partners because of sharing links?

### ISSUE THREAD

**Issue by Martijn-Boomsma** [joomla/joomla-websites#94]
http://repository.joomla.org/about-joomla/partners.html 

This looks like we have the sharing links as new partners. They look like call-to-actions, but I think not always relevant. 

http://repository.joomla.org/about-joomla/the-project/mission-vision-and-values.html
Same story, sharing lings in the top look weird to me, but maybe that's just me ;)

**Comment by brianteeman** [comment]
On the News page sometimes the sharing links (which are a MASSIVE improvement) are above the article image and sometimes below the article image

**Comment by Martijn-Boomsma** [comment]
I think under might be better here. Personally I think they are to demanding overall, compared to the content, but maybe that's something for a redesign phase 2.

**Comment by Sandra97** [comment]
You're right @Martijn-Boomsma , it's something for the phase 2.
@brianteeman, I saw that too. The display is different because the images in the news are not integrated all in the same way: some using the images tab some directly in the HTML view. It's a content issue so it's for phase 2.

**Comment by MATsxm** [comment]
Not displayed anymore.
Closing - reopen if needed
