### ISSUE TITLE
[jcomm] 

### ISSUE THREAD

**Issue by hoerby** [joomla/joomla-websites#943]
Tried to update my joomla to new release 3.7. from: administrator-component-update.
error: "The archive file is corrupt, truncated og archive parts are missing"

can anyone help
mogens H
hoerby2016@gmail.com

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla-Websites like joomla.org.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
