### ISSUE TITLE
[demo.joomla.org] Demo site: Help button

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-websites#944]
On demo-site https://demo.joomla.org/ click "Launch Test Drive", click "New article", click "Help" button on the right: blank popup

**Comment by Sandra97** [comment]
Just sent a message to SiteGround. I'll keep you informed.

**Comment by brianteeman** [comment]
It is all the help pages that are returning a white page.
If you look at the url it is using
`https://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help37:Content_Article_Manager_Edit`
and it should be

`https://help.joomla.org/proxy?keyref=Help37:Content_Article_Manager_Edit&lang=en
`
is there a redirect not happening ?

**Comment by zero-24** [comment]
It is working just change `&amp;` => `&` and we got the result.

**Comment by zero-24** [comment]
https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help37:Content_Article_Manager_Edit

**Comment by brianteeman** [comment]
so its not working on the demo site ;)

**Comment by Sandra97** [comment]
I'll send a reminder to SiteGround.

**Comment by brianteeman** [comment]
Still broken

**Comment by nikolayt** [comment]
Can you confirm this is not an issue within Joomla itself. The &amp; is added by htmlspecialchars:

http://php.net/manual/en/function.htmlspecialchars.php

        $url = htmlspecialchars($url, ENT_QUOTES);

**Comment by brianteeman** [comment]
Confirming that the help screens work perfectly on my site on siteground servers see movie (the wrong version number in the help is an unrelated bug)

![sg](https://cloud.githubusercontent.com/assets/1296369/26203446/391bfaea-3bd3-11e7-862d-432ae7466022.gif)

**Comment by nikolayt** [comment]
Thanks @brianteeman . Problem has been resolved.

**Comment by brianteeman** [comment]
I can confirm that this is now working correctly and the problem has been resolved

**Comment by Sandra97** [comment]
Thanks!
Closing this issue.
Re-open if needed.
