### ISSUE TITLE
[joomla.org] optimise images

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#945]
joomla.org should be a showcase of the best that joomla can be.

unfortunately the images are far too large. just look at the showcase images which are massively scaled down in html

https://pageweight.imgix.com/jobs/3a9b2d8d-3f98-4183-ba0e-23894af405ef/

**Comment by Sandra97** [comment]
Don't fully agree.
The header image is covering the width of the screen so having a image of 1280px width can result in an 'ugly' display on large screen.
And if showcase images are resized to 270px, then the display on screen under 767px will be pixellised.
The other solution would be to have different images regarding the size of the screen for the showcase part, resulting in making my life just a bit more miserable as I change them manually twice a month. 
But you may have a solution I didn't think about to solve this without making my life miserable ;)

**Comment by brianteeman** [comment]
1. the showcase images are never displayed at the full native size unless I am missing something
2. the modern way to resolve this woulld be to use srcset

**Comment by Sandra97** [comment]
1. The showcase images are displayed full width
![capture-d ecran-2017-05-07-05 46](https://cloud.githubusercontent.com/assets/4682328/25779537/cf7fbc86-32e8-11e7-992d-6d3f1443ff33.jpg)
2. I've never used it, but it's never too late to start ;)

**Comment by brianteeman** [comment]
ah I missed that one size ;)

there are a few plugins that will create the srcset immages - i think @dgt41 has one

**Comment by Sandra97** [comment]
Thanks Brian, I'll contact him.
