### ISSUE TITLE
[jcomm] Typical language file headers

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#946]
I was on the page listing the translations and saw a link that I didnt know - Typical language file headers

When I followed it I ended up here
https://community.joomla.org/translations/593-typical-language-file-headers.html

As you can see there is something not correct about it. Looks like some wiki markup?

**Comment by Joomv** [comment]
Sadly the translation team still haven't sorted out their section.
Will chase again

**Comment by Sandra97** [comment]
You're fulll of hope Rowan, not sure you'll ever get an answer...
Why about just killing this page as it's  "typical for 1.5.x files"?

**Comment by Joomv** [comment]
I've archived the article and removed the accordion.
Closing
