### ISSUE TITLE
[joomla.org] Joomla 3.7 and CACHE plugin problems

### ISSUE THREAD

**Issue by stavroszach** [joomla/joomla-websites#947]
Since the update to version 3.7, my own custom made "Contact Us" forms don't appear in any of my sites. Instead, completely blank pages appear <body></body> and nothing in between. Similarly my Phoca Guestbooks do present exactly the same problem.
The problem appears only when Joomla's CACHE plugin is enabled and the specific pages are set to be excluded. It goes away when either the CACHE is disabled or the pages are deleted from the CACHE's exclusion list.

**Comment by mbabker** [comment]
Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org.
