### ISSUE TITLE
Joomla Docs - JFactory/getEditor page deleted

### ISSUE THREAD

**Issue by JorgeGama** [joomla/joomla-websites#948]
The page https://docs.joomla.org/JFactory/getEditor has been deleted.

> This page has been deleted. The deletion and move log for the page are provided below for reference. 12:15, 27 February 2017 JoomlaWikiBot (Talk | contribs) deleted page JFactory/getEditor (duplicate)

Unfortunately, I am unable to find the original of the duplicate. Would it be possible to restore this page?

**Comment by zero-24** [comment]
This should do the trick: https://api.joomla.org/cms-3/classes/JEditor.html As JFactory::getEditor is deprecated anyway :)

**Comment by Sandra97** [comment]
We don't restore obsolete pages, and Tobias mentioned a link which should do the job.
Closing this issue.
Re-open if needed.
