### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by jesimon71** [joomla/joomla-websites#949]
I am the Board Chair of Kraft Tennis Partners.  I am not a techy, I'm a doc!  Our website, which I believe you host (Krafttennis.com) is operating EXTREMELY slowly.  The members of our club are screaming at me.  The volunteer who shepherds our website says that he has contacted Joomla but has not received any satisfaction.  Whoever is reading this please go to Krafttennis.com and note that there is a 2 minute delay between clicks.  Please help me resolve this problem.  Dr. Joe Simon

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by zero-24** [comment]
> which I believe you host (Krafttennis.com) is operating EXTREMELY slowly

Joomla itself do NOT host. Based on a whois it looks like your hoster is: lunarpages.com
