### ISSUE TITLE
[jrepo] Breadcrumb for announcements section?

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#95]
There's no intuitive navigation method for moving around pages in the announcements category.  No page navigation links nor is there any breadcrumb with the category tree.

**Comment by Sandra97** [comment]
Fully agree with you.

**Comment by MAT978** [comment]
agree...
and still thinking breadcrumb is a need!

**Comment by Sandra97** [comment]
Breadcrumb added for the news part. Some CSS adjustments are needed.

**Comment by MAT978** [comment]
Done with a bottom Breadcrumb - Thanks
Closed
Please reopen if needed.
