### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by kminor** [joomla/joomla-websites#950]
Please describe the problem #404 Category not found

 or your issue

**Comment by kminor** [comment]
sir/ madam,

kindly help re upload or sort the problem encountered on opening the west african college of surgeon surgery pass list for april 2017 membership examination. 
it kept showing this message "#404 Category not found "
thank you

**Comment by franz-wohlkoenig** [comment]
Please close this Issue and ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla Websites like https://www.joomla.org/.

**Comment by MATsxm** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
