### ISSUE TITLE
[jrd] URLs rewriting not activated

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#951]
Hello, 

@genr8r Is there any reason why SEF options are not activated on the site?
URLs look like this `https://resources.joomla.org/index.php?option=com_content&view=featured&Itemid=101&lang=en`

Thanks

**Comment by genr8r** [comment]
Hey @Sandra97 thanks for the heads up. We have been troubleshooting some caching issues on the site. Must have forgot to flip it back on.
