### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by davidcchapman** [joomla/joomla-websites#952]
After updating to Joomla! 3.7, we are seeing hundreds of thousands of messages in Apache's error_log of the form:

PHP Warning:  Illegal string offset 'relative' in /var/www/html/site/libraries/cms/html/html.php on line 620
PHP Warning:  Illegal string offset 'relative' in /var/www/html/site/libraries/cms/html/html.php on line 626
PHP Warning:  Illegal string offset 'detectBrowser' in /var/www/html/site/libraries/cms/html/html.php on line 626
PHP Warning:  Illegal string offset 'detectDebug' in /var/www/html/site/libraries/cms/html/html.php on line 626
PHP Warning:  Illegal string offset 'pathOnly' in /var/www/html/site/libraries/cms/html/html.php on line 629

Most of the offending lines are of the form

`$options['string'] = isset($options['string']) ? $options['string'] : boolean_value`

The intent seems to be "if the option string exists then use it, otherwise use a default value." It seems that it would be better to use

`array_key_exists('string',$options)`

before referencing the option value but I am not a Joomla! developer and am hesitant to make this change on our site.

**Comment by sam-suresh** [comment]
Please post your question at forum.joomla.org
This repo is to post issues related to joomla official websites not the software itself.
