### ISSUE TITLE
joomla.com 3.7

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#953]
on **some** of my sites on joomla.com the upgrade to 3.7 has not been completed successfully

<img width="639" alt="screenshotr09-28-56" src="https://cloud.githubusercontent.com/assets/1296369/26145142/487346d8-3ae3-11e7-93a9-23e8d069f92f.png">

**Comment by Sandra97** [comment]
I'll report it to SiteGround.

**Comment by kirilhristov** [comment]
This has been fixed now. Thanks!

**Comment by Sandra97** [comment]
Thanks Kiril!
Closing this issue.
Re-open if needed.
