### ISSUE TITLE
[jshop] Update Message "… before our next Joomla! release (3.7)"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#955]
At Joomla-Shop this Message is shown:
![bildschirmfoto 2017-05-17 um 18 53 38](https://cloud.githubusercontent.com/assets/8235763/26166087/aa64f0fe-3b32-11e7-861b-7fdf5302719d.JPG)
3.7 is out, so this Message needs an Update.

**Comment by Sandra97** [comment]
Message has been updated.
Closing this issue.
Re-open if needed.
