### ISSUE TITLE
[jcomm]  The Joomla! Shop Off 

### ISSUE THREAD

**Issue by medator** [joomla/joomla-websites#956]
The Joomla! Shop Off 

![adsiz](https://cloud.githubusercontent.com/assets/519104/26177881/3e06d134-3b64-11e7-90f6-3fccb49b2501.png)

The Joomla! Shop is offline for a bit while we re-tool everything before our next Joomla! release (3.7)

**Comment by franz-wohlkoenig** [comment]
Duplicate Report of #955. Please close Issue, thanks.
