### ISSUE TITLE
[jdocs] Update from 3.7.x to 3.7.1 Timeout

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-websites#957]
link: https://docs.joomla.org/J3.x:Update_from_3.7.x_to_3.7.1_Timeout
1. In How to fix package named names shoud be updatated and linked
2. https://github.com/joomla/joomla-cms/pull/11497 is closed so last sentece shoud be chenged or removed.

**Comment by MATsxm** [comment]
The JDoc is a wiki then thank you to edit/update directly the content that needs to be updated

**Comment by wojsmol** [comment]
@MATsxm I Cen't create account on JDoc. Additionaly this article is in Relase FAQ category wich can be protected.

**Comment by Sandra97** [comment]
I'm closing this issue. This page can be edited by anyone.
