### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by kpriyacdac** [joomla/joomla-websites#958]
I just moved my Joomla  website  from local  to server  and I get the following error, requesting Help in this

Warning: Attempt to modify property of non-object in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php on line 428

Warning: Attempt to modify property of non-object in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php on line 428

Warning: Attempt to modify property of non-object in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php on line 428

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php:428) in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/joomla/session/session.php on line 658

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php:428) in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/joomla/session/session.php on line 658

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php:428) in /homepages/22/d285911174/htdocs/clickandbuilds/plugins/system/languagefilter/languagefilter.php on line 121

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d285911174/htdocs/clickandbuilds/libraries/framework/Joomla/Registry/Registry.php:428) in /homepages/22/d285911174/htdocs/clickandbuilds/libraries/joomla/input/cookie.php on line 87

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
