### ISSUE TITLE
[jdev] PhpStorm Code Style Scheme missing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#960]
on this page

https://developer.joomla.org/coding-standards/analysis.html

There is a title of "PhpStorm Code Style Scheme" which is neither linked or has any description,

**Comment by mbabker** [comment]
No idea what the content is supposed to be, but anyone who has it can do a PR editing https://github.com/joomla/coding-standards/blob/master/manual/appendices/analysis.md

**Comment by zero-24** [comment]
see: https://github.com/joomla/coding-standards/pull/185

**Comment by zero-24** [comment]
Mabe we want close here as the PR is merged now?

**Comment by zero-24** [comment]
Thanks
