### ISSUE TITLE
[jdev] Missing content of examples page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#961]
https://developer.joomla.org/coding-standards/examples.html

This page is blank

**Comment by mbabker** [comment]
As weird as it sounds, that's correct.

The coding standards section is pulled from the manual folder on the coding-standards repo, and https://github.com/joomla/coding-standards/blob/master/manual/appendices/examples.md is empty.

**Comment by mbabker** [comment]
Put text on the page saying examples are welcome, the new component also has a "Edit on GitHub" link.  Closing, page is doing what it's intended, even if the content is lacking.
