### ISSUE TITLE
[jcertif] Learning Partners site broken

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#962]
Hello, for Certification Team, this link is broken : https://resources.joomla.org/en/joomla-learning-partners

![image](https://cloud.githubusercontent.com/assets/2596554/26503905/d50199fe-4242-11e7-920e-4a15f27684bc.png)

Reported by Eric Lamy in Glip.

**Comment by mbabker** [comment]
Known issue - https://github.com/joomla/joomla-websites/issues/877

**Comment by zero-24** [comment]
thanks just added another coment.
