### ISSUE TITLE
[jorg] How many languages? 68 or 74?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-websites#964]
In www.joomla.org says Joomla is available in 68 languages.

But in Joomla "Install Languages" says Joomla have 73 languages (not including en-GB) to install.

![image](https://cloud.githubusercontent.com/assets/9630530/26789667/eebedeec-4a08-11e7-87ab-b7a4c9a4c14c.png)

So in reallity seems Joomla is available in 74 languages (73 + en-GB).
If that's the case it needs to be updated in www.joomla.org (and other places probably).

**Comment by zero-24** [comment]
This may come from the fact that e.g. german has a few copy of that language for de-DE de-CH etc. I'm not sure if that counts as language.

**Comment by andrepereiradasilva** [comment]
If only counting the language itself, then as de-DE, de-LU, de-AT, de-CH, etc would be [German language](https://en.wikipedia.org/wiki/German_language) (de), pt-PT and pt-BR would be [Portuguese Language](https://en.wikipedia.org/wiki/Portuguese_language) (pt), as en-GB, en-US, en-AU, en-NZ, etc would be [English language](https://en.wikipedia.org/wiki/English_language) (en).

So if that logic would be followed it would be, i guess, a lot less than 68.

If, on the other hand, it's counting the code *language-COUNTRY* used by Joomla then it seems the number is 74.

But, probably there is some logic around that 68 number, that i don't know of.

**Comment by zero-24** [comment]
hmm the thing about german is that all packages are containing the same translation. The reason is you don't need to package the language your self if you need multi language.

I'm not sure for the other ones. IIRC en-GB != en-US. Similiar to the other ones.

**Comment by andrepereiradasilva** [comment]
yes of course they are different.
so de-* are exactly the same? didn't know that

**Comment by zero-24** [comment]
> so de-* are exactly the same? didn't know that

Yes.

**Comment by andrepereiradasilva** [comment]
ok the logic is the 5 de-* lang packs count as 1 language?

should be 70 them :smile_cat: . but i guess there are more cases like de-* in other languages

**Comment by zero-24** [comment]
> ok the logic is the 5 de-* lang packs count as 1 language?

Maybe. I have not come up with that count just with that kind of extra info ;)

For sure we can also count them as individual language. But this is not my decision ;)

**Comment by andrepereiradasilva** [comment]
yes, sure just raised this issue because saw the difference in number.

doesn't mean that is really an issue if this was decided this way.

If it's not an issue can be closed.

**Comment by Bakual** [comment]
I don't think there are other languages which are identical. THe german one is special here.
There website is likely off by the two or so languages we added recently.

**Comment by Sandra97** [comment]
Seems we have 76 Joomla 3.x Accredited Translations packs on joomlacode (even if some are still Beta). + en-GB
We can use this number. 
And don't forget that it's more marketing data than accurate ones in all this number section of jorg (we can't have accurate numbers for most of them).

**Comment by Sandra97** [comment]
I'm sorry, but I don't see any real interest in this discussion. 
Closing this issue.
Re-open if needed.
