### ISSUE TITLE
"My server cannot connect to update.joomla.org"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-websites#966]
Dear @mbabker et al.

This Joomla Users server cannot connect for updates 

I have uploaded a test script containing this code:

```php
<?php
ob_start();


error_reporting(E_ALL);
ini_set('display_errors', 1);

echo file_get_contents('https://update.joomla.org/core/list.xml');

echo file_get_contents('https://update.joomla.org/core/extensions/com_joomlaupdate.xml');

echo '<br/>';
echo 'My Server IP is: ' . $_SERVER['SERVER_ADDR'];


$contents = ob_get_contents();
ob_clean();
echo str_replace('/path/to/domain.com/','',$contents);


```

To his server here: https://winkelcentrumheinkenszand.nl/test-myjoomla.php

As you can see the error message is `Connection Refused`

You can see the servers IP address its coming from

Please can you check any firewall rules that might be blocking this customers IP address from accessing the update.joomla.org server. 

Thanks.

**Comment by mbabker** [comment]
Can someone who can submit tickets take this on please?  Until I get the hardware failures in my laptop addressed, my availability is going to be severely limited.

**Comment by Sandra97** [comment]
@Joomv Could you submit a ticket please?

**Comment by jpmdejonge** [comment]
Dear all, @Joomv ,

It is still not possible to make a connection to the update server. Is a ticket for this already created?
The IP address of our server is 79.170.88.108

**Comment by Joomv** [comment]
Rochen have come back saying nothing their end of this IP.  I have referred them to this thread for more information.  When I have more feedback I will let you know.

**Comment by jpmdejonge** [comment]
Seems that our FW is blocking outgoing to Joomla update servers.

**Comment by jpmdejonge** [comment]
Resolved, IP of Joomla update server was indeed blocked in CSF.
