### ISSUE TITLE
not possible to create categories

### ISSUE THREAD

**Issue by umuehlbo** [joomla/joomla-websites#968]
HEllo.
When I want to create a new category it's not possible to click save or save&leave.
Nothing happens.
Also the same for new posts.
thanks
Uwe

**Comment by Radek-Suski** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
