### ISSUE TITLE
[jcm] "Register Now!" not working

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-websites#970]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by Radek-Suski** [comment]
??

**Comment by pe7er** [comment]
There seems to be a problem with the JCM registration page: The "Register Now!" at https://magazine.joomla.org/authors redirects to https://magazine.joomla.org/login

Source: https://forum.joomla.org/viewtopic.php?f=573&t=951633
I was able to reproduce the issue.

**Comment by pe7er** [comment]
@Radek-Suski Sorry for the confusion. I pressed "Comment" too early :-)

**Comment by Radek-Suski** [comment]
Now it make sense 👍

**Comment by Sandra97** [comment]
True. You can login but you can't create an account.
@helvecio @JacquesR, could you please look at that?

**Comment by JacquesR** [comment]
Thanks @pe7er 
I'll have a look

**Comment by JacquesR** [comment]
OK, Author registration page text updated, and duplicate Author registration module unpublished. I'll post a comment in the forum thread.
(re-open if you still find an issue)
