### ISSUE TITLE
My Docs Language Plugin proposal for *joomla.org

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#971]
As previously discussed with @Sandra97 and @mbabker here is my plugin for the my Docs language thing.

https://github.com/zero-24/plg_content_mydocslanguage/releases/latest

This content plugin makes sure that all links to docs.joomla.org inlcude the `Special:MyLanguage` tag. We are currently using this on the offical german site maybe we can use it on the offical joomla sites too. This way the author don't need to take care about the internatiolisation part if he poste a docs page link. And this improves the visibility of the translated pages.

Thanks.

**Comment by mbabker** [comment]
I don't think we need to make it policy to use this, but it definitely seems like a good idea for the sites that are commonly referencing stuff in the docs wiki (so the main www site since we link there in every release announcement and probably the dev site since we do have a fair number of docs links there).

**Comment by zero-24** [comment]
Yes this was the intention ;)

**Comment by Sandra97** [comment]
@zero-24 
Installed on https://www.joomla.org/3 and it works fine.

But I have a question...
Why for German the URL is  `https://docs.joomla.org/Special:MyLanguage/J3.x:Adding_custom_fields/de`?
It should just be `https://docs.joomla.org/Special:MyLanguage/J3.x:Adding_custom_fields` (it works with `/de` at the end but it's not correct) 
(Note that the other languages I checked are ok, it happens only with German)

**Comment by zero-24** [comment]
hmm could it be that the link was already `https://docs.joomla.org/J3.x:Adding_custom_fields/de` before the plugin did run? The Plugin just adds the `Special:MyLanguage/` when not there. ;)

**Comment by Sandra97** [comment]
Let me check

**Comment by Sandra97** [comment]
You were right. It's ok now.
I'm gonna install it on org too.

**Comment by zero-24** [comment]
👍

**Comment by zero-24** [comment]
Closing as it is implemented now thanks ❤️
