### ISSUE TITLE
OSTraining - Invalid License Key

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-websites#972]
@stevejburge  Sorry to bother you again, but I can't update the Ostraining Component, it says invalid license key.  Could you please take a look?  Thanks

**Comment by andergmartins** [comment]
@Joomv Please, could you check what license key you are using? You can check on the OSMyLicensesManager plugin's settings. Please, could you send it to my email: anderson@ostraining.com. Thanks.

**Comment by Joomv** [comment]
Emailed it to you.
Thank you!
Rowan

**Comment by andergmartins** [comment]
Hi, thank you.
Please, could you try again? I double checked your license and everything looks ok now.
Cheers,

**Comment by Joomv** [comment]
Now the entire section is down with the following error message.
Fatal error: Call to undefined method Defuse\Crypto\Crypto::hexToBin() in /administrator/components/com_osteammatejoomla/library/osteammate/src/API/Client.php on line 206
I have replaced the component with an offline page in the meantime.
@andergmartins @stevejburge

**Comment by stevejburge** [comment]
Guys, with the greatest respect, this stuff keeps getting reported at about
8pm on Friday nights when everyone is gone for the weekend.

I'll see what I can do.

**Comment by stevejburge** [comment]
Guys, with the greatest respect, this stuff keeps getting reported at about 8pm on Friday night when everyone is gone for the weekend.

I'll see what I can do.

**Comment by Joomv** [comment]
Hi Steve,
I completely understand where you are coming from, but I only report it when I see it.  
Its 23:30 here and I just ended up with a cold dinner (first meal of my day too) so I really do understand where you are coming from.

**Comment by stevejburge** [comment]
Is there a link we can use to verify it’s working? (avoiding the offline page)

**Comment by Joomv** [comment]
https://community.joomla.org/train-test.html

**Comment by stevejburge** [comment]
Thanks

It looks like a update from a while back was applied today. Friday updates :-0

We're working on it

**Comment by billtomczak** [comment]
We've published a new release I'm hoping will correct the problem. Could you please update OSTeammateJoomla and let us know?

**Comment by Joomv** [comment]
HI @billtomczak  - sadly, doesn't appear to have fixed it.
We have an offline notice up, so there's a temporary solution in place.
Go enjoy your Friday night guys, we can pick this up in the morning or even Monday.
I really didn't mean to ruin your Friday, and am truly sorry for that.

**Comment by stevejburge** [comment]
Ok, sorry about that, Rowan

**Comment by andergmartins** [comment]
Hi @Joomv, sorry for the inconvenience.
I just released a new package addressing this issue.
Please, could you try updating? Let me know how it goes.

Looking forward to helping.

**Comment by Joomv** [comment]
@andergmartins  - We have a winner. Training is back and live! Thank you for your help!

**Comment by Sandra97** [comment]
And thank you Rowan for taking care of it!

**Comment by andergmartins** [comment]
@Joomv Cool! You're more than welcome.
