### ISSUE TITLE
[jhelp] Unable to see API Manager Configuration and Email Templates in Joomla Global Configuration (Administrator > System)

### ISSUE THREAD

**Issue by smangipudigithub** [joomla/joomla-websites#976]
[jhelp] Unable to see API Manager Configuration and Email Templates in Joomla Global Configuration (Administrator > System)

**Comment by smangipudigithub** [comment]
This is related to TIBCO API Exchange Manager - Developer Portal Configuration

**Comment by zero-24** [comment]
@smangipudigithub this sounds like a issue with the extension ? And had nothing to with the core help system?

**Comment by smangipudigithub** [comment]
Thank you.

Installed these extensions - pkg_cobalt.j3.everything.v.8.542_patch08.zip, pkg_cobalt.j3.media.v.8.78.zip 
They came as part of Cobalt extensions for TIBCO API Manager Portal Setup through Joomla.

**Comment by zero-24** [comment]
Great. Than please contact the developer of that extension. As I don't know that extension nor is this extension shipped with the core cms :)
