### ISSUE TITLE
[jorg] Press Inquiries/ Contact for Press and Media only - First option

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#977]
In the Press Inquiries page, the alternative "Looking to get in touch with the Media & Marketing team" to the users that follow the right path is the last one in the list.

The option "Looking to get in touch with the Media & Marketing team" should be the first one of the list.

The rest of the alternatives are defined to guide users who don't find what they are looking for.

A

**Comment by Sandra97** [comment]
You already know I agree with you ;) 
Let's wait for more feedback.

**Comment by MATsxm** [comment]
+1

**Comment by Joomv** [comment]
It completely defeats the purpose of the form.  The purpose of the form is to reduce the 1000's of spam messages that account gets and to direct those who are not spam but looking in the wrong place to the right place, you put that choice first and people will ignore all the other options and just send a message.
No point in changing it if that's all you're going to do, might as well just keep it as it is.

**Comment by MATsxm** [comment]
then just delete it....
this is just crazy

**Comment by Sandra97** [comment]
To reduce spams, just add a reCAPTCHA.
But AFAIK, many messages are requests from Joomla users, do we consider our users as spammers? ;)
No need to mention the answer for these users is ready, and translated in many languages. Answering a user is never a lack of time. Some users can be a bit lost and don't know where to find the information they are looking for, it doesn't require so much time to guide them.

If the goal of this contact form is Media as mentioned in the menu item title and title of the page, then Media should be placed at the top of the dropdown list, not at the bottom. 
If the goal is just to avoid receiving messages from users, then ok, let's keep Media at the bottom. 
I'm sorry, but I don't get this logic.

If nobody wants to answer these users, fine, forward me the messages and I'll answer them.

**Comment by Sandra97** [comment]
I've reordered the dropdown list and put the Media Contact first. 
It's a page for Media Requests so Media should be logically first.

**Comment by Sandra97** [comment]
No need to keep this issue opened.
I'm closing it. 
Re-open if needed.
