### ISSUE TITLE
[jrd] Edit profile form is empty

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#978]
Hi! I wanted to edit my resources Profile since i changed my businessname last year. When i click on "edit" there are no input fields. 
Thanks,
Elisa

**Comment by genr8r** [comment]
Hi Elisa,
Are you clicking the pencil icon to edit? If you simply click the listing title it will open the listing and not allow you to edit. Clicking the pencil icon gives you access to the fields.

**Comment by coolcat-creations** [comment]
Hi @genr8r thank you for your fast reaction. Now it worked. I tried to edit it through the link inside the listing: 
![image](https://user-images.githubusercontent.com/828371/27651751-a9562160-5c39-11e7-84f4-50239cab1da0.png)

Maybe this link can be hidden, because it does not work :)

**Comment by genr8r** [comment]
Thanks @coolcat-creations. Apparently, everyone has been happily using the "pencil" method on this as there wasn't a view setup for the submissions edit. I know you closed this already, but I setup a basic view and we will review it more extensively at the JRD team meeting next week. Thanks for letting us know. I am glad you got everything set with you listing.

**Comment by coolcat-creations** [comment]
Thank you @genr8r :-)
