### ISSUE TITLE
Don't have access to the Super Admin account but want to use domain name registered to me

### ISSUE THREAD

**Issue by jeffreygreenemetaldesigns** [joomla/joomla-websites#979]
the domain name is registered to my dad, but he had a friend design the website for him (she used joomla) she gave him basic instructions to upkeep the website by adding pictures but now he's asked me, to do more. I want to update the website to the newest version of joomla and run it myself. This is the only problem I've run into

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
