### ISSUE TITLE
[jvols] Spam

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#98]
Still spam in the Joomlers part. 
Example: http://volunteers.joomla.org/joomlers/admin

**Comment by Radek-Suski** [comment]
It gives me (an ugly) 403 page. So I guess it is resolved

**Comment by Sandra97** [comment]
Still think that lots of profile are spam. 
Example: http://volunteers.joomla.org/joomlers/cheryl-sabarita

**Comment by Radek-Suski** [comment]
Ah. So it is actually an ongoing issue?

**Comment by Sandra97** [comment]
Yes it is

**Comment by Sandra97** [comment]
Should maybe a good thing to have someone to control regularly the new accounts. And maybe, to mark more field as required (like the description) will decrease the numbers of spam.

**Comment by Radek-Suski** [comment]
Yep. Let's see what @sanderpotjer say to that

**Comment by sanderpotjer** [comment]
That profile was actually not a spam account, but someone who changed their name in "remove me". Spam accounts are reduced a lot since the captcha has been activated about 1,5 month ago. 

Furthermore couple changes are coming, like reporting a profile and indeed more fields that needs to be filled in.

**Comment by Sandra97** [comment]
Thanks Sander! 
I close this issue.
Re-open it if needed.

**Comment by Sandra97** [comment]
It seems the Joomlers part is still spammed. 
Example:
![joomlers 2016-01-21 10-00-14](https://cloud.githubusercontent.com/assets/4682328/12482475/25735e2c-c026-11e5-87bc-26a0fcd38960.png)

**Comment by MATsxm** [comment]
@sanderpotjer 
Few others....
duplicates eg. Simon Grange
And few to check:
- user user
- tradcatknight tradcatknight
- rkdcjfwhvo rkdcjfwhvo
- strukt strukt
- LoseYourInkLaserTattooRemoval
- getapk love
- nk shastri
- perfumearoma
And I guess few others....
Thanks

**Comment by Sandra97** [comment]
Does anyone manage this website?
Spammers mentioned in March are still displayed and many new ones.
Just some examples:
- https://volunteers.joomla.org/joomlers/getapk
- https://volunteers.joomla.org/joomlers/faresahmmed
- https://volunteers.joomla.org/joomlers/joe-economy
- https://volunteers.joomla.org/joomlers/loseyourinklasertattooremoval (already mentioned in March)
- https://volunteers.joomla.org/joomlers/user (already mentioned in March)
- https://volunteers.joomla.org/joomlers/tradcatknight  (already mentioned in March)
And so on...

**Comment by Joomv** [comment]
Sander is the only person with access.

**Comment by Sandra97** [comment]
So, it would justify the fact that nothing is done?

**Comment by Joomv** [comment]
You asked who ran it.  

 

Justify? No.  

 

Anyone able to fix it other than him AFAIK? Sadly also no.

**Comment by jeckodevelopment** [comment]
Another: `https://volunteers.joomla.org/joomlers/amec`

**Comment by sanderpotjer** [comment]
As much as possible "fake" / "spammer" users have been removed. Besides that an "Report as Spammer" button is added below a Joomler profile (visible after login) that can be used to report spam profiles. 

<img width="249" alt="screen shot 2016-08-22 at 21 17 56" src="https://cloud.githubusercontent.com/assets/522834/17868273/73c48728-68ae-11e6-8412-98327f19ba93.png">

The registration workflow has been improved too, which should prevent spammers in the first place. For the past days this seems to work well.

**Comment by MATsxm** [comment]
Great improvement! :+1:

**Comment by Sandra97** [comment]
+1

**Comment by jeckodevelopment** [comment]
Wow :D great improvement!
