### ISSUE TITLE
[jcomm] Training Site

### ISSUE THREAD

**Issue by tsmitharts** [joomla/joomla-websites#980]
It seems like the Joomla Training videos are broken. I tried Safari and Chrome. I was using the yesterday. Thanks for any help -Tim
<img width="1123" alt="screen shot 2017-06-29 at 2 40 40 pm" src="https://user-images.githubusercontent.com/29805934/27755482-d0c97730-5da4-11e7-8fb1-a01702f0fdc8.png">
<img width="1084" alt="screen shot 2017-06-29 at 2 49 32 pm" src="https://user-images.githubusercontent.com/29805934/27755483-d0da99c0-5da4-11e7-9a35-5f23e7f60a0b.png">

**Comment by Sandra97** [comment]
Hi Tony,
Thanks for your report.
We have had to take the training section down for maintenance.
Please try back shortly.

**Comment by tsmitharts** [comment]
Thank you for working on it! -Tim

**Comment by Joomv** [comment]
@tsmitharts  This has been fixed by the provider and training is now live again.
