### ISSUE TITLE
Joomla log in

### ISSUE THREAD

**Issue by musiclessonsinyourhouse** [joomla/joomla-websites#981]
Joomla: Experiencing issues with log-in to update website. 
Doesn't recognize my email to reset password.
 Is there an 800-number for support ?

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or repport an issue on: https://issues.joomla.org/

Regards,
Thanks
