### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by 2-49bespoke** [joomla/joomla-websites#982]
I'm receiving intermittent 500 internal server error and couldn't find anyway to fix it.
Have browsed the web for answers and checked all the ones I could find, which mainly focus on htaccess file, to no avail.
I'm using joomla 3.7.2 with PHP 5.6.30

Any help would be appreciated

**Comment by Sandra97** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
or report an issue on: https://issues.joomla.org/

Regards,
Thanks

**Comment by 2-49bespoke** [comment]
Sorry about that, did not know.

Can you please direct me to the right place?

 

Thanks in advance,

Helio

**Comment by Sandra97** [comment]
Best place is to ask for help on the forum: https://forum.joomla.org/
