### ISSUE TITLE
[joomla.com] php version 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#983]
Some of my joomla.com sites are running on php5 and are getting the warning message (some are on php7)

<img width="941" alt="screenshotr09-52-09" src="https://user-images.githubusercontent.com/1296369/27856965-c1c0fada-6167-11e7-92b4-bedb25665a79.png">

**Comment by Sandra97** [comment]
I'll inform SiteGround and will let you know.

**Comment by kirilhristov** [comment]
We are working on rolling out the PHP update to all servers. 

Meanwhile, we have temporarily set the plugin that displays the error to disabled by default.

I will provide an update here when we are all done.

Thanks for reporting.

**Comment by Sandra97** [comment]
Thanks Kiril!

**Comment by dustenharward** [comment]
We have migrated all of our dedicated servers to PHP 7.0 and everything is running great for us. We tried to take a few sites to 7.1 and it caused some issues with plugins not being compatible so I wouldn't advise going that far.

**Comment by brianteeman** [comment]
That's not relevant to joomla.com

**Comment by brianteeman** [comment]
@kirilhristov I just checked and my sites on joomla.com are still displaying the php message. So neither the servers have been updated nor the plugin disabled

**Comment by kirilhristov** [comment]
@brianteeman We are still rolling out the php update on all servers. It's taking longer than expected.

As for the plugin, I am sorry for not being completely clear. By "disabled by default" I meant we disabled it for new activations by default, we did not alter the sites of existing users. However, since we need a bit more time for the update, we will disable the plugin for existing users later today, too.

**Comment by kirilhristov** [comment]
All joomla.com servers are now running PHP 7.1. 

Please review and close the issue (it seems I can't). Thanks for your patience!

**Comment by Sandra97** [comment]
@brianteeman When you can, could you confirm it's ok for you? Thanks!

**Comment by brianteeman** [comment]
all ok
