### ISSUE TITLE
Volunteers contact form is not working

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#984]
A volunteer tried to contact the JED team ... but the contact was never received.

I've just tested the contact form and I didn't receive an email either.

https://volunteers.joomla.org/teams/extensions-directory-team#contact

Please, confirm us if we should be receiving these emails or they are going to somewhere else.

A

**Comment by Sandra97** [comment]
You should edit the team and first check if you have set up the right email address.

**Comment by anibalsanchez** [comment]
Yes, it works in that way.

It should be better to warn that emails are not being sent... or configure a default address for all teams.

A

**Comment by sanderpotjer** [comment]
It should use the team leader email as fall-back, but will double check that.

**Comment by sanderpotjer** [comment]
@anibalsanchez Just checked it, and without the email specifically set the mail went to the team leader indeed. Also for the JED, so to Jaz.

**Comment by anibalsanchez** [comment]
okok, Txs
