### ISSUE TITLE
[jforum] Contact Board Administrator has been disabled

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#985]
As i can't remember my Username  clicked on the Link:
![bildschirmfoto 2017-07-05 um 18 03 50](https://user-images.githubusercontent.com/8235763/27873420-58956c18-61ac-11e7-8f4e-35cf2cfc7997.jpg)
got:
![bildschirmfoto 2017-07-05 um 18 04 27](https://user-images.githubusercontent.com/8235763/27873435-6a3087a0-61ac-11e7-9110-31a3589af389.jpg)

**Comment by mbabker** [comment]
There's an area on https://community.joomla.org that gets used for that (for the life of me I can't remember where), but it'd also be a good UX improvement to change that link to point to CJO.

**Comment by Sandra97** [comment]
That area maybe: https://community.joomla.org/helpdesk/department/general-assistance.html

**Comment by ooffick** [comment]
Would you mind submitting the following form:
https://community.joomla.org/helpdesk/forum-un-ban-request.html

Kind regards 
Olaf

**Comment by pe7er** [comment]
Could you try **franzwohlkoenig** as username?

**Comment by franz-wohlkoenig** [comment]
@pe7er thanks, works. Close this Issue?

**Comment by pe7er** [comment]
@franz-wohlkoenig Ok, good to hear!
I suppose that you can close your own issue with the button below the comment box.

**Comment by franz-wohlkoenig** [comment]
you're right ;-)
