### ISSUE TITLE
[jshow] Can't select tags

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#987]
When submitting a site, I cannot select the tags I would like.
When I click in the box, some tags suddenly appear but I can't delete them.
![index](https://user-images.githubusercontent.com/4682328/27917680-179b51e0-6243-11e7-8a88-8eacb85757df.png)

@sebastienlapoux Could you give a look?

Merci !!!

**Comment by Sandra97** [comment]
Issue is still there, I can't select tags properly. 
@sebastienlapoux Coud you give a look? Thank you!

**Comment by sebastienlapoux** [comment]
Thanks @Sandra97 .
Confirmed, working on it.

**Comment by Sandra97** [comment]
@sebastienlapoux Any update about this issue? It is still not working as expecting for me.

**Comment by sebastienlapoux** [comment]
@Sandra97 , has been fixed at least one month ago. I forgot this issue on github.
Please try again and close if ok.

**Comment by Sandra97** [comment]
Thank you @sebastienlapoux. I confirm it works now as expected.
I'm closing this issue.
Re-open if needed.
