### ISSUE TITLE
[jshow] How to remove a site

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#988]
Hello,

I haven't seen any button in my account in order to delete a website. 
It would be useful to be able to, at least, unpublished an entry when for example a site is rebuild with another CMS...

Thanks

**Comment by sebastienlapoux** [comment]
Hi @Sandra97 ,
Currently you can use the report button to request it.
Yes, can be an enhancement.

Maybe not delete definitively but more to change the state. How to manage the link (404 or other)? Redirection? Or we don't care.

Thanks

**Comment by Sandra97** [comment]
Merci Sébastien !
We care about 404 ;) 
Just use the com_redirect for them.

**Comment by Sandra97** [comment]
@sebastienlapoux, I used the report button but no action has been done. 
Would be nice to find a solution to be able to remove sites which don't exist anymore or don't use Joomla anymore.

**Comment by sebastienlapoux** [comment]
Thanks @Sandra97 .
Your report items has been processed on 2017-10-17.

Are you agree to add the possibility to unpublish an item by the person who submit it?

Thanks.

**Comment by Sandra97** [comment]
Yes, I'm fine with that. 
(It also means of course that when someone is unpublishing a site, 404 will need to be managed.)

**Comment by Sandra97** [comment]
@sebastienlapoux, seems the unpublish button is not available. What's the status of this option?

**Comment by Sandra97** [comment]
@sebastienlapoux Still no unpublish button for a site. Any news about that?

**Comment by sebastienlapoux** [comment]
@Sandra97 thanks! Trying to add during summer. Come back to you.

**Comment by conconnl** [comment]
@sebastienlapoux we are more then 2,5 year in the future, since the first message.
Is those option going to be added, or this something you can't fix?

**Comment by sebastienlapoux** [comment]
It's just not a priority! Closing it.
