### ISSUE TITLE
[jshow] Instagram Icon not displayed - Template update

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-websites#989]
Could you please update the template to its latest version? 
At the same time, it will solve the Instagram icon issue
![index](https://user-images.githubusercontent.com/4682328/27936382-7c0509f6-627e-11e7-9ce4-0d5d0d057d19.png)

**Comment by Sandra97** [comment]
@sebastienlapoux Could you please update the template? 
Thanks!

**Comment by sebastienlapoux** [comment]
@Sandra97 , thanks will be done next week.

**Comment by Sandra97** [comment]
Thanks Sébastien!
When main issues are solved, we will start promoting again the Showcase on Social Media. Several posts are already ready.

**Comment by Joomv** [comment]
@sebastienlapoux  Make sure when you update the template that you replace the helpers/template.php file with the one in the repo or your cache will explode.

**Comment by Sandra97** [comment]
As the template has been updated, I'm closing this issue.
Re-open if needed.
