### ISSUE TITLE
[general] ID graphics to move to CDN

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#99]
Meta issue for all sites...

Identify graphics to move to the CDN for more efficient resource sharing.  At a minimum this should include release graphics and conference banners.  Once moved, content should be updated to point to the CDN source (which does support HTTPS).

**Comment by mbabker** [comment]
Partial list of graphics to move:

- 3.4 release graphic: http://www.joomla.org/images/joomla34graphic.png
- 3.3 release graphic: http://www.joomla.org/images/do-more-33.png
- 2.5 release graphic: http://www.joomla.org/images/stories/landing/25/version-25.png
- Security release graphic: http://www.joomla.org/images/stories/security_release.png

**Comment by jessicadunbar** [comment]
https://www.joomla.org/images/stories/announcements/security.png is the new one i've been using
