### ISSUE TITLE
Sado

### ISSUE THREAD

**Issue by Sardarbek1** [joomla/joomla-websites#990]
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

**Comment by franz-wohlkoenig** [comment]
there is no Content given. Please add Content about one of the Websites of Joomla-Communtiy.

**Comment by Sandra97** [comment]
Closing this issue.
Re-open if needed.
