### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by lumptolaughter** [joomla/joomla-websites#991]
I am using 2.5 I believe of Joomla.  I turned on Force SSL and my site is completely gone.  I make changes in Joomla but host it with GoDaddy.  I can now not log in at all to change that back and I need assistance.  I need a backup of my site before the changes were made too.  the site is www.lumptolaughter.org    GoDaddy does not have a backup and cannot access the site.  My number is 910-617-4455 and I really need assistance please.

**Comment by zero-24** [comment]
Please use the forum you can find here: https://forum.joomla.org This repo is about the joomla org sites ;)
