### ISSUE TITLE
Contact Us Page v3.7.3

### ISSUE THREAD

**Issue by clivepinchbeck** [joomla/joomla-websites#992]
After updating to Joomla 3.7.3 our 'contact us' page has lost the address and post cost code information.
Can anyone advise how to resolve please - I have compared and checked all settings.

After Update
https://www.baby-bouquets.co.uk/contact

Before Update
https://www.dev.baby-bouquets.co.uk/contact-us

**Comment by Sandra97** [comment]
Hello, 

It's a known issue with 3.7.3 : https://github.com/joomla/joomla-cms/issues/16968
Here is the PR: https://github.com/joomla/joomla-cms/pull/16971
Or you can just wait for 3.7.4 for the fix.

**Comment by clivepinchbeck** [comment]
Hi Sandra, thanks I will wait rather than edit any code, I am pleased to hear it is a known issue and will be fixed in next release though.
