### ISSUE TITLE
[jforum] 

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#993]
https://forum.joomla.org/ this page has a title of Joomla - index page.  I think someone should speak to the SEO team about renaming this page and seeing if there are any other tweaks that could help.

**Comment by Sandra97** [comment]
@ooffick Could you give a look? 
Thanks!

**Comment by ooffick** [comment]
Hi,

I have looked at this, and added temporarily a better title, what title/description would you or the SEO team suggest?

Kind Regards
Olaf

**Comment by uglyeoin** [comment]
What you have used looks fine to me but I defer to the SEO team who may decide to change it.  I personally would remove "index page" if at all possible as it dilutes the message and is irrelevant.  In fact it's likely to be on many PHP BB or whatever forum software we're using.

**Comment by Joomv** [comment]
I would kill the second Joomla!

So - Joomla! Forum - community, help and support

Chris is still working with the JED, the forum is on our list for help, but until the JED is done, we don't have the capacity.

**Comment by ooffick** [comment]
Thanks, I have changed this as requested.

**Comment by Sandra97** [comment]
As changes have been applied, I'm closing it.
Re-open if needed.
