### ISSUE TITLE
[Joomla.com] PHP and languages outdated

### ISSUE THREAD

**Issue by webdjam** [joomla/joomla-websites#994]
Hello @Sandra97 
I would  like to report two issue on Joomla.com, the first one is the php version who is out of date, the php version running on joomla.com is 5.5.22, this version is not more supported and can cause some security issue, please can you ask Siteground to update the php version at least to the version 5.6, the same happen with the languages pack who don’t match the current version of joomla! 3.7.3.

Best,
Djamel Kherbi

**Comment by Sandra97** [comment]
Hi Djamel, 

Regardin the PHP version, it has already been reported and they are working on it. See #983 

I'll inform SiteGround  for the language packs.

**Comment by webdjam** [comment]
Hi Sandra,
Thank you for reporting the issue on the language packs.

**Comment by Sandra97** [comment]
As joomla.com is now managed by CloudAcces, I'm closing this issue
