### ISSUE TITLE
JED down

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#995]
http://downforeveryoneorjustme.com/extensions.joomla.org

It's not just you! extensions.joomla.org looks down from here.

**Comment by zero-24** [comment]
Looks like it is up again?
![image](https://user-images.githubusercontent.com/2596554/28169462-abb77f30-67e2-11e7-9241-7389efd2b75b.png)

**Comment by Sandra97** [comment]
Yes it's back online
