### ISSUE TITLE
[jforum] Problem with forum.jooma.org

### ISSUE THREAD

**Issue by AMurray2016** [joomla/joomla-websites#997]
I don't know if this is the correct place to report this but I cannot get into https://forum,joomla.org  it is giving me "time out" errors.  All other Joomla.org sites work and my internet connection generally is working fine.  The forum site's been down for a couple of days.

> The connection has timed out
> 
> The server at forum.joomla.org is taking too long to respond.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
>

**Comment by AMurray2016** [comment]
This is occurring in multiple browsers ex: firefox, Chrome etc.  I thought it might be my firewall at first blocking the site, but can't identify any issues there, and the forum site/domain is in my "trusted sites" list in the Windows Control Panel internet options settings.

**Comment by Sandra97** [comment]
Hello,
For forum.joomla.org, maybe better to fill the form: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by AMurray2016** [comment]
Have submitted the help ticket. 
Thanks
