### ISSUE TITLE
[jforum] uptimereport IP got blocked by the forum on 15.07.2017

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#999]
It looks like the uptimereport IP got blocked by the forum on 15.07.2017: https://stats.uptimerobot.com/oVJJqSrX7/778232605

![image](https://user-images.githubusercontent.com/2596554/28356693-41a0041a-6c69-11e7-854d-7787bb618f92.png)

Here the current IP's from uptimereport can be found: https://uptimerobot.com/locations.php

As the page is reported to be down but it is not ;)

**Comment by zero-24** [comment]
Just also reported it to: https://community.joomla.org/helpdesk/forum-un-ban-request.html

**Comment by bindi266** [comment]
how does it look like? 
uptimereport IP got blocked
[xmovies8 2017](https:xmovies8.biz)

**Comment by Sandra97** [comment]
@ooffick Anything you can do? Thanks!

**Comment by ooffick** [comment]
Thanks, I have requested to get those ips added to the whitelist.

**Comment by ooffick** [comment]
Those ip address /ip ranges are whitelisted now.

**Comment by zero-24** [comment]
Thanks.
